### ISSUE TITLE
Message format for MySQL

### ISSUE THREAD

**Issue by kirill-linnik** [zendesk/maxwell#1006]
Hi Guys,

Thank you for the tool, idea is awesome! Unfortunately, I don’t see the result described.

I run it like this:
`kubectl run -n dev -it --image=zendesk/maxwell maxwell -- bin/maxwell --user=maxwell --password=test --host=mysqldb --producer=stdout`

And on this SQL:
```
create table test (id integer, primary key (id));
insert into test (id) values (1);
update test set id = 2 where id = 1;
drop table test;
```

I get:
```
12:44:27,829 INFO  AbstractSchemaStore - storing schema @Position[BinlogPosition[mysql-bin.000018:627677], lastHeartbeat=1528461861764] after applying "create table test (id integer, primary key (id))" to TestSchema, new schema id is 4
12:44:31,523 WARN  BinlogConnectorReplicator - Unhandled QueryEvent inside transaction: QueryEventData{threadId=5, executionTime=0, errorCode=0, database='TestSchema', sql='insert into test (id) values (1)'}
12:44:33,453 WARN  BinlogConnectorReplicator - Unhandled QueryEvent inside transaction: QueryEventData{threadId=5, executionTime=0, errorCode=0, database='TestSchema', sql='update test set id = 2 where id = 1'}
12:44:35,591 INFO  AbstractSchemaStore - storing schema @Position[BinlogPosition[mysql-bin.000018:629919], lastHeartbeat=1528461872789] after applying "DROP TABLE `test` /* generated by server */" to TestSchema, new schema id is 5
```

How could I get it in a nice changeset way as described in README (I mean:
```
 mysql> update test.maxwell set daemon = 'firebus!  firebus!' where id = 1;
  maxwell: {
    "database": "test",
    "table": "maxwell",
    "type": "update",
    "ts": 1449786341,
    "xid": 940786,
    "commit": true,
    "data": {"id":1, "daemon": "Firebus!  Firebus!"},
    "old":  {"daemon": "Stanislaw Lem"}
  }
```

**Comment by osheroff** [comment]
you need to set `binlog_format=ROW` on your mysql server.

**Comment by kirill-linnik** [comment]
I did. Otherwise it doesn't work at all.

Sent from my not so smart phone.
-------- Original message --------From: Ben Osheroff <notifications@github.com> Date: 08/06/2018  18:13  (GMT+02:00) To: zendesk/maxwell <maxwell@noreply.github.com> Cc: kirill-linnik <kirill.linnik@mail.ee>, Author <author@noreply.github.com> Subject: Re: [zendesk/maxwell] Message format for MySQL (#1006) 
you need to set binlog_format=ROW on your mysql server.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or mute the thread.
{"@context":"http://schema.org","@type":"EmailMessage","potentialAction":{"@type":"ViewAction","target":"https://github.com/zendesk/maxwell/issues/1006#issuecomment-395792359","url":"https://github.com/zendesk/maxwell/issues/1006#issuecomment-395792359","name":"View Issue"},"description":"View this Issue on GitHub","publisher":{"@type":"Organization","name":"GitHub","url":"https://github.com"}}
{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/zendesk/maxwell","title":"zendesk/maxwell","subtitle":"GitHub repository","main_image_url":"https://assets-cdn.github.com/images/email/message_cards/header.png","avatar_image_url":"https://assets-cdn.github.com/images/email/message_cards/avatar.png","action":{"name":"Open in GitHub","url":"https://github.com/zendesk/maxwell"}},"updates":{"snippets":[{"icon":"PERSON","message":"@osheroff in #1006: you need to set `binlog_format=ROW` on your mysql server."}],"action":{"name":"View Issue","url":"https://github.com/zendesk/maxwell/issues/1006#issuecomment-395792359"}}}
{
"@type": "MessageCard",
"@context": "http://schema.org/extensions",
"hideOriginalBody": "false",
"originator": "AF6C5A86-E920-430C-9C59-A73278B5EFEB",
"title": "Re: [zendesk/maxwell] Message format for MySQL (#1006)",
"sections": [
{
"text": "",
"activityTitle": "**Ben Osheroff**",
"activityImage": "https://assets-cdn.github.com/images/email/message_cards/avatar.png",
"activitySubtitle": "@osheroff",
"facts": [

]
}
],
"potentialAction": [
{
"name": "Add a comment",
"@type": "ActionCard",
"inputs": [
{
"isMultiLine": true,
"@type": "TextInput",
"id": "IssueComment",
"isRequired": false
}
],
"actions": [
{
"name": "Comment",
"@type": "HttpPOST",
"target": "https://api.github.com",
"body": "{\n\"commandName\": \"IssueComment\",\n\"repositoryFullName\": \"zendesk/maxwell\",\n\"issueId\": 1006,\n\"IssueComment\": \"{{IssueComment.value}}\"\n}"
}
]
},
{
"targets": [
{
"os": "default",
"uri": "https://github.com/zendesk/maxwell/issues/1006#issuecomment-395792359"
}
],
"@type": "OpenUri",
"name": "View on GitHub"
},
{
"name": "Unsubscribe",
"@type": "HttpPOST",
"target": "https://api.github.com",
"body": "{\n\"commandName\": \"MuteNotification\",\n\"threadId\": 343956571\n}"
}
],
"themeColor": "26292E"
}

**Comment by osheroff** [comment]
see this?

```
12:44:31,523 WARN  BinlogConnectorReplicator - Unhandled QueryEvent inside transaction: QueryEventData{threadId=5, executionTime=0, errorCode=0, database='TestSchema', sql='insert into test (id) values (1)'}
```

it means it's still replicating in statement-based.  Most likely solution is you have to disconnect and reconnect to the mysql server after setting binlog_format=ROW.

**Comment by kirill-linnik** [comment]
That is strange as without setting logs to ROW it doesn't work for me at all. So I set, start maxwell - and this strange thing happens... any other ideas?


Sent from my not so smart phone.
-------- Original message --------From: Ben Osheroff <notifications@github.com> Date: 08/06/2018  18:49  (GMT+02:00) To: zendesk/maxwell <maxwell@noreply.github.com> Cc: kirill-linnik <kirill.linnik@mail.ee>, Author <author@noreply.github.com> Subject: Re: [zendesk/maxwell] Message format for MySQL (#1006) 
see this?
12:44:31,523 WARN  BinlogConnectorReplicator - Unhandled QueryEvent inside transaction: QueryEventData{threadId=5, executionTime=0, errorCode=0, database='TestSchema', sql='insert into test (id) values (1)'}

it means it's still replicating in statement-based.  Most likely solution is you have to disconnect and reconnect to the mysql server after setting binlog_format=ROW.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or mute the thread.
{"@context":"http://schema.org","@type":"EmailMessage","potentialAction":{"@type":"ViewAction","target":"https://github.com/zendesk/maxwell/issues/1006#issuecomment-395803599","url":"https://github.com/zendesk/maxwell/issues/1006#issuecomment-395803599","name":"View Issue"},"description":"View this Issue on GitHub","publisher":{"@type":"Organization","name":"GitHub","url":"https://github.com"}}
{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/zendesk/maxwell","title":"zendesk/maxwell","subtitle":"GitHub repository","main_image_url":"https://assets-cdn.github.com/images/email/message_cards/header.png","avatar_image_url":"https://assets-cdn.github.com/images/email/message_cards/avatar.png","action":{"name":"Open in GitHub","url":"https://github.com/zendesk/maxwell"}},"updates":{"snippets":[{"icon":"PERSON","message":"@osheroff in #1006: see this?\r\n\r\n```\r\n12:44:31,523 WARN  BinlogConnectorReplicator - Unhandled QueryEvent inside transaction: QueryEventData{threadId=5, executionTime=0, errorCode=0, database='TestSchema', sql='insert into test (id) values (1)'}\r\n```\r\n\r\nit means it's still replicating in statement-based.  Most likely solution is you have to disconnect and reconnect to the mysql server after setting binlog_format=ROW."}],"action":{"name":"View Issue","url":"https://github.com/zendesk/maxwell/issues/1006#issuecomment-395803599"}}}
{
"@type": "MessageCard",
"@context": "http://schema.org/extensions",
"hideOriginalBody": "false",
"originator": "AF6C5A86-E920-430C-9C59-A73278B5EFEB",
"title": "Re: [zendesk/maxwell] Message format for MySQL (#1006)",
"sections": [
{
"text": "",
"activityTitle": "**Ben Osheroff**",
"activityImage": "https://assets-cdn.github.com/images/email/message_cards/avatar.png",
"activitySubtitle": "@osheroff",
"facts": [

]
}
],
"potentialAction": [
{
"name": "Add a comment",
"@type": "ActionCard",
"inputs": [
{
"isMultiLine": true,
"@type": "TextInput",
"id": "IssueComment",
"isRequired": false
}
],
"actions": [
{
"name": "Comment",
"@type": "HttpPOST",
"target": "https://api.github.com",
"body": "{\n\"commandName\": \"IssueComment\",\n\"repositoryFullName\": \"zendesk/maxwell\",\n\"issueId\": 1006,\n\"IssueComment\": \"{{IssueComment.value}}\"\n}"
}
]
},
{
"targets": [
{
"os": "default",
"uri": "https://github.com/zendesk/maxwell/issues/1006#issuecomment-395803599"
}
],
"@type": "OpenUri",
"name": "View on GitHub"
},
{
"name": "Unsubscribe",
"@type": "HttpPOST",
"target": "https://api.github.com",
"body": "{\n\"commandName\": \"MuteNotification\",\n\"threadId\": 343956571\n}"
}
],
"themeColor": "26292E"
}

**Comment by osheroff** [comment]
this is documented here:

http://maxwells-daemon.io/quickstart/#configure-mysql

> note: binlog_format is a session-based property. You will need to shutdown all active connections to fully convert to row-based replication.

to clarify, you have to do:

`SET GLOBAL BINLOG_FORMAT='ROW'`

now *disconnect* and *reconnect* to the mysql server, then you can do:

```
INSERT INTO foo ...
```

and it will all work.

**Comment by kirill-linnik** [comment]
cool! it works! I haven't closed all connections before...


 

 

----- Reply to message -----
Subject: Re: [zendesk/maxwell] Message format for MySQL (#1006)
Date: 8 June 2018 at 20:43:28
