### ISSUE TITLE
Any estimate when to use kafka client libraries 1.0+?

### ISSUE THREAD

**Issue by jsalmeron** [zendesk/maxwell#1007]
Hello, wondering if there is a short term plan to use the newer kafka client libraries.

For the moment, our maxwell producers are not impacting broker cpu for message downconversion, but I am interested in knowing if we 0.11 libraries will be upgraded.

Thanks!

**Comment by osheroff** [comment]
there's a PR open to do that, but it got caught up in some additional changes I didn't like.  I'll re-start work on it.

**Comment by jsalmeron** [comment]
Great, thanks!

**Comment by osheroff** [comment]
available in v1.16.1
