### ISSUE TITLE
Modular Maxwell

### ISSUE THREAD

**Issue by gessnerfl** [zendesk/maxwell#1009]
Similar to issue #634 I would like to integrate Maxwell into my application. However as size matters for me I do not want to get all the dependencies into my application. Furthermore the application is already using dropwizzard metrics and uses an own web server so that I would like to reuse the existing setup with maxwell.
Basically I see the potential to modularize maxwell so that on the one hand side producers can be provided through specific modules as well as metric reporters. With this maxwell would be reduced to a base set which can be extended easily with additional producers and/or metric reporter depending on the specific needs.
I

**Comment by osheroff** [comment]
I can see the value in this, and I'd be happy to accept PRs towards this end, as long as it doesn't change anything for the tarball builds and doesn't get in the way of the development process.

As a simple solution you might just override the scope of maxwell's dependencies on the libs you don't need, I'm not 100% on how that'll work with class loading but it might do.

**Comment by gessnerfl** [comment]
After vacationing and some busy business weeks I finally tried to simplify the project structure to get rid of the api projects. But it turned out that this refactoring would require eve more code changes. As it is already hard right now to keep up with the changes in master branch I decided to stop this for now.

I think it is really hard to do such a major refactoring as a side-project. If you plan to change into such a direction and if you are looking for some volunteers then please let me know.
