### ISSUE TITLE
TRUNCATE not supported

### ISSUE THREAD

**Issue by kirill-linnik** [zendesk/maxwell#1012]
Hi all,

Product looks awesome! Found one minor thing (or maybe a major for some). Use these lines:
`CREATE TABLE test (id integer, val varchar(255), primary key(id));`
`INSERT INTO test (id, val) VALUES (1, 'a');`
`INSERT INTO test (id, val) VALUES (2, 'a');`
`UPDATE test SET val = 'b' WHERE id = 2;`
`DELETE FROM test WHERE id = 1;`
`TRUNCATE TABLE test;`
`DROP TABLE test;`

In console:
`07:14:32,621 INFO  AbstractSchemaStore - storing schema @Position[BinlogPosition[mysql-bin.000014:601597], lastHeartbeat=1528787668418] after applying "CREATE TABLE test (id integer, val varchar(255), primary key(id))" to <...>, new schema id is 2`
`{"database":"<...>","table":"test","type":"insert","ts":1528787672,"xid":1604,"commit":true,"data":{"id":1,"val":"a"}}`
`{"database":"<...>","table":"test","type":"insert","ts":1528787672,"xid":1605,"commit":true,"data":{"id":2,"val":"a"}}`
`{"database":"<...>","table":"test","type":"update","ts":1528787672,"xid":1606,"commit":true,"data":{"id":2,"val":"b"},"old":{"val":"a"}}`
`{"database":"<...>","table":"test","type":"delete","ts":1528787672,"xid":1607,"commit":true,"data":{"id":1,"val":"a"}}`
`07:14:32,664 INFO  AbstractSchemaStore - storing schema @Position[BinlogPosition[mysql-bin.000014:602714], lastHeartbeat=1528787668418] after applying "DROP TABLE `test` /* generated by server */" to <...>, new schema id is 3`

As you see, nothing is logged/handled for `TRUNCATE`. Any ideas why?

**Comment by osheroff** [comment]
yeah, `TRUNCATE` is just ignored.  TRUNCATE is replicated as SQL, not rows, so maxwell is unable to output data for it.

**Comment by kirill-linnik** [comment]
OK, I have managed to debug with the row mysql binlog client. In order to be consistent, I have created procedure with `TRUNCATE` first:
`delimiter //`
`CREATE PROCEDURE test_proc()`
`BEGIN`
`  TRUNCATE TABLE test;`
`END//`
`delimiter ;`

Then I did the following:
`START TRANSACTION;`
`	CALL test_proc();`
`	INSERT INTO test (id, val) VALUES (2, 'a');`
`	INSERT INTO test (id, val) VALUES (3, 'c');`
`COMMIT;`

And events are sent to `stdout`:
 
`Event{header=EventHeaderV4{timestamp=1528872868000, eventType=QUERY, serverId=1, headerLength=19, dataLength=76, nextPosition=1653422, flags=0}, data=QueryEventData{threadId=3, executionTime=0, errorCode=0, database='<...>', sql='TRUNCATE TABLE test'}}`
`Event{header=EventHeaderV4{timestamp=1528872868000, eventType=QUERY, serverId=1, headerLength=19, dataLength=62, nextPosition=1653503, flags=8}, data=QueryEventData{threadId=3, executionTime=0, errorCode=0, database='<...>', sql='BEGIN'}}`
`Event{header=EventHeaderV4{timestamp=1528872868000, eventType=TABLE_MAP, serverId=1, headerLength=19, dataLength=40, nextPosition=1653562, flags=0}, data=TableMapEventData{tableId=1266, database='<...>', table='test', columnTypes=3, 15, columnMetadata=0, 765, columnNullability={1}}}`
`Event{header=EventHeaderV4{timestamp=1528872868000, eventType=EXT_WRITE_ROWS, serverId=1, headerLength=19, dataLength=24, nextPosition=1653605, flags=0}, data=WriteRowsEventData{tableId=1266, includedColumns={0, 1}, rows=[
    [2, [B@aec6354]
]}}`
`Event{header=EventHeaderV4{timestamp=1528872868000, eventType=XID, serverId=1, headerLength=19, dataLength=12, nextPosition=1653636, flags=0}, data=XidEventData{xid=20782}}
Event{header=EventHeaderV4{timestamp=1528872868000, eventType=QUERY, serverId=1, headerLength=19, dataLength=62, nextPosition=1653717, flags=8}, data=QueryEventData{threadId=3, executionTime=0, errorCode=0, database='<...>', sql='BEGIN'}}`
`Event{header=EventHeaderV4{timestamp=1528872868000, eventType=TABLE_MAP, serverId=1, headerLength=19, dataLength=40, nextPosition=1653776, flags=0}, data=TableMapEventData{tableId=1266, database='<...>', table='test', columnTypes=3, 15, columnMetadata=0, 765, columnNullability={1}}}`
`Event{header=EventHeaderV4{timestamp=1528872868000, eventType=EXT_WRITE_ROWS, serverId=1, headerLength=19, dataLength=24, nextPosition=1653819, flags=0}, data=WriteRowsEventData{tableId=1266, includedColumns={0, 1}, rows=[
    [3, [B@1c655221]
]}}`
`Event{header=EventHeaderV4{timestamp=1528872868000, eventType=XID, serverId=1, headerLength=19, dataLength=12, nextPosition=1653850, flags=0}, data=XidEventData{xid=20783}}`

As you see, even within procedure, `TRUNCATE` is nicely logged and captured. Can you please add that to your cool product?

**Comment by kirill-linnik** [comment]
Ben, so what about fixing that as I described?
