### ISSUE TITLE
SQS FIFO is not supported

### ISSUE THREAD

**Issue by kirill-linnik** [zendesk/maxwell#1013]
If you try to use AWS SQS FIFO queue (well, not FIFO doesn't make sense for DB Sync, right?), then you get an exception:

`10:14:55,292 ERROR SQSCallback - Exception during put
com.amazonaws.services.sqs.model.AmazonSQSException: The request must contain the parameter MessageGroupId. (Service: AmazonSQS; Status Code: 400; Error Code: MissingParameter; Request ID: ...`

**Comment by metersk** [comment]
Hey is there any update on this? We'd love to use SQS FIFO queues with maxwell.

**Comment by amondnet** [comment]
@metersk PR - https://github.com/zendesk/maxwell/pull/1301
