### ISSUE TITLE
Issue in Bootstrap process

### ISSUE THREAD

**Issue by nfityo** [zendesk/maxwell#1014]
We are using Maxwell to replicate data from BinaryLog and it works good.
But if we started bootstrapping data from one table and during this process we updated/inserted data in this table then bootstrap started again from the beginning. And as our table is quite big with a lot of insert/update so we have continuous bootstrap starting without ending.
Tested on 1.14.2 and 1.14.4
Any idea or suggestion how to fix this?

**Comment by osheroff** [comment]
Hmm, can you attach some sample output?  Did maxwell output two “bootstrap-start” rows?
