### ISSUE TITLE
Datadog Metrics:  I/O exception (java.net.SocketException) caught when processing request to {s}->https://app.datadoghq.com:443: Socket is closed

### ISSUE THREAD

**Issue by adamgeorgeson** [zendesk/maxwell#1016]
I realise this may be more for coursera/metrics-datadog, but thought I'd ask here first incase anyone else has seen this issue.

We have a maxwell worker instance with the following config:

        MAXWELL_METRICS_TYPE: "http,datadog"
        MAXWELL_METRICS_DATADOG_TYPE: "http"

We're deployed in AWS ECS, and we've experienced the following error. This causes the instance to stall, and not process any messages.

```
09:22:31,184 INFO RetryExec - I/O exception (java.net.SocketException) caught when processing request to {s}->https://app.datadoghq.com:443: Socket is closed

09:22:31,184 INFO RetryExec - Retrying request to {s}->https://app.datadoghq.com:443
```

Is this something anyone has experienced before?

Thanks in advance!
Adam.

**Comment by liulikun** [comment]
Any reason you need to use `http` for datadog? I think `udp` is preferred protocol.

**Comment by adamgeorgeson** [comment]
No actual need to use http. Just used as a first run, but using `udp` makes sense (especially as it's default!). I'll switch it over. 

Cheers!
