### ISSUE TITLE
JSON Data Type Parser Throwing Exception

### ISSUE THREAD

**Issue by yosefrat** [zendesk/maxwell#1017]
The Maxwell Kafka Producer is breaking upon read of what appears to be larger size JSON data types from MySQL. It is throwing the following error:

`java.lang.ClassCastException: java.lang.String cannot be cast to [B at com.zendesk.maxwell.schema.columndef.JsonColumnDef.asJSON(JsonColumnDef.java:18) at com.zendesk.maxwell.bootstrap.SynchronousBootstrapper.setRowValues(SynchronousBootstrapper.java:241) at com.zendesk.maxwell.bootstrap.SynchronousBootstrapper.startBootstrap(SynchronousBootstrapper.java:66) at com.zendesk.maxwell.bootstrap.AsynchronousBootstrapper$1.run(AsynchronousBootstrapper.java:74) at java.lang.Thread.run(Thread.java:748)`

This seems to occur exclusively on json data type columns from MySQL, but I haven't been able to see any obvious gremlin characters in the JSON. Is it possible this is due to encoding issues? Looks like the JSON encoder is also reliant upon this: https://github.com/shyiko/mysql-binlog-connector-java/blob/master/src/main/java/com/github/shyiko/mysql/binlog/event/deserialization/json/JsonBinary.java#L181 could it be an issue with the binlog deserialization? I can't paste the exact JSON object, but the only characters that look even remotely suspect would just be ()[]/=: none of which are very extraordinary for JSON objects. Is there any limitation on the size of the JSON object?

**Comment by osheroff** [comment]
I think this is just an issue with JSON values + the bootstrapper, looking.
