### ISSUE TITLE
Suppressing delete statements from Maxwell

### ISSUE THREAD

**Issue by rredhatt** [zendesk/maxwell#1020]
Is there a way in Maxwell to completely suppress a delete statement from being processed by Maxwell?

**Comment by rredhatt** [comment]
Thanks for your prompt reply on this !! .... looking forward to the javascript feature !!!

**Comment by osheroff** [comment]
v1.17.0 released with javascript filters.  LMK how it works out for you.

**Comment by rredhatt** [comment]
Many thanks, will surely try it out in the coming days
