### ISSUE TITLE
Maxwell fails to start after a table drop 

### ISSUE THREAD

**Issue by tomlis** [zendesk/maxwell#1025]
Hello,
  then I dropped a tabel in my database,  the maxwell client fails to start with error:
09:06:48,404 ERROR AbstractSchemaStore - Error on bin log position Position[BinlogPosition[mysql-bin.000002:2284182], lastHeartbeat=0]
com.zendesk.maxwell.schema.ddl.InvalidSchemaError: Couldn't find table 'my_dropped_table' in database my_database
Is there a way for automatic update maxwel's database with schema structure ? 
How to deal with such errors ? I wouldn like to truncate table 'table'@maxwell everytime. 

Thanks in advance.

**Comment by liulikun** [comment]
Do you know what caused the error? Maxwell should be able to capture all the schema changes and apply those changes accordingly. But if you manually changed some tables managed by maxwell, you may have this error. This PR may help: https://github.com/zendesk/maxwell/pull/1022, it only works if there are no migrations between now and the binlog position where maxwell has stopped replication previously.

**Comment by tomlis** [comment]
Thanks for quick reply. 
I did not changed the maxwell's database. 
I did not found what caused the problem yet, however thoose records might give us some clues: 

The server contains:

- -rw-r----- 1 mysql mysql  524288049 Jun 18 16:22 mysql-bin.000573
- -rw-r----- 1 mysql mysql  524292738 Jun 18 16:40 mysql-bin.000574
- -rw-r----- 1 mysql mysql  524288278 Jun 18 17:21 mysql-bin.000575

So the oldest binlog file is "mysql-bin.000573" 

The only one record in table 'positions'@maxwellDB:

- '3333', 'mysql-bin.000002', '323724', NULL, 'maxwell', NULL, '0'

It points to non existing 'mysql-bin.000002'

However "SELECT * FROM maxwell.`schemas`;" returns:
`id, binlog_file, binlog_position, last_heartbeat_read, gtid_set, base_schema_id, deltas, server_id, position_sha, charset, version, deleted`

- '2', 'mysql-bin.000002', '323724', '0', NULL, NULL, NULL, '3333', '..', 'latin1', '4', '0'
- '4', 'mysql-bin.000002', '2284182', '0', NULL, '2', '[{\"type\":\"table-drop\",\"database\":\"my_DB\",\"table\":\"my_droppped_table\"}]', '3333', '...', 'latin1', '4', '0'
- '6', 'mysql-bin.000002', '2284415', '0', NULL, '4', '[{\"type\":\"table-drop\",\"database\":\"my_DB\",\"table\":\"my_other_droppped_table\"}]', '3333', '...', 'latin1', '4', '0'
- ... 
- ...
- last:
- '28', 'mysql-bin.000002', '0', '0', NULL, NULL, NULL, '3333', '...', 'latin1', '4', '0'


It looks that maxwell has recorded the fact "my_droppped_table" has been dropped, but for some reason it stopped at position 323724 at the 'mysql-bin.000002' file. 
Why is that ? Is the maxwell, after restart, trying to follow all the deltas found in 'schemas' table ? 

I am also wondering what means the last record in 'schemas' where binlog_position=0 and base_schema_id=null and deltas=null ?

**Comment by liulikun** [comment]
From those records, it seems it was working before at least for `mysql-bin.000002`, then maxwell was stopped (not sure manually or crashed), when you tried to start it again, the old binlog files are not available anymore. 

Regarding your question: Maxwell records all the db migrations as `deltas` and apply all the deltas up to the binlog position when it starts to replicate. 
The last record with base_schema_id=null and deltas=null is the record for rebase line the schemas from `information_schema` mysql db. But I'm confused with  `binlog_position=0`. It should be >0. 

It seems you have multiple maxwell instances running with different client ids?
