### ISSUE TITLE
HTTP metrics endpoint replication.lag

### ISSUE THREAD

**Issue by pollosp** [zendesk/maxwell#1029]
Hi I'm using Maxwell daemon version 1.16.0 and I'm getting negative values for `replication.lag` monitoring gauge is this possible or is it a bug?  For the explanation in the doc `the time elapsed between the database transaction commit and the time it was processed by Maxwell, in milliseconds` doesn't seem to be possible to have negative values.

Thanks :)

**Comment by osheroff** [comment]
It could if the clocks on your mysql server and the place you're running maxwell were off from each other.  suggest you check your `ntp` setup.

**Comment by pollosp** [comment]
They were in AWS and they were spinned for a test, could be but sounds weird, I will perform the test again. But this means that it can be negative right? 

Thanks for your answer :)

**Comment by osheroff** [comment]
yes, if one clock is ahead of another (which is very, very common) there could be negative values.  I wouldn't expect to see more than a small negative number under normal circumstances.

**Comment by osheroff** [comment]
I'm gonna close this issue for now, feel free to re-open if you feel like there's something seriously amiss.
