### ISSUE TITLE
消息能否保证顺序性

### ISSUE THREAD

**Issue by zhijilangzhong** [zendesk/maxwell#1039]
maxwell通过binlog把对db的改动通过kafka发送出去，如果kafka是有个partition，那么这个执行的binlog是如何保证顺序性的呢？会不会出现实际是123顺序的操作，通过kafka变成了231呢？

Maxwell sends the changes through the Kafka . if Kafka has a partition, how does the binlog of this execution be guaranteed to be sequentially? Will there be a real 123 order operation, which is changed to 231 by Kafka?

**Comment by liulikun** [comment]
Kafka maintains the same order from the producer when there are no errors. The ordering can be an issue for retries due to sending failures. You can set `max.in.flight.requests.per.connection=1` for kafka to guarantee the ordering in this case.

**Comment by dbapower** [comment]
Kafka only provides a total order over records within a partition, not between different partitions in a topic. Is the max.in.flight.requests.per.connection=1 or retries=0 for kafka can guarantee the ordering between different partitions in a topic?

> Kafka maintains the same order from the producer when there are no errors. The ordering can be an issue for retries due to sending failures. You can set `max.in.flight.requests.per.connection=1` for kafka to guarantee the ordering in this case.

**Comment by osheroff** [comment]
@dbapower, there's no such thing as "ordering between different partitions"  -- different partitions are entirely different entities.

**Comment by laihaibing** [comment]
我发现在同一个事务里，maxwell推给队列的消息，顺序也是没法保证顺序的。

**Comment by laihaibing** [comment]
我发现maxwell 在使用Rabbitmq MQ作为生产者时，在同一个队列里设置最大并发数为1 ，也是没有顺序消费，感觉是maxwell在推送消息的时候也不是有序的。
