### ISSUE TITLE
Questions about bootstrap per client ID

### ISSUE THREAD

**Issue by leonjoyce** [zendesk/maxwell#1041]
I reviewed the latest code, but have some questions:
**com.zendesk.maxwell.bootstrap.SynchronousBootstrapper.resume(AbstractProducer, Replicator)**

@osheroff
Should we add client ID to the function above? So that we only resume bootstrap of the specified maxwell client?

If not, I am afraid that the following code will throw NULL pointer exception.
public boolean isBootstrapRow(RowMap row) {
return row.getDatabase().equals(this.context.getConfig().databaseName) &&
row.getTable().equals("bootstrap") &&
**row.getData("client_id")**.equals(this.context.getConfig().clientID);
}

**Comment by osheroff** [comment]
@leonjoyce sure, nice catch.  Otherwise if one maxwell client was bounced it'd clobber the in-progress bootstrap from another.  can you go ahead and make that PR?

**Comment by osheroff** [comment]
fixed now
