### ISSUE TITLE
Cannot find position after failover

### ISSUE THREAD

**Issue by beebird** [zendesk/maxwell#1043]
I got the following error when I triggered a failover on MySQL. Looks like the position is not available on the slave. Is there any solution?
```log
com.github.shyiko.mysql.binlog.network.ServerException: bogus data in log event; the first event 'mysql-bin.000042' at 673587, the last event read from '/home/mysql/data0001/mysql/mysql-bin.000042' at 673587, the last byte read from '/home/mysql/data0001/mysql/mysql-bin.000042' at 673606.
        at com.github.shyiko.mysql.binlog.BinaryLogClient.listenForEventPackets(BinaryLogClient.java:882) [mysql-binlog-connector-java-0.16.1.jar:0.16.1]
        at com.github.shyiko.mysql.binlog.BinaryLogClient.connect(BinaryLogClient.java:559) [mysql-binlog-connector-java-0.16.1.jar:0.16.1]
        at com.github.shyiko.mysql.binlog.BinaryLogClient$7.run(BinaryLogClient.java:793) [mysql-binlog-connector-java-0.16.1.jar:0.16.1]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_171]
14:28:46,004 INFO  BinlogConnectorLifecycleListener - Binlog disconnected.
14:28:46,100 WARN  BinlogConnectorReplicator - replicator stopped at position: mysql-bin.000042:673587 -- restarting
14:28:46,104 INFO  BinaryLogClient - Connected to xxxxxx:3306 at mysql-bin.000042/673587 (sid:6379, cid:117580430)
14:28:46,104 INFO  BinlogConnectorLifecycleListener - Binlog connected.
14:28:46,105 WARN  BinlogConnectorLifecycleListener - Communication failure.
```

**Comment by osheroff** [comment]
can you describe your failover situation more?  Do you have `--master_recovery` enabled?  Binlogs are not the same between master/slave so maxwell needs to jump through some hoops to work between failovers.

**Comment by beebird** [comment]
Thanks so much, ``--master_recovery`` does work during failover, will it be a official feature? I saw it's experimental now.

More detail about my situation: I have a running RDS service, and now I'm trying to pull all old + realtime data from RDS to a data warehouse. Because the HA of RDS is critical for me, so I'm eager to find a solution that can both process mysql binlog and handle failover.

Any comments will be much appreciated.

**Comment by osheroff** [comment]
it's been in production at Zendesk for some years now.  I think I can probably take off the experimental label.  The only warning I'd say is that code like this is used very rarely, so problems can occur.

**Comment by beebird** [comment]
Got it, thanks!
