### ISSUE TITLE
Old data incorrectly shows JSON column changed

### ISSUE THREAD

**Issue by wpstuurman** [zendesk/maxwell#1044]
Hi, I noticed that the 'old' data in the row always contains JSON columns, even if they did not change.

I tracked it down to RawJSONString and added an 'equals' method in our code base so it compares based on the json string itself and not the RawJSONString object instance:

```
public boolean equals(Object other) {
	if ((this.json != null) && (other instanceof RawJSONString) && (((RawJSONString)other).json != null)) {
		return this.json.equals(((RawJSONString)other).json);
	}
	else {
		return super.equals(other);
	}
}
```

It now correctly shows if a JSON column was changed.

Is this the correct way to do this?

Thanks.

**Comment by osheroff** [comment]
close.  I think this is maybe simpler:

```
    if ( other == null || !(other instanceof RawJSONString) ) 
        return false;
    else
        return Objects.equals(this.json, ((RawJSONString) other).json)
```

**Comment by osheroff** [comment]
fixed in some version or other
