### ISSUE TITLE
Comment column not captured by SchemaCapturer

### ISSUE THREAD

**Issue by wpstuurman** [zendesk/maxwell#1045]
Hi, 

We are using maxwell to auto-sync data changes in MySQL to Sphinx Search using a custom producer. Works great.

As we don't want to index all columns in Sphinx we need a way to define in MySQL which columns need to be indexed. We really would like the use the 'comment' column definition in MySQL for this. 

We would add parameters (or json) into the comment field for a particular column indicating it needs to be indexed by Sphinx and read it from the SchemaCapture in our custom producer.

The nice thing is that when we change the comment it triggers an 'ALTER TABLE' and maxwell should pick it up automatically.

Currently maxwell doesn't capture the comment column definition. We looked at the maxwell code and it all seems pretty straightforward except for the SQL parsing part. Any hints on how to proceed with the parsing code?

Thanks
WP

**Comment by osheroff** [comment]
So there’s a couple of things that would need to be done.  First, we’d have to capture the comment (both in the capturer and the sql parser), that’s some work but reasonably straightforward.  

The other bit is going to be tunneling column information into the producer via RowMap.  This isn’t super straightforward as row maps can be serialized to disk, so we’d probably have to keep a schema_id and have the row map ask for a copy of the schema (which, ugh, may have changed by the time the producer gets the row — meaning we’d have to keep multiple copies of the schema around in memory, or load them on-demand when RowMap asks for them)

**Comment by wpstuurman** [comment]
Thanks for the detailed info in this. Looks like it is a bit more work than I hoped.

We solved it for now by setting outputConfig.outputDDL to true and read the column meta data directly from MySQL ourselves when we receive a ddl row.
