### ISSUE TITLE
What is xid in the producer message

### ISSUE THREAD

**Issue by winterfellding** [zendesk/maxwell#1049]
From the document of the [website](http://maxwells-daemon.io/dataformat/), I see xid is innodb's transaction id, but when I insert a record from an application, the information_schema.innodb_trx's id is different from the producer's xid record, then where does this xid come from.

**Comment by osheroff** [comment]
the documentation might be slightly incorrect.  It's mysql's internal transaction_id, which is basically just a counter that starts when the server starts up.  It corresponds to nothing outside of the running server, but can be useful to know what rows belong to a transaction.
