### ISSUE TITLE
Learning to use maxwell and new to it,please help,thanks in advance 

### ISSUE THREAD

**Issue by engineerashish007** [zendesk/maxwell#1051]
New to Maxwell,researching it to implement it while transferring bin-logs from MySql to Kafka.Please help me know certain things:
1)Can we configure the frequency at which we transfer data from source to Kafka? like every 1 min or every 5 minutes.
2)Do it support other database sources apart from MySql,I read somewhere it supports ProxySql.Please tell me if it supports MongoDB,Postgre or other tools.

**Comment by liulikun** [comment]
It's not configurable for the timing of publishing events to kafka. Maxwell will publish asap.

It supports MySQL and some MySQL engine based databases. ProxySQL is a proxy to MySQL, not a database itself. So it should work in theory. It doesn't support MongoDB and PostgreSQL.

**Comment by engineerashish007** [comment]
thanks @liulikun .Can we configure the frequency at which we transfer data from source to Kafka? eg:like every 1 minutes or every 5 minutes,can we change the max no. of tuples transferred from mysql to kafka which is 1500 tuples/sec.

**Comment by liulikun** [comment]
I'm confused by ` no. of tuples transferred`. Do you mean key value pairs in json messages published by maxwell? We don't limit how many pairs in json if that's what you mean.

**Comment by engineerashish007** [comment]
@liulikun I mean no. of tuples from mysql table transferred per second as json format in binlogs,can we transfer binlogs of multiple tables at the same time ?sorry for silly questions but I am trying .

**Comment by ericwush** [comment]
You can have custom producer to fulfil your requirements. That way you have control over the pace/size you'd like it to produce. Binlogs contain the logs for all tables so maxwell produces messages for all tables unless you filter some out by using the filter. Not sure if that's what you meant by multiple tables at the same time.

You can take the kafka producer as an example/template for the custom producer.

**Comment by engineerashish007** [comment]
thanks @ericwush . how to achieve distributed/parallel processing in while transferring binlogs to kafka?I read somewhere that kafka-mysql-connector allows us to run in distributed mode.how?,please give a source or explain.I read somewhere at the site maxwells-daemon.io following:
   Maxwell can operate with multiple instances running against a single master, in different configurations. This can be useful if you wish to have producers running in different configurations, for example producing different groups of tables to different topics. Each instance of Maxwell must be configured with a unique client_id, in order to store unique bin-log positions.
  Getting confused,please help me clear it. Can this serve our approach for parallel processing .

**Comment by ericwush** [comment]
I can only speak for maxwell. If you break it down into two steps, a) parse binlogs into json messages (binlogs -> maxwell) b) publish json messages (maxwell -> e.g. kafka). Step b will back pressure step a. 

What exactly do you mean by parallel processing? Reading binlog is sequential. You can have multiple instances of maxwell replicating the same db cluster as you read, but they will end up reading the same pieces of binlog. If you can elaborate your requirement a bit more we might be able to point you into the right direction.

**Comment by engineerashish007** [comment]
@ericwush I mean to say if maxwell has single point of failure or its distributed to recover it using standby or any secondary connection?Please reply back.

**Comment by ericwush** [comment]
Maxwell is a standalone application. You can't start two exactly the same instances of maxwell replicating one db cluster to achieve _distributed mode_. 

[Consul lock](https://www.consul.io/docs/commands/lock.html) provides distributed locking. For example if your service looks like below:
1) try to acquire Consul lock
2) upon the successful acquisition of the lock, start maxwell replicating db1
3) if cannot acquire the lock, do 1)

You can start as many instances of this service as you want but only one instance will acquire the lock to start up maxwell. The lock will be released when maxwell exits. Since other instances of your service are constantly trying to acquire the lock (remember the infinite loop), the next winning instance will start up maxwell again.

You have other choices like Kubernetes to schedule exactly 1 replica meaning at any time there is only one maxwell running. Hope it helps.

**Comment by engineerashish007** [comment]
@ericwush thanks
