### ISSUE TITLE
How to achieve backup of maxwell failure?

### ISSUE THREAD

**Issue by engineerashish007** [zendesk/maxwell#1055]
If maxwell has single point of failure or its distributed to recover it using standby or any secondary connection?I read somewhere that using kafka connector framework with maxwell we can achieve distributed mode but did not got how to do that,so wanted to ask.By plugging in to the Kafka Connect framework, we are able to:
⦁	benefit from standardized best practices for Kafka producers and consumers
⦁	run in distributed or standalone mode
⦁	manage the Kafka MySQL Connector via REST interfaces
⦁	manage offsets in Kafka
source:https://github.com/wushujames/kafka-mysql-connector

I also read reply from @osheroff on similar question asked by someone:
Question : Is it possible to have two Maxwells connected to same MySQL(primary) in active , standby mode? if one of the Maxwell offline, the second Maxwell will function?

@osheroff replied :
No, what you're describing is a distributed lock, which I didn't want to have to embed that inside maxwell. At Zendesk we use consul lock to do what you're describing. There may be zookeeper based solutions too, though I'm not sure what they are.

Could you please explain this consul lock working?

Please reply back.

**Comment by ericwush** [comment]
https://github.com/zendesk/maxwell/issues/1051
