### ISSUE TITLE
Tests fail - boot_isolated_mysql_server missing

### ISSUE THREAD

**Issue by magaton** [zendesk/maxwell#106]
mvn clean install
DEBUG MysqlIsolatedServer - Booting server: /Users/agaton/maxwell/src/test/mysql_isolated_server/bin/boot_isolated_mysql_server -- --binlog_format=row --innodb_flush_log_at_trx_commit=1 --server_id=123123
Tests run: 1, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 0.008 sec <<< FAILURE!
com.zendesk.maxwell.SchemaCaptureTest  Time elapsed: 0.007 sec  <<< ERROR!
java.io.IOException: Cannot run program "/Users/agaton/maxwell/src/test/mysql_isolated_server/bin/boot_isolated_mysql_server": error=2, No such file or directory

**Comment by osheroff** [comment]
try `git submodule init && git submodule update`.  But I'm also reworking a lot of the isolated server stuff, so I'll leave this issue open...

**Comment by magaton** [comment]
Thanks, I tried that but:
Running com.zendesk.maxwell.MaxwellIntegrationTest
DEBUG MysqlIsolatedServer - Booting server: /Users/agaton/maxwell/src/test/mysql_isolated_server/bin/boot_isolated_mysql_server -- --binlog_format=row --innodb_flush_log_at_trx_commit=1 --server_id=123123

hangs forever.
I am using JDK 1.8, but javac source and target are 1.7 per pom.xml
OSX Yosemite, MBP, 4 cores, 4GB heap size

**Comment by osheroff** [comment]
try running the command: `/Users/agaton/maxwell/src/test/mysql_isolated_server/bin/boot_isolated_mysql_server -- --binlog_format=row --innodb_flush_log_at_trx_commit=1 --server_id=123123` by itself.  It needs to find `mysql_install_db` and `mysqld` in your path somewhere...

**Comment by osheroff** [comment]
closing this issue, stuff should be better with the new utlitiy.
