### ISSUE TITLE
Is there sink connector to  get data from kafka to mysql(or any other RMDB\NoSql)?

### ISSUE THREAD

**Issue by runtime16** [zendesk/maxwell#1060]
maxwell provide a perfect framework for mysql->kafka,however I need to get data from kafka to other DB.

I was aware that confluent provide kafka-connect-jdbc.However maxwell data format is not compatible with what confluent platform require.

https://github.com/confluentinc/kafka-connect-jdbc

**Comment by osheroff** [comment]
not at current.  with some work we could support a sort of "maxwell-replicate" thingy (@gabetax that might be useful for exodus).  @runtime16 could you explain your use case more?

**Comment by gabetax** [comment]
@osheroff last we talked about using Maxwell for Exodus CDC you seemed skeptical on the solution, but I don't remember what exactly you were most sour on (maybe related to dropping records?). That said, Aurora's binlog read throughput bottlenecking has left us wanting a better place to buffer binlog data. I'm all ears if you have thoughts.

**Comment by Achyut4** [comment]
@timbertson I'm using MySQL and In my database I have multiple tables and one View. I'm using debezium For Kafka-Connect.
Now when I'm listing Kafka Topics, So I only get Kafka Topics of Database tables, not View.

So Is it possible to get Mysql View's in Kafka Topic?
