### ISSUE TITLE
when could we use kafka2.0.0 version in maxwell ?

### ISSUE THREAD

**Issue by kimbc** [zendesk/maxwell#1061]
Hi,

I have one question.

when could we use kafka2.0.0 version in maxwell ?

is there any plan for this?

thanks.

**Comment by finnplay** [comment]
@kimbc I have same question.
But I have tried to run 1.17.1, at least it works well with kafka-2.0.0. Is there any big change on the kafka's client lib?

**Comment by yangzhongj** [comment]
Fork maxwell ,then add by yourself

**Comment by kimbc** [comment]
@finnplay 

here is kafka's updates.

https://kafka.apache.org/downloads

I think there is no big changes on the kafka's client lib.

**Comment by osheroff** [comment]
So far in all Kafka upgrades the producer API hasn’t changed.  If that api stays the same adding the upgrade is trivial, otherwise it’ll take some work.  Will have to look.
