### ISSUE TITLE
the problem about field "BeginTime"

### ISSUE THREAD

**Issue by SmythAsen** [zendesk/maxwell#1062]
When I create a table containing the field "BeginTime", Maxwell does not listen to the table data.
But this Table is in the Maxwell monitor range.And，When I insert data into the table,maxwell throw
the Exception:"Couldn't find table in database ".
Is "BiginTime" a keyword for maxwell?

**Comment by SmythAsen** [comment]
I find the regex in maxwell source code on class "SchemaChange" about field "BEGIN",I think there are some problems with the way Maxwell deals with these "key-words".

**Comment by osheroff** [comment]
are you using blacklists?

**Comment by SmythAsen** [comment]
no

**Comment by osheroff** [comment]
Fixed in 1.19.0.
