### ISSUE TITLE
How could I except specific columns ? (column filtering)

### ISSUE THREAD

**Issue by kimbc** [zendesk/maxwell#1064]
Hi,

I am not sure it is the best way for excepting specific columns.

in my case, 

I use javascript filer like this ;

-- filter.js

function process_row(row) {
    if ( row.table == "table_name" ) {

        row.data.put("except_col1","");
        row.data.put("except_col2","");
    }
}

-- execute command

 ./maxwell --user='maxwell' --password='password' --host='123.123.123.123' --producer=kafka --kafka.bootstrap.servers=localhost:9092 --kafka_topic=mongodb --config=/usr/local/maxwell/config.properties --filter='exclude: *.*, include: *.table_name' --javascript=/usr/local/maxwell/filter.js

is there any other way for this ?

thanks.

**Comment by osheroff** [comment]
you can use `--exclude_columns='except_col1, except_col2'`

**Comment by rredhatt** [comment]
Just tried the exclude_columns flag using version 1.17.1 and it worked fine. I just wanted to check whether there are any plans to also move this into the newly added --filter capability?

**Comment by ashutosh-valuelabs** [comment]
@osheroff can we specify from which database and table this except_col1 can be excluded like --exclude_columns='databaseA.tableA.except_col1, databaseB.tableB.except_col2'.

**Comment by kennedy-han** [comment]
I suggest that put `exclude_columns ` this command into https://maxwells-daemon.io/config/ page and also https://maxwells-daemon.io/filtering/
@osheroff 
When I filtering, there couldn't find any specific columns.
