### ISSUE TITLE
How to replicate multi master node using maxwell?

### ISSUE THREAD

**Issue by kimbc** [zendesk/maxwell#1065]
hi,

I have one question about replicating multi master node.

there is three mysql server.

I want to replicate these mysql servers.

do I have to use three maxwell daemon?

each daemon use 4~5g memory in maxwell server.

thanks,

**Comment by kimbc** [comment]
these three mysql has different data each other.

it is not cluster node.

**Comment by liulikun** [comment]
Yes, you'll need to run 3 maxwell daemons.

**Comment by osheroff** [comment]
Ok, this is not a "multi-master" setup but 3 different masters.  yeah, you need 3 daemons in that case.  Note that you can limit maxwell's memory via "-Xmx" -- each instance should be able to operate comfortably with about 1gb of memory, depending on your setup.
