### ISSUE TITLE
How could I reduce maxwell's memory usage ?

### ISSUE THREAD

**Issue by kimbc** [zendesk/maxwell#1066]
Hi,

I will replicate 100 mysql servers.

but maxwell use over 10Gb memory space per each daemon.

so I want to reduce maxwell daemon's memory usage.

in my case,

I modified the maxwell java command like this ;

-- Launch mode
if [ "x$DAEMON_MODE" = "xtrue" ]; then
    nohup $JAVA -d64 $JAVA_OPTS -Dfile.encoding=UTF-8 -Dlog4j.shutdownCallbackRegistry=com.djdch.log4j.StaticShutdownCallbackRegistry -Xmx300m -cp $CLASSPATH com.zendesk.maxwell.Maxwell "$@" > "$CONSOLE_OUTPUT_FILE" 2>&1 < /dev/null &
else
    exec $JAVA  -d64  $JAVA_OPTS -Dfile.encoding=UTF-8 -Dlog4j.shutdownCallbackRegistry=com.djdch.log4j.StaticShutdownCallbackRegistry -Xmx300m  -cp $CLASSPATH com.zendesk.maxwell.Maxwell "$@"
fi

as you can see

I added -Xmx300m option on java command.

but this error happened after execute.

"Exception in thread "main" java.lang.OutOfMemoryError: GC overhead limit exceeded"

maxwell version is 1.17.1

how could I customize this?

is it related with this issue?
https://github.com/zendesk/maxwell/pull/366

thanks.

**Comment by kimbc** [comment]
target type : kafka

**Comment by kimbc** [comment]
-- this is maxwell information


10:18:10,725 INFO  ProducerConfig - ProducerConfig values: 
        acks = 1
        batch.size = 16384
        bootstrap.servers = [localhost:9092]
        buffer.memory = 33554432
        client.id = 
        compression.type = snappy
        connections.max.idle.ms = 540000
        enable.idempotence = false
        interceptor.classes = null
        key.serializer = class org.apache.kafka.common.serialization.StringSerializer
        linger.ms = 0
        max.block.ms = 60000
        max.in.flight.requests.per.connection = 5
        max.request.size = 1048576
        metadata.max.age.ms = 300000
        metric.reporters = []
        metrics.num.samples = 2
        metrics.recording.level = INFO
        metrics.sample.window.ms = 30000
        partitioner.class = class org.apache.kafka.clients.producer.internals.DefaultPartitioner
        receive.buffer.bytes = 32768
        reconnect.backoff.max.ms = 1000
        reconnect.backoff.ms = 50
        request.timeout.ms = 30000
        retries = 0
        retry.backoff.ms = 100
        sasl.jaas.config = null
        sasl.kerberos.kinit.cmd = /usr/bin/kinit
        sasl.kerberos.min.time.before.relogin = 60000
        sasl.kerberos.service.name = null
        sasl.kerberos.ticket.renew.jitter = 0.05
        sasl.kerberos.ticket.renew.window.factor = 0.8
        sasl.mechanism = GSSAPI
        security.protocol = PLAINTEXT
        send.buffer.bytes = 131072
        ssl.cipher.suites = null
        ssl.enabled.protocols = [TLSv1.2, TLSv1.1, TLSv1]
        ssl.endpoint.identification.algorithm = null
        ssl.key.password = null
        ssl.keymanager.algorithm = SunX509
        ssl.keystore.location = null
        ssl.keystore.password = null
        ssl.keystore.type = JKS
        ssl.protocol = TLS
        ssl.provider = null
        ssl.secure.random.implementation = null
        ssl.trustmanager.algorithm = PKIX
        ssl.truststore.location = null
        ssl.truststore.password = null
        ssl.truststore.type = JKS
        transaction.timeout.ms = 60000
        transactional.id = null
        value.serializer = class org.apache.kafka.common.serialization.StringSerializer

**Comment by kimbc** [comment]
I modified the value from -Xmx300m to -Xmx1000m.

but the same error happend.

thanks.

**Comment by osheroff** [comment]
How many databases / tables do you have in each schema?

**Comment by kimbc** [comment]
-- each count

database : 2000

tables : 400000

**Comment by kimbc** [comment]
-- this is maxwell mysql db's disk size

# ls -lh
total 765M
-rw-r----- 1 mysql mysql 8.9K Aug  9 17:33 bootstrap.frm
-rw-r----- 1 mysql mysql  96K Aug  9 17:43 bootstrap.ibd
-rw-r----- 1 mysql mysql 8.7K Aug  9 17:33 columns.frm
-rw-r----- 1 mysql mysql 716M Aug  9 19:20 columns.ibd
-rw-r----- 1 mysql mysql 8.5K Aug  9 17:33 databases.frm
-rw-r----- 1 mysql mysql 272K Aug  9 18:58 databases.ibd
-rw-r----- 1 mysql mysql   61 Aug  9 17:33 db.opt
-rw-r----- 1 mysql mysql 8.5K Aug  9 17:33 heartbeats.frm
-rw-r----- 1 mysql mysql  96K Aug 10 11:11 heartbeats.ibd
-rw-r----- 1 mysql mysql  21K Aug  9 17:33 positions.frm
-rw-r----- 1 mysql mysql  96K Aug 10 11:19 positions.ibd
-rw-r----- 1 mysql mysql  21K Aug  9 17:33 schemas.frm
-rw-r----- 1 mysql mysql 112K Aug 10 11:02 schemas.ibd
-rw-r----- 1 mysql mysql  13K Aug  9 17:33 tables.frm
-rw-r----- 1 mysql mysql  48M Aug  9 19:19 tables.ibd

**Comment by osheroff** [comment]
400k tables, yup, that’s a lot.  How many of the tables have identical schemas?

**Comment by kimbc** [comment]
there are 2,000 databases.

all these databases are same tables.

so 2,000 tables are same.

each databases has only 200 tables.


200 tables X 2,000 databases = 400k tables.

**Comment by kimbc** [comment]
There are only 200 tables.
However, the same table exists repeatedly in 2000 databases.

**Comment by kimbc** [comment]
select count(1) from `tables` ;
400k

select count(distinct table_name) from `tables` ;
200

**Comment by osheroff** [comment]
ok, I think there's a reasonably straightforward patch to reduce mem usage for schemas.   Maxwell startup / capture is probably gonna be pretty slow in this scenario no matter what ya do, but I can at least get the memory footprint down.

**Comment by kimbc** [comment]
ok, I will wait for this.

thanks.

**Comment by kimbc** [comment]
I am very helpful in utilizing maxwell.
We are using it very usefully and will be applied widely in the future.

One thing I would like to know is what will happen to the ETA plan in relation to this issue.

Thank you.

**Comment by osheroff** [comment]
hola from panama!  
just opened a PR

**Comment by osheroff** [comment]
optimizations released in v1.18.0
