### ISSUE TITLE
maxwell complained  Unhandled QueryEvent inside transaction Warning

### ISSUE THREAD

**Issue by yxs1112003** [zendesk/maxwell#1068]
Hi，We use Mysql5.7 build a master slave envirment，Mysql master binlog is mixed and Mysql slave is row. 
I use Maxwell read slave row binlog and restart mysql slave, but Maxwell complain 
```
"BinlogConnectorReplicator - Unhandled QueryEvent inside transaction" WARN Message。
```
Does mysql master mixed binlog effect Maxwell?

Hope your reply.

**Comment by kimbc** [comment]
as I know,
maxwell has to use raw based bin log type.

**Comment by yxs1112003** [comment]
Thanks your reply.
I change to canal,it seem OK.
