### ISSUE TITLE
Messages to large for greylog

### ISSUE THREAD

**Issue by tomlis** [zendesk/maxwell#1074]
Hello,
  I have encountered a problem with maxwell's producer type Rabbit. I forward messages from Rabbit to Greylog. Some messages exceeds 32kB and cannot be processed by greylog, even causing some greylog/s server issues. 
The message weight is mostly the full SQL query, I use maxwell with "output_row_query=true". I need the query for other purposes, however I could use truncated query, for example first 2000chars. Is there any way to truncate SQLs before it hit the Rabbit (and then Greylog) ?

**Comment by osheroff** [comment]
I think you could use JavaScript filters to accomplish this.  I’d have to check that the query is settable from JavaScript tho

**Comment by tomlis** [comment]
I am affraid that "query" is not settable :( 
I have created a simple JS filter file with content: 

```
function process_row(row) {
  row.query = 'TEST';
  row.data.put("new_field", "new field value");
}
```
and the output : 
```{"database":"my_db","table":"my_table","query":"UPDATE `my_db`.`my_table` SET `subject`='12345' WHERE `id`='2'","type":"update","ts":1534854694,"xid":1111112222,"commit":true,"position":"mysql-bin.000522:378468892","server_id":10001,"thread_id":2146872,"data":{"id":2,"priority_id":1,"reporter_id":2,....,"subject":"12345","due_date":null,"created_at":"2018-07-03 13:05:04","updated_at":"2018-07-24 07:59:49",..."deleted_at":null,"system_data":null,"new_field":"new field value"},"old":{"subject":"123"}}
```

Field "query" seems not to be affected by change. 
Can you make that field settable ?

**Comment by osheroff** [comment]
row-query now accessible from javascript filters in 1.18.0

**Comment by tomlis** [comment]
It works ! Thanks
