### ISSUE TITLE
Non-english column name support?

### ISSUE THREAD

**Issue by d8888** [zendesk/maxwell#1075]
When I used Maxwell Daemon to stream data from table containing Chinese column name (such as "你好"), I noticed that the key corresponding to column name became question marks, that is:

I expect message should be:

{..., "data": {"你好":"123"}}

however in reality the message will looks like:

{..., "data": {"????":"123"}}

I also noticed that the "columns" table in "maxwell" database used latin_swedish_ci encoding for "name" column (which corresponds to column name), the "name" column also incorrectly stored column name as question marks (e.g stored "????" instead of "你好"). I changed encoding for "name" column into UTF-8 and repeated bootstraping process however the problem persisted.

Does Maxwell Daemon support non-English column name? Or is there anywhere to circumvent this problem? Thanks in advance!

**Comment by osheroff** [comment]
Interesting bug, I will have to look.  No clue why I would have picked latin-1 for column names, seems overly optimistic :)

**Comment by d8888** [comment]
I have proposed pull request for this issue. In my own manual testing, Chinese letters now display correctly in JSON message in stdout.
https://github.com/zendesk/maxwell/pull/1099

**Comment by osheroff** [comment]
fixed in v1.18.0
