### ISSUE TITLE
NPE in TableAlter

### ISSUE THREAD

**Issue by davidhao3300** [zendesk/maxwell#1076]
Charset is potentially null, which causes an NPE at this line.
https://github.com/zendesk/maxwell/blob/master/src/main/java/com/zendesk/maxwell/schema/ddl/TableAlter.java#L57

Would open a PR, but I'm not exactly sure how Maxwell should handle null behavior.

An example query that managed to replicate this error (on mysql 5.5), was running the following query in the database called "mysql":
```
ALTER TABLE db
   MODIFY Host char(60) NOT NULL default '',
   MODIFY Db char(64) NOT NULL default '',
   MODIFY User char(16) NOT NULL default '',
   ENGINE=MyISAM, CONVERT TO CHARACTER SET utf8 COLLATE utf8_bin;
```
This query was performed when performing a security update on mysql, and maxwell crashes with an NPE due to calling a method on a null object at the linked line

**Comment by osheroff** [comment]
we could certainly just add a NPE check here and allow the conversion to continue, but it's weird that there's a null character set here.  I can't really imagine how the built-in tables would have gotten a NULL charset.  hmmmm.

**Comment by shannontan-addepar** [comment]
@osheroff This can be closed with my PR that was merged.

**Comment by davidhao3300** [comment]
Fixed in https://github.com/zendesk/maxwell/pull/1101
