### ISSUE TITLE
unable to monitor data insertion

### ISSUE THREAD

**Issue by chaserchen** [zendesk/maxwell#1078]
**System version: Ubuntu 16.04
Mysql version: 5.7.23
Maxwell version: 1.17.1**

After maxwell is successfully started, the operation of adding a new table to the database can be monitored, but the inserted data cannot be monitored.

$ bin/maxwell --user='maxwell' --password='maxwell' --host='127.0.0.1' --producer=stdout
Using kafka version: 1.0.0
20:15:40,965 WARN  MaxwellMetrics - Metrics will not be exposed: metricsReportingType not configured.
20:15:41,314 INFO  SchemaStoreSchema - Creating maxwell database
20:15:43,893 INFO  Maxwell - Maxwell v1.17.1 is booting (StdoutProducer), starting at Position[BinlogPosition[master.000003:5376], lastHeartbeat=0]
20:15:44,136 INFO  AbstractSchemaStore - Maxwell is capturing initial schema
20:15:44,534 INFO  BinlogConnectorReplicator - Setting initial binlog pos to: master.000003:5376
20:15:44,966 INFO  BinaryLogClient - Connected to 127.0.0.1:3306 at master.000003/5376 (sid:6379, cid:9)
20:15:44,967 INFO  BinlogConnectorLifecycleListener - Binlog connected.
20:16:14,783 INFO  AbstractSchemaStore - storing schema @Position[BinlogPosition[master.000003:29499], lastHeartbeat=1535372167390] after applying "create table test (id integer)" to maxwell, new schema id is 2

```
mysql> desc test;  

+-------+---------+------+-----+---------+-------+
| Field | Type    | Null | Key | Default | Extra |
+-------+---------+------+-----+---------+-------+
| id    | int(11) | YES  |     | NULL    |       |
+-------+---------+------+-----+---------+-------+
1 row in set (0.00 sec)
```
### `insert into test values(1);`  
**The result of this statement will not print in the output above**

**Comment by osheroff** [comment]
maxwell doesn't output changes in the `maxwell` database.  This will work if you run the test in a different database.
