### ISSUE TITLE
error: Started replication stream inside a transaction

### ISSUE THREAD

**Issue by tomlis** [zendesk/maxwell#1079]
Maxwell has crashed with error, why is that ? 

```
root@debian:/mnt/storage/provision.d# docker logs maxwell
Using kafka version: 1.0.0
14:33:51,714 WARN  MaxwellMetrics - Metrics will not be exposed: metricsReportingType not configured.
14:33:52,530 WARN  BinlogConnectorReplicator - Started replication stream inside a transaction.  This shouldn't normally happen.
14:33:52,530 WARN  BinlogConnectorReplicator - Assuming new transaction at unexpected event:com.zendesk.maxwell.replication.BinlogConnectorEvent@17aad511
```

**Comment by osheroff** [comment]
what version of maxwell are you running?  we fixed quite a few things in v1.15.0

**Comment by ede-n** [comment]
I came across this error when I manually updated `maxwell.positions.binlog_position` to a value in between the begin and end position of a transaction in binary log. This should not happen usually.

**Comment by osheroff** [comment]
Hi, because it's been too long waiting for a response, I'm closing down this issue.  Feel free to re-open it if you have more information.  Thanks!
