### ISSUE TITLE
[Question] Can maxwell also send table schema changes to kinesis stream?

### ISSUE THREAD

**Issue by jingchima-appf** [zendesk/maxwell#1089]
I want to strictly synchronizing two databases. If the source the schema of a table in source database changed, I want the target database to do the same thing as well. Now I found that the schema changed is stored as AbstractSchema #number but it's not sent. Is there a way to do that? Thanks!

**Comment by osheroff** [comment]
you can use `--output_ddl` to output schema changes.  Can you describe your use case more?  I'm thinking a bit about adding native support for database synch like this.
