### ISSUE TITLE
when install maxwell 0.11.1 it raise error gzip: stdin: unexpected end of file

### ISSUE THREAD

**Issue by yester354** [zendesk/maxwell#109]
Hi
    i am installing maxwell 0.11.1 using command as below:
    curl -sLo - https://github.com/zendesk/maxwell/releases/download/v0.11.1/maxwell-0.11.1.tar.gz \
       | tar zxvf -
    then it raise error :
    gzip: stdin: unexpected end of file
    tar: Child returned status 1
    tar: Error is not recoverable: exiting now

**Comment by osheroff** [comment]
odd.  does this work?
```
 curl -L https://github.com/zendesk/maxwell/releases/download/v0.11.1/maxwell-0.11.1.tar.gz  >maxwell-0.11.1.tar.gz
tar zxvf maxwell-0.11.1.tar.gz
```

**Comment by yester354** [comment]
@osheroff 
  it works now.thank you
