### ISSUE TITLE
Maxwell process dying 

### ISSUE THREAD

**Issue by theoreh1** [zendesk/maxwell#1093]
We are using Maxwell 1.17.1 and writing to google pub/sub .  Maxwell will run fine for 15-20 minutes, then eventually throw the following and shutdown: 

17:13:17,045 ERROR PubsubCallback - DeadlineExceededException @ Position[BinlogPosition[masterLog.000083:922968811], lastHeartbeat=0]
17:13:17,045 ERROR PubsubCallback - io.grpc.StatusRuntimeException: DEADLINE_EXCEEDED: deadline exceeded after 9999976773ns
17:13:17,050 ERROR PubsubCallback - DeadlineExceededException @ Position[BinlogPosition[masterLog.000083:922723394], lastHeartbeat=0]
17:13:17,050 ERROR PubsubCallback - io.grpc.StatusRuntimeException: DEADLINE_EXCEEDED: deadline exceeded after 9999975852ns
17:13:17,061 ERROR PubsubCallback - DeadlineExceededException @ Position[BinlogPosition[masterLog.000083:922772486], lastHeartbeat=0]
17:13:17,061 ERROR PubsubCallback - io.grpc.StatusRuntimeException: DEADLINE_EXCEEDED: deadline exceeded after 9999976475ns
........
17:16:38,106 DEBUG NettyClientHandler - [id: 0xd6c68283, L:/10.250.0.5:34850 - R:pubsub.googleapis.com/<ip>:443] OUTBOUND HEADERS: streamId=1138721 headers=GrpcHttp2OutboundHeaders[:authority: pubsub.googleapis.com:443, :path: /google.pubsub.v1.Publisher/Publish, :method: POST, :scheme: https, content-type: application/grpc, te: trailers, user-agent: grpc-java-netty/1.7.0, x-goog-api-client: gl-java/1.8.0_181 gapic/0.30.0-beta gax/1.15.0 grpc/1.7.0, grpc-accept-encoding: gzip, grpc-timeout: 9999999u, authorization: Bearer ya29.c.EloRBuiyHPex5mfMAVjpyLCAkVU6nZ-ITJw7b71IqEE56-zg6M3Vtpat-4GNIaFye3Ss0Ib5rTcQSEt8rgHgO4wX3HJH0ALF9RBX-1TmVbR2VMtiJeFGq-kf0Pg, grpc-trace-bin: ] streamDependency=0 weight=16 exclusive=false padding=0 endStream=false 
17:16:38,110 DEBUG NettyClientHandler - [id: 0xd6c68283, L:/10.250.0.5:34850 - R:pubsub.googleapis.com/<ip>:443] OUTBOUND RST_STREAM: streamId=1138365 errorCode=8
17:16:38,110 DEBUG NettyClientHandler - [id: 0xd6c68283, L:/10.250.0.5:34850 - R:pubsub.googleapis.com/<ip>:443] OUTBOUND RST_STREAM: streamId=1138369 errorCode=8
17:16:38,110 DEBUG NettyClientHandler - [id: 0xd6c68283, L:/10.250.0.5:34850 - R:pubsub.googleapis.com/<ip>:443] OUTBOUND RST_STREAM: streamId=1138373 errorCode=8
17:17:13,122 DEBUG MaxwellContext - Shutdown complete: false
17:17:13,122 ERROR MaxwellContext - Shutdown stalled - forcefully killing maxwell process   

From the mysql side there are 2000 databases with 505 tables each.  Any guidance is appreciated.

Thanks

**Comment by osheroff** [comment]
it looks like you're hitting a 10 second timeout connecting to google pubsub.  what's your max-heap size?  A hunch of mine (given your schema size) says that maybe the jvm is getting trapped doing too much garbage collection.  Is the JVM pegged at like 100% cpu usage?  

FYI am working on code to improve the memory usage for large schemas here https://github.com/zendesk/maxwell/pull/1080, going to try to get it into the next release

**Comment by theoreh1** [comment]
It's 10G, and yes cpu was 100%.

**Comment by osheroff** [comment]
Ok.  If you'd like to test out the code in #1080 and see if the issue goes away, great.  If not it should make it into the next release.

**Comment by theoreh1** [comment]
So far so good.  Been running all weekend without error.
