### ISSUE TITLE
Output as SQL Statements

### ISSUE THREAD

**Issue by SqlAdmin** [zendesk/maxwell#1094]
Im using the latest version of Maxwell. I want to replicate from one mysql to another Mysql. Unfortunately, I can't setup direct replication from that server. But I have access to binlog. So Im planning to setup replication. 

So, --output_ddl will provide SQL statement of CREATE, ALTER, DELETE things, but how can I get the sql statement of all the queries?

**Comment by osheroff** [comment]
if you're on mysql 5.6+, you can use `--output_row_query` (note that `binlog_rows_query_log_events` must be enabled on the server) to retrieve the original SQL.  This *may* be a frequent enough use case to just go ahead and implement a maxwell "replication" format.  It seems a lot like re-inventing a wheel but there can be use cases for it (easier partial-replication comes to mind, splitting databases for sharding automatically, stuff like that)....
