### ISSUE TITLE
Filtering with exclude *.* filters out maxwell row events

### ISSUE THREAD

**Issue by richhart** [zendesk/maxwell#1104]
I've recently encountered an issue with maxwell not updating its binlog position and heartbeat in the `maxwell.positions` db table. I've managed to trace the issue back to the way I am filtering out events with the filter param in `config.properties`.

I have been using a strict exclude list with named includes so that maxwell is unaffected if new schemas are added to the db instance that the maxwell db user doesn't have rights to access:
`filter: "exclude: *.*,  include: mydb.mytable.mycolumn=0, blacklist: /^((?!mydb).)*$/.*"`
where mydb.mytable is the specific db and table that I want to push events out to a Kinesis enabled stream.

By enabling this config I can see the `maxwell.heartbeats` table being updated correctly (every 10s) as detailed in the code, but the update to this table is then not being consumed after transaction commit as an event to update the `binlog_file` and `last_heartbeat_read` in the `maxwell.positions` table, due to the filter configuration I've set up. 

The knock on effect of this is that when the system is idle for a period longer than the binlog retention period (i.e. the last binlog file referenced in the `maxwell.positions` table is no longer available in the binlog) and a maxwell restart takes place (this happened when my AWS RDS cluster failed over to a 2nd node and there was a momentary mysql communication failure) it cannot restart as it attempts to restart processing from the entry in the `maxwell.positions` table that no longer exists. 

My question is.... Is this a bug in the code that the filtering can allow the user to configure an exclusion to the maxwell schema which is required for maxwell heartbeats to work correctly? If not, the documentation for filtering should state that you **must** include the maxwell schema in the filter configuration inclusions and never exclude it?

I hope I've explained the scenario well enough.

Thanks
Rich

**Comment by osheroff** [comment]
this is a bug that's reared its head, regressed, and then reared again.  What version of maxwell are you running?  I coulda swore I fixed this.

**Comment by richhart** [comment]
I'm using version: 1.17.1

**Comment by osheroff** [comment]
I've added a fix for this in 1.19.0.  Thanks for the super detailed bug report, it helped a lot.

**Comment by 1813705585** [comment]
Hello, landlord, The Maxwell version I used cannot filter the specified database. The Maxwell version I used is 1.27.1. The filtering configuration in the configuration file is as follows:    filter = 'exclude: mysqldb.*,include: mysqldb.mysqltable'   I hope you will reply when you see this, thank you very much,  if you can give an example of configuration filtering on Maxwell's website and demo
