### ISSUE TITLE
The option --output_binlog_position=true,  only output delete type query，the insert、update will not output.

### ISSUE THREAD

**Issue by yiwenshuo** [zendesk/maxwell#1109]
Version maxwell-1.16.0
The maxwell command:./maxwell --user='xxxx' --password='xxxxx' --host='xxxx' --port=3306 --producer=kafka --kafka.bootstrap.servers=xxxxx:9092  --output_binlog_position=true --output_row_query=true  --kafka_topic=CrmRdsData --output_ddl=true --ddl_kafka_topic=DDLCrmRdsData 

The MySQL server parameter  "binlog_rows_query_log_events=1".

The phenomenon is the kafka consumer topic only output delete  original sql, but update,insert  will not output  original sql.

**Comment by osheroff** [comment]
that's a strange error.  did you happen to change the `binlog_rows_query_log_events` parameter with the server running?  If so, you probably need to disconnect and reconnect all clients....

**Comment by osheroff** [comment]
reporter drive-by, feel free to re-open if you have new information.

**Comment by ashutosh-valuelabs** [comment]
Is there any way to take only inserted new records in kafka topic, neglecting updating and deleting options. In table when there is insert or update or delete happens, then i only want new records which are inserted in my kafka consumer, neglecting updated and deleted one. Any help would be appriciated. Thanks in advanced.
