### ISSUE TITLE
Bootstrapping + docker

### ISSUE THREAD

**Issue by jimymodi** [zendesk/maxwell#1119]
Till now we were running maxwell instances on a standalone machine. But now we are moving to AWS ECS and docker based deployments. 
Till now, we were bootstrapping by running command by sshing into the standalone server. But now we won't be having ssh access to the docker container. So how to run the bootstrapping from a very different server ?
Do anyone do this bootstrapping + docker workload. How do you work around this ?

**Comment by osheroff** [comment]
the bootstrap code communicates only through the database, so you can simply use the same docker container and execute the `maxwell-bootstrap` utility.  This utility just inserts a row into the database that signals the main maxwell process to do a bootstrap.
