### ISSUE TITLE
Diagnostic endpoint - how does it work?

### ISSUE THREAD

**Issue by jkrcma** [zendesk/maxwell#1124]
Hi,

I've been trying to use the `/diagnostic` endpoint for purposes of liveness probe in k8s, however I am not able to get it working. I am using the split server setup as Maxwell is replicating from a slave and k8s provides me an easy way to tighten the "state db" directly to Maxwell deployment. From the output of `/diagnostic` call it looks like the "state db" connection is being checked (k8s internal IP) which is afaik wrong:

```
{
    "success": false,
    "checks": [
        {
            "name": "binlog-connector",
            "success": false,
            "mandatory": true,
            "resource": "10.104.61.158:3306",
            "message": "check did not return after 10000 ms"
        }
    ]
}
```
I am not familiar with Maxwell's source code and Java much however [this line](https://github.com/zendesk/maxwell/commit/7fc34aef2c7de88f9d75690024d41dc34cab2b6d#r30729240) in 7fc34ae got my attention.

Btw are you interested in a Helm chart for Maxwell? I could send you the PR.

**Comment by osheroff** [comment]
I'm not super-familiar with this code either, looks like @ericwush is the main one to answer this?

**Comment by ericwush** [comment]
@jkrcma Unfortunately diagnostic endpoint won't work in split db server setup. For the binlog connection check, it also reports the latency, i.e. how long it takes the event in binlog to be seen by maxwell after it occurred in db. To achieve this in a manageable manner, we use maxwell's heartbeats which are written into the "state db", to measure (the time the event is seen in maxwell) - (the time it occurred). The latency _could_ be measured in the same way by checking _your_ db, but if there is no traffic when the check happens, we won't be able to report the latency. So the uncertainty makes it less manageable.

You may consider other endpoints like `/ping` for liveness check. Hope it helps.

**Comment by jkrcma** [comment]
@ericwush I see the point as I am facing very similar problems. I tried to use `/ping`, but the endpoint reports alive status even when there is any of the random errors present, causing Maxwell to get stuck in a dead loop, like the _"max allowed packet"_ problem. I am able to decet the anomaly by watching different metrics, but I miss the ability to automate the restart.

**Comment by ericwush** [comment]
Yes, `/ping` is very basic only reporting whether the process is alive or not. In most cases maxwell will crash if it's a critical error e.g. cannot connect to binlog or cannot deliver the messages to the destination, so you wouldn't need to use a health check endpoint to detect those errors. 

In your case, what do you do if it gets stuck? Would a restart fix the issue? If so, it sounds like a scenario where maxwell should crash. I don't know about the details of your problem. Can you please elaborate, along with other anomaly you are currently using metrics to detect?

**Comment by jkrcma** [comment]
I simply delete the pod in k8s and let it restart, that does indeed fix the issues.

The runtime problems are described in #1118 and #1087 (however I am pretty sure the binlog file is not missing in my case). I can assist you in finding the causes of the issues above but it will be a longer run :) also I might create a new issue for #1087 because there is an exception worth posting.

**Comment by kevinclcn** [comment]
please check this issue and see whether it is caused by the same one https://github.com/zendesk/maxwell/issues/1088
