### ISSUE TITLE
Stuck at binlog position when catching up 

### ISSUE THREAD

**Issue by jkrcma** [zendesk/maxwell#1130]
We have quite a big Percona 5.6 setup running, GTID, 4T database, over 1k transactions per second, Maxwell is connected to a slave node and replicates to RabbitMQ cluster.

When I was trying to fix GTID gaps as described in #1129 I found out that after a single gap is cleared, Maxwell refuses to jump onto another gap and remains stuck at the last GTID of the binlog file which was just catched up. Restarting Maxwell helps but the issue repeats until there are any gaps present in the GTID set.

Maxwell doesn't report anything in the logs.

**Comment by osheroff** [comment]
I think this was fixed as well in 1.19.5.  not 100% sure but i think so
