### ISSUE TITLE
run Maxwell on kubernetes to send mysql binlog to rabbitMQ

### ISSUE THREAD

**Issue by HBO2** [zendesk/maxwell#1138]
HI,

It would be helpful if someone already deployed the docker image on kubernetes (relative easy), but with the configuration for sending to RabbitMQ included. I am trying to do it on basis of the example:
`bin/maxwell --user='maxwell' --password='XXXXXX' --host='127.0.0.1' \
    --producer=rabbitmq --rabbitmq_host='rabbitmq.hostname'
`

But cannot figure it out. any help would appreciated

**Comment by osheroff** [comment]
can you provide more information on what you've tried, and where you're running into problems?

**Comment by jkrcma** [comment]
We do have Maxwell running in k8s and streaming data to RabbitMQ. I offered my helm chart to developers, so I might just publish it to my public or company Github.

**Comment by HBO2** [comment]
@jkrcma Oh.. that would be great!

**Comment by osheroff** [comment]
closing for lack of info about the issue, feel free to re-open with more specifics

**Comment by jkrcma** [comment]
@pedrodparkes Sorry I don't work for the mentioned company anymore. @sparkycz I guess this topic was forgotten, right? Could you ask someone please? :)

**Comment by Sparkycz** [comment]
As I know, the topic was absolutely forgotten...
I forwarded the request to our Infrastructure team.
