### ISSUE TITLE
Include primary key in output?

### ISSUE THREAD

**Issue by rogershieh** [zendesk/maxwell#1143]
I'm trying to make sure deletes and updates work properly with the target db and don't accidentally delete the wrong row or worse a bunch of unrelated rows. Is it possible to include which column is the pk in the maxwell output (to kafka)?

**Comment by osheroff** [comment]
not currently, no.  There's *occasionally* a request to get some parts of the schema information into the maxwell output row, but I'm not sure exactly what use cases it would be supporting.  Maybe this is something that could be opened up to the scripting engine, not sure.

**Comment by rogershieh** [comment]
I see, I'm using maxwell to essentially mirror data in mySQL to another database. While inserts work perfectly, updates and deletes are muddied by the lack of primary keys.

**Comment by wangtran1990** [comment]
Hi, I think we have the same issue, but I choose the approach is to replicate data by SQL command, not parsing JSON to SQL.
Try my issue link, hope it help.
https://github.com/zendesk/maxwell/issues/1144

**Comment by rogershieh** [comment]
yeah that seems to be the only way right now, but would pose a problem when there is a large amount of data. also when running broad queries like delete from db.table, wouldn't the same query be run n times depending on the number of rows?

**Comment by wangtran1990** [comment]
In my case, I use RabbitMQ, pop the message from queue then execute the query one by one. It increases latency but data is guaranteed (maybe).

**Comment by osheroff** [comment]
I guess I have some questions about this: why use maxwell for this and not standard replication?  
Generally queues like kafka, rabbitMQ, kinesis, whatever, are not really reliable enough to (strictly) replicate a database.  It might work most of the time, but there's chances of out-of-order events, duplicate events, stuff like that.  

Maaaaybe it'd make sense to have a utility of maxwell that can do replication, but honestly it'd probably have to be direct replication (read from one database, write to another) without the queue in the middle to make sense.

**Comment by rogershieh** [comment]
very true. The roadmap for my current project would lead to combining multiple databases (oracle, sql server) and also include some stream processing. But currently I'm just trying to get the basics working. (e.g. streaming sales data but also reflecting order changes/refunds with updates and deletes)

**Comment by guycoleman** [comment]
I could be missing something but isn't the PK included in the record key?

`{"database":"test","table":"user","pk.user_id":148}`
