### ISSUE TITLE
Can I get pure SQL command?

### ISSUE THREAD

**Issue by wangtran1990** [zendesk/maxwell#1144]
Hi there!
I have a quick question.
Please let me know, Can I get pure SQL command (not to JSON formatted) by Maxwell (and how to config if it had)?
For some reasons..., I need this data
Please help me.
Thanks.

**Comment by liulikun** [comment]
You'll need to config MySQL server to enable query log, check out https://dev.mysql.com/doc/refman/5.6/en/replication-options-binary-log.html#sysvar_binlog_rows_query_log_events for `binlog_rows_query_log_events`, once that's enabled, maxwell output will include `query` field which is the SQL command.

**Comment by wangtran1990** [comment]
It worked for me.
Thank @liulikun for your support.
