### ISSUE TITLE
zendesk/maxwell:v1.13.2 - Please advise if Binlog is loosing records putting into Kinesis stream

### ISSUE THREAD

**Issue by RajanBhattIntapp** [zendesk/maxwell#1147]
Hi, 
I am observing following logs and observing that may be Binlog is loosing records as I difference between UserRecords and KinesisRecords," Is that correct or I am interpreting is wrong .

Thanks for advise/suggestion.

Rajan

=========
rs: { stream: '', manual: 0, count: 0, size: 0, matches: 0, timed: 15, KinesisRecords: 16, PutRecords: 15 }
21:32:46,448 INFO  LogInputStreamReader - [2018-10-26 21:32:46.448432] [0x0000006b][0x00007ff6cffff700] [info] [processing_statistics_logger.cc:127] () Average Processing Time: 9.4 ms
21:33:01,448 INFO  LogInputStreamReader - [2018-10-26 21:33:01.448576] [0x0000006b][0x00007ff6cffff700] [info] [processing_statistics_logger.cc:109] Stage 1 Triggers: { stream: ', manual: 0, count: 0, size: 0, matches: 0, timed: 13, UserRecords: 16, KinesisRecords: 13 }
21:33:01,448 INFO  LogInputStreamReader - [2018-10-26 21:33:01.448613] [0x0000006b][0x00007ff6cffff700] [info] [processing_statistics_logger.cc:112] Stage 2 Triggers: { stream: '', manual: 0, count: 0, size: 0, matches: 0, timed: 13, KinesisRecords: 13, PutRecords: 13 }
21:33:01,448 INFO  LogInputStreamReader - [2018-10-26 21:33:01.448622] [0x0000006b][0x00007ff6cffff700] [info] [processing_statistics_logger.cc:127] () Average Processing Time: 9.4615385 ms

**Comment by osheroff** [comment]
I'm not 100% up on the Kinesis producer, but my guess here is that Kinesis does what Kafka does, which is to batch up records together for performance's sake, and so you're seeing that you sent 16 records but kinesis bundled a few of them up together and only sent 13.  

maybe @thomasdziedzic-pd would know for sure.

**Comment by RajanBhattIntapp** [comment]
That makes sense. Thanks @osheroff, So KPL library batches up before sending to Kinesis. Let me also check source code. Why that does not happen for all records, any guess. Should I always expect less KinessRecord for UserRecord which is not the case. @thomasdziedzic-pd

**Comment by osheroff** [comment]
generally producer libraries will wait some amount of milliseconds to see if there's a batch available, and if there isn't, will send it.  So if you send 3 rows very quickly, kinesis will see that and make a batch.  But if you send just one row every second, kinesis has to send the row by itself.  At least that's how kafka works, and I'm imagining kinesis is similar.

**Comment by RajanBhattIntapp** [comment]
@osheroff You are correct, Aggregation is enabled. It uses default record_max_buffered_time  of 100ms it is default as mentioned in https://github.com/awslabs/amazon-kinesis-producer/blob/master/java/amazon-kinesis-producer-sample/default_config.properties. So UserRecord and KinesisRecord count may differ.
