### ISSUE TITLE
WARN  BinlogConnectorReplicator - Unhandled QueryEvent inside transaction

### ISSUE THREAD

**Issue by shehuaqigai** [zendesk/maxwell#1155]
i use aws RDS mysql5.6.35  set binlog_format=row  
maxwell1.18
centos7.4

WARN  BinlogConnectorReplicator - Unhandled QueryEvent inside transaction: QueryEventData{threadId=11720519, executionTime=0, errorCode=0, database='lala89', sql='update `InitialTagJobs` set `status` = 3 where `id` in (-1)'}

**Comment by osheroff** [comment]
generally this means that you had a client connected that didn't pick up the `binlog_format=row` change -- for everything to go into row format all clients must reconnect to the mysql server.
