### ISSUE TITLE
How can I change Json Format?

### ISSUE THREAD

**Issue by Mehdiyadollahi** [zendesk/maxwell#1157]
Hi, 
I want to customize the json format of the messages that are produced in kafka. How can I change its format? Does changing the  "toJSON" method in "RowMap" class help me?

The structure of json that mentioned in README :
```
 maxwell: {
    "database": "test",
    "table": "maxwell",
    "type": "insert",
    "ts": 1449786310,
    "xid": 940752,
    "commit": true,
    "data": { "id":1, "daemon": "Stanislaw Lem" }
  }
```

The structure of json that I want to produce in kafka:
```
{
   "id":1, 
   "daemon": "Stanislaw Lem"
 }
```

**Comment by osheroff** [comment]
you could change the `toJSON` method, you could also implement a custom producer as described here: http://maxwells-daemon.io/producers/#custom-producer
