### ISSUE TITLE
why not allow easy change json format?

### ISSUE THREAD

**Issue by tkaven** [zendesk/maxwell#1163]
Why not open the modification of the protection variable? In this case, you can easily change the data level in the filter.

#1157 

at code RowMap.java line 401

**Comment by osheroff** [comment]
sorry, what exactly are you trying to accomplish?

**Comment by tkaven** [comment]
> sorry, what exactly are you trying to accomplish?

if it open, so i can change the data level in filter, such as prefixing data field names flattening, this eliminates the need to retrieve data twice in json object. I use KSQL directly, the intermediate process has not gone through code development,  so i can save a lot of ksql steps, can also reduce the creation of many kafka topic.

**Comment by osheroff** [comment]
RowMap.java line 401 doesn't really refer to much.  

The only way I could see to *really* make this easy would be to pass a fully formed JSON object into the javascript filters.  This approach would slow maxwell down quite a bit, as the code to generate a JSON string is the most performance sensitive code in maxwell.

If there's a very easy fix that's not too big of a deal and lets you do what you want, open up a PR.  I'm not sure if there is one though.
