### ISSUE TITLE
Unhandled QueryEvent @ master-bin.000029:242025806 inside transaction

### ISSUE THREAD

**Issue by changyuxin** [zendesk/maxwell#1164]
`BinlogConnectorReplicator - Unhandled QueryEvent @ master-bin.000029:242025806 inside transaction: QueryEventData{threadId=386, executionTime=0, errorCode=0, database='mociresync', sql='update mcrp_doc_index set PATIENT_ID = 'JH181112172633924', HOSPITAL_NO = '40068980X4', VISIT_TYPE = '1', VISIT_ID = '181122162356247', VISIT_DATE_TIME = '2017-04-11 00:00:00', DATA_RESOURCE = 2, REPORT_TYPE = '4', FILE_TYPE = '2', EXIST_FLAG = 1, IMAGE_FILE_IS_EXIST = 0, DOC_ROWKEY = 'docrowkey/f436ecddee2f11e88ed1005056ac3223/181122162356348', REQ_PHYSICIAN = null, CREATE_BY = 'de6a3e07eba111e79a00005056ac3223', CREATE_DATE = '2018-11-22 16:23:56', UPDATE_DATE = '2018-11-22 16:23:56', IMAGE_ACC_NO = null, REPORT_CLASS = '其他', REPORT_NO = null, REPORT_DATE_TIME = '2017-04-11 00:00:00', LIB_DATE_TIME = null, PART_FIRST_CLASS_CODE = null, RESOURCE_FALG = 2, CLINIC_DIAGNOSIS = null, SAMPLE_TIME = null, PERFORMED_DOCTOR_NAME = null, BEDLABEL = null, VERIFIED_BY = null, SPCM_RECEIVED_DATE_TIME = null, CLIN_SYMP = null, REPORT_DOCTOR_NAME = null, DISTRICT = null, BRANCH_ALIAS = null, ORDERING_DEPT = null, REQ_DEPT = null, KDSJ = null, MANUFACTURER_FLAG = null, EXAM_METHOD_NAME = null, SERIAL_NO = null, SAMPLE_NURSE_NAME = null, LAB_PERFORMED_TIME = null, MSR_NO = null, APP_CODE = '40068980X4_1', AUDIT_TIME = '2018-11-23 06:23:55', AUDIT_STATUS = 2 where ID = 'f436ecddee2f11e88ed1005056ac3223''}`

**Comment by osheroff** [comment]
hi, this means that there's still some statement-based binlogs.  Often this is caused by a client that hasn't yet disconnected and reconnected after you turn on ROW based binlogs.
