### ISSUE TITLE
Missing support for 'BIT' datatype

### ISSUE THREAD

**Issue by aquarapid** [zendesk/maxwell#117]
Probably somewhat unusual, but there's no BIT datatype support:

https://dev.mysql.com/doc/refman/5.6/en/bit-type.html

```
00:13:15,085 INFO  Maxwell - Maxwell is capturing initial schema
00:13:15,086 DEBUG SchemaStore - Capturing schema
java.lang.IllegalArgumentException: unsupported column type bit
       at com.zendesk.maxwell.schema.columndef.ColumnDef.build(ColumnDef.java:83)
```

**Comment by osheroff** [comment]
ah!  Yeah.  I will look into adding support for the `bit` type, it should be a pretty easy fix.

**Comment by jairamc** [comment]
Facing the exact same issue here. I am using [liquibase](http://www.liquibase.org/) and it creates its own tables that use `bit` fields. Is there a way I can exclude certain tables? Any one using [liquibase](http://www.liquibase.org/) is going to face this issue by the way.

**Comment by jairamc** [comment]
Ah, just realised https://github.com/zendesk/maxwell/pull/121 fixes this. Will give the new version a try.

**Comment by osheroff** [comment]
@jairamc released https://github.com/zendesk/maxwell/releases/tag/v0.12.0 with BIT support.
