### ISSUE TITLE
how to configuration when metrics_type=jmx

### ISSUE THREAD

**Issue by liuxgui** [zendesk/maxwell#1180]
with the document [http://maxwells-daemon.io/monitoring/#jmx-configuration] ,i decide to try the way of jmx ,but i can not find a example.then i use the following configuration :

export JAVA_OPTS="-Dcom.sun.management.jmxremote \
-Dcom.sun.management.jmxremote.port=9010 \
-Dcom.sun.management.jmxremote.local.only=false \
-Dcom.sun.management.jmxremote.authenticate=false \
-Dcom.sun.management.jmxremote.ssl=false \
-Djava.rmi.server.hostname=node02"

./maxwell 
--user='maxwell' 
--password='root' 
--host='127.0.0.1' 
--producer=kafka  
--kafka.bootstrap.servers=192.168.33.163:9092  
--kafka_topic=test4 
--replication_host=192.168.33.161 
--replication_user=root 
--replication_password=root 
--replication_port=3306 
--metrics_type=jmx
--metrics_jvm=true 
--http_bind_address=192.168.33.162 
--http_port=8091 
--http_path_prefix=db_test_maxwell 
--client_id=maxwell_16113 
--replica_server_id=16113

it is up and running ok . but then what to do.

**Comment by osheroff** [comment]
well, then you'll want to use a program that collects the JMX metrics.  google "jmx console" or "jmx collector".
