### ISSUE TITLE
Prevent maxwell binlog position getting updated when kafka is down

### ISSUE THREAD

**Issue by akulgoel96** [zendesk/maxwell#1181]
We wanted to test certain failover scenarios while pushing binlog events from Maxwell to Kafka. We tried this experiment:

1. Start Kafka.
2. Start Maxwell. (Binlog streaming happening successfully)
3. Stop Kafka. (This is what we want to test)

The problem that we're facing is that when Kafka is down, Maxwell keeps updating `maxwell.positions` and that is something we totally want to avoid. It is ok if Maxwell keeps re-trying pushing the same event to Kafka and waits until Kafka is back up but we don't want the positions to get updated.

Is this expected ? Is there a solution around this problem ?

Note: I'm aware of `ignore_producer_error=false` but would prefer the flow described above.

@osheroff

**Comment by osheroff** [comment]
I think if you configure `kafka.retries` (and maybe `delivery.timeout.ms` in newer kafka versions?) to something very very large you will basically stall out maxwell until Kafka comes back up -- without advancing the position and moving on. 

It looks like before 03c934e18847559d6e64561f8208281683bb72e8 I thought that the correct solution was to throw a runtime-error in any case except record-too-large exceptions.  Now I'm really not sure of the correct default behavior; we have all these configuration flags of what to do in various scenarios, but none of them really make all that much sense. 

@liulikun @timbertson I know you've been dealing with some of this of late, any opinions?   I'd at least say we should jam a sane retry value (3?) into the maxwell config.  the rest of it... dunno.

**Comment by timbertson-zd** [comment]
Yeah, what @osheroff said should work. What don't you like about `ignore_produced_error=false`? You do get some noise from all the restarting, but is that why you dislike it, or are there other reasons?

The main issue with your suggested approach is that the kafka client could be in a bad state, in which case a retry won't work but a crash+restart will. It could be that this was only an issue with old kafka versions and it'll never happen again, so maybe the super-large timeout is enough for you. I'd still recommend `ignore_produced_error=false` if you care about this though.

@osheroff do we already have defaults?
If so, I'd be happy to add/change the retries one to something reasonable.
But if not, I'd be fine to keep out of the business of specifying defaults - it's pretty well known that you shouldn't just use kafka's defaults, adding a layer of defaults might be more confusing than helpful.

**Comment by osheroff** [comment]
It'd be good if we could be a bit smarter about the type of errors we got: If the error is message-too-large, yes, eat the record and continue.  On the other hand, it's *rarely* correct to say "oh, kafka is down.  let's just ignore the error and continue."  I mean in some rare situations it might be (database as udp, anyone?), but largely this is not what people want.  I'm not sure how we came down this road (I suspect it's my fault), but either always-crashing or always-retrying seems quite a lot saner of default behaviors than simply eating the message.

@timbertson we don't have any defaults that get set in code, but we do have them uncommented in `config.properties.example`: we set `kafka.retries = 0`.  

I think we should probably setup a decent value for retries in config.properties.example (and maybe in code) and then set ignore_produced_error to true by default.

**Comment by osheroff** [comment]
> either always-crashing or always-retrying seems quite a lot saner of default behaviors than simply eating the message.

And to clarify, this is in the cases where it's *not* just message-too-big.

**Comment by timbertson-zd** [comment]
> I think we should probably setup a decent value for retries in config.properties.example (and maybe in code) and then set ignore_produced_error to true by default.

Yep, I agree. The only trouble is that's a breaking change, since people could be relying on the current behaviour, and they _could_ get stuck in a crash-loop with the new default, or get into trouble if restarting maxwell is expensive in their setup. That's the only we defaulted `ignore_producer_error` to `false` when we added it.
