### ISSUE TITLE
I only change a little fields,but kafka return all  fields of table

### ISSUE THREAD

**Issue by programmer-luxw** [zendesk/maxwell#1182]
On lastest version,quick start with Docker,I only change a little fields,but kafka return all  fields of table。 Is it wrong?
e.g. {
    "database": "test",
    "table": "bill",
    "type": "update",
    "ts": 1545800753,
    "xid": 905,
    "commit": true,
    "data": {
        "id": 73,
        "statement": "20160419-4-3877/abc",
        "user_id": 77,
        "user_type": 1,
        "bill_start": "2016-04-20",
        "bill_end": "2016-04-20",
        "total_amount": "1",
        "due_date": "2016-04-05",
        "timezone": "America/Belize",
        "status": 8,
        ...(all field of table)
    
    },
    "old": {
        "user_id": 55,
        "user_type": 2,
        "status": 1
    }
}

**Comment by osheroff** [comment]
no, this is working as expected.
