### ISSUE TITLE
Not able to get proper data for decimal type from MySQL to maxwell output

### ISSUE THREAD

**Issue by bhavinrshah** [zendesk/maxwell#1183]
In our MySQL, one of the columns is set with decimal data type with (18, 6) so the total length is 18 digit and including 6 digits as precision.
While getting the data from Maxwell, we are not getting proper data. If data is with 18 digits then Maxwell gives garbage data instead of proper data. If data is with 12 digits then Maxwell works fine and gives proper data,
Do we have to make changes in any settings to work properly?

**Comment by bhavinrshah** [comment]
@osheroff : Following are examples.
1. 999999999999.999998
2. 999999999999.999999
3. 99999999999.999998

Above examples converts to int(1000000000000) instead of keeping same data. We have set the Kinesis as the output of data and getting the data as an encrypted format so while decrypting data, it gives to int(1000000000000). We are using Python code to decrypt the data.

**Comment by osheroff** [comment]
```
mysql> create table foo2 ( d decimal(18, 6) );
Query OK, 0 rows affected (0.03 sec)

mysql> insert into foo2 set d = 999999999999.999998;
Query OK, 1 row affected (0.04 sec)

mysql> insert into foo2 set d = 999999999999.999999;
Query OK, 1 row affected (0.01 sec)

table foo2 ( d decimal(18, 6) )" to test, new schema id is 3
{"database":"test","table":"foo2","type":"insert","ts":1546814015,"xid":713,"commit":true,"data":{"d":999999999999.999998}}
{"database":"test","table":"foo2","type":"insert","ts":1546814026,"xid":731,"commit":true,"data":{"d":999999999999.999999}}
```

maxwell seems ok to me.  maybe check your python library?  In theory I suppose encryption could be corrupting this too.  But I'd at least want to see the decrypted JSON before your python gets at it.

**Comment by osheroff** [comment]
feel free to reopen with more information.
