### ISSUE TITLE
Two maxwell instances, the binlog file and position for one of the instances is not moving

### ISSUE THREAD

**Issue by amrishkmr** [zendesk/maxwell#1184]
Hi,
I am trying to run two instances on Maxwell against a single master. I am using a different client_id as instructed in the documentation. When I start the second instance it runs for a while and then the postion (binlog file and binlog_position) doesn't move. I seems to be stuck due to some reason. The heartbeat is running fine and there is no exception in the log file.
Maxwell version is 1.17.
Any help would be much appreciated.
Thanks,
Amrish

**Comment by osheroff** [comment]
hi, curious to know what the problem was.

**Comment by amrishkmr** [comment]
Apologies for the false alarm! Nothing related to Maxwell. There was a configuration issue in custom-producer(written with http-client) which was causing the issue. There was no error in the logs and from the symptom, it appeared as if the running Maxwell might be interfering.
