### ISSUE TITLE
Migrating to a new replication host (Couldn't find database foo)

### ISSUE THREAD

**Issue by drfloob** [zendesk/maxwell#1187]
I have a single-master/multi-slave MySQL setup, and need to teach a running Maxwell instance to read binlog data from a new slave, same place it left off on the previous slave. The error that Maxwell produces is `Couldn't find database foo`. I've checked my grants, and have logged in from various machines to ensure the grants allow my db user to select from db foo (`USE foo; SELECT * from foo.bar;`). Replication permissions are identical too, all permissions match those on the previous db slave. I don't think it's related to permissions.

The slave db servers are not completely identical, the new server has a few new databases, and is missing a few others the previous slave had. However, the database I'm listening to (foo) is present and identical. My filter is `filter= exclude: *.*, include: foo.*`. I know this is applied on the producer side, not the binlog consumer side, so maybe maxwell is crashing when it sees some schema it doesn't expect?

Any other insights into why this might be failing? And how I can fix it without losing position / restarting from current binlog position?

```
java.lang.RuntimeException: Couldn't find database foo
        at com.zendesk.maxwell.replication.TableCache.processEvent(TableCache.java:23) ~[maxwell-1.17.1.jar:1.17.1]
        at com.zendesk.maxwell.replication.BinlogConnectorReplicator.getTransactionRows(BinlogConnectorReplicator.java:396) ~[maxwell-1.17.1.jar:1.17.1]
        at com.zendesk.maxwell.replication.BinlogConnectorReplicator.getRow(BinlogConnectorReplicator.java:490) ~[maxwell-1.17.1.jar:1.17.1]
        at com.zendesk.maxwell.replication.BinlogConnectorReplicator.work(BinlogConnectorReplicator.java:150) ~[maxwell-1.17.1.jar:1.17.1]
        at com.zendesk.maxwell.util.RunLoopProcess.runLoop(RunLoopProcess.java:27) ~[maxwell-1.17.1.jar:1.17.1]
        at com.zendesk.maxwell.Maxwell.startInner(Maxwell.java:224) ~[maxwell-1.17.1.jar:1.17.1]
        at com.zendesk.maxwell.Maxwell.start(Maxwell.java:156) ~[maxwell-1.17.1.jar:1.17.1]
        at com.zendesk.maxwell.Maxwell.main(Maxwell.java:245) ~[maxwell-1.17.1.jar:1.17.1]
```

**Comment by osheroff** [comment]
hmm.  what's the output of: 

```
 select * from maxwell.databases where name = 'foo';
```

on the new server?  Could there be case sensitivity differences?

And just to be clear: when you say `foo`, it refers to the same database everywhere in the issue you opened, yes?

**Comment by drfloob** [comment]
@osheroff  good question. The MySQL server that stores the `maxwell` db is separate, and did not change. I'm using both `host` and `replication_host` config entries, and only `replication_host` changed.

Regardless, this is the (sanitized) output, same maxwell db on the same server (`host` field) it was previously:

```
 select * from maxwell.databases where name = "inDB";
+----+-----------+------+---------+
| id | schema_id | name | charset |
+----+-----------+------+---------+
|  3 |         1 | foo  | latin1  |
+----+-----------+------+---------+
1 row in set (0.00 sec)
```

**Comment by osheroff** [comment]
it's odd to me that people need to sanitize the names of their databases.  I assume that the capitAliZation of `foo` in the error message matches the one in `maxwell.databases`?

The other question I have here: you say 

> and need to teach a running Maxwell instance to read binlog data from a new slave, same place it left off on the previous slave.

how are you getting the position on the new slave?  Can you do a `SHOW BINLOG EVENTS IN '{file}' from {pos} LIMIT 1` on the new server at the position you're starting up at?

**Comment by drfloob** [comment]
Thank you. Sanitization is mostly CYA 😬 . 

That query doesn't make any sense on the new server, using the old server's binlog position information taken from `maxwell.positions`. That's the problem, right? Different slave servers have different binlog files and positions, so maxwell can't pick up where it left off. I assumed since both slaves read from the same master DB, maxwell reading from either slave would track to the top-tier master's binlog position.

```
       +----------+                           +----------+
       |          |                           |          |
       |  master  |                           |  master  |
       |          |                           |          |
       +-+------+-+                           +-+------+-+
         ^      ^                               ^      ^
         |      |            --TO--             |      |
+--------++    ++--------+             +--------++    ++--------+
|         |    |         |             |         |    |         |
| slave 1 |    | slave 2 |             | slave 1 |    | slave 2 |
|         |    |         |             |         |    |         |
+------+--+    +---------+             +---------+    +-+-------+
       |                                                |
       |                                                |
  +----+-----+                                    +-----+----+
  |          |                                    |          |
  | maxwell  |                                    | maxwell  |
  |          |                                    |          |
  +----------+                                    +----------+
```

It seems like it won't be possible to seamlessly migrate maxwell from one slave db to the other. Any ideas how that might be done?

Aside: I still can't make sense of the error in the logs "Could not find database". It seems like Maxwell started tracking the new DB position separately within the same DB. More info:

```
> select * from maxwell.positions;
+-----------+------------------+-----------------+----------+---------------------------+--------------+---------------------+
| server_id | binlog_file      | binlog_position | gtid_set | client_id                 | heartbeat_at | last_heartbeat_read |
+-----------+------------------+-----------------+----------+---------------------------+--------------+---------------------+
|         1 | mysql-bin.000XYZ |           12345 | NULL     |            maxwell_reader |         NULL |                   0 |
|         2 | mysql-bin.000ABC |           67890 | NULL     |            maxwell_reader |         NULL |                   0 |
+-----------+------------------+-----------------+----------+---------------------------+--------------+---------------------+
```

**Comment by osheroff** [comment]
>  It seems like it won't be possible to seamlessly migrate maxwell from one slave db to the other. Any ideas how that might be done?

There's support for this when promoting a new master, but not when flipping slave-to-slave like this.  It *is* possible; if you can find corresponding positions between the old slave and new slave, you can do like:

1.  stop maxwell on slave a.
2. find the position on slave b that matches this.
3.  insert into maxwell.positions with the server_id, file/position/etc
4.  make sure there's an entry in maxwell.schemas that corresponds too.

> Aside: I still can't make sense of the error in the logs "Could not find database"

At first I was thinking that maybe you had manually pointed maxwell at the new slave and screwed up there somehow.  Now I'm thinking that maybe there was an old schema lying around for the new replica and maxwell is using that.  What's the output of `select * from maxwell.schemas`?

**Comment by drfloob** [comment]
Sorry for the delay @osheroff . I just ran the query, and it's going to be pretty hard to obfuscate it. There are 14 records, 13 tagged with the previous server_id, one with the new server_id. The one tagged with the new server id, oddly, has its `base_schema_id = NULL`, unlike the others; `deltas = NULL` as well.

I'm happy to close this ticket, it's not a maxwell bug. I can keep digging if you'd like, it probably wouldn't be too difficult to dockerize a similar setup.

**Comment by osheroff** [comment]
no, I mean there's something wrong with Maxwell in this scenario.  I'm happy to give you an email to pass the query to if you like.  If not, my question is:

What is the position of the schema with the new server_id?  Is it at a very old position?
