### ISSUE TITLE
Set as unhealthy when not able to find the next gtid

### ISSUE THREAD

**Issue by acampoh** [zendesk/maxwell#1189]
Hello!

We want to write a liveness check (k8s) in order to detect possible errors in maxwell and be able to restart it in case we get some errors. 

One of the most common cases (for us) is maxwell not being able to find the gtid-set in node it has connected. It would be great if this happens the **/healthcheck** endpoint reports maxwell is not in a healthy state, despite no errors sending messages happens (as no messages are sent, none can fail)

Thanks a lot!

**Comment by osheroff** [comment]
sorry, what do you mean exactly by "can't find the gtid-set"?  This is like, maxwell has connected to the wrong mysql server?  

What is the behavior of maxwell in this case?  We should probably just crash, which means that a healthcheck isn't hugely useful.

**Comment by acampoh** [comment]
yep, or if maxwell has been stuck / stopped for a long time enough to make the mysql server flush the binary log with the gtid maxwell has on the positions table.

Currently maxwell starts flooding the log with this messages

`15:47:51,390 INFO  BinaryLogClient - Connected to XXXX:3306 at a22fc3cc-2e9f-ee17-7310-bcc3f51b6cf4:1-5765250 (sid:6379, cid:9641693)
15:47:51,390 INFO  BinlogConnectorLifecycleListener - Binlog connected.
15:47:51,434 WARN  BinlogConnectorLifecycleListener - Communication failure.
com.github.shyiko.mysql.binlog.network.ServerException: The slave is connecting using CHANGE MASTER TO MASTER_AUTO_POSITION = 1, but the master has purged binary logs containing GTIDs that the slave requires.
	at com.github.shyiko.mysql.binlog.BinaryLogClient.listenForEventPackets(BinaryLogClient.java:882) [mysql-binlog-connector-java-0.16.1.jar:0.16.1]
	at com.github.shyiko.mysql.binlog.BinaryLogClient.connect(BinaryLogClient.java:559) [mysql-binlog-connector-java-0.16.1.jar:0.16.1]
	at com.github.shyiko.mysql.binlog.BinaryLogClient$7.run(BinaryLogClient.java:793) [mysql-binlog-connector-java-0.16.1.jar:0.16.1]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_181]
15:47:51,434 INFO  BinlogConnectorLifecycleListener - Binlog disconnected.
15:47:51,491 WARN  BinlogConnectorReplicator - replicator stopped at position: a22fc3cc-2e9f-ee17-7310-bcc3f51b6cf4:1-5765250 -- restarting` 

i think both approaches will be good as well. If maxwell crashes kubernetes will restart it, if the healthcheck returns "unhealthy", i can make k8s detect it and restart maxwell as well. I don't know which will be the best approach but for me both works perfectly

**Comment by osheroff** [comment]
it's certainly nonsensical to try to continue in this state.   Do you have time to do a PR around simply crashing out of these states?  It's a little deep/mucky but I could give you pointers. 

If not, I'm happy to get to it when I get the chance.

**Comment by acampoh** [comment]
Here is the PR.

https://github.com/zendesk/maxwell/pull/1190

Let me know if it looks OK to you,

Thanks!

**Comment by osheroff** [comment]
fixed in v1.19.6.  Thanks for the work @acampoh!
