### ISSUE TITLE
Use CP-1252 to decode latin1 instead of ISO-8859-1

### ISSUE THREAD

**Issue by borleaandrei** [zendesk/maxwell#1194]
I have a problem with maxwell's decoding. The database I am working with uses latin1 encoded with CP-1252 which is an extention of (ISO-8859-1) but when maxwell reads data from the database it  decodes it with ISO-8859-1, so all the extended list of characters from CP-1252 are **LOST**.
Wouldn't it be better if maxwell would decode latin1 with CP-1252 ? Having in mind that CP-1252 is the same as ISO-8859-1 only that it has a few more characters.

**Comment by osheroff** [comment]
yeah, after a trip through this issue it looks like you're correct.   Feel free to open a PR (with a test, please), otherwise I'll fix it when time permits.

**Comment by borleaandrei** [comment]
Ok. I opened a pr #1197

**Comment by osheroff** [comment]
fixed in v1.19.7
