### ISSUE TITLE
Way to bootstrap on launch?

### ISSUE THREAD

**Issue by rayjlinden** [zendesk/maxwell#1195]
In our development environment we are running mysql, Maxwell, kinesislite and elastic search - along with your service we wrote on top of all that!  docker-compose brings it all up.  One issue I have though is we have to "kick" Maxwell with the bootstrap process with some data that is in mysql during its start-up process.  It would be nice if I could tell Maxwell to boot-strap before the daemon starts.

I'd write the sql to do the bootstrap in our sql init code.  However, the tables do not exist until Maxwell starts for the first time.

Any idea how I can tell Maxwell to boot-strap data before Maxwell starts (or when it starts via options)?

**Comment by rayjlinden** [comment]
BTW, I tried creating the Maxwell database and Maxwell.bootstrap table before Maxwell starts - and inserting a row for the table I want boot-strapped.  However, Maxwell started normally but ignored that line in the table and never bootstrapped the table.  So that didn't work...

**Comment by osheroff** [comment]
how are you setting up the row for maxwell?  Maxwell does this on boot:

```
update `bootstrap` set started_at = NULL where is_complete = 0 and started_at is not NULL and client_id = ?";
```
which will trigger a bootstrap to start.

So I think the trick here is to insert a row with a non-null `started_at`.  Kinda goofy but there ya go.

**Comment by rayjlinden** [comment]
I was just doing this:
insert into maxwell.bootstrap (database_name, table_name) values ('mydb', 'mytable');

So you think setting started_at to say current time might work?

Well, I'll give that a shot and report back!

**Comment by rayjlinden** [comment]
It works!!  Not pretty - but it works!  A feature to start bootstrap on an initial setup of maxwell would still be nice.  But at least I'm good to go.
