### ISSUE TITLE
Schema deltas compaction

### ISSUE THREAD

**Issue by jakubkulhan** [zendesk/maxwell#1207]
We have Maxwell running against our staging database. Every night we drop all tables in the database, create again from current schema, and fill with sample data. This causes Maxwell to record quite a lot schema deltas. I've looked into the `maxwell` database and everything refers to `schema_id` `1` and then there's a lot of records in `schemas` table. As a consequence when Maxwell starts it has to replay all the deltas. This causes a lot of overhead and high memory usage.

I've seen that some optimization was done in #1080, so we've upgraded from 1.17.1 to latest version 1.19.7. However, this was to no effect. Memory usage and startup time stayed about the same.

Is there a way to compact schema deltas? If not, would you consider adding such feature (e.g. to commit schema version older than X days and remove older deltas)?

**Comment by osheroff** [comment]
yeah #1080 just deals with the held-in-memory expanded representation of the schema, not with deltas.

I would definitely at least take a patch to compact schemas.  are you offering to do dev work?  unclear from your message :)

**Comment by jakubkulhan** [comment]
@osheroff I'll try to take a look at it. Could you give me pointers how to approach the implementation and where to look in the source?

**Comment by osheroff** [comment]
start here:

https://github.com/zendesk/maxwell/blob/master/src/main/java/com/zendesk/maxwell/schema/MysqlSavedSchema.java#L147

in `saveDerivedSchema`.  

You've seen that Maxwell represents an evolving schema as a linked list, with the full capture at the head of the linked list and a series of deltas chaining off that.  The list is built by the schemas pointing backwards at a previous `baseSchemaID`.

The trick here would be that after the chain grows to N elements (or is N days old, whatever), we break the chain in the middle and nominate a new HEAD of the list.  

If I were implementing this I'd probably do something like this:

- somewhere in `saveDerivedSchema` check the length of the chain (or whatever measurement we're using the break the chain).  If we decide we want to compact the schema, we fire off a new thread.
- this thread restores a duplicate copy of the schema (hmmm, could be memory issues) and starts walking the chain.  When it detects it wants to compact at that point, it:

1.  does the equivalent of `saveSchema` - saves a full copy of the schema as it stands into the various tables. 
2.  removes the back pointer to the previous `base_schema_id`.
3.  lazily starts deleting the old schema.

Things to note:

- this schema will have both a full copy of the schema and a `delta`, will have to make sure that we process that correctly. 

if you decide to take it on, feel free to open PRs early and ask for whatever you need.

**Comment by osheroff** [comment]
we shipped some version of this
