### ISSUE TITLE
can maxwell parse sql with no strict model?

### ISSUE THREAD

**Issue by usernameisnull** [zendesk/maxwell#1213]
CREATE TABLE `table_name` (
  `id` int(10) unsigned NOT NULL AUTO_INCREMENT COMMENT '自增ID',
  `create_time` datetime NOT NULL DEFAULT '1970-01-01 00:00:00' '创建时间',
  `update_time` datetime NOT NULL DEFAULT '1970-01-01 00:00:00' ON UPDATE CURRENT_TIMESTAMP(0) COMMENT '修改时间',
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='some comment'

this sql can work on out mysql, we don't use strict model
but maxwell think this is wrong, and stuck
i have to delete the record in maxwell.positions

**Comment by usernameisnull** [comment]
maxwell think the `update_time` field's default value is illegal

**Comment by usernameisnull** [comment]
we use maxwell-1.19.2

**Comment by usernameisnull** [comment]
use jdbc options?

**Comment by usernameisnull** [comment]
the reason is 
``create_time` datetime NOT NULL DEFAULT '1970-01-01 00:00:00' '创建时间',` miss the `comment` key word
can create table in MySQL, successfully,but crashed the maxwell,so sad
some solutions？

**Comment by osheroff** [comment]
what version of mysql allows you to create a table like that?  just tested your SQL against 8.0 and it doesn't work...

**Comment by usernameisnull** [comment]
> what version of mysql allows you to create a table like that? just tested your SQL against 8.0 and it doesn't work...

5.6 and 5.7(no strict model)

**Comment by usernameisnull** [comment]
![910](https://user-images.githubusercontent.com/3390414/52869776-5f3ebc80-3181-11e9-9f89-cfdb7a941420.png)

**Comment by usernameisnull** [comment]
![086](https://user-images.githubusercontent.com/3390414/52869978-cfe5d900-3181-11e9-88ca-24c34360455d.png)

**Comment by osheroff** [comment]
fixed in 1.20.0
