### ISSUE TITLE
Dockerfile with config files

### ISSUE THREAD

**Issue by yosefrat** [zendesk/maxwell#1215]
I noticed it's not possible (or rather I'm doing something wrong) to run the dockerfile with a config file passed to it. I created another dockerfile locally to pass over the .conf files at build time then at run time this `CMD ["/bin/bash", "-c", "bin/maxwell --config=$MAXWELLCONF"]` so that a user can store multiple .conf files in a git repo then at run time identify the one to run. It's helped me keep multiple instances running in better order. Might be something worth considering, but I didn't want to send a PR because I'm not sure if you'd want to implement it the same way.

**Comment by osheroff** [comment]
Go ahead and open a pr
