### ISSUE TITLE
Why maxwell need SELECT privilege on *.*?

### ISSUE THREAD

**Issue by dbapower** [zendesk/maxwell#1229]
GRANT SELECT, REPLICATION CLIENT, REPLICATION SLAVE ON *.*

if only have the REPLICATION CLIENT, REPLICATION SLAVE ON *.*
maxwell will report: Couldn't find database xxx

**Comment by osheroff** [comment]
Maxwell needs to capture schema from the `information_schema` database, and therefore needs "some" privelege to all databases and tables:  see https://dev.mysql.com/doc/refman/8.0/en/information-schema-introduction.html.

**Comment by dbapower** [comment]
Thanks for the reply!~
