### ISSUE TITLE
Maxwell and MySQL 8

### ISSUE THREAD

**Issue by garyrussell** [zendesk/maxwell#1232]
```
$ brew info maxwell
maxwell: stable 1.21.0
```
```
$ brew info mysql
mysql: stable 8.0.15 (bottled)
```

What I had to do to get it working...

**my.cnf**
```
server_id=1
log-bin=master
binlog_format=row
default-authentication-plugin=mysql_native_password
```

and

```
CREATE USER 'maxwell'@'localhost' IDENTIFIED WITH 'mysql_native_password' AS 'XXXXXX';
```

Perhaps add a note to the quick start?

**Comment by osheroff** [comment]
can do.  I thought we addressed some of this with the upgrade of the jdbc lib, but I guess not.

**Comment by osheroff** [comment]
I guess I never added a note.  but 1.26.0 finally supports newer auth methods.
