### ISSUE TITLE
Releases after v1.19.7 doesn't have Docker image

### ISSUE THREAD

**Issue by pasali** [zendesk/maxwell#1236]
I think there is something wrong with publishing docker images. Last image is v1.19.7 and published 2 months ago.

**Comment by osheroff** [comment]
@timbertson can someone inside zendesk take a look at this?  I don't have perms to the docker hub stuff anymore.

**Comment by timbertson-zd** [comment]
:+1: will do

**Comment by timbertson-zd** [comment]
Looks like the github service was deprecated and turned off a couple months back, we'll need to replace it with https://docs.docker.com/docker-hub/builds/link-source/

**Comment by osheroff** [comment]
yeah and that you want to create a very limited-perms user for them..

**Comment by pasali** [comment]
@timbertson-zd  any ETA ?

**Comment by timbertson-zd** [comment]
Might be a week or two I'm afraid, there's a bit of back & forth across timezones to figure out what settings / webhooks aren't working right.

**Comment by timbertson-zd** [comment]
Good news! The webhook fairies have blessed us, and it's building once again. I've pushed a few duplicate tags (e.g. `v1.20.0.0` is identical to `v1.20.0`) to kick it into action:

https://hub.docker.com/r/zendesk/maxwell/tags/

Thanks for reporting, @pasali

**Comment by pasali** [comment]
@timbertson-zd thanks for quick fix!
