### ISSUE TITLE
filter.js don't work with '&&' option

### ISSUE THREAD

**Issue by AnthonyMRodrigues** [zendesk/maxwell#1255]
Hi.
First of all, awesome project, very helpful.
I'm currently working with maxwell in AWS ECS.
ECS only use volume files with alphanumeric characters, hyphens, and underscores, so config.properties don't work.
Because of that I'll have to use javascript filter.
But I only need that maxwell to send events when is a specific type and table, so in filter.js I did:
`function process_row(row) {
    if ( row.table !== "table_name" && row.type !== "insert" ) {
           row.suppress();
    }
}
`
With this file, maxwell is sending all records, but if I do:
`function process_row(row) {
    if ( row.table !== "table_name" ) {
           row.suppress();
    }
    if (row.type !== "insert") {
        row.suppress();
    }
}
`
Then works.
Any idea why this happens??

**Comment by osheroff** [comment]
took me a second, but your logic is wrong.  you probably mean:

```
 if ( !(row.table == "table_name" && row.type == "insert") ) {
  row.suppress();
 } 
```
