### ISSUE TITLE
prevent text, blob and json

### ISSUE THREAD

**Issue by pjebs** [zendesk/maxwell#1257]
To reduce the load, is it possible (as a setting) to prevent blob, text and json from getting transmitted when a change is detected?

**Comment by nyilmaz** [comment]
It is possible with [filtering](http://maxwells-daemon.io/filtering/). Jump to "Column Filtering"

**Comment by pjebs** [comment]
i think I want to detect that a field has changed, but not transmit the change when it is detected.

**Comment by osheroff** [comment]
You can look into a javascript filter to try to do what you want, I'm not sure exactly the behavior you desire, but it looks far too specific to belong in master.
