### ISSUE TITLE
Bootstrapping when Maxwell host and the replication host are different

### ISSUE THREAD

**Issue by jddionappdirect** [zendesk/maxwell#1259]
In the Maxwell changelog for the version v1.22.0 it is written :

"Bootstrapping has been reworked and is now available in all setups, **including those in which the maxwell store is split from the replicator.**"

But when I try to bootstrap with different values for the "host" and the "replication_host" configuration fields,  I got this warning message :

19:02:36,055 WARN  MaxwellConfig - disabling bootstrapping; not available when using a separate replication host.

When you look in src/main/java/com/zendesk/maxwell/MaxwellConfig.java:728 the validation is still present.

Does Maxwell support bootstrap when the host and the replication host are different ?

Thank you

**Comment by pjebs** [comment]
Might be related to this: https://github.com/zendesk/maxwell/issues/645

**Comment by liuxgui** [comment]
As i konw,it`s still can`t support it.

**Comment by osheroff** [comment]
fixed in 1.22.1, thanks for the heads up
