### ISSUE TITLE
Bootstrap initial database into kafka

### ISSUE THREAD

**Issue by bbnsumanth** [zendesk/maxwell#126]
Can we use this to do a Mysql db dump to a kafka topic.

**Comment by osheroff** [comment]
not directly -- currently Maxwell only tracks binlog events, ie it tracks inserts/updates/deletes, not the data as it stands. 

You can do a mysqldump/import into a new master with maxwell connected, and that will get your data into kafka, but it won't track ongoing updates.  I'll definitely be looking into some kind of solution for this problem in the future, but can't say precisely when.

**Comment by osheroff** [comment]
This has been addressed in v1.0.0-PRE1
