### ISSUE TITLE
change filters live

### ISSUE THREAD

**Issue by pjebs** [zendesk/maxwell#1261]
Is there a way to change the filters dynamically. The docs seem to suggest it is done via a command line.

**Comment by osheroff** [comment]
no, there currently is no way to change any configuration in runtime; the accepted way to do it is to change the configuration and restart maxwell.

**Comment by pjebs** [comment]
will maxwell properly detect the changes that have occurred whilst it was restarting?

**Comment by osheroff** [comment]
yes.
