### ISSUE TITLE
mysql8.0.13 get Public Key Retrieval is not alloweds error

### ISSUE THREAD

**Issue by liuxgui** [zendesk/maxwell#1263]
I use mysql8 to store the maxwell data,But the process get error.
The error message like this :
**Could not connect to jdbc:mysql://X.X.X.249:3306?connectTimeout=5000&zeroDateTimeBehavior=convertToNull&useSSL=false&characterEncoding=UTF-8&tinyInt1isBit=false: Public Key Retrieval is not alloweds**
Then i search it online ,And lots of people suggest that with mysql8.x version,we need to add the  config "allowPublicKeyRetrieval=true".But i can not find that maxwell has this configuration,so i just want to know how do i to solve it？

**Comment by osheroff** [comment]
You can try passing "allowpublickey..." through the "jdbc_options" flag.  Not totally sure that that will fix it.

**Comment by liuxgui** [comment]
the problem was resolved.
one method is i add this code in MaxwellMysqlConfig.java,and it is work:
   _this.jdbcOptions.put("allowPublicKeyRetrieval", "true");_
the other method is i put the "_jdbc_options=allowPublicKeyRetrieval=true_" in the  configuration with your suggestion,and it is ok.
So i think it`s best to use the configuration with "_jdbc_options".And so thanks for your help @osheroff .
