### ISSUE TITLE
How can Maxwell achieve high availability

### ISSUE THREAD

**Issue by sixsixsix516** [zendesk/maxwell#1264]
My question is what should I do if Maxwell becomes unavailable on my server for various reasons

Could someone help me? thanks

**Comment by osheroff** [comment]
Maxwell does not provide any HA "out of the box" -- generally you will want to solve this via other tools that provide HA: kubernetes, ec2 autoscaling, consul lock, etc, etc.... there's no "one" answer and it's always felt like too much to try to jam into maxwell itself.

**Comment by sixsixsix516** [comment]
> etc

I see what you mean. Thank you
