### ISSUE TITLE
how to  compile source  code  by  maven

### ISSUE THREAD

**Issue by newluhuibiao** [zendesk/maxwell#1268]
mvn   clean  compile  package  -Dmaven.test.skip=true , but  it's  wrong.

**Comment by huibioa89** [comment]
source version is :1.19.0

**Comment by jddionappdirect** [comment]
If your compile fail related to gpg, you can use the -Dgpg.skip=true flag.

**Comment by osheroff** [comment]
this is in "works for me" state.  maybe you have an old version of maven?  i'm on maven 3.6 and it works fine, but it's impossible to know without some error logs...

**Comment by huibioa89** [comment]
if  u  can compile  success,but what is  your  command?

**Comment by jddionappdirect** [comment]
Me, I used : mvn clean install -Dgpg.skip=true
