### ISSUE TITLE
mysql double quotes escaping fail

### ISSUE THREAD

**Issue by sablastik** [zendesk/maxwell#1271]
We are parsing mysql (v. 5.7) binlog. In one field can appear strings with escaped double quotes like this:
`"CollAddressText":"Жилой комплекс \"Некрасовский\""`
Maxwell encodes it to:
`"CollAddressText":"\xD0\x96\xD0\xB8\xD0\xBB\xD0\xBE\xD0\xB9 \xD0\xBA\xD0\xBE\xD0\xBC\xD0\xBF\xD0\xBB\xD0\xB5\xD0\xBA\xD1\x81 \x5C"\xD0\x9D\xD0\xB5\xD0\xBA\xD1\x80\xD0\xB0\xD1\x81\xD0\xBE\xD0\xB2\xD1\x81\xD0\xBA\xD0\xB8\xD0\xB9\x5C""`

Then in KSQL I try to create new stream & topic over maxwell topic.
If there I don't use column with double quotes in KSQL then JSON structure looks fine:
**print city__order_closed ;
Format:JSON
{"ROWTIME":1560594297608,"ROWKEY":"{\"database\":\"city\",\"table\":\"order_closed\",\"pk.id\":295646602}" ...**

But when I add column with double quotes then structure changes to String:
**print city__order_closed ;
Format:STRING
6/15/19 10:24:10 AM UTC , {"database":"city","table":"order_closed","pk.id":295623922} ...**

Also the topic itself created by Maxwell from binlog table with escaped double quotes takes String format:
**print 'maxwell.city.order_closed';
Format:STRING
6/15/19 10:36:34 AM UTC , {"database":"city","table":"order_closed","pk.id":295649098}, ...**

While topic from table without such quotes looks fine:
**print 'maxwell.city.order_price_calculations';
Format:JSON
{"ROWTIME":1560596287782,"ROWKEY":"{\"database\":\"city\",\"table\":\"order_price_calculations\",\"pk.id\":10124027250}", ...**

Is there any solution to handle such strings ?

**Comment by sablastik** [comment]
Seems like Maxwell should encode " as \x22 but failing at \"

**Comment by osheroff** [comment]
what is the encoding of the database column?

**Comment by millin** [comment]
> what is the encoding of the database column?

utf8

Looks like quotes are escaped in mysql bin log, but this not processed correctly.
Original db value is `Жилой комплекс "Некрасовский"`
