### ISSUE TITLE
usecase when bootstrapping is turned off

### ISSUE THREAD

**Issue by pjebs** [zendesk/maxwell#1279]
when maxwell's bootstrapping is turned off, **what does maxwell do**?

What does output look like for example in that scenario? When bootstrapping is complete, the output shows the diff (I assume)?

When no bootstrapping, **does it just show the actual change to the database row**?

This should be in docs.

**Comment by osheroff** [comment]
I don’t quite understand the question.

Maxwell always shows updates (inserts, updates, deletes) that you make to the database.  Bootstrapping is a feature that lets you output the entire current state of the database.  It doesn’t affect the default behavior of maxwell.

**Comment by pjebs** [comment]
What does bootstrapping do? I thought it was required for the diffs when something changes to the database.

**Comment by osheroff** [comment]
bootstrapping does a "select * from ..." on your database and outputs it into the stream
