### ISSUE TITLE
binlog本身是有序的，如果kafka的topic有多个partition，那么如何保证我写入的消息是有序的呢？

### ISSUE THREAD

**Issue by celestewang1026** [zendesk/maxwell#1289]
binlog本身是有序的，如果kafka的topic有多个partition，那么如何保证我写入的消息是有序的呢？

**Comment by xiaoshuaishuai** [comment]
1个topic多个分区，肯定保证不了有序性。
 我认为可以这样：

1. 1个topic1个分区，namespace_%{database}_%{table} 一个库下面的一个表对应一个topic，增加吞吐量
2. 业务层规避对有序性的依赖，监听到maxwell的消息之后去查db，以db表中的数据为准，不要依赖于maxwell mq中的数据为最新数据

**Comment by liquidgenius** [comment]
Question: 

> Binlog itself is ordered. If kafka's topic has multiple partitions, how can I ensure that the messages I write are ordered?

Response: 
> 1 topic multiple partitions, certainly can not guarantee the order.
> I think it can be like this:
> 
> 1 topic1 partition, namespace_%{database}_%{table} A table below a library corresponds to a topic, increasing throughput
> The business layer evades the dependency on the order. After listening to the maxwell message, check the db. The data in the db table is used. Do not rely on the data in the maxwell mq as the latest data.

**Comment by osheroff** [comment]
i have no idea what's happening in this issue, feel free to re-open if your question wasn't answered.

**Comment by chengcxy** [comment]
> binlog本身是有序的，如果kafka的topic有多个partition，那么如何保证我写入的消息是有序的呢？

每一条记录都存下来 后面一个merge任务 根据主键id 分区id offset 为联合索引去重
