### ISSUE TITLE
table bootstrap where_clause field type varchar(255) is too short

### ISSUE THREAD

**Issue by tkaven** [zendesk/maxwell#1291]
> CREATE TABLE `bootstrap` (
>  `id` int(10) unsigned NOT NULL AUTO_INCREMENT,
>  `database_name` varchar(255) NOT NULL,
>  `table_name` varchar(255) NOT NULL,
>  `where_clause` varchar(255) DEFAULT NULL,
>  `is_complete` tinyint(1) unsigned NOT NULL DEFAULT '0',
>  `inserted_rows` bigint(20) unsigned NOT NULL DEFAULT '0',
>  `total_rows` bigint(20) unsigned NOT NULL DEFAULT '0',
>  `created_at` datetime DEFAULT NULL,
>  `started_at` datetime DEFAULT NULL,
>  `completed_at` datetime DEFAULT NULL,
>  `binlog_file` varchar(255) DEFAULT NULL,
>  `binlog_position` int(10) unsigned DEFAULT '0',
>  `client_id` varchar(255) CHARACTER SET latin1 NOT NULL DEFAULT 'maxwell',
>  PRIMARY KEY (`id`)
> ) ENGINE=InnoDB AUTO_INCREMENT=733 DEFAULT CHARSET=utf8

 > `where_clause` varchar(255) DEFAULT NULL,
is too short for long where sql

**Comment by osheroff** [comment]
feel free to submit a PR

**Comment by osheroff** [comment]
fixed around 1.23.3
