### ISSUE TITLE
Redis Producer Options

### ISSUE THREAD

**Issue by acrois** [zendesk/maxwell#1307]
Currently:
LPUSH
PUBLISH

Future:
XADD - As of July 23, [Jedis officially supports Redis streams](https://github.com/xetorthio/jedis/releases/tag/jedis-3.1.0). This means bumping dependency for Jedis to 3.1.0 from 2.9.0

Additional:
RPUSH - Same operation as LPUSH, different end of the list

I will provide PR after some time.

**Comment by osheroff** [comment]
PR merged
