### ISSUE TITLE
Underutilisation of memory

### ISSUE THREAD

**Issue by DPGrev** [zendesk/maxwell#1312]
I noticed that when running maxwell, we actually see an underutilization in terms of memory usage. Meaning that Maxwell defaults to writing to disk impacting the performance greatly whilst not fully using all the memory. 

I think the reason for this is two-fold:

1. `MAX_TX_ELEMENTS` is ignored, since the `shouldBuffer()` method is overridden:
https://github.com/zendesk/maxwell/blob/b1f0d1ced9fa3a3d10db3de8ba65e1b62960fe76/src/main/java/com/zendesk/maxwell/row/RowMapBuffer.java#L34-L37
Meaning that settings `MAX_TX_ELEMENTS` does not do anything:
https://github.com/zendesk/maxwell/blob/9c9aadfbd59aa49474cf1143ce27e4af727bb337/src/main/java/com/zendesk/maxwell/replication/BinlogConnectorReplicator.java#L441
https://github.com/zendesk/maxwell/blob/9c9aadfbd59aa49474cf1143ce27e4af727bb337/src/main/java/com/zendesk/maxwell/bootstrap/BootstrapController.java#L53

2. The memory utilized by RowMapBuffer is only 25% of the total memory available. As can be seen in: https://github.com/zendesk/maxwell/blob/b1f0d1ced9fa3a3d10db3de8ba65e1b62960fe76/src/main/java/com/zendesk/maxwell/row/RowMapBuffer.java#L18-L21

One of the solutions would be to make this configurable. So have a parameter in the config with default value 0.25. I would be more than willing to create this PR.

**Comment by DPGrev** [comment]
See PR #1318

**Comment by osheroff** [comment]
PR merged
