### ISSUE TITLE
最新版本

### ISSUE THREAD

**Issue by Rsyncc** [zendesk/maxwell#1321]
[root@szwpldb1080 ~]# cd /database/maxwell-1.22.3/
[root@szwpldb1080 maxwell-1.22.3]# cd bin/
[root@szwpldb1080 bin]# ./maxwell --user='maxwell' --password='XXXXXX' --host='127.0.0.1'    --producer=kafka --kafka.bootstrap.servers=localhost:9092 --kafka_topic=maxwell
Using kafka version: 1.0.0
Error: Could not find or load main class com.zendesk.maxwell.Maxwell

**Comment by Rsyncc** [comment]
[root@szwpldb1080 bin]# java -version
java version "1.8.0_221"
Java(TM) SE Runtime Environment (build 1.8.0_221-b11)
Java HotSpot(TM) 64-Bit Server VM (build 25.221-b11, mixed mode)
[root@szwpldb1080 bin]# echo $JAVA_HOME
/usr/java/jdk1.8.0_221/

**Comment by osheroff** [comment]
i can't reproduce this.  did you mess with the tarball directory somehow?

**Comment by Rsyncc** [comment]
I've solved ,thanks
