### ISSUE TITLE
Maxwell reads from binlog in bursts

### ISSUE THREAD

**Issue by utk-spartan** [zendesk/maxwell#1325]
We are trying to use maxwell for selective data replication by reading from binlog and pushing to kafka.
We are observing that maxwell is reading from binlog in bursts eg:
Runs normally for 30 mins
The input rate from replication host throttles down to less than 10% of actual traffic.
After 20 minutes all the accumulated records are read in one go
maxwell resumes normal operation.

Following is the grafana graph created using `row_meter_total` prometheus metric

![image](https://user-images.githubusercontent.com/11501282/63934925-09c16180-ca7a-11e9-8d9a-740c46f393f4.png)

The above graph seem to have no correlation with the traffic on replication host, or slow queries or long running open transactions.

This periodically repeats every hour.

In mysql processlist, maxwell thread will show `Master has sent all binlog to slave; waiting for binlog to be updated`.

Maxwell log (INFO level) shows nothing except the initial bootstrap logs

Following is the config file (removed values of hostname etc.)

```
replication_host=
replication_user=
replication_password=
replication_port=
host=
user=maxwell
password=
port=
schema_database=maxwell
kafka.bootstrap.servers=

producer=kafka
kafka_topic=internal_%{database}
javascript=./filter.js

log_level=info

metrics_type=http
metrics_prefix=maxwell_metrics
metrics_jvm=true
http_port=8080
http_diagnostic=true
http_diagnostic_timeout=10000

kafka.max.block.ms=604800000
kafka.retries=50
max.in.flight.requests.per.connection=1
kafka.request.timeout.ms=86400000

output_ddl=true
ddl_kafka_topic=internal_api

kafka.security.protocol=SSL
kafka.ssl.truststore.location=
kafka.ssl.truststore.password=
kafka.ssl.keystore.location=
kafka.ssl.keystore.password=
kafka.ssl.endpoint.identification.algorithm=
```

The mysql replication host is a RDS instance and configured as specified [here](http://maxwells-daemon.io/config/#deployment-scenarios)

**Comment by osheroff** [comment]
can you graph out the 'message.publish.time' and 'message.publish.age' metrics?

**Comment by utk-spartan** [comment]
Graph for `message.publish.age` for the time period
![image](https://user-images.githubusercontent.com/11501282/64082586-d8bd8700-cd2e-11e9-87a1-a1762271edf6.png)


for `message.publish.time`
![image](https://user-images.githubusercontent.com/11501282/64082580-cb080180-cd2e-11e9-9c18-995d730725b2.png)

**Comment by osheroff** [comment]
based on these graphs I *think* your kafka cluster is back-pressuring maxwell.   `message.publish.time` is the time between when maxwell hands off a message to the kafka producer and when the message is complete.  Notice how this shoots up hugely at :30, the same time at which maxwell's row counts drop to zero.  

My guess (and it's just a guess) is that if you sniffed around your kafka cluster you'd find its load shot up at half-past the hour as some periodic job elsewhere in the system fired off.

**Comment by utk-spartan** [comment]
Thanks, this was indeed caused by kafka, since there were large amount of consumers reading from kafka concurrently it was creating significant pressure on kafka which in turn was backpressuring maxwell.

Periodicity of the graph is because of how these consumers have their spark-kafka batch interval configured.

Reducing the kafka consumers and uniformly distributing them solved the issue.
