### ISSUE TITLE
How to add primary keys in JSON？

### ISSUE THREAD

**Issue by zhangxinjian123** [zendesk/maxwell#1326]
{"database":"zhang","table":"haow","type":"insert","ts":1555984612,"xid":90202,"commit":true,"data":{"id":7,"Name":"zhang","Age":19}}

{"database":"zhang","table":"haow","type":"delete","ts":1555984612,"xid":90202,"commit":true,"data":{"id":6,"Name":"zhang","Age":13,"code":13}}

{"database":"zhang","table":"haow","type":"update","ts":1555984612,"xid":90202,"commit":true,"data":{"id":10,"Name":"zhang","Age":90,"code":90}}
There are no primary keys in inserting and deleting updated jsons. How can table primary keys be added to these jsons?

**Comment by liquidgenius** [comment]
Please include —output_primary_keys=true —output_primary_keys_columns=true in your command line, or consider using the config.properties file with those parameters I commented and set to true.

**Comment by zhangxinjian123** [comment]
My Maxwell version is 1.22.4

bin/maxwell --user='root' --password='passwor' --host='192.168.0.13'--producer=kafka --kafka.bootstrap.servers=192.168.0.9:9092,192.168.0.10:9092,192.168.0.11:9092 --kafka_topic=maxwell --output_primary_keys=true --output_primary_keys_columns=true
Using kafka version: 1.0.0
joptsimple.UnrecognizedOptionException: output_primary_keys_columns is not a recognized option
	at joptsimple.OptionException.unrecognizedOption(OptionException.java:108)
	at joptsimple.OptionParser.handleLongOptionToken(OptionParser.java:449)
	at joptsimple.OptionParserState$2.handleArgument(OptionParserState.java:56)
	at joptsimple.OptionParser.parse(OptionParser.java:381)
	at com.zendesk.maxwell.MaxwellConfig.parse(MaxwellConfig.java:330)
	at com.zendesk.maxwell.MaxwellConfig.<init>(MaxwellConfig.java:149)
	at com.zendesk.maxwell.Maxwell.main(Maxwell.java:228)

**Comment by liquidgenius** [comment]
It should be:
--output_primary_key_columns=true 

Try:

bin/maxwell --user='root' --password='passwor' --host='192.168.0.13'--producer=kafka --kafka.bootstrap.servers=192.168.0.9:9092,192.168.0.10:9092,192.168.0.11:9092 --kafka_topic=maxwell --output_primary_keys=true --output_primary_key_columns=true

**Comment by osheroff** [comment]
answered here and in the other issue
