### ISSUE TITLE
allowPublicKeyRetrieval

### ISSUE THREAD

**Issue by RenlySir** [zendesk/maxwell#1333]
i run:docker run -it --rm zendesk/maxwell bin/maxwell --user='maxwell' --password='123456' --host='192.168.118.31'  --producer=stdout; then ERROR Maxwell - SQLException: Public Key Retrieval is not allowed;mysql is 8,i want to know how to do this

**Comment by osheroff** [comment]
v1.126.0 contains support for mysql 8's authentication mechanisms.
