### ISSUE TITLE
TableMetaTSDB

### ISSUE THREAD

**Issue by Bruce2jiang** [zendesk/maxwell#1334]
TableMetaTSDB  ，How did you deal with it?

**Comment by osheroff** [comment]
no idea what this means.

**Comment by Bruce2jiang** [comment]
How to deal with these three problem :
If the table structure A has increased the DDL operation of the column in the time period from T0 to T1, then when the binlog of the table A of the T0 time period is processed, the table structure obtained is the mirror of T1, and the column mismatch will occur. For example, the previous exception: column size is not match for table: xx , 12 vs 13

If the C1 column is added and the C2 column is deleted in T0~T1, the total number of columns obtained at this time is still the same as that of T0, but the corresponding column is misplaced.

If the DDL of the drop table occurs in T0~T1, there will be an exception that cannot be found when taking the table structure, and the entire binlog processing is blocked, such as not found [xx] in db

**Comment by Bruce2jiang** [comment]
@osheroff osheroff

**Comment by osheroff** [comment]
maxwell parses and processes DML (ALTER TABLE) statements and thus will always have a schema that matches the DML.
