### ISSUE TITLE
Maxwell database becomes large if you make lots of table creates

### ISSUE THREAD

**Issue by davidsheldon** [zendesk/maxwell#134]
In our app, there are a selection of tables (one per day), and they get created every minute or so. We have several servers, and they each create these tables using "CREATE ... IF NOT EXISTS". Normally this is fine, as it will do nothing in mysql. These DDL lines still get replicated, and maxwell parses them, and adds the 'new' table to the schema each time it is seen.

<pre>
> select count(*) from tables;
+----------+
| count(*) |
+----------+
|   386694 |
+----------+

> select count(distinct name) from tables;
+----------------------+
| count(distinct name) |
+----------------------+
|                  824 |
+----------------------+

</pre>

This is after running Maxwell for less than an hour.

**Comment by osheroff** [comment]
@davidsheldon let me know if you want to take on the work to handle no-op DDL statements properly, otherwise I knock it out.

**Comment by osheroff** [comment]
fixed in https://github.com/zendesk/maxwell/releases/tag/v0.13.0
