### ISSUE TITLE
how to support sqs?

### ISSUE THREAD

**Issue by dreamMonkeyZ** [zendesk/maxwell#1343]
i set producer with sqs； and param for sqs_queue_url  ，but i don't konw how to solve 403  fault that seems like autorization problem； what should i do ；

bin/maxwell --user='maxwell' --password='test123' --host='192.168.10.214' \
   --producer=sqs --sqs_queue_uri=https://sqs.us-east-1.amazonaws.com/517361610859/test-max     
Using kafka version: 1.0.0
15:01:12,540 WARN  MaxwellMetrics - Metrics will not be exposed: metricsReportingType not configured.
15:01:13,754 INFO  Maxwell - Maxwell v1.22.5 is booting (MaxwellSQSProducer), starting at Position[BinlogPosition[mysql-bin.000002:2049932], lastHeartbeat=1569308428773]
15:01:13,767 INFO  MysqlSavedSchema - Restoring schema id 1 (last modified at Position[BinlogPosition[mysql-bin.000001:4500], lastHeartbeat=0])
15:01:14,121 INFO  BinlogConnectorReplicator - Setting initial binlog pos to: mysql-bin.000002:2049932
15:01:14,215 INFO  BinaryLogClient - Connected to 192.168.10.214:3306 at mysql-bin.000002/2049932 (sid:6379, cid:74)
15:01:14,215 INFO  BinlogConnectorLifecycleListener - Binlog connected.

15:01:46,929 ERROR SQSCallback - AmazonSQSException @ Position[BinlogPosition[mysql-bin.000002:2054412], lastHeartbeat=1569308497873] -- 
15:01:46,929 ERROR SQSCallback - The security token included in the request is invalid. (Service: AmazonSQS; Status Code: 403; Error Code: InvalidClientTokenId; Request ID: 20155b1a-96a7-5480-a86a-0d19573d31b4)
15:01:46,929 ERROR SQSCallback - Exception during put
com.amazonaws.services.sqs.model.AmazonSQSException: The security token included in the request is invalid. (Service: AmazonSQS; Status Code: 403; Error Code: InvalidClientTokenId; Request ID: 20155b1a-96a7-5480-a86a-0d19573d31b4)

**Comment by osheroff** [comment]
SQS is supported, please see http://maxwells-daemon.io/producers/#sqs as well as amazon documentation for how to set up IAM permissions properly
