### ISSUE TITLE
Incomplete documentation for jdbc_options

### ISSUE THREAD

**Issue by ypereirareis** [zendesk/maxwell#1346]
Hi ! (and as always, thanks for maxwell :+1: )

Upgrading to maxwell 1.22.6 and mysql-connector-java to 8.0.17 I had this error.

```
SQLException: The server time zone value 'CEST' is unrecognized or represents more than one time zone.
You must configure either the server or JDBC driver (via the serverTimezone configuration property) to use a more specifc time zone value if you want to utilize time zone support.
```

So I added a new configuration to my maxwell instance :
```
jdbc_options=zeroDateTimeBehavior=convertToNull&connectTimeout=5000&serverTimezone=Europe/Paris
```

But still the same error after restarting Maxwell.

Actually, I **supposed** that the error message is exactly the same but not thrown from the same MySQL connection. Indeed, you can have many different sql connections (replicated database and maxwell positions database).

So looking for `jdbc_options` parsing in the code, I found: 

https://github.com/zendesk/maxwell/blob/fdad34ec464a91754d773cb828b9e5d9c2f29e5f/src/main/java/com/zendesk/maxwell/MaxwellConfig.java#L363-L365

So, I had to add all those configurations to get it working: 
```
jdbc_options=zeroDateTimeBehavior=convertToNull&connectTimeout=5000&serverTimezone=Europe/Paris
schema_jdbc_options=zeroDateTimeBehavior=convertToNull&connectTimeout=5000&serverTimezone=Europe/Paris
replication_jdbc_options=zeroDateTimeBehavior=convertToNull&connectTimeout=5000&serverTimezone=Europe/Paris
```

**Comment by propersam** [comment]
I alsobget dame error..but when i us

```
jdbc_options=serverTimeZone=UTC
```

It works fine for me

**Comment by FanAs** [comment]
I created a pull request for this: https://github.com/zendesk/maxwell/pull/1509

**Comment by osheroff** [comment]
merged the PR that fixes
