### ISSUE TITLE
handling bulk deletions

### ISSUE THREAD

**Issue by rredhatt** [zendesk/maxwell#1351]
Hi,

In a mysql/maxwell/kinesis setup what is the best way to omit deletions? On our end we have a daily process that archives transactions which are older than one year and we are omitting such deletions through maxwell's js filtering capabilities. It works fine, but we always noticed a delay in our streams when such archiving is being processed. 

Is there a better way to handle such scenario with Maxwell?

Mark

**Comment by osheroff** [comment]
can you collect some metrics from the maxwell node while its processing the deletions?  I'm wondering if it's fully CPU bound in the javascript, or whether it's spending time buffering the transaction to disk.  

Also, how many rows are deleted in one transaction?
