### ISSUE TITLE
Question: Different tables and different consumers on kafka

### ISSUE THREAD

**Issue by anasjaghoubbq** [zendesk/maxwell#1352]
I've a question, where I am using maxwell daemon with kafka and everything is working fine. 
Now, we've another use case, where we're going to include more tables and use it in a different system. 

My initial implementation, was one kafka topic and one kafka consumer. Now, since I need to include more tables to consume, I need to have multiple kafka topics and different consumers. 

My question here, how can I guarantee the sequence of insert/update on different topics ? or is there a way to define set of tables to go into one kafka topic, and another set into another topic ?

**Comment by osheroff** [comment]
> My question here, how can I guarantee the sequence of insert/update on different topics ? 

there is no way to guarantee sequence between two different kafka topics (either with maxwell or more generally).  

> or is there a way to define set of tables to go into one kafka topic, and another set into another topic ?

you can do two things here.  either you can run multiple maxwell instances with different filter lists, or you can run one instance with a javascript filter (http://maxwells-daemon.io/filtering/), which can set the kafka topic based on the table.
