### ISSUE TITLE
Question on bootstrap

### ISSUE THREAD

**Issue by simplifymatt** [zendesk/maxwell#1354]
If I run bootstrap on an existing table I get blank data records. Below is an example, and it outputs the correct number of rows.
```
{"database":"polarisglobal","table":"kitchendatasetpackages","type":"bootstrap-insert","ts":1570630877,"primary_key":[],"data":{}}
```

**Comment by simplifymatt** [comment]
I was on version 1.22.6 (brew) and switched to 1.21.1 and it works as expected.

**Comment by osheroff** [comment]
i can't reproduce this with the simplest form of trying.  what version of mysql?  Is there anything special about the table I should know? does the blank row come before or after all the other rows?

**Comment by lunaz2** [comment]
I was able to reproduce the problem. Looks like it has to do with table name in uppercase.
Using: maxwell 1.24.1, local mysql 5.7.25.

I created 2 different tables, 1 has some letter in uppercase and 1 all in lowercase. Bootstrap produce empty data for the the first table and valid data for second.
