### ISSUE TITLE
How to guarantee maxwell HA

### ISSUE THREAD

**Issue by xuzhaocai** [zendesk/maxwell#1355]

**Comment by osheroff** [comment]
not enough information

**Comment by xuzhaocai** [comment]
maxwell achieve high availability

**Comment by xuzhaocai** [comment]
or  how should I compile the package after I modify the code

**Comment by xuzhaocai** [comment]
I use idea edit maxwell code， Finally, how should I compile and package，thank you

**Comment by xuzhaocai** [comment]
> not enough information

I use idea edit maxwell code， Finally, how should I compile and package，thank you

**Comment by osheroff** [comment]
use maven to compile.  bring your own HA via kubernetes/swarm/etc etc etc
