### ISSUE TITLE
Couldn't find database or table 

### ISSUE THREAD

**Issue by sixinyiyu** [zendesk/maxwell#1359]
we have a problem ： eg:
Couldn't find database mgtj_third_content；com.zendesk.maxwell.schema.ddl.InvalidSchemaError: Could not find column company in

I found the is no record in table: databases or tables ;  but the schemas table had record.

**Comment by osheroff** [comment]
generally this means maxwell's view of the schema is out of sync with the actual schema.  Suggested course of action is to `drop database maxwell` and restart.  if the problem re-occurs or can be reproduced please re-open.  thanks!

**Comment by dalaopo** [comment]
> 通常这意味着 maxwell 的模式视图与实际模式不同步。建议的做法是`drop database maxwell`重新启动。如果问题再次出现或可以重现，请重新打开。谢谢！

But if doing so will not cause data duplication and loss, or need to do a full synchronization again?
