### ISSUE TITLE
Documentation Update: Using the maxwell.bootstrap table

### ISSUE THREAD

**Issue by liquidgenius** [zendesk/maxwell#1361]
Bootrapping using the maxwell bootstrap table fails for me if I follow the [documentation](https://maxwells-daemon.io/bootstrapping/) on the website:

> **Using the maxwell.bootstrap table**
> Alternatively you can insert a row in the maxwell.bootstrap table to trigger a bootstrap.
> 
> mysql> insert into maxwell.bootstrap (database_name, table_name) values ('fooDB', 'barTable');

Only by including the maxwell client_id from the config file will it succeed. This undocumented requirement threw me for a loop for a month until I stumbled across issue #987  that explicitly states that the Maxwell client_id must be included in the bootstrap SQL statement. The client_id is defined on the [Configuration page](https://maxwells-daemon.io/config/) as:

option | argument | description | default
-- | -- | -- | --
client_id | STRING | unique text identifier for maxwell instance | maxwell

Please consider updating the [documentation](https://maxwells-daemon.io/bootstrapping/) to read:
> **Using the maxwell.bootstrap table**
> Alternatively you can insert a row in the maxwell.bootstrap table, including the maxwell config client_id parameter, to trigger a bootstrap.
> 
> mysql> insert into maxwell.bootstrap (database_name, table_name, client_id) values ('fooDB', 'barTable', 1);

**Comment by DPGrev** [comment]
@liquidgenius I think this is the case when you set a custom `client_id` but when you leave it as default the original command still works. 

Nonetheless, I agree with you that the documentation should be updated.
