### ISSUE TITLE
redis_pub_channel doesn't have effect

### ISSUE THREAD

**Issue by KimPeeters** [zendesk/maxwell#1362]
When changing the redis_pub_channel all the messages are still published to "maxwell"

I've tested it with v1.23.2 and the latest master. Both don't seem to change the channel for me.

```
bin/maxwell --jdbc_options "serverTimezone=Europe/Amsterdam" --host xxxx --user maxwell --password xxxx --producer redis --redis_host 10.0.254.1 --redis_pub_channel testting
```
Changing redis_host is does work.

Any help on this would be appreciated.

**Comment by osheroff** [comment]
i took a look here, the logic in this code in super funky/not too smart.  as a workaround you can just set `redis_list_key`, I'll fix this next release.

**Comment by KimPeeters** [comment]
Yeah, noticed that yesterday too. Also saw that rpush is documented but wasn't implemented.

**Comment by acrois** [comment]
Honestly, having worked in the Redis producer, it needs to be reimplemented and have tests if we're going to survive in production.

I would call the version in master: "Just good enough to do what we want".

**Comment by elmehalawi** [comment]
FYI this also happens with `redis_type=xadd`. Basically `redis_stream_key` is ignored, and I needed to also set `redis_list_key`.

**Comment by osheroff** [comment]
cleaned up these params a few releases ago.
