### ISSUE TITLE
About creating maxwell databases

### ISSUE THREAD

**Issue by zhangxinjian123** [zendesk/maxwell#1363]
When I connect to a database with maxwell, maxwell itself creates a maxwell database and creates tables in the maxwell database. If I only have read access to the database. What if you do not have permission to create a maxwell database? Because the production database does not allow the creation of other databases and tables。

**Comment by KimPeeters** [comment]
As far is i understand, you can use another database server to store this "maxwell" database. 
See https://maxwells-daemon.io/config/  and look for replication_host and the link to the split server roles.

**Comment by osheroff** [comment]
seems like a decent answer
