### ISSUE TITLE
ERROR MaxwellKafkaProducer - Expiring 1 record(s) for maxwell-0: 30009 ms has passed since batch creation plus linger time

### ISSUE THREAD

**Issue by hawkingabc** [zendesk/maxwell#1368]
kafka disconnect   ， after  connected ,  the message has lost.

**Comment by osheroff** [comment]
sounds like your kafka server is overloaded; maxwell has waited 30 seconds to send the message. 

see https://stackoverflow.com/questions/46750420/kafka-producer-error-expiring-10-records-for-topicxxxxxx-6686-ms-has-passed
