### ISSUE TITLE
how to config filter 

### ISSUE THREAD

**Issue by sixinyiyu** [zendesk/maxwell#1379]
maxwell  version 1.22.4 

how to config filter params ；
My purpose is exclude some db  but include some table in this db;
filter=exclude:*.*,exclude.v3*,blacklist:v2.*,include:audio_qa.album,include:v3.user_anchor_info

eg:exclude:*.*,exclude.v3*,blacklist:v2.*,include:audio_qa.album,include:v2.user_anchor_info
this not event from user_anchor_info 

eg:exclude:*.*,exclude.v3*,blacklist:v2.*,include:audio_qa.album,include:v3.user_anchor_info
this has other table event from some tables in v3 db

**Comment by sixinyiyu** [comment]
![image](https://user-images.githubusercontent.com/3435446/68848901-0dc15f00-070c-11ea-90dc-e9f5fbbb90fe.png)

ide run maxwell-1.23.2 

--filter = 'blacklist:abcd_activity*,blacklist:abcdaop*,blacklist:abcd_dc,blacklist:abcd_third_content,blacklist:abcd_fund,blacklist:abcd-umps,blacklist:nacos*,blacklist:usearch, exclude:*.*, include:sound.album*, include:sound.audio*, include: sound.origin*,include:abcdv3.user_anchor_info'

**Comment by osheroff** [comment]
blacklist and include don't mix.  Don't blacklist any db where you want to include a table.  

Other than that,  your syntax is generally wrong. Go ahead and read http://maxwells-daemon.io/filtering/ again, you want to be saying like `exclude: v3.*, include: v3.included_table`.

**Comment by sixinyiyu** [comment]
eg:
exclude: *.*,blacklist:app_test.*,exclude:v3.*,include:sound_test.album,include:sound.audio,include:v3.user_anchor_info

this is event from v3 db exclude user_anchor_info table;  and the table not in maxwell tables;
 TaskManager - cause: 
java.lang.RuntimeException
Couldn't find table weixin_answerinfo in database v3
