### ISSUE TITLE
Is zero downtime migration possible by maxwell?

### ISSUE THREAD

**Issue by codewaring** [zendesk/maxwell#1380]
zero downtime migration is important for many scenario.

Can we achieve it by maxwell?  start data initialization firstly, then do data replication?

As for data initialization, i know that we can use maxwell-bootstrap to do it.

Does the application need to stop during this process to let the data unchanged?

**Comment by osheroff** [comment]
I'm not sure I 100% understand the question you're asking, but about bootstrapping:

The design of bootstrapping contains a guarantee that you'll get all the data in the table out; maxwell buffers any updates that occur while it's bootstrapping and then replays them when the initial dump is complete.  So it's not necessary to stop mutating the database while you're bootstrapping.  you'll get the data replication after the bootstrap completes.
