### ISSUE TITLE
maxwell filter params  of config.properties

### ISSUE THREAD

**Issue by chengcxy** [zendesk/maxwell#1381]
Hi,  In the past, I used a lower version of docker Maxwell to monitor mysql table,and used config.properties to start maxwell service,old config.properties like this 
```
...
include_tables = bw_dashboard.tasks
```

Today,I pull the latest version of docker zendesk/maxwell,
 I expect maxwell only monitor mysql table(bw_dashboard.coupon_product_v25),
I found the command line arguments "--filter"  in [http://maxwells-daemon.io/filtering/#basic-filters](http://maxwells-daemon.io/filtering/#basic-filters).
```
--filter = 'exclude: *.*, include: db1.*'
```
so I  used "exclude" param and  "include"  param in config.properties，
```
exclude=*.*
include=bw_dashboard.coupon_product_v25
```
 However when I update one another table(example: bw_dashboard.task_log)data,I found it in my kafka_topic(coupon_product_v25)

It caused my kafka consumer raised an exception;

would you tell me how to set the filter parameter please?

Thanks~

#################

1.docker image veision :  **zendesk/maxwell:latest**
2.docker maxwell config.properties like :
```
client_id=bw_dashboard.coupon_product_v25
user=maxwell
password=mypassword
host=192.168.7.9
port=3310
schema_database=maxwell
producer_partition_by=primary_key
exclude=*.*
include=bw_dashboard.coupon_product_v25
producer=kafka
kafka.acks=1
kafka.retries=5
kafka.request.timeout.ms=60000
ignore_producer_error=false
kafka.bootstrap.servers=192.168.6.187:9092
kafka_topic=coupon_product_v25
metrics_prefix=coupon_product_v25
metrics_type=http
metrics_http_port=31203
```
3.docker run command:
```
docker run -d --name coupon_product_v25 \
--net=host \
--restart=always \
-v /etc/localtime:/etc/localtime \
-v /data/config/coupon_product_v25-config.properties:/config.properties \
--log-driver json-file \
--log-opt max-size=100m \
zendesk/maxwell:latest bin/maxwell \
--config=/config.properties
```

**Comment by DPGrev** [comment]
Try changing your config.properties to:
```
filter='exclude: *.*, include: bw_dashboard.coupon_product_v25'
```

**Comment by osheroff** [comment]
what @DPGrev said.
