### ISSUE TITLE
Receiving PubSub messages from tables that have not been request for bootstrap.

### ISSUE THREAD

**Issue by GhostDZ9** [zendesk/maxwell#1382]
I am running a process where I am exporting a lot of data from an existing database and bringing it into Google Cloud Platform. I have imported a specific set of tables into a database prior to doing the bootstrap. When I start the process to send the messages to GCP via pubsub I am receiving messages from tables which I haven't specified nor included in my bootstrap commands.

Maxwells Daemon Version: 1.23.2
DB Type: Mysql

What am I missing to get this process to work properly?

**Comment by osheroff** [comment]
I imagine you're seeing the updates happening in your database.  If you want to only see updates for a specific set of tables please see http://maxwells-daemon.io/filtering/
