### ISSUE TITLE
 can't use Intranet IP to connect to aws aurora

### ISSUE THREAD

**Issue by shehuaqigai** [zendesk/maxwell#1383]
You can't connect aws aurora database with Intranet IP, you can only connect aws aurora with outer network IP. On maxwell instance, I can use go program to connect aws aurora with domain name, because it is VPC environment, the IP resolved by domain name is Intranet, I want Intranet access, the strange thing is maxwell can access mysql on Intranet, can't maxwell recognize aws aurora, if you use Intranet access, it will report
maxwell[30249]: Using kafka version: 1.0.0
maxwell[30249]: 10:32:41,440 WARN  MaxwellMetrics - Metrics will not be exposed: metricsReportingType not configured.
maxwell[30249]: 10:32:41,631 INFO  TaskManager - Stopping 0 tasks
maxwell[30249]: 10:32:41,631 ERROR TaskManager - cause:
maxwell[30249]: com.zendesk.maxwell.MaxwellCompatibilityError: server_id is '0'.  Maxwell will not function without a server_id being set.
maxwell[30249]: at com.zendesk.maxwell.MaxwellMysqlStatus.ensureServerIDIsSet(MaxwellMysqlStatus.java:50) ~[maxwell-1.23.2.jar:1.23.2]
maxwell[30249]: at com.zendesk.maxwell.MaxwellMysqlStatus.ensureReplicationMysqlState(MaxwellMysqlStatus.java:68) ~[maxwell-1.23.2.jar:1.23.2]
maxwell[30249]: at com.zendesk.maxwell.Maxwell.startInner(Maxwell.java:173) ~[maxwell-1.23.2.jar:1.23.2]
maxwell[30249]: at com.zendesk.maxwell.Maxwell.start(Maxwell.java:156) ~[maxwell-1.23.2.jar:1.23.2]
maxwell[30249]: at com.zendesk.maxwell.Maxwell.main(Maxwell.java:244) ~[maxwell-1.23.2.jar:1.23.2]
maxwell[30249]: 10:32:41,634 INFO  TaskManager - Stopped all tasks
maxwell[30249]: com.zendesk.maxwell.MaxwellCompatibilityError: server_id is '0'.  Maxwell will not function without a server_id being set.
maxwell[30249]: at com.zendesk.maxwell.MaxwellMysqlStatus.ensureServerIDIsSet(MaxwellMysqlStatus.java:50)
maxwell[30249]: at com.zendesk.maxwell.MaxwellMysqlStatus.ensureReplicationMysqlState(MaxwellMysqlStatus.java:68)
maxwell[30249]: at com.zendesk.maxwell.Maxwell.startInner(Maxwell.java:173)
maxwell[30249]: at com.zendesk.maxwell.Maxwell.start(Maxwell.java:156)
maxwell[30249]: at com.zendesk.maxwell.Maxwell.main(Maxwell.java:244)
systemd[1]: maxwellcp57.service: main process exited, code=exited, status=1/FAILURE

**Comment by osheroff** [comment]
can you check that your aurora config has its `server_id` setup properly?  that's what maxwell is complaining about.
