### ISSUE TITLE
[Feature request] Allow listening to specified databases

### ISSUE THREAD

**Issue by moewww** [zendesk/maxwell#1385]
Currently, maxwell will listen to **all** databases in the same MySQL instance, but I don't want to listen to all the databases, just want to listen to **some** of them, is there a way to configure it? 

I have read the [document](http://maxwells-daemon.io/config/), but I have not found the proper configuration item, did I miss something.

Thank you.

**Comment by DPGrev** [comment]
Please see: https://maxwells-daemon.io/filtering/

**Comment by moewww** [comment]
Thank you for response.
