### ISSUE TITLE
old values

### ISSUE THREAD

**Issue by pjebs** [zendesk/maxwell#1397]
For updates, maxwell seems to give you the new value and old values.

```
"data": {"id":1, "daemon": "Firebus!  Firebus!"},
    "old":  {"daemon": "Stanislaw Lem"}
```

I'm not a java developer. How does maxwell determine the old values? Surely it doesn't store the entire state of the relevant tables in memory and keep track of the "old values" as new values come in.

**Comment by pjebs** [comment]
My understanding is the read replica mysql protocol doesn't provide old values. Is this assumption incorrect?

**Comment by pjebs** [comment]
@propersam

**Comment by propersam** [comment]
After taking some time to look into the code...my thought on how i think this is done is more like...the data found on the current position is fetched and stored somewhere before updating the sqlPostion to the next latest SqlPos. in the replication log. and then this old data is sent along with the new updated data recorded in the replication log to the producer output.

Here is a starting point to figure this out in the source code...
https://github.com/zendesk/maxwell/blob/master/src/main/java/com/zendesk/maxwell/row/RowMap.java

**Comment by propersam** [comment]
There is a comment in this function that explains what is happening i guess...
..check if it helps...
https://github.com/zendesk/maxwell/blob/833077f68eea65ed2165bea08e31e5c1073491f0/src/main/java/com/zendesk/maxwell/replication/BinlogConnectorEvent.java#L120

**Comment by osheroff** [comment]
mysql includes the previous value for a column in the binlog.  It's used internally to mysql to determine which rows the replica should update.
