### ISSUE TITLE
Does Maxwell support generation of millisecond timestamps(13 bits)？

### ISSUE THREAD

**Issue by chengcxy** [zendesk/maxwell#1398]
` I used Maxwell to listen  MySQL binlog,and Maxwell sends binlog to kafka.`

`I found that if I insert and update data to mysql concurrently in the same second, the JSON of kafkaConsumer have the same ts(10bits)

```
maxwell: {
    "database": "test",
    "table": "maxwell",
    "type": "update",
    "ts": 1449786341, ===> it is 10bits
    "xid": 940786,
    "data": {"id":1, "daemon": "Firebus!  Firebus!"},
  }
```

![image](https://user-images.githubusercontent.com/25173362/70308896-3a6a2180-1847-11ea-809c-7ad3f86a4c3d.png)

When I parsed json and sorted with primary key and ts desc,it maybe cause the data not equal with the source of mysql table

   I know Kafka sends one data, which will generate a millisecond timestamp (13 bits),like this 

```json
{"item_id": 86829, "timestamp": 1575614758592, "partition": 0, "offset": 8908521, "src_add_type": "delete", "shop_id": 453297, "status": 1, "id": 4424262, "startdate": "20191206"}
```

Could you tell me   Maxwell maybe generate the ts in JSON accurate to the millisecond level (13bits) ,please?

That I reparsed Json sorted with primary key and  ts(13 bits) desc ,I will get the same data in Json which  equal with the source of mysql table

Thanks~

**Comment by chengcxy** [comment]
Sorry ,generation of millisecond timestamps(13 bits)  not 17 bits

**Comment by osheroff** [comment]
The MySQL timestamp (the Json field “ts”) only has a resolution of 32 bits, and is in seconds.  There’s no way to raise this, as it’s the format of the MySQL bin log.  

Additionally, these time stamps mean different things.  The MySQL timestamp refers to when the row was created in the database.  The Kafka timestamp refers to when the row arrived in Kafka.  There is absolutely no guarantee that these timestamp will line up.

**Comment by chengcxy** [comment]
> The MySQL timestamp (the Json field “ts”) only has a resolution of 32 bits, and is in seconds. There’s no way to raise this, as it’s the format of the MySQL bin log. Additionally, these time stamps mean different things. The MySQL timestamp refers to when the row was created in the database. The Kafka timestamp refers to when the row arrived in Kafka. There is absolutely no guarantee that these timestamp will line up.
> […](#)
> On Dec 6, 2019, at 22:15, chengxinyao ***@***.***> wrote: ﻿ Sorry ,generation of millisecond timestamps(13 bits) not 17 bits — You are receiving this because you are subscribed to this thread. Reply to this email directly, view it on GitHub, or unsubscribe.


ok,I consider change my solution of technology. I used the param "producer_partition_by=primary_key" in Maxwell，It will guarantee the data changed(update/insert/delete),the data would be into the same partition of Kafka,and in the same partition the data would be sorted,I used the timestamp(13bits) of Kafka to instead the maxwell Json field “ts”

Thanks~

**Comment by osheroff** [comment]
sounds good
