### ISSUE TITLE
kafka to hbase or hdfs example

### ISSUE THREAD

**Issue by nphouse2008** [zendesk/maxwell#140]
Do you have example or reference code to read this events from kafka and persists on hbase or hdfs?

**Comment by osheroff** [comment]
Sorry for the lag here.

I don't, sorry.  In theory it should be as simple as creating an alternate `Producer` for hbase/hdfs, but those are not familiar things to mine coding hands.  Patches welcome, of course, and you can always use the "stdout" producer in a pinch and feel the rows via a pipe, although that methodology is probably a lot less reliable than you'd like.
