### ISSUE TITLE
Maxwell shutting down. Binlog disconnecting.

### ISSUE THREAD

**Issue by LeninGangwal** [zendesk/maxwell#1402]
For mysql 5.6, our maxwell stops every time after running for a few minutes.

[WARN ] 2019-12-12 17:22:34.245 [Thread-6] MaxwellContext - Timed out waiting for heartbeat 1576151549237
[INFO ] 2019-12-12 17:22:34.246 [shutdownThread] TaskManager - Stopping 4 tasks
[INFO ] 2019-12-12 17:22:34.246 [shutdownThread] TaskManager - Stopping: com.zendesk.maxwell.schema.PositionStoreThread@3a6caf24
[INFO ] 2019-12-12 17:22:34.246 [shutdownThread] StoppableTaskState - com.zendesk.maxwell.schema.PositionStoreThread requestStop() called (in state: RUNNING)
[INFO ] 2019-12-12 17:22:34.247 [shutdownThread] TaskManager - Stopping: com.zendesk.maxwell.producer.MaxwellKafkaProducerWorker@34ab5619
[INFO ] 2019-12-12 17:22:34.247 [shutdownThread] StoppableTaskState - MaxwellKafkaProducerWorker requestStop() called (in state: RUNNING)
[DEBUG] 2019-12-12 17:22:34.247 [Position Flush Thread] MaxwellConnectionPool - MaxwellConnectionPool: Checkout - 1/1 (HitRate=99.84614%)
[INFO ] 2019-12-12 17:22:34.247 [shutdownThread] KafkaProducer - [Producer clientId=producer-1] Closing the Kafka producer with timeoutMillis = 9223372036854775807 ms.
[DEBUG] 2019-12-12 17:22:34.247 [Position Flush Thread] MysqlPositionStore - writing heartbeat: 1576151554247 (last heartbeat written: 1576151553555)
[DEBUG] 2019-12-12 17:22:34.247 [kafka-producer-network-thread | producer-1] Sender - [Producer clientId=producer-1] Beginning shutdown of Kafka producer I/O thread, sending remaining records.

**Comment by osheroff** [comment]
are there more logs (before these entries)?  these are standard shutdown messages.
