### ISSUE TITLE
Gracefully stop the daemon

### ISSUE THREAD

**Issue by Stormhand** [zendesk/maxwell#1405]
Hello,
I've searched but there is nothing in the documentation. Im using Maxwell on CentOS but when its running with --daemon it seems that i cannot gracefully stop it. The only way is kill -9.
In this case I am not sure what happens next with the offsets of the binlog and the currently buffered data.
Is there any wait to gracefully shutdown on SIGTERM or/and SIGINT?
Thanks

**Comment by osheroff** [comment]
Kill with a TERM should trigger a graceful shutdown.  What error messages do you get on TERM?

**Comment by Stormhand** [comment]
There is nothing in the default log file. The process is staying in the list too. Just looks like nothing is happening.

**Comment by osheroff** [comment]
so the *only* thing `--daemon` does is to run maxwell underneath `nohup`.  are you sure that this issue only repros when running with `--daemon`?

**Comment by Stormhand** [comment]
Yes, without it if I Ctrl+C I see it shuts down properly.

**Comment by osheroff** [comment]
i will try this on a linux system but nothing I can think of would be
blocking a TERM signal...

**Comment by Stormhand** [comment]
I don't know how but when I migrated to centos7 and the latest Maxwell version everything is working as expected.
Thanks
