### ISSUE TITLE
Why daemon mode not use log4j2 config?

### ISSUE THREAD

**Issue by greydesolate** [zendesk/maxwell#1413]
i use this command to start maxwell
```linux
nohup bin/maxwell ..... &
```
but i find out the log came out to this file
>MaxwellDaemon.out
not use lo4j2 config.
i check maxwell file.
Find this script to log to the MaxwellDaemon.out file,not use log4j2 config.
```linux
do
	case "$key" in
		--kafka_version)
		use_kafka "$2"
		;;

		--kafka_version=*)
		use_kafka "${key#*=}"
		;;

        --daemon)
		DAEMON_MODE="true"
		DAEMON_NAME="MaxwellDaemon"
		;;

	esac
done

if [ "x$DAEMON_MODE" = "xtrue" ]; then
    # Log directory to use
    if [ "x$LOG_DIR" = "x" ]; then
        LOG_DIR="$base_dir/logs"
    fi
    # Create logs directory
    if [ ! -d "$LOG_DIR" ]; then
        mkdir -p "$LOG_DIR"
    fi
    # Console output file when maxwell runs as a daemon
    CONSOLE_OUTPUT_FILE=$LOG_DIR/$DAEMON_NAME.out
    echo "Redirecting STDOUT to $CONSOLE_OUTPUT_FILE"
fi
```

1. Is there some reason is better not use log4j2 in daemon mode?
2. If I like use log4j2 in daemon mode,could I change some code like?
```linux
if [ "x$DAEMON_MODE" = "xtrue" ]; then
->
if [ "x$DAEMON_MODE" = "xfalse" ]; then
```

**Comment by osheroff** [comment]
The default `log4j2.xml` file that ships with maxwell logs to STDOUT, and then daemon mode redirects STDOUT to `MaxwellDaemon.out`.   Maxwell will honor whatever you put in log4j2.xml, but it'll still redirect STDOUT.

If this doesn't fix your issue feel free to reopen.
