### ISSUE TITLE
Issue while reading binary column value from mysql binlog

### ISSUE THREAD

**Issue by SyedSulaimanM** [zendesk/maxwell#1424]
We are using maxwell with kinesis to read the mysql binlog. If the table has binary data for a column we are not receiving the exact data as in the source table.It looks like it has encoded with something. Is is something we need to do it on receiver side ?

**Comment by osheroff** [comment]
It’s base-64 encoded.  You’ll need to decode it.

**Comment by SyedSulaimanM** [comment]
Thanks. After decoding got the original data.
