### ISSUE TITLE
Bootstrapping from Slave / replicating from master

### ISSUE THREAD

**Issue by anasjaghoubbq** [zendesk/maxwell#1429]
I've maxwell installed and running on master db. 

Now, I need to do bootstrapping, but I need to have it run from slave db not from master, is there any way or technique to do such operation? 

the idea the bootstrapping condition is complex and loads the master at production, so it's better if I have a way to do it in slave.

Thanks

**Comment by anasjaghoubbq** [comment]
Any luck to answer / help in this

**Comment by osheroff** [comment]
supported for quite awhile in production, use a separate `replication_host`
