### ISSUE TITLE
Performance issues when replicating from a slave

### ISSUE THREAD

**Issue by Stormhand** [zendesk/maxwell#1435]
I am replicating from several MySQL servers which are a slaves. Producing to Kafka. I noticed that the sometimes some of the instances are drastically increasing the memory consumption to 2.5GB+ ram. Normally it's around 200-300MB. 
I found that if I change the replication host to point to the master everything is ok.
Sometimes Maxwell is crashing with:
> Could not find first log file name in binary log index file

When I check the server the SHOW SLAVE STATUS message is: Waiting for master to send event.
Also, when an instance is in that state the Kafka broker is heavily loaded but I'm not sure why.
I'm using Maxwell 1.24.1

**Comment by osheroff** [comment]
sorry for the delay here @stormhand.  I can't think of any reason offhand why replicating from the slave would be more memory intensive.    

`Could not find first log file...` usually means you're rotating the binlogs out from under maxwell before it can process them.  It's probably because the processes are GC bound and not making any progress.  

I'm trying to think of a good reason why / how memory would blow up; there's lots of controls and backpressures that should prevent this.    How many partitions are you producing to?  How often does this occur?

**Comment by Stormhand** [comment]
Thanks for the response! I have single partition per topic. Im replicating 48 nodes, all of them are pairs master/slave, some of the tables have several millions of records changed per day. It happens often if I connect to the slave.

**Comment by osheroff** [comment]
can you get one of the nodes into that state and then run `jmap -histo:live [PID]` on the maxwell instance?

**Comment by osheroff** [comment]
do you have any metric graphs?  is there an increased data rate into kafka at those times?

**Comment by Stormhand** [comment]
Attached is the jmap output of such a process which is currently consuming 3GB of memory. I have metrics in grafana but i dont watch them constantly so i dont know when they start growing.
[jmap.log](https://github.com/zendesk/maxwell/files/4382904/jmap.log)

**Comment by osheroff** [comment]
i should also ask some basics; what's the CPU usage of that process?
What's the max heap size? ( remember the jvm max heap is 1/4 of system
memory by default )  It looks like maxwell is retaining some 50k rows in
memory.

**Comment by Stormhand** [comment]
buffer_memory_usage is 0.15
CPU usage is between 0.3% and 1%. The server has 264GB RAM.
2x Intel(R) Xeon(R) CPU E5-2630 v3 @ 2.40GHz

**Comment by osheroff** [comment]
I have at least a theory; when maxwell is running off the master, transactions come in in small batches, maxwell is able to keep up, and the memory footprint stays low.  When maxwell is running off a slave, occasionally the rows will come in in a giant batch.  Maxwell bloats up trying to process this (it's likely that the javascript filter is honestly the source of the bottleneck, not sure though) and then the JVM doesn't release the memory back to the OS.

what values of buffer_memory_usage have you tried?  0.15 is still not a very effective limit; you're saying "use no more than 40GB of memory".  

If this isn't causing other problems I'd be tempted to say "just slap -xMx on it and move along", but it is still a curiousity. 

If my theory is correct, you should see the slave processes chug along normally, then all at once bloat up to 3gb, and then never release their memory back to the OS.

**Comment by Stormhand** [comment]
Yep, once the memory grows it stays 3gb forever until I restart the process. 
In the future I would like to have a table2topic mapping so I can remove the javascript filter :)
Thanks for the tips, I'll lower the buffer limit more.

**Comment by osheroff** [comment]
no problem.  let me know how it works out.  I'd probably start with `-Xmx` to limit the heap size before tuning the buffer limit.

**Comment by Bruce2jiang** [comment]
@Stormhand Hello, has this problem been solved? I have this problem, please write down your solution

**Comment by Stormhand** [comment]
> @Stormhand Hello, has this problem been solved? I have this problem, please write down your solution

No, but I'm starting the daemon with -Xmx option to limit the memory which seems like a working option for now. I just stopped watch the processes lately.

**Comment by osheroff** [comment]
let's call this issue solved unless we feel like there's more to be done.  thanks all.
