### ISSUE TITLE
How to sync mysql data structure to elasticsearch?

### ISSUE THREAD

**Issue by 81519434** [zendesk/maxwell#1439]
Hi~
I know my question may not be related to maxwell. and I know what is Maxwell.
The data flow for Maxwell is shown below.
MySQL --> Maxwell --> mq  -->  logstash -->es
Because Maxwell just parses binlog to JSON, so the es just saved raw data.
What I want is like [go-mysql-elasticsearch](https://github.com/siddontang/go-mysql-elasticsearch), it can sync the MySQL data structure too.
But I can't use go-mysql-elasticsearch for some reason.
There is my question: How to sync the MySQL data structure to es when we have the json that parsed by Maxwell. In other words, is there have other product can do that?

**Comment by hawkingabc** [comment]
MySQL --> Maxwell --> mq --> logstash -->es
logstash can be insteaded by your application , in your application, you can define data structure in elasticsearch.

**Comment by 81519434** [comment]
ok
