### ISSUE TITLE
Maxwell reboots or hangs up unexpectedly, data is lost

### ISSUE THREAD

**Issue by porkling** [zendesk/maxwell#1446]
kiil ${PID} to stop the Maxwell process, or when Maxwell hangs up due to network and other factors. Restarting a process always loses a small amount of data

**Comment by osheroff** [comment]
this isn't the case, although it can depend on your producer settings.  In general maxwell doesn't update `maxwell.positions` until the records have been sent,  especially when dealing with reliable producers like kafka/kinesis etc.  

in other words: more info plz.  what producer are you using?

**Comment by Bruce2jiang** [comment]
@porkling Hello, have you solved this problem

**Comment by porkling** [comment]
> @porkling Hello, have you solved this problem

No, but now the data is normal after restarting. I'll take a look at the Maxwell source code. It's true that data will not be lost. It may be due to the wrong posture of the producer to the data landing

**Comment by osheroff** [comment]
i'm going to close this one.  feel free to reopen if there's something actionable.
