### ISSUE TITLE
Datadog integration doesn't allows http-push to eu-site

### ISSUE THREAD

**Issue by RikJansen81** [zendesk/maxwell#1448]
Due to customer privacy compliance, Datadog opened a datacenter in the EU.
Maxwell currently depends on https://github.com/coursera/metrics-datadog/ which has the .com-URL hardcoded and appears to be abandoned. A more active fork seems to be https://github.com/viafoura/metrics-datadog, which has implemented support for EU.

Without this upgrade, the datadog-integration becomes useless for many EU users.

**Comment by osheroff** [comment]
Ok, happy to accept a PR to switch to the new fork with the eu changes.

**Comment by RikJansen81** [comment]
The project is in RC2 stage. Is that acceptable?
