### ISSUE TITLE
Limit maxwell producer to specific SQL databases and tables?

### ISSUE THREAD

**Issue by rns7a1** [zendesk/maxwell#145]
Thanks for making a great tool.  I believe this comes 99% of the way to solving my use case.  But I need to limit the maxwell producer to only certain SQL databases and tables on the server.  In other words, changes to some SQL databases and tables cause maxwell to emit a JSON object, while changes in other databases and tables do not.  Is this possible?  Thanks!

**Comment by osheroff** [comment]
@rns7a1, in the next release of maxwell we'll have filters.  see https://github.com/zendesk/maxwell/pull/143

**Comment by rns7a1** [comment]
To be clear; I'd like the option to be _logging_ for all databases.  Therefore, the filtering would come on the maxwell side.

**Comment by osheroff** [comment]
yup, that's how it'll operate.

**Comment by rns7a1** [comment]
Thanks!  And do you have a rough estimate of when the next release is coming?

**Comment by osheroff** [comment]
done.  https://github.com/zendesk/maxwell/releases/tag/v0.14.0.  let me know how it works for you.

**Comment by rns7a1** [comment]
Thanks Ben.  Is there any documentation for implementing the new filters?

- Rich

On Tue, Nov 3, 2015 at 11:59 AM, Ben Osheroff <notifications@github.com>
wrote:

> done. https://github.com/zendesk/maxwell/releases/tag/v0.14.0. let me
> know how it works for you.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/zendesk/maxwell/issues/145#issuecomment-153417377>.
>

-- 

------------------------------
This e-mail and any files transmitted with it may be proprietary and are 
intended solely for the use of the individual or entity to whom they are 
addressed. If you have received this e-mail in error please notify the 
sender. Please note that any views or opinions presented in this e-mail are 
solely those of the author and do not necessarily represent those of IST 
Research. The recipient should check this e-mail and any attachments for 
the presence of viruses. IST Research accepts no liability for any damage 
caused by any virus transmitted by this e-mail.

**Comment by rns7a1** [comment]
Sorry! Found it: http://maxwells-daemon.io/config/#row-filters


On Mon, Nov 9, 2015 at 10:01 AM, Rich Salaway <rich.salaway@istresearch.com>
wrote:

> Thanks Ben.  Is there any documentation for implementing the new filters?
>
> - Rich
>
> On Tue, Nov 3, 2015 at 11:59 AM, Ben Osheroff <notifications@github.com>
> wrote:
>
>> done. https://github.com/zendesk/maxwell/releases/tag/v0.14.0. let me
>> know how it works for you.
>>
>> —
>> Reply to this email directly or view it on GitHub
>> <https://github.com/zendesk/maxwell/issues/145#issuecomment-153417377>.
>>
>
>

-- 

------------------------------
This e-mail and any files transmitted with it may be proprietary and are 
intended solely for the use of the individual or entity to whom they are 
addressed. If you have received this e-mail in error please notify the 
sender. Please note that any views or opinions presented in this e-mail are 
solely those of the author and do not necessarily represent those of IST 
Research. The recipient should check this e-mail and any attachments for 
the presence of viruses. IST Research accepts no liability for any damage 
caused by any virus transmitted by this e-mail.
