### ISSUE TITLE
mysql latin1 Chinese output to redis garbled

### ISSUE THREAD

**Issue by rentiansheng** [zendesk/maxwell#1451]
Chinese string  "蓝"，  maxwell  output redis is  hex encoding value  "c3a8e2809cc29d" but golang hex encoding value "c3a8c293c29d"

binary bit:
maxwel redis hex string: c3a8e2809cc29d
golang iconv hex string: c3a8c293c29d

different:
maxwel redis  -  hex string:  e2809c  bit : 11100010 1000000 10011100 
golang iconv    - hex string:   c293     bit: 11000010  10011001

**Comment by osheroff** [comment]
You can't encode these characters inside latin1.  It *might* work, depending on how the various tools treat it, but in order to reliably encode these characters you need to have a utf-8 column and a utf-8 database connection.

**Comment by rentiansheng** [comment]
> You can't encode these characters inside latin1. It _might_ work, depending on how the various tools treat it, but in order to reliably encode these characters you need to have a utf-8 column and a utf-8 database connection.

mysql database and table is latin1 encode

**Comment by osheroff** [comment]
don't try to encode chinese characters in a latin1 encoding.
