### ISSUE TITLE
How to do high availability  & maxwell

### ISSUE THREAD

**Issue by HelloDate** [zendesk/maxwell#1453]
1, maxwell  have a high availability configuration？
2, what should i do when kafka upgrade

**Comment by osheroff** [comment]
1.  It's not included in maxwell.  At Zendesk we used to use `consul lock`, and i'm sure mesos/kubernetes/AWS has their own form of offerings.  what platform do you run on?

**Comment by osheroff** [comment]
2. shut down maxwell, upgrade kafka, restart maxwell

**Comment by osheroff** [comment]
dupe of #1481
