### ISSUE TITLE
Documentation on Kafka key is incorrect

### ISSUE THREAD

**Issue by wushujames** [zendesk/maxwell#146]
The website http://maxwells-daemon.io/kafka/ says the format is something like
```
db:test_db/tbl:test_tbl/id:93/id_2:17910090
```
But in practice, it appears the key is actually json:
```
{"database":"test","table":"users","pk.userId":4}
```
This output is from my test database.

**Comment by osheroff** [comment]
ah, true.  ok.  I'll take a look.

**Comment by osheroff** [comment]
thanks james.  fixed.
