### ISSUE TITLE
Autosearch earliest/latest binlog on maxwell restart if current binlog not available

### ISSUE THREAD

**Issue by rohitgcs** [zendesk/maxwell#1463]
Hey guys - first things first- LOVE this project. We use this as a main part of our system to sync data between multiple MySQL databases and services. 
I had a quick question about Maxwell when it restarts. Explained below.

If Maxwell restarts and is unable to find the last position it was on - is there a way to for Maxwell to autoseek to earliest binlog available in MySQL.

If not - how would you advise catching Maxwell's error on not finding a binlog position ina programmatic fashion? I'm aware of the `--init_position` but I want to be able to catch the error so I can use this flag.
Trying to use this in production. Any help would be great!
Thanks

**Comment by osheroff** [comment]
i can look into an autoseek feature, it's possibly a bit nasty and will obviously duplicate data, but might be kinda useful if one can't control their binlog rotation.  It's also possible that the error might be catchable if you did an embedded maxwell install, but I'd have to look.  

that said, care to advise on why/how the binlogs are getting rotated out from under your install?

**Comment by rohitgcs** [comment]
Well, if there are lot of updates/inserts in a period of time and Maxwell is currently processing one of those large binlogs that soon gets rotated out given a time period for rotation. In this case, Maxwell dies and being a Pythonista - I just have a simple restart if maxwell dies. But in this case, Maxwell continues to run in that endless loop where from a process perspective it looks like its running but the info logs keep reconnecting.

Well, it is a little nasty - that's why I was wondering if there's some way I could catch it this reconnection and accordingly programmatically start Maxwell with a `--init_position` after? Maybe if Maxwell isn't able to connect to a binlog after 5 times - kill it with an exception?

**Comment by osheroff** [comment]
I’ll see if we can’t maybe exit with a specific error code in this case.  

Meanwhile, I highly suggest bumping up your binlog retention values

**Comment by RohitJacob** [comment]
Yes, there are multiple reasons why we keep binlog retention to the value we have. But do let me know if there's another way I can catch the lost binlog exception in the meanwhile - if its going to exit with a specfic error code in future. That would be very helpful - thanks!

**Comment by RohitJacob** [comment]
@osheroff will the change for exiting maxwell with a specific error code be on the cards for development? If so, what does the timeline look like? I ask only because I want to be able to handle this on my side in the meanwhile. Any suggestions would be really helpful. Thanks.

**Comment by osheroff** [comment]
Yeah I’ve got a pr in the works for next release.

**Comment by RohitJacob** [comment]
Thanks - is there a PR number I can follow so I know when its merged :)

**Comment by osheroff** [comment]
released, returns exit code 2 on unfound binlogs in 1.25.1
