### ISSUE TITLE
跑源码报错，求指导！

### ISSUE THREAD

**Issue by zhangbc** [zendesk/maxwell#1465]
`☁  maxwell [master] bin/maxwell --user='maxwell' --password='123456' --host='127.0.0.1' --producer=stdout

Error: No matches for kafka version: 1.0.0
Supported versions:
ls: /home/tools/maxwell/bin/../lib/kafka-clients: No such file or directory`

kafka安装的是2.4.1，难道是版本不支持？

**Comment by osheroff** [comment]
Did you untar Maxwell fully?  Is /home/tools/Maxwell the correct directory?

**Comment by zhangbc** [comment]
> Did you untar Maxwell fully? Is /home/tools/Maxwell the correct directory?
> […](#)
> On Apr 11, 2020, at 00:24, zhangbc ***@***.***> wrote: ﻿ ☁ maxwell [master] bin/maxwell --user='maxwell' --password='123456' --host='127.0.0.1' --producer=stdout Error: No matches for kafka version: 1.0.0 Supported versions: ls: /home/tools/maxwell/bin/../lib/kafka-clients: No such file or directory kafka安装的是2.4.1，难道是版本不支持？ — You are receiving this because you are subscribed to this thread. Reply to this email directly, view it on GitHub, or unsubscribe.

thks，supported.
