### ISSUE TITLE
The last packet successfully received from the server was xxx milliseconds ago

### ISSUE THREAD

**Issue by wanghangyu817** [zendesk/maxwell#1470]
ERROR c3p0connectionpool-got SQL Exception: The last packet successfully received from The server was XXX milliseconds ago
I've set --jdbc_options='autoReconnect=true'
What should I do？

**Comment by wanghangyu817** [comment]
![error](https://user-images.githubusercontent.com/18672877/79710939-0d4f7480-82f9-11ea-843b-ed0508500af8.png)

**Comment by wanghangyu817** [comment]
![conf](https://user-images.githubusercontent.com/18672877/79711096-8222ae80-82f9-11ea-9b0b-24b23a5babb7.png)

**Comment by osheroff** [comment]
hi, can you send the rest of the log?

**Comment by wanghangyu817** [comment]
[a.log](https://github.com/zendesk/maxwell/files/4513516/a.log)
Hi @osheroff  According to my configuration, I only get these logs

**Comment by osheroff** [comment]
does this happen often or only once?

**Comment by wanghangyu817** [comment]
So far, it's happened twice

**Comment by wanghangyu817** [comment]
![2EC8C7B1-ED74-43b2-A58F-CE67929AB998](https://user-images.githubusercontent.com/18672877/80200185-d9f04b00-8654-11ea-85fb-98c07b0c17be.png)
hi @osheroff ,This is the new exception

**Comment by osheroff** [comment]
very weird.  Unless my math is wrong that value is *7 days*.  I'm wondering if the clock on your system could be jumping around or something like that?  How long has the process been up for?  and why 7 days? 

very very odd.  I don't have any theories, yet.

**Comment by wanghangyu817** [comment]
Is it the time zone?This is China.If so, how do I deal with him

**Comment by Stormhand** [comment]
I had the same error when somebody probably switched the master server:

> ERROR C3P0ConnectionPool - got SQL Exception: The last packet successfully received from the server was 35,048,748 milliseconds ago.  The last packet sent successfully to the server was 35,048,749 milliseconds ago. is longer than the server configured value of 'wait_timeout'. You should consider either expiring and/or testing connection validity before use in your application, increasing the server configured values for client timeouts, or using the Connector/J connection property 'autoReconnect=true' to avoid this problem., The last packet successfully received from the server was 35,048,748 milliseconds ago.  The last packet sent successfully to the server was 35,048,749 milliseconds ago. is longer than the server configured value of 'wait_timeout'. You should consider either expiring and/or testing connection validity before use in your application, increasing the server configured values for client timeouts, or using the Connector/J connection property 'autoReconnect=true' to avoid this problem., retrying..

My JDBC options are:

> zeroDateTimeBehavior=convertToNull&connectTimeout=5000&serverTimezone=US/Pacific

**Comment by wanghangyu817** [comment]
hi @Stormhand  Has the problem been solved?

**Comment by Stormhand** [comment]
No because i didnt notice that the maxwell instance has died for 3 days. So when i checked the server the binlog file was different and new. I just changed the file name in the 'positions' table and set the position to 0. I lost 3 days of changes but its still testing platform. 
Probably the guy who swapped the master node started it with different time zone in the beginning.

**Comment by wanghangyu817** [comment]
I have no good way to solve this problem at presen

**Comment by osheroff** [comment]
ok, according to https://stackoverflow.com/questions/45114889/the-last-packet-successfully-received-from-the-server-was-43417-seconds-ago this makes some sense; connections are left unused, the mysql server kills them, and then when we go to use them the connections are dead.  lemme see what c3p0 says about this.

**Comment by osheroff** [comment]
issue fixed in 1.25.3.  please re-open if not
