### ISSUE TITLE
start maxwell from new db host binlog position

### ISSUE THREAD

**Issue by mpkd** [zendesk/maxwell#1471]
Hello,

We are using maxwell-1.21.1 for getting CDC events from AWS RDS Mysql. When we need to shrink or expand the RDS DB host to different size, we will get new cluster with replicated data. 
But the problem is old hosts binlog file was **binlog.xxxxxxx** and the new host has new binlog files **binlog.yyy** with fully replicated pipeline. Because of this scenario we ended up bootstrap whenever this kind of migration is there. As this environment is cloud, scale up and down will be a common scenario we need to handle. Is there any better approach other than the approach what we are doing now.

Current process.
```
- change maxwell config to point to new host
- stop respective processes for maxwell
- delete _maxwell_ metadata database from mysql
- start the respective maxwell processes
- It will start reading from latest of the new host(there will be a small data loss between stopping maxwell and starting maxwell)
- then bootstrap tables 
```

Is there any way to avoid bootstrap and seamlessly read from a binlog position if we know the binlog position in new host?

**Comment by osheroff** [comment]
The best way: 

- enable GTID. 

Another way:

*If* you can ensure there's NO schema changes happening, you can start the new server with `--init_position=newbinlog:newposition` and things will work fine.

I'm gonna close this issue, but let me know how it works out!

thanks.
-ben
