### ISSUE TITLE
Full synchronization of a large table, the speed is slow

### ISSUE THREAD

**Issue by wanghangyu817** [zendesk/maxwell#1475]
![微信图片_20200427204826](https://user-images.githubusercontent.com/18672877/80373969-7ec68e80-88c8-11ea-950f-ec84fbb190e1.png)
Hi @osheroff ,It takes a long time to collect when synchronizing a 4000W data table, which has only a federated primary key, and I find that I have an orderby operation on my query. Why
-thank you

**Comment by wanghangyu817** [comment]
![image](https://user-images.githubusercontent.com/18672877/80443314-7fe7d200-8941-11ea-9932-0b1799c60d76.png)
Same sentence, maxwell takes 10 minutes, navicat takes 20 seconds, I wonder what caused the big difference

**Comment by wanghangyu817** [comment]
Hi @osheroff 
  I tested 50W of data again and it took me 10 minutes. Is that normal?I want to increase the speed. What should I do?

**Comment by osheroff** [comment]
@wanghangyu817 can you give me `SHOW CREATE TABLE` info from this table?  you say "it only has a federated primary key", I'm not quite sure what that means.  If there's a primary key on the table maxwell attempts to order a bootstrap by that primary key.

**Comment by wanghangyu817** [comment]
@osheroff This table was created by the business side. I think the problem is that the method used in the full collection may cause the data to be collected too slowly. I noticed that the method used in the use of JDBC protocol is streaming, which may be the main reason for the slow

**Comment by osheroff** [comment]
well, streaming the query means that it takes as long as the producer takes.  you say that "the table is 4000 wide".  How many rows?  what producer?

**Comment by wanghangyu817** [comment]
The test table has 500,000 rows, and the full extraction takes 10 minutes. The production environment table is basically more than 400,000 rows. I am so worried about this efficiency problem that I have to use other tools to replace the full initialization.The producer is kafka

**Comment by osheroff** [comment]
can you run a profiler on maxwell or give me a small sample of test data?  You say it's 4000 columns?  Probably there's some optimizations that can happen.

**Comment by wanghangyu817** [comment]
Sorry maybe I didn't make it clear, the table only has 10 columns of data, but there are 500,000 rows, it takes 10 minutes to collect the full volume, and the table on production has tens of millions of rows, I worry about the efficiency

**Comment by osheroff** [comment]
10 minutes for 500k rows still seems pretty slow.  Is maxwell cpu bound?

**Comment by wanghangyu817** [comment]
No, so I think the speed is relatively slow

**Comment by osheroff** [comment]
no I mean, is maxwell at 100% cpu?  It could be many things creating load; mysql, maxwell, or kafka.

**Comment by wanghangyu817** [comment]
Low CPU usage

**Comment by osheroff** [comment]
then I'd check to see if you kafka cluster is maybe i/o bound. 

I would also run a test with the `file` producer to see how fast maxwell can go if you eliminate kafka from the process.

**Comment by wanghangyu817** [comment]
I tried to test it with a file, and the result was the same as in kafka. I suspected mysql was the problem
