### ISSUE TITLE
maxwell clustering

### ISSUE THREAD

**Issue by rottenmu** [zendesk/maxwell#1481]
please,how I do a cluster about maxwell

**Comment by osheroff** [comment]
maxwell has no native clustering facilities.  can you describe more about what you want to accomplish?

**Comment by rottenmu** [comment]
implement maxwell HA

**Comment by rottenmu** [comment]
Can you help me

**Comment by osheroff** [comment]
currently there is no native support for clustering or HA of maxwell.  It's a very frequently requested feature, and I think it might do for us to bite the bullet and implement something.

**Comment by osheroff** [comment]
I think we could pull off something fairly simple and stupid using mysql's native locking functionality.  Ideally we'd put the lock on the main binlog thread, but I'm not sure if it'd be more trouble than it's worth...

**Comment by rottenmu** [comment]
I know than can try it.

**Comment by rottenmu** [comment]
Can I use raft to implemnt it

**Comment by stym06** [comment]
We've implemented maxwell on a mesos environment with in-house ZK client that does runtime config-assignment using Zookeeper. It's been running on scale with more than 20 instances.

**Comment by leoChaoGlut** [comment]
#1591

**Comment by osheroff** [comment]
shipped a lightweight solution in 1.29.0
