### ISSUE TITLE
Getting error while reading binlogs

### ISSUE THREAD

**Issue by HarshitShihora7** [zendesk/maxwell#1495]
I have a Schemas in AWS RDS where binlog is enabled. but what i am trying to achieve is i have deployed my jar on one EC2 which will read for schema1 and another EC2 which will read for schema2.I have configured different schema names in the schema_host param of the config.properties. so the error that i face is below :

`[ERROR] 2020-05-20 09:39:48.198 [main] BinlogConnectorReplicator - Shutting down due to communication errors to Mysql
com.github.shyiko.mysql.binlog.network.ServerException: A slave with the same server_uuid/server_id as this slave has connected to the master; the first event 'mysql-bin-changelog.170291' at 4281521, the last event read from '/rdsdbdata/log/binlog/mysql-bin-changelog.170291' at 4305151, the last byte read from '/rdsdbdata/log/binlog/mysql-bin-changelog.170291' at 4305151.
        at com.github.shyiko.mysql.binlog.BinaryLogClient.listenForEventPackets(BinaryLogClient.java:946) ~[My.jar:?]
        at com.github.shyiko.mysql.binlog.BinaryLogClient.connect(BinaryLogClient.java:581) ~[My.jar:?]
        at com.github.shyiko.mysql.binlog.BinaryLogClient$7.run(BinaryLogClient.java:857) ~[My.jar:?]
        at java.lang.Thread.run(Thread.java:745) ~[?:1.8.0_111-internal]`

can you help me with this problem? or how can i fix this?

**Comment by osheroff** [comment]
>  A slave with the same server_uuid/server_id as this slave has connected to the master;

configure the two maxwell processes with different values of `--replica-server-id`.

**Comment by HarshitShihora7** [comment]
@osheroff It worked Thank you so much

**Comment by miked0004** [comment]
The [Deployment Docs](https://maxwells-daemon.io/deployment/#:~:text=maxscale%20replication%20proxy.-,Multiple%20Maxwells,-Maxwell%20can%20operate) say that `replica_server_id` is needed for MySql 5.5. & below. I'm running MySql 8.0 & have the same error.

Is the correct solution to use **arbitrary** but unique values for **both** `client_id` and `replica_server_id`? 

Thanks

**Comment by osheroff** [comment]
well `client_id` is a string and `replica_service_id` is an integer but roughly speaking you're right.

`client_id` is unique but should be re-used amongst any maxwell instances in a HA group.
`replica_server_id` should probably be unique amongst all maxwell instances.
