### ISSUE TITLE
Using maxwell with redis can corrupt messages if using bootstrapper in async mode

### ISSUE THREAD

**Issue by lucastex** [zendesk/maxwell#1497]
Hi @osheroff , me again :) 

After the reconnection problem solved in the other issue/pull request, our maxwell/redis environment is already running for some days in production.

In some cases, we had a chance to see "corrupted" messages, that was in form of an invalid json, and even with redis commands inside of it. You can see one example here:

```
"{\"database\":\"moskit\",\"oskit\",\"table\":\"project\",\"type\":\"bootstrap-insert\",
\"ts\":1590008497,\"data\":{\"id\":47908,\"created_by_id\":10113,\"customer_id\":7490,
\"date_created\":\"2019-11-28 18:38:38\",\"date_deleted\":null,\"last_updated\":\"2019-11-28 18:38:38\",
\"name\":\"Nome Projeto\",\"prevision_close_date\":null,\"responsible_id\":10113,\"source\":\"MANUAL\",
\"summary_id\":47908,\"step_id\":344,\"archived\":0,\
"archived_date\":null}}\r\n*3\r\n$5\r\nLPUSH\r\n$41\r\ncdc:search-service-worker:project:pending\r\n$389\r\n
{\"database\":\"moskit\",\"table\":\"p"
```
_line breaks on me, to make it better to read here in github_

We can see some problems in the message above:
- after the first "database:moskit", we can see another "oskit" property alone
- the message is not ended correctly: "table: p" is the end of the message
- after the end of the "correct" message, we can see a `\r\n*3\r\n$5LPUSH <queue_name>`. This is for sure the next redis command that would be sent after this.

Very strange at the first time, but after digging a little bit, I realized that every time this happens, was when we're running a bootstrap task. Then I found the same issue in some other projects that uses redis, and all of them, pointed to the same problem, that is that a Jedis instance is not thread safe as we can see here: https://github.com/xetorthio/jedis/wiki/Getting-started#using-jedis-in-a-multithreaded-environment

> You shouldn't use the same instance from different threads because you'll have strange errors. And sometimes creating lots of Jedis instances is not good enough because it means lots of sockets and connections, which leads to strange errors as well. A single Jedis instance is not threadsafe! To avoid these problems, you should use JedisPool, which is a threadsafe pool of network connections. You can use the pool to reliably create several Jedis instances, given you return the Jedis instance to the pool when done. This way you can overcome those strange errors and achieve great performance.

This makes sense, since we're running bootstrap in the default `async` mode, and bootstrap task was spanning another thread to make its job. Then, to make sure this is the problem, we've changed our bootstarp to the `sync` mode and stressed our environment a lot creating several bootstrap tasks, and then, we couldn't find the error again, not even one time.

This issue is to evidence the error, I'll work on a pull request to use a `JedisPool` inside `MaxwellRedisProducer` instead of the Jedis instance directly. 

Are you ok with this @osheroff ?

**Comment by osheroff** [comment]
yes indeed.  sorry you're catching all our bugs lucas!  thanks for fixing them tho...

**Comment by lucastex** [comment]
No problem! I know maxwell is being used widely and in most cases with kafka, but it is an awesome tool and helping us a lot with redis! Thanks for the hard work @osheroff
