### ISSUE TITLE
lack of error messages when unable to connect

### ISSUE THREAD

**Issue by ArachnidXiang** [zendesk/maxwell#1499]
<img width="876" alt="屏幕快照 2020-05-25 下午5 21 35" src="https://user-images.githubusercontent.com/19658960/82799470-af401f00-9eac-11ea-9c6a-38d507896009.png">

It was fine a few days ago, and today suddenly I can’t connect to mysql, but mysql can be used normally.Any solution to this?

**Comment by osheroff** [comment]
what's the rest of the stack trace?

**Comment by ArachnidXiang** [comment]
> what's the rest of the stack trace?

That's all displayed on the terminal.So I really don't know what to do.

**Comment by osheroff** [comment]
might want to check out the various suggestions here:

https://stackoverflow.com/questions/24835592/java-sql-sqlexception-connections-could-not-be-acquired-from-the-underlying-dat/26739038

of course make sure your mysql instance is up and running.  I'd definitely check for number of connections.  too bad there's not more info in the error message.

**Comment by xulek** [comment]
I had the same problem today when I didn't have the variable "default_time_zone = '+0:00'" defined in my.cnf. The old version of maxwell(1.22.6) displays a message that there is a problem with the database timezone. In the new version of maxwell(1.26.3) this message no longer appears. This is probably a bug in the new version of maxwell.

Old version:
`Using kafka version: 1.0.0
11:56:42,347 WARN  MaxwellMetrics - Metrics will not be exposed: metricsReportingType not configured.
11:56:42,629 ERROR Maxwell - SQLException: The server time zone value 'EEST' is unrecognized or represents more than one time zone. You must configure either the server or JDBC driver (via the serverTimezone configuration property) to use a more specifc time zone value if you want to utilize time zone support.`

in new version only this:
```
11:40:41,337 WARN  MaxwellMetrics - Metrics will not be exposed: metricsReportingType not configured.
11:40:42,728 ERROR Maxwell - SQLException: Connections could not be acquired from the underlying database
```

**Comment by ArachnidXiang** [comment]
> I had the same problem today when I didn't have the variable "default_time_zone = '+0:00'" defined in my.cnf. The old version of maxwell(1.22.6) displays a message that there is a problem with the database timezone. In the new version of maxwell(1.26.3) this message no longer appears. This is probably a bug in the new version of maxwell.
> 
> Old version:
> `Using kafka version: 1.0.0 11:56:42,347 WARN MaxwellMetrics - Metrics will not be exposed: metricsReportingType not configured. 11:56:42,629 ERROR Maxwell - SQLException: The server time zone value 'EEST' is unrecognized or represents more than one time zone. You must configure either the server or JDBC driver (via the serverTimezone configuration property) to use a more specifc time zone value if you want to utilize time zone support.`
> 
> in new version only this:
> 
> ```
> 11:40:41,337 WARN  MaxwellMetrics - Metrics will not be exposed: metricsReportingType not configured.
> 11:40:42,728 ERROR Maxwell - SQLException: Connections could not be acquired from the underlying database
> ```

Thank u.Although my error is different from yours, but I changed to the old version and it shows the error message.

**Comment by ArachnidXiang** [comment]
> might want to check out the various suggestions here:
> 
> https://stackoverflow.com/questions/24835592/java-sql-sqlexception-connections-could-not-be-acquired-from-the-underlying-dat/26739038
> 
> of course make sure your mysql instance is up and running. I'd definitely check for number of connections. too bad there's not more info in the error message.

Thanks for your help, I solved it.

**Comment by osheroff** [comment]
merged a fix that will show connection errors better in the future.  we apologize for the inconvienence.
