### ISSUE TITLE
maxwell CDC with Apache NiFi

### ISSUE THREAD

**Issue by xmlking** [zendesk/maxwell#150]
I am using maxwell CDC solution along with Apache NiFi and it is working great:
https://github.com/xmlking/nifi-examples/tree/master/oltp-cdc-olap

**Comment by wushujames** [comment]
Super awesome. Added to my CDC list: https://github.com/wushujames/mysql-cdc-projects/wiki

Can I ask a little about your architecture? You are using the Maxwell to write to Kafka, correct? The part of this that is specific to Nifi is the reading from Kafka and the parsing of the JSON that Maxwell emitted?

**Comment by xmlking** [comment]
yes Maxwell —> Kafka and NiFi connects to Kafka as client.
NiFi DataFlows helps to do custom transformation/aggregation specific to each consumer and target database.   
thanks for adding to the CDC list.

**Comment by osheroff** [comment]
good deal.  I should do a little ABOUT.md and add some related / consuming projects.  Let me know if you have an issues, and of course, PRs welcome.
