### ISSUE TITLE
About Mysql switch between main and backup

### ISSUE THREAD

**Issue by wanghangyu817** [zendesk/maxwell#1500]
![image](https://user-images.githubusercontent.com/18672877/82821223-453c6f80-9ed6-11ea-9e63-93f2fd150a08.png)

Can a retry mechanism be added to solve this problem

**Comment by osheroff** [comment]
it's really best to just have the service under the control of something that will restart it, ie `runit` or similar.

**Comment by lucastex** [comment]
http://supervisord.org/ can make the dirty job.
