### ISSUE TITLE
Techniques for joining maxwell data with application context

### ISSUE THREAD

**Issue by jl-gogovapps** [zendesk/maxwell#1525]
Hello, 
I've started experimenting with Maxwell for CDC, with the hope that I can use it to generate Audit logs.  
One requirement for audit logs is understanding who within the application made the change.  

I was hoping that the `thread_id` would be a viable way to create this linkage, and some have suggested publishing application context to a blackhole table.  This sounded promising, but seemed to collapse for me in the context of Connection Pooling, where the connection_id (thread_id for mysql) is reused.

I could refactor all my database tables to have a "last_modified_by_id", but I'm trying to avoid that, since it doesn't help for hard deletes, and requires quite a bit of overhaul across a very legacy application.  

I've been trying to determine if the transaction_id (xid) is accessible by an application (Sinatra/rails) in a relatively opaque way, does anyone have any experience here that might help me out?

Thanks in advance
JL

**Comment by osheroff** [comment]
I looked into this, under the hood, down into that deep deep cave that is mysql, and I don't have good news.  There's plenty of features that surround this, but nothing that seems to solve it.  `information_schema.innodb_trx` has a transaction id, sure, but it doesn't correspond to anything in the binlog.  If you're using XA style transactions there's a host of features lining up to give you back *that* XID.  But nothing baked in that seems to grant you the holy rites of passage that are knowing something correlated to the backend.

Here's some hacky ideas, you've probably thought of a lot of them:

- at the top and bottom of a web request, write the current thread_id into the BLACKHOLE table, along with whatever unique identifier you plan to put in your audit logs.  Assuming that you retain a connection for the duration of your request (which I believe activerecord does out of the box), everything done by that thread between the blackhole markers will be audited.
- do the same but do it per-transaction, hooking in right after your mysql client issues a BEGIN statement.  
- probably a bunch of variations on that theme.

this really *should* be available.

**Comment by jl-gogovapps** [comment]
@osheroff thank you so much for the response, I greatly appreciate it.

I went quite a distance with the Blackhole approach:
- Set up the blackhole table
- Created a concern (ruby) that would send thread ids and context data (a concern seemed like a relatively scalable way to do this across the system, with low lift)
- Created a kinesis stream
- Created a kinesis data analytics app to self join the stream based on the thread id over a window and produce a joined stream
- Created a KCL consumer to process the joined stream, manage audit tables, and generate audit logs

I got all the way to the end, when I realized that the thread_id was NOT unique per request.  This is because [sinatra] apps use of Connection pooling.  (Even if I didn't have a connection pool in the app, but pg bouncer, i think this would still be a problem).  So unless I missed something (which is certainly a possibility 😄  ) I couldn't figure out a way to tie the request ID to the Maxwell (or DMS btw, yes I tried that too 😂 ) transaction ID.

I also tried hooking into transactions.  This would be a lot harder to enforce across an app, but it was a last gap effort in terms of seeing if this approach was feasible at all.  However, that didn't seem to work either, because as you pointed out, that transaction id is not the same as the binlog id.  

With that said, did you have something else in mind for:
> do the same but do it per-transaction, hooking in right after your mysql client issues a BEGIN statement.

> If you're using XA style transactions there's a host of features lining up to give you back that XID
I'm not sure what those are (glanced a bit through https://github.com/zendesk/maxwell/issues/838), we've inherited (gasp) mysql 5.6

Alas, I think I've come to terms with having to do a couple things:
- Start implementing soft deletes as I migrate/refactor areas of the software
- Add columns to models to manage "who" performed the last update

This complexity aside, I just want to take a moment to say thanks and I've had a great early experience with Maxwell overall!

**Comment by osheroff** [comment]
> thread_id was NOT unique per request

thread_id's won't be unique per request (they'll be re-used), but depending on how you pool is setup I think they could be non-overlapping (serialized), couldn't they?  So you could put some markers in binlog that are like:

`  
   before do 
      cx.query("INSERT INTO blackhole.marker set thread_id = CONNECTION_ID(), web_request='341203981-XXX-XXXXX', state='started')
   end

  after do
      cx.query("INSERT INTO blackhole.marker set thread_id = connection_id(), web_request='341203981-XXX-XXXXX', state='finished')
  end
```

and then everything for that thread *between* those markers in the stream could be tied back to that web request.

In this scenario, you'd have to check out a single database connection for the entirety of the web request, which is what I think ActiveRecord does by default, though not the `connection_pool` gem.

Anyway, you know your stack better than I.  I may poke a bit more at this issue with a stick.

**Comment by jl-gogovapps** [comment]
Ahhh interesting.  That should, in theory, work.  And I agree, it seems viable with connection pooling as each request gets a connection/thread.

I'll have to think about how that would play with streams, joins, and kcl

Thanks for the suggestion!

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by jl-gogovapps** [comment]
Giving this some more thought, I have a question about the sharding, and want to test my understanding

- A solution, as described above, for 1 shard, 1 consumer:  Create a hash, on a "START" marker, put the request context from the blackhole table in the hash by thread id.  Subsequent transactions can look up that hash to get the right thread id.  When the "END" marker is received, clear the thread id from the hash.  Simple enough 

However, I'm not sure how multiple shards would work.  Reading the partitioning docs, it seems like the blackhole table would always publish to the same shard, and other transactions would be distributed between the two shards.  Is this accurate?

This would mean that consumers might not have received the START marker (or in the case of one consumer, the START marker could be out of order).

I think this could be resolved by using a Kinesis Data analytics app to publish to a _new_ stream partitioned by thread_id.  But before I jumped into that, I wanted to confirm these suspicions.

Thanks again advance, I'm appreciating your input on this thread

**Comment by osheroff** [comment]
can you describe more about your sharding setup?  In the context of a web request, is a single webserver writing to multiple shards or only one shard?  

If a single web request generally only touches one shard, the correct answer is definitely having one blackhole table per shard, as well as having one shard map to a unique kinesis partition. 

If a single web request can update multiple shards, the situation grows more complex.

**Comment by jl-gogovapps** [comment]
> can you describe more about your sharding setup? In the context of a web request, is a single webserver writing to multiple shards or only one shard?

Yea, so even though it's idealistic to some to have one API endpoint only manage one resource, I feel like this is a difficult requirement to meet in terms of: transactions, efficiency (network, developer speed and product experience), organization (especially in many legacy contexts).  That said, I'd be planning on having an endpoint update multiple columns in multiple tables.

> If a single web request generally only touches one shard, the correct answer is definitely having one blackhole table per shard, as well as having one shard map to a unique kinesis partition.

It's my understanding that each table/column is mapped to a specific shard by default (I definitely could be wrong here) based on a hashing algorithm (at a high level).  I think managing a CDC table per shard would be challenging because it would be hard to devise a "shim" or concern that could be inserted generically into a service and provide those "START"/"END" markers.

Is it possible to shard by thread_id?  If not, which I could understand, I arrive at the potential Kinesis repartitioning solution I described above where records are pumped into a new stream partitioned by thread_id

**Comment by osheroff** [comment]
oh, I see, you're talking about kinesis shards.  Amazon decided that instead of using kafka topic/partition terminology they'd borrow a noun from database land, thus throwing the world into great confusion.

out of the box, maxwell partitions ("shards", in kinesis land) by database;  this keeps everything nice and serialized but obviously has its scalability limits.  One can also choose to segment by table, tx_id, or the value of a column.  Currently there's no feature to partition by thread_id but it should be fairly trivial to add.  If you like, take on the code and add the feature.

**Comment by jl-gogovapps** [comment]
Closing this, as I think we are on our way with a viable audit log process.  Thanks so much for having this discussion with me, and letting me contribute!

**Comment by osheroff** [comment]
my pleasure, it's more or less how open source is supposed to work :)  hope everything goes well for you with your audits!  And sorry you're stuck developing audit logs, we've all been there :P
