### ISSUE TITLE
MaxWell collects no data from Alibaba's RDS

### ISSUE THREAD

**Issue by boy-xiaozhang** [zendesk/maxwell#1528]

**Comment by osheroff** [comment]
more information, please.

**Comment by boy-xiaozhang** [comment]
> more information, please.

Does MaxWell need to configure anything for Alibaba RDS to read? It is normal for me to read native Mysql, but alibaba's RDS cannot get the data and there is no exception

**Comment by wanghangyu817** [comment]
To read RDS, you need to connect the Maxwell process to the main library because the binlog is on the RDS main library

**Comment by wanghangyu817** [comment]
> > more information, please.
> 
> Does MaxWell need to configure anything for Alibaba RDS to read? It is normal for me to read native Mysql, but alibaba's RDS cannot get the data and there is no exception

To read RDS, you need to connect the Maxwell process to the main library because the binlog is on the RDS main library

**Comment by osheroff** [comment]
@boy-xiaozhang did you solve your issue?
