### ISSUE TITLE
Is there a way to filter out schema updates from particular databases or tables?

### ISSUE THREAD

**Issue by stym06** [zendesk/maxwell#1549]
the `filter` property does not output the row updates if enabled for a particular table/db. Anything similar for schema?

**Comment by osheroff** [comment]
If filtering is setup, *and* the particular DDL statement refers exclusively to a table (there's DDL statements that span multiple tables, things get a little weird), it should work exactly like row updates.  Please re-open this issue if it doesn't work as expected.

**Comment by stym06** [comment]
Schema changes for filtered tables are still maintained/updated in the schema database. Yes, the row updates don't come.
