### ISSUE TITLE
Hook up to slave database settings

### ISSUE THREAD

**Issue by david604** [zendesk/maxwell#1550]
Does anybody know how to hook up to slave database instead of master?

I read documentation, it says using Replication_host and etc. I tried it did not work.

My questions are,

1. When we hook to the slave database, does it read binlog relay files?
2. Do we still need to enable binlog in slave? it's so confusing.

Thanks for any suggestions

**Comment by osheroff** [comment]
sorry for the lag, david.  maxwell hooks up to the slave database as though the slave were a master, and the slave needs the `log_slave_updates` setting enabled.  Relay logs are purely internal to the slave.
