### ISSUE TITLE
Reopening #1549 Schema updates synced even after filtering

### ISSUE THREAD

**Issue by stym06** [zendesk/maxwell#1553]
#1549 
Hi,
The row updates are suppressed using the `filter` but schema changes like `ALTER` are still updated in the `schemas` db in Maxwell database

**Comment by osheroff** [comment]
Hi, 
If you need to fully remove tables/databases from being tracked you can use the `blacklist` option.  Please note that you should *not* use this.  ever.  Unless you need to.  But you probably shouldn't.  Unless you really really really want to.
