### ISSUE TITLE
Changing position on binlog manually to read (replay) old binlog data

### ISSUE THREAD

**Issue by lucastex** [zendesk/maxwell#1559]
Hi guys,

Is there any way to manually change the binlog position maxwell is reading from? We retain our binglog for 24h, and I want to know how can I point maxwell to read from 3 hours ago.

I imagine that the position column keep this data, but how can we discover the position of a given time?

Thank you,

[]s,

Lucas

**Comment by lucastex** [comment]
@osheroff Is this viable in any way?

Thanks,

**Comment by wanghangyu817** [comment]
> 嗨，大家好，
> 
> 有什么方法可以手动更改maxwell读取的二进制记录位置？我们将binglog保留24小时，我想知道如何指向maxwell从3小时前开始阅读。
> 
> 我想想位置列会保留这些数据，但是我们如何发现给定时间的位置呢？
> 
> 谢谢，
> 
> [] s，
> 
> 卢卡斯
if you can position or GTID, try modifying the positions table manually(I think so. You can try it)

**Comment by wanghangyu817** [comment]
> Hi guys,
> 
> Is there any way to manually change the binlog position maxwell is reading from? We retain our binglog for 24h, and I want to know how can I point maxwell to read from 3 hours ago.
> 
> I imagine that the position column keep this data, but how can we discover the position of a given time?
> 
> Thank you,
> 
> []s,
> 
> Lucas
if you can position or GTID, try modifying the positions table manually(I think so. You can try it)

**Comment by lucastex** [comment]
Thanks @wanghangyu817  but how can I discover the position number given a datetime....

:(

**Comment by osheroff** [comment]
you can't do it with maxwell alone.  but it should be easy enough to script; 

do like:

```
 mysql -e "show master status" # capture current master position
 mysqlbinlog -R -h XXX -u root -pXXX 'master.000005' | egrep '^#' | ...
 # from the above output, get the position in the binlog for a timestamp.  note that you may have to go back 
 # multiple files to find "3 hours ago".  
 now you can start maxwell with `--init_position`
```

**Comment by lucastex** [comment]
Thanks a lot @osheroff

**Comment by stym06** [comment]
You can also set Maxwell to start from a previous binlog file and position by altering the positions table columns `binlog_file` and `binlog_position`, and then restarting the application.

**Comment by osheroff** [comment]
closing, feel free to reopen
