### ISSUE TITLE
Maxwell config reload and service stop,DDL schemastore changes

### ISSUE THREAD

**Issue by jeanron100** [zendesk/maxwell#1561]
Hi,Maxwell team
we are now using maxwell as one component for Data Transmission Service,we have some suggestions :
1)for maxwell server managment,we have start option, and we need stop (not kill) option,if will be graceful
2)for maxwell configuration changes,(usually with filter_conf),we need to restart maxwell again, if there is one option to reload it without bounce maxwell service?
3)for DDL changes, for example, a new table created, schemastore is not reflected on tables( tables,columns ),in some cases, we need to change it manually,or init it again with the potential issue (data loss)

**Comment by osheroff** [comment]
1.  just send it a TERM signal, it's graceful. 
2. no.
3. schema is kept in a large initial capture (tables, columns, etc) and then a list of deltas that are applied on top of that.
