### ISSUE TITLE
lost data

### ISSUE THREAD

**Issue by zhouxb615** [zendesk/maxwell#1562]
discover some data of the type(update) be losted  and the type(insert,delete) is ok ,why? (the maxwell version is  maxwell-1.26.4)

**Comment by osheroff** [comment]
i have no idea what this means.  more info or a better translation, please.

**Comment by zhouxb615** [comment]
exsample: type---->  update
{
    "database": "test",
    "table": "maxwell",
    "type": "update",
    "ts": 1449786341,
    "xid": 940786,
    "commit": true,
    "data": {"id":1, "daemon": "Firebus!  Firebus!"},
    "old":  {"daemon": "Stanislaw Lem"}
  }
after one minutes data changed as below :
{
    "database": "test",
    "table": "maxwell",
    "type": "update",
    "ts": 1449786341,
    "xid": 940786,
    "commit": true,
    "data": {"id":1, "11111111111": "22222222222222222222"},
    "old":  {"daemon": "Stanislaw Lem"}
  }

when  Big Concurrent, some data will correct, but some data incorrect , the data look like losted

**Comment by osheroff** [comment]
I still don't really know what you're asking; perhaps ask someone with a bit better english to help?  I think you might be talking about the order of updates, which is generally not a problem depending on how you partition your data.

**Comment by zhouxb615** [comment]
thanks ! the issue  is solved
