### ISSUE TITLE
not support jaas authorization when producer is kafka

### ISSUE THREAD

**Issue by thomasbryant1024** [zendesk/maxwell#1564]
kafka producer：http://maxwells-daemon.io/config/#kafka-producer

The auth of Kafka is very common and important in the prod env. I was shocked that the maxwell doesn't  support the jass auth of kafka. Do hope Maxwell can provide any support of  kafka auth seriously.

**Comment by osheroff** [comment]
as far as i can tell all this stuff is baked into the standard kafka producer library which maxwell is built atop of.

if you follow (roughly) https://stackoverflow.com/questions/45756543/kafka-login-module-not-specified-in-jaas-config you should get there; in maxwell you'd pass `kafka.sasl.jaas.config=...`.
