### ISSUE TITLE
How to configure the timestamp precision to be ms

### ISSUE THREAD

**Issue by jiweicao-outreach** [zendesk/maxwell#1590]
Right now seems the default time format is yyyy-MM-dd HH:mm:ss.
How can I configure the timestamp output with milisecond precision?

Also, is the time as UTC?

**Comment by osheroff** [comment]
the fine is UTC yes.  Unfortunately mysql only ever sends second-based timestamps in the binlogs so millisecond timestamp precision is not availabe.
