### ISSUE TITLE
Failover instance of maxwell daemon

### ISSUE THREAD

**Issue by xcdr** [zendesk/maxwell#1594]
Hi.

We have replicated MySQL database in two DC (master<>master) and we want to make maxwell instances that works in failover mode.

I there any recommended setup?

**Comment by osheroff** [comment]
I'm working on some code for the next release that may address this; making maxwell instances HA has been an oft-requested feature. 

Is your multi-master setup hot/cold or hot/hot?  Does maxwell produce records to a single location or to both DCs?

Generally speaking you'd probably want to run both masters with `log_slave_updates = 1` and then have maxwell run off one server at a time, but a lot depends on your setup...

**Comment by osheroff** [comment]
hi @xcdr today I released maxwell v1.29.0 which includes high availability support via jgroups-raft.  Maybe it will work for your scenario.  Feel free to reopen this issue with any new information.
