### ISSUE TITLE
New Maxwell release

### ISSUE THREAD

**Issue by FanAs** [zendesk/maxwell#1600]
Hello @osheroff. Thank you for your great work!
Is it possible for you to release a new version of Maxwell?
There are some fixes (like SRID) that we need in production. We've been waiting for release for a month, and surely we can build it by ourself, but our deploy now depends on original github repo and we would like to keep it this way...
Thank you in advance,
Artyom from Livesport.

**Comment by osheroff** [comment]
Yeah no problem, will get to this today

**Comment by osheroff** [comment]
released.
