### ISSUE TITLE
Error: No matches for kafka version: 1.0.0   检测kafka版本

### ISSUE THREAD

**Issue by yaqianghan** [zendesk/maxwell#1608]
bin/maxwell --host='192.168.1.3' --port=3306 --user='duoletest' --password='359359' --producer=stdout                                         使用标准输出，也会检测kafka版本吗？  CentOS Linux release 7.7.1908 (Core)

**Comment by osheroff** [comment]
are you running maxwell from the correct directory?  please run the command with `bash -x` to see what's going on if you still are having problems.

**Comment by Trevor-zhang** [comment]
hi, @yaqianghan  could you tell me, how did you solve this problem?
