### ISSUE TITLE
gtid synchronization problem

### ISSUE THREAD

**Issue by yaqianghan** [zendesk/maxwell#1612]
If gtid is set to true, when the master-slave switch is performed, data cannot be automatically synchronized, and maxwell needs to be manually restarted for data synchronization

**Comment by osheroff** [comment]
what do you mean by "data cannot be automatically synchronized"?  Do you mean maxwell doesn't switch to the new host?

**Comment by yaqianghan** [comment]
> what do you mean by "data cannot be automatically synchronized"? Do you mean maxwell doesn't switch to the new host?
Yes, the data synchronization stopped after the master-slave switch, and I need to restart Maxwell to continue the synchronization

**Comment by yaqianghan** [comment]
> what do you mean by "data cannot be automatically synchronized"? Do you mean maxwell doesn't switch to the new host?

**Comment by yaqianghan** [comment]
> what do you mean by "data cannot be automatically synchronized"? Do you mean maxwell doesn't switch to the new host?

I only configured "gtid_mode=true"

**Comment by yaqianghan** [comment]
> what do you mean by "data cannot be automatically synchronized"? Do you mean maxwell doesn't switch to the new host?

Please help me; Thank you

**Comment by osheroff** [comment]
> Please help me; Thank you

I need you to give me a lot more detail about your problem; it's very hard to help if you only write 1 sentence answers.  I understand that translating your problem is difficult, but without many more details I'm left guessing.

**Comment by yaqianghan** [comment]
> > Please help me; Thank you
> 
> I need you to give me a lot more detail about your problem; it's very hard to help if you only write 1 sentence answers. I understand that translating your problem is difficult, but without many more details I'm left guessing.


The problem is this, I configure "gtid_mode=true", start the script, keep mysql always writing state, switch between master and slave, and then the data stops syncing after the switch is completed, and I need to manually restart Maxwell to continue the slave switch Continue to sync afterwards

**Comment by osheroff** [comment]
yes, you'll always need to restart maxwell in order to change masters.  Generally people use a VIP (virtual IP) that points to the active master.  When you want to promote a slave to a master, the VIP moves to the new server.  This then breaks your active connection, maxwell restarts, and continues.

You could also simply set `READ_ONLY` to "1" on the old master.  this will usually get maxwell to crash and restart.

**Comment by yaqianghan** [comment]
> yes, you'll always need to restart maxwell in order to change masters. Generally people use a VIP (virtual IP) that points to the active master. When you want to promote a slave to a master, the VIP moves to the new server. This then breaks your active connection, maxwell restarts, and continues.
> 
> You could also simply set `READ_ONLY` to "1" on the old master. this will usually get maxwell to crash and restart.

thank you for your reply
