### ISSUE TITLE
Facing problem to run maxwell for mysql8

### ISSUE THREAD

**Issue by naveenmodi10** [zendesk/maxwell#1621]
Having issue to run mysql8 with maxwell

pom.xml having below version for connector
            <artifactId>mysql-binlog-connector-java</artifactId>
            <version>0.23.2</version>

Getting event type ANONYMOUS_GTID for any DML transaction, which is not supported for this version.
Binlogs rotation is not happening at all.

**Comment by abhijitkumartech** [comment]
Pull out the latest code changes. It will work as per expectation. Tried and verified with the master branch.

**Comment by osheroff** [comment]
ok.  I will release a new connector j and get a maxwell release asap

**Comment by osheroff** [comment]
fixed in 1.29.1
