### ISSUE TITLE
Run Maxwell error

### ISSUE THREAD

**Issue by birkh8792** [zendesk/maxwell#1625]
![20201230131824](https://user-images.githubusercontent.com/74575713/103331601-b746e980-4aa1-11eb-9bf3-ba7f2e0ebe6b.png)

Error:(3, 19) java: 无法访问org.jgroups.JChannel
  错误的类文件: /D:/Java/maven/apache-maven-3.5.4/m2/repository/org/jgroups/jgroups/5.1.2.Final/jgroups-5.1.2.Final.jar!/org/jgroups/JChannel.class
    类文件具有错误的版本 55.0, 应为 52.0
    请删除该文件或确保该文件位于正确的类路径子目录中。

**Comment by birkh8792** [comment]
jdk is must java11?

**Comment by zhuoqianmingyue** [comment]
我尝试切换成 JDK 11  java version "11.0.10"  重新编译就好了。

**Comment by osheroff** [comment]
I.. don't speak this language but I think you're saying "you need JDK 11" which sounds right to me.

**Comment by pengweizhong** [comment]
This helps me, thank you
