### ISSUE TITLE
how to user kafka-clients 2.5.0

### ISSUE THREAD

**Issue by lijiawen** [zendesk/maxwell#1626]
i am interests to use kafka-clients 2.5.0,but it not work.

i copy the kafka-clients-2.5.0 dependencies to the lib dir, start maxwell with option  `--kafka_version 2.5.0` 

Error: No matches for kafka version: config.properties
Supported versions:
 - 0.10.0.1
 - 0.10.2.1
 - 0.11.0.1
 - 0.8.2.2
 - 0.9.0.1
 - 1.0.0

**Comment by osheroff** [comment]
latest kafka supported in forthcoming 1.32.0 release
