### ISSUE TITLE
bootstrapping performance regression from v1.24.2 to v1.25.0

### ISSUE THREAD

**Issue by macboy012** [zendesk/maxwell#1630]
I use `bootstrapper=sync` producing to Kafka from MySQL 8. I noticed after a recent upgrade bootstrapping performance got significantly slower than it used to be.

I tested out some version and found the regression to be from `v1.24.2` to `v1.25.0`, my test involved bootstrapping the same 100,000 rows.
`v1.24.2` completed in 7 seconds
`v1.25.0` completed 3 minutes and 7 seconds
~25 times slower!

I tested up through `v1.29.1` and performance does not improve.

From the changelog there's the message
>protect against lost connections during key queries (bootstrapping, heartbeats, postition setting)

Those changes are almost certainly related to this regression.

**Comment by osheroff** [comment]
woof.  will look into this.

**Comment by cosmostail** [comment]
`producer.push(row);
 Thread.sleep(1);
++insertedRows;`

I think that Thread.sleep(1) caused the problem for large dataset.

**Comment by osheroff** [comment]
fixed in v1.29.2

**Comment by macboy012** [comment]
Thanks for the prompt response!
