### ISSUE TITLE
MysqlSchemaCompactor

### ISSUE THREAD

**Issue by wlyu** [zendesk/maxwell#1632]
the problem about MysqlSchemaCompactor:
there is two maxwell (client_id_01  \client_id_02) connected to Mysql
client_id_02  update schema after  client_id_01 delete schema 
the schema (client_id_02  memory) not found int database
===============================
i will add a field "client_id" in maxwell.schema 
or
use different mysql  maxwell Metadata database?

**Comment by osheroff** [comment]
have you experienced a problem?  the code is written to honor multiple clients -- the compactor will only delete schemas up to the minimum of all clients `maxwell.positions` values.
