### ISSUE TITLE
can maxwell read Encrypted replication_password

### ISSUE THREAD

**Issue by spiderman106** [zendesk/maxwell#1633]
for IT security we need use encrypted replication_password, is maxwell can do that?

**Comment by osheroff** [comment]
please provide more details about your setup.  I'm not sure what "encrypted replication_password" means.

**Comment by spiderman106** [comment]
sorry, I mean when I start maxwell with command line, if I set --replication_password='encrypted string',  which is use to connect replication host, well this work?

**Comment by osheroff** [comment]
no.  mysql authentication simply doesn't work that way.

**Comment by spiderman106** [comment]
or can I config --replication_password in config.properties, and assign a encrypted password to --replication_password, and then decisie decrypte or not when parse config.properties?

**Comment by osheroff** [comment]
no, there is no support for anything like that.  you probably want to look into something like client side certificates?  Or something like that.  I really only understand your request insofar as you don't want to store a plaintext password on disk, but that's sort of just the reality of how these systems work. 

maybe you could roll your own something with `--env_config_prefix` and decrypting something off disk before passing it into maxwell via the environment.  I dunno.

**Comment by spiderman106** [comment]
ok, thanks for replying, I will find other way to handle this problem, close this issue
