### ISSUE TITLE
how do you connect to a amqps:// connection?

### ISSUE THREAD

**Issue by johnsimmons1980** [zendesk/maxwell#1636]
I've been trying to connect to secure amqp (to a  amazonMQ rabbit instance) but I keep getting timeouts. Think it's due to trying to connect on amqp://

does maxwell support amqps:// and if so how do you define it.

Many thanks

**Comment by osheroff** [comment]
have you tried connecting with `--rabbitmq_port=5671`?

**Comment by johnsimmons1980** [comment]
hi @osheroff 
yep thats what I had in the docker-compose file:

`version: '2'
services:
  cdctest:
    restart: "always"
    image: "zendesk/maxwell:v1.29.2"
    logging:
      options:
        max-size: '500m'
        max-file: '3'
    ports:
      - 9110:8080
    volumes:
      - /var/log/apps:/var/log/apps
      - ./config/log4j2.xml:/app/log4j2.xml
    command: >
      bin/maxwell --user="*******" --password="**************" --host="**.***.*.***"
      --producer='rabbitmq' --rabbitmq_host="b-414b7823-****-****-****-************.mq.eu-west-2.amazonaws.com" --rabbitmq_port="5671"
      --rabbitmq_user="***************" --rabbitmq_pass="*********************************************"
      --rabbitmq_message_persistent='true'
      --rabbitmq_exchange='main.exchange' --rabbitmq_exchange_type='topic'
      --rabbitmq_routing_key_template='tis.cdc.%table%.%type%'
      --rabbitmq_exchange_durable='true' --rabbitmq_virtual_host="/"
      --recapture_schema=true
      --metrics_type=http
    environment:
      LOGGING_LEVEL: DEBUG
      LOGGING_LEVEL_MCHANGE: WARN
`

getting this in the logs:

`cdctest_1  | Using kafka version: 1.0.0
cdctest_1  | 2021-01-28 09:58:19 INFO  Starting Maxwell. maxMemory: 8038383616 bufferMemoryUsage: 0.25
cdctest_1  | 2021-01-28 09:58:19 WARN  An unexpected connection driver error occured (Exception message: Connection reset)
cdctest_1  | 2021-01-28 09:58:19 INFO  Stopping 0 tasks
cdctest_1  | 2021-01-28 09:58:19 ERROR cause: 
cdctest_1  | java.lang.RuntimeException: java.io.IOException
cdctest_1  | 	at com.zendesk.maxwell.producer.RabbitmqProducer.<init>(RabbitmqProducer.java:38) ~[maxwell-1.29.2.jar:1.29.2]
cdctest_1  | 	at com.zendesk.maxwell.MaxwellContext.getProducer(MaxwellContext.java:401) ~[maxwell-1.29.2.jar:1.29.2]
cdctest_1  | 	at com.zendesk.maxwell.Maxwell.startInner(Maxwell.java:213) ~[maxwell-1.29.2.jar:1.29.2]
cdctest_1  | 	at com.zendesk.maxwell.Maxwell.start(Maxwell.java:183) ~[maxwell-1.29.2.jar:1.29.2]
cdctest_1  | 	at com.zendesk.maxwell.Maxwell.main(Maxwell.java:286) ~[maxwell-1.29.2.jar:1.29.2]
cdctest_1  | Caused by: java.io.IOException
cdctest_1  | 	at com.rabbitmq.client.impl.AMQChannel.wrap(AMQChannel.java:129) ~[amqp-client-5.7.3.jar:5.7.3]
cdctest_1  | 	at com.rabbitmq.client.impl.AMQChannel.wrap(AMQChannel.java:125) ~[amqp-client-5.7.3.jar:5.7.3]
cdctest_1  | 	at com.rabbitmq.client.impl.AMQConnection.start(AMQConnection.java:375) ~[amqp-client-5.7.3.jar:5.7.3]
cdctest_1  | 	at com.rabbitmq.client.impl.recovery.RecoveryAwareAMQConnectionFactory.newConnection(RecoveryAwareAMQConnectionFactory.java:64) ~[amqp-client-5.7.3.jar:5.7.3]
cdctest_1  | 	at com.rabbitmq.client.impl.recovery.AutorecoveringConnection.init(AutorecoveringConnection.java:156) ~[amqp-client-5.7.3.jar:5.7.3]
cdctest_1  | 	at com.rabbitmq.client.ConnectionFactory.newConnection(ConnectionFactory.java:1106) ~[amqp-client-5.7.3.jar:5.7.3]
cdctest_1  | 	at com.rabbitmq.client.ConnectionFactory.newConnection(ConnectionFactory.java:1063) ~[amqp-client-5.7.3.jar:5.7.3]
cdctest_1  | 	at com.rabbitmq.client.ConnectionFactory.newConnection(ConnectionFactory.java:1021) ~[amqp-client-5.7.3.jar:5.7.3]
cdctest_1  | 	at com.rabbitmq.client.ConnectionFactory.newConnection(ConnectionFactory.java:1182) ~[amqp-client-5.7.3.jar:5.7.3]
cdctest_1  | 	at com.zendesk.maxwell.producer.RabbitmqProducer.<init>(RabbitmqProducer.java:33) ~[maxwell-1.29.2.jar:1.29.2]
cdctest_1  | 	... 4 more
cdctest_1  | Caused by: com.rabbitmq.client.ShutdownSignalException: connection error
cdctest_1  | 	at com.rabbitmq.utility.ValueOrException.getValue(ValueOrException.java:66) ~[amqp-client-5.7.3.jar:5.7.3]
cdctest_1  | 	at com.rabbitmq.utility.BlockingValueOrException.uninterruptibleGetValue(BlockingValueOrException.java:36) ~[amqp-client-5.7.3.jar:5.7.3]
cdctest_1  | 	at com.rabbitmq.client.impl.AMQChannel$BlockingRpcContinuation.getReply(AMQChannel.java:502) ~[amqp-client-5.7.3.jar:5.7.3]
cdctest_1  | 	at com.rabbitmq.client.impl.AMQConnection.start(AMQConnection.java:317) ~[amqp-client-5.7.3.jar:5.7.3]
cdctest_1  | 	at com.rabbitmq.client.impl.recovery.RecoveryAwareAMQConnectionFactory.newConnection(RecoveryAwareAMQConnectionFactory.java:64) ~[amqp-client-5.7.3.jar:5.7.3]
cdctest_1  | 	at com.rabbitmq.client.impl.recovery.AutorecoveringConnection.init(AutorecoveringConnection.java:156) ~[amqp-client-5.7.3.jar:5.7.3]
cdctest_1  | 	at com.rabbitmq.client.ConnectionFactory.newConnection(ConnectionFactory.java:1106) ~[amqp-client-5.7.3.jar:5.7.3]
cdctest_1  | 	at com.rabbitmq.client.ConnectionFactory.newConnection(ConnectionFactory.java:1063) ~[amqp-client-5.7.3.jar:5.7.3]
cdctest_1  | 	at com.rabbitmq.client.ConnectionFactory.newConnection(ConnectionFactory.java:1021) ~[amqp-client-5.7.3.jar:5.7.3]
cdctest_1  | 	at com.rabbitmq.client.ConnectionFactory.newConnection(ConnectionFactory.java:1182) ~[amqp-client-5.7.3.jar:5.7.3]
cdctest_1  | 	at com.zendesk.maxwell.producer.RabbitmqProducer.<init>(RabbitmqProducer.java:33) ~[maxwell-1.29.2.jar:1.29.2]
cdctest_1  | 	... 4 more
cdctest_1  | Caused by: java.net.SocketException: Connection reset
cdctest_1  | 	at java.net.SocketInputStream.read(SocketInputStream.java:186) ~[?:?]
cdctest_1  | 	at java.net.SocketInputStream.read(SocketInputStream.java:140) ~[?:?]
cdctest_1  | 	at java.io.BufferedInputStream.fill(BufferedInputStream.java:252) ~[?:?]
cdctest_1  | 	at java.io.BufferedInputStream.read(BufferedInputStream.java:271) ~[?:?]
cdctest_1  | 	at java.io.DataInputStream.readUnsignedByte(DataInputStream.java:293) ~[?:?]
cdctest_1  | 	at com.rabbitmq.client.impl.Frame.readFrom(Frame.java:91) ~[amqp-client-5.7.3.jar:5.7.3]
cdctest_1  | 	at com.rabbitmq.client.impl.SocketFrameHandler.readFrame(SocketFrameHandler.java:184) ~[amqp-client-5.7.3.jar:5.7.3]
cdctest_1  | 	at com.rabbitmq.client.impl.AMQConnection$MainLoop.run(AMQConnection.java:598) ~[amqp-client-5.7.3.jar:5.7.3]
cdctest_1  | 	at java.lang.Thread.run(Thread.java:834) [?:?]
cdctest_1  | 2021-01-28 09:58:19 INFO  Stopped all tasks
cdctest_1  | 2021-01-28 09:58:19 DEBUG Shutdown complete: true
cdctest_1  | java.lang.RuntimeException: java.io.IOException
cdctest_1  | 	at com.zendesk.maxwell.producer.RabbitmqProducer.<init>(RabbitmqProducer.java:38)
cdctest_1  | 	at com.zendesk.maxwell.MaxwellContext.getProducer(MaxwellContext.java:401)
cdctest_1  | 	at com.zendesk.maxwell.Maxwell.startInner(Maxwell.java:213)
cdctest_1  | 	at com.zendesk.maxwell.Maxwell.start(Maxwell.java:183)
cdctest_1  | 	at com.zendesk.maxwell.Maxwell.main(Maxwell.java:286)
cdctest_1  | Caused by: java.io.IOException
cdctest_1  | 	at com.rabbitmq.client.impl.AMQChannel.wrap(AMQChannel.java:129)
cdctest_1  | 	at com.rabbitmq.client.impl.AMQChannel.wrap(AMQChannel.java:125)
cdctest_1  | 	at com.rabbitmq.client.impl.AMQConnection.start(AMQConnection.java:375)
cdctest_1  | 	at com.rabbitmq.client.impl.recovery.RecoveryAwareAMQConnectionFactory.newConnection(RecoveryAwareAMQConnectionFactory.java:64)
cdctest_1  | 	at com.rabbitmq.client.impl.recovery.AutorecoveringConnection.init(AutorecoveringConnection.java:156)
cdctest_1  | 	at com.rabbitmq.client.ConnectionFactory.newConnection(ConnectionFactory.java:1106)
cdctest_1  | 	at com.rabbitmq.client.ConnectionFactory.newConnection(ConnectionFactory.java:1063)
cdctest_1  | 	at com.rabbitmq.client.ConnectionFactory.newConnection(ConnectionFactory.java:1021)
cdctest_1  | 	at com.rabbitmq.client.ConnectionFactory.newConnection(ConnectionFactory.java:1182)
cdctest_1  | 	at com.zendesk.maxwell.producer.RabbitmqProducer.<init>(RabbitmqProducer.java:33)
cdctest_1  | 	... 4 more
cdctest_1  | Caused by: com.rabbitmq.client.ShutdownSignalException: connection error
cdctest_1  | 	at com.rabbitmq.utility.ValueOrException.getValue(ValueOrException.java:66)
cdctest_1  | 	at com.rabbitmq.utility.BlockingValueOrException.uninterruptibleGetValue(BlockingValueOrException.java:36)
cdctest_1  | 	at com.rabbitmq.client.impl.AMQChannel$BlockingRpcContinuation.getReply(AMQChannel.java:502)
cdctest_1  | 	at com.rabbitmq.client.impl.AMQConnection.start(AMQConnection.java:317)
cdctest_1  | 	... 11 more
cdctest_1  | Caused by: java.net.SocketException: Connection reset
cdctest_1  | 	at java.base/java.net.SocketInputStream.read(SocketInputStream.java:186)
cdctest_1  | 	at java.base/java.net.SocketInputStream.read(SocketInputStream.java:140)
cdctest_1  | 	at java.base/java.io.BufferedInputStream.fill(BufferedInputStream.java:252)
cdctest_1  | 	at java.base/java.io.BufferedInputStream.read(BufferedInputStream.java:271)
cdctest_1  | 	at java.base/java.io.DataInputStream.readUnsignedByte(DataInputStream.java:293)
cdctest_1  | 	at com.rabbitmq.client.impl.Frame.readFrom(Frame.java:91)
cdctest_1  | 	at com.rabbitmq.client.impl.SocketFrameHandler.readFrame(SocketFrameHandler.java:184)
cdctest_1  | 	at com.rabbitmq.client.impl.AMQConnection$MainLoop.run(AMQConnection.java:598)
cdctest_1  | 	at java.base/java.lang.Thread.run(Thread.java:834)
cdctest_cdctest_1 exited with code 1`

any great ideas?

**Comment by osheroff** [comment]
ok, i read through the code, setting up the port is definitively not enough, one has to call at the very least the `setURI` method.

https://github.com/rabbitmq/rabbitmq-java-client/blob/c8003121d3c92549623cc1ee8b57c56c7ea34bb5/src/main/java/com/rabbitmq/client/ConnectionFactory.java

you comfortable making a PR where we accept `amqps://...` as a connection option or you need me to?

**Comment by johnsimmons1980** [comment]
@osheroff, unfortunately, I'm not a Java dev, (i'm ops for my sins). Would it be possible for you to make the change as I fear if I went near it, maxwell would never work again.

Many thanks

**Comment by osheroff** [comment]
can you try running https://github.com/zendesk/maxwell/pull/1640?

my code is probably correct but I don't have a rabbit installation to test with.

**Comment by johnsimmons1980** [comment]
@osheroff 
Many thanks 👍🏻  that works really well (only thing you still have to supply the `--rabbitmq_host` var as well otherwise it defaults to localhost. Do you have any idea when it may be released fully?

**Comment by osheroff** [comment]
lemme rectify the situation with rabbitmq_host, it shouldn't be clobbering the value in the uri if it's not specified. 

I've got this and another fix somewhere that i'll stick into the next release.  sometime this week i think.

**Comment by osheroff** [comment]
@johnsimmons1980 corrected the situation with rabbitmq_host, can you try the PR again?

**Comment by osheroff** [comment]
released in 1.30.0
