### ISSUE TITLE
maxwell not reconnecting

### ISSUE THREAD

**Issue by eirik-andersen** [zendesk/maxwell#1642]
We have a windows server running MySQL 5.7 in our datacenter and a linux server running docker container og maxwell 1.29.1 and rabbitmq in azure. 

My issue is that maxwell disconnects from the binary log without any errors and notification.
I can monitor my MySQL server and see that maxwell disconnects from reading the binary log, but when I connect to the container there is no error logged.

If I kill the maxwell thread in MySQL, then maxwell immediately reconnects and  writes the statements below to the log.

```
20:09:23,543 INFO  BinlogConnectorReplicator - Binlog disconnected.
20:09:23,561 WARN  BinlogConnectorReplicator - replicator stopped at position: binlog.001545:486865573 -- restarting
20:09:23,782 INFO  BinaryLogClient - Connected to 10.1.1.148:3306 at binlog.001545/486865573 (sid:6379, cid:288755)
20:09:23,783 INFO  BinlogConnectorReplicator - Binlog connected.
```

So it seems like there is a drop in connection between our datacenter and Azure and this is not picked up by maxwell that believes that it's still connected to MySQL's binlog. 

I have set the reconnect option on the JDBC driver.

My current fix is to restart the docker image for maxwell every hour to prevent long downtime.

**Comment by osheroff** [comment]
https://github.com/zendesk/maxwell/pull/1643 may be helpful here.

> I can monitor my MySQL server  and see that maxwell disconnects from reading the binary log

what do you mean by this?   What are you seeing?  

The JDBC reconnect option has no affect here, as the binlog connection doesn't/can't use JDBC.

**Comment by eirik-andersen** [comment]
When maxwell is reading from the binlog the connection will show up in the MySQL process list as show in the picture below.

![maxwell-binlogdump](https://user-images.githubusercontent.com/52753676/106712379-2790df80-65f9-11eb-8017-665e6b3bec31.gif)


We are using PRTG Network Monitor to monitor that maxwell is connected to MySQL and reading from the binlog. PRTG is running the query below every 10 minutes. This query will return 0 if maxwell is not connected and if it's connected it will return how many seconds maxwell has been connected since last connection. The picture below shows the graph from the PRTG monitor the last days. The red dots indicate downtime. The downtime is not ended before the container running maxwell is restarted. We started out with restarting every 6 hours, but this gave us too much downtime so we changed it to every hour.

`SELECT ifnull(sum(processlist_time),0) AS ant FROM performance_schema.threads WHERE processlist_command = 'Binlog Dump' AND processlist_user = 'maxwell'`

![prtg-maxwell](https://user-images.githubusercontent.com/52753676/106710752-c962fd00-65f6-11eb-8c4d-31beb7692ace.gif)

There is nothing written to the maxwell log when the connection disappears from the processlist in MySQL.  When I restart the container running maxwell after the connection to MySQL is lost. There is a warning in the maxwell log shown in the picture below. 

![maxwell-restart](https://user-images.githubusercontent.com/52753676/106711908-8ace4200-65f8-11eb-9b12-a9a89c529bcd.gif)

**Comment by osheroff** [comment]
can you try to catch maxwell in this state?  I'd be curious to know:

- what the maxwell mysql thread looks like from `SHOW FULL PROCESSLIST`
- what the output of `jstack` on maxwell looks like when it enters this state.

**Comment by eirik-andersen** [comment]
Hi, I just had downtime for the maxwell. 

My monitoring of the problem is based on looking in the output of `SHOW FULL PROCESSLIST` to see if the maxwell user is connected to Binlog Dump. So when maxwell stops working the maxwell user dissapears from `SHOW FULL PROCESSLIST`

I took 2 jstack dumps with a few minutes apart. Files is attached

when taking the second dump I ran docker logs <containername>. The image below shows the end of the log. And it show no messages the last 20 minutes.

![image](https://user-images.githubusercontent.com/52753676/107019974-9b222080-67a2-11eb-89d9-648f399b8dab.png)


[jstack1.txt](https://github.com/zendesk/maxwell/files/5931639/jstack1.txt)
[jstack2.txt](https://github.com/zendesk/maxwell/files/5931640/jstack2.txt)

.

**Comment by eirik-andersen** [comment]
Hi, just had another downtime for maxwell so attached is the jstack for this downtime too. The `SHOW FULL PROCCESSLIST` is still missing the maxwell replication thread.

[jstack3.txt](https://github.com/zendesk/maxwell/files/5934049/jstack3.txt)

**Comment by eirik-andersen** [comment]
the picture below how long the maxwell replication thread has been connected to MySQL. maxwell is automatically restartet every hour but where there is red dots maxwell has been disconnecten from MySQL. It seems to be a repetitive  pattern. After 6 restarts it stops working.

![image](https://user-images.githubusercontent.com/52753676/107064942-6fbc2780-67dc-11eb-8306-0c8f1d184d92.png)

**Comment by osheroff** [comment]
these show the same state; Maxwell is utterly convinced the socket is alive
and well and is listening for events as normal.

can you also gather some tcp info from maxwell sides during an event?
 `lsof -p MAXWELL_PID` and `netstat -an`?

I suppose your mysql server is something of a black box?  (ie we're not
going to get network connection info out of it)

**Comment by eirik-andersen** [comment]
will do on the next crach :)

I have access to the MySQL server that is running on windows.

**Comment by osheroff** [comment]
ok, could be useful to try to get equivalent network connection info from the windows box too; my guess is that the connection is for whatever reason half-dead; your linux box has no idea that the windows box (or a roluter in between) has closed the connection.

After you get that info (and, likely, we determine there's really not much to do on our end about it), feel free to upgrade to 1.30.0 and enable @timbertson's `--binlog_heartbeat` code; this should prevent zombie maxwells.

**Comment by eirik-andersen** [comment]
Hi,
I have collected the requested connection information from linux and windows. Is it possible to send it to you without posting for everyone?

**Comment by osheroff** [comment]
Sure.  ben dot osheroff at gmail

**Comment by osheroff** [comment]
the suspicion here is a half-closed connection between maxwell and the server.  Not much to do if that's the case, although the `--binlog_heartbeat` option should help lots here.  Gonna close and reopen if new info comes to light.
