### ISSUE TITLE
Bootstrapping all tables of a database and setting up replica based on maxwell log format

### ISSUE THREAD

**Issue by albehrens** [zendesk/maxwell#1649]
Hey everyone,

I am a big fan of this application. I have two questions and I was wondering how I can solve this with Maxwell?

1. Is there a way of bootstrapping all tables of a database or do I need to specify every table explicitly?
2. How do I set up database replication using `maxwell` and `maxwell-boostrap` or do you recommend not relying on Maxwell for replication and instead using instruction from the [official MySQL docs](https://dev.mysql.com/doc/refman/5.7/en/replication-configuration.html).

Thank you

**Comment by osheroff** [comment]
Hi,
1) yeah you have to specify each table individually 
2) I don't recommend doing this.  The JSON maxwell produces is in no way loss-less, and there's a host of other concerns as well.

**Comment by albehrens** [comment]
Okay, good to know. Thank you for your answer
