### ISSUE TITLE
How to set the timezone parameter ?

### ISSUE THREAD

**Issue by shuaizhong95** [zendesk/maxwell#1650]
when parsse date type of mysql binlog; there is  a problem;  The parsed date is eight hours later than them in MySQL .such as the date in mysql is 2020-02-08 14:30:00, but the parsed date is 2020-02-08 06:30:00.  so how to set timezone parameter。

**Comment by osheroff** [comment]
Maxwell assumes that both the client and server will be in UTC timezone.   that's really the best way to make things work, otherwise things get crazy confusing.
