### ISSUE TITLE
Increase throughput to Kinesis

### ISSUE THREAD

**Issue by albehrens** [zendesk/maxwell#1664]
I have a table of 2.400.000 records. It takes 15 minutes to bootstrap the entire table. This is too long. My kinesis stream has 1 shard and 1 shard can take 1000 PUT/second. So I thought I increase the number of shards to 2. I hoped that this cuts the time in half, but in fact it was still 15 minutes.

Do you know how I can bootstrap faster? Is it a configuration of the KPL? Is it a limitation of Maxwell or the machine that runs Maxwell?

**Comment by osheroff** [comment]
What maxwell version?  There was a bad and embarrassing performance issue in bootstrapping until a release or so ago

**Comment by albehrens** [comment]
We are using `maxwell-1.31.0`, which is the latest version, if I am correct.

**Comment by albehrens** [comment]
I have asked the same question in the KPL repository: https://github.com/awslabs/amazon-kinesis-producer/issues/342

Here is what they advise:
> Please check your Kafka message key and kinesis producer message partition strategy. By default it will do hash on Kafka message key as Kinesis shard key, so if your messages are having the same key or default null keys, the messages will go into the same shard, the additional shard is not used.

How does Maxwell work? Does always use the same key?

**Comment by albehrens** [comment]
Okay, I found `producer_partition_by` in the config.properties. When I set this to any value, maxwell quits with this message:

<img width="1515" alt="Screenshot 2021-03-01 at 09 34 29" src="https://user-images.githubusercontent.com/51319339/109471693-69cf0480-7a71-11eb-9c16-af6c6cafb3f4.png">

When I also set `producer_partition_by` via the CLI like `--producer_partition_by=random` it not only works, but KPL is actually using both shards.
