### ISSUE TITLE
maxwell crashed after add index on a none including table

### ISSUE THREAD

**Issue by plutoid** [zendesk/maxwell#1668]
Hi,

after I added a index on a table, which not on in including table list, the maxwell crashed with below error log.

adding index:
alter table send_record_log add INDEX cust_phone_idx(cust_id, phone);

error log:
com.zendesk.maxwell.schema.ddl.InvalidSchemaError: Couldn't find table 'send_record_log' in database uniqlo at com.zendesk.maxwell.schema.Database.findTableOrThrow(Database.java:55) at 
com.zendesk.maxwell.schema.ddl.TableAlter.resolve(TableAlter.java:37) at 
com.zendesk.maxwell.schema.ddl.TableAlter.resolve(TableAlter.java:12) at 
com.zendesk.maxwell.schema.AbstractSchemaStore.resolveSQL(AbstractSchemaStore.java:58) at 
com.zendesk.maxwell.schema.MysqlSchemaStore.processSQL(MysqlSchemaStore.java:103) at 
com.zendesk.maxwell.replication.BinlogConnectorReplicator.processQueryEvent(BinlogConnectorReplicator.java:316) at 
com.zendesk.maxwell.replication.BinlogConnectorReplicator.processQueryEvent(BinlogConnectorReplicator.java:338) at 
com.zendesk.maxwell.replication.BinlogConnectorReplicator.getRow(BinlogConnectorReplicator.java:610) at
com.zendesk.maxwell.replication.BinlogConnectorReplicator.work(BinlogConnectorReplicator.java:180) at 
com.zendesk.maxwell.util.RunLoopProcess.runLoop(RunLoopProcess.java:34) at com.zendesk.maxwell.Maxwell.startInner(Maxwell.java:225) at 
com.zendesk.maxwell.Maxwell.start(Maxwell.java:158) at com.zendesk.maxwell.Maxwell.main(Maxwell.java:247)

then I tried adding similar record on  `maxwell.tables` and `maxwell.columns`, maxwell worked again.

maxwell version: maxwell-1.24.0.jar

thanks and regards,
Hua

**Comment by osheroff** [comment]
what's your `filter` configuration exactly?  was the tables/database not included, or was it blacklisted?
