### ISSUE TITLE
The image in docker can't support ARM64 platform

### ISSUE THREAD

**Issue by charlotte-xiao** [zendesk/maxwell#1673]
The requested image's platform (linux/amd64) does not match the detected host platform (linux/arm64/v8) and no specific platform was requested

**Comment by osheroff** [comment]
yyyeah.  we're currently not building for arm64.  Happy to take PRs here...

**Comment by charlotte-xiao** [comment]
I make a Docker Image which is support amd for maxwell.
Just input "docker pull charlottexiao123/maxwell:1.0" have a try.
But this  image isn't made by maven image.Can I take PRs for you check?

**Comment by VictorVasconcelos** [comment]
PR: #1775
