### ISSUE TITLE
The Dockerfile maybe have some problem

### ISSUE THREAD

**Issue by charlotte-xiao** [zendesk/maxwell#1675]
[https://github.com/zendesk/maxwell/blob/master/Dockerfile](url)
Environment To Build Docker:Arm64v8

The 16th line is
`&& mv /workspace/target/maxwell-$MAXWELL_VERSION/maxwell-$MAXWELL_VERSION/* /app/ \`
I think the right code is 
`    && mv /workspace/maxwell-$MAXWELL_VERSION/* /app/ \`

**Comment by osheroff** [comment]
nope, the code is correct.
