### ISSUE TITLE
Azure mysql8: com.github.shyiko.mysql.binlog.network.AuthenticationException

### ISSUE THREAD

**Issue by plutoid** [zendesk/maxwell#1688]
Hi,

I met below authentication issue situation, not sure what's happening, any helps are appreciated. 
env:
azure mysql8

maxwell version:
maxwell/lib/mysql-binlog-connector-java-0.23.1.jar
maxwell/lib/maxwell-1.26.4.jar
seting:
| binlog_row_image | FULL  |
| gtid_mode     | ON    |

user:
| GRANT SELECT, REPLICATION SLAVE, REPLICATION CLIENT ON *.* TO `m`@`%` |
| GRANT ALL PRIVILEGES ON `maxwell`.* TO `m`@`%`                        |

| GRANT SELECT, REPLICATION SLAVE, REPLICATION CLIENT ON *.* TO `m@mysql-cn-chinaeast2-maptrial01`@`%` |
| GRANT ALL PRIVILEGES ON `maxwell`.* TO `m@mysql-cn-chinaeast2-maptrial01`@`%`                        |

| m                                | %         |
| m@mysql-cn-chinaeast2-maptrial01 | %         |
| azure_superuser                  | 127.0.0.1 |
| azure_superuser                  | localhost |
| mysql.infoschema                 | localhost |
| mysql.session                    | localhost |
| mysql.sys                        | localhost |

error log:

![image](https://user-images.githubusercontent.com/1091981/116697343-a4173c80-a9f5-11eb-9430-92503f7dd04f.png)

update:

It worked well  on below versions, maybe some authentication issue on binlog-connector.
maxwell/lib/maxwell-1.24.0.jar
mysql-binlog-connector-java-0.20.0.jar

Many thanks!

**Comment by osheroff** [comment]
please upgrade.  I believe this was fixed here in v1.30.0.
