### ISSUE TITLE
Cannot read init_position from configuration file

### ISSUE THREAD

**Issue by ljpojo** [zendesk/maxwell#1690]
Cannot read init_position from configuration file

![UNTITLED](https://user-images.githubusercontent.com/68684456/117416507-07502400-af4c-11eb-9f5e-d0e229e5d282.png)

**Comment by zcw5116** [comment]
Maxwell can be configured via a java properties file, specified via --config or named "config.properties" in the current working directory. Any command line options (except init_position, replay, kafka_version and daemon) may be specified as "key=value" pairs.

**Comment by ljpojo** [comment]
For what reason, don't support init_partition in the configuration file?

**Comment by osheroff** [comment]
this was done to prevent users from shooting themselves in the foot; the notion is that `init_position` is something you'll want to use once, when recovering from a bad state, and that leaving it in a config file makes it easy to screw up.

Curious, what's your need to have it in a config file?
