### ISSUE TITLE
Intellij IDEA run maxwell error

### ISSUE THREAD

**Issue by Trevor-zhang** [zendesk/maxwell#1697]
I run maxwell jar on the terminal on MAC using the following command
`bin/maxwell --user='maxwell' --password='maxwell' --host='x.x.x.x' --producer=stdout `no problem

When I run the main() of Maxwell.java on IDEA of MAC, the input args is `--user='maxwell' --password='maxwell' --host='x.x.x.x' --producer=stdout`, console report error
```
20:54:24,021 ERROR Maxwell-SQLException: Communications link failure

The last packet sent successfully to the server was 0 milliseconds ago. The driver has not received any packets from the server.
```

**Comment by Trevor-zhang** [comment]
I tried to modify the mysql-related configuration, but still did not solve the problem.

**Comment by osheroff** [comment]
this is definitely just a problem trying to connect to the mysql database.  I don't have any insight as to why it can't connect from IDEA.
