### ISSUE TITLE
binlog replicator keeps disconnecting and reconnecting on new positions

### ISSUE THREAD

**Issue by Shukla-Ankur** [zendesk/maxwell#1700]
maxwell v1.26.3
mysql Ver 8.0.19 for Linux on x86_64 (MySQL Community Server - GPL)

I am running a mysql innodb cluster in group replication, with one primary. The primary died and there was a failover. 
There were 2 maxwell running: 

1. M1 runs on the primary machine (P) itself, 
2. M2 runs on another machine but connects to same primary P
Since primary P crashed, M1 also died but instead of determining the failover, M2 also died.

I restarted M1 on new Primary but M1 kept disconnecting/reconnecting without any specific error
`
07:50:30,319 INFO  BinlogConnectorReplicator - Binlog disconnected.
07:50:30,419 WARN  BinlogConnectorReplicator - replicator stopped at position: binlog.000524:268528708 -- restarting
07:50:30,422 INFO  BinaryLogClient - Connected to 10.0.3.114:3306 at binlog.000524/268528708 (sid:0, cid:1436766)
07:50:30,422 INFO  BinlogConnectorReplicator - Binlog connected.
07:50:30,422 INFO  BinlogConnectorReplicator - Binlog disconnected.
07:50:30,522 WARN  BinlogConnectorReplicator - replicator stopped at position: binlog.000524:268528708 -- restarting
07:50:30,525 INFO  BinaryLogClient - Connected to 10.0.3.114:3306 at binlog.000524/268528708 (sid:0, cid:1436767)
07:50:30,525 INFO  BinlogConnectorReplicator - Binlog connected.
07:50:30,525 INFO  BinlogConnectorReplicator - Binlog disconnected.
07:50:30,625 WARN  BinlogConnectorReplicator - replicator stopped at position: binlog.000524:268528708 -- restarting
07:50:30,628 INFO  BinaryLogClient - Connected to 10.0.3.114:3306 at binlog.000524/268528708 (sid:0, cid:1436768)
07:50:30,628 INFO  BinlogConnectorReplicator - Binlog connected.
07:50:30,628 INFO  BinlogConnectorReplicator - Binlog disconnected.
07:50:30,728 WARN  BinlogConnectorReplicator - replicator stopped at position: binlog.000524:268528708 -- restarting
07:50:30,731 INFO  BinaryLogClient - Connected to 10.0.3.114:3306 at binlog.000524/268528708 (sid:0, cid:1436769)
07:50:30,731 INFO  BinlogConnectorReplicator - Binlog connected.
07:50:30,731 INFO  BinlogConnectorReplicator - Binlog disconnected.
07:50:30,831 WARN  BinlogConnectorReplicator - replicator stopped at position: binlog.000524:268528708 -- restarting
07:50:30,834 INFO  BinaryLogClient - Connected to 10.0.3.114:3306 at binlog.000524/268528708 (sid:0, cid:1436770)
07:50:30,834 INFO  BinlogConnectorReplicator - Binlog connected.`

And this goes on. Maxwell does not stop but keeps disconnecting and reconnecting at forward positions.
I tried these config options to maxwell

1. Passed no  replica_server_id and used the old client_id
2. Changed replica_server_id and used old client_id
3. Changed both
In first 2 cases, maxwell kept disconnecting/reconnecting.
In 3rd case, it worked. 

To check if binlog file was not corrupt, I used mysqlbinlog utility to dump the binlogs to a file and validated that the position mentioned in --init-position option to maxwell was fine.

So finally 3 doubts
1. maxwell M2 should have detected primary failover and connected to replica machine. For this feature to work, do the names of binlog files need to be same on both machines? What conditions must be met?
2. Can you please explain the reason for disconnect/reconnect?
3. I used gtid=ON with maxwell but in table maxwell.positions, gtid_set is null. How to use gtid correctly so that maxwell does not rely on binlog file name?

**Comment by osheroff** [comment]
> a mysql innodb cluster in group replication

Ok, I don't think I've seen an instance of group replication in the wild.

> To check if binlog file was not corrupt, I used mysqlbinlog utility to dump the binlogs to a file and validated that the position mentioned in --init-position option to maxwell was fine.

can you be more specific about "was fine"?  What events exactly are at that binlog position?  If I'm understanding group replication correctly, the servers operate completely independently of each other and so in this case Maxwell M1 was trying to access a binlog file/position that it got from the old master (P1) on the new master (P2).  Which would explain the disconnection loop.

> maxwell M2 should have detected primary failover and connected to replica machine. For this feature to work, do the names of binlog files need to be same on both machines? What conditions must be met?

Can you be more specific about your mysql setup?  How does the failover happen?  Are you moving a VIP that represents the master or what?

> I used gtid=ON with maxwell but in table maxwell.positions, gtid_set is null. How to use gtid correctly so that maxwell does not rely on binlog file name?

you're definitely going to want GTID in this case.  you need to pass `--gtid` to maxwell in order to enable its functionality.
