### ISSUE TITLE
maxwell can not capture binlog continuously

### ISSUE THREAD

**Issue by zybQAQ** [zendesk/maxwell#1702]
In our PROD environment，I test maxwell to capture mysql binlog. In the beginning，maxwell will capture binlog from master mysql normally，but after about 25 minutes，maxwell do not capture binlog and logs didn't throw any exceptions,just throw 
`Test of PooledConnection` again and again.  In fact,at this time, the master mysql always produce binlog normally.
 Have any ideas about this situation?

 maxwell config in detail:
`# config:host,replication_host are not same,replication_host,schema_host are same,  other config are default config,maxwell version:1.33  master mysql version:5.7`
`docker run -d  zendesk/maxwell bin/maxwell --name prod-maxwell --user='maxwell' \
--password='xxxx' --host=xxxx --port=3306 \
--replication_host='xxxxxxx' \
--replication_port=3306 \
--replication_user='xxxx' --replication_password='xxxx' \
--schema_host='xxxxxxxxxxxxxxxxxx' \
--schema_port=3306 \
--schema_user='xxx' --schema_password='xxxxxx' \
--producer=kafka --kafka.bootstrap.servers=xxxxx:9092 \
--kafka_topic=maxwell --log_level=debug`

**Comment by osheroff** [comment]
can you paste the log here?  thanks.

**Comment by zybQAQ** [comment]
> can you paste the log here? thanks.

Thanks for your attention,this problem had been solved, the reason is our mysql server were deployed in aliyun RDS sever, maxwell server in local,we use vpn to conncet mysql server , this vpn has some problem ,our Ops solved it . I think this problem
has nothing to do with maxwell.I will close this issue~
