### ISSUE TITLE
PRs for Improving Multi-Tenant DB Support

### ISSUE THREAD

**Issue by redcape** [zendesk/maxwell#1720]
Hey, this isn't an issue, but I wasn't sure how else to raise this discussion.

I want to get thoughts on accepting PRs to improve support for multi-tenant/DB-per-user/larger DB instances, specifically larger in terms of 100K- databases with some small-ish number (< 100) of tables in each one. Let's try not to discuss whether having this many DBs is a good idea, just the fact these use-cases exist across different companies and aren't well-served by existing OSS CDC capture products.

Here's some changes that should be made to support this use-case and some light benchmarks after the appropriate changes were made on a 70K DB, 1M Table, 6M column instance:

1. Don't do n^2 scans on database diffs / improve startup time from 12m to 3m by moving from ArrayList storage to LinkedHashMap for databases.  https://github.com/zendesk/maxwell/pull/1718
2. Parallel initial schema capture - this will be slow regardless, but running in parallel greatly improves capture time. (7x-8x on increase in speed with DB load remaining under 2% - using 6 threads). Basically this is just run multiple SchemaCapturer instances in parallel over different subsets of databases.
3. Perform memory optimizations through immutable objects - make ColumnDefs and TableColumnLists immutable and intern them. This is all about optimizing on the fact that we see the same column and table definitions over and over in multi-tenant DBs. We can reduce memory, improve L2/L3 cache hit-rate and take a negligible hit on modify performance when DDL changes occur to rebuild these immutable objects. This doesn't hurt existing use-case performance where DDL changes occur infrequently and greatly improves memory usage for multi-tenant use-cases.  This is all without adding a "special" multi-tenant mode that knows some tables are implicitly the same, maxwell just performs better.
- Schema retained size went from 350MB -> 140MB with ColumnDef immutability + TableColumnList internal immutable object. This could drop ~110MB further by making immutability at the table/PK level, but this would require more refactoring. https://github.com/zendesk/maxwell/pull/1719
 
4. Related to above, translate these more compact representations into the maxwell database model to greatly improve load time and time to store the schema.
- I haven't fully thought through how to do this, but understand the need to be careful / worry about automatic schema-upgrade. 
```
 - sha1 columnList as key (compute once, store w/ immutable obj) (order is based on id, which maybe is a bad idea?, store ordinal?)
 - table stores sha1 byte reference to column, has own sha1 that includes pk, name,
table(tableSha1, tbl_name, pkCols, columnSha1) <- works well for repetitive tables or repetitive DBs
- database_tables (db_id, tableSha1)
—— to protect against changes to schema / sha1 definition, sha1 is stored only locally - we use smart monotonically incrementing UUID / server-id - followed by timestamp or something
```

5. With frequent DDL changes, the `schemas` table can get rather large, rather quick. Improve on this through checkpointing. (12min startup -> 3 min startup, can we improve this further?)
 - This sort of exists, but maybe not with gtid? It becomes easier when the schema is smaller through above changes. Need to look into/understand existing process better before making suggestions.

**Comment by osheroff** [comment]
merged and released

**Comment by osheroff** [comment]
@redcape if you want to keep track of the other proposals you've got in here plz split them into their own issues.
