### ISSUE TITLE
Help needed: Using CustomProducer

### ISSUE THREAD

**Issue by dedaels** [zendesk/maxwell#1723]
Hi everyone,
may you can help me.
I have tried to set up a custom producers. but it does not work.
Even if I add the example custom producer and its factory from this repo. So I added them to the /lib dir.
I also added _"custom_producer.factory=com.zendesk.maxwell.example.producerfactory.CustomProducerFactory"_ to the proprties file.
Everytime I start maxwell he said he cant find the class.
_Invalid value for custom_producer.factory, class 'com.zendesk.maxwell.example.producerfactory.CustomProducerFactory' not found_

Could anyone tell me, what I am doing wrong?

**Comment by osheroff** [comment]
sorry, which files did you add to the lib dir?

**Comment by quanhieuluan** [comment]
I can not start maxwell with custom producer too.
After complied custom producer and factory's java file to class files, I also compress it to jar for, then put class files, jar file into /lib directory, but it's not work by showing not found error.
The value in custom_producer.factory and class name is matching.

**Comment by quanhieuluan** [comment]
I try this pattern and it worked:
1. create directory hierarchy exactly same as the custom producer class's package
```
$ mkdir -p com/zendesk/maxwell/example/producerfactory
```
2. Create custom producer class in the directory above
3. Make jar file with producer class
```
$ jar -cvf custom-producer.jar com/zendesk/maxwell/example/producerfactory/*.class
```
4. Copy the jar file to maxwell's /lib
5. Start maxwell

**Comment by osheroff** [comment]
so is this solved?

**Comment by dedaels** [comment]
Thanks a lot guys!
