### ISSUE TITLE
Must Create Maxwell Database ?

### ISSUE THREAD

**Issue by darionyaphet** [zendesk/maxwell#173]
Hi ~

I have read [Introducing Maxwell, a mysql-to-kafka binlog processor](http://planet.mysql.com/entry/?id=5992024)  found maxwell is a wonderful component to sync MySQL Binary Log into Kafka and I want to replace our origin python scripts . 

And now , I have a question: 

maxwell will create a maxwell database on each MySQL instance which it reading ?

Maybe could store this metadata in a MySQL instance such as hive

**Comment by osheroff** [comment]
hi @darionyaphet, yes, Maxwell will create a database named `maxwell` on each instance, to store schema snapshots as well as its replication position.  Currently we don't have plans to implement any alternative storage for this state, although I haven't ruled out someday putting all the state in kafka itself. 

The reasoning is that I wanted maxwell (a) recoverable -- any process of maxwell requires no local state, and so may pick up where another maxwell left off, and (b) low ops-overhead -- I didn't want to require more bits of architecture than necessary.

**Comment by darionyaphet** [comment]
Thank you for you relay @osheroff , I know what you mean keep schema metadata and replication point in reading MySQL instance would reduce another storage , it's very useful . Just a small question , our product environment or DBA maybe not allow create another database instance on each replication slave machine . I try to put this in a config to point where to storage metadata . Thank you for you great work and useful help :)

**Comment by osheroff** [comment]
I see, so you just want to be able to configure a different server to store schemas and positions in?

**Comment by darionyaphet** [comment]
I'm not sure . I wish to design a common metadata schema .  Store in MySQL maybe not a goods idea for example MySQL has single point problem .

**Comment by osheroff** [comment]
ok, not quite sure what you're after, but you can check out https://github.com/zendesk/maxwell/blob/master/src/main/java/com/zendesk/maxwell/schema/Schema.java as a starting point -- that's the in-memory representation of the schema.  I'll close this issue out, but feel free to re-open it if you have something more specific.
