### ISSUE TITLE
Unhandled QueryEvent inside transaction

### ISSUE THREAD

**Issue by Shukla-Ankur** [zendesk/maxwell#1733]
RDS MySQL v8.0.23
Maxwell v1.33.1 (last commit e8671240e7f2a8e68ce968147853f0578c621bfc)

Seeing the following error for all the maxwell clients running for a MySQL server.

`3550 [WARN] BinlogConnectorReplicator: Unhandled QueryEvent @ mysql-bin-changelog.022317:29296 inside transaction: QueryEventData{threadId=102626, executionTime=0, errorCode=0, database='coaching', sql='REPLACE INTO Learner(user_id,company_id,org_id,state,added_on,group_ids,language_code,updated_on,env) VALUES ("138b934564d00000","1408381230044991479","1408381228034092097","ACTIVE",1624619227,"[]","en-US",0,'prod-us')'}`

binlog file data for above warn log

```
SET @@SESSION.GTID_NEXT= 'ANONYMOUS'/*!*/;
# at 29206
#210818 17:09:22 server id 518713287  end_log_pos 29296 CRC32 0xf96ec867 	Query	thread_id=102626      	exec_time=0	error_code=0
SET TIMESTAMP=1629286762/*!*/;
SET @@session.sql_mode=1073741824/*!*/;
/*!\C utf8mb3 *//*!*/;
SET @@session.character_set_client=33,@@session.collation_connection=33,@@session.collation_server=255/*!*/;
BEGIN
/*!*/;
# at 29296
#210818 17:09:22 server id 518713287  end_log_pos 29599 CRC32 0x52e65022 	Query	thread_id=102626      	exec_time=0	error_code=0
use `coaching`/*!*/;
SET TIMESTAMP=1629286762/*!*/;
REPLACE INTO Learner(user_id,company_id,org_id,state,added_on,group_ids,language_code,updated_on,env) VALUES ("xxxxxx","xxxxxxxx","xxxxxxxxx","ACTIVE",1624619227,"[]","en-US",0,'prod-us')
/*!*/;
# at 29599
#210818 17:09:22 server id 518713287  end_log_pos 29630 CRC32 0x2f86456d 	Xid = 28309766
COMMIT/*!*/;
# at 29630
```

Observations here:
1. This is happening intermittently. Some events flow through while some do not.
2. I'm using same version of maxwell and mysql on several other machines. However, this is happening on a specific RDS. I checked older similar issues and found that this might be because 'binlog_format' might not be correctly picked as 'ROW'. Verified this on the machine and the variable is correct. I also stopped the maxwell clients and restarted several times.
3. I am running maxwell with a filter `exclude: *.*, include: coaching.*` However, I can see these logs for other DBs which are to be excluded also.
4. I went through the code in BinlogConnectorReplicator to see when this specific warning is thrown. Based on that, I added more logs for debugging. Following is data in log file for another event. 1756 is just an unique# to identify the related logs. 

```
68304242 [WARN] BinlogConnectorReplicator: 1756 original event:Event{header=EventHeaderV4{timestamp=1629358718000, eventType=QUERY, serverId=518713287, headerLength=19, dataLength=88, nextPosition=227485, flags=8}, data=QueryEventData{threadId=63107, executionTime=0, errorCode=0, database='db2', sql='BEGIN'}}
68304242 [WARN] BinlogConnectorReplicator: 1756 TR event_type:QUERY
68304242 [WARN] BinlogConnectorReplicator: Unhandled QueryEvent @ mysql-bin-changelog.022558:227485 inside transaction: QueryEventData{threadId=63107, executionTime=0, errorCode=0, database='db2', sql='/* update SyncCompanyTracker */ update sync_company_tracker set cname='xxxxx', enabled=1, lock_request_id=null, state='DONE', state_updated_timestamp=1629358718358, sync_type='LiLContent', tag=null where id=3'}
```

**Comment by osheroff** [comment]
what this means is that one of your client connections is still doing statement-based replication.  this can happen if you switch to row-based replication in runtime (using `set GLOBAL ...`) but a client (not a maxwell client, but an application client) has a long lived connection to the server.  

I suggest you reboot the application responsible for the `REPLACE` statements; the error should go away.

**Comment by Shukla-Ankur** [comment]
tried this, have not faced this issue for now. Closing this
