### ISSUE TITLE
Encoding issues with special chars

### ISSUE THREAD

**Issue by Shukla-Ankur** [zendesk/maxwell#1737]
mysql version: 8.0.23
maxwell version: 1.33.1 (last commit e8671240e7f2a8e68ce968147853f0578c621bfc)

Seeing encoding issues on maxwell output.
This issue is seen intermittently, mostly when multiple inserts/updates are done in single transaction.
I checked the mysql binlog to see if mysql table charSet and collation might have some issues. I checked maxwell code and saw the JDBC always uses UTF-8 character Set.

table charSet and collation: 
`ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci`

Mysql binlog logs
```
#210901 12:28:29 server id 1  end_log_pos 169017361     Write_rows: table id 177 flags: STMT_END_F
### INSERT INTO `test`.`test0`
### SET
###   @1='André'
### INSERT INTO `test`.`test0`
### SET
###   @1='González'
# at 169017361
```

Events output in stdout/kafka
```
{"database":"test","table":"test0","type":"insert","ts":1630499309,"xid":391050737,"xoffset":0,"data":{"name":"Andr??"}}
{"database":"test","table":"test0","type":"insert","ts":1630499309,"xid":391050737,"commit":true,"data":{"name":"Gonz??lez"}}
```

**Comment by Shukla-Ankur** [comment]
any updates on this? I can intermittently reproduce this with single row updates also. 
With same maxwell jar on different machines, this was consistently seen on 1 machine while never on another.
Seems like there could be an encoding issue with one of the dependencies on maxwell

**Comment by osheroff** [comment]
what is the difference between the machines?  I've literally never seen an issue like this one...

**Comment by Shukla-Ankur** [comment]
I ran these 2 on a mac and Linux machine.
However, even if we consider one single machine, I am able to intermittently repro this issue, both for single and multi row upserts.
Tried this out on Linux machine running v16.04 and then v18.04 hoping there might be a system library dependency. Same issue in both cases. So my hypothesis was proven wrong.

**Comment by osheroff** [comment]
are you able to repro the issue on specific row/data?  Or does the same
data/row intermittently fail/succeed?

**Comment by Shukla-Ankur** [comment]
I am able to get this issue on different rows.
On same rows, I am not able to intermittently reproduce this issue. Sometimes the issue is seen, sometimes not.

**Comment by Shukla-Ankur** [comment]
Closing this because of no updates
