### ISSUE TITLE
Output some form of the DDL in kafka

### ISSUE THREAD

**Issue by lynch0227** [zendesk/maxwell#174]
Hi Guys,

When I test the maxwell, I find it only can send the DML to kafka, but DDL, like create,drop,alter.
Do I miss something? or it can't support this feature?

And I also can't make sure which database the table is created in from DEBUG log.
e.g.
17:47:13,088 DEBUG SchemaChange - SQL_PARSE <- "create table t (id int auto_increment primary key,name varchar(10))"

**Comment by osheroff** [comment]
Hi @lynch0227, currently Maxwell only outputs DML, not DDL. Outputting DDL to the stream is on a hazy wishlist of features that have been asked for, but I don't have that particular need.   What's your use case?

**Comment by lynch0227** [comment]
Hi  @Osheroff,

I want to consume the mysqlbinlog to greenplum database from kafka.
So I need to get the whole DDL and DML script.

**Comment by osheroff** [comment]
K.  It's easy enough to spit out the dml as a separate event, you think the raw SQL from the `create table` or whatever will apply cleanly to greenplum?  Longer term when I was thinking about this feature I wanted to give back the parsed DDL in some form (ideally JSON), but I have no particular urgency to implement that.

**Comment by xmlking** [comment]
would be nice if we can produce DDLs to a Kafka topic in [JSON Schema](http://json-schema.org/) format or utilize  Kafka schema-registry

**Comment by xmlking** [comment]
@osheroff I would like to emit DDL changes to a kafka topic. Can you please point me where I can tap DDL changes in the code base?

```sql
{
  "databaseName" : "inventory",
  "tableName" : "customers",
  "ddl" : "CREATE TABLE customers\n(\n  id INT(11) PRIMARY KEY NOT NULL AUTO_INCREMENT,\n  first_name VARCHAR(255) NOT NULL,\n  last_name VARCHAR(255) NOT NULL,\n  email VARCHAR(255) NOT NULL\n)"
}
```
PS: developers in my team working on Talend Data Fabric are asking me for DDL events.

**Comment by osheroff** [comment]
@xmlking I've got the basics of that going here: https://github.com/zendesk/maxwell/pull/344/files.  Here's the gist of I/O:

```

mysql> create table foo ( id int(11) primary key, a varchar(255) );
{
  "type": "table-create",
  "database": "test",
  "table": "foo",
  "def": {
    "database": "test",
    "charset": "utf8mb4",
    "table": "foo",
    "columns": [
      {
        "type": "int",
        "name": "id",
        "signed": true
      },
      {
        "type": "varchar",
        "name": "a",
        "charset": "utf8mb4"
      }
    ],
    "primary-key": [
      "id"
    ]
  }
}


mysql> alter table foo add column b datetime after id;

{
  "type": "table-alter",
  "database": "test",
  "table": "foo",
  "old": {
    "database": "test",
    "charset": "utf8mb4",
    "table": "foo",
    "columns": [
      {
        "type": "int",
        "name": "id",
        "signed": true
      },
      {
        "type": "varchar",
        "name": "a",
        "charset": "utf8mb4"
      }
    ],
    "primary-key": [
      "id"
    ]
  },
  "def": {
    "database": "test",
    "charset": "utf8mb4",
    "table": "foo",
    "columns": [
      {
        "type": "int",
        "name": "id",
        "signed": true
      },
      {
        "type": "datetime",
        "name": "b"
      },
      {
        "type": "varchar",
        "name": "a",
        "charset": "utf8mb4"
      }
    ],
    "primary-key": [
      "id"
    ]
  }
}

mysql> drop table foo;
{"type":"table-drop","database":"test","table":"foo"}
```

**Comment by osheroff** [comment]
Look like about what you'd want? 

There's some open questions before the thing merges, though:

- should the DDL be mixed into the general kafka stream?  How would it get mixed in if the data stream is partitioned by table or primary key? 
- should it be able to live on its own topic?  
- would it be necessary to output the original SQL?

**Comment by xmlking** [comment]
1. should the DDL be mixed into the general kafka stream? How would it get mixed in if the data stream is partitioned by table or primary key?
- prefer separate topic as the consumers of for this data are different then consumers of main stream.
should it be able to live on its own topic?
would it be necessary to output the original SQL?
- some cases we need field lengths e.g.,  int(11) and varchar(256). If you are not intend to include  length field, we can at least derive from raw SQL.

**Comment by wushujames** [comment]
Once you start emitting DDL to Kafka, you are getting very close to "schema registry stored in Kafka". FYI, this is what Debezium does. They store their schema registry in Kafka (instead of how Maxwell stores it in mysql), and then also (kinda) support people reading from the Schema registry topic in order to listen to mysql schema changes.

**Comment by xmlking** [comment]
I think Confluent's Schema Registry also uses Kafka as its underlying storage mechanism.

Maxwell as a library should provide more versatile options for users to consume Schema changes.  i.e., Kafka Schema Topic as well as Avro formatted DML that can be used with `Schema Registry` when maxwell is bundled as Kafka connector.

**Comment by nabeelmoidu** [comment]
I'm working on a Data sanitization project on mysql data, and using maxwell as part of it. Would be great to see this implemented.
Having the DDL on a separate topic seems better, with the original sql preserved as necessary to recreate the table on a new database.

**Comment by osheroff** [comment]
feature added in 1.4.0.  DDL goes to a separate topic and is configurable.
