### ISSUE TITLE
No docker image for v1.34.0 release

### ISSUE THREAD

**Issue by chriskirkland** [zendesk/maxwell#1744]
There is no tag for the [zendesk/maxwell](https://hub.docker.com/r/zendesk/maxwell/tags?page=1&ordering=last_updated) image on Dockerhub for the [v1.34.0](https://github.com/zendesk/maxwell/releases/tag/v1.34.0) release.  Was that intentional or just an accidental omission?

We don't have a particular need for that release today, but I wanted to understand if there's a formal release process or expectation that each git release will have a corresponding Docker image version.  Historically, it looks like each git release has a corresponding image tag.

**Comment by osheroff** [comment]
hmph, this is all dependent on docker hub building and pushing.  but I know there's been changes in their policies.  i'll look.

**Comment by osheroff** [comment]
new releases going forward are being lovingly pushed to docker hub.
