### ISSUE TITLE
Map to different kafka topics based on the row content

### ISSUE THREAD

**Issue by gangluo-addepar** [zendesk/maxwell#1746]
Currently we are able to specify a templated Kafka topic with database/table/type so to send updates with different values to different topics. I wonder if it is possible today, or if it is on the roadmap in the future, to route updates based on the content of the row.

For example, I have a table `users`
```
ID  |  Username  |  Org
 1   |       test1       |  O1
 2   |       test2       |  O1
 3   |       test3       |  O2
```

I want to route the update those those rows to different Kafka topic based on the value from `Org` column, such that first 2 rows go to topic "O1" while 3rd row goes to topic "O2"

**Comment by osheroff** [comment]
It's possible with a javascript filter -- you can compute `kafka_topic` based on data inside the row.  See `example/filter.js` inside this repo.
