### ISSUE TITLE
Support for binlog_row_image = minimal

### ISSUE THREAD

**Issue by StormLordMikey** [zendesk/maxwell#175]
We turned on row-based replication in our mysql database but we also changed the binlog_row_image to be minimal rather than full.  When we did this, Maxwell was logging the following message: "binlog_row_image must be FULL"
From our understanding minimal row image will log only changed columns, and columns needed to identify rows which should be enough for our purposes.  This will avoid performance issues.  Is there any plan to support MINIMAL binlog_row_image?

**Comment by osheroff** [comment]
poked my head into this last night: https://github.com/zendesk/maxwell/pull/179

doesn't look too bad from where I stand.  Need to make sure that it doesn't affect performance for the other cases, but I don't think it will.

**Comment by jpeyper** [comment]
Is there any progress on this?

**Comment by osheroff** [comment]
nope.  patches welcome of course, I just don't have the time right now to push this over the finish line.

**Comment by osheroff** [comment]
well, that bit of psychology seems to have worked.

https://github.com/zendesk/maxwell/pull/199

**Comment by osheroff** [comment]
fixed in https://github.com/zendesk/maxwell/releases/tag/v0.16.2
