### ISSUE TITLE
Sending final heartbeat: 1634631700868     stopping replicator

### ISSUE THREAD

**Issue by nanfangyoumeng-an** [zendesk/maxwell#1759]
binlog没有最新的日志就会断掉，请大神在线解答！！！！！！！！！

**Comment by osheroff** [comment]
sorry, I can't read this.

**Comment by ljwtorch** [comment]
I use Maxwell to synchronize the MySQL database on the Hong Kong server with a server in mainland China. After running for 3-4 hours, I see the log message 'INFO MaxwellContext - Sending final heartbeat: 1706848518690.' How should I troubleshoot the cause of the interruption?

below is part of log

`09:57:22,765 WARN  Filter - using exclude/include/includeColumns is deprecated.  Please update your configuration to use: 
09:57:22,770 WARN  Filter - filter = "exclude: *.*, include: songuo_biz_platform.*, include: songuo_production.*, exclude: *.*, include: *.support_work_orders, include: *.support_work_order_comments, include: *.games, include: *.game_libraries, include: *.orders, include: *.order_games, include: *.products, include: *.taggings, include: *.tag_terms, include: *.tag_term_details, include: *.system_requirements, include: *.sku_profiles, include: *.sku_profile_details"
09:57:22,779 WARN  MaxwellMetrics - Metrics will not be exposed: metricsReportingType not configured.
09:57:24,547 INFO  SchemaStoreSchema - Creating maxwell database
09:57:26,721 INFO  ProducerConfig - ProducerConfig values: 
	acks = 1
	batch.size = 16384
	bootstrap.servers = [sonkwo-bj-data001:9092, sonkwo-bj-data002:9092, sonkwo-bj-data003:9092]
	buffer.memory = 33554432
	client.id = 
	compression.type = snappy
	connections.max.idle.ms = 540000
	enable.idempotence = false
	interceptor.classes = null
	key.serializer = class org.apache.kafka.common.serialization.StringSerializer
	linger.ms = 0
	max.block.ms = 60000
	max.in.flight.requests.per.connection = 5
	max.request.size = 1048576
	metadata.max.age.ms = 300000
	metric.reporters = []
	metrics.num.samples = 2
	metrics.recording.level = INFO
	metrics.sample.window.ms = 30000
	partitioner.class = class org.apache.kafka.clients.producer.internals.DefaultPartitioner
	receive.buffer.bytes = 32768
	reconnect.backoff.max.ms = 1000
	reconnect.backoff.ms = 50
	request.timeout.ms = 30000
	retries = 0
	retry.backoff.ms = 100
	sasl.jaas.config = null
	sasl.kerberos.kinit.cmd = /usr/bin/kinit
	sasl.kerberos.min.time.before.relogin = 60000
	sasl.kerberos.service.name = null
	sasl.kerberos.ticket.renew.jitter = 0.05
	sasl.kerberos.ticket.renew.window.factor = 0.8
	sasl.mechanism = GSSAPI
	security.protocol = PLAINTEXT
	send.buffer.bytes = 131072
	ssl.cipher.suites = null
	ssl.enabled.protocols = [TLSv1.2, TLSv1.1, TLSv1]
	ssl.endpoint.identification.algorithm = null
	ssl.key.password = null
	ssl.keymanager.algorithm = SunX509
	ssl.keystore.location = null
	ssl.keystore.password = null
	ssl.keystore.type = JKS
	ssl.protocol = TLS
	ssl.provider = null
	ssl.secure.random.implementation = null
	ssl.trustmanager.algorithm = PKIX
	ssl.truststore.location = null
	ssl.truststore.password = null
	ssl.truststore.type = JKS
	transaction.timeout.ms = 60000
	transactional.id = null
	value.serializer = class org.apache.kafka.common.serialization.StringSerializer

09:57:26,790 INFO  AppInfoParser - Kafka version : 1.0.0
09:57:26,791 INFO  AppInfoParser - Kafka commitId : aaa7af6d4a11b29d
09:57:27,054 INFO  Maxwell - Maxwell v1.25.0 is booting (MaxwellKafkaProducer), starting at Position[BinlogPosition[mysql-bin.000960:40096534], lastHeartbeat=0]
09:57:27,312 INFO  AbstractSchemaStore - Maxwell is capturing initial schema
09:58:08,423 INFO  BinlogConnectorReplicator - Setting initial binlog pos to: mysql-bin.000960:40096534
09:58:08,907 INFO  BinaryLogClient - Connected to rm-3nsqvd9yjrs7ag81z1o.mysql.rds.aliyuncs.com:3306 at mysql-bin.000960/40096534 (sid:6379, cid:6625036)
09:58:08,907 INFO  BinlogConnectorLifecycleListener - Binlog connected.
12:35:18,690 INFO  MaxwellContext - Sending final heartbeat: 1706848518690
12:35:18,742 INFO  BinlogConnectorReplicator - received final heartbeat 1706848518690; stopping replicator
12:35:18,743 INFO  BinlogConnectorLifecycleListener - Binlog disconnected.
12:35:18,842 INFO  TaskManager - Stopping 4 tasks
12:35:18,842 INFO  TaskManager - Stopping: com.zendesk.maxwell.schema.PositionStoreThread@62d80f8e
12:35:18,842 INFO  StoppableTaskState - com.zendesk.maxwell.schema.PositionStoreThread requestStop() called (in state: RUNNING)
12:35:18,842 INFO  TaskManager - Stopping: com.zendesk.maxwell.producer.MaxwellKafkaProducerWorker@6c1ffda5
12:35:18,843 INFO  StoppableTaskState - MaxwellKafkaProducerWorker requestStop() called (in state: RUNNING)
12:35:18,845 INFO  KafkaProducer - [Producer clientId=producer-1] Closing the Kafka producer with timeoutMillis = 9223372036854775807 ms.
12:35:18,850 INFO  TaskManager - Stopping: com.zendesk.maxwell.bootstrap.BootstrapController@77298fad
12:35:18,850 INFO  StoppableTaskState - com.zendesk.maxwell.bootstrap.BootstrapController requestStop() called (in state: RUNNING)
12:35:18,850 INFO  TaskManager - Stopping: com.zendesk.maxwell.replication.BinlogConnectorReplicator@4d0d08d1
12:35:18,850 INFO  StoppableTaskState - com.zendesk.maxwell.replication.BinlogConnectorReplicator requestStop() called (in state: STOPPED)
12:35:18,892 INFO  PositionStoreThread - Storing final position: Position[BinlogPosition[mysql-bin.000960:112343719], lastHeartbeat=1706848518690]
12:35:20,399 INFO  TaskManager - Stopped all tasks`
