### ISSUE TITLE
New Maxwell release

### ISSUE THREAD

**Issue by FanAs** [zendesk/maxwell#1781]
Hello @osheroff. Thank you again for your work!
Is it possible for you to release a new version of Maxwell?
There are some fixes that we need in production. We've been waiting for release for a month, and surely we can build it by ourself, but our deploy now depends on original github repo and we would like to keep it this way...
Thank you in advance,
Artyom from Livesport.

**Comment by osheroff** [comment]
yah, done.  was spinning the release behind some docker fixes that finally landed.
