### ISSUE TITLE
Maxwell was unable to get the incremental binlog

### ISSUE THREAD

**Issue by rookiegao** [zendesk/maxwell#1793]
**Problem Description:**
Maxwell program starts normally.  

command is as follows:
bin/maxwell --config /opt/bigdataRunTime/maxwell/maxwell-1.29.2/config.properties

The log is as follows: 

13:55:35,062 INFO  AppInfoParser - Kafka version : 1.0. 0
13:55:35,062 INFO  AppInfoParser - Kafka commitId : aaa7af6d4a11b29d
13:55:35,086 INFO  Maxwell - Maxwell v1. 29.2 is booting (MaxwellKafkaProducer), starting at Position[BinlogPosition[mysql-bin.005429:4449996], lastHeartbeat=0]
13:55:35,277 INFO  MysqlSavedSchema - Restoring schema id 1 (last modified at Position[BinlogPosition[mysql-bin.005429:4449996], lastHeartbeat=0])
13:55:35,660 INFO  BinlogConnectorReplicator - Setting initial binlog pos to: mysql-bin. 005429:4449996
13:55:35,680 INFO  BinaryLogClient - Connected to 10.176.xxx.xxx:3306 at mysql-bin. 005429/4449996 (sid:6379, cid:5217102)
13:55:35,680 INFO  BinlogConnectorReplicator - Binlog connected.

**At this time, Kafka does not create the corresponding topic.**

When I use the full fetch command, the topic is created at this time, However, subsequent incremental binlog information cannot be obtained.

The full execution command is as follows: 
bin/maxwell-bootstrap --database xxxx --table user --config /opt/bigdataRunTime/maxwell/maxwell-1.29.2/config.properties

**The configuration file is as follows:** 

log_level=info
producer=kafka
kafka.bootstrap.servers=pDataHadoopxx:9092,pDataHadoopxx:9092

#kafka topic
kafka_topic=%{table}
#mysql login info
replication_host=10.176.xxx.xxx
replication_user=username1
replication_password=password1
host=10.176.xxx.xxx
user=username1
password=password1
jdbc_options=useSSL=false&serverTimezone=Asia/Shanghai

#filter
filter= include:xxx.ordertrance,include:xxx.ordertrance_agent_info,include:xxx.user

**User permissions are as follows：**
SELECT, REPLICATION SLAVE, REPLICATION CLIENT,RELOAD

The user performs the canal task normally. Canal is a real-time synchronization tool similar to Maxwell

How should I troubleshoot the problem? Please help me solve the problem. Thank you.

**Comment by osheroff** [comment]
sorry, what do you see in kafka?  Do you see inserts / updates?  the output of the bootstrapping?  anything?

**Comment by rookiegao** [comment]
So far, we haven't seen any abnormal Kafka logs

**Comment by rookiegao** [comment]
The problem is solved. The reason is that we have a problem with the binlog of the slave database. Just monitor the master database. Thank you
