### ISSUE TITLE
Maxwell binlog file records cannot be promoted

### ISSUE THREAD

**Issue by Trevor-zhang** [zendesk/maxwell#1800]

**Comment by Trevor-zhang** [comment]
Maxwell version:1.33.0
![image](https://user-images.githubusercontent.com/33487819/147544500-946886d3-bfb3-4c6e-9bdf-47fd9415a77e.png)
The binlog file recorded by maxwell in the position table is mysql-bin-changelog.999999.
But what is recorded in mysql is mysql-bin-changelog.1103860.

![image](https://user-images.githubusercontent.com/33487819/147544815-40d1d5db-3987-4456-babb-88f9a019b62e.png)

Although the program keeps running, the binlog file is not upgraded normally. When restarting maxwell, it will report an error `maxwell binlog file not found Alert.`
We manually modified the binlog file to let the program continue to run.
I want to try to fix this bug but no success, I want to ask the community for help,  @osheroff  Can you give me some suggestions？

**Comment by osheroff** [comment]
blah.  I think we are assuming somewhere you only use 6 digits to store the binlogs

**Comment by osheroff** [comment]
https://github.com/zendesk/maxwell/compare/fix_long_binlog_fnames?expand=1

**Comment by Trevor-zhang** [comment]
could u tell me where to store binary files with6 digits ?
