### ISSUE TITLE
Content based routing for kafka topics

### ISSUE THREAD

**Issue by gangluo-addepar** [zendesk/maxwell#1801]
I didn't see this mentioned in the doc, but does Maxwell supports routing to the different kafka topics based on the content of the event? Say I have a table with a column `client_id`. I want to route events with `client_id` == 1 to kafka topic `client_1` while events with `client_id` == 2 to kafka topic `client_2`. Is that possible? If not now, any plan to add such content based routing capability? Thanks.

**Comment by osheroff** [comment]
sorry for the delay.  you can do this with "javascript filters'
