### ISSUE TITLE
replica_server_id values used in server_id column of maxwell.positions table

### ISSUE THREAD

**Issue by Shukla-Ankur** [zendesk/maxwell#1813]
maxwell v1.33.0
1. In maxwell.positions table, server_id is either 1(if gtid is enabled) or `@@server_id` variable.
This should mean I can either see 1 or actual `sever_id` in the column server_id. However, I have often seen replica_server_id used as server_id in this column. When does this happen?

2. I generally see 0 as server_id in the column when gtid mode is enabled and maxwell creates a new entry. As per mysql documentation, 

> "If the server ID is set to 0, binary logging takes place, but a source with a server ID of 0 refuses any connections from replicas, and a replica with a server ID of 0 refuses to connect to a source"
ref: https://dev.mysql.com/doc/mysql-replication-excerpt/8.0/en/replication-options.html#sysvar_server_id

3. If my observation is not correct and either 1 or actual `server_id` should be used, what exactly is the relevance of this column? If I am in a replication topology where Maxwell is reading binlogs from replica(R1) of primary node(P1), are the tables created in Maxwell DB in P1? 

4. When new Maxwell instance starts, Maxwell checks if it can find position/gtid against the client_id and server_id. If it does not find, it checks this for server_id. 
IMO this is not correct behavior. Say Maxwell M1 stopped at some time. After a long time, I start another Maxwell M2 with a different client_id and replica_server_id for reading fresh changes. Even when both client_id and replica_server_id are different from M1, I would still end up reading all of binlog files, right from where M1 left.
It considers state of M1 in maxwell.positions table while M1 and M2 do not have any replication except they both want to get the changes for same mysql instance. 
If I want to read from where M1 left, I would use the same client_id as M1. Why use a different client_id?

**Comment by osheroff** [comment]
Hi, you're misunderstanding what these values mean.

`server_id` in maxwell.positions is the master's server_id (meaning, this position is only applicable for a matching server_id), or 0 if GTID is enabled (meaning the position is usable by any matching `client_id`). 
`replica_server_id` has no relation to `server_id` or `maxwell.positions.server_id` - it is an integer that maxwell reports to the master (as if maxwell were an instance of mysql).  It is not stored anywhere, it is only used to identify a unique instance of a replica (or maxwell) to the server.

regarding (4) -- this is weird behavior, I agree - it has to do with the fact that multiple clients share one view of the master's schema -- if M2 picked up in a new location (ahead of M1), it would have to re-capture the schema.  starting to play changes from M1's position means it can share the schema with M1.   I should probably document this behavior, but if you want M2 to read fresh changes, it's advised that you drop the maxwell database and start fresh.
  
> If I want to read from where M1 left, I would use the same client_id as M1. Why use a different client_id?

There's many use cases for having a different `client_id` -- mostly it's when people want to replicate to different producers or some such.

**Comment by Shukla-Ankur** [comment]
1. On your suggestion regarding reading fresh changes for a new maxwell, providing a init position is safer than deleting the maxwell Db.
Also, I think this can be taken as a parameter during bootstrapping like kafka offsets i.e. whether to read fresh changes or continue from old. This way, the behavior will not be hidden from users of maxwell. 
Currently, when setting a new client_id, it is more intuitive to assume that it will starting a new maxwell with fresh changes, without knowledge of state of other maxwells. My point is "connect between state of multiple maxwell" is not intuitive unless one reads the code or it is documented.

2. I see that default server_id is 0. However, when trying to get initialPosition, if maxwell does not find for(server_id, client_id), it uses 1 as server_id to search. Why?

**Comment by Shukla-Ankur** [comment]
@osheroff any thoughts on this?

**Comment by osheroff** [comment]
> Currently, when setting a new client_id, it is more intuitive to assume that it will starting a new maxwell with fresh changes, without knowledge of state of other maxwells. My point is “connect between state of multiple maxwell” is not intuitive unless one reads the code, or it is documented.

I actually agree, but it's really a cause of the decision that multiple clients would share one copy of the schema, and there's no "safe" way to change the behavior without re-architecting huge sections of the application.  Call it lesson learned.

> Also, I believe this can be taken as a parameter during bootstrapping like kafka offsets i.e. whether to read fresh changes or continue from old. This way, the behavior will not be hidden from users of maxwell and usage itself will make it clear.
I can contribute to this if this suggestion makes sense. I can refine and share details of changes, and then create a pull request.

The problem is that if we don't start from where the old clients picked up, we will have no way of knowing whether the shared copy of the schema is correct or not -- if the new client picks up from "the current server position",  there may be giant gaps between the old client's schema and the new client's schema.

Now you *can* run the new client in a totally different maxwell database, and that will trigger the behavior you're proposing.

**Comment by osheroff** [comment]
> I see that default server_id is 0. However, when trying to get initialPosition, if maxwell does not find for(server_id, client_id), it uses 1 as server_id to search. Why?

I don't really understand the question.  Maxwell reads the `server_id` from the mysql server and tries to find a row in the positions table that matches that.
