### ISSUE TITLE
[SUGGEST] Make the event queue size configurable

### ISSUE THREAD

**Issue by gangluo-addepar** [zendesk/maxwell#1815]
For context, when Maxwell starts, a thread runs with `BinaryLogClient` to subscribe to MySql binlog and convert the byte array into some raw event object. Those raw events are then passed to `BinlogConnectorEventListener` which wrap the raw event then put them into a queue. `BinlogConnectorReplicator`, running in a different thread, are polling events off the queue for serialization and publishing. 

In this pub-sub model, `BinlogConnectorEventListener` is the producer and `BinlogConnectorReplicator` is the consumer. The queue connecting the two is a blocking queue with a fixed size of 20. See https://github.com/zendesk/maxwell/blob/master/src/main/java/com/zendesk/maxwell/replication/BinlogConnectorReplicator.java#L53. 

The problem with the fixed and small size for the queue is, both producer and consumer are keep getting blocked when the queue become empty/full. A quick profiling shows that producer thread spends 10% of the time in "PARK" state getting blocked during offer, while consumer thread spends 27% of time in PARK state getting blocked during poll. 

A quick test with that queue size removed (which makes the queue of size Integer.MAX_VALUE) shows that producer NO LONG getting blocked during offer, while consumer continue spent similar amount of time for poll. This indicate that producer is the bottleneck and consumer is being starved by not having enough events to consume. A sufficiently large queue size will eliminates the blocking for producer, which will in turn produce events faster to have consumer less starved. This generates some non-trivial performance boost. 

I suggest to make the queue size configurable. A new field `eventQueueSize` can be added to `MaxwellConfig` which get set with `fetchIntegerOption` from a config `event_queue_size`, with 20 being the default value. That config value will be passed down to `BinlogConnectorReplicator` to initialize the queue. That make it back-compatible while provide a config that could help improve performance a lot.

**Comment by osheroff** [comment]
Can you experiment with different queue sizes and just find a new default?  There’s no good reason that the queue size is 20, and if you find 100 or even 500 unblocks your use case it’s fine that we just up the size.

**Comment by gangluo-addepar** [comment]
Thanks @osheroff . My test involves 5 concurrent runs with a mixture of various write operations. 200 and 500 doesn't really make any difference. Time goes down with 1k and 2k but it is 5k that completely squeeze out the bubble. I suggest to make 5k the new default, which is still small enough to not cause much memory concern.

**Comment by osheroff** [comment]
what's the memory usage like at 5k?

**Comment by gangluo-addepar** [comment]
> what's the memory usage like at 5k?

It is minimal. I didn't notice any change from the system memory report despite not using a deep profiler. Not change in GC pattern either. 

A quick back of the envelop match shows that, the overhead of the `Event` (with the actually event data represented in `UpdateRowEventData`) is ~200b, while my actual data is ~300b per row. That is ~500b per event. 5k of that will be 2.5Mb extra memory. Event with really "fat" table like 3kb per row, that takes only 15Mb. It is trivial enough. 

@osheroff
