### ISSUE TITLE
MaxwellKafkaProducer reports data loss after TimeoutException

### ISSUE THREAD

**Issue by limaiwang** [zendesk/maxwell#1827]
I am using Maxwell version 1.29.2. After sending data to kafka using Maxwell, if one of the kafka clusters is down or there is a network problem, there is a TimeoutException. Then I check the MySQL Maxwell position table, the data in the position is changed, but the data to kafka will be lost, not up to the amount of data to generate binlog.

In my maxwell kafka configuration, I have configured kafka.aks=all with the following configuration details:
producer=kafka
kafka_topic=bi_maxwell_dev
kafka.bootstrap.servers=test.bj1:9092
kafka.max.request.size=17000000
kafka.retry.backoff.ms=10000
producer_partition_by=primary_key
kafka_partition_hash=default
kafka.compression.type=gzip
kafka.retries=8640
kafka.aks=all
ddl_kafka_topic=maxwell_ddl

Error details:
01:53:17,432 ERROR MaxwellKafkaProducer - Expiring 40 record(s) for bi_maxwell-19: 31221 ms has passed since batch creation plus linger time
01:53:17,432 ERROR MaxwellKafkaProducer - TimeoutException @ Position[BinlogPosition[mysql-bin.002293:675450394], lastHeartbeat= 1550113908124] -- bi_maxwell_dev: testdb:coredopics:[(id,log::log::1524719127)]

How do I adjust the configuration so that I don't lose data?

**Comment by sun642514265** [comment]
请问，最后您是怎么解决的呢？
