### ISSUE TITLE
[SUGGEST] Make the event queue size configurable

### ISSUE THREAD

**Issue by gangluo-addepar** [zendesk/maxwell#1835]
(This is re-opening https://github.com/zendesk/maxwell/issues/1815)

In  https://github.com/zendesk/maxwell/issues/1815 we increase the blocking queue size from 20 to 5k that dramatically improve the throughput/performance. For a period with heavy writes, we observed 56ms average blocking time with `maxwell.replication.queue.time` BEFORE the change, and 8ms AFTER the change. 

Still that is not enough for higher traffic. At p99 -- max there are still many enqueues getting blocked due to queue being full. The blocking time could be 300ms way higher than the 8ms average, and ever higher than below p99 which is 0. 

300ms may seem small and the frequency it happens is small (p99+). However it creates a large back pressure to the replication process and result in much larger increase in `maxwell.message.publish.age` which grows from ~0.5s to as high as 15s and the period with such high latency last for 1/7 of the time, way longer than the p99+ the blocking happens in queue. In a nutshell, tiny and small blocking in queue cause much higher latency for much longer period. 

IMO the best way to handle such edge case (1%) with crazy perf degradation is to make it configurable. So I am still suggesting the original idea, adding a new field `eventQueueSize` into `MaxwellConfig` which get set with `fetchIntegerOption` from a config event_queue_size, with 5k being the default value. That config value will be passed down to `BinlogConnectorReplicator` to initialize the queue. That make it back-compatible while provide a config that could help improve performance a lot for whoever needs it. 

I will be happy to take it over and make the code change, add tests and update the doc. Let me know if this sounds reasonable and how I can help with this. Thanks

cc @osheroff

**Comment by osheroff** [comment]
ok go for it

**Comment by gangluo-addepar** [comment]
https://github.com/zendesk/maxwell/pull/1836 was merged. closing this. 

Thanks for the review. @osheroff . I will keep an eye but if there is already schedule you can share when next release will be cut and put into maven it will be great.

**Comment by osheroff** [comment]
it's already out
