### ISSUE TITLE
Unable to specify Custom Producer Argument as environment variables

### ISSUE THREAD

**Issue by avaitla** [zendesk/maxwell#1847]
Hello Folks,

I'm trying to create a custom producer and have gotten very close! However I noticed that we can't provide arguments as envvars, specifically:

```
MAXWELL_CUSTOM_PRODUCER.CUSTOM_KEY=1 MAXWELL_PRODUCER=custom_producer maxwell --env_config_prefix="MAXWELL_" 
```

Will give the following error in bash

```
bash: MAXWELL_CUSTOM_PRODUCER.CUSTOM_KEY=1: command not found
```

This is due to bash not supporting periods in environment variables: https://unix.stackexchange.com/questions/93532/exporting-a-variable-with-dot-in-it

We use envvars for secrets so we don't need to pass them as flags. I'm curious if theres anyway to provide envvars to the maxwell process for custom providers?

The other tools I use to inject envvars into our environment drop envvars with periods or simply convert them to underscores

**Comment by avaitla** [comment]
Here is one potential change:

<img width="1028" alt="Screen Shot 2022-04-04 at 1 17 08 AM" src="https://user-images.githubusercontent.com/841497/161484304-c73f8c58-8442-45d8-a161-3af8b2e84fcf.png">

**Comment by avaitla** [comment]
Another alternative could be:

```
MAXWELL_CUSTOM_PRODUCER_CUSTOM_KEY=1 MAXWELL_PRODUCER=custom_producer maxwell --env_config_prefix="MAXWELL_" --custom_producer.custom_key=$MAXWELL_CUSTOM_PRODUCER_CUSTOM_KEY
```

So the caller passes in the underscore case which the flag with the dot then references

**Comment by avaitla** [comment]
Thank you!

**Comment by avaitla** [comment]
Thank you @osheroff for your hard work. I am very happy to use this great project.

**Comment by avaitla** [comment]
Are you able to push the 1.37.4 to maven?

**Comment by osheroff** [comment]
yah pushed.
