### ISSUE TITLE
Maxwell in kubernetes questions

### ISSUE THREAD

**Issue by mpkd** [zendesk/maxwell#1862]
Hello,

We are setting up maxwell in kubernetes. Need some help on resource allocation and bootstrap process. Appreciate any inputs on this.

In a highlevel overview:
- there are multiple databases with multiple tables in each databases(different wps)
- single pod deployment and a config for `each` databases

### Resource allocation
1. What are the criteria's to decide the resources(`cpu`, `memory` and `heap`) for maxwell deployments? _Given `0.1 cpu` and `250mb` memory to start with, but not sure what are the criteria's to decide these spec and increase as we needed._ This is the smallest product we have chosen to migrate first
2. Is maxwell is `cpu` bound or `memory` bound? Do we need to scale both `cpu` and `memory` or any of this is not recommended to go beyond certain level?
3.  How can we specify `heap` for maxwell process? looks like `50% memory` is allocated as `heap` by default, is that understanding is correct?

### Bootstrap
In onprem maxwell setup, we run maxwell bootstrap scripts in maxwell servers in `async` mode. 
In kubernetes setup:
1. planning to run `bootstrap` as a kubernertes `job`, so a separate pod will be deployed to run bootstrap and exits after the bootstrap is completed. How much resources, we need to allocate for these containers? hope this approach will be asynchronous and there is no impact to the maxwell deployments.

### Metrics
We exposed maxwell metrics via prometheus. We are exploring the key metrics for scaling up the resources
1. what are the key metrics to scale up the resources? we are assuming `replication_lag`, `replication_queue_time` & `message_publish_time`. are these metrics are key metrics for deciding when to scale up the resources? If yes, is there any threshold recommendations? 
2. if I understand correctly `message_publish_age` is the total time taken for processing a mysql insert as a kafka message
3. how to determine maxwell is not dropping any events? is it `message_failed`metrics or any other metrics available?

Thank you so much in advance.

**Comment by osheroff** [comment]
A lot of the answers to your questions depend on your replication load.  Generally speaking you'll get cpu bound before you're memory bound, but it depends on how many large transactions you process.  I don't really know what the "heap" resource means.  

Re: bootstrap:  the bootstrap code is part of the main maxwell server.  there's a separate utility that triggers bootstrapping, but all the work is done by the same server that replicates things.  If you're doing something outside that model... dunno.

metrics:  the ones to watch look fine, and messages.failed seems like a good place to monitor.

if you need more advice get in touch with me on linkedin or something, I'm happy to offer you a lightweight support contract.
