### ISSUE TITLE
How to point Maxwell to another MySQL server if original fails?

### ISSUE THREAD

**Issue by krv783** [zendesk/maxwell#1876]
Hello,

I've been reading through the docs as well as GitHub issues, and I was hoping to get some clarification on how to get Maxwell to work with a master/slave MySQL setup. I see that the configuration only allows for a single MySQL host, so I'm wondering if this is something that simply needs to be handled outside of Maxwell.

For example, on Maxwell crashing due to an inability to reconnect to the original host, should Maxwell simply be re-launched with the secondary MySQL host's hostname/ip as the source?

I'm also assuming that the Maxwell database should also be replicated to the slave along with the other databases.

If anyone could point me in the right direction on this that would be great.

Thank you!

**Comment by osheroff** [comment]
>  I see that the configuration only allows for a single MySQL host, so I'm wondering if this is something that simply needs to be handled outside of Maxwell.

There's a few different options but nothing standardized (and thus nothing baked in):

- you can hit the databases through HAProxy or other tcp-level load balancer with a preference towards the current master. 
- you can accomplish a similar setup with a floating VIP
- you can bolt a shell script onto the outside of maxwell that searches amongst a list of servers and finds the current master

> I'm also assuming that the Maxwell database should also be replicated to the slave along with the other databases.

yeah.  you should also look into running in GTID mode for best master/slave promotion.
