### ISSUE TITLE
com.zendesk.maxwell.schema.ddl.MaxwellSQLSyntaxError about TABLESPACE

### ISSUE THREAD

**Issue by yunduan16** [zendesk/maxwell#1879]
SchemaChange - Error parsing SQL: 'CREATE TABLE IF NOT EXISTS concurrency_control ( Id bigint AUTO_INCREMENT NOT NULL, Type enum('SELECT','UPDATE','INSERT','DELETE','DDL') COLLATE utf8_general_ci DEFAULT 'SELECT' NOT NULL, Schema_name varchar(64), Table_name varchar(64), Concurrency_count bigint NOT NULL, Keywords text, State enum('N','Y') COLLATE utf8_general_ci DEFAULT 'Y' NOT NULL, Ordered enum('N','Y') COLLATE utf8_general_ci DEFAULT 'N' NOT NULL, PRIMARY KEY Rule_id(id) ) Engine=InnoDB STATS_PERSISTENT=0 CHARACTER SET utf8 COLLATE utf8_bin comment='Concurrency control' TABLESPACE=mysql'
10:35:23,307 ERROR AbstractSchemaStore - Error on bin log position Position[BinlogPosition[mysql-bin.000279:5571072], lastHeartbeat=1654453002998]
com.zendesk.maxwell.schema.ddl.MaxwellSQLSyntaxError: =

**Comment by live-github** [comment]
MySQL 8.0 Reference Manual
https://dev.mysql.com/doc/refman/8.0/en/create-table.html#create-table-options

MySQL 5.7 Reference Manual
https://dev.mysql.com/doc/refman/5.7/en/create-table.html

MySQL 5.6 Reference Manual
https://dev.mysql.com/doc/refman/5.6/en/create-table.html

  | STATS_SAMPLE_PAGES [=] value
  | TABLESPACE tablespace_name [STORAGE {DISK | MEMORY}]
  | UNION [=] (tbl_name[,tbl_name]...)

There is no ‘=’ sign after TABLESPACE，Maxwell is consistent with the documentation。
