### ISSUE TITLE
Handling event drops for Kafka producer

### ISSUE THREAD

**Issue by Shukla-Ankur** [zendesk/maxwell#1880]
Maxwell v1.33.0
MySQL v8.0.23
Kafka v2.2.1

I use multiple maxwell pipelines which write events to kafka. I use below options
`producer_ack_timeout=200 --ignore_producer_error=false --dead_letter_topic=dlq-topic`

Based on documentation https://maxwells-daemon.io/config/ 
1. For ignore_producer_error=false, maxwell stops if it is unable to publish to kafka and only publishes a skeleton row in dql for RecordTooLargeException. Does maxwell log the original message and error in other cases? Or else it will not be possible to determine what message was not sent. 
2. I run maxwell with retries such that maxwell is restarted if it stops. And maxwell succeeds on restart usually. If maxwell had stopped due to not being able to publish a message, is that message skipped by maxwell? Or retried again after restart?

**Comment by osheroff** [comment]
1.  If `ignore_producer_error=true` or the record is too large, maxwell will publish a skeleton row to the `dead_letter_topic`.
2. unless `ignore_producer_errors` is true it'll retry.
