### ISSUE TITLE
Exchange?

### ISSUE THREAD

**Issue by luo981695830** [zendesk/maxwell#1883]
How can I contact you?The official documentation is not very detailed。I have some problems to solve。Maybe we can build Chinese communities.

**Comment by osheroff** [comment]
you're welcome to continue opening issues here.  I tried to get zendesk to open up forums for github but no one did (I don't work there anymore).  Other than that, you know, eh.....

**Comment by luo981695830** [comment]
ok，thank you for your reply.I`m interested in maxwell and I plan keep writing articles about maxwell
