### ISSUE TITLE
Warning on tables non-included tables

### ISSUE THREAD

**Issue by jpeyper** [zendesk/maxwell#189]
One of my environments is reporting this `WARN` (a lot!).
```
14:31:07,477 WARN  MaxwellReplicator - Unhandled QueryEvent inside transaction: QueryEvent[header=BinlogEventV4HeaderImpl[timestamp=1449710974000,eventType=2,serverId=441,eventLength=279,nextPosition=219695949,flags=0,timestampOfReceipt=1449718267477],threadId=4,elapsedTime=0,databaseNameLength=6,errorCode=0,statusVariablesLength=35,statusVariables=[QFlags2Code[flags=0], QSQLModeCode[sqlMode=2097152], QCatalogNzCode[catalogName=std], QCharsetCode[characterSetClient=8,collationConnection=8,collationServer=8], QUpdatedDBNames[accessedDbCount=1,accessedDbs=[Lcom.google.code.or.common.glossary.column.StringColumn;@2da0770]],databaseName=merlyn,sql=INSERT INTO merlyn.system_variables(project, var_name, var_value) VALUES('xxxxx', 'yyyyy', 'zzzzz') ON DUPLICATE KEY UPDATE var_value= 'zzzzz']
```

My config file is setup to include specify databases (`include_dbs`) and tables (`include_tables`). Both `merlyn` and `system_variables` are not included.

Is there any reason that Maxwell needs to care about tables and databases that I'm not tracking events for?

And secondly, if I got this `WARN` on a table that I was tracking, what does it actually mean? have I missed a change? What is causing this `WARN`?

**Comment by osheroff** [comment]
This means that Maxwell is receiving statement-based replication in its streams, which it doesn't expect.

I could think of two ways this could happen:

1.  An odd client *could* trigger this by doing `set binlog_format='STATEMENT'` at the top of its session.  I'm not sure why you'd do that, but it's possible.

2.  `binlog_format=ROW` doesn't affect old sessions -- so if these connections existed before you set binlog_format to ROW on your machine, they will still be doing statement based replication.  Once they reconnect they'll pick up row-based logging.

**Comment by osheroff** [comment]
btw, this also explains your CREATE TEMPORARY TABLE error -- those statements are not replicated with row-based replication.

**Comment by jpeyper** [comment]
Okay, I'll investigate more as to who was running what against that server :)

**Comment by wushujames** [comment]
Since binlog_format was set incorrectly, do you think https://github.com/zendesk/maxwell/pull/187 is still necessary? I could see as still necessary, just to make it more robust against errors such as this?

**Comment by osheroff** [comment]
@wushujames, I think it's probably good just towards a goal that no SQL accepted by mysql causes maxwell to crash.

that might be a bit of a hubristic goal, but hey.

**Comment by wushujames** [comment]
No, that makes sense. "Robustness". :thumbsup:

**Comment by osheroff** [comment]
@jpeyper I'm gonna close this issue out, but if you find out more feel free to re-open.

**Comment by jpeyper** [comment]
That fine, our dba's theory is that the dB was set to mixed mode,  and Maxwell's position in the log was set behind where the switch to row was made (not sure how it was set there, but anyway). 

As it was a testing environment we deleted the existing logs and Maxwell schema and we having seen any issues since.
