### ISSUE TITLE
After the db failover, the master-standby switch occurs, and then maxwell cannot pull the binlog

### ISSUE THREAD

**Issue by Trevor-zhang** [zendesk/maxwell#1892]

**Comment by Trevor-zhang** [comment]
After the db failsover, the master-standby switchover occurs, and the db has returned to normal. However, we checked the maxwell status and found that although it did not exit, it could not consume data normally, such as false active.

Then we execute the following statement in mysql:
<img width="920" alt="image" src="https://user-images.githubusercontent.com/33487819/179940331-4ff45710-d931-456b-bb84-a86d89966e60.png">

It is found that the Binlog Dump process of the maxwell user is no longer there, although its jdbc connection is still there.

Excuse me, how can we avoid false active behavior after db failover?

**Comment by osheroff** [comment]
How are you performing the failover?   You should trigger maxwell to crash and resume.  We used to do this by settting Read_only to true on the old master.

**Comment by Trevor-zhang** [comment]
When failover occurred in the past, the jdbc connection would be disconnected and maxwell would be restarted. But this time the jdbc connection is still there, so the instance is stuck there, and we only discovered the problem a day later. What can we do on the maxwell side? @osheroff

**Comment by osheroff** [comment]
> How are you performing the failover? You should trigger maxwell to crash and resume. We used to do this by settting Read_only to true on the old master.

**Comment by Trevor-zhang** [comment]
> Read_only to true on the old master.
Read_only has been set to true when the last accident happened, but maxwell is still stuck :(  @osheroff

**Comment by wanghangyu817** [comment]
Is it community mysql or Ali Cloud RDS?

**Comment by osheroff** [comment]
Ok read-only set to 1 *should* crash maxwell, allowing it to failover to the new master.  Was there any logs from the dead maxwell process? 

I think the positionstorethread should have crashed and allowed failover.  Not sure why it didn't.
