### ISSUE TITLE
Any way to covert maxwell kafka message to SQL statement

### ISSUE THREAD

**Issue by 29swastik** [zendesk/maxwell#1893]
I've configured Maxwell(latest version) to capture changes from MariaDb(version 10.4.22). I'm receiving messages through kafka for DML. Is there any way to convert these messages to SQL statements, any config parameters in Maxwell will help to do this or is there any tool for this?

**Comment by yangzhongj** [comment]
Mark，I also need it.

**Comment by wanghangyu817** [comment]
#1842

**Comment by 29swastik** [comment]
So it is not recommended to use on production with MariaDb?

**Comment by osheroff** [comment]
mariadb is fine in production AFAIK.  there may be some odd features that aren't fully supported but the basics of maria are just mysql.

**Comment by osheroff** [comment]
there's no functionality currently to output SQL.  There used to be, long ago, but it wasn't really useful for maxwell so I stopped maintaining it.  Happy to accept PRs that could specify an alternate output format but I have no plans to add SQL support at the moment.
