### ISSUE TITLE
New implementation and existing replicas

### ISSUE THREAD

**Issue by mlcpap** [zendesk/maxwell#1901]
Our main production server where we would install Maxwell already has binlogs configured as well as 3 slaves attached.  It wasn't clear from what I have read that Maxwell would be a good fit and not interfere with that existing replication somehow.  I assume that Maxwell is merely reading binlog contents via SELECT commands and writing schema, etc. to its own database and that this is why it requires the amount of permissions it does.  So, will this work piggy backing on our existing binlog arrangement?  The format is already row, so at least we have that going for us.  Server is still mysql 5.6.X.

I am also curious how we might limit database or table access or otherwise limit what data maxwell will see and send over to rabbitmq, et al.

**Comment by mlcpap** [comment]
I suppose we could run this downstream on one of the replicas or on a new replica designed for this purpose.  But, I await your thoughts on this.

**Comment by osheroff** [comment]
Maxwell acts as if it's a replica.  It doesn't add much more load than another replica would, and it won't interfere with other replicas.  It'll probably be fine for your setup.

You can look into the filtering options to limit what maxwell will send.
