### ISSUE TITLE
MariaDB Crash: IF on ALTER TABLE ADD CONSTRAINT

### ISSUE THREAD

**Issue by acrois** [zendesk/maxwell#1913]
An example statement that causes an error reading the binlog:
```SQL
ALTER IGNORE TABLE table_name ADD CONSTRAINT table_name_pk PRIMARY KEY IF NOT EXISTS (colA, colB)
```

Error:
```java
AbstractSchemaStore - Error Parsing SQL
...
com.zendesk.maxwell.ddl.MaxwellSQLSyntaxError: IF
```

Sorry, I can't share the full trace, but it's relatively uninteresting compared to the meaningful info I extracted...

https://github.com/zendesk/maxwell/blob/d266f480c54dc894b685f77b3cf9aa85e591e92b/src/main/java/com/zendesk/maxwell/schema/ddl/MysqlParserListener.java#L93

Interesting: No `ADD CONSTRAINT` only `DROP CONSTRAINT`. Is this intentional?
https://github.com/zendesk/maxwell/blob/d266f480c54dc894b685f77b3cf9aa85e591e92b/src/main/antlr4/imports/mysql_alter_table.g4#L57-L72

Besides skipping the event that is failing to process, what else could be done to help resolve DDL syntax discrepancies between MySQL/MariaDB?

I know maxwell is designed for MySQL with no real guarantee beyond what is compatible between them both.

Tested version: (a little old): [v1.23.2, "you enjoy it every time"](https://github.com/zendesk/maxwell/commit/28be021bc3a7af7ee29d34096e14a9d4246c0524)

I don't think upgrading will address the issue because the grammar 

However, if one were to address this statement's incompatibility:
1. Add `ADD CONSTRAINT` to complement `DROP CONSTRAINT` to ignore all `ADD CONSTRAINT`s?
2. Add `IF NOT EXISTS` which would normally not be seen in MySQL to support MariaDB option?
3. Add MariaDB-specific definitions to support MariaDB valid query grammar?
   * Can existing definitions be updated to encapsulate both syntaxes with no impact to maxwell thus supporting all variations of the grammars?

Hope this is informative for others in a similar situation. Thanks.

**Comment by osheroff** [comment]
fixed in latest
