### ISSUE TITLE
Google PubSub message ordering

### ISSUE THREAD

**Issue by billybraga** [zendesk/maxwell#1919]
Has adding an option to use message ordering ever been discussed? 

https://cloud.google.com/pubsub/docs/ordering

Could it cause a problem with how maxwell works?

I believe adding an option to support it would be quite trivial, and I'd be open to submitting a PR for it.

**Comment by osheroff** [comment]
Seems like a good idea, very similar to Kafka partitions or kinesis shards.  Feel free to open a PR
