### ISSUE TITLE
Bootstrapping is not working

### ISSUE THREAD

**Issue by yeziblo** [zendesk/maxwell#1926]
I want to init my total data into kafka, so I use command like :

./maxwell-bootstrap --config ../config.properties --user maxwell --password 'xxx' --host localhost --database test --table test_table

But it doesn't works, it always show: 'waiting for bootstrap to start...'

I checked mysql and the binlog position is at 208319233.

Then I checked maxwell.positions, the `binlog_position` value is 175013953 and it's never change!

Please help.

**Comment by osheroff** [comment]
is maxwell running?

**Comment by osheroff** [comment]
the main daemon that is
