### ISSUE TITLE
Maxwell is using JDK7 and not support JDK 6 ?

### ISSUE THREAD

**Issue by darionyaphet** [zendesk/maxwell#193]
Maxwell is using `JDK 7` and not support `JDK 6` ?

I'm reading maxwell and found something maybe could rewrite 

such as : 

```
		InputStream schemaSQL = SchemaStore.class.getResourceAsStream(
				"/sql/maxwell_schema.sql");
		BufferedReader r = new BufferedReader(new InputStreamReader(schemaSQL));
		String sql = "", line;

		LOGGER.info("Creating maxwell database");
		while ((line = r.readLine()) != null) {
			sql += line + "\n";
		}

```
In JDK 7 Files.readAllLines(path, cs) is looks better :)

**Comment by osheroff** [comment]
yeah, jdk 7.  I think I use switch() on strings.  feel free to PR it if you like.

**Comment by darionyaphet** [comment]
@osheroff  a code style is necessary ？my ide(eclipse) format seems have some difference with your
