### ISSUE TITLE
Download links broken

### ISSUE THREAD

**Issue by kovyrin** [zendesk/maxwell#1930]
Hello,

Thank you for creating and maintaining this amazing project! I've noticed that download links and the changelog have been updated to a new release, but looks like the actual release has not happened: download links are broken and the `com.zendesk:maxwell:jar:1.39.0` artifact does now exist on Maven Central.

**Comment by osheroff** [comment]
k yeah.  1.39.0 was not a great release and I pulled it down.  I've reverted the download links back to 1.38.0
