### ISSUE TITLE
Maxwell crashing/going down

### ISSUE THREAD

**Issue by 29swastik** [zendesk/maxwell#1931]
We have maxwell running on docker in our production and it is configured to listen to changes on MariadDb tables and push them to a kafka topic. Our MariadDb has some 10-12 tables and we have configured maxwell to listen to only 4 tables and all these 4 tables are heavily used (number of writes is too high). 

Recently we have seen that our Maxwell is going down, following are the few error logs we found when maxwell is going down

```
Oct 28, 2022 @ 06:10:40.037	06:10:40,037 ERROR MysqlParserListener - (parse SET STATEMENT max_statement_time = 60 FOR flush table)

Oct 28, 2022 @ 06:10:40.040	06:10:40,040 ERROR SchemaChange - Error parsing SQL: 'SET STATEMENT max_statement_time=60 FOR flush table'

Oct 28, 2022 @ 06:10:40.047	06:10:40,045 ERROR AbstractSchemaStore - Error on bin log position Position[BinlogPosition[mysql-bin-changelog.049610:3209], lastHeartbeat=1666898518069]

```

As the last error log says **Error on bin log position Position[BinlogPosition[mysql-bin-changelog.049610:3209]**, so to verify whether bin log file with name `mysql-bin-changelog.049610:3209` exists or not we ran `SHOW binary logs;` and we found that file in list outputted by above command 

Please help me in understanding what is going wrong here and help in solving the issue

**Environment Details**

1. OS: Centos
2. Platform - AWS instance(T4g Medium)
3. CPU - 2 CPU
4. RAM - 4GB

**Maxwell Version** - `v1.37.7`

**Note**: We are not handling DDL & our log retention is 3 days

Detailed logs that was logged when Maxwell was going down, sorry for posting huge logs :)

> ```
> Oct 28, 2022 @ 06:10:39.084	06:10:39,082 INFO  ProducerConfig - ProducerConfig values: 
> Oct 28, 2022 @ 06:10:39.146	06:10:39,146 INFO  AppInfoParser - Kafka commitId : aaa7af6d4a11b29d
> 
> Oct 28, 2022 @ 06:10:39.146	06:10:39,146 INFO  AppInfoParser - Kafka version : 1.0.0
> 
> Oct 28, 2022 @ 06:10:39.188	06:10:39,187 INFO  Maxwell - Maxwell v1.37.7 is booting (MaxwellKafkaProducer), starting at Position[BinlogPosition[mysql-bin-changelog.049610:3136], lastHeartbeat=1666898518069]
> 
> Oct 28, 2022 @ 06:10:39.377	06:10:39,377 INFO  MysqlSavedSchema - Restoring schema id 22 (last modified at Position[BinlogPosition[mysql-bin-changelog.046940:91534], lastHeartbeat=1666103424529])
> 
> Oct 28, 2022 @ 06:10:39.502	06:10:39,502 INFO  MysqlSavedSchema - Restoring schema id 1 (last modified at Position[BinlogPosition[mysql-bin-changelog.040524:418929], lastHeartbeat=0])
> 
> Oct 28, 2022 @ 06:10:39.555	06:10:39,555 INFO  MysqlSavedSchema - beginning to play deltas...
> 
> Oct 28, 2022 @ 06:10:39.576	06:10:39,576 INFO  MysqlSavedSchema - played 21 deltas in 15ms
> 
> Oct 28, 2022 @ 06:10:39.601	06:10:39,601 INFO  BinlogConnectorReplicator - Setting initial binlog pos to: mysql-bin-changelog.049610:3136
> 
> Oct 28, 2022 @ 06:10:39.605	06:10:39,605 INFO  MaxwellHTTPServer - Maxwell http server starting
> 
> Oct 28, 2022 @ 06:10:39.607	06:10:39,607 INFO  MaxwellHTTPServer - Maxwell http server started on port 8080
> 
> Oct 28, 2022 @ 06:10:39.649	06:10:39,649 INFO  BinlogConnectorReplicator - Binlog connected.
> 
> Oct 28, 2022 @ 06:10:39.649	06:10:39,646 INFO  BinaryLogClient - Connected to mariadb-nlp.app.engati.local:3306 at mysql-bin-changelog.049610/3136 (sid:6379, cid:1560183)
> 
> Oct 28, 2022 @ 06:10:39.669	06:10:39,669 INFO  log - Logging initialized @2288ms to org.eclipse.jetty.util.log.Slf4jLog
> 
> Oct 28, 2022 @ 06:10:39.902	06:10:39,902 INFO  Server - jetty-9.4.41.v20210516; built: 2021-05-16T23:56:28.993Z; git: 98607f93c7833e7dc59489b13f3cb0a114fb9f4c; jvm 11.0.15+10
> 
> Oct 28, 2022 @ 06:10:40.037	06:10:40,037 ERROR MysqlParserListener - (parse SET STATEMENT max_statement_time = 60 FOR flush table)
> 
> Oct 28, 2022 @ 06:10:40.040	06:10:40,040 ERROR SchemaChange - Error parsing SQL: 'SET STATEMENT max_statement_time=60 FOR flush table'
> 
> Oct 28, 2022 @ 06:10:40.047		at com.zendesk.maxwell.Maxwell.main(Maxwell.java:336)
> 
> Oct 28, 2022 @ 06:10:40.047		at com.zendesk.maxwell.Maxwell.start(Maxwell.java:227)
> 
> Oct 28, 2022 @ 06:10:40.047		at com.zendesk.maxwell.Maxwell.startInner(Maxwell.java:301)
> 
> Oct 28, 2022 @ 06:10:40.047		at com.zendesk.maxwell.util.RunLoopProcess.runLoop(RunLoopProcess.java:34)
> 
> Oct 28, 2022 @ 06:10:40.047		at com.zendesk.maxwell.replication.BinlogConnectorReplicator.work(BinlogConnectorReplicator.java:228)
> 
> Oct 28, 2022 @ 06:10:40.047		at com.zendesk.maxwell.replication.BinlogConnectorReplicator.getRow(BinlogConnectorReplicator.java:723)
> 
> Oct 28, 2022 @ 06:10:40.047		at com.zendesk.maxwell.replication.BinlogConnectorReplicator.processQueryEvent(BinlogConnectorReplicator.java:400)
> 
> Oct 28, 2022 @ 06:10:40.047		at com.zendesk.maxwell.replication.BinlogConnectorReplicator.processQueryEvent(BinlogConnectorReplicator.java:378)
> 
> Oct 28, 2022 @ 06:10:40.047		at com.zendesk.maxwell.schema.MysqlSchemaStore.processSQL(MysqlSchemaStore.java:102)
> 
> Oct 28, 2022 @ 06:10:40.047		at com.zendesk.maxwell.schema.AbstractSchemaStore.resolveSQL(AbstractSchemaStore.java:49)
> 
> Oct 28, 2022 @ 06:10:40.047		at com.zendesk.maxwell.schema.ddl.SchemaChange.parse(SchemaChange.java:108)
> 
> Oct 28, 2022 @ 06:10:40.047		at com.zendesk.maxwell.schema.ddl.SchemaChange.parseSQL(SchemaChange.java:94)
> 
> Oct 28, 2022 @ 06:10:40.047		at org.antlr.v4.runtime.tree.ParseTreeWalker.walk(ParseTreeWalker.java:28)
> 
> Oct 28, 2022 @ 06:10:40.047		at org.antlr.v4.runtime.tree.ParseTreeWalker.walk(ParseTreeWalker.java:17)
> 
> Oct 28, 2022 @ 06:10:40.047		at com.zendesk.maxwell.schema.ddl.MysqlParserListener.visitErrorNode(MysqlParserListener.java:93)
> 
> Oct 28, 2022 @ 06:10:40.047	com.zendesk.maxwell.schema.ddl.MaxwellSQLSyntaxError: SET
> 
> Oct 28, 2022 @ 06:10:40.047	06:10:40,045 ERROR AbstractSchemaStore - Error on bin log position Position[BinlogPosition[mysql-bin-changelog.049610:3209], lastHeartbeat=1666898518069]
> 
> Oct 28, 2022 @ 06:10:40.047	06:10:40,044 INFO  ContextHandler - Started o.e.j.s.ServletContextHandler@5628733f{/,null,AVAILABLE}
> 
> Oct 28, 2022 @ 06:10:40.075	06:10:40,074 INFO  Server - Started @2700ms
> 
> Oct 28, 2022 @ 06:10:40.075	06:10:40,074 INFO  AbstractConnector - Started ServerConnector@7152d3c1{HTTP/1.1, (http/1.1)}{0.0.0.0:8080}
> 
> Oct 28, 2022 @ 06:10:40.129	06:10:40,129 INFO  BinlogConnectorReplicator - Binlog disconnected.
> 
> Oct 28, 2022 @ 06:10:40.149	06:10:40,149 INFO  TaskManager - Stopping 5 tasks
> 
> Oct 28, 2022 @ 06:10:40.187		at com.zendesk.maxwell.schema.ddl.SchemaChange.parseSQL(SchemaChange.java:94) ~[maxwell-1.37.7.jar:1.37.7]
> 
> Oct 28, 2022 @ 06:10:40.187		at org.antlr.v4.runtime.tree.ParseTreeWalker.walk(ParseTreeWalker.java:28) ~[antlr4-runtime-4.8-1.jar:4.8-1]
> 
> Oct 28, 2022 @ 06:10:40.187		at org.antlr.v4.runtime.tree.ParseTreeWalker.walk(ParseTreeWalker.java:17) ~[antlr4-runtime-4.8-1.jar:4.8-1]
> 
> Oct 28, 2022 @ 06:10:40.187		at com.zendesk.maxwell.schema.ddl.MysqlParserListener.visitErrorNode(MysqlParserListener.java:93) ~[maxwell-1.37.7.jar:1.37.7]
> 
> Oct 28, 2022 @ 06:10:40.187	com.zendesk.maxwell.schema.ddl.MaxwellSQLSyntaxError: SET
> 
> Oct 28, 2022 @ 06:10:40.187	06:10:40,152 ERROR TaskManager - cause: 
> 
> Oct 28, 2022 @ 06:10:40.187		at com.zendesk.maxwell.Maxwell.main(Maxwell.java:336) ~[maxwell-1.37.7.jar:1.37.7]
> 
> Oct 28, 2022 @ 06:10:40.187		at com.zendesk.maxwell.Maxwell.start(Maxwell.java:227) ~[maxwell-1.37.7.jar:1.37.7]
> 
> Oct 28, 2022 @ 06:10:40.187		at com.zendesk.maxwell.Maxwell.startInner(Maxwell.java:301) ~[maxwell-1.37.7.jar:1.37.7]
> 
> Oct 28, 2022 @ 06:10:40.187		at com.zendesk.maxwell.util.RunLoopProcess.runLoop(RunLoopProcess.java:34) ~[maxwell-1.37.7.jar:1.37.7]
> 
> Oct 28, 2022 @ 06:10:40.187		at com.zendesk.maxwell.replication.BinlogConnectorReplicator.work(BinlogConnectorReplicator.java:228) ~[maxwell-1.37.7.jar:1.37.7]
> 
> Oct 28, 2022 @ 06:10:40.187		at com.zendesk.maxwell.replication.BinlogConnectorReplicator.getRow(BinlogConnectorReplicator.java:723) ~[maxwell-1.37.7.jar:1.37.7]
> 
> Oct 28, 2022 @ 06:10:40.187		at com.zendesk.maxwell.replication.BinlogConnectorReplicator.processQueryEvent(BinlogConnectorReplicator.java:400) ~[maxwell-1.37.7.jar:1.37.7]
> 
> Oct 28, 2022 @ 06:10:40.187		at com.zendesk.maxwell.replication.BinlogConnectorReplicator.processQueryEvent(BinlogConnectorReplicator.java:378) ~[maxwell-1.37.7.jar:1.37.7]
> 
> Oct 28, 2022 @ 06:10:40.187		at com.zendesk.maxwell.schema.MysqlSchemaStore.processSQL(MysqlSchemaStore.java:102) ~[maxwell-1.37.7.jar:1.37.7]
> 
> Oct 28, 2022 @ 06:10:40.187		at com.zendesk.maxwell.schema.AbstractSchemaStore.resolveSQL(AbstractSchemaStore.java:49) ~[maxwell-1.37.7.jar:1.37.7]
> 
> Oct 28, 2022 @ 06:10:40.187		at com.zendesk.maxwell.schema.ddl.SchemaChange.parse(SchemaChange.java:108) ~[maxwell-1.37.7.jar:1.37.7]
> 
> Oct 28, 2022 @ 06:10:40.189	06:10:40,189 INFO  TaskManager - Stopping: com.zendesk.maxwell.schema.PositionStoreThread@51b3ee1b
> 
> Oct 28, 2022 @ 06:10:40.191	06:10:40,189 INFO  TaskManager - Stopping: com.zendesk.maxwell.producer.MaxwellKafkaProducerWorker@5ec6ffb6
> 
> Oct 28, 2022 @ 06:10:40.192	06:10:40,192 INFO  KafkaProducer - [Producer clientId=producer-1] Closing the Kafka producer with timeoutMillis = 9223372036854775807 ms.
> 
> Oct 28, 2022 @ 06:10:40.201	06:10:40,201 INFO  TaskManager - Stopping: com.zendesk.maxwell.monitoring.MaxwellHTTPServerWorker@1490968e
> 
> Oct 28, 2022 @ 06:10:40.201		at com.zendesk.maxwell.Maxwell.main(Maxwell.java:336)
> 
> Oct 28, 2022 @ 06:10:40.201		at com.zendesk.maxwell.Maxwell.start(Maxwell.java:227)
> 
> Oct 28, 2022 @ 06:10:40.201		at com.zendesk.maxwell.Maxwell.startInner(Maxwell.java:301)
> 
> Oct 28, 2022 @ 06:10:40.201		at com.zendesk.maxwell.util.RunLoopProcess.runLoop(RunLoopProcess.java:34)
> 
> Oct 28, 2022 @ 06:10:40.201		at com.zendesk.maxwell.replication.BinlogConnectorReplicator.work(BinlogConnectorReplicator.java:228)
> 
> Oct 28, 2022 @ 06:10:40.201		at com.zendesk.maxwell.replication.BinlogConnectorReplicator.getRow(BinlogConnectorReplicator.java:723)
> 
> Oct 28, 2022 @ 06:10:40.201		at com.zendesk.maxwell.replication.BinlogConnectorReplicator.processQueryEvent(BinlogConnectorReplicator.java:400)
> 
> Oct 28, 2022 @ 06:10:40.201		at com.zendesk.maxwell.replication.BinlogConnectorReplicator.processQueryEvent(BinlogConnectorReplicator.java:378)
> 
> Oct 28, 2022 @ 06:10:40.201		at com.zendesk.maxwell.schema.MysqlSchemaStore.processSQL(MysqlSchemaStore.java:102)
> 
> Oct 28, 2022 @ 06:10:40.201		at com.zendesk.maxwell.schema.AbstractSchemaStore.resolveSQL(AbstractSchemaStore.java:49)
> 
> Oct 28, 2022 @ 06:10:40.201		at com.zendesk.maxwell.schema.ddl.SchemaChange.parse(SchemaChange.java:108)
> 
> Oct 28, 2022 @ 06:10:40.201		at com.zendesk.maxwell.schema.ddl.SchemaChange.parseSQL(SchemaChange.java:94)
> 
> Oct 28, 2022 @ 06:10:40.201		at org.antlr.v4.runtime.tree.ParseTreeWalker.walk(ParseTreeWalker.java:28)
> 
> Oct 28, 2022 @ 06:10:40.201		at org.antlr.v4.runtime.tree.ParseTreeWalker.walk(ParseTreeWalker.java:17)
> 
> Oct 28, 2022 @ 06:10:40.201		at com.zendesk.maxwell.schema.ddl.MysqlParserListener.visitErrorNode(MysqlParserListener.java:93)
> 
> Oct 28, 2022 @ 06:10:40.201	com.zendesk.maxwell.schema.ddl.MaxwellSQLSyntaxError: SET
> 
> Oct 28, 2022 @ 06:10:40.201	06:10:40,199 INFO  TaskManager - Stopping: com.zendesk.maxwell.replication.BinlogConnectorReplicator@5a1d68e0
> 
> Oct 28, 2022 @ 06:10:40.201	06:10:40,198 INFO  TaskManager - Stopping: com.zendesk.maxwell.bootstrap.BootstrapController@3857c48d
> 
> Oct 28, 2022 @ 06:10:40.220	06:10:40,219 INFO  AbstractConnector - Stopped ServerConnector@7152d3c1{HTTP/1.1, (http/1.1)}{0.0.0.0:8080}
> 
> Oct 28, 2022 @ 06:10:40.223	06:10:40,223 INFO  ContextHandler - Stopped o.e.j.s.ServletContextHandler@5628733f{/,null,STOPPED}
> 
> ct 28, 2022 @ 06:10:41.637	06:10:41,636 INFO  TaskManager - Stopped all tasks
> ```

**Comment by grooverdan** [comment]
To get to `com.zendesk.maxwell.schema.ddl.SchemaChange.parse(SchemaChange.java:108`, it passed the blacklist a few lines above.

The blacklist at the top of this file seems intend to catch `FLUSH` SQL, but with the `SET STATEMENT max_statement_time = 60 FOR flush table` this isn't sufficient to match the regex.

**Comment by 29swastik** [comment]
Yeah was able to replicate this with one of the test cases written in Maxwell. 

So how can we solve this issue?. Is there any config to handle this type of Regex. 

Also This statement is not executed by any of our applications looks like some process in RDS is executing this.

**Comment by grooverdan** [comment]
I think just strip out the statement `SET STATEMENT ... FOR\s` in  `matchesBlacklist` just like the current implementation strips the comments.

**Comment by 29swastik** [comment]
Like this?
`--filter = blacklist: SET STATEMENT max_statement....`

**Comment by grooverdan** [comment]
In the [Maxwell implementation](https://github.com/zendesk/maxwell/blob/0e924210e7574125a4c44044b111b68529d81a72/src/main/java/com/zendesk/maxwell/schema/ddl/SchemaChange.java#L62), I'd include more than that just `max_statement_time` An session system variable can be applied on this statement. The problem is `set statement ... for` can be used for statements you don't want to blacklist like ordinary `insert` / `update`.

As a workaround for you, `--filter = blacklist: SET STATEMENT max_statement_time=60 FOR flush` (maybe with ` table` too) seems like something that could get around your existing issue (I having never used Maxwell, mileage may vary).

**Comment by 29swastik** [comment]
Thanks for the help 🙏

**Comment by grooverdan** [comment]
I'd leave this as an open issue. It isn't something you should need to manually work around. Adjust issue topic to something like SET STATEMENT forms of blacklisted items aren't parsed

**Comment by 29swastik** [comment]
> As a workaround for you, `--filter = blacklist: SET STATEMENT max_statement_time=60 FOR flush` (maybe with ` table` too) seems like something that could get around your existing issue (I having never used Maxwell, mileage may vary).

Unfortunately, workaround didn't help, looks like blacklisting a statement isn't supported. Also since this statement `SET STATEMENT max_statement_time=60 FOR flush` is likely to be executed on `mysql` db, I tried blacklisting that db itself but that also didn't work not sure why

Both below didn't work

`--filter="exclude:MY_DB.*, blacklist: SET STATEMENT max_statement_time=60 FOR flush table, include:MY_DB.my_table_1, ....  `

`--filter="exclude:MY_DB.*, blacklist: mysql.*, include:MY_DB.my_table_1, ....  `

**Comment by grooverdan** [comment]
lucky a proper solution is in the works - #1934  :-)

**Comment by 29swastik** [comment]
When is that expected to go, curious
