### ISSUE TITLE
Timers exported in metrics exported as seconds instead of milliseconds as documented

### ISSUE THREAD

**Issue by msg555** [zendesk/maxwell#1944]
`message.publish.time`, `replication.queue.time`, and `message.publish.age` are each published in units of seconds rather than milliseconds as indicated by the documentation.

It looks like the metrics server automatically converts to seconds by default and has a servlet config key `com.codahale.metrics.servlets.MetricsServlet.durationUnit` to control what unit the data is exported as, as described in https://metrics.dropwizard.io/4.2.0/manual/servlets.html. As the default is seconds it appears that is what we are getting.

For example, when I query /metrics I get the below for my "message.publish.age" metric. Note that the "duration_units" field indicates the units are "seconds".

```json
{
  "maxwell.message.publish.age": {
      "count": 1200,
      "max": 0.751,
      "mean": 0.751,
      "min": 0.545,
      "p50": 0.751,
      "p75": 0.751,
      "p95": 0.751,
      "p98": 0.751,
      "p99": 0.751,
      "p999": 0.751,
      "stddev": 4.971789762942413e-43,
      "m15_rate": 7.67614725242547e-06,
      "m1_rate": 6.497535997190759e-35,
      "m5_rate": 1.0991035976292236e-09,
      "mean_rate": 0.006368745781449043,
      "duration_units": "seconds",
      "rate_units": "calls/second"
    }
}
```

**Comment by osheroff** [comment]
ok.  Unless you think I should enable a config option to change this I'm just gonna update the documentation to remove a mention of units and consider this fixed?  the slf4j report does milliseconds, I'm not sure what the jmx or datadog reporter do....

**Comment by msg555** [comment]
Just changing the documentation sounds good to me
