### ISSUE TITLE
Unknown table 'CHECK_CONSTRAINTS' in information_schema

### ISSUE THREAD

**Issue by soshika** [zendesk/maxwell#1949]
I have this issue when i try to use rabbit-mq  producer .
i ran this command:   `bin/maxwell --user='maxwell' --password='' --host='' --producer=rabbitmq --rabbitmq_user="" --rabbitmq_pass="" --rabbitmq_message_persistent=true`

and i got this error as a result :
2022-11-29 08:21:22 INFO  AbstractSchemaStore - Maxwell is capturing initial schema
2022-11-29 08:21:26 INFO  TaskManager - Stopping 1 tasks
2022-11-29 08:21:26 ERROR TaskManager - cause:
com.zendesk.maxwell.schema.SchemaStoreException: java.sql.SQLSyntaxErrorException: Unknown table 'CHECK_CONSTRAINTS' in information_schema

**Comment by osheroff** [comment]
yeah there's a bug with mariadb support for certain versions.  I'll have to do some fixes.

**Comment by soshika** [comment]
@osheroff Thanks

**Comment by osheroff** [comment]
hey what version is your server?  I can't actually reproduce this error.

**Comment by soshika** [comment]
Hey @osheroff 
Server version: 10.1.48-MariaDB-0+deb9u1 - Debian 9.13

**Comment by dalaopo** [comment]
Hi!
we had the same problem，information_schema has no tables but only views，we created tables with the same structure, temporarily bypassing this problem

**Comment by osheroff** [comment]
fixed this in 1.39.4
