### ISSUE TITLE
a question about filter

### ISSUE THREAD

**Issue by dalaopo** [zendesk/maxwell#1956]
We are doing boot-strap data from mysql to kafka, but I have some tables which are not wanted,this is my config
```
filter=exclude: *.*, include: members.*, include: heimdallr.*, include: information_schema_tables.*, include: recognize_daily.*, include: recognize.*, include: t8891.*
```
I don't want to monitor table1，table2, table3's decoration and the table name has no rules,I tried many ways.
t8891.t_admin_access
t8891.t_carinfo_tts
heimdallr.t_reven_sale_value
are the tables I don't want to monitor

**Comment by osheroff** [comment]
I don't understand your issue, exactly.  Bootstrapping doesn't honor include/exclude filters -- if you want to bootstrap a table, you do so, otherwise don't start the bootstrap process for a table.  If there's another issue, please re-open the issue.
