### ISSUE TITLE
How to avoid this problem

### ISSUE THREAD

**Issue by dalaopo** [zendesk/maxwell#1958]
Hello！

When I was doing synchronization, I reported an error about the different positions of the fields。
![94d526904e8bbe5eeaeeb397d8636425-239347](https://user-images.githubusercontent.com/48463475/207578252-b5a2de0d-3771-43e4-b133-419cb4598318.png)
But 

The data when I was doing bootstrap is the same as the data at this point, and no fields have been added, so I don’t understand why this error occurs。
How should I troubleshoot or is there any solution?

**Comment by dalaopo** [comment]
sorry,I saw that they added a field, but my maxwell did not read it. It may be caused by my use of --init_position. This is my command 
```
--bin/maxwell -config config.properties --jdbc_options='useSSL=false&serverTimezone= Asia/Shanghai' --init_position=mysql-bin.000016:4
```
This should be the earliest position

**Comment by dalaopo** [comment]
There is no rule in the column table and how to solve the change of the table

**Comment by dalaopo** [comment]
There is no rule in the column table and how to solve the change of the table

**Comment by osheroff** [comment]
you're right yes.  `--init_position` is *really* dangerous and you shouldn't use it unless you know what you're doing -- you can miss schema updates, which is probably what happened here.  I'm going to add a note to not use it generally.

**Comment by dalaopo** [comment]
> 你是对的。 `--init_position`真的_很_危险，除非您知道自己在做什么，否则不应使用它——您可能会错过架构更新，这可能就是这里发生的情况。我要添加一个注释，一般不要使用它。


Can I manually add the change column of this table to the column table?

**Comment by dalaopo** [comment]
I deleted the cloumn related to the table and added it again to solve this problem
