### ISSUE TITLE
better starter script 

### ISSUE THREAD

**Issue by xmlking** [zendesk/maxwell#196]
checking if there is any interest to implement  `maxwell` starter script to support start, restart, stop, status  etc in the background mode. something similar to :

https://github.com/apache/nifi/blob/b809031195405c04ec7a950c293482225f64e8dc/nifi-nar-bundles/nifi-framework-bundle/nifi-framework/nifi-resources/src/main/resources/bin/nifi.sh

**Comment by osheroff** [comment]
I don't personally, as I just use runit to daemonize, but if others had interest I'd be fine.

**Comment by darionyaphet** [comment]
@osheroff maxwell is a long running service some GC and memory parameter should be config ?
