### ISSUE TITLE
Kafka default version

### ISSUE THREAD

**Issue by miked0004** [zendesk/maxwell#1963]
I've found I can only get maxwell to work with my kafka cluster is to 
explicitly set `--kafka_version=2.7.0`. I'm using the maxwell version `1.39.4`. 

Looking at [bin/maxwell](https://github.com/zendesk/maxwell/blob/master/bin/maxwell#L21) & the docs, I see `1.0.0` is the default and didn't see a mention of `2.7.0` as an option.  

Just wondering if there is a reason for keeping a default of 1.0.0 versus the latest in your code. 

Thank you

**Comment by osheroff** [comment]
nope, go ahead and open a PR for making the default the latest if you like

**Comment by osheroff** [comment]
fixed in latest master
