### ISSUE TITLE
Error parsing SQL: 'ALTER TABLE task ADD COLUMN IF NOT EXISTS

### ISSUE THREAD

**Issue by fzwart** [zendesk/maxwell#1968]
maxwell version 1.35.3
Maxwell has stopped running, probably because of the error below. An SQL validator like https://www.eversql.com/sql-syntax-check-validator/ seems to suggest that the "IF NOT EXISTS" addition is invalid even though MariaDB has accepted the query.

Could you maybe give us some pointers on how we can make Maxwell accept this query?

```
ERROR MysqlParserListener - (alter_partition_specification ADD COLUMN IF NOT EXISTS deleted_at DATETIME NULL)
ERROR SchemaChange - Error parsing SQL: 'ALTER TABLE task ADD COLUMN IF NOT EXISTS deleted_at DATETIME NULL'
ERROR AbstractSchemaStore - Error on bin log position Position[BinlogPosition[master.006382:12395005], lastHeartbeat=0]
```

**Comment by osheroff** [comment]
it's a pretty simple change to the sql parser, you can see 8c8234740ba99931bc4df9ab0db08484d9ef3cc6 for an example of adding support for different statements.  DIY it and it'll get done quicker, or you can wait for me and I'll get to it.

**Comment by bartvw** [comment]
If we run into these kind of issues, is there any way to skip a single event in the log? 
It is possible to manually set the position, but we noticed that the stored position is actually way before the parse error, so how do we make sure the events are at least processed up until the one that causes the parse error?
