### ISSUE TITLE
Whether the filter parameter in config.properties can support line feeds

### ISSUE THREAD

**Issue by caofanqi** [zendesk/maxwell#1976]
![image](https://user-images.githubusercontent.com/39029623/218674922-674b7387-a1e1-4c24-bde0-06ee6345e584.png)

![image](https://user-images.githubusercontent.com/39029623/218674995-de3d16bd-f162-470f-99e1-c5a5173f36f4.png)

**Comment by osheroff** [comment]
yes but you need to use a backslash (`\`) a the end of each line.

**Comment by caofanqi** [comment]
> yes but you need to use a backslash (`\`) a the end of each line.

thank you
