### ISSUE TITLE
Assertion Failed

### ISSUE THREAD

**Issue by jpeyper** [zendesk/maxwell#198]
Updated to 0.16.1 this morning and one of my environments reported this.

```
08:12:25,823 ERROR AbstractBinlogParser - failed to parse binlog
java.lang.RuntimeException: assertion failed!  We left -339 unconsumed bytes in the buffer for event: BinlogEventV4HeaderImpl[timestamp=1449632908000,eventType=31,serverId=11543,eventLength=102,nextPosition=917023964,flags=0,timestampOfReceipt=1450041145808]	asis-regressionprod.hq.local
		at com.google.code.or.binlog.impl.AbstractBinlogParser$Task.run(AbstractBinlogParser.java:263) [open-replicator-1.3.2.jar:?]	asis-regressionprod.hq.local
		at java.lang.Thread.run(Thread.java:745) [?:1.8.0_40]	asis-regressionprod.hq.local
		at com.google.code.or.binlog.impl.ReplicationBasedBinlogParser.doParse(ReplicationBasedBinlogParser.java:110) ~[open-replicator-1.3.2.jar:?]	asis-regressionprod.hq.local
		at com.google.code.or.net.impl.EventInputStream.finishEvent(EventInputStream.java:86) ~[open-replicator-1.3.2.jar:?]
```

**Comment by osheroff** [comment]
bah.  any chance you can get me a copy of the binlog maxwell was replicating?

**Comment by jpeyper** [comment]
Ah I doubt it, there is probably a lot of private customer data in there.

**Comment by jpeyper** [comment]
So I'm going back over the logs of that environment, looks like it wasnt 0.16.1 that caused it. 
I was running 0.16.0 over the weekend and looks like the first occurrence was Friday evening.

**Comment by osheroff** [comment]
maybe just a snippet of the file then?  ```hexdump -n 600 -s 917023862 [file]```

I doubt it was any recent upgrade that cause this -- this is a low-level problem in open-replicator somewheres, just need to figure out what/why -- it's running off the end of the binlog event, meaning either there's a problem with the header size or something in the rows themselves

**Comment by jpeyper** [comment]
I've asked out DBA whether he can provide that for us. I've reset maxwell (dropped the maxwell schema) now so it starts from the current positions.

**Comment by osheroff** [comment]
k.  to be clear, the situation was consistent?  ie if you pointed maxwell at that binlog position, it would crash every time?

**Comment by jpeyper** [comment]
well it was consistanly crashing over the course of the weekend, since Wednsays 3PM. kept on printing different log positions when crashing.

The last thing before it started version 0.15.0 was this line
```
MaxwellCompatibilityError: binlog_row_image must be FULL.
```
My DBA fixed that and then this error occured. Could that be related?

**Comment by jpeyper** [comment]
This was the first one
```
14:57:50,728 ERROR AbstractBinlogParser - failed to parse binlog
java.lang.RuntimeException: assertion failed!  We left -339 unconsumed bytes in the buffer for event: BinlogEventV4HeaderImpl[timestamp=1449632908000,eventType=31,serverId=11543,eventLength=102,nextPosition=917023964,flags=0,timestampOfReceipt=1449633470725]
```

**Comment by osheroff** [comment]
yes, could be related; maybe these are still MINIMAL events (old sessions not having picked up the new setting), and that code path isn't super-well tested.  Just as a lark, what's the table schema?  I fixed a bug  in open-replicator around longer bitfields, this could be related if there's a bunch of columns....

**Comment by osheroff** [comment]
(https://dev.mysql.com/doc/refman/5.6/en/show-binlog-events.html) can be helpful if you've got the right permissions..

**Comment by jpeyper** [comment]
sorry, which table did you want to get the schema for?

I ran `SHOW BINLOG EVENTS` and here are the results around (before and after) positions 917023964 in sthx11543-bin.000002

| Log_name | Pos | Event_type | Server_id | End_log_pos | Info |
| -------------------- | ---------: | ----------- | ---------: | ---------: | -------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------- |
| sthx11543-bin.000002 | 917023516 | Query | 11543 | 917023587 | BEGIN |
| sthx11543-bin.000002 | 917023587 | Table_map | 11543 | 917023721 | table_id: 2488517 (map.reginvrun_d) |
| sthx11543-bin.000002 | 917023721 | Table_map | 11543 | 917023862 | table_id: 2488528 (map_audit.reginvrun_d) |
| sthx11543-bin.000002 | 917023862 | Update_rows | 11543 | 917023964 | table_id: 2488517 flags: STMT_END_F |
| sthx11543-bin.000002 | 917023964 | Xid | 11543 | 917023995 | COMMIT /* xid=73573582 */ |
| sthx11543-bin.000002 | 917023995 | Query | 11543 | 917024066 | BEGIN |
| sthx11543-bin.000002 | 917024066 | Query | 11543 | 917027587 | use `asp`; CREATE TABLE `cgt`.`20151209_asp_24795__cgpos_0_476701b0419342cfa10c27e1decd28a5` (`id` int(11) NOT NULL DEFAULT '0', `trnnum` int(11) DEFAULT NULL, `seq` int(1) NOT NULL DEFAULT '0', `trnnumrev` bigint(11) NOT NULL DEFAULT '0', `memberno` varchar(8) DEFAULT NULL, `imnum` int(11) DEFAULT '0', `memclass` char(1) DEFAULT NULL, `type` char(1) DEFAULT NULL, `imdispcode` varchar(13) DEFAULT '0', `imname` varchar(40) DEFAULT NULL, `divname` varchar(40) DEFAULT NULL, `dispname` varchar(60) DEFAULT NULL, `batch` int(11) DEFAULT NULL, `effdate` date DEFAULT NULL, `duedate` date DEFAULT NULL, `trntype` char(1) DEFAULT NULL, `trnsubtype` char(1) DEFAULT NULL, `short` varchar(14) DEFAULT NULL, `cgtax` decimal(13,2) DEFAULT NULL, `gross` decimal(13,2) DEFAULT NULL, `costs` decimal(13,2) DEFAULT NULL, `tax` decimal(13,2) DEFAULT NULL, `net` decimal(13,2) DEFAULT NULL, `assetvalue` decimal(17,9) DEFAULT NULL, `holding` decimal(17,6) DEFAULT NULL, `units` decimal(17,6) DEFAULT NULL, `units_before` decimal(16,6) NOT NULL DEFAULT '0.000000', `units_after` decimal(16,6) NOT NULL DEFAULT '0.000000', `units_review` decimal(16,6) NOT NULL DEFAULT '0.000000', `review_status` int(2) NOT NULL DEFAULT '0', `ir_taxfree` decimal(13,2) NOT NULL DEFAULT '0.00', `ir_taxdef` decimal(13,2) NOT NULL DEFAULT '0.00', `ir_capreturn` decimal(13,2) NOT NULL DEFAULT '0.00', `cg_o_taxfree` decimal(13,2) NOT NULL DEFAULT '0.00', `cg_o_taxdef` decimal(13,2) NOT NULL DEFAULT '0.00', `cg_o_capreturn` decimal(13,2) NOT NULL DEFAULT '0.00', `cg_taxfree` decimal(13,2) NOT NULL DEFAULT '0.00', `cg_taxdef` decimal(13,2) NOT NULL DEFAULT '0.00', `cg_capreturn` decimal(13,2) NOT NULL DEFAULT '0.00', `adj_taxfree` decimal(16,6) NOT NULL DEFAULT '0.000000', `adj_taxdef` decimal(16,6) NOT NULL DEFAULT '0.000000', `adj_capreturn` decimal(16,6) NOT NULL DEFAULT '0.000000', `iadj_taxfree` decimal(16,6) NOT NULL DEFAULT '0.000000', `iadj_taxdef` decimal(16,6) NOT NULL DEFAULT '0.000000', `iadj_capreturn` decimal(16,6) NOT NULL DEFAULT '0.000000', `adj_gross` decimal(12,2) NOT NULL DEFAULT '0.00', `cb_short` decimal(12,2) NOT NULL DEFAULT '0.00', `cb_long` decimal(12,2) NOT NULL DEFAULT '0.00', `cb_index` decimal(12,2) NOT NULL DEFAULT '0.00', `cb_loss` decimal(12,2) NOT NULL DEFAULT '0.00', `cba_short` decimal(12,2) NOT NULL DEFAULT '0.00', `cba_long` decimal(12,2) NOT NULL DEFAULT '0.00', `cba_index` decimal(12,2) NOT NULL DEFAULT '0.00', `cba_loss` decimal(12,2) NOT NULL DEFAULT '0.00', `cg_costbase` decimal(14,2) NOT NULL DEFAULT '0.00', `cg_indexcost` decimal(13,2) NOT NULL DEFAULT '0.00', `cg_costdate` date DEFAULT NULL, `cb_indexfactor` decimal(8,5) NOT NULL DEFAULT '0.00000', `cg_minKdate` date DEFAULT NULL, `cg_soldtrn` bigint(11) NOT NULL DEFAULT '0', `cg_solddate` date DEFAULT NULL, `cg_assetvalue` decimal(17,9) DEFAULT NULL, `cg_proceeds` decimal(13,2) DEFAULT '0.00', `cg_method` char(1) DEFAULT '', `cg_short` decimal(13,2) DEFAULT NULL, `cg_long` decimal(13,2) DEFAULT '0.00', `cg_index` decimal(13,2) DEFAULT '0.00', `cg_loss` decimal(13,2) DEFAULT '0.00', `cgtevent` char(1) DEFAULT 'Y', `cg_id` int(11) DEFAULT '0', `zzzdate` varchar(8) DEFAULT NULL, `zzztime` varchar(11) DEFAULT NULL, `zzzusrcode` varchar(8) DEFAULT NULL, `orderdate` date DEFAULT NULL, `Status` int(1) NOT NULL DEFAULT '0') |
| sthx11543-bin.000002 | 917027587 | Query | 11543 | 917027659 | COMMIT |

Hope that helps

**Comment by osheroff** [comment]
would love to get the schema for `map.reginvrun_d` -- that's the table that corresponds to the binlog event that starts at 917023862, which is the one that crashed maxwell

**Comment by osheroff** [comment]
My guess is that there's more than 8 columns in that table, and that if we were to put that row under a microscope, we'd find it was a MINIMAL format row.  Found a bug down in open-replicator.

**Comment by jpeyper** [comment]
I can confirm, there is definately more than 8 columns in map.reginvrun_d, closer to 40.

seems like that is the cause of this issue.

The bug you found in open-replicator, is that what caused such a cryptic error to appear?

**Comment by osheroff** [comment]
yeah, looks very much like the case.  open-replicator has a subtle error from the mysql spec; it's reading `nColumns` bits from a field that deals with what columns are null, but it's supposed to be reading `nUsedColumns` bits.

**Comment by wushujames** [comment]
Ooh, that's exciting. And probably only just surfaced because you started parsing minimal columns, which is the only time nColumns != nUsedColumns.

**Comment by osheroff** [comment]
ayup.  https://github.com/zendesk/open-replicator/pull/13

**Comment by jpeyper** [comment]
glad I could help :)

**Comment by osheroff** [comment]
Fixed in https://github.com/zendesk/maxwell/releases/tag/v0.16.2
