### ISSUE TITLE
Schema change parser error with json indexes on MySQL 8

### ISSUE THREAD

**Issue by Marc3001** [zendesk/maxwell#1982]
We are currently running Maxwell 1.39.3 to sync a MySQL8 instance to GCP PubSub.
We encountered issue when modifying some tables with json columns.

Maxwell schema parser seems to not like some index creation on JSON fields. It will crash with following error.
`ERROR SchemaChange - Error parsing SQL: 'ALTER TABLE tournaments ADD INDEX idx_team_name (('$.teams.name'))'`

I don't see any SQL error in this request and it has been successfully processed by MySQL engine.

**Comment by osheroff** [comment]
ok i posted a patch, but i don't think that index isn't doing what you want -- that's literally just indexing the string '$.teams.name', you want _something_ like:

```
add  INDEX idx ((CAST(data->>"$.teams.name" AS CHAR(30)) COLLATE utf8mb4_bin))
```
