### ISSUE TITLE
Change maxwell output log pattern

### ISSUE THREAD

**Issue by lucastex** [zendesk/maxwell#1983]
Hi guys, 

Is it possible to change the output patter of maxwell's log messages? We have some maxwell instances in our infrastructure and we want to handle those log messages the same way we handle our application's logs, parsing and ingesting it in our log analyzer.

Thanks,

Lucas

**Comment by osheroff** [comment]
yup it's all controlled by the log4j2.xml file in the root of the maxwell install -- check out "PatternLayout".
