### ISSUE TITLE
document repari

### ISSUE THREAD

**Issue by luo981695830** [zendesk/maxwell#1985]
document website:https://maxwells-daemon.io/high_availability/

error:
if all goes well, the 3 nodes will communicate via multicast/UDP, elect one to be the cluster leader, and away you will go. If one node is terminated or partitioned, a new election will be held to replace it.

right:
if all goes well, the 3 nodes will communicate via multicast/UDP, select（fixed content） one to be the cluster leader, and away you will go. If one node is terminated or partitioned, a new election will be held to replace it.

**Comment by osheroff** [comment]
nope they do hold what's known as an election, thx tho

**Comment by luo981695830** [comment]
that's ok。elect is more suitable。thank you for your reply
