### ISSUE TITLE
Docker maxwell only picking up CREATE TABLE commands

### ISSUE THREAD

**Issue by himanshub1995** [zendesk/maxwell#1999]
Using maxwell for the first time. 
I am running maxwell on docker and the connections seem to be working fine. However, apart from CREATE TABLE commands, maxwell is not logging any actions like INSERT, UPDATE, DELETE etc. It just seems to be storing schema. 

_AbstractSchemaStore - storing schema @Position[BinlogPosition[master.000001:92791], lastHeartbeat=1681237453184] after applying "create table test_table1 (id int, name varchar(255))" to maxwell, new schema id is 3_

Am I missing any configuration or command or running the daemon in a wrong manner. Any help would be appreciated. TIA.

**Comment by osheroff** [comment]
what producer are you using?

**Comment by himanshub1995** [comment]
Was using kafka. There was a problem on consumer side. Maxwell seems to be working fine.
