### ISSUE TITLE
TableColumnList affects the performance of restoreFullSchema 

### ISSUE THREAD

**Issue by dpy1123** [zendesk/maxwell#2011]
Hi team, 
I'm using a huge mysql instance which has 500+ tables, 20k+ tables and 247k+ columns. 
During schema restore at first time,  calling `MysqlSavedSchema#restoreFullSchema`. The qurey is fast but the whole process is slow, takes like 2mins. I find that `TableColumnList#add` is very inefficient.
change from:
```
tempList.addAll(columns);
tempList.add(index, definition);
```
<img width="982" alt="image" src="https://github.com/zendesk/maxwell/assets/3691507/00a6aed8-c6fa-4c07-9554-0148fe4a9816">

to:
```
tempList.addAll(columns.subList(0, index));
tempList.add(definition);
tempList.addAll(columns.subList(index, columns.size()));
```
<img width="1040" alt="image" src="https://github.com/zendesk/maxwell/assets/3691507/82a134c0-06b3-4d32-b421-29135bbbf4c2">

and restoreFullSchema takes only like 10s. (Changed log level to see clearly.)

**Comment by osheroff** [comment]
fixed in 1.40.1

**Comment by dpy1123** [comment]
hi team,
pls also optimize here `com.zendesk.maxwell.schema.SchemaCapturer#captureTables`

**Comment by osheroff** [comment]
please open a pr thx
