### ISSUE TITLE
jackson-core security vulnerability

### ISSUE THREAD

**Issue by zbehr** [zendesk/maxwell#2013]
Maxwell is used at the company I work for and the following security vulnerability pertaining to one of its dependencies was recently identified:

com.fasterxml.jackson.core_jackson-core package versions before 2.15.0 are vulnerable to Denial of Service (DoS). The package does not properly restrict the size or amount of resources that are requested or influenced by an actor, which can be used to consume more resources than intended and leads to Uncontrolled Resource Consumption ('Resource Exhaustion').

Consequently, we're requesting the maintainers of this software update the code to leverage at least version 2.15.0 of jackson-core, per [this](https://github.com/FasterXML/jackson-core/pull/827) PR conversation.

**Comment by osheroff** [comment]
will be included in next release
