### ISSUE TITLE
Want to  run Maxwell and MySQL on separate servers

### ISSUE THREAD

**Issue by shwetadesai-tgs** [zendesk/maxwell#2024]
I am using Maxwell 1.40.2 and MySQL 8.0.31. I am running Maxwell in Ubuntu through the Windows WSL feature. I use RabbitMQ as a producer.
Issue : I want to run Maxwell on a separate host and Mysql on a separate host. 
Ex, Transaction MySql  running  on 192.168.1.11  (Maxwell read binlog files from here)
Maxwell and its db configuration should be on 192.168.1.12 (Maxwell keep its bootstrap detail here with HA implemented).

I have tried host=192.168.1.12 and schema_host=192.168.1.11 but no luck. Its listen only to 12 and create Maxwell db on 12 also 

Please guide how to separate both host

**Comment by osheroff** [comment]
try `host` (schema storage here) and `replication_host` (read binlogs from here) instead.
