### ISSUE TITLE
LinkedBlockingDeque performance issue

### ISSUE THREAD

**Issue by linking12** [zendesk/maxwell#2026]
I am trying to use threads instead of processes to solve the problem of multiple databases connecting to the same maxwell process;
But we run into a problem:
When on 4c/8g the cpu usage is too high and the bottleneck is on the LinkedBlockingDeque, my question is:
1: Is there any way to discard LinkedBlockingDeque? I don't quite understand the following code:

```
  switch (event. getType()) {
                 case WRITE_ROWS:
                 case EXT_WRITE_ROWS:
                 case UPDATE_ROWS:
                 case EXT_UPDATE_ROWS:
                 case DELETE_ROWS:
                 case EXT_DELETE_ROWS:
                     LOGGER.warn("Started replication stream inside a transaction. This shouldn't normally happen.");
                     LOGGER.warn("Assuming new transaction at unexpected event:" + event);

                     queue.offerFirst(event); // what this means?
                     rowBuffer = getTransactionRows(event);
                     break;
```
2: Have you considered using Jctools to achieve a lock-free effect?

**Comment by osheroff** [comment]
Can you show a profile that illustrates the problem?  The
linkedblockingdeque is the communication channel between the
BinaryLogClient (low level, talks to mysql) and
BinlogConnnectorReplicator (higher level, turns rows into json and sends to
the producer).  lock-free is not relevant to the current architecture as
there's only one BinlogConnectorReplicator thread currently.

**Comment by linking12** [comment]
<img width="1618" alt="Wea 2023-07-08T13_33_43 200Z" src="https://github.com/zendesk/maxwell/assets/4882172/d0260de6-26fc-4882-82fa-90c952c99a3c">
<img width="509" alt="Wea 2023-07-08T13_35_31 812Z" src="https://github.com/zendesk/maxwell/assets/4882172/9ae2bfca-548a-4620-94fd-5b5128809fc8">

Another about  queue.offer(ep, 100, TimeUnit.MILLISECONDS ) has missed

**Comment by linking12** [comment]
<img width="1615" alt="Wea 2023-07-11T09_04_31 501Z" src="https://github.com/zendesk/maxwell/assets/4882172/3c3b720b-fd50-4a37-83d6-12739cfbd7d9">
As you you see , LinkedBlockingDeque lock consume too much cpu

**Comment by linking12** [comment]
<img width="1615" alt="image" src="https://github.com/zendesk/maxwell/assets/4882172/651c28a0-c9d8-4e90-991c-2d0760929c5e">

**Comment by osheroff** [comment]
can you post these benchmarks in an html format somewhere?  It looks like maybe this is a benchmark of an instance that isn't actually producing any json?  In benchmarks I've done creating JSON was always by far the most limiting factor of maxwell's performance.

**Comment by linking12** [comment]
> can you post these benchmarks in an html format somewhere? It looks like maybe this is a benchmark of an instance that isn't actually producing any json? In benchmarks I've done creating JSON was always by far the most limiting factor of maxwell's performance.

* sorry，i can not provide html format, i think pic can explain the issue；
* my test scenario is that an aws RDS cluster contains multiple instances, and the binlog is sent by the cluster, so there is indeed a situation where no json is generated, because this is not the binlog expected by the downstream；

**Comment by linking12** [comment]
> you're welcome to try jctools if you like; somehow i doubt it's going to give you the performance boost you want. `offerFirst` is a method that puts an object back onto the head of the queue in case we didn't want to consume the object.
> 
> another idea might be to play around with `BinlogConnectorEventListener#onEvent` and:
> 
> * buffer 50 rows in an array
> * flush the buffer to the queue using `addAll` once it's 50 rows or after X milliseconds have passed

@osheroff  Thanks for you quick reply;
* by you idea i can do not care about offerFirst? discard this event is simple and direct？
* In fact I tried the solution of batch addAll，but will bring pressure on the GC, after all, a lot of data needs to be cached in the JVM memory
    ```
        @Override
        public void handler(EventSpscArrayQueue<BinlogConnectorEvent> queueCache) {
            List<BinlogConnectorEvent> temp = Lists.newArrayList();
            do {
                temp.add(queueCache.poll());
            } while (queueCache.isEmpty());
            queue.addAll(temp);
        }
    ```
   so this is not a good solution for problem

**Comment by osheroff** [comment]
> by you idea i can do not care about offerFirst? discard this event is simple and direct？

no.

**Comment by RoySunnySean007** [comment]
Dear @osheroff ,

We encountered the same issue as well.  Could u pls kindly let me know if there is any performance overhead to use thread instead of process?

Really appreciate ur great help in advance!

Thanks,
Roy
