### ISSUE TITLE
Unable to start Maxwell container along with mysql 

### ISSUE THREAD

**Issue by kvk24680** [zendesk/maxwell#2054]
URISyntaxException: Illegal character in opaque part at index 18: jdbc:mysql://mysql :3306?allowPublicKeyRetrieval=true&connectTimeout=5000&zeroDateTimeBehavior=convertToNull&useSSL=false&characterEncoding=UTF-8&tinyInt1isBit=false

**Comment by osheroff** [comment]
you have a space in your url.
