### ISSUE TITLE
Allow persistent variables in Javascript filters

### ISSUE THREAD

**Issue by kellertobias** [zendesk/maxwell#2063]
In our company we have the issue that there are some big data jobs that should not end up in or cdc events.

Currently we have a date based filter in place, however that solution is not very good. 

We know when the data jobs start and when they end, because they start and end always with the same commands.

We would like to do something like this:

```
let currentlyDisabled = false;

function process_row(row) {
    ...
    // enable/ disabled based on changes
    if(first command of data job found) {
       currentlyDisabled = true
    }
    if(last command of data job found) {
       currentlyDisabled = false
    }
    if(currentlyDisabled) {
      row.suppress()
   }
}

```

**Comment by osheroff** [comment]
reasonable enough, I think maybe easier would be to do like:

```
function process_row(row, state) {
    ...
    // enable/ disabled based on changes
    if(first command of data job found) {
       state.currentlyDisabled = true
    }
    if(last command of data job found) {
       state.currentlyDisabled = false
    }
    if(state.currentlyDisabled) {
      row.suppress()
   }
}
```

any desire to take a pass at a PR?

**Comment by kellertobias** [comment]
Well, I am usuailly a typescript/ node developer and also do not have direct access to our deployment of maxwell at the moment, just to the repo were our filter scripts lay in.

**Comment by kellertobias** [comment]
Let's do the same for the DDL function

**Comment by kellertobias** [comment]
Added yet another PR: https://github.com/zendesk/maxwell/pull/2066
