### ISSUE TITLE
Allow for separation of schema store and replication stream

### ISSUE THREAD

**Issue by trivedipankaj** [zendesk/maxwell#208]
When I'm running maxwell, I get the following error:

WARN  MaxwellReplicator - Unhandled QueryEvent inside transaction: QueryEvent[header=BinlogEventV4HeaderImpl[timestamp=1450339656000,eventType=2,serverId=10,eventLength=259,nextPosition=684603801,flags=0,timestampOfReceipt=1450344595074],threadId=2935445014,elapsedTime=0,databaseNameLength=[],errorCode=0,statusVariablesLength=26,statusVariables=[QFlags2Code[flags=0], QSQLModeCode[sqlMode=0], QCatalogNzCode[catalogName=std], QCharsetCode[characterSetClient=8,collationConnection=8,collationServer=8]],databaseName=******,sql= *****AN INSERT QUERY****]

seems like eventType=2 in the above object is not handled in the code.

Please help.

**Comment by osheroff** [comment]
This means that Maxwell received a STATEMENT based replication row where it didn't expect it.  Maxwell only deals with ROW based replication events.  Seeing this warning generally means that when you  did `set GLOBAL binlog_format=ROW`, there were still some mysql sessions left open to your mysql server.  These mysql sessions will continue to write STATEMENT based replication rows until they reconnect to the server.

It could also mean that you started Maxwell with `binlog_format=ROW`, but switched back to `binlog_format=STATEMENT` after Maxwell was running.

**Comment by trivedipankaj** [comment]
Thanks. I want to clarify that I am only changing the binlog_format to ROW for the slave machine and master still continues to be in STATEMENT format. Will that be a problem?

**Comment by osheroff** [comment]
that will be a problem.  maxwell can only operate with row based replication on, and has no support for running on a slave (it requires write access to a database where it stores its position and schema).

**Comment by trivedipankaj** [comment]
The problem is that we can't change the binlog_format at our master. Is there any way around to be able to read relay logs at the slave and get all the queries in form of events?

**Comment by osheroff** [comment]
not at present; it'd require that you have one server that stores the schema and positions, and a different server that provides the replication.  In theory this isn't a huge change, but at the moment maxwell doesn't support it.

**Comment by osheroff** [comment]
if you needed a nasty work around, you could try:

- set `read_only = 0` on the slave
- start maxwell with `--replay`

But I'm not guaranteeing this to work, at all.

**Comment by wushujames** [comment]
Ben, are you sure that maxwell won't work on a slave? What if the slave is row based and has log_slave_updates turned on?

I know that when using my own binlog listener (equivalent to Maxwell), I've been able to do
Master->Slave->Maxwell.

Master was writing binlogs as statements
Slave was receiving statements and writing binlogs as rows.
And then my Maxwell-equivalent was reading the row-based binlogs.

Wouldn't that work? Maxwell would then store its position and schema in the slave.

**Comment by trivedipankaj** [comment]
I have already set read_only to 0 at the slave and the maxwell is perfectly writing to the maxwell database at the slave. My only problem is that the maxwell is receiving binlog in STATEMENT format, probably because it is reading relay logs at the slave. 

@wushujames Can you please confirm if the above arrangement works, I would like to have a similar setup. 

Thanks

**Comment by osheroff** [comment]
@wushujames, It'll... work.  There's nothing technical that should differentiate the master from the slave.  But I can't really recommend the configuration, as you'll be writing maxwell updates to the slave database only, which will desynchronize the master and slave.

If I (or someone) writes a patch to allow maxwell's replication stream to point to a different place than where it stores data, it'd be a fine configuration.

**Comment by trivedipankaj** [comment]
Well, it is working now, exactly like how @wushujames  mentioned. The only problem was that it took time to reflect the ROW format even after restart of the slave.

Thanks Guys!

**Comment by osheroff** [comment]
cool, glad to hear it's working for you.  I'll leave this issue open, just as a feature request to do it more "right".

**Comment by trivedipankaj** [comment]
cool. Thanks.

**Comment by wushujames** [comment]
@osheroff, by desynchonize, I guess what you mean is that there will be writes that go to the slave (from Maxwell) that did not also go through the masterr? So the contents of the master and slave will not be the same anymore?

I agree that it's not a great setup. @trivedipankaj, one thing you should be aware of is that it may get difficult to trace the origin of row updates. For example, if you see a row in kafka that was generated by Maxwell, you can probably trace where in the slave's binlogs it came from. But it will be difficult to trace where that in the *master's* binlogs that *slave* update came from. Does that make any sense?

**Comment by trivedipankaj** [comment]
Yes, makes sense. I can do with this constraint for now.

**Comment by osheroff** [comment]
@wushujames yup that's what I meant.

**Comment by kristiankaufmann** [comment]
I just created a branch that allows one to specify a separate mysql for the "maxwell" database. https://github.com/kristiankaufmann/maxwell/tree/different_mysql_for_schema. If there is interested I can work this up into a pull request.

**Comment by osheroff** [comment]
@kristiankaufmann yeah that'd be great.  The request has come up a couple of times now, I think.
