### ISSUE TITLE
Recommended Daemon?

### ISSUE THREAD

**Issue by danfiza** [zendesk/maxwell#209]
Whats the best way to run Maxwell as a daemon in production?

**Comment by osheroff** [comment]
at zendesk we're big fans of runit: http://smarden.org/runit/, and run maxwell under that.

**Comment by osheroff** [comment]
fwiw, we tend not to run runit as "replace init.d" but using the `runsvdir` style stuff.  

Also at some point it'd be awesome to do a debian package.  But I'm not sure how one gets things into debian.
