### ISSUE TITLE
Option for poll rate?

### ISSUE THREAD

**Issue by abccbaandy** [zendesk/maxwell#2127]
Correct me if I am wrong.

In my understand, read binlog is a infinite loop to keep check if any new sql event.

Is there an option to control the poll rate?

**Comment by osheroff** [comment]
you're wrong 😺  -- the binlog client keeps a connection always open and just waits for data from the server.  doesn't poll in the way an HTTP client would poll

**Comment by osheroff** [comment]
check the mysql internals manual:  https://dev.mysql.com/doc/dev/mysql-server/latest/

debezium's property... yeah if you read that description it's not really about polling the server, seems like not a great name.
