### ISSUE TITLE
bin log not found

### ISSUE THREAD

**Issue by trivedipankaj** [zendesk/maxwell#216]
Sometimes I'm facing the following error. It gets fixed after I delete the maxwell database and maxwell starts again from scratch.

com.google.code.or.net.TransportException: Could not find first log file name in binary log index file
	at com.google.code.or.OpenReplicator.dumpBinlog(OpenReplicator.java:288)
	at com.google.code.or.OpenReplicator.start(OpenReplicator.java:104)
	at com.zendesk.maxwell.MaxwellReplicator.beforeStart(MaxwellReplicator.java:83)
	at com.zendesk.maxwell.RunLoopProcess.runLoop(RunLoopProcess.java:25)
	at com.zendesk.maxwell.Maxwell.run(Maxwell.java:89)
	at com.zendesk.maxwell.Maxwell.main(Maxwell.java:95)
12:05:46,520 INFO  SchemaPosition - Storing final position: null

Any idea how to get it fixed. This usually happens when there is change of date, so around midnight.

**Comment by jpeyper** [comment]
From my understanding, it happens when the binlog position maxwell is at is
in a log that mysql has cleaned up and deleted.

So if maxwell hasn't been running for a few days, and your logs aren't
being kept long enough, you will get this error.

My guess is in your case you're only keeping the logs for a single day, so
at midnight it gets deleted at the same time the new log is created,
confusing maxwell.

But I'm far from an expert on the inner working of maxwell or mysql
replication, so please wait for a more official answer, but perhaps this
will help point you in the right direction.

**Comment by trivedipankaj** [comment]
Please note that it gets fixed as soon as I start maxwell from scratch (i.e. I delete maxwell database and start maxwell again), it starts working. I think it has something to do with the bin_log position that maxwell keeps track of?

**Comment by wushujames** [comment]
I think @jpeyper might be right. If you delete the Maxwell database and restart, Maxwell starts listening at the most current position, and so you will not see the error again.

In order to diagnose this more directly, the next time this occurs look at the maxwell.positions table and look at the last row. That will contain the name and position of the binlog file that Maxwell is trying to connect at.

Then, connect to your MySQL server and run "SHOW BINARY LOGS" and see if that binlog file still exists. If the file no longer exists and only newer file exist, then that would explain it: Maxwell was not able to process that particular binlog before it got deleted.

**Comment by trivedipankaj** [comment]
Thanks. Let me check out on this and get back.

**Comment by osheroff** [comment]
what these guys say is right; somehow the binary log Maxwell expects is suddenly not there.  Perhaps you have an overly aggressive log rotation script running?  

I'll put some code in the next release that catches this error and explains what's happened more clearly.

**Comment by trivedipankaj** [comment]
You guys may be right. It was broken at exactly 1:08 am today as well. I got it right by truncating maxwell.positions table, which makes sense as per your explanation. I can confirm this only on Monday after hearing back from the Infra team.

**Comment by trivedipankaj** [comment]
So, I looked at the maxwell.positions and the only row in the table was asking for filename: mysql-bin-004232 and when I run "SHOW BINARY LOGS", I can see this file in the list. Is there any chance that maxwell seeks the file before it gets created?

**Comment by osheroff** [comment]
anything's possible.  What position did maxwell stop at?  What happens if you simply restart maxwell once it hits that error?  Is there anything logged besides that error?

**Comment by trivedipankaj** [comment]
I think we figured out the issue here but not sure how to fix it. At 1 am, a lot of tables are archived and hence a lot of records are deleted from one table. (around 10 million rows), which results in a sudden pause of replication at the slave. the replication changes position and bin log filenames very quickly in this duration and maxwell loses track of that somehow.So during the deleting:

SHOW MASTER STATUS  shows same bin log position for around 3-4 minutes and suddenly the position starts changing with a new bin log file name. However , maxwell keeps the old bin log file and old position in its positions table. It does not change after that and hence it stops producing any data. 

I'm not sure if I'm very clear though. Please let me know if you require more details.

**Comment by osheroff** [comment]
ok, perhaps this is a single transaction that spans a binlog boundary (can you confirm that these 10mm rows are deleted in a single transaction?)  I'm not quite why that would cause maxwell to freak out, but it may be reproducible. 

Another possibility is that there's something still wrong (or just slow?) with how maxwell buffers very large transactions to disk.  A 10mm row event will definitely trigger maxwell to buffer to disk; if you do a periodic `ls -l /tmp/maxwell*` you should be able to see these files.  If maxwell is still chewing on the 10mm row transaction you'll see a tmpfile growing.

Can you be exceedingly clear on the timeline?

- big DELETE happens
- 3-4 minute lag
- binlog file rotates
- maxwell throws com.google.code.or.net.TransportException... when?  immediately or after some time? 

how long do you keep binlog files on the mysql server?

**Comment by osheroff** [comment]
hmmm, no, "A transaction is written in one chunk to the binary log, so it is never split between several binary logs. Therefore, if you have big transactions, you might see binary log files larger than max_binlog_size."  http://dev.mysql.com/doc/refman/5.7/en/replication-options-binary-log.html

**Comment by trivedipankaj** [comment]
I need to get some clarity on the error we see when maxwell actually stops progressing. The error that I posted in the original issue was after 9 hours, when I restarted maxwell without tempering with the positions table. (In the morning 10:30am actually). But, the binary log file with the name in positions table was displayed in SHOW BINARY LOGS;

Coming to the events I encountered yesterday night (01:08AM):

* DELETE query triggered
* the file size in the show binary logs command was static, generally it keeps changing at very rapid pace.
* SHOW MASTER STATUS was also showing static co-ordinates for the bin log file.
* MAXWELL positions table was containing same bin log file and a static position. 
* After 3-4 minutes, The SHOW MASTER STATUS and SHOW BINARY LOGS were changing the bin log positions very rapidly again and the bin log file name was incremented. The file size for old bin log file was also increased. 
* However, maxwell positions table never changed its coordinates. It never progressed further.

**Comment by osheroff** [comment]
sounds good.  Also, what version of maxwell are you running?  I had memory issues with the buffering code that I finally fixed in v0.16.2

**Comment by trivedipankaj** [comment]
I am running a bit older version though (0.14.5). I will upgrade and try. Thanks

**Comment by osheroff** [comment]
aha!  definitely upgrade.  My guess is that the 10mm row transaction was causing maxwell to run out of heap space.

**Comment by trivedipankaj** [comment]
Yes, I was thinking on the same lines too. I will upgrade today and keep you posted about the results.

**Comment by trivedipankaj** [comment]
Guys, I checked it for two days and updating the maxwell version (to 0.16.20) has fixed the issue. Thanks.

**Comment by osheroff** [comment]
@trivedipankaj good to hear it.  will keep this issue open for the task of "better error message in this case"

**Comment by osheroff** [comment]
put in some better error messaging.
