### ISSUE TITLE
 how to run the test in your open-replicator fork

### ISSUE THREAD

**Issue by wanghaisheng** [zendesk/maxwell#221]
source code https://github.com/zendesk/open-replicator/tree/master/src/test
it seems OnetimeServer.java
```
	String json = reader.readLine();
```
json is null
could you show me how to use these existing tests

**Comment by osheroff** [comment]
in theory they should  just run.  if you do:

```
cd src/test
./onetimeserver -debug
```

what happens?

**Comment by wanghaisheng** [comment]
```
Couldn't execute onetimeserver-go: Exec format error
Child exited without printing info!
```

**Comment by osheroff** [comment]
what platform are you running on?

**Comment by wanghaisheng** [comment]
ubuntu 15.10  64 bit  zsh

**Comment by osheroff** [comment]
and the output of:
`uname -s | tr '[:upper:]' '[:lower:]'`?

**Comment by wanghaisheng** [comment]
```
➜  daladala   uname -s | tr '[:upper:]' '[:lower:]'?
linux

```

**Comment by osheroff** [comment]
`ls -lR ~/.onetimeserver`?  
`which curl`?

**Comment by wanghaisheng** [comment]
/home/edwin-clear/.onetimeserver:
总用量 4
drwxrwxr-x 2 edwin-clear edwin-clear 4096 12月 21 12:51 Linux-x86_64

/home/edwin-clear/.onetimeserver/Linux-x86_64:
总用量 52
-rwxrwxr-x 1 edwin-clear edwin-clear     0 12月 21 12:51 onetimeserver-go
-rwxrwxr-x 1 edwin-clear edwin-clear 21272 12月 21 12:51 wrapper
-rw-rw-r-- 1 edwin-clear edwin-clear  2379 12月 21 12:51 wrapper.c

**Comment by wanghaisheng** [comment]
```
➜  test git:(master) ✗ curl --version
curl 7.43.0 (x86_64-pc-linux-gnu) libcurl/7.43.0 GnuTLS/3.3.15 zlib/1.2.8 libidn/1.28 librtmp/2.3
Protocols: dict file ftp ftps gopher http https imap imaps ldap ldaps pop3 pop3s rtmp rtsp smb smbs smtp smtps telnet tftp 
Features: AsynchDNS IDN IPv6 Largefile GSS-API Kerberos SPNEGO NTLM NTLM_WB SSL libz TLS-SRP UnixSockets 

```

**Comment by osheroff** [comment]
odd.  ok, I'll add some verification when it downloads the binaries.  for now, try:

```
rm -Rf ~/.onetimeserver
```

and then try the test suite again.

**Comment by osheroff** [comment]
I've also updated onetimeserver to protect against bad downloads of its subservient utilities.
