### ISSUE TITLE
datetime column does not work

### ISSUE THREAD

**Issue by wanghaisheng** [zendesk/maxwell#229]
i am using your fork of open-replicator, i have a table with a datatime column 
in mysql
```
# id, first_name, last_name, birth_date, deleted, datetime
'1', 'John', 'travaolta', '1980-01-01', 'false', '2015-08-26 17:44:55'
```
but when i read it from binlog ,it became 
```
dateTIme    Wed Aug 26 17:44:55 CST 2015
```
perhaps 
https://github.com/zendesk/open-replicator/blob/master/src/main/java/com/google/code/or/common/util/MySQLUtils.java
toDatetime2 and toDatetime should be adjusted

**Comment by wanghaisheng** [comment]
there is  a example  
https://github.com/alibaba/canal/blob/44f2b74862f67eeac2b16738475ff48cb4abdb6c/dbsync/src/main/java/com/taobao/tddl/dbsync/binlog/event/RowsLogBuffer.java

**Comment by osheroff** [comment]
you're pointing out that the timezone is CST?  Yeah, this is actually why Maxwell's timezone is set to UTC, if I recall correctly.  Maxwell also uses the `longValue` method to get back the original numeric value that mysql had stored for the datetime column : https://github.com/zendesk/open-replicator/blob/master/src/main/java/com/google/code/or/common/glossary/column/DatetimeColumn.java#L61

As far as what's "correct" -- it's unclear to me what the right thing to do here is: there's no timezone information in mysql, so in theory the datetime column in mysql could represent any timezone.  In practice, I think treating them as UTC by default (unless maybe the user configured it differently?)  Would be a fine answer.

I'm going to close this issue and open one over on the open-replicator fork, where it belongs.  I'd also happily accept patches if you wanted to try a fix.

**Comment by osheroff** [comment]
https://github.com/zendesk/open-replicator/issues/14
