### ISSUE TITLE
Local mysql server needed for interaction with remote mysql server?

### ISSUE THREAD

**Issue by rns7a1** [zendesk/maxwell#234]
I'm trying to port a Maxwell based application to another developer.  His local environment doesn't have a MySQL server installed.  I didn't think we'd need one.  We are pointing to a remote MySQL server that has the Maxwell database and works with my instance.  Is a MySQL server needed on the machine from which the Maxwell app is running, if the SQL server is remote?  I thought since it was monitoring the bin-log, it may have an alternate way of interacting with SQL server.

If it IS needed, we've just mistakenly installed SQL 5.7 (the "unsupported" version) and are having a hard  time getting it to SQL 5.6.  Any suggestions?

**Comment by osheroff** [comment]
Hi, no, there's no requirement that one has mysql installed locally.  What kind of problems are you seeing, exactly?

**Comment by rns7a1** [comment]
13:51:31,845 ERROR Maxwell - Failed to connect to mysql server @
jdbc:mysql://pulse-dev-db.istresearch.com:3306

13:51:31,846 ERROR Maxwell - Communications link failure

​

Last packet sent to the server was 0 ms ago.


On Tue, Dec 29, 2015 at 2:43 PM, Ben Osheroff <notifications@github.com>
wrote:

> Hi, no, there's no requirement that one has mysql installed locally. What
> kind of problems are you seeing, exactly?
>
> > On Dec 29, 2015, at 11:27, Rich Salaway <notifications@github.com>
> wrote:
> >
> > I'm trying to port a Maxwell based application to another developer. His
> local environment doesn't have a MySQL server installed. I didn't think
> we'd need one. We are pointing to a remote MySQL server that has the
> Maxwell database and works with my instance. Is a MySQL server needed on
> the machine from which the Maxwell app is running, if the SQL server is
> remote? I thought since it was monitoring the bin-log, it may have an
> alternate way of interacting with SQL server.
> >
> > If it IS needed, we've just mistakenly installed SQL 5.7 (the
> "unsupported" version) and are having a hard time getting it to SQL 5.6.
> Any suggestions?
> >
> > —
> > Reply to this email directly or view it on GitHub.
> >
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/zendesk/maxwell/issues/234#issuecomment-167862346>.
>

-- 

------------------------------
This e-mail and any files transmitted with it may be proprietary and are 
intended solely for the use of the individual or entity to whom they are 
addressed. If you have received this e-mail in error please notify the 
sender. Please note that any views or opinions presented in this e-mail are 
solely those of the author and do not necessarily represent those of IST 
Research. The recipient should check this e-mail and any attachments for 
the presence of viruses. IST Research accepts no liability for any damage 
caused by any virus transmitted by this e-mail.

**Comment by osheroff** [comment]
Strange to see a communications link failure.  If it was a 5.7 problem id expect to see something else.  Are you sure the machines can talk to each other?  (I.e. "mysql --host=pulse-dev..." work?)

**Comment by rns7a1** [comment]
Yup.  That was it.  Fixed the connection.  Thanks!
