### ISSUE TITLE
Maxwell/MySQL high availability setup  

### ISSUE THREAD

**Issue by xmlking** [zendesk/maxwell#248]
I have some `maxwell` high availability setup  questions. wonder if someone can help me:

**My Environment**
1. MySQL    Active / Passive 
   1. One database 
   2. max 1500tps 
2. binlogs are rotated every 15 min and archived 
3. Maxwell is pointed to Master MySQL 
4. Kafka: Three node `Kafka` cluster and one `Zookeeper`

**Capacity Planning question:**
1. How many Kafka partitions/replications are recommended for singe database?  

**High Availability question:**
in my environment binlogs are rotated every 15 min. if `maxwell` is down for more than 15 min, it will get out of sync. 
In this case, is there a high availability configuration option for Maxwell?

_MySQL outage scenario:_
1. MySQL role change scenario: [Active / passive (standby) master](https://www.packtpub.com/books/content/setting-mysql-replication-high-availability)
Is this a good idea, to have one Maxwell configured for Primary MySQL and once for passive MySQL, so that when secondary MySQL becomes master, second Maxwell will automatically emit new change records to Kafka?   

_Maxwell outage scenario:_
Is it possible to have two Maxwells connected to same MySQL(primary) in  active , standby mode? if one of the Maxwell offline, the second Maxwell will function?

**Comment by osheroff** [comment]
> How many Kafka partitions/replications are recommended for singe database?

if it's a single database, maxwell will write to a single partition -- I decided that the unit of serializability should be a logical mysql database.   As far as replica factor goes, it's really up to you.  At Zendesk we have ~100 logical databases per pod spread across multiple clusters, so have about 100 partitions.

> Is this a good idea, to have one Maxwell configured for Primary MySQL and once for passive MySQL, so that when secondary MySQL becomes master, second Maxwell will automatically emit new change records to Kafka?

I have a little wrapper script for maxwell that probes the cluster, discovers the current master, and then starts maxwell pointed at that master.  It seems to work pretty good when we promote a new master -- the old maxwell process crashes, the new master is discovered and maxwell continues along its way.

> Is it possible to have two Maxwells connected to same MySQL(primary) in active , standby mode? if one of the Maxwell offline, the second Maxwell will function?

No, what you're describing is a distributed lock, which I didn't want to have to embed that inside maxwell.  At Zendesk we use `consul lock` to do what you're describing.  There may be zookeeper based solutions too, though I'm not sure what they are.

**Comment by xmlking** [comment]
Thanks @osheroff . this is really helpful. 
Can you share if possible, your wrapper script  to re-point maxwell to current master MySQL node?  

Would be nice if you support multiple maxwell instances leach to same MySQL node for High Availability.
  
I was originally thinking this setup but your approach may reduce infrastructure requirements.   
![maxwell ha](https://cloud.githubusercontent.com/assets/627951/12398934/ab75d070-bdcb-11e5-96c8-1cafe7f6e84d.png)

**Comment by osheroff** [comment]
my script is pretty basic -- we have READ_ONLY=1 set on the inactive members of the cluster, and we boot maxwell with a list of each possible master in the cluster, and then do:

```
  def find_master(hosts)
    hosts.select do |h|
      name, port = h.split(':')
      port ||= 3306

      puts "checking master status on #{name}:#{port}"
      `mysql --host=#{name} --port=#{port} --user=#{user} --password='#{pass}' -NBe 'select @@read_only'`.chomp == "0"
    end.first
  end
```

When we promote a new master, we will set READ_ONLY=1 on the old master, which will crash the existing maxwell process.  The restarted process will then attach itself to the new master.

> My DBA said, binglogs are configured to rotate even 15 min, but it looks too small for me.  What is the best practices for binlogs archive/purge (frequency, expire_logs_days ? relay_log_space_limit? etc) when implementing CDC with maxwell?

since Maxwell doesn't buffer relay-logs in the same way a standard mysql slave does, you want to leave enough wiggle room to do various upgrades & handle a bit of unplanned downtime; what if your kafka cluster goes down or needs to be upgraded?  We plan for zero downtime in these things of course but should leave some buffer.  I'd say 24 hours of binlogs at least...

> Would be nice if you support multiple maxwell instances leach to same MySQL node for High Availability.

I'd probably accept a coordination patch based around https://twitter.github.io/commons/apidocs/com/twitter/common/zookeeper/DistributedLockImpl.html or similar, but probably don't have time to do much around it this month.  Feel free to open an issue.

**Comment by xmlking** [comment]
just want to share this **_autopilot pattern_** for MySQL which can be used to detect master role change and reconnect Maxwell to new master MySQL: 
https://www.joyent.com/blog/dbaas-simplicity-no-lock-in

**Comment by osheroff** [comment]
four years later, shipped some native HA.  how's that for expediency?
