### ISSUE TITLE
bootstrapping and transaction oddness

### ISSUE THREAD

**Issue by osheroff** [zendesk/maxwell#250]
@nmaquet 

Did a 1mm row bootstrap today in our staging environment.  Everything went pretty well, though the progress estimates were maybe a bit fictional.  Only averaged 2k rows per second, but it's just a cheap AWS staging environment.

I did however have a bit of an 'aha' while looking at the final output.  I noticed that the final rows came without a transaction id.   One of our consumers at Zendesk uses multiple rows in a transaction, correlating changes from two different tables.  If updates came in while bootstrapping, the changes would be lost to them.  I figure that in order to accommodate that consumer, I have a couple of options:

1.  run in synchronous bootstrap mode.  probably the easiest.
2.  There's a possible way to avoid this, although it may be too cumbersome to bother with:

- maintain a "bootstrap-buffer" list of tables. 
- initialize the list to the table that's being bootstrapped
- any transaction that touches a table that's being bootstrapped will get buffered in its entirety.  The tables involved in that transaction also get added to the "bootstrap-buffer" list.

now we have a situation where all tables that are involved in transactions whilst bootstrapping is happening have correct timelines with relation to each other.  But again, I somewhat doubt it's worth the effort.  hm.

cc @seancaffery @zendesk/rules

**Comment by nmaquet** [comment]
@osheroff 
Are you sure that the replayed RowMap instances (i.e. those written by `replaySkippedRows`) are missing a transaction id? In my understanding, thy should be perfectly serialized copies of the original RowMap instances coming from the Replicator (and thus have the same `xid` field as the original). The bootstrapped inserts however, do not have an `xid` field.

**Comment by osheroff** [comment]
I will check.  either way I think it'll fuck with our consumer, as they expect transactions to come in a fairly linear fashion, I think.  I'll probably just use the synchronous boostrapper, as we can tolerate a little lag and we only have to do it once...

the other thing I was thinking about:  my main application of maxwell will be doing delta-style counts.  for this reason, it'd be nice if it could disambiguate a bootstrapped row from a normally inserted row.  What do you think about changing the `type` to "bootstrap"?

**Comment by osheroff** [comment]
Out of curiousity: what's the application that you're using maxwell for?

**Comment by osheroff** [comment]
Aside: @nmaquet @kristiankaufmann @vanchi-zendesk @wushujames would you guys bother with a maxwell mailing list if I set one up?  Or is Github issues fine?

**Comment by wushujames** [comment]
I would be fine with either way. If you create a mailing list, I would join.

Are you okay with using Github issues for non-specific discussion, such as your "out of curiousity, what are people using Maxwell for"? I admit, I do have some general questions like that, that I've been meaning to ask, but haven't yet. And I wasn't sure if I should just post them as Github issues, or if you preferred that discussion to happen in another place (email, mailing list, etc).

**Comment by nmaquet** [comment]
Mailing list sounds good. Github issues is fine also.

We're currently using Maxwell for real-time tracking and analytics in our cinema loyalty products (still a work in progress, first production delivery is expected in a few weeks). We'll track real-time email opens, link clicks, trailer views, ticket purchases, etc. for roughly 30 million loyalty members worldwide. See movio.co for more info about our company.

**Comment by wushujames** [comment]
@nmaquet I would have thought that that type of "activity tracking" info would go straight into Kafka, as opposed to into MySQL and then to Kafka. Is there a reason you need/want MySQL to be there?

**Comment by nmaquet** [comment]
@wushujames Our system is 4 years old with bits in crons, shell scripts, PHP, Java and Scala, with a giant MySQL DB in the middle. It would be really really hard to change all that code to also write messages into Kafka. Maxwell saves us hundreds of engineering hours by allowing us to build a real-time processing engine right now, and to progressively add Kafka producers throughout our application as time permits.

**Comment by wushujames** [comment]
@nmaquet Yup, that's what I was guessing. Makes perfect sense, and the reason why I like Maxwell (and CDC in general) so much. It lets you isolate your application from Kafka, as well as move to it over time.

**Comment by osheroff** [comment]
@wushujames yeah I dunno I feel sorta mixed.  On the one hand an email list is disconnected from the code base, hard to link to, etc... on the other hand if you do it all in github issues you end up with these long-lingering issues that never really "close" and they're intermingled with actualy bugs, etc, etc.

I guess let's stick with github issues for and I'll get better at tagging stuff.

**Comment by osheroff** [comment]
@nmaquet btw:

> the other thing I was thinking about: my main application of maxwell will be doing delta-style counts. for this reason, it'd be nice if it could disambiguate a bootstrapped row from a normally inserted row. What do you think about changing the type to "bootstrap"?

**Comment by nmaquet** [comment]
@osheroff Agreed that it would be useful to distinguish normal inserts from bootstrap inserts. Can we use `"bootstrap-insert"` instead of just `"bootstrap"` ?

**Comment by osheroff** [comment]
`bootstrap-insert` is fine.

**Comment by kristiankaufmann** [comment]
@osheroff regarding the mailing list. I echo both nmaquet and wushujames. I'd join and read the mailings if available, but I am fine using github issues as well

**Comment by osheroff** [comment]
I've changed the type to `bootstrap-insert`, and am going to do precisely none of the other stuff I talked about.  At least not now.
