### ISSUE TITLE
filtering out tables from SchemaStore updates

### ISSUE THREAD

**Issue by nmaquet** [zendesk/maxwell#252]
@osheroff One of our applications is spamming the binlog by creating and dropping tables hundreds of times per minute (we should be using temporary tables but for some arcane reason this piece of legacy code does not). Unfortunately, this translates into millions of writes into the `maxwell.columns` table; and because of this Maxwell just can't keep up and is falling behind.

We're thinking of adding functionality to Maxwell to allow for completely ignoring tables, including schema updates. Would this be of general interest? Otherwise we'd need to maintain our own patch.

**Comment by osheroff** [comment]
yeah, I think I've heard interest in this type of behavior from other parties with similar setups.  The implications of totally blacklisting a table like this is that if you ever remove it from the blacklist, maxwell will start crashing.. so it should probably be done as a separate thing from normal table/database exclusion.

Something like:
```
  --exclude_tables             exclude these tables, formatted as exclude_tables=tb1,tb2
  --blacklist_tables             ignore data AND schema changes to these tables.  see the docs for details before setting this!
```

BTW, today I've been working on a changes to how maxwell stores schema (we'll keep an initial snapshot, and then store DDL stuffs as JSON as overlays on top of that, maybe checkpointing once in awhile).  Given the level of chattiness in your setup, sounds like this patch would still be worthwhile...

**Comment by nmaquet** [comment]
Brilliant. I'll implement this and submit a PR shortly.

**Comment by jpeyper** [comment]
Just putting my comment on here to say thanks to @nmaquet, this feature will help me out greatly keeping Maxwell performing at its lightning speed despite out own legacy application trying its best to kill it.

**Comment by nmaquet** [comment]
@osheroff @jpeyper Just submitted PR https://github.com/zendesk/maxwell/pull/253
