### ISSUE TITLE
Should we switch the way we "parse" SQL?

### ISSUE THREAD

**Issue by wushujames** [zendesk/maxwell#257]
There has been a lot of work on the schema parser in the past couple months. Some of it is necessary for Maxwell, but a bunch of it has simply been to make sure that Maxwell ignores stuff it doesn't care about.

One idea I floated a while back was to use MySQL itself to "parse" the SQL. The idea was, we would have a small private MySQL installation locally. When Maxwell encounters a DDL statement, it would "apply" it to private MySQL database. MySQL would then parse and apply the DDL and when it is done, Maxwell would simply look at the (newly changed) database schema and extract out the schema.

This would mean Maxwell wouldn't have to handle so much of the esoteric parsing.

I'm sure there are a bunch of pros/cons to this. And I know it wouldn't be "free", since Maxwell would still have to have some minimal set of parsing in order to even pull this off. But just floating the idea for discussion.

**Comment by osheroff** [comment]
I've noodled on this one for the last few days, here's the tradeoffs I think of:

Side-chain approach: 
- + won't crash on parse errors
- + simplifies certain operations, lets mysql figure out character sets and default values and stuff
- - likely more fragile -- have to keep a server up and running on the side, plus its data someplace.
- - slower; discovering all of INFORMATION_SCHEMA on big databases is a fairly expensive operation
- - no ability to ever output DDL-as-json
- - loses ability to go where I'm starting to go in https://github.com/zendesk/maxwell/compare/compact_schema?expand=1, which is storing one copy of the schema at checkpoints and then storing deltas: I'm working towards fixing the fact that on large schemas a single DDL statement can generate hundreds of thousands of events
- - would probably have to somehow auto-download a binary distribution of mysql (or require it to be installed alongside maxwell) that matched the distribution it was running.

Looking at that list, I'm inclined to decline, although the idea still intrigues me a bit.
