### ISSUE TITLE
blacklisted table question

### ISSUE THREAD

**Issue by jpeyper** [zendesk/maxwell#260]
For a lack of somewhere better to ask this...

Does this setting allow be to blacklist entire schemas or just tables?

For example, can I do
`--blacklist_tables=/__temp.*/`
to blacklist everything in the `__temp` scheme?

edit:

I'm not actually in a position to test this right now so asking the question.

**Comment by osheroff** [comment]
@jpeyper, no, it just deals with table names.  will have to add a corresponding option to filter out whole databases.  

cc @nmaquet

**Comment by osheroff** [comment]
fixed in https://github.com/zendesk/maxwell/pull/289
