### ISSUE TITLE
Grouping change records based on transaction ID 

### ISSUE THREAD

**Issue by xmlking** [zendesk/maxwell#267]
E.g.: If   CUSTOMER table and CUSTOMER_ADDRESS table are updated in MySQL in one transaction, will there be an identifier in Logical Change Records (JSON) indicating they belongs to same transaction?
My goal is to implement Real-time ETL to sync normalized transitional database (MySQL) to de- normalized analytical database (MongoDB)

**Comment by osheroff** [comment]
yes, you can use the `xid` and `commit` fields to batch transaction rows together.
