### ISSUE TITLE
Should I exclude Maxwell database form replicating? 

### ISSUE THREAD

**Issue by xmlking** [zendesk/maxwell#268]
Should I exclude explicitly Maxwell database using `exclude_dbs` to prevent emitting changes to  Maxwell database itself ?
I think I noticed changed to `maxwell.bootstrap` are emitted on Kafka topic

**Comment by osheroff** [comment]
No, doing this will break bootstrapping.  The bootstrapping features hooks into the replication stream this way.  You won't see updates to any other table in the maxwell database.
