### ISSUE TITLE
please specify --bootstrapper=none when specifying a replication host !!!

### ISSUE THREAD

**Issue by xmlking** [zendesk/maxwell#271]
When I started Maxwell ( 1.0.0-PRE2 ) with `./bin/maxwell`
I am getting following error:
`please specify --bootstrapper=none when specifying a replication host`

My intention was to start Maxwell to replicate database changes in real-time as well as bootstrap certain  tables  listed in `maxwell.bootstrap` table. 

Please advise why I cannot use `replication_host` and `bootstrapper=async` together 

**config.properties**

```
# log level
log_level=INFO
user=maxwell
password=mypass
host=localhost
port=3306

producer=kafka

kafka.acks=1
kafka.bootstrap.servers=kafka_host1:9092,kafka_host2:9092,kafka_host3:9092
kafka_topic=maxwell

# only send updates from these databases
include_dbs=my_replication_db
replication_host=my_replication_host
replication_port=3306
replication_user=maxwell
replication_password=mypass

# bootstrap
bootstrapper=async
#bootstrapper_fetch_size=64000
```

**Comment by osheroff** [comment]
hi @xmlking, it's because the bootstrap mechanism relies on the maxwell schema database residing on the same host as the one it's replicating from -- the bootstrapper thread reads the mutations to the `maxwell.bootstrap` table and acts upon them as they enter the replication stream. 

It's also simply the recommended configuration to have Maxwell store its schema information inside the server it's replicating from.

**Comment by xmlking** [comment]
@osheroff sound good.  in my case I have `maxwell` and `my_replication_db` databases on the same MySQL host. 
with the `config.properties` below, please conform I can get this: 

1. any tables added to the  `maxwell.bootstrap` table will be bootstrapped. 
2. data updates to any tables in `my_replication_db` will be emitted into Kafka topic

```
# log level
log_level=INFO
user=maxwell
password=mypass
host=localhost
port=3306

producer=kafka
kafka.acks=1
kafka.bootstrap.servers=kafka_host1:9092,kafka_host2:9092,kafka_host3:9092
kafka_topic=maxwell

# only send updates from these databases
include_dbs=my_replication_db

# bootstrap
bootstrapper=async
bootstrapper_fetch_size=64000
```

**Comment by osheroff** [comment]
That config looks fine.
