### ISSUE TITLE
producer to  kafka

### ISSUE THREAD

**Issue by fanlifei** [zendesk/maxwell#284]
BinlogRowEventFilterImpl - failed to find TableMapEvent, header: BinlogEventV4HeaderImpl[timestamp=1456137022000,eventType=30,serverId=110,eventLength=732,nextPosition=801269751,flags=0,timestampOfReceipt=1456137726607]

**Comment by osheroff** [comment]
can you give any more context?  Generally this error means that Maxwell started up in a bad replication position.  Did you hit this error on startup, or mid stream?

**Comment by fanlifei** [comment]
[maxwell.cnf]
log_level=INFO
user=maxwell
password=maxwell
host=127.0.0.1
port=3306
schema_database=maxwell_yc_core

# only send updates from these databases
include_dbs=yc_core
include_tables=service_order,service_order_charge,service_order_ext


#producer=stdout
producer=kafka
kafka.acks=1
kafka.bootstrap.servers=172.17.0.124:9092,172.17.0.125:9092,172.17.0.126:9092
kafka_topic=sys.dw.db.yc_core
kafka_partition_by=table




# bootstrap
bootstrapper=async
bootstrapper_fetch_size=64000


[fanl@db3 maxwell]$ bin/maxwell --config=/etc/maxwell.cnf  
09:27:26,801 INFO  ProducerConfig - ProducerConfig values: 
        compression.type = gzip
        metric.reporters = []
        metadata.max.age.ms = 300000
        metadata.fetch.timeout.ms = 5000
        acks = 1
        batch.size = 16384
        reconnect.backoff.ms = 10
        bootstrap.servers = [172.17.0.124:9092, 172.17.0.125:9092, 172.17.0.126:9092]
        receive.buffer.bytes = 32768
        retry.backoff.ms = 100
        buffer.memory = 33554432
        timeout.ms = 30000
        key.serializer = class org.apache.kafka.common.serialization.StringSerializer
        retries = 0
        max.request.size = 1048576
        block.on.buffer.full = true
        value.serializer = class org.apache.kafka.common.serialization.StringSerializer
        metrics.sample.window.ms = 30000
        send.buffer.bytes = 131072
        max.in.flight.requests.per.connection = 5
        metrics.num.samples = 2
        linger.ms = 0
        client.id = 

09:27:26,829 WARN  ProducerConfig - The configuration value.serializer = class org.apache.kafka.common.serialization.StringSerializer was supplied but isn't a known config.
09:27:26,829 WARN  ProducerConfig - The configuration key.serializer = class org.apache.kafka.common.serialization.StringSerializer was supplied but isn't a known config.
09:27:27,082 INFO  Maxwell - Maxwell is booting (MaxwellKafkaProducer), starting at BinlogPosition[mysql-bin.004330:1000383277]
09:27:27,084 INFO  SchemaStore - Restoring schema id 1 (last modified at BinlogPosition[mysql-bin.004318:181513012])
09:27:27,330 INFO  ProducerConfig - ProducerConfig values: 
        compression.type = gzip
        metric.reporters = []
        metadata.max.age.ms = 300000
        metadata.fetch.timeout.ms = 5000
        acks = 1
        batch.size = 16384
        reconnect.backoff.ms = 10
        bootstrap.servers = [172.17.0.124:9092, 172.17.0.125:9092, 172.17.0.126:9092]
        receive.buffer.bytes = 32768
        retry.backoff.ms = 100
        buffer.memory = 33554432
        timeout.ms = 30000
        key.serializer = class org.apache.kafka.common.serialization.StringSerializer
        retries = 0
        max.request.size = 1048576
        block.on.buffer.full = true
        value.serializer = class org.apache.kafka.common.serialization.StringSerializer
        metrics.sample.window.ms = 30000
        send.buffer.bytes = 131072
        max.in.flight.requests.per.connection = 5
        metrics.num.samples = 2
        linger.ms = 0
        client.id = 

09:27:27,334 WARN  ProducerConfig - The configuration value.serializer = class org.apache.kafka.common.serialization.StringSerializer was supplied but isn't a known config.
09:27:27,334 WARN  ProducerConfig - The configuration key.serializer = class org.apache.kafka.common.serialization.StringSerializer was supplied but isn't a known config.
09:27:27,554 INFO  TransportImpl - connecting to host: 127.0.0.1, port: 3306
09:27:27,598 INFO  TransportImpl - connected to host: 127.0.0.1, port: 3306, context: AbstractTransport.Context[threadId=12596890,scramble=:b_86HHnswyyu^Vuj6i2,protocolVersion=10,serverHost=127.0.0.1,serverPort=3306,serverStatus=2,serverCollation=33,serverVersion=5.6.25-73.0-log,serverCapabilities=63487]
09:27:27,598 INFO  AuthenticatorImpl - start to login, user: maxwell, host: 127.0.0.1, port: 3306
09:27:27,603 INFO  AuthenticatorImpl - login successfully, user: maxwell, detail: OKPacket[packetMarker=0,affectedRows=0,insertId=0,serverStatus=2,warningCount=0,message=<null>]
09:27:27,621 WARN  BinlogRowEventFilterImpl - failed to find TableMapEvent, header: BinlogEventV4HeaderImpl[timestamp=1456153164000,eventType=30,serverId=110,eventLength=948,nextPosition=1000384225,flags=0,timestampOfReceipt=1456190847620]

**Comment by osheroff** [comment]
trying to think through how this happened... were you previously running maxwell with `--producer=stdout` or `--producer=file` before, by any chance?  If not, is there any chance you could attach a binlog dump of this file?

fwiw, this warning just means that a single row was dropped from the stream.

**Comment by osheroff** [comment]
@fanlifei, I'm going to close this issue as I don't have a good way to repro it, feel free to re-open if you have more information or can give me a repro case.
