### ISSUE TITLE
Multiple updates in the same commit/transaction

### ISSUE THREAD

**Issue by mbittmann** [zendesk/maxwell#285]
Hello - Question for the maxwell community. My use case is to send binlogs to Kafka and then write to HDFS. Once in HDFS, the order of my records is not necessarily preserved by downstream applications. 

Suppose I update the same row in a table two times in a single database commit. The two updated records will have the same timestamp and transaction ID. Since the order fo my records is not necessarily preserved, I won't know which update happened before the other. 

Have you encountered this and, if so, do you have any recommendations on how to handle this? Would you entertain the idea of including BinlogPosition.getFile() and BinlogPosition.getOffset() as part of the JSON record itself, or is this too niche a use case? I'd be happy to dig in and submit a PR if you think that would be a useful feature.

**Comment by wushujames** [comment]
Have you tested what Maxwell sees when you update the same row twice in the same MySQL transaction? I suspect that MySQL would collapse these changes and only write to the binlog the one that actually "won". But I didn't test this, so I'm not sure.

**Comment by mbittmann** [comment]
Thanks for replying! Yep, I did test it. Multiple updates within the same commit do in fact show as separate logs in MySQL:

{"database":"bintest","table":"mytable","type":"update","ts":1456261064,"xid":4508029,"data":{"id":1,"uuid":"15c5fade-da70-11e5-9a59-acbc32a1c083","some_value":1},"old":{"some_value":0}}
{"database":"bintest","table":"mytable","type":"update","ts":1456261064,"xid":4508029,"data":{"id":1,"uuid":"15c5fade-da70-11e5-9a59-acbc32a1c083","some_value":2},"old":{"some_value":1}}

**Comment by osheroff** [comment]
@mbittmann I could see the utility of either:

- the output containing binlog filename / position, or:
- Maxwell collapses multiple rows that share the same primary key in a transaction into one row

and would be good taking patches for either, as long as they're optional features

**Comment by osheroff** [comment]
we now include the binlog position in the output optionally.
