### ISSUE TITLE
Support multiple topics

### ISSUE THREAD

**Issue by criccomini** [zendesk/maxwell#286]
It would be nice to have the ability to configure one topic per table, rather than a single topic. An optional prefix config would also be useful.

**Comment by nmaquet** [comment]
:+1: This would be useful for us as well. Right now we're running a Samza job to demux the Maxwell topic into one topic per table; would be even better to have Maxwell do that directly.

**Comment by rtorrero** [comment]
@nmaquet could you by any chance provide more insight on how you do that with Samza? We are looking for a similar solution.

**Comment by nmaquet** [comment]
@rtorrero Sure. Basically, we're running a simple stateless Samza job that reads each Maxwell message on the Maxwell topic and parses the JSON. Then, depending on the values of "database" and "table" in the message, the job outputs the message to the corresponding topic.

**Comment by nmaquet** [comment]
@rtorrero Here's a simple Scala example of what I mean:

```
import java.util.{Map => JavaMap}
import scala.collection.mutable

import org.apache.samza.system.{SystemStream, IncomingMessageEnvelope, OutgoingMessageEnvelope}
import org.apache.samza.task.MessageCollector
import org.apache.samza.task.StreamTask
import org.apache.samza.task.TaskCoordinator
import org.apache.samza.util.Util


object MaxwellDemuxerTask {
  val OutputStreamPrefix = "maxwell"

}

class MaxwellDemuxerTask extends StreamTask {
  private val systemStreamCache = mutable.Map.empty[String, SystemStream]

  override def process(envelope: IncomingMessageEnvelope, collector: MessageCollector, coordinator: TaskCoordinator): Unit = {
    val map = envelope.getMessage.asInstanceOf[JavaMap[String, Object]]
    for {
      database <- Option(map.get("database").asInstanceOf[String])
      table <- Option(map.get("table").asInstanceOf[String])
    } {
      val outputSystemStream = getSystemStreamFromNames(s"kafka.${MaxwellDemuxerTask.OutputStreamPrefix}-$table-$database")
      val out = new OutgoingMessageEnvelope(outputSystemStream, map)
      collector.send(out)
    }
  }

  def getSystemStreamFromNames(name: String): SystemStream = {
    systemStreamCache.getOrElseUpdate(name, Util.getSystemStreamFromNames(name))
  }
}
```

**Comment by MaheshMadushnaka** [comment]
Added changes related to this and created a full request.  
 #372

When we start maxwell if we pass

- --kafka_topic='database.table' create separate topic for each database table
- --kafka_topic='database' create separate topic for each database
else use default topic

**Comment by osheroff** [comment]
support for this added in 1.4.1
