### ISSUE TITLE
Support Avro and schema registry

### ISSUE THREAD

**Issue by criccomini** [zendesk/maxwell#287]
I know you opted for JSON instead of Avro, but it would be nice to have Avro support as well. Preferably with integration to https://github.com/confluentinc/schema-registry

I believe the JDBC connector in Kafka connect might be of use to see how DB->Avro schema conversion can be done. https://github.com/confluentinc/kafka-connect-jdbc

**Comment by wushujames** [comment]
@criccomini: Work-in-progress, but there's a project to turn Maxwell into a Kafka Connector. https://github.com/wushujames/kafka-mysql-connector
 You would then be able to configure Kafka Connect to encode to your choice of wire format.

**Comment by osheroff** [comment]
yeah, I definitely looked at pulling in schema-registry.  It wasn't an easy set of trade-offs to make, as avro offers some nice features (blobs, dates, compression).   In the end I never felt I could justify making every maxwell consumer do side-lookups on an http channel to make sense of the data; maybe if schema-registry was part of my infrastructure (and part of every stream processor) already I might feel differently.  I dunno.

I'll leave this issue open, and I wouldn't turn down a well-written PR (one that goes out and dynamically creates avro schemas, and then references them in each row, probably), but this honestly won't make my personal priority list anytime soon.

**Comment by bwilliams42** [comment]
I'm actually working on a solution for exactly this at the moment. My goal is to connect this and some schema registry (I'm using confluentinc atm) so that each emitted update will have an associated schema id. If this is not being worked on by you guys, we can put out a PR when its done. Thoughts?

**Comment by osheroff** [comment]
cool!  do it!

The only other thought I had was to jam a confluent-compatible registry inside maxwell itself, or as a separate server in the same repo (yay for self-contained stuff), but that'd be quite the scope-blowing.

**Comment by cccc1999** [comment]
@bwilliams42 That's awesome, we are trying to the exactly same thing(integrating confluent schema registry and putting schema id into every message), do you mind sharing your progress? Maybe we can collaborate on this.

**Comment by bwilliams42** [comment]
@cccc1999 I was about to do the work myself when i was pointed to a comment by @kristiankaufmann  further up in this thread. @wushujames has done some work here. @kristiankaufmann  forked his work and made a few changes to it, and we were able to get it doing what we want it to do. update confluents schema server when ever someone updates a table and emit records to a kafka topic. Amazing stuff! There is still some testing to be done here. Tests need to be written and we need to put all the pieces under real pressure. But so far so good. Check out @wushujames  https://github.com/wushujames/kafka-mysql-connector and if you have questions, feel free to reach out. Or if you're not in a hurry, you can hang on a few days as we will make what we did available in the days to come.

**Comment by wushujames** [comment]
@bwilliams42 Super excited to see what you've done with the kafka-mysql-connector!

**Comment by cccc1999** [comment]
@bwilliams42 great, thanks buddy! Has @kristiankaufmann made his work available yet?

**Comment by osheroff** [comment]
@kristiankaufmann I'd like to see maxwell packaged as a jar with a reasonably sane public API, so that it can be consumed as either a library (as in james' connector) or as a standalone.

**Comment by wushujames** [comment]
Agree with @osheroff said, but let me take it one further. I think maxwell can be packaged as a library jar. The current implementation of Maxwell should then use that library to implement the existing functionality. And new projects can be written, like my connector, that will use the library.

That means that a lot of the current functionality would need to be supported by the library, including the mysql schema storage/reads/writes. That might be difficult to accomplish cleanly.

It's up to Ben if https://github.com/wushujames/kafka-mysql-connector eventually gets pulled back into the main Maxwell project. I don't think he is signing up for that, though.

**Comment by kristiankaufmann** [comment]
@cccc1999 @wushujames 
I've made my kafka-mysql-connector [branch](https://github.com/kristiankaufmann/kafka-mysql-connector/tree/maxwell-1.0.0) available. As @wushujames mentioned it is still a work in progress, but we been able to use confluent's supplied avro-converter to registry the schemas in the schema-registry and produce avro encoded message to the topics. This is done by setting the convertor properties in the copycat properties file copycat-standalone.properties
```
value.converter=io.confluent.connect.avro.AvroConverter
value.converter.schema.registry.url=http://localhost:8081
```
Make sure to include the avro-convertor jar on the classpath when starting the connector

Most of the changes have been to enable using some of the newer maxwell features.

**Comment by osheroff** [comment]
interesting stuff guys.  LMK when/if you have an idea of what you'd like a "library" style interface to look like, and I can start thinking about how the `.poll` interface that the connectors might fit together with the standard `main` maxwell loop.

**Comment by osheroff** [comment]
folks on this issue:

@smferguson is working towards avro support here, I'm curious about your avro use cases.  

https://github.com/zendesk/maxwell/pull/473#issuecomment-262554640

Would it fit your use case if you specified avro schemas up front and had maxwell munge the data to fit that shape?  Or would it be better if maxwell dynamically generated its avro schemas on the fly?
