### ISSUE TITLE
RDS setup help

### ISSUE THREAD

**Issue by ethangunderson** [zendesk/maxwell#298]
We're trying to setup Maxwell to read from our RDS MySQL databases. Unfortuantely, we can't get past the variable state checks for `log_bin`, as there isn't a direct corollary in an AWS Parameter Group. Can anyone point me to documentation, or how you got around this on RDS?

**Comment by osheroff** [comment]
from http://docs.aws.amazon.com/AmazonRDS/latest/UserGuide/USER_LogAccess.Concepts.MySQL.html, 

> To set the MySQL binary logging format:
> Sign in to the AWS Management Console and open the Amazon RDS console at 
> https://console.aws.amazon.com/rds/.
> Click Parameter Groups in the left pane.
> For the default.mysql5.6 or default.mysql5.7 DB parameter group, click the Go to Details Page icon.
> Click the Edit Parameters button to modify the parameters in the DB parameter group.
> Set the binlog_format parameter to the binary logging format of your choice (MIXED or ROW).
> Click the Save Changes button to save the updates to the DB parameter group.

I haven't tried it tho.  We've been running Maxwell on Aurora and that's been working good so far.

**Comment by osheroff** [comment]
work for you ethan?

**Comment by chris-chambers** [comment]
We had similar confusion with AWS.  The problem in our case was that the database in question had a 0-day backup retention policy.  Changing to a 1-day retention policy set log_bin=1.  Found here:

Select Instance
Instance Actions > Modify
Backup section

We had already set ROW binary logging as @osheroff outlined above.

**Comment by ethangunderson** [comment]
Sorry, I've been meaning to reply to this thread and keep forgetting.

@chris-chambers is correct. When you enable backups in RDS, the log_bin option is enabled. It's not obvious in RDS documentation that this will happen, but I confirmed with AWS support that this is the only way to enable the option.

Thanks for the help everyone.

**Comment by osheroff** [comment]
anyone here wanna help out and turn this into a note somewhere in the documentation?

**Comment by ethangunderson** [comment]
No problem, I can try to get something put together this weekend.

I should also note that the main reason we ran into this issue was that we're doing cascading replication (primary -> replica -> maxwell), and we don't normally have backups turned on for replicas.

**Comment by Overbryd** [comment]
I came here via Google search, and I wanted to point out that it is important to reboot the (Aurora) RDS-instance after applying the new parameter group. Otherwise the changes will have no effect.
