### ISSUE TITLE
Can maxwell give update at transaction boundaries as a single atomic update across multiple tables

### ISSUE THREAD

**Issue by r-tock** [zendesk/maxwell#304]

**Comment by osheroff** [comment]
Not currently.  https://github.com/zendesk/maxwell/issues/285 discusses the possibility, although I'd be somewhat concerned that one could easily shoot oneself in the foot by having mega-huge transactions overflow kafka's max-buffer size. 

PRs welcome, certainly.

**Comment by r-tock** [comment]
That's a bummer we have multi-table transactions for common action which give semantic meaning for our updates.

We are debating whether to go with Maxwell or write custom code in our ApiServer on each handler which generates an event record based on an action as opposed to doing it on a database row. 

Have you had such debates and what has been the reason to go with the Maxwell approach?

**Comment by osheroff** [comment]
Maxwell gives you a couple of nice advantages over generating your own event record:

- you get transaction-like semantics; there's no chance of a kafka event appearing while the transaction failed, or vice versa.  To put it another way: Maxwell gives you at-least-once semantics.

- you don't have to make sure that every place in code where you touch the database also is instrumented to emit events.

The downsides of maxwell:

- you often have to do additional processing on the stream to put semantic information back in
- the downstream stream is tied directly to the database schema
- it's another bit of software to run.

**Comment by r-tock** [comment]
@osheroff  follow up question. We are faced with the trouble of recreating the references downstream

For example, if Phone table references Patron table. If a transaction only updates a column in Patron. Then another transaction modifies a number the Phone table. How can we stitch together the value at each of the transaction in both tables. How have you solved it.

**Comment by osheroff** [comment]
@r-tock, I'm sketching out a prototype for a stream-join engine here:

https://github.com/zendesk/maxwell-join

The premise is that you'll put SQL (or sql-like config) in, and get back a denormalized stream.  It's just a prototype, though, I really don't how well it will scale.  

Anyway, ultimately you've really only got 2 choices.

1.  Make sure you touch all the related rows when you update a row.
2.  Use a buffer in a stream processor to store the last known copy of each row.

**Comment by r-tock** [comment]
1. Is expensive.
2. is very expensive. 

I think the premise of maxwell-join makes total sense. Let me know if you would like bounce ideas for it.

**Comment by osheroff** [comment]
they're both expensive, but those are basically your options; option 2 is what maxwell-join does, except it uses the KStreams framework to do so.

**Comment by osheroff** [comment]
rolling up this feature request into #504
