### ISSUE TITLE
Provide maxwell with a topic-consumer utility

### ISSUE THREAD

**Issue by osheroff** [zendesk/maxwell#307]
feature list:

- database stats -> statsd
- bisection by time
- ability to read a particular database's topic (or possible a table's, if maxwell is partitioned that way)
- JSON data filter 

cc @lileeyao

**Comment by lileeyao** [comment]
what kind of database stats? R/W rate?

**Comment by osheroff** [comment]
Inserts, updates, deletes as statsd items with database, table, and maybe server as tags?  See what unboxed_cat does
