### ISSUE TITLE
add --jdbc_options command line flag

### ISSUE THREAD

**Issue by mcleae** [zendesk/maxwell#312]
I'm trying to bootstrap a large table and I keep exceeding my db's wait_timeout setting.  Instead of changing the setting on the server I'd like to tweak it for just the maxwell db connection by including the netTimeoutForStreamingResults property in the jdbc connection string.  Since maxwell constructs the jdbc connection string from the --host and --port properties I was wondering if there was a way to give it additional properties for the jdbc connection string so i end up with something like 
jdbc:mysql://localhost:3306?useCursorFetch=true&zeroDateTimeBehavior=convertToNull&netTimeoutForStreamingResults=XXX

thanks

**Comment by osheroff** [comment]
@lileeyao can you take a look at adding an option that lets you pass through jdbc options?

**Comment by lileeyao** [comment]
k, will do it soon.
