### ISSUE TITLE
MySQL 5.7 Support

### ISSUE THREAD

**Issue by jpeyper** [zendesk/maxwell#313]
I realise that this has been mentioned before (#251 among others).

We are wanting to upgrade our databases to 5.7 in the not to distant future and would like to add weight to the requests to support for this version.

**Comment by osheroff** [comment]
Maxwell 1.7.0 lands (alpha) quality Mysql support.  GTID replication is still unsupported.

**Comment by HenryCaiHaiying** [comment]
@osheroff any timeline to support GTID?  It seems https://github.com/shyiko/mysql-binlog-connector-java have support for GTID, can maxwell use that binlog-connector?

**Comment by osheroff** [comment]
yes, gtid support among others was a large part of the motivation for the port to binlog-connector which happened over the last month or so (1.7.0 integrates shyko's library).  My problem though is that I don't have production installation of GTID to play with.  I can kinda do a best-guess pass at the support developing locally, but the things I need to figure out are:

- how to upgrade from a regular replicator position to a GTID position
- what mysql's behavior with "auto-positioning" is.

And then there's just some refactoring and lifting to ensure that maxwell stores and processes GTID-based positions properly.  Something that can kick this process along is someone stepping up with a first pass (hint, hint).

**Comment by HenryCaiHaiying** [comment]
I didn't know you already integrated with shyiko's binlog connector.  We are definitely interested in adding GTID support, maybe we can take a look to see how we can contribute to this project.

**Comment by HenryCaiHaiying** [comment]
@osheroff by looking at Shyiko's BinaryLogClient.java, looks like most of the code related to GTID is there.  He kept the past gtids in memory, maxwell just need to persist that information into a table.  In the normal mysql slave hosts, they are using gtid_executed table keep track that history, we can do the same thing to create a similar table in maxwell schema (similar to how you persist binlog file/position).  One extra work is we need to compact the gtid_executed table otherwise there will be too many rows in that table (this was done automatically by mysql replication daemons for mysql slave hosts).

**Comment by osheroff** [comment]
in my understanding GTIDs were monotonic.  I think we could just store a single long string in `maxwell`.`positions`, no?  ie just store it as 

SJDFXFKJSDFJASDF:1-10;FDJKASJDFKJD:1-100

no?

**Comment by HenryCaiHaiying** [comment]
I think it's more than that.  The server's uuid can change too.  Suppose maxwell was initially listening on master A and it got transactions up to A:4.  And A crashed, B was promoted, maxwell will need consume from A:4, A:5, B:1, B:2  (assume maxwell didn't got A:5 previously but B has it).  And it's also possible that A comes back as the master again.

I think we need to at least keep one row for each master host.

**Comment by HenryCaiHaiying** [comment]
Also take a look at the discussion in: https://github.com/shyiko/mysql-binlog-connector-java/issues/144, there might be a way to migrate from non-GTID mode to GTID mode smoothly.

**Comment by osheroff** [comment]
> I think we need to at least keep one row for each master host.

I don't necessarily see the *need*.  It's certainly one way to store the data, but I'd probably still prefer stashing positions as single strings, ie `'A:4-5,B:1-23`.  It would mean we could just add a `gtid_set` column to `maxwell.positions` rather than adding a whole new table

**Comment by HenryCaiHaiying** [comment]
I feel a separate table is cleaner.  The structure of binlog position is a
bit different than gtid set.  It might be easier when you need to migrate
from non-gtid mode to gtid mode.

**Comment by osheroff** [comment]
ok.  code it and see.  keep in mind that maxwell has the notion of a `client_id` that identifies a separate version of maxwell; so the gtid table should be unique by (client_id, server_uuid)

**Comment by HenryCaiHaiying** [comment]
Looks like adding a new table is a lot of work, I decide to just add a column in positions table for gtid_set, your original idea.  

PR should be coming soon, but I need to submit a small patch into shyiko's repo first.
