### ISSUE TITLE
Health Check in Marathon

### ISSUE THREAD

**Issue by nnordrum** [zendesk/maxwell#315]
What would be the preferred method of doing a health check in Marathon?

Would you be open to exposing an HTTP port that just returned "OK" (HTTP_200) if the process is up?

**Comment by osheroff** [comment]
really, the best way is testing side-effects: something that checks to see if the row in `maxwell.positions` is moving (assuming you have something like a maatkit's heartbeat runnning).  Or checking that the kafka offset is incrementing.  I suppose you could expose some kind of more wholistic health check via HTTP as well that takes into account whether the replication is running and such. 

The thing is, just having a port open with a web server on it that says "OK" isn't really much better than checking if the PID is alive.  Maybe it tells you that the PID is alive and the JVM isn't frozen or OOM, but it's... I dunno.  It's not much.

**Comment by nnordrum** [comment]
it's remotely testable too.

**Comment by osheroff** [comment]
yeah, that's a good point.  In theory JMX is *supposed* to solve these problems, but I'll be fucked if I can make heads or tails of how to implement that. 

Ok, I'd be ok with an http api as long as it did a bit more than "OK" -- ie it should expose '/status' which dumps some useful json about current position, rows-per-second, that kinda stuff.

**Comment by nnordrum** [comment]
where would be "the best" place to put this? my initial spike has it in MaxwellReplicator, so I can see RunLoopProcess.runState (I also made a protected .getRunState), but I'm guessing now that we'll probably want metrics from the other RunLoopProcess subclasses, so I'll move it out.

Add MaxwellReplicator to MaxwellContext and put it in there? Only suggesting here since it seems to have almost everything we'd be reporting status on.

Create something new and register the various components with that thing?

**Comment by osheroff** [comment]
rough sketch in my mind:  `MaxwellContext` has a shared object `MaxwellState` that contains stats/positions/etc.  `MaxwellReplicator` writes to the shared object and then a separate thread containing the webserver reads it.

**Comment by nnordrum** [comment]
#319 mostly just concerned about locations and general patterns. Will clean up and make correct as we go along.

**Comment by xmlking** [comment]
@osheroff any near-time plans to implement metrics/stats API for Maxwell? if you have any ideas I can contribute implementation. would u prefer JMX or some REST API  to expose stats?

**Comment by osheroff** [comment]
@xmlking no plans.  http://metrics.dropwizard.io/3.1.0/ seems like the way to go with this stuff, yeah?

**Comment by osheroff** [comment]
we have an http endpoint now with metrics, health check, etc.
