### ISSUE TITLE
some primary keys are coming as null  due to case sensitive comparison 

### ISSUE THREAD

**Issue by xmlking** [zendesk/maxwell#317]
while testing with `Percona MySQL` , we noticed second primarykey is coming as `null `.
wonder if anyone else facing this issue? 

```sql
UPDATE test.person SET
  id = 5,
  firstName = 'aaa',
  address_id = 3
WHERE id = 1 AND firstName = 'qqqq';
```

kafka key:
```json
'{"database":"test","table":"person","pk.id":5,"pk.firstName":null}'
```

kafka value: 
```json
{
    "database": "test",
    "table": "person",
    "type": "update",
    "ts": 1458335796,
    "xid": 4168944,
    "commit": true,
    "data": {
        "firstname": "aaa",
        "address_id": 3,
        "id": 5,
        "lastname": "aaa"
    },
    "old": {
        "firstname": "qqqq",
        "address_id": 4,
        "id": 1
    }
}
```

**Comment by osheroff** [comment]
looks like a case-sensitivity issue.  If you write a test, I can probably whack out a fix.  Or you can try :)

**Comment by xmlking** [comment]
tested locally switching  ` LinkedHashMap  with `TreeMap<String, Object>(String.CASE_INSENSITIVE_ORDER);` in RowMap.java. this resolved the problem.

**Comment by osheroff** [comment]
keep `LinkedHashMap`, but downcase the column names on insert and lookup?  `LinkedHashMap` is in there preserving the order that the columns serialize in json, which is a nice readability win

**Comment by xmlking** [comment]
agree. I will test  `data.containsKey(pk.toLowerCase())`

**Comment by xmlking** [comment]
Changing to `data.containsKey(pk.toLowerCase()) ` at three locations works for me.
Will you cosider releasing this fix?

**Comment by osheroff** [comment]
sure thing.  just PR it
