### ISSUE TITLE
Configurable replicator params

### ISSUE THREAD

**Issue by Komnomnomnom** [zendesk/maxwell#320]
We were encountering issues when using maxwell to talk to a sluggish MySQL server (remote host and overburdened server). Maxwell replication was regularly timing out and restarting.

We needed to increase [heartbeat period](https://github.com/zendesk/maxwell/blob/master/src/main/java/com/zendesk/maxwell/MaxwellReplicator.java#L62) and [heartbeat timeout ](https://github.com/zendesk/maxwell/blob/master/src/main/java/com/zendesk/maxwell/MaxwellReplicator.java#L87) to solve the problems. 

Would it be possible to expose these and other hardcoded values to be configurable via maxwell's config file or startup params?

**Comment by osheroff** [comment]
sure, patches welcome, if not someone over on this side will get to it at some point.
