### ISSUE TITLE
Add Github link to maxwells-daemon.io

### ISSUE THREAD

**Issue by danielytics** [zendesk/maxwell#321]
It would be nice if there was a link to this GH repo from the http://maxwells-daemon.io/ site.

Looking at the template, `nav.html`, only the `repo_url` variable needs to be set. I'd open a PR, but I'm not familiar with gh-pages, so don't know where this needs to be set.

**Comment by osheroff** [comment]
yeah, good call.  had a dumb stripey banner at some point but it got lost.   Added links to the homepage and download section
