### ISSUE TITLE
'update' detected as 'insert' in ndbcluster

### ISSUE THREAD

**Issue by rtorrero** [zendesk/maxwell#328]
Hi,

We are trying to use Maxwell inside one of our SQL nodes in our ndbcluster setup. It works fine for tables stored in each node using InnoDB, but when we attempt to follow changes in ndbcluster engine-based tables, we see all updates also as insert. Example:

Here I just added a record to table 'ruben_test':
```
info: Receive message
Done processing job, info:  { database: 'games',
  table: 'ruben_test',
  type: 'insert',
  ts: 1461923084,
  commit: true,
  data: { id: 4, ruben_testcol: 'hola' },
  queueId: 'maxwell' }
```

Here I update the column 'ruben_testcol' to 'changed':
```
info: Receive message
Done processing job, info:  { database: 'games',
  table: 'ruben_test',
  type: 'insert',
  ts: 1461923092,
  commit: true,
  data: { id: 4, ruben_testcol: 'changed' },
  queueId: 'maxwell' }
```

I'm assuming this is due to how MySQL internally handles ndbcluster-based tables. Is there any way to really detect a update instead of a delete?

Thanks.

**Comment by osheroff** [comment]
Sorry for the delay here.  I know almost zero about ndb but this may be of interest:

http://dev.mysql.com/doc/refman/5.7/en/mysql-cluster-replication-conflict-resolution.html#option_mysqld_ndb-log-update-as-write

**Comment by rtorrero** [comment]
@osheroff nice catch there! after setting ndb-log-update-as-write to 0, maxwell correctly reports updates as updates, and not as inserts.

Thanks.
