### ISSUE TITLE
BitColumnDef should handle java types byte[] and Boolean

### ISSUE THREAD

**Issue by mcleae** [zendesk/maxwell#339]
According to the jdbc connector docs [here](https://dev.mysql.com/doc/connector-j/5.1/en/connector-j-reference-type-conversions.html) mysql bit columns can be treated as java type byte[] or Boolean.  When the type is Boolean the asJSON method in BitColumnDef.java throws a class cast exception.

I have a patch in my local fork where I conditionally map the boolean to 0 or 1 prior to the cast, I can push as a pr if you agree with the approach.

**Comment by osheroff** [comment]
I agree, plz make sure you include a test is all

**Comment by mcleae** [comment]
done, here you go
https://github.com/zendesk/maxwell/pull/340

**Comment by osheroff** [comment]
will be released in 1.1, already in the -pre release.
