### ISSUE TITLE
Unhandled QueryEvent inside transaction

### ISSUE THREAD

**Issue by MartinAmps** [zendesk/maxwell#345]
Since rotating the primary node, I'm seeing lots of these errors, and it rows are being dropped. Has this been observed before? Our data hasn't changed nor have the inserts, but it has upset maxwell somewhere.

Attached is the error:

`Unhandled QueryEvent inside transaction: QueryEvent[header=BinlogEventV4HeaderImpl[timestamp=1463436951000,eventType=2,serverId=2886863499,eventLength=1341,nextPosition=45151048,flags=0,timestampOfReceipt=1463436951927],threadId=6109764,elapsedTime=0,databaseNameLength=10,errorCode=0,statusVariablesLength=34,statusVariables=[QFlags2Code[flags=0], QSQLModeCode[sqlMode=2097152], QCatalogNzCode[catalogName=std], QCharsetCode[characterSetClient=33,collationConnection=33,collationServer=8], QTimeZoneCode[timeZone=SYSTEM]]`

Any input greatly appreciated

**Comment by MartinAmps** [comment]
Ah I just found https://github.com/zendesk/maxwell/issues/208 -- seems that even after ` SET GLOBAL binlog_format='ROW'; FLUSH LOGS` clients with a persistent connection are in MIXED mode.. Bummer. Is there a way for maxwell to recover those rows or will it need to be done separately?

**Comment by osheroff** [comment]
@MartinAmps if you have another node (esp the old master, perhaps) that was doing binlogs as ROW based, you could in theory have maxwell replay off there.  Otherwise, the data would have to be recovered independently.

**Comment by MartinAmps** [comment]
that's what I feared, thanks @osheroff!
