### ISSUE TITLE
maxwell crash error

### ISSUE THREAD

**Issue by xmlking** [zendesk/maxwell#354]
I am using  `maxwell-1.0.0` noticed my Maxwell  demon crashed with following error.
wonder if somebody can figureout the  root cause of the NPE. 
```
com.zendesk.maxwell.schema.ddl.TableDrop@3c4a6ade
java.lang.NullPointerException
        at com.zendesk.maxwell.MaxwellReplicator.processQueryEvent(MaxwellReplicator.java:337)
        at com.zendesk.maxwell.MaxwellReplicator.getRow(MaxwellReplicator.java:303)
        at com.zendesk.maxwell.MaxwellReplicator.work(MaxwellReplicator.java:112)
        at com.zendesk.maxwell.RunLoopProcess.runLoop(RunLoopProcess.java:31)
        at com.zendesk.maxwell.Maxwell.run(Maxwell.java:100)
        at com.zendesk.maxwell.Maxwell.main(Maxwell.java:106)
02:11:52,826 INFO  SchemaPosition - Storing final position: BinlogPosition[binarylog.037162:287941240]
```

**Comment by osheroff** [comment]
@xmlking any chance you could dump (with `mysqlbinlog -vv`) the binlog around that position?  I'm trying to reason through the stack trace, but it's oddly out of sync with the code.  are you sure you're not on `1.1.0`?  that stack trace seems to align a bit better.. 

Also, does it repro when you restart maxwell?

**Comment by xmlking** [comment]
I might be using a custom maxwell build based on 1.0.0(was trying to print some DDLs to logs) , I noticed the  crash after two weeks (non-prod) , our binlogs are  archived everyday by cron job, so I had to start maxwell with `--init_position`to reset position. 
I will  invistigate tomorrow and update my findings.
Thanks

**Comment by osheroff** [comment]
can post the patch here too; possible that your patch didn't account for the possibility of a null pointer there?

**Comment by osheroff** [comment]
hey @xmlking I'm gonna chalk this up to your patch unless you say otherwise.  Feel free to re-open if you want to post the patch you were using.
