### ISSUE TITLE
Maxwell xid in the json written to kafka

### ISSUE THREAD

**Issue by malingaperera** [zendesk/maxwell#361]
I can see in the json below we get a xid in all jasons written to the kafka.

{"database":"TEST","table":"MAXWELL","type":"insert","ts":1465806121,"xid":2009527,"commit":true,"data":{"id":5,"name":"FIVE"}}
{"database":"TEST","table":"MAXWELL","type":"insert","ts":1465806201,"xid":2009701,"commit":true,"data":{"id":6,"name":"SIX"}}

What I want to know is,

1. Is this xid unique for each event.

2. This this even is resent for some reason, will that events have the same xid?

I tried resending the same event by manually changing the positions.binlog_positions and starting a new maxwell instance in a new server. I got same xids for same events from new maxwell instance.

I just want to know If this work like that always. So that I can you that xid to uniquely identify a database event.

**Comment by osheroff** [comment]
`xid` comes from mysql's binlog, and corresponds to innodb's "transaction_id".  It's unique to a transaction, but only in the context of a running server.  So two consecutive database events are highly unlikely to share an `xid`, but as your server restarts duplicates will be common.

**Comment by malingaperera** [comment]
Thanks osheroff..
I got the answer that I was searching for.

**Comment by osheroff** [comment]
welcome.
