### ISSUE TITLE
Lower casing field names

### ISSUE THREAD

**Issue by daledude** [zendesk/maxwell#362]
Looks like lower casing was forced in #51. Is it possible to have a cli arg to disable this? I have a number of systems that require the case be the same as in the schema. I could remap it in my code but that would mean maintaining a mapping and conversion.

Thanks for consideration.

**Comment by osheroff** [comment]
yeah, I think the ideal behavior is to try to preserve the case that the columns were created with, but always do case-insensitive comparisons on lookup and such.
