### ISSUE TITLE
add event timestamp in kafka messages. 

### ISSUE THREAD

**Issue by xmlking** [zendesk/maxwell#363]
Apache Kafka 0.10.0.0 now supports event time,  received time and processing time concept. 
It would not nice if Maxwell set timestamp into messages so that we can do some interesting windowing operations in `kafka streams`

https://cwiki.apache.org/confluence/display/KAFKA/KIP-32+-+Add+timestamps+to+Kafka+message
http://docs.confluent.io/3.0.0/release-notes.html 
`Timestamps in Mesages. Messages are now tagged with timestamps at the time they are produced, allowing a number of future features including looking up message by time and measuring timing. KAFKA-2511`

**Comment by osheroff** [comment]
yup, quite reasonable request.  I think this would mostly just involve packaging maxwell with a 0.10 producer, which means we'd have to release different versions of maxwell depending on your desired kafka version.

**Comment by smferguson** [comment]
unclear how best to move forward, but i'd love to see maxwell keeping up with kafka.
the upgrade does have some notables (http://kafka.apache.org/documentation.html#upgrade_10):
> Notes to clients with version 0.9.0.0: Due to a bug introduced in 0.9.0.0, clients that depend on ZooKeeper (old Scala high-level Consumer and MirrorMaker if used with the old consumer) will not work with 0.10.0.x brokers. Therefore, 0.9.0.0 clients should be upgraded to 0.9.0.1 before brokers are upgraded to 0.10.0.x. This step is not necessary for 0.8.X or 0.9.0.1 clients.

http://kafka.apache.org/documentation.html#upgrade_10_breaking

http://kafka.apache.org/documentation.html#upgrade_10_performance_impact
> The message format in 0.10.0 includes a new timestamp field and uses relative offsets for compressed messages. The on disk message format can be configured through log.message.format.version in the server.properties file. The default on-disk message format is 0.10.0. If a consumer client is on a version before 0.10.0.0, it only understands message formats before 0.10.0. In this case, the broker is able to convert messages from the 0.10.0 format to an earlier format before sending the response to the consumer on an older version. However, the broker can't use zero-copy transfer in this case. Reports from the Kafka community on the performance impact have shown CPU utilization going from 20% before to 100% after an upgrade, which forced an immediate upgrade of all clients to bring performance back to normal. To avoid such message conversion before consumers are upgraded to 0.10.0.0, one can set log.message.format.version to 0.8.2 or 0.9.0 when upgrading the broker to 0.10.0.0. This way, the broker can still use zero-copy transfer to send the data to the old consumers. Once consumers are upgraded, one can change the message format to 0.10.0 on the broker and enjoy the new message format that includes new timestamp and improved compression. The conversion is supported to ensure compatibility and can be useful to support a few apps that have not updated to newer clients yet, but is impractical to support all consumer traffic on even an overprovisioned cluster. Therefore it is critical to avoid the message conversion as much as possible when brokers have been upgraded but the majority of clients have not.
> 
> For clients that are upgraded to 0.10.0.0, there is no performance impact.

**Comment by osheroff** [comment]
we now have v0.10 producer support.  fixed!

**Comment by kadnan** [comment]
Can anyone provide example how to consume messages wr.t time stamps?
