### ISSUE TITLE
'bin' is not recognized as an internal or external command, operable program or batch file.

### ISSUE THREAD

**Issue by tonykim0328** [zendesk/maxwell#365]
I'm following Quick Start Maxwell manual, and I keep getting the output, 'bin' is not recognized as an internal or external command, operable program or batch file, when I run, "bin/maxwell --user='maxwell' --password='XXXXXX' --host='127.0.0.1' --producer=stdout" in the terminal. I have the folder included in my PATH. I don't know why this keeps popping up. Anybody know how to fix this issue?

**Comment by tonykim0328** [comment]
I went to the folder where bin, build, docs, img, src, and target is located and typed that command, and it still says 'bash' is not recognized as an internal or external command, operable program or batch file...

**Comment by osheroff** [comment]
are you on windows perhaps?

**Comment by tonykim0328** [comment]
Yes, does this need to be on Linux?

**Comment by osheroff** [comment]
There's no reason that maxwell shouldn't run on windows, but there's no script written to start it (no `.bat` file).  If you happen to write a batch file, open a PR.

**Comment by tonykim0328** [comment]
Um, I don't know what you mean by PR...Also, do you recommend doing it on Linux?

**Comment by osheroff** [comment]
"PR" is a "pull request" -- it's how you request source to be changed on github.
