### ISSUE TITLE
Error when running Maxwell.java

### ISSUE THREAD

**Issue by tonykim0328** [zendesk/maxwell#368]
![maxwell](https://cloud.githubusercontent.com/assets/9668580/16238224/492a3f38-37a5-11e6-8c77-ace2725b9b8e.png)

I'm getting this error when I try to run Maxwell.java. I created maxwell user in mySQL through terminal. Am I running the file wrong or am I suppose to create the user somewhere else other than terminal? Any  solution to this?

**Comment by osheroff** [comment]
you need to specify `--user` and `--password` when running `bin/maxwell`

**Comment by tonykim0328** [comment]
That error resulted from running it through eclipse. However, the proper way, as told in the Quick Start manual, is to run it through terminal, right? In the terminal, I went to the maxwell folder. There, assuming my mysql password is XXXXXX, I typed bin/maxwell --user='maxwell' --password='XXXXXX' --host='127.0.0.1' --producer=stdout. However, I keep getting "bin is not recognized as an internal or external command" error...

**Comment by osheroff** [comment]
you can run it from eclipse and give it the same command line parameters.  You won't be able to run it under windows using `bin/maxwell`, unless you install cygwin or another version of "bash" for windows

**Comment by tonykim0328** [comment]
How do you run it form eclipse while giving it the same command line parameters?

**Comment by tonykim0328** [comment]
![maxwelllinux](https://cloud.githubusercontent.com/assets/9668580/16243310/40c836f8-37bc-11e6-96d2-e79cc62c7cb7.png)

I have Virtual Box / Ubuntu installed, so I went through the Quick Start manual from there. However, I'm getting similar error, here in Linux as well...

**Comment by tonykim0328** [comment]
![maxwellaccessdenied](https://cloud.githubusercontent.com/assets/9668580/16247922/cdc49910-37d1-11e6-8747-0df8b1c2ef0d.png)

I ended up figuring out how to run it and give it the same command line parameters. However, I'm getting the errors above. Do you think it's because the maxwell user is not granted permissions correctly?

**Comment by osheroff** [comment]
yes, it's very likely the permissions are incorrect.

**Comment by tonykim0328** [comment]
By accessing MySQL server through command prompt (terminal), I logged in as root user and typed, GRANT ALL PRIVILEGES ON maxwell.* TO 'maxwell'@'%' WITH GRANT OPTION; After doing so, I exited out of the terminal and ran maxwell through eclipse with the same command line parameters, but I'm still getting the same errors. However, I really think this error has to do with maxwell user permission. Is there any other way to grant maxwell user privileges?

**Comment by tonykim0328** [comment]
So, I thought the error from the image above had to do with my Eclipse being not connected to MySQL. Following the tutorials on setting up database connection, I got to the end to test connection. However, I get ping failed. Do you know the solution to that?
![newconnectionprofile](https://cloud.githubusercontent.com/assets/9668580/16279350/40d0e6b2-3880-11e6-9101-eeef3761285d.png)

**Comment by tonykim0328** [comment]
![communications link failure](https://cloud.githubusercontent.com/assets/9668580/16344718/921e9936-3a03-11e6-9fb2-c4263254c9c0.png)

So I was able to connect to mysql databse. However, even though connection was successfully done, I keep getting this error. I kept searching but was not able to find a solution. Do you know any solution to this?

**Comment by osheroff** [comment]
in mysql `localhost` and every other host are treated differently.  So you have to run:

`GRANT ALL PRIVILEGES ON maxwell.* TO 'maxwell'@'localhost'`

**Comment by tonykim0328** [comment]
I was able to run everything successfully in Eclipse by connecting to mySQL with Data Source Explorer and giving commands through SQL Scrapbook last Friday. Thanks for the help!

**Comment by osheroff** [comment]
cool, best of luck.

**Comment by zly010101** [comment]
请问跟mysql的版本有关系嘛 5.7的可以嘛
