### ISSUE TITLE
Not an issue but a question about where Maxwell is reading MySQL binlogs and formatting them to JSON output.

### ISSUE THREAD

**Issue by tonykim0328** [zendesk/maxwell#375]
Hello. Can anyone tell me what specific java file handles reading off of MySQL binlogs and formatting them into JSON output? I wanted to take a closer look at how Maxwell handles those, but I couldn't find the files. Thank you!

**Comment by leeparayno** [comment]
My initial guess would be MaxwellReplicator.java.  Maxwell is acting as a replication user and connecting to the master to request binlog events using OpenReplicator.

**Comment by osheroff** [comment]
Hi tony, 

MaxwellReplicator.java is the main loop.  From there you'll want to look at MaxwellAbstractRowsEvent.java, and finally RowMap.java.
