### ISSUE TITLE
cannot bootstrap from a separate host

### ISSUE THREAD

**Issue by smferguson** [zendesk/maxwell#382]
Apologies if this is the wrong forum. I'm curious why bootstrapping is disabled when using a separate replication host:
https://github.com/zendesk/maxwell/blob/master/src/main/java/com/zendesk/maxwell/MaxwellConfig.java#L307
```java
	if ( this.replicationMysql.host != null && !this.bootstrapperType.equals("none") ) {
			LOGGER.warn("disabling bootstrapping; not available when using a separate replication host.");
			this.bootstrapperType = "none";
		}
```

**Comment by osheroff** [comment]
this is a fine forum, haven't bothered to setup a mailing list.  

The reason you can't separate replication and schema for bootstrapping is that the current implementation uses the replication stream as a control channel for the bootstrapper; you send it requests to start bootstrapping by generating events in its stream.

I think @nmaquet and I had discussed possibly doing something else (API control, or having it watch a table, or something) in a phase 2 of bootstrapping, but not much has come of that.

**Comment by smferguson** [comment]
ahh. thanks!
