### ISSUE TITLE
partitioned tables

### ISSUE THREAD

**Issue by smferguson** [zendesk/maxwell#387]
Maxwell currently blows up when it encounters a partitioned table.
Does it need to know about the schema? I'm wondering if it would be possible/not too complex to add an option to skip ddl processing. It feels like a much more straightforward change than parsing partitioned table ddl.

**Comment by osheroff** [comment]
Yeah, Maxwell needs to know about the schema.  The binlog itself only contains columns in arrays (no lovely column names for you!).  I think ultimately will have to bite the bullet and parse the partition statements; maxwell doesn't care about them, but they have to be parsed even so to get at the DDL that it needs.

**Comment by smferguson** [comment]
ahh. thank you!

**Comment by osheroff** [comment]
You're welcome :)
Going to leave this issue open until the PR merges and I release the fixes, otherwise I tend to forget stuff.

**Comment by smferguson** [comment]
makes sense. sorry for closing!

**Comment by osheroff** [comment]
fixed in v1.1.5
