### ISSUE TITLE
can maxwell continue work if it's master crash in mysql replication env

### ISSUE THREAD

**Issue by rsjssc** [zendesk/maxwell#390]
here is my environment
       mysql5.6, one master and several slaves, we can not read binlog from master for the following reason:
       cause we can not read data from master and we need to fill some other data into the data  maxwell offer, those data store in mysql as well, if we read binlog from Mysql master and read data from mysql slave, we can not sure slaves have the data the same as master because of the asynchronous. so we can not make maxwell as a slave of Mysql master and get data from  Mysql slave.
      And the issue is, if we choose one of the mysql salve as maxwell's master and get it binlog, we can we can not handle the scenario like this: slave which is maxwell's master crash, we want to change another slave as maxwell's master, but we do not know where to start in other slave's binlog. maxwell only have it's master(slave in mysql replication) binlog filename and position as a index. but there is no relationship of slave's binlog index within mysql replication.

![problem](https://cloud.githubusercontent.com/assets/15614106/17016085/e82ad38c-4f5f-11e6-95c3-df03566fcccd.png)

cause we don't have GTID, so hard to locate the same event in C's filename+postion in B's binlog

**Comment by osheroff** [comment]
I will be putting some work into Maxwell's 5.5/5.6 recovery code (especially around being able to detect a newly promoted master and restart at the right position), but even with that I don't think I'll be able to support this configuration; to match up the binlog positions of two independent slaves would require jumping through a *ton* of hoops (probably heartbeating into the master, then sifting through B's positions, stuff like that).

5.7 + GTID support for maxwell is really the only right way to support these types of configurations, that's still down the road though.

For now, your options are:
- accept a small window of data loss after you point maxwell to the new slave (try to automate this to minimize the window). 
- when slave C crashes, you can use "--init_position" when restarting maxwell to point it at the proper position in slave B.  If you're ok with duplicating a bit of data simply pointing maxwell back to the start of the file is a pretty easy way to go. 

I'm gonna close this issue, feel free to re-open it if you need more.
