### ISSUE TITLE
Assertion failure in Open Replicator

### ISSUE THREAD

**Issue by nmaquet** [zendesk/maxwell#394]
Maxwell crashes regularly with the following error:
Version used: 1.1.1

```
java.lang.RuntimeException: assertion failed!  We left -61325 unconsumed bytes in the buffer for event: BinlogEventV4HeaderImpl[timestamp=1469414502000,eventType=24,serverId=1,eventLength=420,nextPosition=527288895,flags=0,timestampOfReceipt=1469419214078]
    at com.google.code.or.net.impl.EventInputStream.finishEvent(EventInputStream.java:73) ~[open-replicator-1.4.2.jar:?]
    at com.google.code.or.binlog.impl.ReplicationBasedBinlogParser.doParse(ReplicationBasedBinlogParser.java:156) ~[open-replicator-1.4.2.jar:?]
    at com.google.code.or.binlog.impl.AbstractBinlogParser$Task.run(AbstractBinlogParser.java:263) [open-replicator-1.4.2.jar:?]
    at java.lang.Thread.run(Thread.java:745) [?:1.8.0_60]
```

Maxwell restarts and proceeds without issue but it's a bit concerning. Could you explain what this error means? I'm keen to try and help fix this but a bit of context and guidance would be really helpful.

**Comment by osheroff** [comment]
this means that open replicator over-read the buffer by 61325 bytes.  The process for reading a binlog event is:

- pull the header 
- the header has an event size.  set this as a guard.
- now pass off control to a parser for the specific row.  In this case, https://github.com/zendesk/open-replicator/blob/master/src/main/java/com/google/code/or/binlog/impl/parser/UpdateRowsEventV2Parser.java
- at the end, we verify that the specific-event parser consumed as many bytes as we were expecting -- this assertion. 

My suspicion is that something is going wrong around https://github.com/zendesk/open-replicator/blob/master/src/main/java/com/google/code/or/binlog/impl/parser/AbstractRowEventParser.java#L71.  some questions:

- when maxwell restarts, what position does it restart at?  Does it re-process the event it crashed on, or does it move ahead? 
- If you run maxwell with `--replay --init_position=FILE:527288475`, does it crash?
- `SHOW BINLOG EVENTS IN 'log_name' FROM 527288475 LIMIT 1` should show you the table it crashed on.  What column types does that table contain?

**Comment by nmaquet** [comment]
> when maxwell restarts, what position does it restart at? Does it re-process the event it crashed on, or does it move ahead?
Typically, it moves ahead directly. Once though, it stayed stuck at the same position for hours, then moved ahead on its own.

> If you run maxwell with --replay --init_position=FILE:527288475, does it crash?
No, it does not.

> SHOW BINLOG EVENTS IN 'log_name' FROM 527288475 LIMIT 1 should show you the table it crashed on. What column types does that table contain?

Unfortunately, the table_id does not correspond to any table listed in `information_schema.INNODB_SYS_TABLES`. Maybe it's a temporary table? Unfortunately on my setup (Mariadb 5.5.5) I don't have INNODB_TEMP_TABLE_INFO.
```
mysql> SHOW BINLOG EVENTS IN 'mysql-bin.000015' FROM 529812391 LIMIT 10;
+------------------+-----------+----------------+-----------+-------------+--------------------------------------+
| Log_name         | Pos       | Event_type     | Server_id | End_log_pos | Info                                 |
+------------------+-----------+----------------+-----------+-------------+--------------------------------------+
| mysql-bin.000015 | 529812391 | Update_rows_v1 |         1 |   529813749 | table_id: 208 flags: STMT_END_F      |
| mysql-bin.000015 | 529813749 | Xid            |         1 |   529813776 | COMMIT /* xid=68760303 */            |
| mysql-bin.000015 | 529813776 | Gtid           |         1 |   529813814 | BEGIN GTID 0-1-11415324              |
| mysql-bin.000015 | 529813814 | Table_map      |         1 |   529813875 | table_id: 177 (mm_mmdb.MovieRelease) |
| mysql-bin.000015 | 529813875 | Write_rows_v1  |         1 |   529813928 | table_id: 177 flags: STMT_END_F      |
| mysql-bin.000015 | 529813928 | Xid            |         1 |   529813955 | COMMIT /* xid=68760699 */            |
| mysql-bin.000015 | 529813955 | Gtid           |         1 |   529813993 | BEGIN GTID 0-1-11415325              |
| mysql-bin.000015 | 529813993 | Table_map      |         1 |   529814054 | table_id: 177 (mm_mmdb.MovieRelease) |
| mysql-bin.000015 | 529814054 | Write_rows_v1  |         1 |   529814107 | table_id: 177 flags: STMT_END_F      |
| mysql-bin.000015 | 529814107 | Xid            |         1 |   529814134 | COMMIT /* xid=68760985 */            |
+------------------+-----------+----------------+-----------+-------------+--------------------------------------+
```

**Comment by nmaquet** [comment]
The binlog info I've posted above is for a different crash. Here's the original one (very similar output):
```
mysql> SHOW BINLOG EVENTS IN 'mysql-bin.000015' FROM 527288475 LIMIT 10;
+------------------+-----------+----------------+-----------+-------------+-----------------------------------------------+
| Log_name         | Pos       | Event_type     | Server_id | End_log_pos | Info                                          |
+------------------+-----------+----------------+-----------+-------------+-----------------------------------------------+
| mysql-bin.000015 | 527288475 | Update_rows_v1 |         1 |   527288895 | table_id: 208 flags: STMT_END_F               |
| mysql-bin.000015 | 527288895 | Xid            |         1 |   527288922 | COMMIT /* xid=67972953 */                     |
| mysql-bin.000015 | 527288922 | Gtid           |         1 |   527288960 | BEGIN GTID 0-1-11409227                       |
| mysql-bin.000015 | 527288960 | Table_map      |         1 |   527289044 | table_id: 208 (mm_memberlists_svc.MemberList) |
| mysql-bin.000015 | 527289044 | Update_rows_v1 |         1 |   527289516 | table_id: 208 flags: STMT_END_F               |
| mysql-bin.000015 | 527289516 | Xid            |         1 |   527289543 | COMMIT /* xid=67972961 */                     |
| mysql-bin.000015 | 527289543 | Gtid           |         1 |   527289581 | BEGIN GTID 0-1-11409228                       |
| mysql-bin.000015 | 527289581 | Table_map      |         1 |   527289665 | table_id: 208 (mm_memberlists_svc.MemberList) |
| mysql-bin.000015 | 527289665 | Update_rows_v1 |         1 |   527290197 | table_id: 208 flags: STMT_END_F               |
| mysql-bin.000015 | 527290197 | Xid            |         1 |   527290224 | COMMIT /* xid=67973015 */                     |
+------------------+-----------+----------------+-----------+-------------+-----------------------------------------------+
```

**Comment by osheroff** [comment]
The table_id (208) here refers to the "MemberList" table -- the ids refer to table map events.  What's that schema?

**Comment by nmaquet** [comment]
@osheroff I've updated my comment above with the MemberList schema.

**Comment by osheroff** [comment]
Rats, that's likely nothing special.  There could be something special in that row that's causing open replicator to over read, still.  

I think to reproduce the bug you'd need to point maxwell *before* the row that it barfs on -- at the table map event that precedes the row.  But even that may not repro the damn thing, to be honest.  So maybe we could try pointing maxwell before the event?

The other thing I could think of would be to dump for me the relevant binlog entry in binary, using mysqlbinlog --raw

**Comment by osheroff** [comment]
If none of that works out I can try doing a build of open replicator that will stop before it over reads and spit out the row that triggered it.

**Comment by osheroff** [comment]
@nmaquet, was thinking more about your problem today.  Really the most reliable repro would be to run a `tcpdump` maxwell-side, wait for a repo and snip out the relevant bits.  possible?

**Comment by nmaquet** [comment]
@osheroff Thanks for your help, `tcpdump` and `mysqlbinlog` aren't practical on my setup. Over the next few days, I'll try patching open-replicator to spill out the offending row. The assertion error hasn't occurred in the last 48h so I have a bit of time to look into it without rushing. At least now I know that the error is caused by a table that maxwell isn't replicating, which is reassuring!
I'll give you an update next week.

**Comment by osheroff** [comment]
curious if you got anywhere on this one?

**Comment by osheroff** [comment]
sigh, closing without a repro.  re-open if there's new data.
