### ISSUE TITLE
Hardware requirements

### ISSUE THREAD

**Issue by rtorrero** [zendesk/maxwell#397]
I'm trying to guess how big our VM/server should be in order to handle what we expect from Maxwell:

Let's say we are running a ndbcluster with a total of around 20 million transactions a day of which we want to process around 1-2 million spread across 5 different tables.

Any suggestion or experience on a similar workload?

**Comment by osheroff** [comment]
we run a cluster that does ~100mm rows per day on a fairly modest VM; a couple of cpus and 8gb of ram.  Maxwell will be able to use about 3 cpus effectively (1 for the replicator, 1 that does rows -> json, 1 for the kafka producer), but not a lot more.  The vast majority of the cpu usage for us is snappy compression.

(now that I'm thinking about it, need to see if throwing more kafka producer threads will spread the  compression workload better).

Maxwell also likes a bit of temp disk space if you have very large transactions.

**Comment by rtorrero** [comment]
Great, this should give a good start point to correctly scale my VM's. Thanks!
