### ISSUE TITLE
Maxwell killed without any reason

### ISSUE THREAD

**Issue by radek1st** [zendesk/maxwell#408]
Our Maxwell app, version 1.1.4 running in Docker and connecting to https://github.com/wurstmeister/kafka-docker is frequently killed, but there is no logs to explain the reason why. Any suggestions?

<img width="1095" alt="screen shot 2016-08-16 at 8 02 25 pm" src="https://cloud.githubusercontent.com/assets/246085/17712113/7affae26-63ec-11e6-9760-b224ff95ca5b.png">

**Comment by osheroff** [comment]
to me this looks like it could be an OOM-killer exception.  does `dmesg` show anything?

**Comment by radek1st** [comment]
I noticed that if I delete the maxwell database, it recreates it and it is working fine. However, when it has to pick up the work, it dies with the above `Killed` error. @osheroff the machine has 15 gig of RAM, what JVM flag do you recommend me trying?

**Comment by osheroff** [comment]
15gb should be equal to a JVM of about 4gb, which is more than enough for maxwell.  Wondering if maybe the docker engine has some ram limits?  You could try `-Xmx1g` to limit maxwell down to 1gb.

**Comment by powerLambda** [comment]
Met same issue in recent label( commit ed8f092c5a9b47826163086553384d68d7c558f0(Date:   Tue Aug 23 15:42:11 2016 -0700)

**Comment by osheroff** [comment]
was there ever a repro here?  a fix?
