### ISSUE TITLE
What do these warnings indicate? (Started replication stream outside of transaction... , Unhandled QueryEvent inside transaction... , IndexOutOfBoundsException)

### ISSUE THREAD

**Issue by Bradyta** [zendesk/maxwell#410]
> 21:24:39,819 WARN  MaxwellReplicator - Started replication stream outside of transaction.  This shouldn't normally happen.  

  

> 21:24:39,819 WARN  MaxwellReplicator - Unhandled QueryEvent inside transaction: QueryEvent[header=BinlogEventV4HeaderImpl[timestamp=1471461410000,eventType=2,serverId=15275,eventLength=83,nextPosition=413978557,flags=8,timestampOfReceipt=1471469079817],threadId=535973765,elapsedTime=7660,databaseNameLength=11,errorCode=0,statusVariablesLength=34,statusVariables=[QFlags2Code[flags=16384], QSQLModeCode[sqlMode=0], QCatalogNzCode[catalogName=std], QCharsetCode[characterSetClient=33,collationConnection=33,collationServer=8], QTimeZoneCode[timeZone=SYSTEM]],databaseName=dbName,sql=BEGIN]    
  
Hello, I've made some changes locally to Maxwell to edit the schema after a query event rather than regenerate it so it would be compatible with a database that had issues with it (a query would require 72 calls to schemaStore and our buffer would overflow) but anyways the tests pass. I'm new to working with Open Source technologies so I hope this is the right place to ask, I'm just looking for insight into what's going wrong. Because eventually I get the error: 
  

> java.lang.IndexOutOfBoundsException: Index: 0, Size: 0
> at java.util.ArrayList.rangeCheck(ArrayList.java:653)
>         at java.util.ArrayList.get(ArrayList.java:429)
>         at com.zendesk.maxwell.ColumnWithDefinitionList$ColumnWithDefinitionIterator.next(ColumnWithDefinitionList.java:53)
>         at com.zendesk.maxwell.ColumnWithDefinitionList$ColumnWithDefinitionIterator.next(ColumnWithDefinitionList.java:28)
>         at com.zendesk.maxwell.MaxwellAbstractRowsEvent.jsonMaps(MaxwellAbstractRowsEvent.java:203)
>         at com.zendesk.maxwell.MaxwellReplicator.getTransactionRows(MaxwellReplicator.java:218)
>         at com.zendesk.maxwell.MaxwellReplicator.getRow(MaxwellReplicator.java:299)
>         at com.zendesk.maxwell.MaxwellReplicator.work(MaxwellReplicator.java:112)
>         at com.zendesk.maxwell.RunLoopProcess.runLoop(RunLoopProcess.java:31)
>         at com.zendesk.maxwell.Maxwell.run(Maxwell.java:121)
>         at com.zendesk.maxwell.Maxwell.main(Maxwell.java:127)

The changes I made were: In case of a processQueryEvent call instead of calling save and therefore saveSchema to call my own functions edit and editSchema which would do some case matching to figure out the resolvedSchemaChange type and send enough information to edit and editSchema to go with additional queries to just edit the existing schema rather than create a new record and regenerate the whole thing with the three nested for loops.

**Comment by osheroff** [comment]
the second stack trace likely means you've goofed up the schema.  I'm not sure what you mean by " edit the schema after a query event rather than regenerate it" -- as of some version of maxwell, it maintains a base schema and delta-changes on top of that.   Anyway, if you need help with a fork, it's best to open a "review-only" PR so folks can actually look at the code in question.

**Comment by Bradyta** [comment]
It looks like our most recent pull was:  
 ## [v0.17.0](https://github.com/zendesk/maxwell/releases/tag/v0.17.0): "wrists of William"  
  
I'll poke around my code with your insight a little more and put up a review-only PR if I still can't figure it out.  
  
Thank you so much!

**Comment by osheroff** [comment]
you should definitely consider just upgrading, as of v1.1.0 the handling of large schemas is infinitely more efficient.

**Comment by Bradyta** [comment]
I think I'm going to after looking at your changes. From the pull we had last every time saveSchema() got called you had to do something similar to this process:  
```
  
		for (Database d : schema.getDatabases()) {
			Long dbId = executeInsert(databaseInsert, schemaId, d.getName(), d.getCharset());

			for (Table t : d.getTableList()) {
				Long tableId = executeInsert(tableInsert, schemaId, dbId, t.getName(), t.getCharset(), t.getPKString());


				for (ColumnDef c : t.getColumnList()) {
					String enumValuesSQL = null;

					if ( c instanceof EnumeratedColumnDef ) {
						EnumeratedColumnDef enumColumn = (EnumeratedColumnDef) c;
						enumValuesSQL = StringUtils.join(enumColumn.getEnumValues(), ",");
					}

					columnData.add(schemaId);
					columnData.add(tableId);
					columnData.add(c.getName());

					if ( c instanceof StringColumnDef ) {
						columnData.add(((StringColumnDef) c).getCharset());
					} else {
						columnData.add(null);
					}

					columnData.add(c.getType());

					if ( c instanceof IntColumnDef ) {
						columnData.add(((IntColumnDef) c).isSigned() ? 1 : 0);
					} else if ( c instanceof BigIntColumnDef ) {
						columnData.add(((BigIntColumnDef) c).isSigned() ? 1 : 0);
					} else {
						columnData.add(0);
					}

					columnData.add(enumValuesSQL);
				}

				if ( columnData.size() > 1000 )
					executeColumnInsert(conn, columnData);

			}
		}
```  
  
But it looks like now you just look to edit the schema if baseSchemaID != null and return that result, rather than do those nested for loops every time, correct?

**Comment by osheroff** [comment]
yeah, the change was: 

- before 1.1.0, we stashed a full copy of the schema in the database every time the schema changed.
- after 1.1.0, we stash the full copy only once, and then with each subsequent schema change we serialize that schema change to JSON.  When we boot up we read the full schema and then overlay all the schema changes on top of it. 

the pre-1.1.0 behavior was a performance problem for us, too.

**Comment by Bradyta** [comment]
Awesome, thank you so much! :)
