### ISSUE TITLE
partition by column?

### ISSUE THREAD

**Issue by smferguson** [zendesk/maxwell#427]
We're going to use maxwell as CDC in a (mysql backed) event sourced system. In this case the primary key has no meaning (tables are append-only). We would like to partition by a non-distinct 'event_id' column instead of the primary key. Is there any ability to partition by a random column? (or are we crazy for a number of reasons?)

**Comment by osheroff** [comment]
i don't think it's crazy.  I actually kinda have a use case for partitioning by a column, but I could never quite figure out what to do if/when the column didn't exist in a table; fall back to PK/random?  Would take a patch around this if you wrote one

**Comment by xmlking** [comment]
partition by a **callback function** that a developer can supply as part of deployment configuration would be nice to accommodate specific use cases:
```java
String getPartitionKey( String database,  String table, Sting pk, Schema schema) {
  // your logic   
 return  composedPartitionKey
} 
```

**Comment by smferguson** [comment]
@xmlking neat idea, but beyond the scope of work for me at the moment (and @osheroff hasn't commented on it). please start a new discussion if you want to pursue that.
