### ISSUE TITLE
Alter with 'engine' + 'character set' crushes maxwell

### ISSUE THREAD

**Issue by imdark** [zendesk/maxwell#429]
`"ALTER TABLE `test` ENGINE=`InnoDB` CHARACTER SET latin1"`

this alter throws a
`java.lang.ClassCastException: com.zendesk.maxwell.schema.ddl.TableAlter cannot be cast to com.zendesk.maxwell.schema.ddl.TableCreate 
`

the source of the issue is MysqlParserListener.java: the first line of this function
```
public void exitCreation_character_set(Creation_character_setContext ctx) {
                TableCreate tableCreate = (TableCreate) schemaChanges.get(0);
                tableCreate.charset = unquote_literal(ctx.charset_name().getText());
}

```
character set should work for both TableCreate and TableUpdate

**Comment by osheroff** [comment]
fixed in 1.2.1
