### ISSUE TITLE
How do I turn on null values for bootstrap operation?

### ISSUE THREAD

**Issue by bmichaud** [zendesk/maxwell#444]
Version 1.2.1
We are now getting null values for changes in the binary log files. (Thank you)
However, we are not getting null column values from the bootstrap operation. Is there some way to turn that on as well?

**Comment by osheroff** [comment]
no, I suppose that's a bug.

**Comment by bmichaud** [comment]
Well I appreciate that assessment. It is rather important for us to have null values in our data. Have you had a chance to look at it yet? If not, could you give me a hint as to where to start, and I will take a look later this week? Thanks.

**Comment by osheroff** [comment]
nope, have not looked.  It may be that simply removing https://github.com/zendesk/maxwell/blob/cec883547efcfb7540088a82b367e8bd04e64ce1/src/main/java/com/zendesk/maxwell/bootstrap/SynchronousBootstrapper.java#L224 will do it for ya, but would need to write a couple of tests around it; not totally confident that `getObject` will do the right thing in all scenarios.

**Comment by bmichaud** [comment]
I'm just about to take the 1.5.1 release and configure Maxwell to allow nulls in bootstrap, but I am not seeing the configuration option to turn nulls on specifically for bootstrap. Should I just use the existing configuration for replication called...
`output_nulls=true`
?

**Comment by osheroff** [comment]
yup, the one config flag controls both.  you don't need to explicitly configure it, either; it's the default.

**Comment by bmichaud** [comment]
That's what I kind of gleaned from the code, but it's good to have confirmation. Thanks. We will be testing it on our systems in the next day or two.
