### ISSUE TITLE
New maxwell v1.2.2 cann't connect to old kafka version0.8.1

### ISSUE THREAD

**Issue by superbool** [zendesk/maxwell#447]
Hi,I'm using  maxwell v1.2.2  ,and my kafka version is 0.8.1,But I get an error when start maxwell:
```
10:42:29,000 ERROR Sender - Uncaught error in kafka producer I/O thread:
org.apache.kafka.common.protocol.types.SchemaException: Error reading field 'throttle_time_ms': java.nio.BufferUnderflowException
	at org.apache.kafka.common.protocol.types.Schema.read(Schema.java:71) ~[kafka-clients-0.9.0.1.jar:?]
	at org.apache.kafka.clients.NetworkClient.handleCompletedReceives(NetworkClient.java:439) ~[kafka-clients-0.9.0.1.jar:?]
	at org.apache.kafka.clients.NetworkClient.poll(NetworkClient.java:265) ~[kafka-clients-0.9.0.1.jar:?]
	at org.apache.kafka.clients.producer.internals.Sender.run(Sender.java:216) ~[kafka-clients-0.9.0.1.jar:?]
	at org.apache.kafka.clients.producer.internals.Sender.run(Sender.java:128) [kafka-clients-0.9.0.1.jar:?]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_45]
```
How can I solve it ?Does maxwell v1.2.2 don't support old kafka version?
Best wishes ,Thank you so much.

**Comment by superbool** [comment]
I got the answer ,Thank you

**Comment by saup007** [comment]
@superbool hello? how to fix it?

**Comment by superbool** [comment]
@saup007 
maxwell跟kafka版本不兼容的问题：
在启动的命令行中加入下面的参数，就能消除错误了。
--kafka0.8

**Comment by superbool** [comment]
@saup007 
http://maxwells-daemon.io/producers/  找了好久文档

Maxwell writes to a kafka topic named "maxwell" by default. It can be static, e.g. 'maxwell', or dynamic, e.g. namespace_%{database}_%{table}. In the latter case 'database' and 'table' will be replaced with the values for the row being processed. This can be changed with the kafka_topic option.

Client version
By default, maxwell runs with kafka clients 0.11.0.1. There is a flag (--kafka_version) that allows maxwell to run with either 0.8.2.2, 0.9.0.1, 0.10.0.1, 0.10.2.1 or 0.11.0.1. Noteables: - Kafka clients 0.9.0.1 are not compatible with brokers running kafka 0.8. The exception below will show in logs when that is the case:

ERROR Sender - Uncaught error in kafka producer I/O thread:
SchemaException: Error reading field 'throttle_time_ms': java.nio.BufferUnderflowException
Kafka clients 0.8 are compatible with brokers running kafka 0.8.
0.10.0.x clients only support 0.10.0.x or later brokers.
Mixing Kafka 0.10 with other versions can lead to serious performance impacts. For More details, read about it here.
0.11.0 clients can talk to version 0.10.0 or newer brokers.

**Comment by saup007** [comment]
@superbool #867

--kafka_version=0.9.0.1，还是不行。
