### ISSUE TITLE
Question: metadata.fetch.timeout.ms vs. max.block.ms

### ISSUE THREAD

**Issue by bmichaud** [zendesk/maxwell#451]
I am getting this message in my error.log on start-up, but I don't see the max.block.ms string anywhere in the project. Is this message out-of-date?

WARN  KafkaProducer - metadata.fetch.timeout.ms config is deprecated and will be removed soon. Please use max.block.ms

**Comment by osheroff** [comment]
no, the message is actually right.  Maxwell can use either the 0.8.2.1 kafka client libs (which use metadata.fetch.timeout.ms), or the 0.9.0.1 version, which doesn't.  I guess I might go ahead and remove the default configuration values for kafka and just drop them into config.properties.example instead.

**Comment by smferguson** [comment]
@osheroff seems like we could just remove the values from the producer and put them back in the .properties file, right? too simple?

**Comment by osheroff** [comment]
we moved the defaults out of maxwell into config.properties in v1.5.0
