### ISSUE TITLE
Maxwell being blocked from the binlog

### ISSUE THREAD

**Issue by lucianjon** [zendesk/maxwell#455]
We've been running maxwell here for a few months now and have noticed that quite regularly maxwell appears to get blocked reading from the binlog. 

We're monitoring this by diffing the position from `show master status` and the position stored in `maxwell.positions`. An example from the last hour is below: 

<img width="479" alt="maxwell" src="https://cloud.githubusercontent.com/assets/1711481/19294758/0c050d28-908c-11e6-844f-d7bd448d44fd.png">

It doesn't seem to be correlated with long running queries as it'll still get stuck with nothing in the process list. The maxwell thread will show `Master has sent all binlog to slave; waiting for binlog to be updated`. The only hunch we have is that there are long running open transactions blocking maxwell, although this has been hard to track down. The contents of `information_schema.innodb_trx` is generally empty, however there are always a large number of transactions in `show engine innodb status` in the process of cleaning up. Some of these are very long running too. There's nothing in maxwell's logs to indicate a problem and this seems more like a mysql configuration issue then anything else. 

Am mainly curious is anyone else has run into this or has an idea of what the culprit might be.

Cheers

**Comment by osheroff** [comment]
important here to narrow down whether maxwell is actually stuck or just lagged/falling behind -- during these incidents does the maxwell position stay totally still?  Or does it move, but at a slower pace than the master?

long running transactions aren't generally a problem, but very *large* transactions can cause performance issues; they get buffered to disk to allow each row to have the same `xid` (it comes in at the end of the transaction in the binlog, sadly).  So that could do it.

About how much binlog data is db5 generating per hour?

**Comment by lucianjon** [comment]
We've added metrics on the position of the master binlog and maxwell's position. It definitely looks like maxwell getting stuck at a position rather than just lagging behind. 

Is there a way to identify transactions that may be blocking maxwell?

db5 is generally generating around 256MB per hour

**Comment by osheroff** [comment]
turn on debug logging for maxwell, it should help you trace when / where maxwell is stalling -- it outputs a log line for each kafka record, so be prepared to store quite a bit of data

**Comment by lucianjon** [comment]
Thanks for the suggestion, the debug logging has narrowed it down somewhat. Most of the transactions against our db servers are created by an application using spring + hibernate. There are a couple of quartz crons inside the application that make pretty heavy use of transactions. Maxwell looks to get blocked as soon as one of these crons finishes and gets unblocked once the other starts. We have been able to repeatedly unblock maxwell by manually triggering the latter cron. So it looks like potentially things aren't being cleaned up properly but we'll have to do some more investigation into it.

**Comment by osheroff** [comment]
you ever make any progress here?

**Comment by lucianjon** [comment]
Haven't had a lot of time to spend on this lately. We've just been trying to track down hibernate code that may not be commiting transactions. Anyway this can probably be closed now, it's definitely something on our end. Thanks for the help

**Comment by osheroff** [comment]
k.  good luck.
