### ISSUE TITLE
Binlog parse error when running multiple Maxwell instances

### ISSUE THREAD

**Issue by jeff8998** [zendesk/maxwell#466]
I'm attempting to run two instances of Maxwell 1.4.2 against the same binlog.  Each instance is configured with a unique client id and unique kafka topic. Each instance replicates a disjoint set of tables.

When I run the two instances at the same time I get the following error. If I run only one of the instances I don't see the error and everything replicates as expected. Is there a race condition between the two instances that blocks them from parsing the same binlog file?

11/1/2016 8:38:38 AM13:38:38,213 ERROR AbstractBinlogParser - failed to parse binlog
11/1/2016 8:38:38 AMjava.lang.RuntimeException: EOFPacket[packetMarker=254,warningCount=0,serverStatus=2]
11/1/2016 8:38:38 AM	at com.google.code.or.binlog.impl.ReplicationBasedBinlogParser.readPacketMarker(ReplicationBasedBinlogParser.java:104) 
11/1/2016 8:38:38 AM	at com.google.code.or.binlog.impl.ReplicationBasedBinlogParser.doParse(ReplicationBasedBinlogParser.java:135) 
11/1/2016 8:38:38 AM	at com.google.code.or.binlog.impl.AbstractBinlogParser$Task.run(AbstractBinlogParser.java:263) 
11/1/2016 8:38:38 AM	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_77-internal]

**Comment by osheroff** [comment]
1.  are you running  on mysql 5.5? 
2.  have you set `replica_server_id` on each maxwell instance?

This is *probably* the problem -- the mysql server thinks it's getting 2 connections from the same client.  I need to make the docs clearer about this weird config hitch, as the server doesn't throw us any useful error.

**Comment by jeff8998** [comment]
Thanks for the quick response. I'm running MariaDB 10 (so far I have not seen any problems using Maxwell with MariaDB). I did not set the replica server id since the docs only mentioned the client id but I will give that I try.

**Comment by osheroff** [comment]
i added some code to set a replica_server_id based on a hash of the client_id so this wouldn't happen in the future.
