### ISSUE TITLE
Unable to bootstrap when using a non-default schema_database

### ISSUE THREAD

**Issue by lucianjon** [zendesk/maxwell#471]
Hey, we've been trying to get bootstrapping working when running multiple instances of maxwell against a binlog. We've had an instance running against the `maxwell` schema for a few months now. It's running v1.1.1 and bootstrapping works without issue.

Now we've set up another instance running v1.4.2/v1.5.0 against the same binlog. They've both been running in parallel for a couple of weeks without issue. The new instance sets the `schema_database` and `client_id` to something else to avoid conflicts. However rows inserted into the `bootstrap` table never get picked up. There's nothing in the logs (with debug) that indicates anything is happening. 

We've tried to keep the config between the two instances as similar as possible, the relevant differences being:

```
client_id=maxwell_two
schema_database=maxwell_two
```

We've tried a couple things to rule out some problems:
* Downgrading the new instance to v1.1.1 and running both in parralel (both crashed due to a binlog parse error in this case)
* Killing the old instance and running the new instance with v1.1.1 
* Killing the old instance and running the new instance with v1.5.0

Nothing has had any effect so far so it seems either we've got horribly wrong somewhere with config or possibly something isn't working with the non-default `schema_database`

**Comment by osheroff** [comment]
Which bootstrap table did the `maxwell-bootstrap` tool end up inserting into, `maxwell.bootstrap` or `maxwell_two.bootstrap`?  I took a look at the code, it definitely pays attention to an alternate `schema_database` name:

```
	public boolean isBootstrapRow(RowMap row) {
		return row.getDatabase().equals(this.context.getConfig().databaseName) &&
			row.getTable().equals("bootstrap");
	}
```

having two maxwell processes pointing at separate schema_databases is a little goofy (in particular, they don't realize that `maxwell.positions` is a maintenance table, and they shouldn't output it), but I can see why you're doing that and there shouldn't, theoretically, be anything that prevents it from working.

**Comment by lucianjon** [comment]
I had a look through the bootstrap utility code and saw it was just inserting the row and waiting on completion. So I've just been inserting the rows manually into `maxwell_two`. 

I also couldn't see a reason why it wouldn't be started given maxwell sees the binlog event. Anyway I may just recompile with some extra print statements to see where it's getting to.

**Comment by lucianjon** [comment]
Alright so I found the issue. The bootstrap events were being filtered out due to the maxwell schema being hardcoded to `maxwell` in the `matches` check inside `MaxwellFilter`. I've changed it to use the maxwell schema from config and it started working. 

I'll created a pr with a fix if you want to use it. https://github.com/zendesk/maxwell/pull/479

**Comment by osheroff** [comment]
1.5.1 includes the fix
