### ISSUE TITLE
bootstrapping fails if an unsupported datatype is used in an excluded table

### ISSUE THREAD

**Issue by mfbeary** [zendesk/maxwell#493]
to reproduce [using OSX with MySQL as installed from homebrew]:
-create a database on a local mySQL instance, including one table "testSchema.table_with_json" with a JSON field
-follow the quickstart instructions, adding `--jdbc_options=useSSL=false` to remove SSL warnings and `--exclude_tables=table_with_json` or `--blacklist_tables=table_with_json` to exclude the table with an unsupported datatype

expected results: success, but unsupported table is not replicated

actual results:
`17:04:41,122 INFO  SchemaStoreSchema - Creating maxwell database
17:04:41,326 INFO  ProducerConfig - ProducerConfig values: 
	compression.type = none
	metric.reporters = []
	metadata.max.age.ms = 300000
	metadata.fetch.timeout.ms = 60000
	reconnect.backoff.ms = 50
	sasl.kerberos.ticket.renew.window.factor = 0.8
	bootstrap.servers = [localhost:9092]
	retry.backoff.ms = 100
	sasl.kerberos.kinit.cmd = /usr/bin/kinit
	buffer.memory = 33554432
	timeout.ms = 30000
	key.serializer = class org.apache.kafka.common.serialization.StringSerializer
	sasl.kerberos.service.name = null
	sasl.kerberos.ticket.renew.jitter = 0.05
	ssl.keystore.type = JKS
	ssl.trustmanager.algorithm = PKIX
	block.on.buffer.full = false
	ssl.key.password = null
	max.block.ms = 60000
	sasl.kerberos.min.time.before.relogin = 60000
	connections.max.idle.ms = 540000
	ssl.truststore.password = null
	max.in.flight.requests.per.connection = 5
	metrics.num.samples = 2
	client.id = 
	ssl.endpoint.identification.algorithm = null
	ssl.protocol = TLS
	request.timeout.ms = 30000
	ssl.provider = null
	ssl.enabled.protocols = [TLSv1.2, TLSv1.1, TLSv1]
	acks = 1
	batch.size = 16384
	ssl.keystore.location = null
	receive.buffer.bytes = 32768
	ssl.cipher.suites = null
	ssl.truststore.type = JKS
	security.protocol = PLAINTEXT
	retries = 0
	max.request.size = 1048576
	value.serializer = class org.apache.kafka.common.serialization.StringSerializer
	ssl.truststore.location = null
	ssl.keystore.password = null
	ssl.keymanager.algorithm = SunX509
	metrics.sample.window.ms = 30000
	partitioner.class = class org.apache.kafka.clients.producer.internals.DefaultPartitioner
	send.buffer.bytes = 131072
	linger.ms = 0

17:04:41,349 INFO  AppInfoParser - Kafka version : 0.9.0.1
17:04:41,349 INFO  AppInfoParser - Kafka commitId : 23c69d62a0cabf06
17:04:41,364 INFO  Maxwell - Maxwell v1.5.1 is booting (MaxwellKafkaProducer), starting at BinlogPosition[master.000001:11716999]
17:04:41,455 INFO  AbstractSchemaStore - Maxwell is capturing initial schema
java.lang.IllegalArgumentException: unsupported column type json
	at com.zendesk.maxwell.schema.columndef.ColumnDef.build(ColumnDef.java:82)
	at com.zendesk.maxwell.schema.SchemaCapturer.captureTable(SchemaCapturer.java:134)
	at com.zendesk.maxwell.schema.SchemaCapturer.captureDatabase(SchemaCapturer.java:92)
	at com.zendesk.maxwell.schema.SchemaCapturer.capture(SchemaCapturer.java:63)
	at com.zendesk.maxwell.schema.AbstractSchemaStore.captureSchema(AbstractSchemaStore.java:42)
	at com.zendesk.maxwell.schema.MysqlSchemaStore.restoreOrCaptureSchema(MysqlSchemaStore.java:66)
	at com.zendesk.maxwell.schema.MysqlSchemaStore.getSchema(MysqlSchemaStore.java:56)
	at com.zendesk.maxwell.Maxwell.start(Maxwell.java:154)
	at com.zendesk.maxwell.Maxwell.main(Maxwell.java:184)
17:04:41,533 INFO  Maxwell - starting shutdown
17:04:41,659 INFO  PositionStoreThread - Storing final position: BinlogPosition[master.000001:11716999]`

**Comment by osheroff** [comment]
yokay, makes sense.  json support has got some motion going, but it makes sense to half-support it until there.

**Comment by osheroff** [comment]
1.7.0 gets experiment json datatype support
