### ISSUE TITLE
can maxwell write db metadata on localfile？

### ISSUE THREAD

**Issue by GitProBo** [zendesk/maxwell#501]
Maxwell save db metadata in a db_schema called maxwell default, can maxwell write db metadata on localfile？

**Comment by osheroff** [comment]
No.  I had started down a road of abstracting `SchemaStore` out with an eye towards building a kafka-based schema store, but it's not a commonly asked-for feature and it's low on the priority list.

**Comment by GitProBo** [comment]
that's ok

**Comment by osheroff** [comment]
closing this one out as a WONTFIX for now, just as it hasn't been requested much.  if I get more rqeuests for the feature I'll re-open
