### ISSUE TITLE
[Feature Request] Producer for AWS Kinesis.

### ISSUE THREAD

**Issue by thomasdziedzic** [zendesk/maxwell#502]
I am investigating using maxwell for a project and would like to send events to kinesis if possible.
The benefits boil down to the benefits of using a managed service over a self-managed service.
Thoughts?

**Comment by osheroff** [comment]
there's https://github.com/zendesk/maxwell/pull/280/files, which never quite made it across the finish line.  Would happily merge it if someone dusted it off and put it through some productionization paces.

**Comment by osheroff** [comment]
wheee, in 1.7.0
