### ISSUE TITLE
failed to start when I specified an existing db_schema to store metadata

### ISSUE THREAD

**Issue by GitProBo** [zendesk/maxwell#507]
It's ok when using maxwell as schema_database, when I switching to test, maxwell failed to start

#10:19:20,271 ERROR Maxwell - SQLException: Table 'test.schemas' doesn't exist
10:19:20,272 ERROR Maxwell - Table 'test.schemas' doesn't exist
10:19:20,273 INFO  Maxwell - starting shutdown

**Comment by GitProBo** [comment]
GRANT SELECT, REPLICATION SLAVE, REPLICATION CLIENT ON *.* TO 'maxwell'@'10.2.%.%' IDENTIFIED BY PASSWORD '*398B5A9CDBC55A409178865ED3D2A0FB9D5E1934' |
| GRANT ALL PRIVILEGES ON `test`.* TO 'maxwell'@'10.2.%.%'

**Comment by osheroff** [comment]
fixed in 1.6.0
