### ISSUE TITLE
Binlog events are skipped if producing fails

### ISSUE THREAD

**Issue by lucianjon** [zendesk/maxwell#531]
So we had a case a couple weeks ago where maxwell failed to produce a couple of messages to kafka due to a leadership change on maxwell's topic. It recovered after that and kept on processing the binlog but the events during that period lost. 

It's pretty important for us to make sure every event makes it into kafka. Would it be possible to implement some method to make sure we don't continue processing the binlog if producing isn't possible?

**Comment by osheroff** [comment]
it's all in the kafka settings.  For reliable delivery you want acks=all and/or retries=(some large number), as *well* as a min.insync.replicas on your maxwell topic (the interaction between acks=all and min.insync.replicas is kinda subtle; data loss is possible even with acks=all if min.insync.replicas is too low). 

I'll keep this issue open as a task to document how to configure at-least-once delivery semantics.

**Comment by wushujames** [comment]
Here's an epic blog post I wrote about the interactions between min.insync.replicas and acks: https://logallthethings.com/2016/07/11/min-insync-replicas-what-does-it-actually-do/

**Comment by lucianjon** [comment]
Yeah cool for cases like this we may just have to bump retries up from 0 and deal with the potential duplicates on the other side. We have our replication factor and min insync replicas set up so a partition will still be available if we lose a node but it seems there is still a small period of time during the leadership handover where requests will fail. It's likely small enough that adding retries will cover it.

**Comment by osheroff** [comment]
I added an at-least-once section in the docs. thx for the link james.
