### ISSUE TITLE
bootstrapping from a specific time/date (event replay)

### ISSUE THREAD

**Issue by smferguson** [zendesk/maxwell#532]
in cases where maxwell has missed data(!) or where it has been down long enough that the binlog it knew about is gone we would need to replay table(s) from a known point-in-time so that there is zero data loss to the outside world (kafka, in our case). i wonder if we could leverage the bootstrap code to accept a date/time when the replay "starts". i see that it's using a simple select in the sync case (https://github.com/zendesk/maxwell/blob/master/src/main/java/com/zendesk/maxwell/bootstrap/SynchronousBootstrapper.java#L181) so it _feels_ like a straightforward addition of a where clause. thoughts?

**Comment by osheroff** [comment]
a where clause option into the bootstrapper sounds like a fine idea.  go for it.  be careful of SQL injection.

**Comment by smferguson** [comment]
I don't see upgrade scripts in maxwell, what's the approved technique for altering a table? (adding a column?)

**Comment by osheroff** [comment]
https://github.com/zendesk/maxwell/blob/c414ad45c94aa1a1c7f384bf7f2ee4781b9fe564/src/main/java/com/zendesk/maxwell/schema/SchemaStoreSchema.java#L154

**Comment by smferguson** [comment]
👍 thanks. for some reason i never look in java for sql.

**Comment by osheroff** [comment]
released in 1.7.1
