### ISSUE TITLE
running multiple instances of maxwell against the same master-more explanation

### ISSUE THREAD

**Issue by yogiGueta** [zendesk/maxwell#547]
Hi,
Can you elaborate more about this subject?
What is the right configuration for it? 
How can i choose the master (there are different projects for maxwell master and slaves)?
Where can i get a maven\Gradle depndency of the maxwell project?
Thanks,

**Comment by osheroff** [comment]
> What is the right configuration for it?

just start different instances of maxwell with different `client_id`.   If mysql is pre-5.6, you'll also want to configure different `replica_server_id`.

> How can i choose the master (there are different projects for maxwell master and slaves)?
No, maxwell is designed to be pointed at the master.  That's the proper config.

> Where can i get a maven\Gradle depndency of the maxwell project?
Not sure what you're asking for here.  Currently maxwell is only released as a tarball.  At some point I need to push the jar up as an artifact.

**Comment by yogiGueta** [comment]
Thanks you for the answers.
