### ISSUE TITLE
zendesk/maxwell has tags from movio/maxwell ???

### ISSUE THREAD

**Issue by nmaquet** [zendesk/maxwell#553]
Now this is a WTF if I've ever seen one.
I've added some tags to movio/maxwell last month for special releases of our production Maxwell instances and somehow these tags ended up in zendesk/maxwell.
I don't have commit rights to zendesk/maxwell so I have no clue how this could happen.
Could you remove these tags? Sorry for the inconvenience. Here's the list:

```
1.1.1-cinep-hack-1
1.1.1-cinep-hack-2
1.1.1-cinep-hack-3
1.1.1-cpx-hack-1
1.1.1-cpx-hack-2
1.1.1-cpx-hack-3
cinep-old-ls
cpx-old-tx
```

**Comment by osheroff** [comment]
yeah I probably fetched your workspace into mine and then pushed all tags.  will remove.

**Comment by nmaquet** [comment]
:+1:

**Comment by osheroff** [comment]
removed
