### ISSUE TITLE
Is it advisable to use bootstrap for tables having 15 to 100 million records

### ISSUE THREAD

**Issue by tankchintan** [zendesk/maxwell#558]
I wanted to know how the bootstrap utility works, in context of how it would behave when bootstrapping tables with multi-million records.

I have couple of tables which have records ranging from 15 million to 100 million records. I would like to know how is the bootstrapping accomplished so that I can plan the infrastructure accordingly.

* If bootstrapping involves re-writing insert statements of all the records to the binlog. Then I would have to make sure that their is enough disk space on the mysql box & that I turn of binlog rotation temporarily.
* If bootstrapping involves just streaming all the records directly from table to the producer then I would have to make sure that their is enough I/O capacity on my box that it can handle such a high burst of I/O.

I am assuming in any case I should do this in `async` mode. Are their any other precautions I need to have? Is it possible to piecemeal bootstrapping like only subset of records? I know their is a where clause but that seems to be only for date field, which I do not have in most tables.

On another note, if maxwell dies in between of bootstrapping session?! will it pick up from where it left off or will I have to re-trigger bootstrap? 

I am asking this because I have seen mixed results in this. After starting bootstrap session (by inserting in to table) & starting maxwell script. In few seconds maxwell exited because it was not able to create topic in Kafka. So I went in & created one myself. When I restarted maxwell exited again due to some other issue (wrong brokers). So after fixing all this I started maxwell 3rd time. But it seemed that maxwell didnt know pick up bootstrap request that I had made earlier. I had to re-insert in bootstrap table again to get things started again.

**Comment by osheroff** [comment]
it's just a `SELECT * from TABLE`.  There is currently no functionality to resume a bootstrap if maxwell crashes in the middle, but I'd love to see a PR around it.  You'd need to specify an ordering condition that gives it watermarks.

**Comment by tankchintan** [comment]
Ok. @osheroff any recommendation for handling bootstrapping table with 100 million records? Since it is a `SELECT * from TABLE` it might be a while before maxwell gets its hands on the actual records.

**Comment by osheroff** [comment]
it does a streaming query, doesn't buffer into ram.
