### ISSUE TITLE
ERROR AbstractBinlogParser - failed to parse binlog

### ISSUE THREAD

**Issue by w7089** [zendesk/maxwell#566]
Hi, i'm encountering the following problem

> [Class: com.google.code.or.binlog.impl.AbstractBinlogParser$Task] [Line: 267] ERROR AbstractBinlogParser - failed to parse binlog
> java.lang.RuntimeException: EOFPacket[packetMarker=254,warningCount=0,serverStatus=2]
> 	at com.google.code.or.binlog.impl.ReplicationBasedBinlogParser.readPacketMarker(ReplicationBasedBinlogParser.java:104) ~[open-replicator-1.6.0.jar:?]
> 	at com.google.code.or.binlog.impl.ReplicationBasedBinlogParser.doParse(ReplicationBasedBinlogParser.java:135) ~[open-replicator-1.6.0.jar:?]
> 	at com.google.code.or.binlog.impl.AbstractBinlogParser$Task.run(AbstractBinlogParser.java:263) [open-replicator-1.6.0.jar:?]
> 	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_121]

While running several instances of Maxwell configured with different _client_id_ values, while using Maxwell with MariaDB.
Adding replica_server_id haven't helped. 
Is there a solution or some configuration?
Thanks in advance.

**Comment by osheroff** [comment]
do you get this on all maxwell instances except one of them?  Possible that the maria-db code for duplicate detection is different than mysql's.  What exact version of mariaDB are you running?

**Comment by w7089** [comment]
Hi. I'm running 
_mysql  Ver 15.1 Distrib 10.1.21-MariaDB, for debian-linux-gnu (x86_64) using readline 5.2_
I guess on on all instances (we have 2) 

More detailed stacktrace is below

> 10:51:25,049 [THREAD ID=binlog-parser-1] [Class: com.google.code.or.binlog.impl.AbstractBinlogParser$Task] [Line: 267] ERROR AbstractBinlogParser - failed to parse binlog
> java.lang.RuntimeException: EOFPacket[packetMarker=254,warningCount=0,serverStatus=2]
> 	at com.google.code.or.binlog.impl.ReplicationBasedBinlogParser.readPacketMarker(ReplicationBasedBinlogParser.java:104) ~[open-replicator-1.6.0.jar:?]
> 	at com.google.code.or.binlog.impl.ReplicationBasedBinlogParser.doParse(ReplicationBasedBinlogParser.java:135) ~[open-replicator-1.6.0.jar:?]
> 	at com.google.code.or.binlog.impl.AbstractBinlogParser$Task.run(AbstractBinlogParser.java:263) [open-replicator-1.6.0.jar:?]
> 	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_121]
> 10:51:25,151 [THREAD ID=vert.x-worker-thread-0] [Class: com.zendesk.maxwell.replication.MaxwellReplicator] [Line: 111] WARN  MaxwellReplicator - open-replicator stopped at position mariadb-bin.000005:218741 -- restarting
> 10:51:25,171 [THREAD ID=vert.x-worker-thread-0] [Class: com.google.code.or.OpenReplicator] [Line: 330] INFO  OpenReplicator - starting replication at mariadb-bin.000005:218741
> 10:51:25,177 [THREAD ID=binlog-parser-1] [Class: com.google.code.or.binlog.impl.AbstractBinlogParser$Task] [Line: 267] ERROR AbstractBinlogParser - failed to parse binlog
> java.lang.RuntimeException: EOFPacket[packetMarker=254,warningCount=0,serverStatus=2]
> 	at com.google.code.or.binlog.impl.ReplicationBasedBinlogParser.readPacketMarker(ReplicationBasedBinlogParser.java:104) ~[open-replicator-1.6.0.jar:?]
> 	at com.google.code.or.binlog.impl.ReplicationBasedBinlogParser.doParse(ReplicationBasedBinlogParser.java:135) ~[open-replicator-1.6.0.jar:?]
> 	at com.google.code.or.binlog.impl.AbstractBinlogParser$Task.run(AbstractBinlogParser.java:263) [open-replicator-1.6.0.jar:?]
> 	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_121]
> 10:51:25,261 [THREAD ID=vert.x-worker-thread-1] [Class: com.zendesk.maxwell.replication.MaxwellReplicator] [Line: 111] WARN  MaxwellReplicator - open-replicator stopped at position mariadb-bin.000005:218741 -- restarting
> 10:51:25,300 [THREAD ID=vert.x-worker-thread-1] [Class: com.google.code.or.OpenReplicator] [Line: 330] INFO  OpenReplicator - starting replication at mariadb-bin.000005:218741
> 10:51:25,304 [THREAD ID=binlog-parser-2] [Class: com.google.code.or.binlog.impl.AbstractBinlogParser$Task] [Line: 267] ERROR AbstractBinlogParser - failed to parse binlog
> java.lang.RuntimeException: EOFPacket[packetMarker=254,warningCount=0,serverStatus=2]
> 	at com.google.code.or.binlog.impl.ReplicationBasedBinlogParser.readPacketMarker(ReplicationBasedBinlogParser.java:104) ~[open-replicator-1.6.0.jar:?]
> 	at com.google.code.or.binlog.impl.ReplicationBasedBinlogParser.doParse(ReplicationBasedBinlogParser.java:135) ~[open-replicator-1.6.0.jar:?]
> 	at com.google.code.or.binlog.impl.AbstractBinlogParser$Task.run(AbstractBinlogParser.java:263) [open-replicator-1.6.0.jar:?]
> 	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_121]
>

**Comment by w7089** [comment]
Was wondering, if my log is clear or you need smth. else?

**Comment by osheroff** [comment]
sorry for the lag.  to be clear, did you configure the two instances of maxwell with *different* `replica_server_id` flags?

**Comment by w7089** [comment]
Hi, it's ok ) Yes, we have tried different_server_id flags, the same error pops.
We would be happy to advance on this issue. If this is a bug, we'll provide any information needed. We also use Rabbitmq producer instead of Kafka and would be happy to donate it)

**Comment by osheroff** [comment]
yes, would love code donation.  I'll try to get mariaDB up and going to investigate this bug, there's probably some magic incantation I'm not doing properly and maria thinks the two different maxwell connections are duplicates.

cc @timbertson @liulikun

**Comment by w7089** [comment]
any news?

**Comment by w7089** [comment]
We have created pull request with RabbitMQ support. It's initial commit, hope it meets expectations. Would be happy to get your review and any updates on multithreading issue
