### ISSUE TITLE
maxwell 1.8.0 in a all-new mysql got Transport exception #1236

### ISSUE THREAD

**Issue by robertbee** [zendesk/maxwell#570]
14:02:43,928 INFO  OpenReplicator - starting replication at mysql-bin.000001:115966
14:02:43,969 ERROR MaxwellReplicator - Missing binlog 'mysql-bin.000001' on *.*.*.*
14:02:43,969 ERROR MaxwellReplicator - Transport exception #1236
com.google.code.or.net.TransportException: Misconfigured master - server_id was not set
	at com.google.code.or.OpenReplicator.dumpBinlog(OpenReplicator.java:343)
	at com.google.code.or.OpenReplicator.start(OpenReplicator.java:115)
	at com.zendesk.maxwell.replication.MaxwellReplicator.startReplicator(MaxwellReplicator.java:127)
	at com.zendesk.maxwell.replication.MaxwellReplicator.beforeStart(MaxwellReplicator.java:142)
	at com.zendesk.maxwell.util.RunLoopProcess.runLoop(RunLoopProcess.java:29)
	at com.zendesk.maxwell.Maxwell.start(Maxwell.java:181)
	at com.zendesk.maxwell.Maxwell.main(Maxwell.java:202)
14:02:43,972 INFO  Maxwell - starting shutdown

actually I check the my.cnf, there is ture the server_id did not set, but this is optional, if it not set, the default server_id is 0. also even I add 

server-id=1
log-bin=master
binlog_format=row

in my.cnf, the same exception got.
pls check it.

**Comment by robertbee** [comment]
add mysql version:
mysql> select @@version;
+-------------------------------------------+
| @@version                                 |
+-------------------------------------------+
| 5.6.33-enterprise-commercial-advanced-log |
+-------------------------------------------+
1 row in set (0.00 sec)

mysql>

**Comment by osheroff** [comment]
did you restart the server?  server-id 0 is not a supported maxwell configuration, and generally you should always give servers server-id.

**Comment by robertbee** [comment]
yes, change the my.cnf, the restart is needed. I restart , the same exception got.

**Comment by aditya-cap** [comment]
Ran into the same issue. On restart after running for a while, got this exception. The bin log was not present, but maxwell was still pointing to it.
