### ISSUE TITLE
data that is sent to kinesis is corrupted 

### ISSUE THREAD

**Issue by Liorba** [zendesk/maxwell#571]
Hey I'm using maxwell to read one table data  from rds  and send to kinesis stream
I'm using the latest docker version to run the process as follows:

```
sudo docker run -d osheroff/maxwell  -v `cd && pwd`/.aws:/root/.aws  sh -c 'cp /app/kinesis-producer-library.properties.example /app/kinesis-producer-library.properties && echo "Region=eu-west-1" >> /app/kinesis-producer-library.properties && bin/maxwell --user=maxwell --password=pass --host=host --producer=kinesis --kinesis_stream=stream-name --log_level info --include_tables=orders'
```

when I read the data from kinesis it seems that there extra characters that making the message not a valid Json

for example :

��db_name��{"database":"db_name","table":"table","type":"update","ts":1487753904,"xid":624618583,"commit":true,"data": {}}

you can see that the prefix ��db_name�� making the message corrupted

any idea what can be the problem?

**Comment by Liorba** [comment]
this happened due to an issue with kinesis producer aggregation  (see [here](https://github.com/awslabs/amazon-kinesis-producer/issues/80)

when I disable the option for aggregation in "kinesis-producer-library.properties" everything came back to normal...

**Comment by rhamnett** [comment]
I can confirm this issue still exists in 1.10.0 when aggregation is enabled.

**Comment by timbertson** [comment]
I'm not very familiar with kinesis, but from https://github.com/awslabs/amazon-kinesis-producer/blob/master/aggregation-format.md it sounds like this is intended behaviour - i.e it's not corrupted, it's protobuf. Sounds like you either need to disable aggregation, or use a consumer that will deaggregate events for you.

**Comment by rhamnett** [comment]
Thanks, looks like you're right - i'll consume it as a protobuf message
