### ISSUE TITLE
output_ddl option ignores include_dbs and appends zeros to timestamp

### ISSUE THREAD

**Issue by bmichaud** [zendesk/maxwell#575]
Maxwell 1.5.1
MySQL 5.6
Kafka 0.9.0.1

We are using the output_ddl option set to true, and we are consuming those messages on our back end data warehouse to capture schema changes. We have been using this feature since before it was merged into Maxwell, as @xmlking was working with our group and added the feature. However, this week, I realized that there are two defects with this feature:

(1) I am getting DDL messages for a database which lives on the same MySQL instance as the one we are replicating, but is not in our configured list of database names in the include_dbs option. Our DML messages are filtering properly, but not the DDL messages. (N.B. We do not use the exclude_dbs filter or the table fileters either.)
(2) The "ts" value in the JSON messages from DDL statements are being appended with three zeros to simulate a milliseconds epoch time stamp, which our source database does not give us. The DML messages have time stamp values like this: 1487428305, whereas the DDL messages look like this: 1487602450000

I will make downstream routing adjustments for this for the time being, as I do not have time to fix it right now. I am willing to take a stab at it next week or the next perhaps.

**Comment by osheroff** [comment]
We've got some code started around this issue.  Am starting another couple engineers on maxwell maintaining and this is their pilot issue

**Comment by bmichaud** [comment]
OK. sounds good. 

Additionally, I am not seeing any replication of **truncate table** statements either. I don't know if you would consider this related to the above or not. (DDL vs. DML)

**Comment by osheroff** [comment]
@bmichaud that's expected behavior; a `truncate table` statement is a DML statement, not a DDL statement and we just ignore it.

**Comment by bmichaud** [comment]
@osheroff I agree that it is a DML statement, but I disagree that it should be ignored in all cases. We, for example need to know when data gets deleted from the source database, and that statement effectively does a mass delete. Having that information would be necessary to clean up our downstream lambda database. Otherwise, all of those column values that existed in that table would be considered still there, when, in fact, they are not. Hopefully, no one will use it during the course of normal business operations in production, but, to automate the synchronization for non-production databases, it may be necessary.

Now, having said all that, I wonder if you meant that you ignore it in DDL replication, in which case I apologize.

**Comment by osheroff** [comment]
hmmm ok.  If you want to output a PR that outputs a `truncate` event I'd take it

**Comment by timbertson** [comment]
Fixes for the initial issues have now been merged (https://github.com/zendesk/maxwell/pull/585 and https://github.com/zendesk/maxwell/pull/578), so I'll close this. @bmichaud could you please open a separate PR/Issue for the truncate table event so we can track it separately?
