### ISSUE TITLE
Can it be 100 mysql instnace 1 maxwell?

### ISSUE THREAD

**Issue by saup007** [zendesk/maxwell#577]
Every mysql instance needs a maxwell's, 100 mysql instance, 100 maxwell?
Can it be 100 mysql instnace 1 maxwell ? 

bin/maxwell --user='root' --password='root' --host='dbaone' --port=3306 --producer=kafka --kafka.bootstrap.servers=dbathree:9092 --kafka_topic=maxwell3306

bin/maxwell --user='root' --password='root' --host='dbatwo' --port=3308 --producer=kafka --kafka.bootstrap.servers=dbathree:9092 --kafka_topic=maxwell3308

and so on

**Comment by osheroff** [comment]
yes, currently the model is 1 maxwell per 1 mysql.  I had had some plans to allow "configuration groups" at some point:

```
# config.properties

client_instances=db1,warehouse,db2
db1_host=dbaone
db1_producer=kafka
db1_include_tables=foo,/bar.*/

warehouse_host=datawarehouse
```

And then internally we'd thread it so that each 'client_instance' spawns off a new "main" thread.

but I never got around to it.  Would accept a good patch around this story.

**Comment by saup007** [comment]
Thank you, hope it arrives soon

**Comment by osheroff** [comment]
I'll be honest with ya @saup007,  it won't unless either some company (or my company) finds the need, and someone contributes source code to do it.  Just the way that open source works; I'm paid to ship code just like anybody and of course do some maxwell maintenance for the community, but it's hard to justify spending the few days on a feature for someone else.

Best way to ensure it's done soon?  Do it yourself!  Open a PR and contribute back.
