### ISSUE TITLE
Need partial database name in kafka topic name

### ISSUE THREAD

**Issue by HenryCaiHaiying** [zendesk/maxwell#579]
Currently kafka topic name can be generated using token, e.g. topic = zen_%{database}

However, we have database names like: zen_AAA_NNNNN where AAA represents a particular business use case and NNNNNN is the database shard, we want to generate topic name as zen_AAA (we don't want the shard number in topic name)

I think we need to enhance the database token with some regular expression.

One thing I was thinking is to express it using two config properties:
database_pattern = zen_(\w+)_(\w+)
topic = zen_%{database<1>} 

<1> means from matching group 1 which matches AAA in this case.

Would love to hear your opinions.

**Comment by HenryCaiHaiying** [comment]
Actually our use case is more complex than this, sometimes the database name is zenNNNN and it needs to be mapped to zen_default topic name.  Looks like I will have to specify multiple patterns:
database_pattern_match_1 = zen_(\w+)_(\w+)
database_pattern_apply_1 = zen_<1>      # use group 1 from the previous match regex
database_pattern_match_2 = zen_(\w+)
database_pattern_apply_2 = zen_default
topic = %{database}         # will replace database string with the database_pattern_apply_X, if match_1 matches we will use apply_1, otherwise move on to match_2 ...

If that proposal sounds too complex, maybe we expose MaxwellKafkaProducer.generateTopic(String topic, RowMap r) as an interface and allow different implementation plugin their own mapping code?

**Comment by osheroff** [comment]
Yeah that definitely sounds like a very very specific use case.  I'm thinking about two different methods for allowing arbitrary configure stuff like this.

The first is the path you mentioned; allowing a plugin interface.  

The second would be to allow a bit of groovy or JavaScript code to be allowed to run after we marshal to RowMap but before we hit the producer that allows this and other functionality like data scrubbing, field partitioning, etc.  not sure what the performance implications would be but it would be a great place to inject flexibility 

Thoughts?

**Comment by HenryCaiHaiying** [comment]
For scripting, java7 bundles with Rhino, Java8 bundles with Nashorn
https://docs.oracle.com/javase/8/docs/api/javax/script/ScriptEngine.html

In my case, I only need to generate a topic name from dbname/tableName, it can be a simple javascript to do that extraction, I think that should still be fast.  I am not sure whether I want to deal with the transformation of the whole RowMap, that might be slow.

**Comment by osheroff** [comment]
went around on this.  I think this feature is odd enough that I'd prefer to do the work do allow someone to write their own producer, and maybe load it up at runtime.  So if you specify `--producer=com.henry.KafkaProder`, that can load up the class from the classpath and call some kinda generic constructor on it.

**Comment by HenryCaiHaiying** [comment]
@osheroff I am not sure whether plugin my own 'producer' is a good idea, looks like there are quite a few hard-coded logic depending on whether producerType == kafka.

How about we just introduce an Interface: KafkaTopicGenerator

public interface KafkaTopicGenerator {
	public String generateTopic(String topic, RowMap r);
}

The default implementation would just be what you have in MaxwellkafkaProducerWorker.

**Comment by osheroff** [comment]
now possible with javascript filters.
