### ISSUE TITLE
Need an uncaughtExceptionHandler for threads

### ISSUE THREAD

**Issue by HenryCaiHaiying** [zendesk/maxwell#581]
Maxwell launched multiple threads and usually threads communicate with in-memory queue.  And many times you saw the thread's run loop was doing this:

	@Override
	public void run() {
		while ( true ) {
			try {
				RowMap row = queue.take();
				this.push(row);
			} catch ( Exception e ) {
				throw new RuntimeException(e);
			}
		}
	}

When the downstream thread died because of an exception, the upstream thread is not aware and will keep pushing data into the in-memory queue and it will spin-waiting when the queue is full.

I think this problem can be simply solved by adding the following uncaughtExceptionHandler in Maxwell main program:

Thread.setDefaultUncaughtExceptionHandler(new Thread.UncaughtExceptionHandler() {
                public void uncaughtException(Thread thread, Throwable exception) {
                    LOG.error("Thread {} failed", thread, exception);
                    System.exit(1);
                }
            };

Let me know what you think, I can quickly add this piece of code in a PR.

**Comment by HenryCaiHaiying** [comment]
@osheroff Let me know if you think that's the right fix, I can create a PR for that fix.

**Comment by timbertson** [comment]
Good catch! This is solved by #615 , it's a bit more complex but allows us to handle termination centrally in MaxwellContext rather than killing the process.

**Comment by HenryCaiHaiying** [comment]
Good to hear that.
