### ISSUE TITLE
jmx/monitoring support

### ISSUE THREAD

**Issue by HenryCaiHaiying** [zendesk/maxwell#582]
Currently there is not much insight into maxwell's running status (e.g. number of messages received from binlog, # of messages published to kafka, # of errors encountered, latency behind binlog).

I was thinking to add some monitoring into those stats.  Since the maxwell is a java program, the standard way of doing this is implementing some MBeans and expose them through jmx.

Let me know what you think.  I can work in this direction if you are fine with this general approach.

**Comment by osheroff** [comment]
Henry, check out https://github.com/zendesk/maxwell/pull/580

Maybe you can pitch in on that effort?

**Comment by HenryCaiHaiying** [comment]
I will take a look, thanks.

**Comment by HenryCaiHaiying** [comment]
Close this issue since it's tracked in  #580
