### ISSUE TITLE
Cannot generate tar.gz file anymore

### ISSUE THREAD

**Issue by HenryCaiHaiying** [zendesk/maxwell#586]
When we do local 'mvn package', I don't see the tar.gz file in target/ folder anymore.

Looks like the assembly file: src/main/assembly/assembly.xml is not referenced in pom.xml anymore, is this intentional?

**Comment by HenryCaiHaiying** [comment]
@osheroff looks like it was intentionally removed as part of this commit:
https://github.com/zendesk/maxwell/commit/6b6fbc641b3d4e5244aecf2bfc802a10fbafbb83#diff-600376dffeb79835ede4a0b285078036

How do we generate tar.gz if we are building from source?  We need all the dependent jars in libs/

**Comment by osheroff** [comment]
it is intentional.  please use `make package` instead.

**Comment by HenryCaiHaiying** [comment]
@osheroff OK. tried that, but got few errors.  Do I need to install/update ruby or other libraries?

build/maven_fetcher:59: syntax error, unexpected tIDENTIFIER, expecting tAMPER
...oup_id.split('.'), artifact_id, version)
                              ^
build/maven_fetcher:59: syntax error, unexpected ')', expecting '='

**Comment by osheroff** [comment]
yeah try ruby 2 at least

**Comment by HenryCaiHaiying** [comment]
ruby2 works, thanks.

By the way, what was the problem of using 'mvn package' do the assembly?
