### ISSUE TITLE
curiosity killed the cat

### ISSUE THREAD

**Issue by smferguson** [zendesk/maxwell#591]
how'd you pick the name 'maxwell'? 
(https://en.wikipedia.org/wiki/James_Clerk_Maxwell?)

**Comment by osheroff** [comment]
yes, in a round about way.  Reading "The Cyberiad" by Stanislaw Lem was a very early attraction of mine into areas of thought, and he talks about maxwell's demon in it.  Highly recommended.  And then I suppose I just always liked called things "daemons", so "maxwell's daemon" was born.

**Comment by smferguson** [comment]
cool. thanks. i'm an addict of backstory like this.
