### ISSUE TITLE
change maxwell default charset=latin1 to utf8

### ISSUE THREAD

**Issue by sreev** [zendesk/maxwell#592]
with all default settings,

` 

mysql> select * from maxwell.databases;

+----+-----------+---------+---------+
| id | schema_id | name    | charset |
+----+-----------+---------+---------+
|  1 |         1 | maxwell | latin1  

`

**Comment by saup007** [comment]
`localhost.test>show create database maxwell;
+----------+------------------------------------------------------------------+
| Database | Create Database                                                  |
+----------+------------------------------------------------------------------+
| maxwell  | CREATE DATABASE `maxwell` /*!40100 DEFAULT CHARACTER SET utf8 */ |
+----------+------------------------------------------------------------------+
1 row in set (0.00 sec)

`
depend on mysql configuration.

**Comment by sreev** [comment]
interesting. thankyou, 

still, it may be good idea 'maxwell' uses utf8 despite the settings of mysql installations ?

**Comment by osheroff** [comment]
I'd accept a PR that setup the default charset for the maxwell database to utf8
