### ISSUE TITLE
maxwell exit 

### ISSUE THREAD

**Issue by worldup** [zendesk/maxwell#594]
hi,i have got so many warning info 
 WARN  BinlogConnectorReplicator - null -- restarting
and  at  last java.io.EOFException was throwed, the main program exited.
i wanna know   the reason.
![image](https://cloud.githubusercontent.com/assets/1046177/23839485/66eed326-07d9-11e7-8962-4d6b9d2e1397.png)

**Comment by worldup** [comment]
so many WARN BinlogConnectorReplicator - null -- restarting 
because mysql-bin.002914  is not exsited ,my mysql server binlog just saved for 1 days.
can  maxwell   recalculate position   when the binlog file  lost?

**Comment by osheroff** [comment]
the proper thing to do when you've lost the binlog position is to perform `drop database maxwell`, and it'll restart.  I'll leave this bug open to see how maxwell w/ binlog-connector reacts to a missing binlog.
