### ISSUE TITLE
Discarding old rows

### ISSUE THREAD

**Issue by borgmark** [zendesk/maxwell#596]
Using Maxwell, how would you go about situations where an alter is required on a huge table and a temporary table (rename old/new and insert old-> new) is used. Would maxwell re-process the historical information being inserted? Is there a way to filter this out?

**Comment by osheroff** [comment]
we use percona-toolkit for big alters and our maxwell config has `exclude_tables=/.*_new$/`

**Comment by borgmark** [comment]
Thanks, much appreciated !! ... exclude_tables=/.*_new$/ filter will do the job for us.
