### ISSUE TITLE
outdated tags on docker hub

### ISSUE THREAD

**Issue by abacaphiliac** [zendesk/maxwell#601]
hi @osheroff ,

i was wondering how you would feel about publishing tags for recent versions of maxwell? i'm not sure what `latest` is, but it's a couple of months old, and the oldest non-`latest` tag is `1.5.1`.

thanks in advance for the feedback : )

**Comment by abacaphiliac** [comment]
oh, for reference, i'm looking at the tags here:
https://hub.docker.com/r/osheroff/maxwell/tags/

**Comment by saidimu** [comment]
@abacaphiliac I cloned this repo and pushed the latest Docker images to https://hub.docker.com/r/saidimu/maxwell/tags/

Might come in handly until @osheroff updates his repo.

**Comment by liulikun** [comment]
Zendesk has just published the new docker image built from the latest code: https://hub.docker.com/r/zendesk/maxwell/, and docker hub will auto build the latest image in the future.
