### ISSUE TITLE
can't get mysql binlog data Output to the screen

### ISSUE THREAD

**Issue by xlingit** [zendesk/maxwell#603]
in use:
1)maxwell version **1.8.1**
2) kafka cluster version  **kafka_2.10-0.8.2.2**

the maxwell started, when i insert into table data ,but the  screen output is null
sh start-stdout.sh 
11:12:29,737 INFO  Maxwell - Maxwell v1.8.1 is booting (StdoutProducer), starting at BinlogPosition[master.000002:4226]
11:12:29,742 DEBUG MysqlPositionStore - Writing binlog position to maxwell.positions: BinlogPosition[master.000002:4226], last heartbeat read: null
11:12:29,905 DEBUG MysqlSavedSchema - looking to restore schema at target position BinlogPosition[master.000002:4226]
11:12:29,906 INFO  MysqlSavedSchema - Restoring schema id 1 (last modified at BinlogPosition[master.000002:4226])
11:12:29,907 DEBUG MysqlSavedSchema - Restoring full schema
11:12:29,917 DEBUG MysqlSavedSchema - Restoring database maxwell...
11:12:29,942 DEBUG MysqlSavedSchema - Restoring database mysql...
11:12:29,986 DEBUG MysqlSavedSchema - Restoring database test...
11:12:29,986 DEBUG MysqlSavedSchema - Restored all databases
11:12:30,007 DEBUG TransportImpl - connecting to host: 172.16.1.162, port: 3306
11:12:30,044 DEBUG TransportImpl - connected to host: 172.16.1.162, port: 3306, context: AbstractTransport.Context[threadId=163,scramble=G4kCL4\Vx{"0lS7[By[=,protocolVersion=10,serverHost=172.16.1.162,serverPort=3306,serverStatus=2,serverCollation=8,serverVersion=5.1.73-log,serverCapabilities=63487]
11:12:30,044 DEBUG AuthenticatorImpl - start to login, user: maxwell, host: 172.16.1.162, port: 3306
11:12:30,051 DEBUG AuthenticatorImpl - login successfully, user: maxwell, detail: OKPacket[packetMarker=0,affectedRows=0,insertId=0,serverStatus=2,warningCount=0,message=<null>]
11:12:30,068 INFO  OpenReplicator - starting replication at master.000002:4226
11:12:30,744 DEBUG MysqlPositionStore - writing heartbeat: 1490325150743 (last heartbeat written: 1490325141833)

[root@pe-test-2 etc]# **cat my.cnf** 
[mysqld]
datadir=/var/lib/mysql
socket=/var/lib/mysql/mysql.sock
user=root
symbolic-links=0
server-id=1
log-bin=master
binlog_format=row
log-slave-updates=ON
#enforce-gtid-consistency=true
[mysqld_safe]
log-error=/var/log/mysqld.log
pid-file=/var/run/mysqld/mysqld.pid

mysql> **show binlog events;**
+---------------+-----+-------------+-----------+-------------+---------------------------------------+
| Log_name      | Pos | Event_type  | Server_id | End_log_pos | Info                                  |
+---------------+-----+-------------+-----------+-------------+---------------------------------------+
| master.000001 |   4 | Format_desc |         1 |         106 | Server ver: 5.1.73-log, Binlog ver: 4 |
| master.000001 | 106 | Stop        |         1 |         125 |                                       |
+---------------+-----+-------------+-----------+-------------+---------------------------------------+
2 rows in set (0.00 sec)

mysql> **show binary logs;**
+---------------+-----------+
| Log_name      | File_size |
+---------------+-----------+
| master.000001 |       125 |
| master.000002 |     45660 |
+---------------+-----------+

**Comment by osheroff** [comment]
maxwell will start at the tail of the binlogs, not the start.  you can change this with the `--initial_position` flag if you like
