### ISSUE TITLE
compilation fails with antlr 4.6

### ISSUE THREAD

**Issue by sreev** [zendesk/maxwell#606]
`

$ make clean all
rm -f  target/.java target/.java-test
rm -rf target/classes
rm -rf target/generated-sources
rm -f  target/*.jar
java -cp target/dependency-antlr/antlr4-runtime-4.6.jar:target/dependency-antlr/antlr-runtime-3.5.2.jar:target/dependency-antlr/ST4-4.0.8.jar:target/dependency-antlr/org.abego.treelayout.core-1.0.3.jar:target/dependency-antlr/javax.json-1.0.4.jar:target/dependency-antlr/junit-4.10.jar:target/dependency-antlr/hamcrest-core-1.1.jar:target/dependency-antlr/antlr4-4.6.jar org.antlr.v4.Tool -package com.zendesk.maxwell.schema.ddl -lib src/main/antlr4/imports -o target/generated-sources src/main/antlr4/com/zendesk/maxwell/schema/ddl/mysql.g4
error(174): mysql.g4:73:15: string literals and sets cannot be empty: [:-+]
make: *** [target/generated-sources/src/main/antlr4/com/zendesk/maxwell/schema/ddl/mysqlBaseListener.java] Error 1

`

**Comment by sreev** [comment]
`
$ mvn clean install
[INFO] Scanning for projects...
[INFO] Inspecting build with total of 1 modules...
[INFO] Installing Nexus Staging features:
[INFO]   ... total of 1 executions of maven-deploy-plugin replaced with nexus-staging-maven-plugin
[INFO]
[INFO] ------------------------------------------------------------------------
[INFO] Building maxwell 1.8.1
[INFO] ------------------------------------------------------------------------
[INFO]
[INFO] --- maven-clean-plugin:2.5:clean (default-clean) @ maxwell ---
[INFO] Deleting /maxwell/target
[INFO]
[INFO] --- antlr4-maven-plugin:4.6:antlr4 (antlr) @ maxwell ---
[INFO] ANTLR 4: Processing source directory /maxwell/src/main/antlr4
[INFO] Processing grammar: com/zendesk/maxwell/schema/ddl/mysql.g4
[ERROR] error(174): com/zendesk/maxwell/schema/ddl/mysql.g4:73:15: string literals and sets cannot be empty: [:-+]
[ERROR] /maxwell/com/zendesk/maxwell/schema/ddl/mysql.g4 [73:15]: string literals and sets cannot be empty: [:-+]
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 2.183 s
[INFO] Finished at: 2017-03-26T16:47:39-07:00
[INFO] Final Memory: 26M/331M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.antlr:antlr4-maven-plugin:4.6:antlr4 (antlr) on project maxwell: ANTLR 4 caught 1 build errors. -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException

`

**Comment by osheroff** [comment]
again, thanks for the heads-up @sreev but there's no *priority* to upgrade to antlr 4.6 so it'd not really an issue.  if you'd like to fix the issue, feel free to open a PR.   thanks!
