### ISSUE TITLE
cnf on mysql-connector-java upgrade to 6.x

### ISSUE THREAD

**Issue by sreev** [zendesk/maxwell#607]
upgrading mysql-connector-java version from 5.1.x to 6.x fails compilation with classnotfound error.

`

MySQLIntegrityConstraintViolationException cannot be resolved to a type	MysqlPositionStore.java	/maxwell/src/main/java/com/zendesk/maxwell/schema	line 98	

MySQLIntegrityConstraintViolationException cannot be resolved to a type	MysqlSavedSchema.java	/maxwell/src/main/java/com/zendesk/maxwell/schema	line 121

`

**Comment by osheroff** [comment]
please open a PR solving the issue rather than an issue, thanks.
