### ISSUE TITLE
detach hard tied logging

### ISSUE THREAD

**Issue by sreev** [zendesk/maxwell#608]
logging dependencies:

`

com.djdch.log4j:log4j-staticshutdown
org.apache.logging.log4j:log4j-core
org.apache.logging.log4j:log4j-slf4j-impl
org.slf4j:jul-to-slf4j

`

Move to implementation independent: slf4j

Test with adding runtime dependency: logback

This results in removing {{log_level}} param.
And log level control goes to the respective runtime log framework and its specific configuration.
(eg. for logback, it is logback.xml)
A package level log level setting and a configurable log line pattern are among the many advantages in doing this.

**Comment by osheroff** [comment]
no i would hate to lose being able to easily setup the log_level.  I think this would be an ok thing to do when using maxwell-as-a-jar, but I'd probably decline PRs that removed the log-level parameter.
