### ISSUE TITLE
message ordering on kafka side

### ISSUE THREAD

**Issue by HenryCaiHaiying** [zendesk/maxwell#609]
It looks like maxwell are using AsyncProducer, this has better performance comparing to Sync.  But the message ordering on kafka side would be undeterministic.  For the following two commits:
    1) update table set A = 1 where id = 1;
    2) update table set A = 2 where id = 1;

My downstream will see commit 1 show up later than commit 2.

How do we deal with this situation?

**Comment by liulikun** [comment]
From my understanding, it will only be indeterministic if the commit 1 is failed and retried. So if you need absolute ordering, you can disable `retries` in kafka?

**Comment by osheroff** [comment]
@liulikun is correct ; the async producer will return to the caller before the message is sent, but all messages for a topic-partition are sent over a single TCP stream and ordering is guaranteed (except in the case of retries).

**Comment by HenryCaiHaiying** [comment]
@liulikun @osheroff I think we actually need to set 'retries' bigger than 0 to have kafka retries (instead of having application retries) on error case, see the following discussion:
https://groups.google.com/forum/#!topic/kafka-clients/lWlRRc5JNmg

And also look at the setting in kafka's MirrorMaker code.

**Comment by liulikun** [comment]
If you need to enable `retries`, you can set `max.in.flight.requests.per.connection` to 1 to maintain the ordering, it's mentioned in the google forum, also here: http://docs.confluent.io/3.1.2/clients/producer.html, though I think it might impact the performance. Do you have a way to reproduce this scenario?

**Comment by HenryCaiHaiying** [comment]
Yes, we will also set the max.in.flight.requests.per.connection to 1.

I think the performance should be fine.  We have used MirrorMaker before
with the default setting (max.in.flight.requests.per.connection = 1), it
can keep up with the throughput without much problem.

**Comment by dbapower** [comment]
Multiple mysql Instances +Multiple maxwell Instances + only one kafka topic with more than one partition.
is the kafka.retries=0 or kafka.max.in.flight.requests.per.connection=1 can guarantee message order?
It's mentioned in here:Kafka only provides a total order over records within a partition, not between different partitions in a topic:
[http://kafka.apache.org/0110/documentation.html](url)
