### ISSUE TITLE
RDS to Kinesis encode problem

### ISSUE THREAD

**Issue by carlos-eduardo-gb** [zendesk/maxwell#610]
We are capturing the events from a mysql base with maxwell and sending to kinesis as a producer. However some events are with encoding problem and when we try to decode base64 we have invalid charsets like the example below:

```
u'\n\x05metal\x1a\x01\x08\x00\x1a\x01{"database":"metal","table":"recommendation","type":"insert"

\x1a\x01\x08\x00\x1a\x01
```
The data value comes correctly, but the values out of it come with error.

Any suggestion for this problem?

**Comment by liulikun** [comment]
How did you decode the message? The message is UTF-8 encoded.

**Comment by carlos-eduardo-gb** [comment]
Hi, i'm using an AWS Lambda function to get the stream data from kinesis, so the code is like this:

```
for record in event['Records']:
        payload = json.loads(base64.b64decode(record['kinesis']['data']))
        print("Decoded payload: " + json.dumps(payload))
```

**Comment by liulikun** [comment]
base64 decoding seems wrong. Can you just try `payload = json.loads(record['kinesis']['data'])`?

**Comment by carlos-eduardo-gb** [comment]
I can try, but the data field is a base64 message like this:

* just  a example

`84mawgoFYmx1ZXMamAIIABqTAnsiZGF0YWJhc2UiOiJibHVlcyIsInRhYmxlIjoiYWRzIiwidHlwZSI6Imluc2VydCIsInRzIjoxNDkwODI3NDgyLCJ4aWQiOjI1MzI3Njg1OSwiY29tbWl0Ijp0cnVlLCJkYXRhIjp7ImlkIjoxMjk1OTgyOTQsImFkX2lkIjoiNzAwMTBjNTYtNDc0Zi00ZjhlLWFiY2UtNjcwYjE3Mjg2N2YwIiwidXNlcl9pZCI6NzU1Njc4NCwiY3JlYX=`

**Comment by liulikun** [comment]
I'm not using Kinesis, so I'm not familiar with that part. It seems the messages is base64 encoded, you do need base64 decoding then. Did you set `kinesis_md5_keys` to true? Is the beginning part of message the message key?

**Comment by carlos-eduardo-gb** [comment]
kinesis_md5_keys in config is a new information for me, i will try it and return with answers (i hope). Thanks @liulikun .

**Comment by carlos-eduardo-gb** [comment]
Hi @liulikun problem solved.

## Solution

I need to add a project called `aws_kinesis_agg` the final code is:
```
from __future__ import print_function

from aws_kinesis_agg.deaggregator import deaggregate_records
import base64
import json

def lambda_handler(event, context):
    
    raw_kinesis_records = event['Records']
    
    #Deaggregate all records in one call
    user_records = deaggregate_records(raw_kinesis_records)
    
    #Iterate through deaggregated records
    for record in user_records:        
        
        # Kinesis data in Python Lambdas is base64 encoded
        payload = base64.b64decode(record['kinesis']['data'])
        print("Decoded payload: " + json.dumps(payload))
        #TODO: Process each record
    
    return 'Successfully processed {} records.'.format(len(user_records))
```
With this i can parse correctly the data returned by Kinesis, thanks and I hope this help another users too.

**Comment by liulikun** [comment]
Nice one! Thanks for the update.
