### ISSUE TITLE
Broker errors can cause message loss

### ISSUE THREAD

**Issue by nzwalker** [zendesk/maxwell#614]
Hey folks,

Noticed a problem with the async callback completer in 

https://github.com/zendesk/maxwell/blob/master/src/main/java/com/zendesk/maxwell/producer/MaxwellKafkaProducer.java#L54

In particular, an exception thrown by Kafka causes the message to be marked as completed. It turns out the producer API can throw exceptions during weird network partitions or broker issues - which is not handled correctly by the Java producer library.

In our case we require Maxwell outputs to be ultra durable, so I've patched it by causing an exception to crash the producer and deliberately restart Maxwell. Its pretty hacky:

```java
public class MaxwellKafkaProducer extends AbstractProducer {
	private final ArrayBlockingQueue<RowMap> queue;
	private final MaxwellKafkaProducerWorker worker;
	private Exception lastException;

	public MaxwellKafkaProducer(MaxwellContext context, Properties kafkaProperties, String kafkaTopic) {
		super(context);
		this.queue = new ArrayBlockingQueue<>(100);
		this.worker = new MaxwellKafkaProducerWorker(this, context, kafkaProperties, kafkaTopic, this.queue);
		new Thread(this.worker, "maxwell-kafka-worker").start();

	}

	public synchronized void stop(Exception e) {
		this.lastException = e;
	}

	public synchronized Exception getLastException() {
		return this.lastException;
	}

	@Override
	public void push(RowMap r) throws Exception {
		Exception e = this.getLastException();
		if (e != null) {
			throw e;
		}

		this.queue.put(r);
	}
}
```

And in the callback:

```java
@Override
	public void onCompletion(RecordMetadata md, Exception e) {
		if ( e != null ) {
			// We've seen some kind of Kafka exception
			// Since we want producing to be ultra-durable, we cannot mark this message as completed
			// The only safe thing to do is to stop processing any new messages and exit!
			LOGGER.error(e.getClass().getSimpleName() + " @ " + position + " -- " + key);
			LOGGER.error(e.getLocalizedMessage());
			if ( e instanceof RecordTooLargeException ) {
				LOGGER.error("Considering raising max.request.size broker-side.");
			}

			this.producer.stop(e);
		} else {
			if ( LOGGER.isDebugEnabled()) {
				LOGGER.debug("->  key:" + key + ", partition:" +md.partition() + ", offset:" + md.offset());
				LOGGER.debug("   " + this.json);
				LOGGER.debug("   " + position);
				LOGGER.debug("");
			}
			cc.markCompleted();
		}
	}
```

**Comment by osheroff** [comment]
sorry I'm late to the party on this one (esp after tim started code), but the more-or-less correct thing to do here is to set kafka's retries to something like 100,000 ; in almost all cases that will get the internal kafka producer to retry failed messages instead of bubbling them back to maxwell.  The problem with the let-it-crash approach is that then there's no way anyone can tune maxwell's durability -- it only allows for 100% durable delivery, which may or may not be what folks actually want.  I think.

most common issues that seem to arise are not-leader-for-partition exceptions and the like.

**Comment by nzwalker** [comment]
Hey @osheroff, thats exactly what I thought at first, because I had already set retries to 2147483646, which I had hoped would cause the producer library to retry in the face of temporary errors. The particular exception I saw the most of during this failure mode was of the variety:

```
23:30:14,681 ERROR MaxwellKafkaProducer - TimeoutException @ BinlogPosition[mysql-bin-changelog.031148:232542] -- {<snip>}
```

Our failure mode that caused the original issue was memory pressure on the brokers, which triggered a cascading failure across the entire cluster + constant ISR shrinks/expands below the min ISR.

It's possible that there is some setting in the producer lib that I need to set as well as retries, but I've been unable to find any thus far. My full config is:

```
kafka.max.request.size=10000000 
kafka.max.block.ms=6000000
kafka.buffer.memory=3355443 
kafka.block.on.buffer.full=true 
kafka.compression.type=gzip 
kafka.metadata.fetch.timeout.ms=120000 
kafka.timeout.ms=600000 
kafka.max.in.flight.requests.per.connection=1 
kafka.acks=all
kafka.retries=2147483646
```

**Comment by osheroff** [comment]
hmmm, no, blah.  the Kafka producer library will catch and retry *most* errors (especially network issues, or protocol-level errors), but stuff like this where arbitrary stuff times out still just gets thrown back at the producer I guess.  Maxwell didn't dump a bigger stack trace there, did it?

**Comment by Anmol-Sharma** [comment]
has this issue been fixed?
I have been getting the same timeout exception. Continuosly
and my config file parameters are similar to those mentioned ^ above by @nzwalker

**Comment by timbertson** [comment]
Apologies for not updating this issue sooner. In [v1.10.1](https://github.com/zendesk/maxwell/releases/tag/v1.10.1) we added an `ignore_producer_error` which will terminate maxwwell on an error like this instead of marking it as complete. The main difference with the patch mentioned above is that it still logs-and-continues on `RecordTooLargeException`, since that exception is not going to go away if you restart.
