### ISSUE TITLE
V1.8.2 - Couldn't find class 'mysqlBaseListener'

### ISSUE THREAD

**Issue by ravi-data-science** [zendesk/maxwell#617]
Cloned into latest version (v 1.8.2) and found that there is a compilation error !!

Package - com.zendesk.maxwell.schema.ddl
com.zendesk.maxwell.schema.ddl.MysqlParserListener extends mysqlBaseListener

1) Couldn't find class 'mysqlBaseListener
2) This import is not valid!!
import com.zendesk.maxwell.schema.ddl.mysqlParser.*;

**Comment by osheroff** [comment]
Doh, release must have gone bad.  Will fix when back from puppet show.

**Comment by osheroff** [comment]
errr, is this a problem with the tarball or with a git clone?

**Comment by relucant1** [comment]
with a git clone.

**Comment by osheroff** [comment]
and how are you compiling it?

**Comment by osheroff** [comment]
can't repro.  if you have a repro here feel free to reopen.

**Comment by yhqs540** [comment]
If you just clone this into IntelliJ to compile with Maven. It will throw this error. It seems that it depends on some generated files.
