### ISSUE TITLE
mysql 5.7 should probably turn on `--binlog_connector`

### ISSUE THREAD

**Issue by abhijitkumartech** [zendesk/maxwell#619]
v1.7.0 onwards mysql 'json' data support was added. However, I am getting this exception being thrown from oper-replicator for columns with 'json' data type.

java.lang.RuntimeException: assertion failed, **unknown column type: 245**
	at com.google.code.or.binlog.impl.parser.AbstractRowEventParser.parseRow(AbstractRowEventParser.java:186) ~[classes/:?]
	at com.google.code.or.binlog.impl.parser.UpdateRowsEventV2Parser.parseRows(UpdateRowsEventV2Parser.java:78) ~[classes/:?]
	at com.google.code.or.binlog.impl.parser.UpdateRowsEventV2Parser.parse(UpdateRowsEventV2Parser.java:67) ~[classes/:?]
	at com.google.code.or.binlog.impl.ReplicationBasedBinlogParser.doParse(ReplicationBasedBinlogParser.java:147) ~[classes/:?]
	at com.google.code.or.binlog.impl.AbstractBinlogParser$Task.run(AbstractBinlogParser.java:256) [classes/:?]

Is there anything that I am missing here ?

**Comment by osheroff** [comment]
Yeah you need to pass --binlog_connector (or something, I forget exactly what) in order to enable JSON support.  We should really do a patch that turns that library on by default when MySQL 5.7 is detected.  Maybe @tcuthbertson could help!

**Comment by abhijitkumartech** [comment]
Thanks @osheroff !!
@timbertson , could you or anyone else please help.

**Comment by osheroff** [comment]
@timbertson are we running with binlog_connector on in production at zendesk?  I forget.  If so we can just switch to that codepath by default in the next release, and then rip out the old code.

**Comment by timbertson** [comment]
We're not running binlog_connector everywhere yet. We'd prefer to make it default and then drop it in a version or two, rather than basing that decision off your mysql version. So yep, this is inconvenient to have to specify `--binlog_connector` for the moment, but it should be somewhat temporary.

**Comment by anandaverma** [comment]
by enabling `--binlog_connector` parsing stopped and binlog position is not moving. Getting below warn - 
```
maxwell_1  | 12:05:56,608 WARN  BinlogConnectorReplicator - replicator stopped at position: mysql-bin-changelog.000021:193465 -- restarting
maxwell_1  | 12:05:56,653 INFO  BinaryLogClient - Connected to proddbmumbai.cwlfcif9i1tn.ap-south-1.rds.amazonaws.com:3306 at mysql-bin-changelog.000021/193465 (sid:6379, cid:5746)
maxwell_1  | 12:05:56,792 WARN  BinlogConnectorReplicator - replicator stopped at position: mysql-bin-changelog.000021:193465 -- restarting
maxwell_1  | 12:05:56,836 INFO  BinaryLogClient - Connected to proddbmumbai.cwlfcif9i1tn.ap-south-1.rds.amazonaws.com:3306 at mysql-bin-changelog.000021/193465 (sid:6379, cid:5747)
maxwell_1  | 12:05:56,976 WARN  BinlogConnectorReplicator - replicator stopped at position: mysql-bin-changelog.000021:193465 -- restarting
maxwell_1  | 12:05:57,021 INFO  BinaryLogClient - Connected to proddbmumbai.cwlfcif9i1tn.ap-south-1.rds.amazonaws.com:3306 at mysql-bin-changelog.000021/193465 (sid:6379, cid:5748)
maxwell_1  | 12:05:57,160 WARN  BinlogConnectorReplicator - replicator stopped at position: mysql-bin-changelog.000021:193465 -- restarting
```

**Comment by timbertson** [comment]
`binlog_connector` is finally the One True Connector in 1.10.5, closing.
