### ISSUE TITLE
lastHeartbeat checks in BinlogPosition cause blowups in RDS

### ISSUE THREAD

**Issue by smferguson** [zendesk/maxwell#636]
I think the changes in https://github.com/zendesk/maxwell/pull/630 break maxwell in the case where we're running in RDS and receive a RDS heartbeat.
Following the codepath  starting at https://github.com/zendesk/maxwell/blob/master/src/main/java/com/zendesk/maxwell/replication/MaxwellReplicator.java#L265 ends in calling the constructor here: https://github.com/zendesk/maxwell/blob/master/src/main/java/com/zendesk/maxwell/replication/BinlogPosition.java#L43 which results in the lastHeartbeat check failing here https://github.com/zendesk/maxwell/blob/master/src/main/java/com/zendesk/maxwell/replication/BinlogPosition.java#L88.

Maybe I'm just missing something?

edit:
I should note that maxwell doesn't die completely (at least in my debugger), but it does stacktrace and look pretty angry:

> 15:04:21,704 INFO  TaskManager - stopped all tasks
> Exception in thread "main" java.lang.AssertionError: BinlogPosition.lastHeartbeat must be set
> 	at com.zendesk.maxwell.replication.BinlogPosition.requireLastHeartbeat(BinlogPosition.java:90)
> 	at com.zendesk.maxwell.row.HeartbeatRowMap.<init>(HeartbeatRowMap.java:15)
> 	at com.zendesk.maxwell.replication.AbstractReplicator.processRDSHeartbeatInsertEvent(AbstractReplicator.java:95)
> 	at com.zendesk.maxwell.replication.MaxwellReplicator.processRDSHeartbeatInsertEvent(MaxwellReplicator.java:377)
> 	at com.zendesk.maxwell.replication.MaxwellReplicator.getTransactionRows(MaxwellReplicator.java:265)
> 	at com.zendesk.maxwell.replication.MaxwellReplicator.getRow(MaxwellReplicator.java:337)
> 	at com.zendesk.maxwell.replication.AbstractReplicator.work(AbstractReplicator.java:141)
> 	at com.zendesk.maxwell.util.RunLoopProcess.runLoop(RunLoopProcess.java:30)
> 	at com.zendesk.maxwell.Maxwell.startInner(Maxwell.java:212)
> 	at com.zendesk.maxwell.Maxwell.start(Maxwell.java:151)
> 	at com.zendesk.maxwell.Maxwell.main(Maxwell.java:236)

**Comment by timbertson** [comment]
Sorry @smferguson , you're right - we don't hit this code path ourselves, and it's not covered by tests. I tried to emulate using plain ol' mysql but couldn't trigger this code path.

The trouble is, since it's a SQL query instead of a row event it's not easy to find the actual heartbeat value to store it with the position. For the purpose of schema resolution it may be acceptable to just construct the HeartbeatRowMap with:

```
HeartbeatRowMap.valueOf(row.getDatabase(), row.getPosition(), this.lastHeartbeatRead);
```

I.e. attach the last (maxwell) heartbeat position to this RDS heartbeat. That could definitely get confusing though, and there may still be a corner case if we haven't yet seen any maxwell heartbeats (lastHeartbeatRead = null).

It also may be OK to relax the requirement for a heartbeat value in RDS, because the issue fixed by #630 will probably never happen in RDS. But determining when it's safe to do that could get messy too.

As for maxwell terminating, it should fully exit for a fatal exception like this - which threads remain running in your debugger?

**Comment by smferguson** [comment]
The remaining thread is the metrics http server.

The heartbeat event does have a header that contains a timestamp, but I don't know if using that is better/worse than the other options.

**Comment by liulikun** [comment]
I think we don't have to process RDS heartbeat specifically if we keep maxwell own heartbeat going every second regardless. Right now, maxwell own heartbeat stops if the db is quiet (https://github.com/zendesk/maxwell/blob/8ea9f7fc3a7c570aef58d089a893458fb1c942bd/src/main/java/com/zendesk/maxwell/schema/PositionStoreThread.java#L79). We can drop this method https://github.com/zendesk/maxwell/blob/8ea9f7fc3a7c570aef58d089a893458fb1c942bd/src/main/java/com/zendesk/maxwell/schema/PositionStoreThread.java#L72-L83 and make `shouldHeartbeat` to true always, and revert this PR https://github.com/zendesk/maxwell/pull/523, that should solve the original issue?

**Comment by smferguson** [comment]
@liulikun if we don't process RDS heartbeats will maxwell still update its binlog position when a RDS heartbeat happens? That was the main issue.
A little more background... RDS has a max binlog retention of 7 days. Maxwell wasn't updating its binlog position for RDS heartbeats prior to https://github.com/zendesk/maxwell/pull/523. The result was that for an idle system when an actual event came through maxwell would fail b/c it didn't know what the current binlog - the one it was referring to had been rotated out. It's a bit of an extreme case, systems that won't write for X days are rare to say the least, but it is possible and we did run into it in our integration env in Dec.
I'll add that I don't _think_ we'll ever see it again, but if we do it'll cause an uproar (ugh).

**Comment by liulikun** [comment]
@smferguson where did you create `maxwell` database? If it resides within the same cluster of your business database, and maxwell heartbeat keeps beeping 1 per second (maxwell will advance binlog position on it's own heartbeats), that'll keep the cluster alive?

**Comment by smferguson** [comment]
@liulikun it's always in the same cluster as the biz db. Given that it sounds like maxwell's heartbeats will do the right thing.
