### ISSUE TITLE
create and expose general interface(s) for metrics

### ISSUE THREAD

**Issue by sreev** [zendesk/maxwell#637]
create general interface(s) for maxwell metrics

so, any one can implement this for a specific consumer(s). eg. graphite

similar to:
Apache Storm / org.apache.storm.metric.api.IMetricsConsumer

eg implementation that sends metrics to graphite server :
Verisign / storm-graphite

**Comment by sreev** [comment]
@osheroff 
what is the best to reach you ?

**Comment by osheroff** [comment]
I'm pretty sure the metrics solution we have, "dropwizard metrics" (used to be yammer metrics), should be pretty adaptable to building custom plugins.  The only problem is that they don't have a standard path for setting up stat-emitter configuration, so you end up having to write custom code inside of maxwell to support each sink.  

@timbertson this might be another avenue to consider in terms of maxwell-consumed-as-a-jar; the ability to pass an instance of a dropwizard `MetricsReporter` (is that the name?) might be nice.

**Comment by sreev** [comment]
@osheroff @timbertson 
it is, com.codahale.metrics.ScheduledReporter.
i found, com.codahale.metrics.GraphiteReporter.
will check providing 'graphite' as an option, like 'slf4j, http'.
i am also checking using 'http' and some collection agent writing to graphite as well.

let me know your approaches, as well.

**Comment by sreev** [comment]
proposed the following: @osheroff @timbertson 
1.
general interface for metrics. similar to Apache Storm's org.apache.storm.metric.api.IMetricsConsumer with an implementation that writes to graphite eg. verisign's storm-graphite.

the implementation is totally outside the maxwell and keeps it clean.  gives complete flexibility for users to implement their own consumers.

2.
add com.codahale.metrics.GraphiteReporter.  then, provide an option for metrics_type=graphite.
completely tied into maxwell.

3.
use metrics_type=http. and use processes like 'collectd' that makes calls to the /metrics and stores responses to the graphite. periodically.
this solution ties together into maxwell and enforcing to start a server on the maxwell host.

**Comment by sreev** [comment]
going with approach 1., unless otherwise.
