### ISSUE TITLE
metrics_type=http

### ISSUE THREAD

**Issue by sreev** [zendesk/maxwell#639]
referring to: http://maxwells-daemon.io/monitoring/

when i use this option, the maxwell start up and works fine.
but when i do $ curl http://localhost:8080/ping, i get connection refused. found nothing started on 8080.

what am i missing ?

**Comment by liulikun** [comment]
Can you check maxwell is running on `localhost` too? Or check maxwell logs see if there are any errors. You should see the following message at the start of maxwell log:

```
05:49:46,943 INFO  MaxwellMetrics - Metrics http server starting
05:49:46,972 INFO  MaxwellMetrics - Metrics http server started on port 8080
```
If not, check if you're updating the right config file.

**Comment by sreev** [comment]
this is working for me as expected.
