### ISSUE TITLE
error connecting maxwell 1.10.0 with mysql 8.0.1

### ISSUE THREAD

**Issue by sreev** [zendesk/maxwell#644]
> 
$ bin/maxwell --user='maxwell' --password='password' --host='localhost' --producer=stdout --log_level=debug
Fri May 12 16:23:04 PDT 2017 WARN: Establishing SSL connection without server's identity verification is not recommended. According to MySQL 5.5.45+, 5.6.26+ and 5.7.6+ requirements SSL connection must be established by default if explicit option isn't set. For compliance with existing applications not using SSL the verifyServerCertificate property is set to 'false'. You need either to explicitly disable SSL by setting useSSL=false, or set useSSL=true and provide truststore for server certificate verification.
16:23:04,530 ERROR Maxwell - SQLException: Could not create connection to database server.
16:23:04,534 ERROR Maxwell - Could not create connection to database server.

**Comment by ericwush** [comment]
@sreev Maxwell is dependant on `mysql-binlog-connector-java` which doesn't look like MySQL 8 is supported. Below is sql driver configured in `mysql-binlog-connector-java`
```        
        <dependency>
            <groupId>mysql</groupId>
            <artifactId>mysql-connector-java</artifactId>
            <version>5.1.21</version>
            <scope>test</scope>
        </dependency>
```
Maybe @shyiko can confirm.

**Comment by shyiko** [comment]
@ericwush tests are green on MySQL 8 (https://github.com/shyiko/mysql-binlog-connector-java/commit/5cfd14276f4a720128ff678dd90e419c327e1704#diff-600376dffeb79835ede4a0b285078036R259) (`mysql:mysql-connector-java:test` had to be upgraded to `8.0.7-dmr`).

**Comment by ericwush** [comment]
@sreev mysql connector 8 [requires Java 8](https://dev.mysql.com/doc/connector-j/8.0/en/connector-j-versions.html). Upgrading maxwell to Java 8 is underway. This issue will be blocked until then.

**Comment by osheroff** [comment]
fixed awhile ago
