### ISSUE TITLE
Bug when format   timestamp column use DateFormatter

### ISSUE THREAD

**Issue by worldup** [zendesk/maxwell#647]
com.zendesk.maxwell.schema.columndef.DateFormatter  
dateFormatter.setTimeZone(TimeZone.getTimeZone("UTC"));
 this code work fine when dispose datetime column ，but when dispose timestamp column，it should
depend  on local timezone， such as  dateFormatter.setTimeZone(TimeZone.getTimeZone("Asia/Shanghai"));

**Comment by osheroff** [comment]
should it, really?  I'm generally of the opinion that everything should stay UTC until the last minute (ie showing the datetime to a user).  Since mysql's timestamps don't have a timezone associated with them, I think it's preferable that Maxwell always assumes you're storing UTC and then outputs UTC.

**Comment by worldup** [comment]
hi,osheroff ,  see the below link 
https://dev.mysql.com/doc/refman/5.5/en/datetime.html
MySQL converts TIMESTAMP values from the current time zone to UTC for storage, and back from UTC to the current time zone for retrieval. (This does not occur for other types such as DATETIME.) By default, the current time zone for each connection is the server's time.

**Comment by osheroff** [comment]
@worldup, 
That may be true but I still feel that maxwell is more of a server-to-server concern, and that the proper place to cast from UTC to local time would be in your Kafka client.

**Comment by sanguinar** [comment]
Actually, I hope that the output of timestamp from maxwell will have a flag of UTC. Otherwise how can I tell the timezone between timestamp and datetime(if not from mysql).

**Comment by Hackeruncle** [comment]
https://github.com/zendesk/maxwell/issues/903
