### ISSUE TITLE
Check the possibility of using X Protocol for maxwell-bootstrap

### ISSUE THREAD

**Issue by sreev** [zendesk/maxwell#649]
new X Protocol in addition to JDBC for connecting to mysql.

@osheroff : i think, they should co-exists.

reference:
https://github.com/sreev/xproto-mysql8

**Comment by timbertson** [comment]
You'd need to provide some more info on why this is useful - i.e. jdbc works fine, what benefit would we get from adding another connection mechanism? I have neither heard of nor used X protocol before, so apologies if the benefits are supposed to be obvious.

**Comment by sreev** [comment]
@timbertson 
MySQL 5.7.12 release announced the support of X Protocol.

This is a good start to know the features of X DevAPI :
https://dev.mysql.com/doc/x-devapi-userguide/en/devapi-users-introduction.html

Usecases for X Protocol:
https://dev.mysql.com/doc/internals/en/x-protocol-use-cases-use-cases.html

**Comment by osheroff** [comment]
Nah, this isn't there yet.  Sometime in the future they may do HA support or something with the x protocol but it's still totally beta code, doesn't provide anything we need yet.
