### ISSUE TITLE
CLARIFICATION: When bootstrapping a table, it's replication events are queued for later, but what is it's type?

### ISSUE THREAD

**Issue by tankchintan** [zendesk/maxwell#659]
After giving a _quick_ look through the code & going through the **bootstrapping** doc I was not able to figure out what is the message `type` of the binlog events of the table which is being bootstrapped.

Per doc, the binlog events for such a table is queued for the end in `async` mode. But I wanted to know what would be the message `type` of it? Will it be `bootstrap-insert`, `bootstrap-update` or `bootstrap-delete`? Or it would be the normal `insert`, `update` or `delete`?

Assuming that `bootstrap-complete` will still be the last message in the whole process regardless of whether `bootstrap-insert` or `insert` is being passed on for binlog events of bootstrapped tables.

**Comment by smferguson** [comment]
binlog events processed by the bootstrapper are of type `bootstrap-*`. those queued for after a bootstrap is complete are the standard `insert`, `update`, `delete`.

**Comment by tankchintan** [comment]
Thanks @smferguson I created a [PR](https://github.com/zendesk/maxwell/pull/661) that would make this explicit in the documentation.

**Comment by smferguson** [comment]
awesome! love improved doc. @timbertson & co. are the gatekeepers here for merges :)
