### ISSUE TITLE
maxwell filtering,How to use one kafka topic?

### ISSUE THREAD

**Issue by saup007** [zendesk/maxwell#660]
3306 db1,db2

db1 all table (t1,t2,t3)
db2 t1,t2

bin/maxwell --include_dbs=db1,db2 --include_tables=t1,t2 

db1.t3 Can not send to kafka

I will use 2 kafka topics 
bin/maxwell --include_dbs=db1 --kafka_topic=3306_db1
bin/maxwell --include_dbs=db2 --include_tables=t1,t2  --kafka_topic=3306_db2

How to use one kafka topic?

**Comment by osheroff** [comment]
It's ok to have two maxwell instances writing to one kafka topic.  You must assign each maxwell a different `client_id` though.  

In an ideal scenario we'd make our filtering a bit better and allow you to do something like:

```
bin/maxwell --include=db1.*,db2.{t1,t2}
```

**Comment by saup007** [comment]
ok. thanks. If it is better in the document

**Comment by saup007** [comment]
include is not a recognized option...
if --include_dbs=db1.*,db2.{t1,t2}
joptsimple.MultipleArgumentsForOptionException: Found multiple arguments for option include_dbs, but you asked for only one

if --include_dbs=orca_test --include_tables=orca_bbbb.{t1,t3}
joptsimple.MultipleArgumentsForOptionException: Found multiple arguments for option include_tables, but you asked for only one

**Comment by saup007** [comment]
Oh, I understand that this is in the ideal state

**Comment by saup007** [comment]
finished.
--include_dbs=db1,db2
--include_dbs=db3 --include_tables=t1,t2,t3
