### ISSUE TITLE
Importing as a maven project in eclipse works on a linux system but not on a windows system

### ISSUE THREAD

**Issue by rohan-shimpi** [zendesk/maxwell#664]
I imported the source code into eclipse as a project and executed the project. It was able to connect to MySQL database and capture changes when on running on a Linux system. But the running the same code with same parameters on Windows system gave the following exception
 SQLException: Access denied for user 'maxwell'@'system_name' (using password: YES)
Is there something I am missing?

**Comment by liulikun** [comment]
It seems the user `maxwell` doesn't have the proper database permission. 

Have you tried this?

```
mysql> GRANT ALL on maxwell.* to 'maxwell'@'%' identified by 'XXXXXX';
mysql> GRANT SELECT, REPLICATION CLIENT, REPLICATION SLAVE on *.* to 'maxwell'@'%'
```

**Comment by rohan-shimpi** [comment]
Yes I have set the permission mentioned. The database can be connected from a remote linux system but not a remote windows system.

**Comment by liulikun** [comment]
This doesn't seem a maxwell issue. If you can connect to the database with user `maxwell` using plain mysql client, that'll be the first step I think.

**Comment by rohan-shimpi** [comment]
I can connect to the database using other clients and also using Maxwell from my Linux system
