### ISSUE TITLE
Use of "null island" throws exception

### ISSUE THREAD

**Issue by magnusboman** [zendesk/maxwell#667]
We have a table defined with coordinates as:
`coordinates` geometry NOT NULL,

If coordinates are not know, we use "null island"[1] (ie, Point(0,0)) to describe that. Somehow, Maxwell doesn't like this and throws an exception:

```
22:37:11,597 DEBUG MaxwellKafkaProducer - ->  key:{"database":"test","table":"test","pk.id":2248240}, partition:0, offset:10898888
22:37:11,597 DEBUG MaxwellKafkaProducer -    {"database":"test","table":"test","type":"bootstrap-insert","ts":1496183831,"data":{"coordinates":"POINT (0 0)"}}
22:37:11,597 DEBUG MaxwellKafkaProducer -    Position[BinlogPosition[mysql-bin-changelog.006088:488719], lastHeartbeat=0]
22:37:11,597 DEBUG MaxwellKafkaProducer -
java.lang.IllegalArgumentException: 4 > 0
        at java.util.Arrays.copyOfRange(Arrays.java:3519)
        at com.zendesk.maxwell.schema.columndef.GeometryColumnDef.asJSON(GeometryColumnDef.java:32)
        at com.zendesk.maxwell.bootstrap.SynchronousBootstrapper.setRowValues(SynchronousBootstrapper.java:238)
        at com.zendesk.maxwell.bootstrap.SynchronousBootstrapper.startBootstrap(SynchronousBootstrapper.java:65)
        at com.zendesk.maxwell.bootstrap.AsynchronousBootstrapper$1.run(AsynchronousBootstrapper.java:74)
        at java.lang.Thread.run(Thread.java:745)
```

1) https://en.wikipedia.org/wiki/Null_Island

**Comment by timbertson** [comment]
Ow, that's no good. Given this comment: "mysql sprinkles 4 mystery bytes on top of the GIS data" (https://github.com/zendesk/maxwell/blob/80f8b18e5c495fe83088d5d49b6e3ba8c1481cce/src/main/java/com/zendesk/maxwell/schema/columndef/GeometryColumnDef.java#L31) it might be time for someone to dig into what those leading 4 bytes are, because maybe (0,0) up with a different byte representation?

**Comment by osheroff** [comment]
I'll see if I can poke at this.  Got a long layover in abu daubi on the way to Berlin

**Comment by osheroff** [comment]
I can't reproduce this with a `POINT(0 0)` column, either in the regular code or the bootstrapping code.  Could you dump what's actually in the table?  think it might be the row that follows the `POINT(0, 0)` row that's causing the issue.

**Comment by magnusboman** [comment]
Looks like you are right. When I looked, the only row with point(0 0) was the one that looked like failing, but checking the next record, coordinates was set to "".
Sorry about the fuzz!

**Comment by osheroff** [comment]
Hmmm any idea how an empty string got there?  Apparently MySQL thinks it's sorta valid, so maxwell shouldn't crash....

**Comment by magnusboman** [comment]
Prior to us using Point(0 0), we set it to "". This caused issues with another 3rd party reader so we updated all those empty values to use null island, after which someone had been running old code against this particular DB.
