### ISSUE TITLE
create a slack channel

### ISSUE THREAD

**Issue by sreev** [zendesk/maxwell#668]

**Comment by sreev** [comment]
created a slack channel (maxwells-daemon.slack.com).
please use the following url to join:

https://join.slack.com/maxwells-daemon/shared_invite/MTkwMzIyMzk0OTQ5LTE0OTYxOTUxNzEtYTc2OWYzMWQ5ZQ

**Comment by timbertson** [comment]
Personally I'd find a mailing list easier to manage - synchronous communication is hard in general, and worse when you're GMT+11. Were you looking into a mailing list @osheroff ? Maybe discourse if people don't care too much about using an email client...

**Comment by osheroff** [comment]
@timbertson yeah I was looking into a mailing list at some point, I could never really find a hosted solution I liked.  I guess a google group might do ok?

**Comment by timbertson** [comment]
I'd be happy with a google group - it's nothing fancy, but it's more durable and async-friendly than a slack channel.

**Comment by sreev** [comment]
created this group group, please join. keeping the slack channel, open, too.

https://groups.google.com/forum/#!forum/maxwell-daemon
