### ISSUE TITLE
blacklist_dbs documentation

### ISSUE THREAD

**Issue by jgysland** [zendesk/maxwell#670]
It would be helpful to state explicitly in the documentation that having `blacklist_dbs` (or `exclude_dbs`, if I understand correctly) include `maxwell` will cause the bootstrapper to never pick up any jobs -- nor raise any exceptions or otherwise make any noise to explain why.

I spent a longer time than I care to admit trying to figure out why nothing I was doing would make the bootstrapper start. When I finally read #268, I realized my error. :dizzy_face: 

Because the MySQL server I'm reading from has myriad databases with lots of DDL churn and the only database want to replicate is `foo`, I had set `blacklist_dbs=/^(?!foo)/` to exclude everything but foo and thus keep Maxwell from getting bogged down with schema versioning. After realizing this was my problem, I set `blacklist_dbs=/^(?!foo|maxwell|mysql)/`,\* and the bootstrapper was suddenly very busy!

\* I saw that `mysql` also appears in `maxwell.databases` regardless of being blacklisted, so I figured it also warranted exclusion from the blacklist.

**Comment by osheroff** [comment]
Hmmm, feels more like a bug than a thing that should just be documented.  There's another PR in-flight that reworks the bootstrapping code and will avoid this issue, but meanwhile it'd be great to have a patch where we never exclude events to the bootstrap control table from trickling into the stream

**Comment by osheroff** [comment]
the blacklist code has been reworked to avoid this.
