### ISSUE TITLE
maxwell is running a little while has throw exception

### ISSUE THREAD

**Issue by AlvinYang-2017** [zendesk/maxwell#677]
i set ignore_producer_error to false in my config, Maxwell run for a while to encounter TimeoutException to quit, every time this is the case.
Is it wrong for maxwell to send a message to kafka？ but I checked that my message to kafka's topic was no problem，The following is the run log.

anyone help me ? 

@liulikun @timbertson 
Thanks~

> 23:19:25,133 ERROR MaxwellKafkaProducer - TimeoutException @ Position[BinlogPosition[mysql-bin.000456:281777608], lastHeartbeat=0] -- {"database":"ne04","table":"chargeorderdetail","pk.id":81597}
> 23:19:25,133 ERROR MaxwellKafkaProducer - Batch Expired
> 23:19:25,133 INFO  TaskManager - stopping 3 tasks
> 23:19:25,133 ERROR TaskManager - cause: 
> org.apache.kafka.common.errors.TimeoutException: Batch Expired
> 23:19:25,136 INFO  StoppableTaskState - MaxwellKafkaProducerWorker requestStop() called (in state: RUNNING)
> 23:19:25,136 INFO  KafkaProducer - Closing the Kafka producer with timeoutMillis = 9223372036854775807 ms.
> 23:19:25,136 WARN  KafkaProducer - Overriding close timeout 9223372036854775807 ms to 0 ms in order to prevent useless blocking due to self-join. This means you have incorrectly invoked close with a non-zero timeout from the producer call-back.
> 23:19:25,137 INFO  KafkaProducer - Proceeding to force close the producer since pending requests could not be completed within timeout 9223372036854775807 ms.
> 23:19:25,137 DEBUG KafkaProducer - The Kafka producer has closed.
> 23:19:25,137 INFO  StoppableTaskState - com.zendesk.maxwell.schema.PositionStoreThread requestStop() called (in state: RUNNING)
> 23:19:25,138 INFO  StoppableTaskState - com.zendesk.maxwell.replication.MaxwellReplicator requestStop() called (in state: RUNNING)
> 23:19:26,349 DEBUG TransportImpl - disconnected from rm-bp10c3d15i9253t0p.mysql.rds.aliyuncs.com:3306
> 23:19:26,449 INFO  TaskManager - stopped all tasks
> org.apache.kafka.common.errors.TimeoutException: Batch Expired
> 23:19:26,453 ERROR MaxwellKafkaProducer - TimeoutException @ Position[BinlogPosition[mysql-bin.000456:281777608], lastHeartbeat=0] -- {"database":"ne04","table":"chargeorderdetail","pk.id":81598}
> 23:19:26,454 ERROR MaxwellKafkaProducer - Batch Expired
> 23:19:26,454 ERROR MaxwellKafkaProducer - TimeoutException @ Position[BinlogPosition[mysql-bin.000456:281777608], lastHeartbeat=0] -- {"database":"ne04","table":"chargeorderdetail","pk.id":81599}
> 23:19:26,454 ERROR MaxwellKafkaProducer - Batch Expired
> 23:19:26,454 ERROR MaxwellKafkaProducer - TimeoutException @ Position[BinlogPosition[mysql-bin.000456:281785695], lastHeartbeat=0] -- {"database":"ne04","table":"chargeorderdetail","pk.id":81600}
> 23:19:26,454 ERROR MaxwellKafkaProducer - Batch Expired
> 23:19:26,454 ERROR MaxwellKafkaProducer - TimeoutException @ Position[BinlogPosition[mysql-bin.000456:281785695], lastHeartbeat=0] -- {"database":"ne04","table":"chargeorderdetail","pk.id":81601}
> 23:19:26,454 ERROR MaxwellKafkaProducer - Batch Expired
> 23:19:26,454 ERROR MaxwellKafkaProducer - TimeoutException @ Position[BinlogPosition[mysql-bin.000456:281785695], lastHeartbeat=0] -- {"database":"ne04","table":"chargeorderdetail","pk.id":81602}
> 23:19:26,454 ERROR MaxwellKafkaProducer - Batch Expired
> 23:19:26,454 ERROR MaxwellKafkaProducer - TimeoutException @ Position[BinlogPosition[mysql-bin.000456:281785695], lastHeartbeat=0] -- {"database":"ne04","table":"chargeorderdetail","pk.id":81603}
> 23:19:26,458 ERROR MaxwellKafkaProducer - Batch Expired
> 23:19:26,458 ERROR MaxwellKafkaProducer - TimeoutException @ Position[BinlogPosition[mysql-bin.000456:281785695], lastHeartbeat=0] -- {"database":"ne04","table":"chargeorderdetail","pk.id":81604}
> 23:19:26,458 ERROR MaxwellKafkaProducer - Batch Expired
> 23:19:26,458 ERROR MaxwellKafkaProducer - TimeoutException @ Position[BinlogPosition[mysql-bin.000456:281785695], lastHeartbeat=0] -- {"database":"ne04","table":"chargeorderdetail","pk.id":81605}
> 23:19:26,458 ERROR MaxwellKafkaProducer - Batch Expired
> 23:19:26,458 ERROR MaxwellKafkaProducer - TimeoutException @ Position[BinlogPosition[mysql-bin.000456:281785695], lastHeartbeat=0] -- {"database":"ne04","table":"chargeorderdetail","pk.id":81606}
> 23:19:26,458 ERROR MaxwellKafkaProducer - Batch Expired
> 23:19:26,459 ERROR MaxwellKafkaProducer - TimeoutException @ Position[BinlogPosition[mysql-bin.000456:281785695], lastHeartbeat=0] -- {"database":"ne04","table":"chargeorderdetail","pk.id":81607}
> 23:19:26,459 ERROR MaxwellKafkaProducer - Batch Expired
> 23:19:26,459 ERROR MaxwellKafkaProducer - TimeoutException @ Position[BinlogPosition[mysql-bin.000456:281785695], lastHeartbeat=0] -- {"database":"ne04","table":"chargeorderdetail","pk.id":81608}
> 23:19:26,459 ERROR MaxwellKafkaProducer - Batch Expired
> 23:19:26,459 ERROR MaxwellKafkaProducer - TimeoutException @ Position[BinlogPosition[mysql-bin.000456:281785695], lastHeartbeat=0] -- {"database":"ne04","table":"chargeorderdetail","pk.id":81609}
> 23:19:26,459 ERROR MaxwellKafkaProducer - Batch Expired
> 23:19:26,459 ERROR MaxwellKafkaProducer - TimeoutException @ Position[BinlogPosition[mysql-bin.000456:281785695], lastHeartbeat=0] -- {"database":"ne04","table":"chargeorderdetail","pk.id":81610}
> 23:19:26,459 ERROR MaxwellKafkaProducer - Batch Expired
> 23:19:26,459 ERROR MaxwellKafkaProducer - TimeoutException @ Position[BinlogPosition[mysql-bin.000456:281785695], lastHeartbeat=0] -- {"database":"ne04","table":"chargeorderdetail","pk.id":81611}
> 23:19:26,460 ERROR MaxwellKafkaProducer - Batch Expired
> 23:19:26,460 ERROR MaxwellKafkaProducer - TimeoutException @ Position[BinlogPosition[mysql-bin.000456:281785695], lastHeartbeat=0] -- {"database":"ne04","table":"chargeorderdetail","pk.id":81612}
> 23:19:26,460 ERROR MaxwellKafkaProducer - Batch Expired
> 23:19:26,460 ERROR MaxwellKafkaProducer - TimeoutException @ Position[BinlogPosition[mysql-bin.000456:281785695], lastHeartbeat=0] -- {"database":"ne04","table":"chargeorderdetail","pk.id":81613}
> 23:19:26,460 ERROR MaxwellKafkaProducer - Batch Expired
> 23:19:26,460 ERROR MaxwellKafkaProducer - TimeoutException @ Position[BinlogPosition[mysql-bin.000456:281785695], lastHeartbeat=0] -- {"database":"ne04","table":"chargeorderdetail","pk.id":81614}
> 23:19:26,460 ERROR MaxwellKafkaProducer - Batch Expired
> 23:19:26,460 ERROR MaxwellKafkaProducer - TimeoutException @ Position[BinlogPosition[mysql-bin.000456:281785695], lastHeartbeat=0] -- {"database":"ne04","table":"chargeorderdetail","pk.id":81615}
> 23:19:26,460 ERROR MaxwellKafkaProducer - Batch Expired
> 23:19:26,460 ERROR MaxwellKafkaProducer - TimeoutException @ Position[BinlogPosition[mysql-bin.000456:281785695], lastHeartbeat=0] -- {"database":"ne04","table":"chargeorderdetail","pk.id":81616}
> 23:19:26,461 ERROR MaxwellKafkaProducer - Batch Expired
> 23:19:26,461 ERROR MaxwellKafkaProducer - TimeoutException @ Position[BinlogPosition[mysql-bin.000456:281785695], lastHeartbeat=0] -- {"database":"ne04","table":"chargeorderdetail","pk.id":81617}
> 23:19:26,461 ERROR MaxwellKafkaProducer - Batch Expired
> 23:19:26,461 ERROR MaxwellKafkaProducer - TimeoutException @ Position[BinlogPosition[mysql-bin.000456:281785695], lastHeartbeat=0] -- {"database":"ne04","table":"chargeorderdetail","pk.id":81618}
> 23:19:26,461 ERROR MaxwellKafkaProducer - Batch Expired
> 23:19:26,461 ERROR MaxwellKafkaProducer - TimeoutException @ Position[BinlogPosition[mysql-bin.000456:281785695], lastHeartbeat=0] -- {"database":"ne04","table":"chargeorderdetail","pk.id":81619}
> 23:19:26,461 ERROR MaxwellKafkaProducer - Batch Expired
> 23:19:26,461 ERROR MaxwellKafkaProducer - TimeoutException @ Position[BinlogPosition[mysql-bin.000456:281785695], lastHeartbeat=0] -- {"database":"ne04","table":"chargeorderdetail","pk.id":81620}
> 23:19:26,461 ERROR MaxwellKafkaProducer - Batch Expired
> 23:19:26,461 ERROR MaxwellKafkaProducer - TimeoutException @ Position[BinlogPosition[mysql-bin.000456:281785695], lastHeartbeat=0] -- {"database":"ne04","table":"chargeorderdetail","pk.id":81621}
> 23:19:26,461 ERROR MaxwellKafkaProducer - Batch Expired
> 23:19:26,461 ERROR MaxwellKafkaProducer - TimeoutException @ Position[BinlogPosition[mysql-bin.000456:281785695], lastHeartbeat=0] -- {"database":"ne04","table":"chargeorderdetail","pk.id":81622}
> 23:19:26,462 ERROR MaxwellKafkaProducer - Batch Expired
> 23:19:26,462 ERROR MaxwellKafkaProducer - TimeoutException @ Position[BinlogPosition[mysql-bin.000456:281785695], lastHeartbeat=0] -- {"database":"ne04","table":"chargeorderdetail","pk.id":81623}
> 23:19:26,462 ERROR MaxwellKafkaProducer - Batch Expired
> 23:19:26,462 ERROR MaxwellKafkaProducer - TimeoutException @ Position[BinlogPosition[mysql-bin.000456:281785695], lastHeartbeat=0] -- {"database":"ne04","table":"chargeorderdetail","pk.id":81624}
> 23:19:26,462 ERROR MaxwellKafkaProducer - Batch Expired
> 23:19:26,462 ERROR MaxwellKafkaProducer - TimeoutException @ Position[BinlogPosition[mysql-bin.000456:281785695], lastHeartbeat=0] -- {"database":"ne04","table":"chargeorderdetail","pk.id":81625}
> 23:19:26,462 ERROR MaxwellKafkaProducer - Batch Expired
> 23:19:26,462 ERROR MaxwellKafkaProducer - TimeoutException @ Position[BinlogPosition[mysql-bin.000456:281785695], lastHeartbeat=0] -- {"database":"ne04","table":"chargeorderdetail","pk.id":81626}
> 23:19:26,462 ERROR MaxwellKafkaProducer - Batch Expired
> 23:19:26,462 ERROR MaxwellKafkaProducer - TimeoutException @ Position[BinlogPosition[mysql-bin.000456:281785695], lastHeartbeat=0] -- {"database":"ne04","table":"chargeorderdetail","pk.id":81627}
> 23:19:26,462 ERROR MaxwellKafkaProducer - Batch Expired
> 23:19:26,463 ERROR MaxwellKafkaProducer - TimeoutException @ Position[BinlogPosition[mysql-bin.000456:281785695], lastHeartbeat=0] -- {"database":"ne04","table":"chargeorderdetail","pk.id":81628}
> 23:19:26,463 ERROR MaxwellKafkaProducer - Batch Expired
> 23:19:26,463 ERROR MaxwellKafkaProducer - TimeoutException @ Position[BinlogPosition[mysql-bin.000456:281785695], lastHeartbeat=0] -- {"database":"ne04","table":"chargeorderdetail","pk.id":81629}
> 23:19:26,463 ERROR MaxwellKafkaProducer - Batch Expired
> 23:19:26,463 ERROR MaxwellKafkaProducer - TimeoutException @ Position[BinlogPosition[mysql-bin.000456:281785695], lastHeartbeat=0] -- {"database":"ne04","table":"chargeorderdetail","pk.id":81630}
> 23:19:26,464 ERROR MaxwellKafkaProducer - Batch Expired
> 23:19:26,464 ERROR MaxwellKafkaProducer - TimeoutException @ Position[BinlogPosition[mysql-bin.000456:281793740], lastHeartbeat=0] -- {"database":"ne04","table":"chargeorderdetail","pk.id":81631}
> 23:19:26,464 ERROR MaxwellKafkaProducer - Batch Expired
> 23:19:26,464 ERROR MaxwellKafkaProducer - TimeoutException @ Position[BinlogPosition[mysql-bin.000456:281793740], lastHeartbeat=0] -- {"database":"ne04","table":"chargeorderdetail","pk.id":81632}
> 23:19:26,464 ERROR MaxwellKafkaProducer - Batch Expired
> 23:19:26,464 ERROR MaxwellKafkaProducer - TimeoutException @ Position[BinlogPosition[mysql-bin.000456:281793740], lastHeartbeat=0] -- {"database":"ne04","table":"chargeorderdetail","pk.id":81633}
> 23:19:26,464 ERROR MaxwellKafkaProducer - Batch Expired
> 23:19:26,464 ERROR MaxwellKafkaProducer - TimeoutException @ Position[BinlogPosition[mysql-bin.000456:281793740], lastHeartbeat=0] -- {"database":"ne04","table":"chargeorderdetail","pk.id":81634}
> 23:19:26,464 ERROR MaxwellKafkaProducer - Batch Expired
> 23:19:26,464 ERROR MaxwellKafkaProducer - TimeoutException @ Position[BinlogPosition[mysql-bin.000456:281793740], lastHeartbeat=0] -- {"database":"ne04","table":"chargeorderdetail","pk.id":81635}
> 23:19:26,464 ERROR MaxwellKafkaProducer - Batch Expired
> 23:19:26,465 ERROR MaxwellKafkaProducer - TimeoutException @ Position[BinlogPosition[mysql-bin.000456:281793740], lastHeartbeat=0] -- {"database":"ne04","table":"chargeorderdetail","pk.id":81636}
> 23:19:26,465 ERROR MaxwellKafkaProducer - Batch Expired
> 23:19:26,465 ERROR MaxwellKafkaProducer - TimeoutException @ Position[BinlogPosition[mysql-bin.000456:281793740], lastHeartbeat=0] -- {"database":"ne04","table":"chargeorderdetail","pk.id":81637}
> 23:19:26,465 ERROR MaxwellKafkaProducer - Batch Expired
> 23:19:26,465 ERROR MaxwellKafkaProducer - TimeoutException @ Position[BinlogPosition[mysql-bin.000456:281793740], lastHeartbeat=0] -- {"database":"ne04","table":"chargeorderdetail","pk.id":81638}
> 23:19:26,465 ERROR MaxwellKafkaProducer - Batch Expired
> 23:19:26,465 ERROR MaxwellKafkaProducer - TimeoutException @ Position[BinlogPosition[mysql-bin.000456:281793740], lastHeartbeat=0] -- {"database":"ne04","table":"chargeorderdetail","pk.id":81639}
> 23:19:26,465 ERROR MaxwellKafkaProducer - Batch Expired
> 23:19:26,465 ERROR MaxwellKafkaProducer - TimeoutException @ Position[BinlogPosition[mysql-bin.000456:281793740], lastHeartbeat=0] -- {"database":"ne04","table":"chargeorderdetail","pk.id":81646}
> 23:19:26,466 ERROR MaxwellKafkaProducer - Batch Expired
> 23:19:26,466 ERROR MaxwellKafkaProducer - TimeoutException @ Position[BinlogPosition[mysql-bin.000456:281793740], lastHeartbeat=0] -- {"database":"ne04","table":"chargeorderdetail","pk.id":81647}
> 23:19:26,467 ERROR MaxwellKafkaProducer - Batch Expired
> 23:19:26,467 ERROR MaxwellKafkaProducer - TimeoutException @ Position[BinlogPosition[mysql-bin.000456:281793740], lastHeartbeat=0] -- {"database":"ne04","table":"chargeorderdetail","pk.id":81648}
> 23:19:26,467 ERROR MaxwellKafkaProducer - Batch Expired
> 23:19:26,467 ERROR MaxwellKafkaProducer - TimeoutException @ Position[BinlogPosition[mysql-bin.000456:281793740], lastHeartbeat=0] -- {"database":"ne04","table":"chargeorderdetail","pk.id":81649}
> 23:19:26,467 ERROR MaxwellKafkaProducer - Batch Expired
> 23:19:26,467 ERROR MaxwellKafkaProducer - TimeoutException @ Position[BinlogPosition[mysql-bin.000456:281793740], lastHeartbeat=0] -- {"database":"ne04","table":"chargeorderdetail","pk.id":81650}
> 23:19:26,467 ERROR MaxwellKafkaProducer - Batch Expired
> 23:19:26,467 ERROR MaxwellKafkaProducer - TimeoutException @ Position[BinlogPosition[mysql-bin.000456:281793740], lastHeartbeat=0] -- {"database":"ne04","table":"chargeorderdetail","pk.id":81651}
> 23:19:26,467 ERROR MaxwellKafkaProducer - Batch Expired
> 23:19:26,467 ERROR MaxwellKafkaProducer - TimeoutException @ Position[BinlogPosition[mysql-bin.000456:281793740], lastHeartbeat=0] -- {"database":"ne04","table":"chargeorderdetail","pk.id":81652}
> 23:19:26,468 ERROR MaxwellKafkaProducer - Batch Expired
> 23:19:26,468 ERROR MaxwellKafkaProducer - TimeoutException @ Position[BinlogPosition[mysql-bin.000456:281793740], lastHeartbeat=0] -- {"database":"ne04","table":"chargeorderdetail","pk.id":81653}
> 23:19:26,468 ERROR MaxwellKafkaProducer - Batch Expired
> 23:19:26,468 ERROR MaxwellKafkaProducer - TimeoutException @ Position[BinlogPosition[mysql-bin.000456:281793740], lastHeartbeat=0] -- {"database":"ne04","table":"chargeorderdetail","pk.id":81654}
>

**Comment by timbertson** [comment]
Does the process keep running after this? Or does it exit?

I'm not sure what you're reporting - is the issue that you're getting the TimeoutException, or is the issue that maxwell is not shutting down after that error?

**Comment by AlvinYang-2017** [comment]
after that error maxwell will shutting down, This is expected.
I checked kafka running without problems，Why does this cause this exception?

**Comment by AlvinYang-2017** [comment]
I found that due to maxwell and kafka is caused by external network communication, the external network bandwidth limit resulting in maxwell production message timeout，thanks~
