### ISSUE TITLE
Curious case of maxwell failure by referring to super old binlog 

### ISSUE THREAD

**Issue by tankchintan** [zendesk/maxwell#678]
So I have been running `maxwell` service in non-production environment for some time now in dev & staging sandbox, & I almost never had an issue which was caused `maxwell` per se.

But yesterday night I saw that `maxwell` service had died in the `dev` environment. When looking in to the logs I found the last entry to be as below,
```
18:31:33,210 WARN  MaxwellReplicator - open-replicator stopped at position mariadb-bin.008690:40917516 -- restarting
18:31:33,228 INFO  OpenReplicator - starting replication at mariadb-bin.008690:40917516
18:31:33,266 ERROR AbstractBinlogParser - failed to parse binlog
java.lang.RuntimeException: EOFPacket[packetMarker=254,warningCount=0,serverStatus=2]
	at com.google.code.or.binlog.impl.ReplicationBasedBinlogParser.readPacketMarker(ReplicationBasedBinlogParser.java:104) ~[open-replicator-1.6.0.jar:?]
	at com.google.code.or.binlog.impl.ReplicationBasedBinlogParser.doParse(ReplicationBasedBinlogParser.java:135) ~[open-replicator-1.6.0.jar:?]
	at com.google.code.or.binlog.impl.AbstractBinlogParser$Task.run(AbstractBinlogParser.java:263) [open-replicator-1.6.0.jar:?]
	at java.lang.Thread.run(Thread.java:745) [?:1.7.0_131]
18:31:33,331 WARN  MaxwellReplicator - open-replicator stopped at position mariadb-bin.008690:40917516 -- restarting
```

But this surprised me because,
1. `maxwell` service was never down before this happened. I know this because I publish all the metrics to datadog & I did not see any break in the metrics reporting before this event.
2. The source mysql instance was not down for any period of time. Again I have datadog metrics to rely on for this assertion.
3. The `binlog` referred to by maxwell is super old. 4 days old at least. The latest binlog is named `mariadb-bin.002131` & the file it failed on is `mariadb-bin.008690`. We have a policy of deleting binlogs after 4 days, so I see that the very next binlog i.e. `mariadb-bin.008691` is still present in our filesystem. But it would be gone tomorrow.

Now my question is, why is maxwell referring to a very old binlog when there are newer binlog files available?

I have a theory. But let me share an observation (I am sure you might know it already, but it was surprising to me).

Looks like the `maxwell.positions` table is not updated every time there is some new _stuff_ in the binlog file. It seems to update the position only when there is an update to the monitored db/tables, and that too not to the exact point at which the binlog is.

e.g. 
```# See current master position
show master status;
mariadb-bin.002131	351132940		

select * from maxwell.positions;
47450	mariadb-bin.002131	351126756		maxwell		0
```

So my guess is, that there were no changes in the `dev` environment for a long time. This meant that `maxwell.positions` was holding on to the oldest binlog position which had some actionable changes. 4 days later that oldest binlog auto-expired. And because maxwell was still holding on to that old bonlog it crashed.

* Is that an accurate assessment?
* If yes, how can I solve this?
* If such a crash occurs, can I update the `maxwell.positions` table myself to a binlog that I know exists & to some position? Because right now to solve the issue, I had to wipe out the maxwell db completely & restart the service. This has danger of losing some updates once maxwell is up, since it will pick it up from the latest position.
* I tried to feed updates to `maxwell.positions` table to Kafka using normal maxwell processes/config, but even when there are updates in that table I dont see any messages being published to Kafka. Is this disabled (I can see why, but want a confirmation). I wanted this since I wanted a historical audit, on when a new binlog is used etc.

**Comment by timbertson** [comment]
Thanks for the detailed report @tankchintan . That all looks like a fairly accurate assessment. My main question is what version of maxwell are you using? We recently altered the behaviour to heartbeat at least every 10s in **v1.10.1** to deal with quiet environments like this, so this should not happen in that version or later.

As for your recovery questions:

> can I update the maxwell.positions table myself to a binlog that I know exists & to some position

It's possible, but the official way to do this is using the `--init_position` flag. You'll need a heartbeat value as well as the binlog position, but if your schema hasn't changed in a long time any recent heartbeat should suffice.

> I tried to feed updates to maxwell.positions table to Kafka using normal maxwell processes/config, but even when there are updates in that table I dont see any messages being published to Kafka. Is this disabled (I can see why, but want a confirmation)

That's right - we don't process changes to maxwell's own database: https://github.com/zendesk/maxwell/blob/3c4f17a883627e88d9bb56ee931a628ab9103e1f/src/main/java/com/zendesk/maxwell/replication/AbstractReplicator.java#L184
. In most cases these messages would be unnecessary noise, in theory I think it would be possible to allow them though.

**Comment by tankchintan** [comment]
> what version of maxwell are you using?
I am pretty sure I had deployed v1.10.1. Unfortunately I had deployed this on a Kubernetes container, & when I got the error I killed it & also upgraded whatever version was there, to v1.10.3. So I can say with high confidence that it was `v1.10.1` but I can not say that categorically.

> `--init_position`
This is great, I can use it. Re: the real world usability of this, can I 
- `show master status` 
- using `binglog_file` as is
- subtracting few thousands from the  `position` and using that 
- subtracting few minutes (depending on my use case) from the `maxwell.heartbeats` and using that

Would this suffice? I guess my question is should I have to be exact in terms of.. at _this_ heartbeat the position has to be _that_? Or can I make a rough guess & it would be fine?

BTW is `heartbeat_at`, `last_heartbeat_read` in `maxwell.positions` seem to be null or empty. Is that fine?

**Comment by timbertson** [comment]
> Would this suffice? I guess my question is should I have to be exact in terms of.. at this heartbeat the position has to be that? Or can I make a rough guess & it would be fine?

Guessing is sadly not permitted ;). Usually an init_position needs some sort of logs or extra information in order to figure out correct values - if this is a dev box I'd recommend blowing away the maxwell database and starting over. But in the interest of understanding, this _might_ work:

 - `binlog_file`: use the latest, that's fine
 - `position`: this is a byte offset within the binlog file - it needs to point to the first byte of an event, so guessing will almost never work. The value `4` is the only known good value for an arbitrary binlog file (the first event in the file)
 - for heartbeat, you may be able to use the result of `select last_heartbeat_read from `schemas` order by last_heartbeat_read desc limit 1;`. If your DB schema has changed between this time and the new binlog position you're using, your data won't match the stored schema and maxwell will eventually crash when it encounters this data.

> BTW is heartbeat_at, last_heartbeat_read in maxwell.positions seem to be null or empty. 

`maxwell.heartbeat_at` is unused and will eventually be removed. `last_heartbeat_read` should be populated though, if that's null / 0 then that sounds maxwell has never successfully seen a heartbeat, which shouldn't be the case if your DB has ever seen activity since you started maxwell.

**Comment by tankchintan** [comment]
Thanks @timbertson this is plenty of information for me to work with.

Closing since I understand the cause & recovery step.

**Comment by tankchintan** [comment]
I am re-opening this since I was seeing this issue again while running on maxwell `1.10.3`. IT is quite possible that even though the symptom is the same (referring to super old binlog) the cause might be different. If the cause is different I would be happy to create a new issue for it, but for now I am re-opening this one instead.

I will jot down the timeline here to explain how I again saw the "missing binlog" error again.

1. Maxwell service `maxwell_beta` was running fine in a beta environment.
2. I was fooling around with running a maxwell service on (I thought) separate environment `maxwell_dev`. But turned out that the DB in this maxwell instance was pointed to `beta_db` environment.
3. When I started `maxwell_dev` it started just fine. But then I immediately saw errors which conveyed that I had mistakenly pointed to a DB used in some other env. Error stacktrace,
```00:51:45,134 INFO  Maxwell - Maxwell v1.10.0 is booting (MaxwellKafkaProducer), starting at BinlogPosition[mariadb-bin.003496:238541334, lastHeartbeat=1497556022384]
00:51:47,188 INFO  MysqlSavedSchema - Restoring schema id 15801 (last modified at BinlogPosition[mariadb-bin.003496:236951289, lastHeartbeat=1497556022384])
00:52:13,915 INFO  MysqlSavedSchema - Restoring schema id 1 (last modified at BinlogPosition[mariadb-bin.002131:350613643, lastHeartbeat=0])
00:52:14,421 INFO  MysqlSavedSchema - beginning to play deltas...
00:52:15,094 INFO  MysqlSavedSchema - played 15794 deltas in 673ms
00:52:16,385 INFO  OpenReplicator - starting replication at mariadb-bin.003496:238541334
00:52:35,614 ERROR AbstractBinlogParser - failed to parse binlog
java.lang.RuntimeException: EOFPacket[packetMarker=254,warningCount=0,serverStatus=2050]
...
...
00:54:27,756 INFO  OpenReplicator - starting replication at mariadb-bin.003496:238543676
^C00:55:57,849 INFO  Maxwell - starting shutdown
00:55:58,469 ERROR Maxwell - failed graceful shutdown
com.zendesk.maxwell.errors.DuplicateProcessException: Expected a heartbeat value of 1499993506679 but didn't find it.  Is another Maxwell process running with the same client_id?
```
4. So I realized my mistake & killed this experiment.
5. Then I had known that my actual `maxwell_beta` will also shutdown in a minute or so with similar issue, but since I have auto-restart on my beta environment, I was sure that things will get back to normal, soon.
6. It didn't get back to normal, it instead started to read binlog form very old time. `mariadb-bin.002471`. I fail to understand why. Error stacktrace for `maxwell_beta` is as follows,
```02:17:43,164 INFO  AppInfoParser - Kafka version : 0.10.0.1
02:17:43,164 INFO  AppInfoParser - Kafka commitId : a7a17cdec9eaa6c5
02:17:43,173 INFO  Maxwell - Maxwell v1.10.3 is booting (MaxwellKafkaProducer), starting at Position[BinlogPosition[mariadb-bin.002642:1524626], lastHeartbeat=1497556022384]
02:17:43,324 INFO  MysqlSavedSchema - Restoring schema id 4876 (last modified at Position[BinlogPosition[mariadb-bin.002471:194886635], lastHeartbeat=1497556022384])
02:17:44,367 INFO  MysqlSavedSchema - Restoring schema id 1 (last modified at Position[BinlogPosition[mariadb-bin.002131:350613643], lastHeartbeat=0])
02:17:44,501 INFO  MysqlSavedSchema - beginning to play deltas...
02:17:45,509 INFO  MysqlSavedSchema - played 4875 deltas in 1007ms
02:17:45,522 INFO  MaxwellMetrics - Metrics http server starting
02:17:45,525 INFO  MaxwellMetrics - Metrics http server started on port 8080
02:17:45,565 INFO  log - Logging initialized @4767ms
02:17:45,596 INFO  OpenReplicator - starting replication at mariadb-bin.002642:1524626
02:17:45,598 ERROR MaxwellReplicator - Missing binlog 'mariadb-bin.002642' on XYZ_DB.com
02:17:45,598 ERROR MaxwellReplicator - Transport exception #1236
02:17:45,599 INFO  TaskManager - stopping 4 tasks
02:17:45,599 ERROR TaskManager - cause:
com.google.code.or.net.TransportException: Could not find first log file name in binary log index file
	at com.google.code.or.OpenReplicator.dumpBinlog(OpenReplicator.java:343) ~[open-replicator-1.6.0.jar:?]
	...
02:17:45,602 INFO  StoppableTaskState - MaxwellKafkaProducerWorker requestStop() called (in state: RUNNING)
02:17:45,602 INFO  KafkaProducer - Closing the Kafka producer with timeoutMillis = 9223372036854775807 ms.
02:17:45,605 INFO  StoppableTaskState - com.zendesk.maxwell.schema.PositionStoreThread requestStop() called (in state: RUNNING)
02:17:45,605 INFO  StoppableTaskState - com.zendesk.maxwell.replication.MaxwellReplicator requestStop() called (in state: RUNNING)
02:17:45,667 INFO  Server - jetty-9.2.21.v20170120
02:17:45,692 INFO  ContextHandler - Started o.e.j.s.ServletContextHandler@2b28b29c{/,null,AVAILABLE}
02:17:45,700 INFO  ServerConnector - Started ServerConnector@372eee{HTTP/1.1}{0.0.0.0:8080}
02:17:45,700 INFO  Server - Started @4903ms
02:17:46,840 ERROR TaskManager - Timed out trying waiting for com.zendesk.maxwell.replication.MaxwellReplicator process to stop after 500ms.
02:17:46,840 INFO  TaskManager - stopped all tasks
com.google.code.or.net.TransportException: Could not find first log file name in binary log index file
	at com.google.code.or.OpenReplicator.dumpBinlog(OpenReplicator.java:343)
	at com.google.code.or.OpenReplicator.start(OpenReplicator.java:115)
	at com.zendesk.maxwell.replication.MaxwellReplicator.startReplicator(MaxwellReplicator.java:117)
	at com.zendesk.maxwell.replication.MaxwellReplicator.beforeStart(MaxwellReplicator.java:132)
	at com.zendesk.maxwell.util.RunLoopProcess.runLoop(RunLoopProcess.java:23)
	at com.zendesk.maxwell.Maxwell.startInner(Maxwell.java:189)
	at com.zendesk.maxwell.Maxwell.start(Maxwell.java:137)
	at com.zendesk.maxwell.Maxwell.main(Maxwell.java:209)
```
I would have thought that maxwell would auto-recover by means of restarting the service after a shutdown. But I think I might be missing something here.

Some other details,
* I did `show master status` after some time I got, 
```
# File, Position, Binlog_Do_DB, Binlog_Ignore_DB
'mariadb-bin.003499', '1037258527', '', ''
```
* It is curious that maxwell would want to go back to `mariadb-bin.002642`, because I think I had set the initial position to this couple of weeks ago. But after that setting of initial position, we have had multiple restarts of the maxwell service.

I can give some other stats, details as well. But let me know which ones.

**Comment by tankchintan** [comment]
Looks like my tool chain which conveys information on `init_position` to maxwell, on restart, was misfiring. And it was the one that was telling maxwell to have an init_position with a super old binlog. Apologies for the confusion.

**Comment by Vardhan22** [comment]
@tankchintan We are facing the similar issue on restart. What is the  tool chain which conveys information on init_position`? How did you fix that?

**Comment by tankchintan** [comment]
Hey @Vardhan22 the tool chain I refer to here, was something very specific to environment that we developed internally. Basically the command that starts maxwell process when a new instance/server is created was wrongly taking up configuration from an old location.
