### ISSUE TITLE
Using the maxwell.bootstrap table to replay only a part of data using a start and stop condition.

### ISSUE THREAD

**Issue by vmishra** [zendesk/maxwell#682]
Can we include other conditions like "and" clause to replay only a part of data based on a stop condition in the below query, Any sample query is appreciated.

bin/maxwell-bootstrap --config localhost.properties --database foobar --table test --where "my_date >= '2017-06-26 00:00:00'" --log_level info

On the similar lines,  Is it an accepted practice to modify the value of "binlog_position" in the maxwell.positions table to a previous number. Do the "last_heartbeat_read" values need a change corresponding to the "binlog_positon" or can I just change the "binlog_positon" value in order to trick Maxwell in believing that a certain MySQL data has not been consumed.  The intention here is to replay data in case the downstream consumer goes down or loses data.

**Comment by timbertson** [comment]
Yes, `and` clauses should work fine. For bootstrapping, the `--where` argument is inserted directly into SQL.

Modifying `binlog_position` without changing `last_heartbeat_read` may work, but only if there have been no schema changes between the two binlog positions, as the heartbeat is used to figure out which schema version to use. You shouldn't be modifying `binlog_position`unless something has gone very wrong.

If your downstream consumer is losing data, you should rewind the _kafka_ consumer offsets for that consumer, or update its code to only commit offsets for messages it has successfully processed. Tricking maxwell into republishing that data is the wrong way to recover - kafka already supports reconsuming old messages and resuming after downtime, which is much cleaner than tricking maxwell into publishing duplicate messages.

**Comment by vmishra** [comment]
Thanks for your response Tim. I'm able to bootstrap based on start condition `and` clause a stop condition.

I agree with your approach of rewinding _Kafka_ consumer offsets for a consumer which is losing data. But only catch here is the assumption that _Kafka_ will never go down. 

In our use case, We are creating a real-time transaction search system using data replicated using `Maxwell` and can't afford to lose any transaction. At this point, the plan is to monitor _Kafka_ and keep track of last successful published offset. In the event of failure, whenever _Kafka_ is up again, Replay the remaining message through the second instance of `Maxwell`.

**Comment by timbertson** [comment]
Sounds like this is closed, but just to follow up: have you tried setting set the new config `ignore_producer_error` to `false`? That should cause maxwell to terminate if it fails to publish a message to kafka. Assuming you run maxwell in some sort of service monitor which will auto-restart, this has the effect of crash-looping until kafka is back up. Since maxwell only stores successfully published message offsets in its positions table, maxwell will not proceed past a given binlog position until it has been successfully published to kafka.

**Comment by osheroff** [comment]
You also want to tune your Kafka producer settings for max durability.  Acks, max_inflight, those things.  Which BTW we should document for maxwell.
