### ISSUE TITLE
Maxwell stopping with `Couldn't find database credentials` exception

### ISSUE THREAD

**Issue by tankchintan** [zendesk/maxwell#684]
Yesterday we switched to using a different maxwell user & password. We made sure that both the users have the same privileges & grants.

I am facing a curious situation whereby everything seems to be working just fine for few hours & then suddenly maxwell stops. The exception I am seeing is,
```23:59:32,905 INFO  OpenReplicator - starting replication at mariadb-bin.008704:137856555
23:59:32,918 INFO  TaskManager - stopping 4 tasks
23:59:32,918 ERROR TaskManager - cause:
java.lang.RuntimeException: Couldn't find database credentials
	at com.zendesk.maxwell.replication.TableCache.processEvent(TableCache.java:24) ~[maxwell-1.10.3.jar:1.10.3]
	at com.zendesk.maxwell.replication.TableCache.processEvent(TableCache.java:42) ~[maxwell-1.10.3.jar:1.10.3]
	at com.zendesk.maxwell.replication.MaxwellReplicator.getTransactionRows(MaxwellReplicator.java:242) ~[maxwell-1.10.3.jar:1.10.3]
	at com.zendesk.maxwell.replication.MaxwellReplicator.getRow(MaxwellReplicator.java:337) ~[maxwell-1.10.3.jar:1.10.3]
	at com.zendesk.maxwell.replication.AbstractReplicator.work(AbstractReplicator.java:157) ~[maxwell-1.10.3.jar:1.10.3]
	at com.zendesk.maxwell.util.RunLoopProcess.runLoop(RunLoopProcess.java:27) ~[maxwell-1.10.3.jar:1.10.3]
	at com.zendesk.maxwell.Maxwell.startInner(Maxwell.java:189) ~[maxwell-1.10.3.jar:1.10.3]
	at com.zendesk.maxwell.Maxwell.start(Maxwell.java:137) [maxwell-1.10.3.jar:1.10.3]
	at com.zendesk.maxwell.Maxwell.main(Maxwell.java:209) [maxwell-1.10.3.jar:1.10.3]
23:59:32,921 INFO  StoppableTaskState - MaxwellKafkaProducerWorker requestStop() called (in state: RUNNING)
23:59:32,921 INFO  KafkaProducer - Closing the Kafka producer with timeoutMillis = 9223372036854775807 ms.
23:59:32,981 INFO  StoppableTaskState - com.zendesk.maxwell.schema.PositionStoreThread requestStop() called (in state: RUNNING)
23:59:32,981 INFO  StoppableTaskState - com.zendesk.maxwell.replication.MaxwellReplicator requestStop() called (in state: STOPPED)
23:59:32,994 INFO  Server - jetty-9.2.21.v20170120
23:59:33,020 INFO  ContextHandler - Started o.e.j.s.ServletContextHandler@4b04f2f3{/,null,AVAILABLE}
23:59:33,028 INFO  ServerConnector - Started ServerConnector@4b08e64d{HTTP/1.1}{0.0.0.0:8080}
23:59:33,028 INFO  Server - Started @3033ms
23:59:33,688 INFO  TaskManager - stopped all tasks
java.lang.RuntimeException: Couldn't find database credentials
	at com.zendesk.maxwell.replication.TableCache.processEvent(TableCache.java:24)
	at com.zendesk.maxwell.replication.TableCache.processEvent(TableCache.java:42)
	at com.zendesk.maxwell.replication.MaxwellReplicator.getTransactionRows(MaxwellReplicator.java:242)
	at com.zendesk.maxwell.replication.MaxwellReplicator.getRow(MaxwellReplicator.java:337)
	at com.zendesk.maxwell.replication.AbstractReplicator.work(AbstractReplicator.java:157)
	at com.zendesk.maxwell.util.RunLoopProcess.runLoop(RunLoopProcess.java:27)
	at com.zendesk.maxwell.Maxwell.startInner(Maxwell.java:189)
	at com.zendesk.maxwell.Maxwell.start(Maxwell.java:137)
	at com.zendesk.maxwell.Maxwell.main(Maxwell.java:209)
```

This is weird because we did not do any restarts of the machine running maxwell. Also to confirm I tried to feed in a wrong password to maxwell & it immediately threw an exception (as expected) like so,
```
00:05:13,137 ERROR Maxwell - SQLException: Access denied for user 'cms_maxwell'@'ip-192-168-239-108.ec2.internal' (using password: YES)
00:05:13,137 ERROR Maxwell - Access denied for user 'cms_maxwell'@'ip-192-168-239-108.ec2.internal' (using password: YES)
```

So I don't know what's going on here, can someone throw a light on it?

**Comment by timbertson** [comment]
Ahh, that this is a very misleading message - maxwell is not failing to find your username / password, it's failing to find the current schema for the database named `credentials`: 

```
throw new RuntimeException("Couldn't find database " + dbName);
```

(https://github.com/zendesk/maxwell/blob/1cd01c5a6d87d7381e9cc078923bf1d47bfc3b74/src/main/java/com/zendesk/maxwell/replication/TableCache.java#L24)

This happens when maxwell sees a binlog event for a database which it has no record of. Have you recently added this database? If so, maxwell should have picked up the database addition and stored that information in its internal `maxwell.schemas` table - so this is still not expected, but may help you track down what's changed.

**Comment by tankchintan** [comment]
Ahh, that makes sense. I think I know what's up, but please correct me.

The erstwhile user just had access to `all_dbs.*` for `SELECT, REPLICATION SLAVE, REPLICATION CLIENT`.

But the new user has access to `main_db.*` for `SELECT, REPLICATION SLAVE, REPLICATION CLIENT`.

So once we switched to the new user, it no longer has visibility in to other dbs/schemas, which I thought was appropriate.

But curiously, I dont even ask `maxwell` to worry about `other_dbs`. I specifically ask it to track `main_db`. So why would it care about `other_dbs`?

Is there a solution for this, @timbertson?

**Comment by timbertson** [comment]
Aha, that makes some sense.

> I specifically ask it to track main_db

There are a few relevant settings: http://maxwells-daemon.io/config/

I presume you're using `include_dbs` / `exclude_dbs`, but that only controls what data gets generated. Maxwell still follows schema changes for all databases unless except for `blacklist_dbs`.

The reason for this difference in config is that a blacklisting is permanent - once you've told maxwell to ignore not just the data but also the structure of a database, you can't later decide to include that table/db later - maxwell would be unable to determine the schema.

I'm assuming this could be your issue, although I'm not 100% sure why - it seems as if you are _missing_ schema updates and yet somehow _seeing_ row updates, from that stacktrace. I would have expected you to see neither (if the permissions are restricting the data you see in the binlog) or both (if binlogs are a server-level permission, and it ignores database-level permissions).

Unfortunately for your use case it looks like you'd have to blacklist every DB other than `main_db`, as there is no equivalent `whitelist_dbs` config.

**Comment by tankchintan** [comment]
Hmm, ok, yeah that's what I feared (blacklisting every single DBs). 

So the options I have in front of me, are either blacklist every single db or let the user have select access on all dbs.

RE: the row levels visibility & schema level invisibility, is definitely curious.
