### ISSUE TITLE
how to run two maxwell

### ISSUE THREAD

**Issue by jayws** [zendesk/maxwell#689]
hi,how to run two maxwell?i have set the different --client_id,but the kafka topic is not data.is the client_id db user?can you give me an example?thanks!

**Comment by timbertson** [comment]
The `client_id` is just an arbitrary string, used by maxwell to namespace multiple client states. Are you seeing kafka output for one of the clients? or neither? If it's neither, your kafka settings are probably not right.

**Comment by saup007** [comment]
--client_id=100 --replica_server_id=100
--client_id=101 --replica_server_id=101

**Comment by osheroff** [comment]
@jayws, care to elaborate on your settings / config?

**Comment by osheroff** [comment]
closing for lack of response
