### ISSUE TITLE
Kafka partition is greater than the number of logical database, whether it can be used normally.

### ISSUE THREAD

**Issue by saup007** [zendesk/maxwell#694]
If kafka defaults to PartitionCount 20, ReplicationFactor 3
Maxwell defaults by producer_partition_by = db, but now there are only three databases (test_orca, test_bbbb, test _...), using kafka partition 6,0,19。

Can it work without a negative effect?

**Comment by timbertson** [comment]
It'll work, but it'll mean that you have 3 partitions with data, while the other 17 are empty, so for consumers three partitions will be doing all the heavy lifting. This will mean you can't scale up to more than 3 consumers.

If you want your load to be better balanced, that's when you might use a different partition strategy. But note that ordering in a kafka topic is per-partition, so if your partition strategy splits up a database's updates over multiple partitions a consumer won't see messages for a single DB in the order the events occurred.

**Comment by saup007** [comment]
I have three database 
bin/kafka-topics.sh --zookeeper ZK_HOST:2181 --create \
                    --topic maxwell --partitions 1 --replication-factor 3
