### ISSUE TITLE
json filed type generate error on ver 1.10.4

### ISSUE THREAD

**Issue by adhiemsumitro** [zendesk/maxwell#695]
I read that starting 1.7 maxwell should support JSON field type for MYSQL 5.7
with this combination, I got error : 

`16:46:22,788 ERROR AbstractBinlogParser - failed to parse binlog
java.lang.RuntimeException: assertion failed, unknown column type: 245
        at com.google.code.or.binlog.impl.parser.AbstractRowEventParser.parseRow(AbstractRowEventParser.java:187) ~[open-replicator-1.6.0.jar:?]
        at com.google.code.or.binlog.impl.parser.UpdateRowsEventV2Parser.parseRows(UpdateRowsEventV2Parser.java:79) ~[open-replicator-1.6.0.jar:?]
        at com.google.code.or.binlog.impl.parser.UpdateRowsEventV2Parser.parse(UpdateRowsEventV2Parser.java:67) ~[open-replicator-1.6.0.jar:?]
        at com.google.code.or.binlog.impl.ReplicationBasedBinlogParser.doParse(ReplicationBasedBinlogParser.java:159) ~[open-replicator-1.6.0.jar:?]
        at com.google.code.or.binlog.impl.AbstractBinlogParser$Task.run(AbstractBinlogParser.java:263) [open-replicator-1.6.0.jar:?]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_131]
16:46:22,888 WARN  MaxwellReplicator - open-replicator stopped at position master.000001:182785 -- restarting
16:46:22,982 INFO  OpenReplicator - starting replication at master.000001:182785
16:46:22,988 WARN  BinlogRowEventFilterImpl - failed to find TableMapEvent, header: BinlogEventV4HeaderImpl[timestamp=1499766382000,eventType=31,serverId=1,eventLength=73,nextPosition=182858,flags=0,timestampOfReceipt=1499766382985]`

**Comment by timbertson** [comment]
The JSON support is enabled by switching the binlog connector that we use. For now you still need to opt in to this via the `--binlog_connector` option - it took a little longer than expected to fully transition, but this new connector will be the default in 1.11.

**Comment by adhiemsumitro** [comment]
Here is what I tried , did I opt it correctly ?

> bin/maxwell --user='maxwell' --password='XXXXXX' --host='127.0.0.1' `--binlog_connector` --producer=stdout

The results : 
> 15:09:09,317 ERROR AbstractBinlogParser - failed to parse binlog
> java.lang.RuntimeException: assertion failed, unknown column type: 245
>         at com.google.code.or.binlog.impl.parser.AbstractRowEventParser.parseRow(AbstractRowEventParser.java:187) ~[open-replicator-1.6.0.jar:?]
>         at com.google.code.or.binlog.impl.parser.UpdateRowsEventV2Parser.parseRows(UpdateRowsEventV2Parser.java:78) ~[open-replicator-1.6.0.jar:?]
>         at com.google.code.or.binlog.impl.parser.UpdateRowsEventV2Parser.parse(UpdateRowsEventV2Parser.java:67) ~[open-replicator-1.6.0.jar:?]
>         at com.google.code.or.binlog.impl.ReplicationBasedBinlogParser.doParse(ReplicationBasedBinlogParser.java:159) ~[open-replicator-1.6.0.jar:?]
>         at com.google.code.or.binlog.impl.AbstractBinlogParser$Task.run(AbstractBinlogParser.java:263) [open-replicator-1.6.0.jar:?]
>         at java.lang.Thread.run(Thread.java:748) [?:1.8.0_131]
> 15:09:09,417 WARN  MaxwellReplicator - open-replicator stopped at position master.000003:1014841 -- restarting
> 15:09:09,494 INFO  OpenReplicator - starting replication at master.000003:1014841
> 15:09:09,500 WARN  BinlogRowEventFilterImpl - failed to find TableMapEvent, header: BinlogEventV4HeaderImpl[timestamp=1499933349000,eventType=31,serverId=1,eventLength=231,nextPosition=1015072,flags=0,timestampOfReceipt=1499933349497]
> ^C15:09:45,205 INFO  MaxwellContext - Sending final heartbeat: 1499933385205
> 15:09:45,314 INFO  AbstractReplicator - received final heartbeat 1499933385205; stopping replicator
> 15:09:45,416 INFO  TaskManager - Stopping 2 tasks
> 15:09:45,417 INFO  TaskManager - Stopping: com.zendesk.maxwell.schema.PositionStoreThread@1c14584b
> 15:09:45,417 INFO  StoppableTaskState - com.zendesk.maxwell.schema.PositionStoreThread requestStop() called (in state: RUNNING)
> 15:09:45,417 INFO  TaskManager - Stopping: com.zendesk.maxwell.replication.MaxwellReplicator@12d3b5b9
> 15:09:45,417 INFO  StoppableTaskState - com.zendesk.maxwell.replication.MaxwellReplicator requestStop() called (in state: STOPPED)
> 15:09:45,417 INFO  PositionStoreThread - Storing final position: Position[BinlogPosition[master.000003:1018025], lastHeartbeat=1499933385205]

**Comment by adhiemsumitro** [comment]
#619 seems has similar problem,  I will watch there and close this issue.
