### ISSUE TITLE
Master failover not working as expected

### ISSUE THREAD

**Issue by fancydba** [zendesk/maxwell#696]
Hey,

 I am trying to work on Maxwell HA. I point it originally to a slave and then kill the maxwell and start it up to replicate from a different slave. 
 I am not seeing the expected behavior of not finding a record in heartbeats and picking up another serverid entry from positions, following which the replication picks up from the last heartbeat of another server. 

Any help is appreciated. thanks

**Comment by timbertson** [comment]
Hmm, have you got some logs?

If I understand you correctly, it sounds like you're expecting a master failover recovery - i.e. maxell is now talking to a different server, so it will scan the new server's binlogs to figure out the position on this server corresponding to the last heartbeat of the previous instance.

This is all in the `com.zendesk.maxwell.recovery.Recovery` class, which is triggered by `getInitialPosition` in the `Maxwell` class (only when `master_recovery` config flag is true - have you checked that?). It is generally pretty good about logging what it's doing. Is the `recover()` method happening but then something goes wrong, or is it not being triggered at all?

**Comment by fancydba** [comment]
ERROR Recovery - Could not recover from master-change: old-server-id. This is what I see when I kill Maxwell to mimic a failure and bring it back up with a different master.

**Comment by fancydba** [comment]
Also, If I just kill mysql. Maxwell fails (as it should). When I bring it back up similar messages:
 WARN  Recovery - attempting to recover from master-change: old-server-id: 1, position: Position[BinlogPosition[886], lastHeartbeat=0]
INFO  OpenReplicator - starting replication at server2:2 
ERROR Recovery - Could not recover from master-change: old-server-id. binlog binlog1:886 , lastheartbeat=0.

**Comment by timbertson** [comment]
lastHeartbeat of 0 doesn't look good - if it doesn't have a heartbeat, it can't pinpoint that same heartbeat value in the new server's binlogs.

 - What version of maxwell are you running?
 - What's in your positions table?

A healthy example looks like:

```
maxwell> select * from positions;
+-----------+---------------+-----------------+----------+-----------+--------------+---------------------+
| server_id | binlog_file   | binlog_position | gtid_set | client_id | heartbeat_at | last_heartbeat_read |
+-----------+---------------+-----------------+----------+-----------+--------------+---------------------+
|      3007 | master.000012 |         1952674 | NULL     | maxwell   |         NULL |       1499052481327 |
+-----------+---------------+-----------------+----------+-----------+--------------+---------------------+
1 row in set (0.00 sec)
```

`heartbeat_at` is old and can be ignored, but `last_heartbeat_read` should definitely be non-zero.

You need to run the initial server for long enough that it creates a heartbeat, and stores a position for this heartbeat. This should happen within a handful of seconds though, so I doubt that's the issue.
