### ISSUE TITLE
QUESTION: Is it possible for there to be a config which would call a function on select columns when fetching data?

### ISSUE THREAD

**Issue by tankchintan** [zendesk/maxwell#700]
I wanted to know if there is even a remote possibility so that I can have maxwell fetch data for a field after applying mysql function on it?

My use case is, there are certain fields in some of the tables which are in `latin1` encoding. So we already have a mysql function in place which converts the data for that field in to `utf8`.

The benefit of maxwell producer emitting the already encoded stream is, that no other consumers will have to do these conversions in their code. Also with experimentation I have found out that in my downstream Kafka Consumers I have not been able to faithfully convert the original stream in to UTF8 without mistranslating.

I understand that this would involve fair amount of customization. But if I can find out that it's possible & an approximate place where I can start working on it, I would appreciate it.

I might even submit a PR (should you think it is ok to have these sort of customizations in maxwell).

**Comment by osheroff** [comment]
agree with @timbertson here; maxwell should be doing the right thing by default and outputting the column as utf-8.  If it's not see if you can't provide a repro.

**Comment by tankchintan** [comment]
Makes sense @timbertson @osheroff 

So below I will post some examples which lost something in translation. To give you some context, all of these inputs were in utf8 to begin with e.g. Kanji characters or Cyrillic etc. But our DB was not setup in optimum manner. It has table collation as `latin1` w/ `latin1_swedish_ci`.

So these non-ASCII characters were stored in `latin1` & we have code in between which will retrieve it in the proper manner in our app (which doesn't use Kafka/Maxwell setup).

Long story short, it is 
> non-ASCII characters (by user) => latin1(in DB) => UTF8 (via maxwell) => UTf8 (in Kafka) => Consumer

|In DB|What it is in Kafka|What it actually should be|
|------|---------------------|-----------------------------|
|`ä¼Šè—¤ãã‚" A to E` | `ä¼Šè—¤ã��ã‚“ A to E` | `伊藤くん A to E`|
|å°†å›½ã®ã‚¢ãƒ«ã‚¿ã‚¤ãƒ«|å°†å›½ã�®ã‚¢ãƒ«ã‚¿ã‚¤ãƒ«|将国のアルタイル|
|Ð' ÐºÑ€ÑƒÐ³Ðµ Ð¿ÐµÑ€Ð²Ð¾Ð¼ 01|Ð’ ÐºÑ€ÑƒÐ³Ðµ Ð¿ÐµÑ€Ð²Ð¾Ð¼ 01|В круге первом 01|

Right now I am going back to the DB again for getting the data which is encoded weirdly. When I fetch from DB, we already have code which will tell Hibernate to execute a function on specific columns.

This function is of the manner,
```CREATE DEFINER=`abcde`@`%` FUNCTION `Latin1_To_Utf8`(str varchar(4096)) RETURNS varchar(4096) CHARSET utf8
    DETERMINISTIC
RETURN CONVERT(CONVERT(CONVERT( str USING LATIN1) USING BINARY) USING UTF8)```

For what's it worth I had the below code that used to encode / decode strings, which I thought worked (well at least for some of the samples.)
```
StringUtils.toEncodedString(input.getBytes("ISO-8859-1"), Charset.forName("UTF-8")));
```
