### ISSUE TITLE
Unable to run Maxwell against a read access only Replica

### ISSUE THREAD

**Issue by josephjaniga** [zendesk/maxwell#701]
My organization has the requirement of not allowing Maxwell to run against our production live database which is currently already heavily overworked.

Our option is to instead point Maxwell at one of our MySQL replicas that is kept up to date by the replication process.  This database is globally read only and this works for the most part with the exception of the new Maxwell schema.  **Maxwell Bootstrapping** currently requires all of the Maxwell specific schema / tables to be on the same database as the target data / binlogs to be parsed.

The ideal solution is to allow Maxwell to have multiple unique configuration settings to house its schema on a separate database.  That way we're not writing to a replica, and we can provide proper DR for the "maxwellSchema" as well.

We have been unable to find or update the configuration settings to tell Maxwell to have its schema on a separate database.  I could find no documentation other than the looking through the `MaxwellConfig.java` source that appears to be defaulting all of the `MaxwellMysqlConfigs` to the same values.

**Is there a reason for Maxwell Bootstrappings "same database requirement/functionality"?**

It seems like this change would be technically viable looking at the source, but I am very curious to why it was written this way?   Possibly to limit complexity of multiple MySQL connections?

Thanks
-Joe

**Comment by osheroff** [comment]
>  Maxwell currently requires all of the Maxwell specific schema / tables to be on the same database as the target data / binlogs to be parsed.

nope, not true.  check out http://maxwells-daemon.io/config/#schema-storage-host-vs-replica-host -- you can configure separate schema-store hosts and binlog-hosts with the `--replication_host` (and similar) parameters.

**Comment by josephjaniga** [comment]
My colleagues inform me an important item I missed here , is that Maxwell Bootstrapping in async mode is not working with this setup.  Is that intended - can bootstrapping work with seperate schema storage host and replica host?

Please and thanks!

**Comment by osheroff** [comment]
Ah yes.  That is true, bootstrapping doesn't work in that config due to how it's currently implemented.  There's a PR to fix it, but it needs more work.  I started some of that work but then wandered off.

**Comment by josephjaniga** [comment]
Thank you very much for the information, this helps clear some things up!  Do you think you might have time to discuss that pull request sometime in the near future and could you point me to that PR?  Our development team is very interested in Maxwell, but this issue is a big blocker for us.  Depending on the circumstances, we may decide to pick up where that pull request was left off and completing it.

Again thanks much, and I would love to pick your brain on this if you have some time.

**Comment by osheroff** [comment]
Here's the PR https://github.com/zendesk/maxwell/pull/653

My last comment on it might be a bit vague, LMK once you get your head into the code and I or someone can answer questions

**Comment by osheroff** [comment]
bootstrapping works on replicas as of 1.22.0
