### ISSUE TITLE
`config.properties` - Regular Expressions for Include/Exclude not working

### ISSUE THREAD

**Issue by josephjaniga** [zendesk/maxwell#702]
In this scenario we have a set of multiple tables (that is constantly growing), those tables follow this pattern: 

- documents_1
- documents_2
- documents_3
- `...`
- documents_N

Currently Maxwell runs smoothly when the following settings are designated in the `config.properties` file:

- Literal list of mysql schemas
- Default configuration for all tables in those schemas (no include_tables entry)

But when using regular expressions as follows for:

- Literal list of mysql schemas
- Include tables by regular expression.
  - `include_tables=/documents_\d+/`

In this scenario Maxwell runs without errors, but no longer identifies or picks up any changes.

**Comment by ericwush** [comment]
@josephjaniga The correct expression should be `include_tables=/documents_\\d+/`. Config example file will be updated accordingly.
