### ISSUE TITLE
SELECT * from table (bootstrapping) initial loads of a table. Please provide a case.

### ISSUE THREAD

**Issue by Hackeruncle** [zendesk/maxwell#704]
I read the http://maxwells-daemon.io/, I can't understand how to do.
So please provide a case for it,thanks.
@smferguson

**Comment by smferguson** [comment]
I'm a bit unclear what you're asking. I think you're looking for a use-case. I'll also include an example.

Use case:
There are a few reasons you would want to bootstrap a table or database. The main one we've encountered is that you want all the table's (or database's) data in Kafka, but Maxwell was connected long after the database was initialized - in our case years after. We used bootstrap to play the existing state into Kafka, then stream changes once it's complete.

Example:
You can either use Maxwell's bootstrap-utility `maxwell-bootstrap` (in the `bin/` dir) or insert a row directly into the `maxwell.bootstrap` table:
`insert into maxwell.bootstrap (database_name, table_name) values ("fooDB", "barTable");`

Hope this helps.

**Comment by Hackeruncle** [comment]
I select  the second way of "insert into maxwell.bootstrap (database_name, table_name) values ("fooDB", "barTable");" , to produce  all data binlog of this database.table.
Thanks, @smferguson
