### ISSUE TITLE
Maxwell output fails to detect updates on NULL fields in json generated in Kafka 

### ISSUE THREAD

**Issue by vmishra** [zendesk/maxwell#708]
We are using Maxwell 1.10.3. In spite of explicitly setting `output_nulls=true`  in `maxwell/config.properties` the JSON generated on the Kafka doesn't have fields which have` "null"` values.  

The problem becomes even serious when the subsequent updates on the row to a valid not-null value (which was initially null) doesn't show up in the following update block.

For example pulling out a sample record from Kafka, The following insert record doesn't have "sig_id" because it was initially null. Doesn't show up the insert JSON. Subsequently, `"sig_id"` is set to NR but "old" data block fails to notice the change.

I thought the issue got fixed as part of #402 But not really, in our case.

```
{
  "database": "transaction",
  "table": "blah",
  "type": "insert",
  "ts": 1500908532,
  "xid": 1249355595,
  "commit": true,
  "data": {
    "id": "1234",
    "created_by": "blah",
    "created_time": "2017-07-24 15:02:13",
    **"lock_id": 1,**
    "modified_by": "blah",
    "modified_time": "2017-07-24 15:02:13",
    "state": "CA",
    "username": "blah"
  }
}



{
  "database": "transaction",
  "table": "blah",
  "type": "update",
  "ts": 1500908532,
  "xid": 1249355884,
  "commit": true,
  "data": {
    "id": "1234",
    "created_by": "blah",
    "created_time": "2017-07-24 15:02:13",
    **"lock_id": 2,**
    "modified_by": "blah",
    "modified_time": "2017-07-24 15:02:13",
    **"sig_id": "NR",**
    "state": "CA",
    "username": "blah"
  },
  "old": {
    "lock_id": 1
  }
}
```

**Comment by osheroff** [comment]
hmmm, I can't reproduce this locally.  can you dump out your `config.properties` and maybe the schema of the table involved?  Does this happen to you for other tables/fields as well?

**Comment by vmishra** [comment]
I updated the Maxwell version and did a bunch of debugging but to no avail, For insert records, Maxwell is still not including the null fields in "data" section of the JSON dumped into Kafka. The update record has the field with not null value (which is previously null and not included in the insert record ) in the data section. But not in the "old" section of JSON.

Please find attached maxwell.config properties (renamed at .txt because of upload restrictions)
[config.properties.txt](https://github.com/zendesk/maxwell/files/1193587/config.properties.txt)

Also, Following is the schema definition for the table, Unfortunately, we are currently only dumping one table to Kafka as of now. I haven't seen this issue for other fields, mostly because they are not null fields.

 CREATE TABLE `blah` (
  `id` varchar(25) COLLATE latin1_general_cs NOT NULL,
  `created_by` varchar(20) COLLATE latin1_general_cs NOT NULL,
  `created_time` datetime NOT NULL,
  `lock_id` int(11) NOT NULL DEFAULT '0',
  `modified_by` varchar(20) COLLATE latin1_general_cs NOT NULL,
  `modified_time` datetime NOT NULL,
  `signature_id` varchar(25) COLLATE latin1_general_cs DEFAULT NULL,
  `state` varchar(24) COLLATE latin1_general_cs NOT NULL,
  `username` varchar(20) COLLATE latin1_general_cs NOT NULL,
  PRIMARY KEY (`id`),
) ENGINE=InnoDB DEFAULT CHARSET=latin1 COLLATE=latin1_general_cs

Any pointers are appreciated, Thanks

**Comment by osheroff** [comment]
meh, this one just got dropped, more than a year ago now.  I wonder what database server this was running, maybe it's a maria-db thing...
