### ISSUE TITLE
MariaDB 10.2 and binlog parse error?

### ISSUE THREAD

**Issue by bash99** [zendesk/maxwell#721]
MariaDB 10.2.7, I've got a exception

19:59:17,892 ERROR AbstractBinlogParser - failed to parse binlog
java.lang.RuntimeException: assertion failed!  We left 4 unconsumed bytes in the buffer for event: BinlogEventV4HeaderImpl[timestamp=1501588756000,eventType=19,serverId=1,eventLength=67,nextPosition=1678479,flags=0,timestampOfReceipt=1501588757889]
	at com.google.code.or.net.impl.EventInputStream.finishEvent(EventInputStream.java:73) ~[open-replicator-1.6.0.jar:?]
	at com.google.code.or.binlog.impl.ReplicationBasedBinlogParser.doParse(ReplicationBasedBinlogParser.java:166) ~[open-replicator-1.6.0.jar:?]
	at com.google.code.or.binlog.impl.AbstractBinlogParser$Task.run(AbstractBinlogParser.java:263) [open-replicator-1.6.0.jar:?]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_131]

binlog_format = ROW

**Comment by ericwush** [comment]
@bash99 I can start Maxwell with MariaDB 10.2.7 ok, seems it can also parse binlog without errors. Can you elaborate the steps to reproduce this issue?

**Comment by bash99** [comment]
Sorry for delayed reply:

it's just continue output

17:03:53,680 WARN  BinlogConnectorReplicator - Unhandled QueryEvent inside transaction: QueryEventData{threadId=0, executionTime=0, errorCode=0, database='', sql='# Dummy event replacing event type 160 that slave cannot handle.                                        '}

MariaDB version is "10.2.8-MariaDB-10.2.8+maria~xenial-log mariadb.org binary distribution"

binlog related config

MariaDB [(none)]> show variables like '%binlog%';
```
+-----------------------------------------+----------------------+
| Variable_name                           | Value                |
+-----------------------------------------+----------------------+
| binlog_annotate_row_events              | ON                   |
| binlog_cache_size                       | 32768                |
| binlog_checksum                         | CRC32                |
| binlog_commit_wait_count                | 0                    |
| binlog_commit_wait_usec                 | 100000               |
| binlog_direct_non_transactional_updates | OFF                  |
| binlog_format                           | ROW                  |
| binlog_optimize_thread_scheduling       | ON                   |
| binlog_row_image                        | FULL                 |
| binlog_stmt_cache_size                  | 32768                |
| encrypt_binlog                          | OFF                  |
| gtid_binlog_pos                         | 0-1-51               |
| gtid_binlog_state                       | 0-1-51               |
| innodb_locks_unsafe_for_binlog          | OFF                  |
| max_binlog_cache_size                   | 18446744073709547520 |
| max_binlog_size                         | 104857600            |
| max_binlog_stmt_cache_size              | 18446744073709547520 |
| read_binlog_speed_limit                 | 0                    |
| sync_binlog                             | 0                    |
| wsrep_forced_binlog_format              | NONE                 |
+-----------------------------------------+----------------------+
```

event related config

```
MariaDB [(none)]> show variables like '%event%';
+--------------------------------------------------------+-----------+
| Variable_name                                          | Value     |
+--------------------------------------------------------+-----------+
| binlog_annotate_row_events                             | ON        |
| event_scheduler                                        | OFF       |
| performance_schema_events_stages_history_long_size     | -1        |
| performance_schema_events_stages_history_size          | -1        |
| performance_schema_events_statements_history_long_size | -1        |
| performance_schema_events_statements_history_size      | -1        |
| performance_schema_events_waits_history_long_size      | -1        |
| performance_schema_events_waits_history_size           | -1        |
| replicate_annotate_row_events                          | ON        |
| replicate_events_marked_for_skip                       | REPLICATE |
+--------------------------------------------------------+-----------+
```

**Comment by mayanksamrat** [comment]
Any Update on this, I am also getting same issue with mariaDB 10

**Comment by xuebingli** [comment]
@ericwush I managed to reproduce the error locally with docker and Maxwell v1.10.6.

With MariaDB 10.1.28
```
$ docker run --rm --name mariadb -e MYSQL_ROOT_PASSWORD=password123 -d  mariadb:10.1.28 --server-id=1 --log-bin=master --binlog_format=row
$ docker run -it --rm --link mariadb:mariadb zendesk/maxwell:v1.10.6 bin/maxwell --user=root --password=password123 --host=mariadb --producer=stdout
01:05:13,952 WARN  MaxwellMetrics - Metrics will not be exposed: metricsReportingType not configured.
01:05:14,356 INFO  SchemaStoreSchema - Creating maxwell database
01:05:14,427 INFO  Maxwell - Maxwell v1.10.6 is booting (StdoutProducer), starting at Position[BinlogPosition[master.000002:4094], lastHeartbeat=0]
01:05:14,617 INFO  AbstractSchemaStore - Maxwell is capturing initial schema
01:05:14,907 INFO  BinlogConnectorReplicator - Setting initial binlog pos to: master.000002:4094
01:05:14,980 INFO  BinaryLogClient - Connected to mariadb:3306 at master.000002/4094 (sid:6379, cid:7)
...
$ docker stop mariadb
```
With MariaDB 10.2.8
```
$ docker run --rm --name mariadb -e MYSQL_ROOT_PASSWORD=password123 -d  mariadb:10.2.8 --server-id=1 --log-bin=master --binlog_format=row # note the version number
$ docker run -it --rm --link mariadb:mariadb zendesk/maxwell:v1.10.6 bin/maxwell --user=root --password=password123 --host=mariadb --producer=stdout
01:08:44,843 WARN  MaxwellMetrics - Metrics will not be exposed: metricsReportingType not configured.
01:08:45,242 INFO  SchemaStoreSchema - Creating maxwell database
01:08:45,308 INFO  Maxwell - Maxwell v1.10.6 is booting (StdoutProducer), starting at Position[BinlogPosition[master.000002:4189], lastHeartbeat=0]
01:08:45,475 INFO  AbstractSchemaStore - Maxwell is capturing initial schema
01:08:45,733 INFO  BinlogConnectorReplicator - Setting initial binlog pos to: master.000002:4189
01:08:45,838 INFO  BinaryLogClient - Connected to mariadb:3306 at master.000002/4189 (sid:6379, cid:13)
01:08:45,882 WARN  BinlogConnectorReplicator - Unhandled QueryEvent inside transaction: QueryEventData{threadId=0, executionTime=0, errorCode=0, database='', sql='# Dummy event replacing event type 160 that slave cannot handle.                                                                                                                                                                                                         '}
(repeats many times)
$ docker stop mariadb # clean up
```

**Comment by liulikun** [comment]
MariaDB is not fully supported yet, see this issue: #769

**Comment by amiryal** [comment]
With regards to these Dummy events, it is worth noting [this MariaDB ticket](https://mariadb.atlassian.net/browse/MDEV-225) ([archive.today link](https://archive.today/3szMZ)):
> # Replace with dummy events an event that is not understood by a slave to which it should be sent
> When new features are added we may want to add new binary log events. But
adding new events presents problems for replicating against older slaves that
do not understand the new event.

> […]

> The proposed solution here is that the master will for such older slaves not
just omit the event. Instead it will replace the event with a dummy event of
the same size - an empty query event (just a comment). The old slave will
execute the event (with no effect) and avoid becoming confused or failing on
unknown event.

> […]

> As dummy event we will use an empty query holding just a comment, like this:
> `# Dummy event replacing event type %u that slave cannot handle.`
> The comment will be padded with spaces as needed, or truncated if the original
event is shorter (the whole idea is to supply the slave with a dummy event of
the same length, as old slaves do not tolerate holes in the binlog stream).

> […]

> The slave will, when connecting, set a user variable
`@mariadb_slave_capability`. The master will read the value of this variable
and use it to determine the capabilities of the slave. This is more robust and
flexible than relying on version numbers, since ideally any version master
should be able to replicate against any version slave. When we release the
code in a master, it is hard to predict what slave capabilities every possible
version of future releases will have - especially with multiple forks/branches
of MySQL being developed individually. And announcing the slave capabilities
explicitly allows the slave code full flexibility in working correctly against
older masters. […]

> […]
