### ISSUE TITLE
How can i get history data message to kafka

### ISSUE THREAD

**Issue by AlvinYang-2017** [zendesk/maxwell#724]
i know maxwell can get incremental data to kafka,  if i want get history data(all table records probably 30 million records) to kafka , what should i do? use Using the maxwell-bootstrap utility?

**Comment by liulikun** [comment]
You can use `--init_position=FILE:POSITION:HEARTBEAT` option to make maxwell start with a position in the past.

**Comment by timbertson** [comment]
`--init_position` works if you need to reprocess some binlogs, but if you want to publish all the data currently in your DB to kafka, then yes - `maxwell-bootstrap` is the right way to do that - see docs at http://maxwells-daemon.io/bootstrapping/

**Comment by luyee** [comment]
acturally,  with update for online  bussiness , the implement of [Debezium Connector for MySQL]
(http://debezium.io/docs/connectors/mysql/)  may works well for binlog ,the position is needed  when incremental ,
