### ISSUE TITLE
Difficulty configuring maxwell to use SSL

### ISSUE THREAD

**Issue by dougmack** [zendesk/maxwell#731]
Having difficulty configuring maxwell to use ssl.  Using settings as described in this post https://github.com/zendesk/maxwell/issues/711.  In addition setting parameters in config.properties to connect to mysql as follows:
# mysql login info
host=127.0.0.1
port=3310
user=sslmax
password=ssl123
jdbc_options=autoReconnect=true&verifyServerCertificate=true&useSSL=true&requireSSL=true

Maxwell appears to connect to the database then an exception is raised in com.github.shyiko.mysql.binlog.BinaryLogClient.authenticate, at which point maxwell shuts down.  Can provide logs :)

**Comment by osheroff** [comment]
we cleaned up ssl handling awhile ago.  optimistically closing this issue, feel free to re-open
