### ISSUE TITLE
The CDC replicator (Maxwell) process doesn't automatically pick up the inserted row from bootstrap table and starts bootstrapping Kafka.

### ISSUE THREAD

**Issue by vmishra** [zendesk/maxwell#732]
I am on the latest version of `Maxwell`.  The Maxwell process (CDC replicator) is running and replicating data to Kafka normally. Now, I want to Bootstrap some old data from the same table & same DB.

Using the maxwell-bootstrap script I started I gave all the details along with the following condition

`--where "id >= '160808105845932Z010023002' AND id <= '170812090729316Z010051389'"
`
I started getting the following logs:

```
22:23:36,272 INFO  MaxwellBootstrapConnectionPool - MaxwellBootstrapConnectionPool: Getting connection (user/password): jdbc:mysql://127.0.0.1:3306/maxwell
Sat Aug 16 22:23:36 UTC 2017 WARN: Establishing SSL connection without server's identity verification is not recommended. According to MySQL 5.5.45+, 5.6.26+ and 5.7.6+ requirements SSL connection must be established by default if explicit option isn't set. For compliance with existing applications not using SSL the verifyServerCertificate property is set to 'false'. You need either to explicitly disable SSL by setting useSSL=false, or set useSSL=true and provide truststore for server certificate verification.
22:23:36,597 INFO  MaxwellBootstrapConnectionPool - MaxwellBootstrapConnectionPool: Created a new connection
22:23:36,599 INFO  MaxwellBootstrapUtility - counting rows
22:23:50,127 INFO  MaxwellBootstrapUtility - inserting bootstrap start row
```
 
Then the processes paused logging for few minutes. No new info on the log. I could see that both `Maxwell` and `maxwell-bootstrap` was running in the background. Nothing happened for a while and I was monitoring the Kafka as well, I did not see any events coming in.

I killed the `Maxwell` process and restarted it, The Bootstrap process started and I could see messages flowing in Kafka and within few minutes the bootstrap process was completed with the following message:

`22:41:49,278 INFO  MaxwellBootstrapUtility - done.`

**Here are a few questions in this regard:**

1. I understand that it's the Maxwell process which does the bootstrapping, not the bootstrap utility. It merely inserts a row in the bootstrap table. But why did Maxwell daemon not automatically pick the row, even though Maxwell process was running, I had to restart it. Is it a normal behavior?

2. I also noticed that the bootstrapping process was quite fast, Does the bootstrapping module read data from MySQL bin logs or from Database?

3. Is there a possibility that `Maxwell` ends up sending duplicate data in Kafka. Let's say, My table has ID from `1 to 500` then I enabled row logging when ID was 400 and start Maxwell daemon. So ideally, all records from ID 400 to 500 gets replicated in the Kafka. Now If I start a bootstrap process with a condition from ID 1 to 450. Will Records 400 to 450 will get bootstrapped all over again, Even though it is present in Kafka? 

I appreciate you reading through the details and taking the time to answer these queries, I've read all the documentation, looked up the web and all the old issues but could not find a clear answer to these question. I would appreciate if you can answer these concerns.

**Comment by osheroff** [comment]
i think this is an issue from an old maxwell, before we rewrote a bunch of the bootstrap code.
