### ISSUE TITLE
How to resend record when Kafka failed

### ISSUE THREAD

**Issue by zhouyuze** [zendesk/maxwell#737]
I found that if Kakfa failed, I will get a timeout exception. But maxwell still mark it completed and update the position. Is there any way to resend these records when Kafka recover?

https://github.com/zendesk/maxwell/blob/e910d19cb874f5204b452a7b9ca518b11f28cfd4/src/main/java/com/zendesk/maxwell/producer/MaxwellKafkaProducer.java#L62-L90

**Comment by liulikun** [comment]
You can set `ignore_producer_error` to `false` in your config, then maxwell will crash on those errors. You'll need to have a process which auto restarts maxwell. maxwell will be in the crash loop until Kafka has recovered from the error.
