### ISSUE TITLE
It's a perfect tool for me, If I delete data from mysql,maxwell will get the what kind of result?

### ISSUE THREAD

**Issue by annisun** [zendesk/maxwell#741]
mysql> deletete from test.maxwell set daemon = 'firebus!  firebus!' where id = 1;
  maxwell: {
    "database": "test",
    "table": "maxwell",
    "type": "update",
    "ts": 1449786341,
    "xid": 940786,
    "commit": true,
    "data": {"id":1, "daemon": "Firebus!  Firebus!"}, // what will be change
    "old":  {"daemon": "Stanislaw Lem"}
  }

**Comment by timbertson** [comment]
See http://maxwells-daemon.io/dataformat/ (under "DELETE"). You'll get the `data` field populated with the previous row values.

**Comment by annisun** [comment]
thanks man, got it
