### ISSUE TITLE
when i run a sql  like  "CREATE DATABASE test  default char set 'utf8' "  the maxwell is error

### ISSUE THREAD

**Issue by rongyousu** [zendesk/maxwell#748]
first ,when i  run the sql "CREATE DATABASE test  default char set 'utf8'"  the mysql's script is  executable ,

bug  the maxwell is error:
ERROR MysqlParserListener - (create_database CREATE DATABASE (name (id wordsbase)) default char set 'utf8')
Although this script is problematic，but ,can make the maxwell to dead.

**Comment by liulikun** [comment]
Thanks for raising this issue. This fix is underway.
