### ISSUE TITLE
Produce only insert into Kafka topic

### ISSUE THREAD

**Issue by HaMo0n** [zendesk/maxwell#751]
I want to split insert and update from a table into two topics. one for update and one for insert
Is there any options to do this?

**Comment by ericwush** [comment]
What you wanted to achieve is not directly supported by maxwell. However you can always have a kafka consumer filtering/splitting events.

**Comment by Sonnbc** [comment]
This can be done if you run Maxwell in embedded mode (i.e.: add splitting logics to your wrapper)

**Comment by osheroff** [comment]
There's enough weird ass requests for so many different ways of slicing and dicing maxwell's output that I think it's time to explore allowing a little glob of JavaScript to run just before Maxwell sends to the producer, with full access to the Kafka topic and all the data.  Thoughts?

This is also where @shajith mocks me for a "sufficiently complex program".

**Comment by timbertson** [comment]
> full access to the Kafka topic and all the data

If we do go down this route I'd prefer to expose just the data at first (i.e. function(message) { return newMessage }) and see if that's enough - exposing the actual destination could get messy.

**Comment by jsalmeron** [comment]
Easy @HaMo0n, just have maxwell STDOUT and grep - pipe onto console producer and you're good to go

**Comment by osheroff** [comment]
now possible with javascript filters.
