### ISSUE TITLE
maxwell filtering db and table

### ISSUE THREAD

**Issue by Hackeruncle** [zendesk/maxwell#762]
version: 1.10.5
db1: t1,t2,t3
db2: t1,t2

**filtering:**
include_dbs = db1,db2
include_tables = t1,t2

When I exec this sql,insert a row in the maxwell.bootstrap table to trigger a bootstrap.
**insert into maxwell.bootstrap (database_name, table_name) values ("db1", "t3");**

**The log:**
```
15:22:36,215 INFO  Replicator - async bootstrapping: replaying 0 skipped rows...
15:22:36,215 INFO  Replicator - async bootstrapping: replay complete
15:22:36,216 INFO  SynchronousBootstrapper - bootstrapping ended for db1.t3
15:22:36,216 INFO  Replicator - async bootstrapping ended for db1.t3
```
The maxwell will  full scan the table for db1.t3 .
Why the table db1.t3 is't filtered?

**Comment by Hackeruncle** [comment]
I've tested the maxwell 1.10.6, the error is aslo existing.

**Comment by Hackeruncle** [comment]
@liulikun  Can you deal with this ? Thankyou.

**Comment by liulikun** [comment]
I think this is intended behavior. When you bootstrap a table, you want the records in this table to be published regardless.

**Comment by Hackeruncle** [comment]
@liulikun  
Actually, 

db1: t1,t2,t3
db2: t1,t2

line1.properties 
   client-id=1
   include_dbs = db1,db2
   include_tables = t1,t2

line2.properties
  client-id=2
   include_dbs = db1
   include_tables = t3

1. I start the two maxwell processes with two topics using the two properties file.
(line1.properties --> topic1)
(line2.properties --> topic2)

2.When I exec this sql,insert a row in the maxwell.bootstrap table to trigger a bootstrap.
insert into maxwell.bootstrap (database_name, table_name) values ("db1", "t3");

3.But, the two maxwell processes will both send the db1.t3 table to own kafka topic.
So, the db1.t3 table will be sended to topic1 , is wrong.

4.If db1.t3 data size is very large, and topic1 will receive the large data, 
bucause these business operations (spark streaming) will not use this db1.t3 data , 
this can lead to the nomal business operations.

**Comment by liulikun** [comment]
I see your use case now. You can try to use the `bin/maxwell-bootstrap` utility to run the bootstrap instead of using the bootstrap table: http://maxwells-daemon.io/bootstrapping/

**Comment by osheroff** [comment]
Not a solution, likun.  I think what he's asking for is either: 

- bootstrapping respects table filters, or
- being able to specify a client_id in a bootstrap

**Comment by Hackeruncle** [comment]
@liulikun @osheroff  
Thanks for quickly response.

1.When bootstrap the db1.t3, 
  the two maxwell client processes both send this table data to the own kafka topic.

2.Actually, i want that the client-id=2 maxwell process only send  this table data.

3.Other than, the client-id=1 also send this table data, is affect with the normal business.

**Comment by liulikun** [comment]
Sorry my mistake. bootstrap utility is also writing to the bootstrap table. To achieve your goal, bootstrap needs to check database/table filters, but it feels a bit redundant since the bootstrap is manually controlled.

**Comment by Hackeruncle** [comment]
But I think that this is about design architecture.
Bootstrap needs to check database/table filters, this is the most consistent user requirement.
Can you add the parameter to control the database/table filters?
**Such as:**
bootstrap_filter_check = false|true

**Comment by liulikun** [comment]
Another solution will be to configure maxwell to disable bootstrap (enabled by default), so you can selectively enable one or more maxwell processes to run the bootstrap.

**Comment by Hackeruncle** [comment]
@liulikun Thanks for quickly response.
no no no. This can't meet the user's need.
I can add this code with new bootstrap_filter_check parameter by myself.
