### ISSUE TITLE
Maxwell kafka cdc data lost with TimeoutException 

### ISSUE THREAD

**Issue by naveenkumara** [zendesk/maxwell#766]
Hi,
     We are running maxwell daemon connected to mysql and kafka cluster with 3 broker nodes. 
We have configured all  600 tables in maxwell. Default replication of all topics is 3 and partition count is 10. We see loss of data like kafka is not having all the events. We looked at http metrics of maxwell, we see below thing
"counters":{"MaxwellMetrics.messages.failed":{"count":266}

And logs of maxwell show below errors.

20:46:37,347 ERROR MaxwellKafkaProducer - Expiring 16 record(s) for maxwell_NextServices_STAFF-3 due to 100616 ms has passed since last append
20:46:37,347 ERROR MaxwellKafkaProducer - TimeoutException @ Position[BinlogPosition[mysql-bin.014131:4018350], lastHeartbeat=0] -- {"database":"NextServices","table":"
STAFF","pk.staff_id":23359}

kafka config for maxwell

kafka.compression.type=snappy
kafka.metadata.fetch.timeout.ms=120000
kafka.retries=5
kafka.acks=all
kafka.request.timeout.ms=100000
kafka.linger.ms=10000

Is there anything wrong in my config ?
I also see below warnings in log file, can we ignore this ?

07:06:43,604 WARN  NetworkClient - Error while fetching metadata with correlation id 459 : {maxwell_NextServices_STORE=LEADER_NOT_AVAILABLE}
07:06:43,772 WARN  NetworkClient - Error while fetching metadata with correlation id 460 : {maxwell_NextServices_STORE=LEADER_NOT_AVAILABLE}
07:06:43,892 WARN  NetworkClient - Error while fetching metadata with correlation id 461 : {maxwell_NextServices_STORE=LEADER_NOT_AVAILABLE}
07:06:44,143 WARN  NetworkClient - Error while fetching metadata with correlation id 462 : {maxwell_NextServices_STORE=LEADER_NOT_AVAILABLE}

**Comment by liulikun** [comment]
The issue was caused by Kafka. There are times when Kafka can be slow like doing rebalance, broker coming and going etc. One way to achieve better durability is to stop Maxwell when Kafka return errors. You can enable this feature by set `ignore_producer_error` to `false`. This way Maxwell will be terminated on publishing errors. You need to have a script to auto restart Maxwell, so the message will be published once Kafka is back to normal.
