### ISSUE TITLE
Parse MySQL comments in binlogs

### ISSUE THREAD

**Issue by xulianghong** [zendesk/maxwell#768]
Hi,

I'm wondering if Maxwell supports parsing MySQL comments in the binlogs? The comments are passed down to row-based binlogs with this option "binlog_rows_query_log_events" enabled, which will include the query string (containing comments) together with the row mutations.

To clarify my question: this is what I'd like to achieve:

  mysql> insert into `test`.`maxwell` set id = 1, daemon = 'Stanislaw Lem' /* **my test comment** */;

  maxwell: {
    "database": "test",
    "table": "maxwell",
    "type": "insert",
    "ts": 1449786310,
    "xid": 940752,
    "commit": true,
    "data": { "id":1, "daemon": "Stanislaw Lem" },
    **"comment": "my test comment"**
  }

Is this feature currently supported in Maxwell already?

Thanks!
Lianghong

**Comment by liulikun** [comment]
Nope, it's not supported yet.

**Comment by jshuping** [comment]
This would be useful for us as well.

**Comment by saimon7** [comment]
👍

**Comment by saimon7** [comment]
@xulianghong @jshuping Check #806, maybe that's enough for you.

**Comment by osheroff** [comment]
I'm gonna go ahead and say #806 should be enough here, having maxwell smart enough to parse out the comments feels out of scope but it should be easy enough for a stream-consumer.

**Comment by jshuping** [comment]
I'm late to reply but thanks a bunch this is great!

**Comment by ivankennethwang** [comment]
Will this work even for ROW bin log replication? I can't seem to see my query comment at all.
