### ISSUE TITLE
Q: have you considered writing to AWS SQS, instead of Kinesis?

### ISSUE THREAD

**Issue by tinynet** [zendesk/maxwell#771]
It seems to me that SQS it's more suitable for a data integration scenario, rather than Kinesis.
Writing to an SQS fifo queue wouldn't be more scalable and appropriate?
I'd like to understand if it's something feasible with a little effort

thx

**Comment by ericwush** [comment]
@tinynet You are always welcome to create a pull request if you'd like to contribute to maxwell. You might want to refer to `RabbitmqProducer` implementation if considering SQS.

**Comment by liulikun** [comment]
There is a PR for this: https://github.com/zendesk/maxwell/pull/710

**Comment by tinynet** [comment]
Great, thank you, I'll have a look!

**Comment by osheroff** [comment]
got support for SQS in 1.12.0
