### ISSUE TITLE
Maxwell exit with error.

### ISSUE THREAD

**Issue by mayanksamrat** [zendesk/maxwell#772]
While starting maxwell getting below error. 
```
11:43:28,996 WARN  BinlogConnectorReplicator - replicator stopped at position: mysql-bin.002192:24132405 -- restarting
11:43:29,062 WARN  MaxwellContext - Timed out waiting for heartbeat 1507117404052
11:43:29,064 INFO  TaskManager - Stopping 3 tasks
11:43:29,064 INFO  TaskManager - Stopping: com.zendesk.maxwell.producer.MaxwellKafkaProducerWorker@27e89b15
11:43:29,064 INFO  StoppableTaskState - MaxwellKafkaProducerWorker requestStop() called (in state: RUNNING)
11:43:29,065 INFO  KafkaProducer - Closing the Kafka producer with timeoutMillis = 9223372036854775807 ms.
11:43:29,067 INFO  TaskManager - Stopping: com.zendesk.maxwell.schema.PositionStoreThread@593076d6
11:43:29,068 INFO  StoppableTaskState - com.zendesk.maxwell.schema.PositionStoreThread requestStop() called (in state: RUNNING)
11:43:29,068 INFO  TaskManager - Stopping: com.zendesk.maxwell.replication.BinlogConnectorReplicator@7309264d
11:43:29,068 INFO  StoppableTaskState - com.zendesk.maxwell.replication.BinlogConnectorReplicator requestStop() called (in state: RUNNING)
11:43:30,382 INFO  TaskManager - Stopped all tasks
java.lang.InterruptedException
    at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.reportInterruptAfterWait(AbstractQueuedSynchronizer.java:2014)
    at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(AbstractQueuedSynchronizer.java:2048)
    at java.util.concurrent.ArrayBlockingQueue.take(ArrayBlockingQueue.java:403)
    at com.zendesk.maxwell.producer.MaxwellKafkaProducerWorker.run(MaxwellKafkaProducer.java:168)
    at java.lang.Thread.run(Thread.java:745)```

**Comment by liulikun** [comment]
For which database? and version?

**Comment by mayanksamrat** [comment]
for mariadb 10.0.25-MariaDB.

**Comment by liulikun** [comment]
Sorry, MariaDb is not fully supported yet, check this issue: https://github.com/zendesk/maxwell/issues/769

**Comment by LeninGangwal** [comment]
For mysql 5.6, we are facing a similar issue. 

[WARN ] 2019-12-12 17:22:34.245 [Thread-6] MaxwellContext - Timed out waiting for heartbeat 1576151549237
[INFO ] 2019-12-12 17:22:34.246 [shutdownThread] TaskManager - Stopping 4 tasks
[INFO ] 2019-12-12 17:22:34.246 [shutdownThread] TaskManager - Stopping: com.zendesk.maxwell.schema.PositionStoreThread@3a6caf24
[INFO ] 2019-12-12 17:22:34.246 [shutdownThread] StoppableTaskState - com.zendesk.maxwell.schema.PositionStoreThread requestStop() called (in state: RUNNING)
[INFO ] 2019-12-12 17:22:34.247 [shutdownThread] TaskManager - Stopping: com.zendesk.maxwell.producer.MaxwellKafkaProducerWorker@34ab5619
[INFO ] 2019-12-12 17:22:34.247 [shutdownThread] StoppableTaskState - MaxwellKafkaProducerWorker requestStop() called (in state: RUNNING)
[DEBUG] 2019-12-12 17:22:34.247 [Position Flush Thread] MaxwellConnectionPool - MaxwellConnectionPool: Checkout - 1/1 (HitRate=99.84614%)
[INFO ] 2019-12-12 17:22:34.247 [shutdownThread] KafkaProducer - [Producer clientId=producer-1] Closing the Kafka producer with timeoutMillis = 9223372036854775807 ms.
[DEBUG] 2019-12-12 17:22:34.247 [Position Flush Thread] MysqlPositionStore - writing heartbeat: 1576151554247 (last heartbeat written: 1576151553555)
[DEBUG] 2019-12-12 17:22:34.247 [kafka-producer-network-thread | producer-1] Sender - [Producer clientId=producer-1] Beginning shutdown of Kafka producer I/O thread, sending remaining records.
