### ISSUE TITLE
Missing libraries in 1.10.8

### ISSUE THREAD

**Issue by mortensen** [zendesk/maxwell#783]
Why is the lib folder missing in the current release?

Just wanted to try the latest release. Getting following error now:

$:> bin/maxwell
Error: No matches for kafka version: 0.9
Supported versions:
ls: cannot access 'bin/../lib/kafka-clients': No such file or directory

**Comment by Hackeruncle** [comment]
@mortensen  copy kafka-client-xxxx.jar from your kafka env to the path of "lib/kafka-clients".

**Comment by mortensen** [comment]
which kafka-environment? ;) i am only using maxwell and rabbitmq. i copied the libs from the last release to  get it work. but i am wondering why it was removed.

**Comment by Hackeruncle** [comment]
I think that any other version of the jar was not specified at compile time.
![maxwell](https://user-images.githubusercontent.com/20901151/31536876-d383585c-b032-11e7-8013-8924774c6c80.png)

**Comment by xuebingli** [comment]
Thank you for reporting this issue. Related: #791 

This has been fixed in [v1.10.9](https://github.com/zendesk/maxwell/releases/tag/v1.10.9).
