### ISSUE TITLE
Question: duplicated events in kafka, can it happen?

### ISSUE THREAD

**Issue by paneq** [zendesk/maxwell#785]
Is it possible to receive duplicated events in kafka if maxwell process unexpectedly crashes? If yes, can it be prevented shomehow? Ie. using `enable.idempotence=true` mentioned in: https://www.confluent.io/blog/exactly-once-semantics-are-possible-heres-how-apache-kafka-does-it/

**Comment by xuebingli** [comment]
> Is it possible to receive duplicated events in kafka if maxwell process unexpectedly crashes?

I believe so. Maxwell supports at-least-once delivery.

> If yes, can it be prevented somehow? Ie. using `enable.idempotence=true`

IMO it can not be prevented with `enable.idempotence=true`. AFAIK `enable.idempotence=true` ensures exactly-once delivery of Kafka message in case of producer retries. It doesn't help when a producer publishes two or more messages with the same content. When Maxwell crashes and comes back up, it might pick up from a (slightly) old position in binary log and publish Kafka messages from db transactions that have been previously published.

**Comment by paneq** [comment]
That's what I assumed. This is similar to what debezium offers.

Have you considered using the new API https://cwiki.apache.org/confluence/display/KAFKA/KIP-98+-+Exactly+Once+Delivery+and+Transactional+Messaging#KIP-98-ExactlyOnceDeliveryandTransactionalMessaging-AnExampleApplication to make it possible to have no duplicates even in case of a crash?

**Comment by xuebingli** [comment]
@zendesk/goanna what do you think of the proposal? Is exactly-once delivery something of importance to our use case?

**Comment by liulikun** [comment]
@paneq Yes, you can take advantage of Kafka exactly-once delivery feature by setting Kafka producer configs in maxwell. If you check out maxwell config doc: http://maxwells-daemon.io/config, you can pass through any kafka producer config like this:
>Additionally, any configuration file options prefixed with 'kafka.' will be passed into the kafka producer library, after having 'kafka.' stripped off the front of the key. So, for example if config.properties contains
>kafka.batch.size=16384
>then Maxwell will send batch.size=16384 to the kafka producer library.

**Comment by paneq** [comment]
@liulikun But to have truly exactly once the code needs to use the transnational feature introduced recently that I mentioned https://cwiki.apache.org/confluence/display/KAFKA/KIP-98+-+Exactly+Once+Delivery+and+Transactional+Messaging#KIP-98-ExactlyOnceDeliveryandTransactionalMessaging-AnExampleApplication . Setting the producer options is not enough.

**Comment by liulikun** [comment]
From my understanding, the transaction api is to achieve atomicity: a group of messages are either all in or all out. It's a different feature compared with exactly once delivery semantics.

**Comment by paneq** [comment]
And for maxwell to remember the offset of last sent records from WAL it needs to send it together with the record changes in a single transaction exactly like the linked code example shows.

How would you otherwise achieve exactly once delivery semantics when maxwell crashes? If you read the offset from a different place than kafka then you can have 2 potential corner cases:

a) maxwell saved the offset locally but the transmistted changes not necessarly were stored in kafka
b) transmistted were stored in kafka but maxwell did not mange to save the offset locally 

which can lead to duplicated messages.

From what I understand setting the producer options only protects from some networking errors when sending data to kafka requires retrying. But it does not protect in case of a crash when the application sends the data again.

Correct me if I am wrong.

**Comment by liulikun** [comment]
That code example is about kafka streams: consume one topic, publish to another, so it manages the  exactly once delivery that way. maxwell is not consuming any kafka topics, it's only a producer. 

For scenario a): maxwell only saves the binlog position after successfully publishing the message (being acknowledged by kafka).

b): this could happen, maxwell saves it's binlog position to mysql, if that fails, we could publish the same message again. I don't have a good solution for this, not sure how kafka transaction api can solve this issue, but this case should be really rare.

**Comment by paneq** [comment]
> I don't have a good solution for this, not sure how kafka transaction api can solve this issue

I imagine it as: store the binlog position in kafka (instead of mysql), use transactions to send new messages and new binlog position together. Upon restart, read from kafka where to start reading from.

> but this case should be really rare.

indeed, but that doesn't change the fact that duplicated events can happen and my code needs to be aware of it.

**Comment by liulikun** [comment]
Yup, that sounds a good solution. Right now, maxwell can publish to quite a few different systems apart from kafka. If we go down this path, we have to maintain multiple ways of manage positions. Will discuss with other team members about this. Thanks for the idea!
