### ISSUE TITLE
when loading chinese from mysql .maxwell display  messy code

### ISSUE THREAD

**Issue by yester354** [zendesk/maxwell#79]
Hi
    I encounter a problem when using maxwell to load change  data from mysql . I insert a chinese in a table and it display normol in mysql but messy code in maxwell 
    in mysql:
    mysql> insert into a values("哈哈");
Query OK, 1 row affected (0.00 sec)

mysql> select * from a;
+------+
| col  |
+------+
| 测试 |
| 哈哈 |
+------+
2 rows in set (0.00 sec)

mysql> exit
Bye
[root@localhost maxwell-0.9.0]# echo $LANG
en_US.UTF-8 

in maxwell:
16:47:18,504 DEBUG SchemaPosition - Writing binlog position to maxwell.positions: BinlogPosition[master.000002:1832]
16:48:45,903 DEBUG NetworkClient - Initiating connection to node 1 at 10.89.131.15:9092.
16:48:45,907 DEBUG NetworkClient - Completed connection to node 1
16:48:45,918 DEBUG MaxwellKafkaProducer - ->  key:{"database":"test","table":"a","pk._uuid":"6fcd9885-d3a3-4d32-a0dc-064a119e8429"}, partition:1, offset:86427
16:48:45,918 DEBUG MaxwellKafkaProducer -    {"database":"test","table":"a","type":"insert","data":{"col":"¹þ¹þ"},"ts":1440406125}
16:48:45,919 DEBUG MaxwellKafkaProducer -    BinlogPosition[master.000002:7471]

it dispay "¹þ¹þ".

**Comment by osheroff** [comment]
Hmmm, I can't reproduce this, at least not trivially.   Can you give me:

- the mysql server version
- the character encoding and data type of the column
- the output of:

```
select 
   columns.name, columns.encoding as column_encoding, 
   tables.encoding as table_encoding, databases.encoding as database_encoding, 
   schemas.encoding as schema_encoding 
from maxwell.columns 
join maxwell.tables on tables.id = columns.table_id 
join maxwell.databases on maxwell.databases.id = tables.database_id 
join maxwell.schemas on maxwell.schemas.id = databases.schema_id 
where columns.name = 'col';
```

thanks.

**Comment by yester354** [comment]
@osheroff 
  Hi ,in my environment. the maxwell and mysql are in the same machine.my mysql version is 5.1.71
 the out put of the sql is：
mysql> select     columns.name, columns.encoding as column_encoding,     tables.encoding as table_encoding, databases.encoding as database_encoding,     schemas.encoding as schema_encoding  from maxwell.columns  join maxwell.tables on tables.id = columns.table_id  join maxwell.databases on maxwell.databases.id = tables.database_id  join maxwell.schemas on maxwell.schemas.id = databases.schema_id  where columns.name = 'col';
+------+-----------------+----------------+-------------------+-----------------+
| name | column_encoding | table_encoding | database_encoding | schema_encoding |
+------+-----------------+----------------+-------------------+-----------------+
| col  | utf8            | utf8           | utf8              | utf8            |
| col  | latin1          | latin1         | utf8              | utf8            |
| col  | NULL            | latin1         | utf8              | utf8            |
| col  | NULL            | latin1         | utf8              | utf8            |
+------+-----------------+----------------+-------------------+-----------------+
4 rows in set (0.00 sec)

 the mysql database character is utf8
 mysql> commit;
Query OK, 0 rows affected (0.00 sec)

mysql> show create database emon;
+----------+---------------------------------------------------------------+
| Database | Create Database                                               |
+----------+---------------------------------------------------------------+
| emon     | CREATE DATABASE `emon` /*!40100 DEFAULT CHARACTER SET utf8 */ |
+----------+---------------------------------------------------------------+
1 row in set (0.00 sec)

mysql> 

and the table character set utf8 
mysql> show table status like '%emon%';
+------+--------+---------+------------+------+----------------+-------------+-----------------+--------------+-----------+----------------+---------------------+-------------+------------+-----------------+----------+----------------+---------+
| Name | Engine | Version | Row_format | Rows | Avg_row_length | Data_length | Max_data_length | Index_length | Data_free | Auto_increment | Create_time         | Update_time | Check_time | Collation       | Checksum | Create_options | Comment |
+------+--------+---------+------------+------+----------------+-------------+-----------------+--------------+-----------+----------------+---------------------+-------------+------------+-----------------+----------+----------------+---------+
| emon | InnoDB |      10 | Compact    |    3 |           5461 |       16384 |               0 |            0 |   9437184 |           NULL | 2015-08-25 09:36:33 | NULL        | NULL       | utf8_general_ci |     NULL |                |         |
+------+--------+---------+------------+------+----------------+-------------+-----------------+--------------+-----------+----------------+---------------------+-------------+------------+-----------------+----------+----------------+---------+
1 row in set (0.00 sec)

mysql> 

and it can display chinese in mysql normally
mysql> select * from emon;
+--------+
| col    |
+--------+
|        |
| 测试 |
| 哈哈 |
+--------+

my server character set as below 
[root@localhost goldengate]# locale
LANG=en_US.UTF-8
LC_CTYPE="en_US.UTF-8"
LC_NUMERIC="en_US.UTF-8"
LC_TIME="en_US.UTF-8"
LC_COLLATE="en_US.UTF-8"
LC_MONETARY="en_US.UTF-8"
LC_MESSAGES="en_US.UTF-8"
LC_PAPER="en_US.UTF-8"
LC_NAME="en_US.UTF-8"
LC_ADDRESS="en_US.UTF-8"
LC_TELEPHONE="en_US.UTF-8"
LC_MEASUREMENT="en_US.UTF-8"
LC_IDENTIFICATION="en_US.UTF-8"
LC_ALL=

thanks for you replay

**Comment by osheroff** [comment]
sorry, can you add `AND tables.name = 'emon`` to the first SQL statement?  I want to see what encoding maxwell thinks the table has...

also, can you do `SHOW CREATE TABLE emon`?  that might give better info than "show table status"

**Comment by yester354** [comment]
Hi 
   it's ok now .it's the problem of the secureCRT settings .now it can display chinese well. thanks very much
