### ISSUE TITLE
Is Maxwell compatible with a MariaDB Galera cluster?

### ISSUE THREAD

**Issue by JeroenMinnaert** [zendesk/maxwell#792]
I would like to know if it's a good idea to point Maxwell to a MariaDB Galera Cluster using GTID replication?

Thanks!

**Comment by liulikun** [comment]
MariaDB is not fully supported yet.

**Comment by JeroenMinnaert** [comment]
Can I ask what isn't working yet?

**Comment by liulikun** [comment]
It's reported by other maxwell users: https://github.com/zendesk/maxwell/issues/769

**Comment by JeroenMinnaert** [comment]
Got it, thanks!
