### ISSUE TITLE
Encryption is not working in latest version.

### ISSUE THREAD

**Issue by Kabilan-techie** [zendesk/maxwell#803]
I found that encryption based configuration property named as "encrypt" in config.property file but different property name ("encryption") is used in code to read this same property value. Hence, the encrypt property configuration is not worked and it always disabled as it is a default value. I hope the fix is just rename the property name "encryption" into "encrypt" while read this property value in code.  I have attached github link for source java file.

https://github.com/zendesk/maxwell/blob/master/src/main/java/com/zendesk/maxwell/MaxwellConfig.java#LC470

Thanks.

**Comment by liulikun** [comment]
Thanks for reporting, will fix it in the next release.
