### ISSUE TITLE
Message Ordering inconformity

### ISSUE THREAD

**Issue by AlvinYang-2017** [zendesk/maxwell#804]
My topic have 5 partitions, I have been set  producer_partition_by=database, but the same database ddl and dml statement  were assigned to different partition, so caused consume message ordering inconformity. 

ddl message key : 3f083bf2-b5f7-4089-a6ed-0a47a00ddcda
dml message key :  {"database":"p2","table":"test_a","pk.id":1}

The reason may be message key format different cause  producer_partition_by function ineffective.
Who can tell me the real reason~  
thanks a lot.

@liulikun

**Comment by liulikun** [comment]
Did you config a different topic for ddl `ddl_kafka_topic`?

**Comment by osheroff** [comment]
this seems like a bit of a bug; DDL messages totally ignore producer_partition_by IIRC.  Obviously DDL messages would have to ignore producer_partition_by=column and sometimes =table (if the DDL applied to a database and not a table), but we should probably make a best-effort here.

**Comment by osheroff** [comment]
@AlvinYang-2017 getting back to this, are you using kafka or kinesis?

**Comment by osheroff** [comment]
oh, crud.  I think I see the issue.

**Comment by osheroff** [comment]
ddl statements now properly honor partitioning by database
