### ISSUE TITLE
Couldn't find table in com.zendesk.maxwell.replication.TableCache.processEvent

### ISSUE THREAD

**Issue by jchmielniak** [zendesk/maxwell#810]
Hi,

I received immediately after starting following Exception:

[maxwell-1.10.9]$ ./bin/maxwell --user='XXXX' --password='XXXX' --host='HOST' --port=13002 --producer=stdout
Using kafka version: 0.9
12:06:09,175 WARN  MaxwellMetrics - Metrics will not be exposed: metricsReportingType not configured.
12:06:09,515 INFO  Maxwell - Maxwell v?? is booting (StdoutProducer), starting at Position[BinlogPosition[binlog.000013:172519648], lastHeartbeat=0]
12:06:09,645 INFO  MysqlSavedSchema - Restoring schema id 1 (last modified at Position[BinlogPosition[binlog.000013:172519648], lastHeartbeat=0])
12:06:09,729 INFO  BinlogConnectorReplicator - Setting initial binlog pos to: binlog.000013:172519648
12:06:09,834 INFO  BinaryLogClient - Connected to HOST:13002 at binlog.000013/172519648 (sid:6379, cid:6571182)
12:06:09,834 INFO  BinlogConnectorLifecycleListener - Binlog connected.
12:06:09,891 INFO  BinlogConnectorLifecycleListener - Binlog disconnected.
12:06:09,892 INFO  TaskManager - Stopping 2 tasks
12:06:09,893 ERROR TaskManager - cause: 
java.lang.RuntimeException: Couldn't find table positions_tmp in database datapool
	at com.zendesk.maxwell.replication.TableCache.processEvent(TableCache.java:29) ~[maxwell-1.10.9.jar:?]
	at com.zendesk.maxwell.replication.BinlogConnectorReplicator.getTransactionRows(BinlogConnectorReplicator.java:189) ~[maxwell-1.10.9.jar:?]
	at com.zendesk.maxwell.replication.BinlogConnectorReplicator.getRow(BinlogConnectorReplicator.java:279) ~[maxwell-1.10.9.jar:?]
	at com.zendesk.maxwell.replication.AbstractReplicator.work(AbstractReplicator.java:148) ~[maxwell-1.10.9.jar:?]
	at com.zendesk.maxwell.util.RunLoopProcess.runLoop(RunLoopProcess.java:27) ~[maxwell-1.10.9.jar:?]
	at com.zendesk.maxwell.Maxwell.startInner(Maxwell.java:190) ~[maxwell-1.10.9.jar:?]
	at com.zendesk.maxwell.Maxwell.start(Maxwell.java:140) ~[maxwell-1.10.9.jar:?]
	at com.zendesk.maxwell.Maxwell.main(Maxwell.java:211) ~[maxwell-1.10.9.jar:?]

The user has SELECT Privileges on all Schemas and Tables.

Regards
jacek

**Comment by liulikun** [comment]
Did you change the code at all? By default, maxwell creates an internal table `positions` to store the binlog position during replication. I'm not sure if the table `positions_tmp` is for that table. If you can provide steps to reproduce the error, that'll be helpful.

**Comment by osheroff** [comment]
@liulikun check out the err message, "Couldn't find table positions_tmp in database datapool" -- it shouldn't have anything to do with the maxwell database itself.  Looks like maybe maxwell failed to capture the table?  I think if there's schema alters happening at the time maxwell does its first capture this is possible, never seen it in prouction though... 

(I think I was aware of the possible race while coding the schema-capture code, but I didn't want to lock all the damn tables.  Something like that.)

@jchmielniak, is `positions_tmp` a frequently dropped/created table by any chance?

**Comment by maniteja6799** [comment]
I have a similar case. using: maxwell-1.10.3
whenever we get a insert/delete/update in db this is coming.

`| 10:25:12,418 INFO  BinaryLogClient - Connected to 172.16.28.54:3306 at master.000011/564477414 (sid:6379, cid:137384)
phqa_maxwell.1.tkydd9trt75k@qa-master    | 10:25:12,699 DEBUG SchemaChange - SQL_PARSE <- "ALTER TABLE TASK.TAG CHANGE TAG_TEXT TAG_TEXT VARCHAR(255) COMMENT 'TEXT FOR THE TAG'"
phqa_maxwell.1.tkydd9trt75k@qa-master    | 10:25:13,086 DEBUG SchemaChange - SQL_PARSE ->   (parse (statement (alter_table (alter_table_preamble ALTER TABLE (table_name (db_name (name (id TASK))) . (name (id TAG)))) (alter_specifications (alter_specification (change_column CHANGE (old_col_name (name (id TAG_TEXT))) (column_definition (name (id TAG_TEXT)) (data_type (string_type VARCHAR (length ( 255 )) (column_options COMMENT (string_literal 'TEXT FOR THE TAG')))))))))) <EOF>)
phqa_maxwell.1.tkydd9trt75k@qa-master    | 10:25:13,094 DEBUG MysqlSavedSchema - findSchemaForPositionSHA: found schema_id: 151 for sha: c25c137d2768eb84267e0303b8c02340b92b9ba9
phqa_maxwell.1.tkydd9trt75k@qa-master    | 10:25:13,094 INFO  AbstractSchemaStore - storing schema @Position[BinlogPosition[master.000011:564477414], lastHeartbeat=0] after applying "ALTER TABLE TASK.TAG CHANGE TAG_TEXT TAG_TEXT VARCHAR(255) COMMENT 'TEXT FOR THE TAG'" to TASK, new schema id is 151
phqa_maxwell.1.tkydd9trt75k@qa-master    | 10:25:13,278 INFO  TaskManager - stopping 3 tasks
phqa_maxwell.1.tkydd9trt75k@qa-master    | 10:25:13,279 ERROR TaskManager - cause: 
phqa_maxwell.1.tkydd9trt75k@qa-master    | java.lang.RuntimeException: Couldn't find table schema_version in database TASK
phqa_maxwell.1.tkydd9trt75k@qa-master    |     at com.zendesk.maxwell.replication.TableCache.processEvent(TableCache.java:29) ~[maxwell-1.10.3.jar:1.10.3]
phqa_maxwell.1.tkydd9trt75k@qa-master    |     at com.zendesk.maxwell.replication.BinlogConnectorReplicator.getTransactionRows(BinlogConnectorReplicator.java:167) ~[maxwell-1.10.3.jar:1.10.3]
phqa_maxwell.1.tkydd9trt75k@qa-master    |     at com.zendesk.maxwell.replication.BinlogConnectorReplicator.getRow(BinlogConnectorReplicator.java:271) ~[maxwell-1.10.3.jar:1.10.3]
phqa_maxwell.1.tkydd9trt75k@qa-master    |     at com.zendesk.maxwell.replication.AbstractReplicator.work(AbstractReplicator.java:157) ~[maxwell-1.10.3.jar:1.10.3]
phqa_maxwell.1.tkydd9trt75k@qa-master    |     at com.zendesk.maxwell.util.RunLoopProcess.runLoop(RunLoopProcess.java:27) ~[maxwell-1.10.3.jar:1.10.3]
phqa_maxwell.1.tkydd9trt75k@qa-master    |     at com.zendesk.maxwell.Maxwell.startInner(Maxwell.java:189) ~[maxwell-1.10.3.jar:1.10.3]`
