### ISSUE TITLE
Could we change the Json format?

### ISSUE THREAD

**Issue by kimbc** [zendesk/maxwell#811]
Hi, It is very useful tool for me.

I want to sync the data from Mysql to AWS DynamoDB.

I can Extract Json data from Mysql using maxwell.

but I can't import the data into AWS DynamoDB. because the format is not same between Maxwell and DynamoDB.

so I want to change the Maxwell Json format.

Is it possible?

one more question.

where is the maxwell daemon source code that is exchanging binlog to json?

thanks.

**Comment by ericwush** [comment]
@kimbc Maxwell JSON format is not configurable however feel free to read `RowMap` class.

**Comment by alejobs** [comment]
Hi @kimbc , I would suggest sending maxwell cdc events to kinesis, then attach a lambda function to the stream that processes the records, changes the format, and inserts them into a dynamodb table.

**Comment by osheroff** [comment]
the `stdout` producer can be useful here too - pipe maxwell directly into an ETL script.  The other suggestions here can work too, more coding but also more reliable.
