### ISSUE TITLE
KPL doesn't handle destroying with SIGINT (Ctrl+C)

### ISSUE THREAD

**Issue by alejobs** [zendesk/maxwell#814]
Hi,

I have experienced some trouble shutting down Maxwell via SIGINT because KPL doesn't handle that very well. I have investigated it and it seems that it has been designed to be shutted down programatically. In this file you can see there are 2 JVM hooks that delete some necessary I/O files on SIGINT:
https://github.com/awslabs/amazon-kinesis-producer/blob/fd6ee0c1a29fa29fe5ab5c358d63cb2b043093d2/java/amazon-kinesis-producer/src/main/java/com/amazonaws/services/kinesis/producer/Daemon.java (lines 362 and 363)

So I would suggest enabling an API method or shutdown mechanism to Maxwell. I have tested it with writing a "shutdown" file and it seems working ok.

Thanks.

**Comment by osheroff** [comment]
SIGINT should trigger a "clean" shutdown - one that runs all shutdown handlers, including KPL's and Maxwell's own.  What problems are you experiencing?

**Comment by osheroff** [comment]
Closing for lack of info.
