### ISSUE TITLE
Errors in Maxwell Log

### ISSUE THREAD

**Issue by SyedSulaimanM** [zendesk/maxwell#815]
We are using Maxwell for selective data replication across database by reading data from binlog and pushing to Kinesis. Here, I observed the below errors in the log intermittently. Can anyone please let me know if you have encountered these errors? I am just looking for information on why these errors are happening and whether it will lead to any data loss/other issues.

com.amazonaws.services.kinesis.producer.LogInputStreamReader|
-----------------------------------------------------------------------------------------|
 (CurlHttpClient)Curl returned error code 28|
 (AWSClient)No response body. Response code: 0|
 (AWSClient)No response body. Response code: 500|
 (AWSErrorMarshaller)Encountered AWSError InternalFailure|

**Comment by osheroff** [comment]
@SyedSulaimanM it definitely looks like an issue on the amazon side.  I'm not sure what the kinesis producer's behavior is in the face of a remote crash like this.  What's the actual Maxwell log message?  I'm looking to see if the kinesis producer will retry in this case or just throw the error back to maxwell....

**Comment by zackb** [comment]
Unrelated to Maxwell, but this GH issue seems to be the only thing google comes up with

You guys ever get this one figured out? I'm getting sporadic episodes of roughly two hours of downtime with a bunch of these errors

Thanks!

9737 [AWS Log: ERROR](CurlHttpClient)Curl returned error code 28
   1091 [AWS Log: ERROR](AWSClient)No response body.  Response code: 0
    210 [AWS Log: ERROR](CurlHttpClient)Curl returned error code 56
     21 [AWS Log: ERROR](CurlHttpClient)Curl returned error code 52
     14 [AWS Log: ERROR](AWSClient)No response body.  Response code: 500
