### ISSUE TITLE
[New feature]: maxwell can auto load the properties file,such as 30 seconds interval.

### ISSUE THREAD

**Issue by Hackeruncle** [zendesk/maxwell#821]
hi , the official, 
the maxwell has a new feature with auto load the properties file,
such as 30 seconds interval in future releases.

example:
[apache flume PollingPropertiesFileConfigurationProvider](http://blog.csdn.net/lw_ghy/article/details/51547442)

**Comment by osheroff** [comment]
mmmm, no.  It's simple and safe and efficient enough to restart maxwell for configuration changes.  The work required to make each part of maxwell reconfigurable in runtime is far too large.  You could easily pull this off in a wrapper script though...
