### ISSUE TITLE
Reading from binlog too fast leads to missing data (RDS, MySQL)

### ISSUE THREAD

**Issue by xaka** [zendesk/maxwell#823]
Curious to hear from community whether anyone faced the same problem, which is - I'm getting binlog events into kafka (and consumers) faster than RDS (MySQL) flushes the data / indices - SELECT statements return nothing until after some period of time. Those statements are run against master i.e. replication lag isn't involved. I really want to avoid any kind of sleep or re-try logic in consumers and keep it as the last possible solution. Thoughts?

P.S. Thanks for the awesome project!

**Comment by xaka** [comment]
I've found that problems only appears when I re-use the same database connection (I have 1 process, 1 thread, i.e. no resource sharing). If I re-connect every time there is a miss, it goes back to normal. Awkward.

**Comment by liulikun** [comment]
I don't quite understand the issue. Can you elaborate a bit more? What do you SELECT? Why you need to SELECT, etc. Thanks.

**Comment by xaka** [comment]
What I meant to say is for example for insert event we get data with new row and its primary key. Such rows are handled by consumers by selecting data based on primary keys, aggregating and storing somewhere. 

Problem is that selecting returns nothing for those rows unless I reconnect to database. Must be some kind of cache in driver or database. Not quite sure yet.

**Comment by xaka** [comment]
Turns out connection to RDS wasn't in auto-commit mode, which is why it didn't see new data.
