### ISSUE TITLE
Is maxwell support MariaDB 10.2.x version's GTID?

### ISSUE THREAD

**Issue by kleinstliuxin** [zendesk/maxwell#825]
Such as the title,in my env ,my sql servers  are in  'MariaDB Galera cluster',so each one of the cluster has different binlog,so i want to use GTID for the replication.
Can someone tell me ,is maxwell support GTID?
Any help thanks!

**Comment by liulikun** [comment]
It's not fully supported, see the issue here: https://github.com/zendesk/maxwell/issues/769
