### ISSUE TITLE
Create table and drop table doesn't generate binlog to json format

### ISSUE THREAD

**Issue by hoangbeatsb3** [zendesk/maxwell#826]
When I create a new table or drop table in my database (MariaDB), maxwell doesn't generate it into json and store in kafka topic. 
Just insert, update, delete query can be generated into json and store in kafka topic.
Please help to check.

Thank you very much!

**Comment by sungjuly** [comment]
hey, please refer `output_ddl` option in this doc
- https://github.com/zendesk/maxwell/blob/master/docs/docs/config.md
