### ISSUE TITLE
Add support for parsing binlog from file

### ISSUE THREAD

**Issue by leonjoyce** [zendesk/maxwell#832]
Currently maxwell seems only parse binlog from mysql, who will only dump "online" binlog files(show master logs). In our experience with Aliyun RDS, online binlog files is periodically purged, so that we have to frequently manually modify maxwell.position table to redirect the position to latest binlog. The consequence is that we skipped some old binlogs and DML/DDL is lost. So there is a need to pickup those lost binlogs and supplement their data to maxwell producer.

I have a PR for adding support for parsing binlog from local/online file. Not sure whether it can be approved.

**Comment by seanlook** [comment]
I'm interested in this feature. Wondering how you parse offlined binlog as the data source. I archive this by moving those binlogs to a new mysql server. But the table schema is the prolem.

**Comment by osheroff** [comment]
I'm interested to see the PR, but as @seanlook points out, the database schema is a problem; you'd have to be able to supply maxwell with the proper schema for the files you need to replay.  

What happens to maxwell when Aliyun purges the binlog files?  Maxwell crashes?  How?

**Comment by seanlook** [comment]
Hi @osheroff ,
That's why I opened issue #833 . I could create database schemas filtered by `include_tables`, not all of the schemas. But binlog contains those tablemap that does not in **fake** mysql binlog server.

**Comment by leonjoyce** [comment]
@seanlook Schema should not be a problem. Let's consider the senario: maxwell positions to binlog file1 and in replica DB we have online master logs of 4,5,6,7. So binlog 2,3 is purged.
In my new code maxwell will start from 1, restoring Schema to that point. then download 2,3 from Aliyun OSS. Parse them. and then we need manually point maxwell position at binlog.(4).

**Comment by leonjoyce** [comment]
@osheroff   when Aliyun purges the binlog files, like mentioned in the senario above, Maxwell will repeated restart, with the following exception:
Nov 25 11:13:53 prod-consul-1 consul[27239]: 11:13:53,919 WARN BinlogConnectorReplicator - replicator stopped at position: 1a65b0bd-49b5-11e7-b8d2-008cfae27ce0:1-53881705,35a3a92d-49b5-11e7-b8d3-7cd30ac4ed32:1-245379,16a6d3a9-61f8-11e7-9708-7cd30ac4272a:1-30407903 -- restarting
Nov 25 11:13:53 prod-consul-1 consul[27239]: 11:13:53,925 INFO BinaryLogClient - Connected to rm-bp1p125xw0bvcey34.mysql.rds.aliyuncs.com:3306 at 1a65b0bd-49b5-11e7-b8d2-008cfae27ce0:1-53881705,35a3a92d-49b5-11e7-b8d3-7cd30ac4ed32:1-245379,16a6d3a9-61f8-11e7-9708-7cd30ac4272a:1-30407903 (sid:6379, cid:721841652)

**Comment by osheroff** [comment]
@leonjoyce ok, yeah, in *theory* that can work, in practice, mmmm.... tricky for the average user to get right, and a pretty rare case.  Feels like something where we might package it as a tool (not part of the main maxwell daemon), you can give it a current schema and a binlog file and it parses that one file and is done.  

Regarding the error on purge: where in the binlog does that GTID occur?  If maxwell is up to date, it shouldn't be requesting a position that's purged, it should be past that...

**Comment by leonjoyce** [comment]
@osheroff  Let's consider the following senario with current Maxwell code:
1 Maxwell position at binlog File1
2 for some reason maxwell is shutdown for sometime, during which File1 is purged. And later the latest binlog became File4.
3 We start maxwell. In Maxwell.positions table maxwell still at File1, so the WARNING in the previous comments happen**s**(Maxwell request a binlog which is purged)****
4 We delete the old positions for the same client. the restart Maxwell, who will reposition to the latest binlog 4. But we missed the data in 2,3.

So I admit that if maxwell is always online

**Comment by osheroff** [comment]
yup.  I get it.  It's fine to PR.  Also, in your case, maxwell was down while the binlog was purged?

**Comment by leonjoyce** [comment]
@osheroff 
Yes. It is a double failure: Mawell is down while binlog was purged.
Here is my PR:
https://github.com/leonjoyce/maxwell/commit/8d7ec901483fab4ed3ff4bd06940bc477b506ded
Please give some comments. Thanks!

**Comment by ericwush** [comment]
@leonjoyce can you please create the PR so it's easy to track and manage?
