### ISSUE TITLE
i could not see old data,the data is update data?

### ISSUE THREAD

**Issue by superman16** [zendesk/maxwell#842]
{"database":"auto_vending_shop","table":"transaction_record_real","type":"update","ts":1515567785,"xid":60566336,"commit":true,"server_id":2319308683,"data":{"aisle":13,"update_time":"2018-01-10 15:03:05","deliver_state":0,"deliver_finish_time":"2018-01-10 15:03:02","error_msg":"","id":543382}}
  
if is update,json will contain data and old? but now is only data

**Comment by liulikun** [comment]
Are those columns blacklisted?

**Comment by superman16** [comment]
@liulikun  config.properties

######### filter stuff ###############

# filter rows out of Maxwell's output.
# all filters may be given either as literal names, or as java-style regular expressions.
# This is a literal name: "exclude_tables=tblname".
# This is a regexp:       "exclude_tables=/tblname_\\d+/"

# include *only* these databases
#include_dbs=db1,/db\\d+/
include_dbs=auto_vending_shop

# exclude these databases (will override an include)
#exclude_dbs=db3,/db\\d+/

# include *only* these tables
#include_tables=tbl1,/tbl\\d+/
include_tables=test,transaction_record_real

# exclude these tables
#exclude_tables=tbl1,/tbl\\d+/
#exclude_tables=push

# exclude these columns
#exclude_columns=col1,/col\\d+/

# "blacklist" these dbs -- this means maxwell will ignore schema
# changes happening to these databases.  Can be useful if you have a
# high-churn schema that you want to completely ignore, but it's
# a bit dangerous: once you set this option, you must leave it set, or
# else maxwell will likely blow up.
#
# All of this is to say: don't set this unless you know what you're doing.
#blacklist_dbs=db1,/db\\d+/
#blacklist_tables=table1,table_no
#

**Comment by liulikun** [comment]
Doesn't seem you have blacklisted columns. Another way to debug this is to check mysql binlog file itself using `mysqlbinlog` utility for transaction id `60566336` to see what's in the binlog.

**Comment by osheroff** [comment]
what's the value of the global mysql setting`binlog_row_image`?

**Comment by superman16** [comment]
@osheroff 
```html
mysql> show variables like 'binlog_format';
+---------------+-------+
| Variable_name | Value |
+---------------+-------+
| binlog_format | ROW   |
+---------------+-------+
1 row in set
```

**Comment by osheroff** [comment]
@superman16, no, the value of `binlog_row_image`

**Comment by osheroff** [comment]
this is a truly weirdo case, I'm not sure whether to close it or what.

**Comment by osheroff** [comment]
@m-denton to be clear, you're seeing a maxwell event with only new data, not old data?

Does it happen with all events?

**Comment by m-denton** [comment]
@osheroff In this case, I am not seeing any event when doing a manual schema change. Events flow properly with DELETE/UPDATE/INSERTS but altering a tables column? Nada.

**Comment by osheroff** [comment]
were you expecting to see data or something representing the schema change?

**Comment by ligyxy** [comment]
I had the same issue. Setting binlog_row_image to 'FULL' solves it.
