### ISSUE TITLE
Maxscale binlog server + maxwell "schema_" feature doesn't seem to work

### ISSUE THREAD

**Issue by gleb-aleksandrovitch** [zendesk/maxwell#843]
I'm having the problem with splitting the schema read and reading replication events described in [this](https://github.com/zendesk/maxwell/issues/545) issue. I'm using the following CLI command to run maxwell:
```
bin/maxwell --replication_host=<maxscale_binlog_host> --replication_password=<maxscale_binlog_pass> --replication_port=<maxscale_binlog_port> --replication_user=<maxscale_binlog_user> --schema_host=<local_mysql_host>--schema_user=<local_mysql_user> --schema_password=<local_mysql_password> --producer=stdout
```

And I'm still running into this error (I'm using docker):
```
2018-01-10 14:51:46   error  : (17) [binlogrouter] Unexpected query from 'maxscale'@'::ffff:172.16.1.50': /* mysql-connector-java-5.1.39 ( Revision: 3289a357af6d09ecc1a10fd3c26e95183e5790ad ) */SELECT  @@session.auto_increment_increment AS auto_increment_increment, @@character_set_client AS character_set_client, @@character_set_connection AS character_set_connection, @@character_set_results AS character_set_results, @@character_set_server AS character_set_server, @@init_connect AS init_connect, @@interactive_timeout AS interactive_timeout, @@license AS license, @@lower_case_table_names AS lower_case_table_names, @@max_allowed_packet AS max_allowed_packet, @@net_buffer_length AS net_buffer_length, @@net_write_timeout AS net_write_timeout, @@query_cache_size AS query_cache_size, @@query_cache_type AS query_cache_type, @@sql_mode AS sql_mode, @@system_time_zone AS system_time_zone, @@time_zone AS time_zone, @@tx_isolation AS tx_isolation, @@wait_timeout AS wait_timeout
```

So even after setting "schema" options it seems like my schema request query is going to MaxScale instead of MySQL container.  What am I doing wrong?

**Comment by osheroff** [comment]
hmmm, assuming the error message you're seeing is coming from maxscale?  Is there a corresponding stacktrace in maxwell?  Looks like something in maxwell is connecting to the replication host using mysql-connector-j, thereby confuddling maxscale, but I'm not sure what/where.

**Comment by gleb-aleksandrovitch** [comment]
The most I can get is this (using log_level=DEBUG):
```
10:10:16,452 WARN  MaxwellConfig - maxwell mysql host not specified, defaulting to localhost
10:10:16,459 WARN  MaxwellConfig - disabling bootstrapping; not available when using a separate replication host.
10:10:16,471 WARN  MaxwellMetrics - Metrics will not be exposed: metricsReportingType not configured.
10:10:16,497 DEBUG SchemaConnectionPool - SchemaConnectionPool: Parameters changed (minpool=0,maxpool=10,maxsize=0,idleTimeout=10,cleanInterval=2000)
10:10:16,850 ERROR Maxwell - SQLException: You have an error in your SQL syntax; Check the syntax the MaxScale binlog router accepts.
10:10:16,850 ERROR Maxwell - You have an error in your SQL syntax; Check the syntax the MaxScale binlog router accepts.
```

**Comment by osheroff** [comment]
ok, I see.  This is all kinda bizarrely specified, but there's 3 different connections:

1.  The place where Maxwell stores its schema (you need to specify this with `--host`, `--password`) -- not specifying this is your particular issue.
2.  The server Maxwell replicates from (`--replication_host`).
3.  (optionally) - a (possibly different) server that maxwell *captures* the schema from.

I'd love a PR (or might do it myself) that makes it very clear what each of the options does, maybe even renaming things `schema_storage_host` and `schema_capture_host`.

**Comment by gleb-aleksandrovitch** [comment]
Sorry, I forgot to mention - I already tried that config, still I got the same error. Here's my CLI command:
```
bin/maxwell --host=172.16.1.12 --user=root --password=<mysql-container-pass> --replication_host=172.16.1.45 --replication_port=4000 --replication_user=maxscale --replication_password=<maxscale-pass> --schema_host=172.16.1.12 --schema_user=root --schema_password=<mysql-container-pass> --schema_port=3306
```
For some reason it's still going to maxscale instead of msyql.

**Comment by stym06** [comment]
hey, did you get to work around this? getting this same error

**Comment by osheroff** [comment]
rolling this into #1585 1585
