### ISSUE TITLE
Filtering by GTID

### ISSUE THREAD

**Issue by fuyar** [zendesk/maxwell#846]
Hello guys,

A feature for filtering by GTID would be a given. In a multi master setup with a writable slave using as the source for Maxwell, it can get stuck if someone write directly onto this slave and a failover is done.

Ideally, I'd like Maxwell to only consider the instruction done by my "real" masters thus using their respective GTID.

What do you think of that ?

Thanks !

**Comment by osheroff** [comment]
hmmmm, seems pretty specific.  I'm curious why maxwell gets stuck, but I can't think of a use for this code outside of your (fairly odd) use-case.  

pro-tip: run your slaves with `read_only=1`

**Comment by fuyar** [comment]
Well it's not really possible as this particular slave is used for adhoc user queries. They need personal schema to store the results somewhere.

Thus using the GTID filering ID.

**Comment by osheroff** [comment]
Yeah, I mean, unless you can find a general use-case for the code, it's not something I think really belongs in mainline.  You're welcome to write a custom producer ([http://maxwells-daemon.io/producers/#custom-producer](http://maxwells-daemon.io/producers/#custom-producer)) that satisfies your use case though.
