### ISSUE TITLE
The flag [--kafka_version] that allows maxwell to run with a special kafka version has been removed ??

### ISSUE THREAD

**Issue by lynchlee** [zendesk/maxwell#848]
maxwell-1.12.0]$ bin/maxwell --user='maxwell' --password='XXXXXX' --host='data-node5' --producer=kafka --kafka.bootstrap.servers=data-node5:9092 --pubsub_topic='flink-stream-seeds' 0.10.2.1
Using kafka version: 0.11.0.1
Unknown argument(s): [0.10.2.1]

Option                              Description                                                                                    
------                              -----------                                                                                    
--config                            location of config file                                                                        
--log_level                         log level, one of DEBUG|INFO|WARN|ERROR                                                        

--host                              mysql host with write access to maxwell database                                               
--port                              port for host                                                                                  
--user                              username for host                                                                              
--password                          password for host                                                                              
--jdbc_options                      additional jdbc connection options                                                             

--replication_host                  mysql host to replicate from (if using separate schema and replication servers)                
--replication_user                  username for replication_host                                                                  
--replication_password              password for replication_host                                                                  
--replication_port                  port for replication_host                                                                      
--schema_host                       overrides replication_host for retrieving schema                                               
--schema_user                       username for schema_host                                                                       
--schema_password                   password for schema_host                                                                       
--schema_port                       port for schema_host                                                                           

--producer                          producer type: stdout|file|kafka|kinesis|pubsub|sqs                                            
--custom_producer.factory           fully qualified custom producer factory class                                                  
--producer_ack_timeout              producer message acknowledgement timeout                                                       
--output_file                       output file for 'file' producer                                                                
--producer_partition_by             database|table|primary_key|column, kafka/kinesis producers will partition by this value        
--producer_partition_columns        with producer_partition_by=column, partition by the value of these columns.  comma separated.  
--producer_partition_by_fallback    database|table|primary_key, fallback to this value when when sing 'column' partitioning and the
                                      columns are not present in the row                                                           
--kafka.bootstrap.servers           at least one kafka server, formatted as HOST:PORT[,HOST:PORT]                                  
--kafka_partition_hash              default|murmur3, hash function for partitioning                                                
--kafka_topic                       optionally provide a topic name to push to. default: maxwell                                   
--kafka_key_format                  how to format the kafka key; array|hash                                                        
--kinesis_stream                    kinesis stream name                                                                            
--sqs_queue_uri                     SQS Queue uri                                                                                  
--pubsub_project_id                 provide a google cloud platform project id associated with the pubsub topic                    
--pubsub_topic                      optionally provide a pubsub topic to push to. default: maxwell                                 
--ddl_pubsub_topic                  optionally provide an alternate pubsub topic to push DDL records to. default: pubsub_topic     

--output_binlog_position            produced records include binlog position; [true|false]. default: false                         
--output_gtid_position              produced records include gtid position; [true|false]. default: false                           
--output_commit_info                produced records include commit and xid; [true|false]. default: true                           
--output_nulls                      produced records include fields with NULL values [true|false]. default: true                   
--output_server_id                  produced records include server_id; [true|false]. default: false                               
--output_thread_id                  produced records include thread_id; [true|false]. default: false                               
--output_ddl                        produce DDL records to ddl_kafka_topic [true|false]. default: false                            
--ddl_kafka_topic                   optionally provide an alternate topic to push DDL records to. default: kafka_topic             
--secret_key                        The secret key for the AES encryption                                                          
--encrypt                           encryption mode: [none|data|all]. default: none                                                

--bootstrapper                      bootstrapper type: async|sync|none. default: async                                             

--replica_server_id                 server_id that maxwell reports to the master.  See docs for full explanation.                  
--client_id                         unique identifier for this maxwell replicator                                                  
--schema_database                   database name for maxwell state (schema and binlog position)                                   
--max_schemas                       deprecated.                                                                                    
--init_position                     initial binlog position, given as BINLOG_FILE:POSITION:HEARTBEAT                               
--replay                            replay mode, don't store any information to the server                                         
--master_recovery                   (experimental) enable master position recovery code                                            
--gtid_mode                         (experimental) enable gtid mode                                                                
--ignore_producer_error             Maxwell will be terminated on kafka/kinesis errors when false. Otherwise, those producer errors
                                      are only logged. Default to true                                                             

--include_dbs                       include these databases, formatted as include_dbs=db1,db2                                      
--exclude_dbs                       exclude these databases, formatted as exclude_dbs=db1,db2                                      
--include_tables                    include these tables, formatted as include_tables=db1,db2                                      
--exclude_tables                    exclude these tables, formatted as exclude_tables=tb1,tb2                                      
--exclude_columns                   exclude these columns, formatted as exclude_columns=col1,col2                                  
--blacklist_dbs                     ignore data AND schema changes to these databases, formatted as blacklist_dbs=db1,db2. See the 
                                      docs for details before setting this!                                                        
--blacklist_tables                  ignore data AND schema changes to these tables, formatted as blacklist_tables=tb1,tb2. See the 
                                      docs for details before setting this!                                                        
--include_column_values             include only rows with these values formatted as include_column_values=C=x,D=y                 

--rabbitmq_user                     Username of Rabbitmq connection. Default is guest                                              
--rabbitmq_pass                     Password of Rabbitmq connection. Default is guest                                              
--rabbitmq_host                     Host of Rabbitmq machine                                                                       
--rabbitmq_virtual_host             Virtual Host of Rabbitmq                                                                       
--rabbitmq_exchange                 Name of exchange for rabbitmq publisher                                                        
--rabbitmq_exchange_type            Exchange type for rabbitmq                                                                     
--rabbitmq_exchange_durable         Exchange durability. Default is disabled                                                       
--rabbitmq_exchange_autodelete      If set, the exchange is deleted when all queues have finished using it. Defaults to false      
--rabbitmq_routing_key_template     A string template for the routing key, '%db%' and '%table%' will be substituted. Default is '% 
                                      db%.%table%'.                                                                                
--rabbitmq_message_persistent       Message persistence. Defaults to false                                                         

--redis_host                        Host of Redis server                                                                           
--redis_port                        Port of Redis server                                                                           
--redis_auth                        Authentication key for a password-protected Redis server                                       
--redis_database                    Database of Redis server                                                                       
--redis_pub_channel                 Redis Pub/Sub channel for publishing records                                                   

--metrics_prefix                    the prefix maxwell will apply to all metrics                                                   
--metrics_type                      how maxwell metrics will be reported, at least one of slf4j|jmx|http|datadog                   
--metrics_slf4j_interval            the frequency metrics are emitted to the log, in seconds, when slf4j reporting is configured   
--http_port                         the port the server will bind to when http reporting is configured                             
--metrics_datadog_type              when metrics_type includes datadog this is the way metrics will be reported, one of udp|http   
--metrics_datadog_tags              datadog tags that should be supplied, e.g. tag1:value1,tag2:value2                             
--metrics_datadog_interval          the frequency metrics are pushed to datadog, in seconds                                        
--metrics_datadog_apikey            the datadog api key to use when metrics_datadog_type = http                                    
--metrics_datadog_host              the host to publish metrics to when metrics_datadog_type = udp                                 
--metrics_datadog_port              the port to publish metrics to when metrics_datadog_type = udp                                 
--http_diagnostic                   enable http diagnostic endpoint: true|false. default: false                                    
--http_diagnostic_timeout           the http diagnostic response timeout in ms when http_diagnostic=true. default: 10000           

--help                              display help

**Comment by osheroff** [comment]
1. your command line didn't actually include `kafka_version=` (assuming you copy/pasted correctly).
2. the option wasn't documented properly in `--help`.  #850 addresses this.

**Comment by osheroff** [comment]
fixed
