### ISSUE TITLE
Maxwell fail to start due to cast error

### ISSUE THREAD

**Issue by dbhatia2** [zendesk/maxwell#854]
17:30:58,412 INFO  MaxwellMetrics - JMX metrics reporter enabled
17:30:58,419 WARN  MaxwellMetrics - JMX remote is disabled
Tue Jan 23 17:30:58 PST 2018 WARN: Establishing SSL connection without server's identity verification is not recommended. According to MySQL 5.5.45+, 5.6.26+ and 5.7.6+ requirements SSL connection must be established by default if explicit option isn't set. For compliance with existing applications not using SSL the verifyServerCertificate property is set to 'false'. You need either to explicitly disable SSL by setting useSSL=false, or set useSSL=true and provide truststore for server certificate verification.
Tue Jan 23 17:30:59 PST 2018 WARN: Establishing SSL connection without server's identity verification is not recommended. According to MySQL 5.5.45+, 5.6.26+ and 5.7.6+ requirements SSL connection must be established by default if explicit option isn't set. For compliance with existing applications not using SSL the verifyServerCertificate property is set to 'false'. You need either to explicitly disable SSL by setting useSSL=false, or set useSSL=true and provide truststore for server certificate verification.
Tue Jan 23 17:30:59 PST 2018 WARN: Establishing SSL connection without server's identity verification is not recommended. According to MySQL 5.5.45+, 5.6.26+ and 5.7.6+ requirements SSL connection must be established by default if explicit option isn't set. For compliance with existing applications not using SSL the verifyServerCertificate property is set to 'false'. You need either to explicitly disable SSL by setting useSSL=false, or set useSSL=true and provide truststore for server certificate verification.
17:30:59,274 INFO  ProducerConfig - ProducerConfig values:
	compression.type = snappy
	metric.reporters = []
	metadata.max.age.ms = 300000
	metadata.fetch.timeout.ms = 5000
	reconnect.backoff.ms = 50
	sasl.kerberos.ticket.renew.window.factor = 0.8
	bootstrap.servers = [***********:9092]
	retry.backoff.ms = 100
	sasl.kerberos.kinit.cmd = /usr/bin/kinit
	buffer.memory = 33554432
	timeout.ms = 30000
	key.serializer = class org.apache.kafka.common.serialization.StringSerializer
	sasl.kerberos.service.name = null
	sasl.kerberos.ticket.renew.jitter = 0.05
	ssl.keystore.type = JKS
	ssl.trustmanager.algorithm = PKIX
	block.on.buffer.full = false
	ssl.key.password = null
	max.block.ms = 60000
	sasl.kerberos.min.time.before.relogin = 60000
	connections.max.idle.ms = 540000
	ssl.truststore.password = null
	max.in.flight.requests.per.connection = 5
	metrics.num.samples = 2
	client.id =
	ssl.endpoint.identification.algorithm = null
	ssl.protocol = TLS
	request.timeout.ms = 30000
	ssl.provider = null
	ssl.enabled.protocols = [TLSv1.2, TLSv1.1, TLSv1]
	acks = 1
	batch.size = 16384
	ssl.keystore.location = null
	receive.buffer.bytes = 32768
	ssl.cipher.suites = null
	ssl.truststore.type = JKS
	security.protocol = PLAINTEXT
	retries = 3
	max.request.size = 1048576
	value.serializer = class org.apache.kafka.common.serialization.StringSerializer
	ssl.truststore.location = null
	ssl.keystore.password = null
	ssl.keymanager.algorithm = SunX509
	metrics.sample.window.ms = 30000
	partitioner.class = class org.apache.kafka.clients.producer.internals.DefaultPartitioner
	send.buffer.bytes = 131072
	linger.ms = 0

17:30:59,284 WARN  KafkaProducer - metadata.fetch.timeout.ms config is deprecated and will be removed soon. Please use max.block.ms
17:30:59,337 INFO  AppInfoParser - Kafka version : 0.9.0.1
17:30:59,337 INFO  AppInfoParser - Kafka commitId : 23c69d62a0cabf06
17:30:59,378 INFO  Maxwell - Maxwell v1.10.6 is booting (MaxwellKafkaProducer), starting at Position[BinlogPosition[mysql-bin.000227:325675562], lastHeartbeat=0]
Tue Jan 23 17:30:59 PST 2018 WARN: Establishing SSL connection without server's identity verification is not recommended. According to MySQL 5.5.45+, 5.6.26+ and 5.7.6+ requirements SSL connection must be established by default if explicit option isn't set. For compliance with existing applications not using SSL the verifyServerCertificate property is set to 'false'. You need either to explicitly disable SSL by setting useSSL=false, or set useSSL=true and provide truststore for server certificate verification.
17:30:59,636 INFO  MysqlSavedSchema - Restoring schema id 8 (last modified at Position[BinlogPosition[mysql-bin.000227:325657455], lastHeartbeat=0])
17:30:59,893 INFO  MysqlSavedSchema - Restoring schema id 1 (last modified at Position[BinlogPosition[mysql-bin.000210:350431715], lastHeartbeat=0])
17:31:00,081 INFO  MysqlSavedSchema - beginning to play deltas...
17:31:00,090 INFO  MysqlSavedSchema - played 7 deltas in 9ms
17:31:00,109 INFO  BinlogConnectorReplicator - Setting initial binlog pos to: mysql-bin.000227:325675562
17:31:00,130 INFO  BinaryLogClient - Connected to ******:**** at mysql-bin.000227/325675562 (sid:6379, cid:2432896)
17:31:00,269 INFO  TaskManager - Stopping 3 tasks
17:31:00,269 ERROR TaskManager - cause:
java.lang.ClassCastException: [B cannot be cast to java.lang.Integer
	at com.zendesk.maxwell.schema.columndef.IntColumnDef.toLong(IntColumnDef.java:35) ~[maxwell-1.10.6.jar:1.10.6]
	at com.zendesk.maxwell.schema.columndef.IntColumnDef.asJSON(IntColumnDef.java:51) ~[maxwell-1.10.6.jar:1.10.6]
	at com.zendesk.maxwell.replication.BinlogConnectorEvent.writeData(BinlogConnectorEvent.java:88) ~[maxwell-1.10.6.jar:1.10.6]
	at com.zendesk.maxwell.replication.BinlogConnectorEvent.buildRowMap(BinlogConnectorEvent.java:136) ~[maxwell-1.10.6.jar:1.10.6]
	at com.zendesk.maxwell.replication.BinlogConnectorEvent.jsonMaps(BinlogConnectorEvent.java:163) ~[maxwell-1.10.6.jar:1.10.6]
	at com.zendesk.maxwell.replication.BinlogConnectorReplicator.getTransactionRows(BinlogConnectorReplicator.java:160) ~[maxwell-1.10.6.jar:1.10.6]
	at com.zendesk.maxwell.replication.BinlogConnectorReplicator.getRow(BinlogConnectorReplicator.java:271) ~[maxwell-1.10.6.jar:1.10.6]
	at com.zendesk.maxwell.replication.AbstractReplicator.work(AbstractReplicator.java:157) ~[maxwell-1.10.6.jar:1.10.6]
	at com.zendesk.maxwell.util.RunLoopProcess.runLoop(RunLoopProcess.java:27) ~[maxwell-1.10.6.jar:1.10.6]
	at com.zendesk.maxwell.Maxwell.startInner(Maxwell.java:183) ~[maxwell-1.10.6.jar:1.10.6]
	at com.zendesk.maxwell.Maxwell.start(Maxwell.java:134) ~[maxwell-1.10.6.jar:1.10.6]
	at com.zendesk.maxwell.Maxwell.main(Maxwell.java:204) ~[maxwell-1.10.6.jar:1.10.6]
17:31:00,275 INFO  TaskManager - Stopping: com.zendesk.maxwell.producer.MaxwellKafkaProducerWorker@691f4497
17:31:00,275 INFO  StoppableTaskState - MaxwellKafkaProducerWorker requestStop() called (in state: RUNNING)
17:31:00,278 INFO  KafkaProducer - Closing the Kafka producer with timeoutMillis = 9223372036854775807 ms.
17:31:00,281 INFO  TaskManager - Stopping: com.zendesk.maxwell.schema.PositionStoreThread@4c6a889d
17:31:00,281 INFO  StoppableTaskState - com.zendesk.maxwell.schema.PositionStoreThread requestStop() called (in state: RUNNING)
17:31:00,281 INFO  TaskManager - Stopping: com.zendesk.maxwell.replication.BinlogConnectorReplicator@4fbe0244
17:31:00,282 INFO  StoppableTaskState - com.zendesk.maxwell.replication.BinlogConnectorReplicator requestStop() called (in state: STOPPED)
java.lang.ClassCastException: [B cannot be cast to java.lang.Integer
	at com.zendesk.maxwell.schema.columndef.IntColumnDef.toLong(IntColumnDef.java:35)
	at com.zendesk.maxwell.schema.columndef.IntColumnDef.asJSON(IntColumnDef.java:51)
	at com.zendesk.maxwell.replication.BinlogConnectorEvent.writeData(BinlogConnectorEvent.java:88)
	at com.zendesk.maxwell.replication.BinlogConnectorEvent.buildRowMap(BinlogConnectorEvent.java:136)
	at com.zendesk.maxwell.replication.BinlogConnectorEvent.jsonMaps(BinlogConnectorEvent.java:163)
	at com.zendesk.maxwell.replication.BinlogConnectorReplicator.getTransactionRows(BinlogConnectorReplicator.java:160)
	at com.zendesk.maxwell.replication.BinlogConnectorReplicator.getRow(BinlogConnectorReplicator.java:271)
	at com.zendesk.maxwell.replication.AbstractReplicator.work(AbstractReplicator.java:157)
	at com.zendesk.maxwell.util.RunLoopProcess.runLoop(RunLoopProcess.java:27)
	at com.zendesk.maxwell.Maxwell.startInner(Maxwell.java:183)
	at com.zendesk.maxwell.Maxwell.start(Maxwell.java:134)
	at com.zendesk.maxwell.Maxwell.main(Maxwell.java:204)
17:31:01,594 INFO  TaskManager - Stopped all tasks

**Comment by dbhatia2** [comment]
Hello Experts,

Can you please suggest on this?

Thanks
D

**Comment by osheroff** [comment]
generally points to a schema-out-of-sync issue. Are you running multiple versions of maxwell, or did you manually move the replication pointer?

**Comment by osheroff** [comment]
can be worked around by dropping the `maxwell` database and restarting, but I'm always curious about more info on this class of issues.

**Comment by dbhatia2** [comment]
Based on binary logs parsing i see it failed for 

#180118 23:28:02 server id 10178193  end_log_pos 325675562 CRC32 0xf73b5444     Write_rows: table id 1935 flags: STMT_END_F
### INSERT INTO `tms`.`_a_schema_history`
### SET
###   @1=875 /* INT meta=0 nullable=0 is_null=0 */
###   @2='2018.1.2.0.201801161650' /* VARSTRING(150) meta=150 nullable=1 is_null=0 */
###   @3='Alter itn RoutingGuide GetAll' /* VARSTRING(600) meta=600 nullable=0 is_null=0 */
###   @4='SQL' /* VARSTRING(60) meta=60 nullable=0 is_null=0 */
###   @5='2018.1.2.0/V2018.1.2.0_201801161650__Alter_itn_RoutingGuide_GetAll.sql' /* VARSTRING(3000) meta=3000 nullable=0 is_null=0 */
###   @6=502982703 /* INT meta=0 nullable=1 is_null=0 */
###   @7='tmsusradm' /* VARSTRING(300) meta=300 nullable=0 is_null=0 */
###   @8=1516346882 /* TIMESTAMP(0) meta=0 nullable=0 is_null=0 */
###   @9=14 /* INT meta=0 nullable=0 is_null=0 */
###   @10=1 /* TINYINT meta=0 nullable=0 is_null=0 */
# at 325675562

- Can you clarify how I can find and fix out-of-sync.
- Dropping maxwell schema , will start from current. Is there is any way to start from particular binlogs position to reduce data change lose.

**Comment by osheroff** [comment]
what do the following queries show?

```
 select columns.* from maxwell.columns join maxwell.tables on tables.id = columns.table_id join maxwell.databases on tables.database_id = databases.id where tables.name='_a_schema_history' and databases.name='tms';
```

```
select * from maxwell.schemas
```

```
select * from maxwell.positions
```

dropping the maxwell database will indeed restart from wherever it stands.

**Comment by ravyn440** [comment]
FWIW, this looks like the opposite of something which happened to me last week - instead of this:
java.lang.ClassCastException: [B cannot be cast to java.lang.Integer

I was getting this:
java.lang.ClassCastException: java.lang.Long cannot be cast to [B

After much confusion and investigation I figured out what was going on and ended up filing a bug with Oracle, but I don't know if they will consider it a bug or not.  It is really weird, regardless. 

https://bugs.mysql.com/bug.php?id=91822

**Comment by weiboyiyou** [comment]
@dbhatia2   how do you  find and fix out-of-sync?

**Comment by jessedobbelaere** [comment]
```
20:18:59,515 DEBUG MysqlSavedSchema - Restored all databases
20:18:59,515 INFO  MysqlSavedSchema - beginning to play deltas...
20:18:59,599 INFO  MysqlSavedSchema - played 134 deltas in 84ms
20:18:59,624 INFO  BinlogConnectorReplicator - Setting initial binlog pos to: mysql-bin.006197:730231497
20:18:59,734 INFO  BinaryLogClient - Connected to 10.2.23.96:3306 at mysql-bin.006197/730231497 (sid:4001, cid:211065)
20:18:59,734 INFO  BinlogConnectorLifecycleListener - Binlog connected.
20:18:59,785 WARN  BinlogConnectorReplicator - Unhandled QueryEvent @ mysql-bin.006197:730231570 inside transaction: QueryEventData{threadId=0, executionTime=0, errorCode=0, database='', sql='# Dummy event replacing event type 160 that slave cannot handle.                                                                                                                                                                                                                                                                                                                                                                                                                                '}
20:18:59,813 WARN  BinlogConnectorReplicator - Unhandled QueryEvent @ mysql-bin.006197:730610233 inside transaction: QueryEventData{threadId=0, executionTime=0, errorCode=0, database='', sql='# Dummy event replacing event type 160 that slave cannot handle.                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  '}
20:18:59,919 INFO  BinlogConnectorLifecycleListener - Binlog disconnected.
20:18:59,921 INFO  TaskManager - Stopping 3 tasks
20:18:59,921 ERROR TaskManager - cause:
java.lang.ClassCastException: java.lang.Integer cannot be cast to java.lang.Long
	at com.zendesk.maxwell.schema.columndef.BigIntColumnDef.toNumeric(BigIntColumnDef.java:19) ~[maxwell-1.19.3.jar:1.19.3]
	at com.zendesk.maxwell.schema.columndef.BigIntColumnDef.asJSON(BigIntColumnDef.java:32) ~[maxwell-1.19.3.jar:1.19.3]
	at com.zendesk.maxwell.replication.BinlogConnectorEvent.writeData(BinlogConnectorEvent.java:108) ~[maxwell-1.19.3.jar:1.19.3]
	at com.zendesk.maxwell.replication.BinlogConnectorEvent.buildRowMap(BinlogConnectorEvent.java:158) ~[maxwell-1.19.3.jar:1.19.3]
	at com.zendesk.maxwell.replication.BinlogConnectorEvent.jsonMaps(BinlogConnectorEvent.java:172) ~[maxwell-1.19.3.jar:1.19.3]
	at com.zendesk.maxwell.replication.BinlogConnectorReplicator.getTransactionRows(BinlogConnectorReplicator.java:384) ~[maxwell-1.19.3.jar:1.19.3]
	at com.zendesk.maxwell.replication.BinlogConnectorReplicator.getRow(BinlogConnectorReplicator.java:493) ~[maxwell-1.19.3.jar:1.19.3]
	at com.zendesk.maxwell.replication.BinlogConnectorReplicator.work(BinlogConnectorReplicator.java:149) ~[maxwell-1.19.3.jar:1.19.3]
	at com.zendesk.maxwell.util.RunLoopProcess.runLoop(RunLoopProcess.java:27) ~[maxwell-1.19.3.jar:1.19.3]
	at com.zendesk.maxwell.Maxwell.startInner(Maxwell.java:224) ~[maxwell-1.19.3.jar:1.19.3]
	at com.zendesk.maxwell.Maxwell.start(Maxwell.java:156) ~[maxwell-1.19.3.jar:1.19.3]
	at com.zendesk.maxwell.Maxwell.main(Maxwell.java:245) ~[maxwell-1.19.3.jar:1.19.3]
20:18:59,926 INFO  TaskManager - Stopping: com.zendesk.maxwell.schema.PositionStoreThread@5d911777
20:18:59,926 INFO  StoppableTaskState - com.zendesk.maxwell.schema.PositionStoreThread requestStop() called (in state: RUNNING)
20:18:59,927 INFO  TaskManager - Stopping: com.zendesk.maxwell.producer.MaxwellKafkaProducerWorker@46be1ed1
20:18:59,927 INFO  StoppableTaskState - MaxwellKafkaProducerWorker requestStop() called (in state: RUNNING)
20:18:59,927 INFO  KafkaProducer - Closing the Kafka producer with timeoutMillis = 9223372036854775807 ms.
20:18:59,927 DEBUG Sender - Beginning shutdown of Kafka producer I/O thread, sending remaining records.
```


Currently also running into this issue after we changed some database tables from int to bigint (unsigned). We ran into Maxwell issues because we blacklisted some tmp tables created by Percona's pt-online-schema-tool to run the ALTER queries. Could fix it by adding `--recapture_schema=true` so I did not have to drop the maxwell database. After it booted up again, we got the cast exception above. 


Seeing both the old value (int) and the new value now (bigint) in the columns table.
![image](https://user-images.githubusercontent.com/1352979/60687048-68b88f00-9eac-11e9-82f7-32b9e7045222.png)


I have little knowledge about the internals of Maxwell but was wondering if we can change the casting from object to Long more flexible so an Integer can be casted to Long? 

```
Long l = (Long)value;
```

**Comment by osheroff** [comment]
I'm pretty sure the issues @jessedobbelaere ran into were a result of trying to play a binlog from a mismatched schema.  There's other cast exceptions that I think I fixed awhile ago where a bit of DDL could be ignored by mis-processing a SQL comment?  I think?

Anyway I put better cast exception logging in and I'm closing down all the old bugs with this.
