### ISSUE TITLE
java.lang.RuntimeException: couldn't extract date/time out of [B@2d23faef

### ISSUE THREAD

**Issue by Hackeruncle** [zendesk/maxwell#855]
```java.lang.RuntimeException: couldn't extract date/time out of [B@2d23faef```

**Comment by osheroff** [comment]
generally points to a schema-out-of-sync issue.  Are you running multiple versions of maxwell, or did you manually move the replication pointer?

**Comment by blockmar** [comment]
I used the `--recapture_schema=true` startup option. That seemed to do the trick. (for anyone else getting here from Google)

**Comment by osheroff** [comment]
I'm closing down old schema-sync issues, haven't seen one in a year or more i think.
