### ISSUE TITLE
The size of each partition not balance with maxwell

### ISSUE THREAD

**Issue by vpants** [zendesk/maxwell#856]
the size of each partition  not balance with maxwell , why each partition not balance or maxwell use what algorithm as producer

**Comment by osheroff** [comment]
it's configurable.  the most balanced you can achieve is probably with `--producer_partition_by=primary_key` and `--kafka_partition_hash=murmur3`.  Maxwell defaults to partitioning by database, as this has the best serialization guarantees.

**Comment by rogershieh** [comment]
Is it possible to set hash function to none? murmur3 and default both resulted in most if not all data being pushed to one partition
