### ISSUE TITLE
Maxwell include_dbs or include_tables feature not workin

### ISSUE THREAD

**Issue by kapil9186** [zendesk/maxwell#857]
Hi, 
i want to restrict the maxwell execution for certain db and few tables and while starting the same i am providing the options as --include_tables=tb1,tb2  --include_dbs=db1, but looks like its not working as i can see the changes for all other objects and database.

Please let me know how can this be achieved.

**Comment by osheroff** [comment]
hmmm, this is working fine for me locally.  can you give your full command line and/or config.properties, as well as some sample output?

**Comment by kapil9186** [comment]
Hi,

Here is the command i running
bin/maxwell --user=<UserName> --password=<Password> --host=<Server>
--producer=kafka --kafka.bootstrap.servers=localhost:9092
--output_ddl=true --include_dbs=<dbname> --include_tables=<tablename>

one quick thing do i need to uncomment the properties under
config.properties.example.

Thanks
Kapil K

**Comment by foundwant** [comment]
sh bin/maxwell --user='root' --password='root' --host='127.0.0.1' --producer=kafka --kafka.bootstrap.servers=bd-dev-hadoop2:6667 --kafka_topic kfktest --include_dbs=hs_secu --include_tables=entrust

This is my command，'hs_secu' is my db_name and 'entrust' is my tb_name，it real work well。

**Comment by osheroff** [comment]
@kapil9186 what is the unexpected output that you're seeing?  DDL is not subject to the tables filters BTW

**Comment by kapil9186** [comment]
I am getting the change logs for all the tables or database.

**Comment by osheroff** [comment]
can you include some sample output?  I really don't have a clue why this isn't working for you

**Comment by ericwush** [comment]
@kapil9186 do you use regex in `--include_tables` or `--include_dbs` configs?

**Comment by kapil9186** [comment]
Nope it was just the db name like if db name is window so my command was
--include_dbs=window

**Comment by osheroff** [comment]
was this related to case-sensitivity maybe?
