### ISSUE TITLE
How i can know the amount of data that maxwell hasn't send yet

### ISSUE THREAD

**Issue by yester354** [zendesk/maxwell#86]
Hi
    i am trying to transfer data from mysql to kafka by using maxwell . the day before yesterday ,about 09:30,I construct three million rows in one table in mysql database.and the maxwell began to load data to kafka. but at now the maxwell is still display message like bellow
   11:41:36,914 DEBUG MaxwellKafkaProducer -    {"database":"emon","table":"msql","type":"insert","data":{"EDITION_NAME":"a","OBJECT_NAME":"ob","GENERATED":"a","OBJECT_TYPE":"OO","OBJECT_ID":813790,"CREATED":"2015-08-28","STATUS":"a","OWNER":"测试","SECONDARY":"a","SUBOBJECT_NAME":"o","TEMPORARY":"a","TIMESTAMP":"1","DATA_OBJECT_ID":813790,"NAMESPACE":1,"LAST_DDL_TIME":"2015-08-28"},"ts":1441165290}
11:41:36,914 DEBUG MaxwellKafkaProducer -    BinlogPosition[master.000007:1013840679]
11:41:36,914 DEBUG MaxwellKafkaProducer - 
11:41:37,219 DEBUG SchemaPosition - Writing binlog position to maxwell.positions: BinlogPosition[master.000007:1013840679]

how i can know the amount of the data that hasn't been transferred by maxwell.

**Comment by osheroff** [comment]
Is Maxwell stuck at a single position?  No way should Maxwell be taking 48 hours to load 3mm rows.  Do you have a test script?

There's no concept of "seconds behind master" or such in Maxwell.  You can get a rough idea by doing "SHOW MASTER STATUS" on the master database and seeing how far maxwell's binlog position is from the current master position.

**Comment by yester354** [comment]
@osheroff 
 Hi, i  checked again. and found that the scripts is still inserting data to mysql.i thought i had stopped it.now it's ok.
 i think it is useful that in  some way i can know how much data had been sent and how much data need to be sent by using maxwell
