### ISSUE TITLE
"alter table" can't get table name.

### ISSUE THREAD

**Issue by weiboyiyou** [zendesk/maxwell#863]
HI:
   "alter table" can't get table name.
like this:
    14:32:01,749 INFO  AbstractSchemaStore - storing schema @Position[BinlogPosition[mysql-bin.000414:13749352], lastHeartbeat=1517455327806] after applying "ALTER TABLE ` MODIFY COLUMN `id`  bigint(20) NOT NULL AUTO_INCREMENT COMMENT '主键ID' FIRST" to cloud_bas, new schema id is 76

**Comment by osheroff** [comment]
is this error message truncated?

**Comment by osheroff** [comment]
closing due to lack of response.  feel free to reopen with more info.
