### ISSUE TITLE
Not able to find remote mysql binlog file location

### ISSUE THREAD

**Issue by issacbalaji** [zendesk/maxwell#864]
//mycode

final BinaryLogClient client = new BinaryLogClient("192.168.73.166", 3306, "appuser", "Appuser");
				
				client.registerEventListener(new EventListener() {

				    @Override
				    public void onEvent(Event event) {
				    	
				    	System.out.println("----------"+client.getBinlogFilename());
				    	
				        System.out.println("----------"+event.getHeader());
				        System.out.println("----------"+event.getData());
				        System.out.println("----------"+getClass());
				        
				        
				        File binlogFile = new File(client.getBinlogFilename());
				        
						BinaryLogFileReader reader;
						try {
							reader = new BinaryLogFileReader(binlogFile);
							
						} catch (IOException e) {
							// TODO Auto-generated catch block
							e.printStackTrace();
						}
						
				        
				        //System.out.println("******"+new QueryEventData().toString());
				    }
				});
				client.connect();
			
			System.out.println("file name: "+client.getBinlogFilename());
			System.out.println("postion: "+client.getBinlogPosition());
			System.out.println("postion: "+client.getSSLMode());
			
}
}

this is my code, more here I'm trying to read  all  bilogfile from other machines location but its taking location machine path, i need to read remote machine binlog file please rectify

**Comment by osheroff** [comment]
this is the wrong repo for this, you probably want to as a question over here: 
https://github.com/shyiko/mysql-binlog-connector-java
