### ISSUE TITLE
Managing kafka's binlog position in custom producer

### ISSUE THREAD

**Issue by jkgeyti** [zendesk/maxwell#866]
First of, apologies for posting on the issue tracked, but I couldn't seem to find a suitable community to post this in.

I assume `context.SetPosition` stores the offset in maxwell's mysql database, so the producer can continue from that position on restart. Please correct me if I'm wrong.

The [CustomProducer example](https://github.com/zendesk/maxwell/blob/master/src/example/com/zendesk/maxwell/example/producerfactory/CustomProducer.java) calls `context.setPosition(r.getPosition());` only on DDL and heartbeat events. Why is that? Should it not be called only after writing (and hence persisting) messages to stdout? Is `context.setPosition` ever called indirectly by other parts of maxwell?

Being able to choose when to store a binlog position in kafka's mysql database is a crucial part of writing a safe custom producer, and it would probably be worth highlighting how and when to do it safely in the custom producer example. I'll be happy to do a PR, but I wanted to make sure I understand the expected behavior and responsibilities of `AbstractProducer.push` and `MaxwellContext.setPosition` before doing so.

**Comment by osheroff** [comment]
Nice catch.   Yeah, please do a PR.  A producer may go off and write rows in the background of `push`, only calling `setPosition` later (the kafka/kinesis producers do this), but yes, generally a producer should be calling `setPosition` every time it's finished processing a row.

**Comment by jkgeyti** [comment]
https://github.com/jkgeyti/maxwell/pull/1
