### ISSUE TITLE
bootstrap data - doesn't show the current time 

### ISSUE THREAD

**Issue by ravikiranks** [zendesk/maxwell#868]
Why would bootstrap data show timestamp as "epoch" start time (1517873969), instead of current time??
example - {"database":"xyz","table":"tbl_1","type":"bootstrap-insert","ts":1517873969,"data":

In the metadata database, table maxwell.bootstrap columns "started_at"    and "completed_at" show correct UTC time, but "created_at" is NULL.

We tried to manually create a row in maxwell.bootstrap instead of running the bootstrap utility but still the data generated into kafka had the "ts" as epoch start time!!!

We need the kafka data field "ts" as the current time !!

**Comment by osheroff** [comment]
that's seconds since the epoch, not milliseconds.

```
alpha21:~  $ irb
irb(main):001:0> Time.at(1517873969)
=> 2018-02-05 15:39:29 -0800
```
