### ISSUE TITLE
Maxwell shutdown on encountering '7B' character

### ISSUE THREAD

**Issue by hbpro** [zendesk/maxwell#869]
12:58:31,938 INFO  BinlogConnectorLifecycleListener - Binlog disconnected.
12:58:31,939 INFO  TaskManager - Stopping 3 tasks
12:58:31,939 ERROR TaskManager - cause: 
java.lang.RuntimeException: java.io.IOException: Unknown value type code '7B'
	at com.zendesk.maxwell.schema.columndef.JsonColumnDef.asJSON(JsonColumnDef.java:27) ~[maxwell-1.11.0.jar:?]
	at com.zendesk.maxwell.replication.BinlogConnectorEvent.writeData(BinlogConnectorEvent.java:104) ~[maxwell-1.11.0.jar:?]
	at com.zendesk.maxwell.replication.BinlogConnectorEvent.buildRowMap(BinlogConnectorEvent.java:152) ~[maxwell-1.11.0.jar:?]
	at com.zendesk.maxwell.replication.BinlogConnectorEvent.jsonMaps(BinlogConnectorEvent.java:179) ~[maxwell-1.11.0.jar:?]
	at com.zendesk.maxwell.replication.BinlogConnectorReplicator.getTransactionRows(BinlogConnectorReplicator.java:182) ~[maxwell-1.11.0.jar:?]
	at com.zendesk.maxwell.replication.BinlogConnectorReplicator.getRow(BinlogConnectorReplicator.java:281) ~[maxwell-1.11.0.jar:?]
	at com.zendesk.maxwell.replication.AbstractReplicator.work(AbstractReplicator.java:148) ~[maxwell-1.11.0.jar:?]
	at com.zendesk.maxwell.util.RunLoopProcess.runLoop(RunLoopProcess.java:27) ~[maxwell-1.11.0.jar:?]
	at com.zendesk.maxwell.Maxwell.startInner(Maxwell.java:190) ~[maxwell-1.11.0.jar:?]
	at com.zendesk.maxwell.Maxwell.start(Maxwell.java:140) ~[maxwell-1.11.0.jar:?]
	at com.zendesk.maxwell.Maxwell.main(Maxwell.java:211) ~[maxwell-1.11.0.jar:?]
Caused by: java.io.IOException: Unknown value type code '7B'
	at com.github.shyiko.mysql.binlog.event.deserialization.json.JsonBinary.readValueType(JsonBinary.java:978) ~[mysql-binlog-connector-java-0.13.0.jar:0.13.0]
	at com.github.shyiko.mysql.binlog.event.deserialization.json.JsonBinary.parse(JsonBinary.java:205) ~[mysql-binlog-connector-java-0.13.0.jar:0.13.0]
	at com.github.shyiko.mysql.binlog.event.deserialization.json.JsonBinary.parse(JsonBinary.java:181) ~[mysql-binlog-connector-java-0.13.0.jar:0.13.0]
	at com.github.shyiko.mysql.binlog.event.deserialization.json.JsonBinary.parseAsString(JsonBinary.java:168) ~[mysql-binlog-connector-java-0.13.0.jar:0.13.0]
	at com.zendesk.maxwell.schema.columndef.JsonColumnDef.asJSON(JsonColumnDef.java:24) ~[maxwell-1.11.0.jar:?]
	... 10 more
12:58:31,943 INFO  TaskManager - Stopping: com.zendesk.maxwell.schema.PositionStoreThread@572e827b
12:58:31,943 INFO  StoppableTaskState - com.zendesk.maxwell.schema.PositionStoreThread requestStop() called (in state: RUNNING)
12:58:31,943 INFO  TaskManager - Stopping: com.zendesk.maxwell.producer.MaxwellKafkaProducerWorker@24df1bb
12:58:31,943 INFO  StoppableTaskState - MaxwellKafkaProducerWorker requestStop() called (in state: RUNNING)
12:58:31,945 INFO  KafkaProducer - Closing the Kafka producer with timeoutMillis = 9223372036854775807 ms.
12:58:31,948 INFO  TaskManager - Stopping: com.zendesk.maxwell.replication.BinlogConnectorReplicator@1364add9
12:58:31,948 INFO  StoppableTaskState - com.zendesk.maxwell.replication.BinlogConnectorReplicator requestStop() called (in state: STOPPED)
java.lang.RuntimeException: java.io.IOException: Unknown value type code '7B'
	at com.zendesk.maxwell.schema.columndef.JsonColumnDef.asJSON(JsonColumnDef.java:27)
	at com.zendesk.maxwell.replication.BinlogConnectorEvent.writeData(BinlogConnectorEvent.java:104)
	at com.zendesk.maxwell.replication.BinlogConnectorEvent.buildRowMap(BinlogConnectorEvent.java:152)
	at com.zendesk.maxwell.replication.BinlogConnectorEvent.jsonMaps(BinlogConnectorEvent.java:179)
	at com.zendesk.maxwell.replication.BinlogConnectorReplicator.getTransactionRows(BinlogConnectorReplicator.java:182)
	at com.zendesk.maxwell.replication.BinlogConnectorReplicator.getRow(BinlogConnectorReplicator.java:281)
	at com.zendesk.maxwell.replication.AbstractReplicator.work(AbstractReplicator.java:148)
	at com.zendesk.maxwell.util.RunLoopProcess.runLoop(RunLoopProcess.java:27)
	at com.zendesk.maxwell.Maxwell.startInner(Maxwell.java:190)
	at com.zendesk.maxwell.Maxwell.start(Maxwell.java:140)
	at com.zendesk.maxwell.Maxwell.main(Maxwell.java:211)
Caused by: java.io.IOException: Unknown value type code '7B'
	at com.github.shyiko.mysql.binlog.event.deserialization.json.JsonBinary.readValueType(JsonBinary.java:978)
	at com.github.shyiko.mysql.binlog.event.deserialization.json.JsonBinary.parse(JsonBinary.java:205)
	at com.github.shyiko.mysql.binlog.event.deserialization.json.JsonBinary.parse(JsonBinary.java:181)
	at com.github.shyiko.mysql.binlog.event.deserialization.json.JsonBinary.parseAsString(JsonBinary.java:168)
	at com.zendesk.maxwell.schema.columndef.JsonColumnDef.asJSON(JsonColumnDef.java:24)
	... 10 more
12:58:33,269 INFO  TaskManager - Stopped all tasks

**Comment by osheroff** [comment]
bizarre.  any idea what the JSON data was in the row that triggered the issue?

**Comment by osheroff** [comment]
two possibilities here:  somehow corrupt data entered into a JSON column, or something that caused the BinlogConnector to improperly read the JSON.  @hbpro, without a binlog dump or some more info it's *really* hard to narrow down the possiblities here.

**Comment by reist** [comment]
A bit late, but could this have been a MariaDB issue? I just hit the same error, as MariaDB stores JSON as a string. Hacked around it by changing the case in ColumnDef.java to use StringColumnDef with a utf8 charset.

**Comment by daledude** [comment]
I hit this today on 10.3.31-MariaDB. Mariadb uses LONGTEXT as json field which is different than Mysql.
@osheroff is there anything I can offer besides the below to help with Mariadb? I wish we didn't, but we use both Mysql and Mariadb.

```
19:18:32,290 WARN  BinlogConnectorReplicator - Unhandled QueryEvent @ mysql-bin.000986:383179258 inside transaction: QueryEventData{threadId=0, executionTime=0, errorCode=0, database='', sql='# Dummy eventreplacing event type 160 that slave cannot handle.                                                                                                                  '}
19:18:32,404 INFO  BinlogConnectorReplicator - Binlog disconnected.

```
```
mysql# mysqlbinlog --start-position 383179258  -v mysql-bin.000986

/*!50530 SET @@SESSION.PSEUDO_SLAVE_MODE=1*/;
/*!40019 SET @@session.max_insert_delayed_threads=0*/;
/*!50003 SET @OLD_COMPLETION_TYPE=@@COMPLETION_TYPE,COMPLETION_TYPE=0*/;
DELIMITER /*!*/;
# at 4
#211101 23:21:40 server id 373  end_log_pos 256 CRC32 0xc9cdc677        Start: binlog v 4, server v 10.3.31-MariaDB-0ubuntu0.20.04.1-log created 211101 23:21:40
# Warning: this binlog is either in use or was not closed properly.
BINLOG '
9NiAYQ91AQAA/AAAAAABAAABAAQAMTAuMy4zMS1NYXJpYURCLTB1YnVudHUwLjIwLjA0LjEtbG9n
AAAAAAAAAAAAAAAAAAAAAAAAEzgNAAgAEgAEBAQEEgAA5AAEGggAAAAICAgCAAAACgoKAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAEEwQADQgICAoKCgF3xs3J
'/*!*/;
# at 383179258
# at 383181327
#211102  0:16:09 server id 373  end_log_pos 383181327 CRC32 0xc9e4f349  Annotate_rows:
#Q> UPDATE `broker`.`dalejsontest` SET `js`='{"type":"table-create","database":"broker","table":"daletest","def":{"database":"broker","charset":"latin1","table":"daletest","columns":[{"type":"bigint","name":"cdrid","signed":true},{"type":"datetime","name":"calldate","column-length":0},{"type":"int","name":"rci","signed":false},{"type":"varchar","name":"peer","charset":"latin1"},{"type":"int","name":"vendor_id","signed":true},{"type":"float","name":"rate"},{"type":"int","name":"costsec","signed":true},{"type":"float","name":"cost"},{"type":"tinyint","name":"successful","signed":true},{"type":"smallint","name":"kind","signed":true},{"type":"tinyint","name":"waslnp","signed":true},{"type":"float","name":"lnprate"},{"type":"float","name":"lnpcost"}],"primary-key":[]},"ts":1635554256000,"sql":"-- DROP TABLE broker.daletest;\\r\\n\\r\\nCREATE TABLE broker.daletest (\\r\\n\\t`cdrid` BIGINT(22) NOT NULL COMMENT \'from cdr.id\',\\r\\n\\t`calldate` DATETIME NOT NULL DEFAULT \'0000-00-00 00:00:00\' COMMENT \'from cdr.calldate\',\\r\\n\\t`rci` INT(4) UNSIGNED ZEROFILL NOT NULL DEFAULT \'0000\' COMMENT \'from cdr.userfield\',\\r\\n\\t`peer` VARCHAR(40) NOT NULL COMMENT \'from cdr.dstchannel, vendors.peer\' COLLATE \'latin1_swedish_ci\',\\r\\n\\t`vendor_id` INT(6) NOT NULL DEFAULT \'0\' COMMENT \'from vendors & i_route\',\\r\\n\\t`rate` FLOAT NOT NULLDEFAULT \'0\' COMMENT \'from i_route\',\\r\\n\\t`costsec` INT(10) NOT NULL DEFAULT \'0\',\\r\\n\\t`cost` FLOAT NOT NULL DEFAULT \'0\',\\r\\n\\t`successful` TINYINT(4) NOT NULL DEFAULT \'0\',\\r\\n\\t`kind` SMALLINT(6) NOT NULL DEFAULT -1 COMMENT \'from cdr.userfield\',\\r\\n\\t`waslnp` TINYINT(1) NULL DEFAULT NULL,\\r\\n\\t`lnprate` FLOAT NULL DEFAULT \'0\',\\r\\n\\t`lnpcost` FLOAT NULL DEFAULT \'0\',\\r\\n\\tINDEX `cdrid` (`cdrid`) USING BTREE,\\r\\n\\tINDEX `calldate` (`calldate`) USING BTREE,\\r\\n\\tINDEX `rci` (`rci`) USING BTREE,\\r\\n\\tINDEX `peer` (`peer`) USING BTREE,\\r\\n\\tINDEX `kind` (`kind`) USING BTREE\\r\\n)","position":"mysql-bin.000979:703768378"}' WHERE  `id`=1
#211102  0:16:09 server id 373  end_log_pos 383181388 CRC32 0x7cbc3633  Table_map: `broker`.`dalejsontest` mapped to number 665686
# at 383181388
#211102  0:16:09 server id 373  end_log_pos 383183354 CRC32 0xc145e938  Update_rows: table id 665686 flags: STMT_END_F

BINLOG '
ueWAYRN1AQAAPQAAAEzi1hYAAFYoCgAAAAEABmJyb2tlcgAMZGFsZWpzb250ZXN0AAMIEvwCAAQA
Mza8fA==
ueWAYRh1AQAArgcAAPrp1hYAAFYoCgAAAAEAA///+AEAAAAAAAAAmasEA+4AAAAA+AEAAAAAAAAA
masEA+5oBwAAeyJ0eXBlIjoidGFibGUtY3JlYXRlIiwiZGF0YWJhc2UiOiJicm9rZXIiLCJ0YWJs
ZSI6ImRhbGV0ZXN0IiwiZGVmIjp7ImRhdGFiYXNlIjoiYnJva2VyIiwiY2hhcnNldCI6ImxhdGlu
MSIsInRhYmxlIjoiZGFsZXRlc3QiLCJjb2x1bW5zIjpbeyJ0eXBlIjoiYmlnaW50IiwibmFtZSI6
ImNkcmlkIiwic2lnbmVkIjp0cnVlfSx7InR5cGUiOiJkYXRldGltZSIsIm5hbWUiOiJjYWxsZGF0
ZSIsImNvbHVtbi1sZW5ndGgiOjB9LHsidHlwZSI6ImludCIsIm5hbWUiOiJyY2kiLCJzaWduZWQi
OmZhbHNlfSx7InR5cGUiOiJ2YXJjaGFyIiwibmFtZSI6InBlZXIiLCJjaGFyc2V0IjoibGF0aW4x
In0seyJ0eXBlIjoiaW50IiwibmFtZSI6InZlbmRvcl9pZCIsInNpZ25lZCI6dHJ1ZX0seyJ0eXBl
IjoiZmxvYXQiLCJuYW1lIjoicmF0ZSJ9LHsidHlwZSI6ImludCIsIm5hbWUiOiJjb3N0c2VjIiwi
c2lnbmVkIjp0cnVlfSx7InR5cGUiOiJmbG9hdCIsIm5hbWUiOiJjb3N0In0seyJ0eXBlIjoidGlu
eWludCIsIm5hbWUiOiJzdWNjZXNzZnVsIiwic2lnbmVkIjp0cnVlfSx7InR5cGUiOiJzbWFsbGlu
dCIsIm5hbWUiOiJraW5kIiwic2lnbmVkIjp0cnVlfSx7InR5cGUiOiJ0aW55aW50IiwibmFtZSI6
Indhc2xucCIsInNpZ25lZCI6dHJ1ZX0seyJ0eXBlIjoiZmxvYXQiLCJuYW1lIjoibG5wcmF0ZSJ9
LHsidHlwZSI6ImZsb2F0IiwibmFtZSI6ImxucGNvc3QifV0sInByaW1hcnkta2V5IjpbXX0sInRz
IjoxNjM1NTU0MjU2MDAwLCJzcWwiOiItLSBEUk9QIFRBQkxFIGJyb2tlci5kYWxldGVzdDtcclxu
XHJcbkNSRUFURSBUQUJMRSBicm9rZXIuZGFsZXRlc3QgKFxyXG5cdGBjZHJpZGAgQklHSU5UKDIy
KSBOT1QgTlVMTCBDT01NRU5UICdmcm9tIGNkci5pZCcsXHJcblx0YGNhbGxkYXRlYCBEQVRFVElN
RSBOT1QgTlVMTCBERUZBVUxUICcwMDAwLTAwLTAwIDAwOjAwOjAwJyBDT01NRU5UICdmcm9tIGNk
ci5jYWxsZGF0ZScsXHJcblx0YHJjaWAgSU5UKDQpIFVOU0lHTkVEIFpFUk9GSUxMIE5PVCBOVUxM
IERFRkFVTFQgJzAwMDAnIENPTU1FTlQgJ2Zyb20gY2RyLnVzZXJmaWVsZCcsXHJcblx0YHBlZXJg
IFZBUkNIQVIoNDApIE5PVCBOVUxMIENPTU1FTlQgJ2Zyb20gY2RyLmRzdGNoYW5uZWwsIHZlbmRv
cnMucGVlcicgQ09MTEFURSAnbGF0aW4xX3N3ZWRpc2hfY2knLFxyXG5cdGB2ZW5kb3JfaWRgIElO
VCg2KSBOT1QgTlVMTCBERUZBVUxUICcwJyBDT01NRU5UICdmcm9tIHZlbmRvcnMgJiBpX3JvdXRl
JyxcclxuXHRgcmF0ZWAgRkxPQVQgTk9UIE5VTEwgREVGQVVMVCAnMCcgQ09NTUVOVCAnZnJvbSBp
X3JvdXRlJyxcclxuXHRgY29zdHNlY2AgSU5UKDEwKSBOT1QgTlVMTCBERUZBVUxUICcwJyxcclxu
XHRgY29zdGAgRkxPQVQgTk9UIE5VTEwgREVGQVVMVCAnMCcsXHJcblx0YHN1Y2Nlc3NmdWxgIFRJ
TllJTlQoNCkgTk9UIE5VTEwgREVGQVVMVCAnMCcsXHJcblx0YGtpbmRgIFNNQUxMSU5UKDYpIE5P
VCBOVUxMIERFRkFVTFQgLTEgQ09NTUVOVCAnZnJvbSBjZHIudXNlcmZpZWxkJyxcclxuXHRgd2Fz
bG5wYCBUSU5ZSU5UKDEpIE5VTEwgREVGQVVMVCBOVUxMLFxyXG5cdGBsbnByYXRlYCBGTE9BVCBO
VUxMIERFRkFVTFQgJzAnLFxyXG5cdGBsbnBjb3N0YCBGTE9BVCBOVUxMIERFRkFVTFQgJzAnLFxy
XG5cdElOREVYIGBjZHJpZGAgKGBjZHJpZGApIFVTSU5HIEJUUkVFLFxyXG5cdElOREVYIGBjYWxs
ZGF0ZWAgKGBjYWxsZGF0ZWApIFVTSU5HIEJUUkVFLFxyXG5cdElOREVYIGByY2lgIChgcmNpYCkg
VVNJTkcgQlRSRUUsXHJcblx0SU5ERVggYHBlZXJgIChgcGVlcmApIFVTSU5HIEJUUkVFLFxyXG5c
dElOREVYIGBraW5kYCAoYGtpbmRgKSBVU0lORyBCVFJFRVxyXG4pIiwicG9zaXRpb24iOiJteXNx
bC1iaW4uMDAwOTc5OjcwMzc2ODM3OCJ9OOlFwQ==
'/*!*/;
### UPDATE `broker`.`dalejsontest`
### WHERE
###   @1=1
###   @2='2021-11-02 00:15:46'
###   @3=''
### SET
###   @1=1
###   @2='2021-11-02 00:15:46'
###   @3='{"type":"table-create","database":"broker","table":"daletest","def":{"database":"broker","charset":"latin1","table":"daletest","columns":[{"type":"bigint","name":"cdrid","signed":true},{"type":"datetime","name":"calldate","column-length":0},{"type":"int","name":
"rci","signed":false},{"type":"varchar","name":"peer","charset":"latin1"},{"type":"int","name":"vendor_id","signed":true},{"type":"float","name":"rate"},{"type":"int","name":"costsec","signed":true},{"type":"float","name":"cost"},{"type":"tinyint","name":"successful","sig
ned":true},{"type":"smallint","name":"kind","signed":true},{"type":"tinyint","name":"waslnp","signed":true},{"type":"float","name":"lnprate"},{"type":"float","name":"lnpcost"}],"primary-key":[]},"ts":1635554256000,"sql":"-- DROP TABLE broker.daletest;\r\n\r\nCREATE TABLE
broker.daletest (\r\n\t`cdrid` BIGINT(22) NOT NULL COMMENT 'from cdr.id',\r\n\t`calldate` DATETIME NOT NULL DEFAULT '0000-00-00 00:00:00' COMMENT 'from cdr.calldate',\r\n\t`rci` INT(4) UNSIGNED ZEROFILL NOT NULL DEFAULT '0000' COMMENT 'from cdr.userfield',\r\n\t`peer` VAR
CHAR(40) NOT NULL COMMENT 'from cdr.dstchannel, vendors.peer' COLLATE 'latin1_swedish_ci',\r\n\t`vendor_id` INT(6) NOT NULL DEFAULT '0' COMMENT 'from vendors & i_route',\r\n\t`rate` FLOAT NOT NULL DEFAULT '0' COMMENT 'from i_route',\r\n\t`costsec` INT(10) NOT NULL DEFAULT
 '0',\r\n\t`cost` FLOAT NOT NULL DEFAULT '0',\r\n\t`successful` TINYINT(4) NOT NULL DEFAULT '0',\r\n\t`kind` SMALLINT(6) NOT NULL DEFAULT -1 COMMENT 'from cdr.userfield',\r\n\t`waslnp` TINYINT(1) NULL DEFAULT NULL,\r\n\t`lnprate` FLOAT NULL DEFAULT '0',\r\n\t`lnpcost` FLO
AT NULL DEFAULT '0',\r\n\tINDEX `cdrid` (`cdrid`) USING BTREE,\r\n\tINDEX `calldate` (`calldate`) USING BTREE,\r\n\tINDEX `rci` (`rci`) USING BTREE,\r\n\tINDEX `peer` (`peer`) USING BTREE,\r\n\tINDEX `kind` (`kind`) USING BTREE\r\n)","position":"mysql-bin.000979:703768378
"}'
# Number of rows: 1
# at 383183354
#211102  0:16:09 server id 373  end_log_pos 383183385 CRC32 0x5fe52118  Xid = 5255920604
COMMIT/*!*/;
# at 383183385
#211102  0:16:14 server id 250223  end_log_pos 383183427 CRC32 0xc1e77604       GTID 0-250223-207345002
/*!100101 SET @@session.skip_parallel_replication=0*//*!*/;
/*!100001 SET @@session.gtid_domain_id=0*//*!*/;
/*!100001 SET @@session.server_id=250223*//*!*/;
/*!100001 SET @@session.gtid_seq_no=207345002*//*!*/;

```
