### ISSUE TITLE
Add optional transaction offset to records

### ISSUE THREAD

**Issue by jkgeyti** [zendesk/maxwell#871]
When pushing rows to non-transactional systems (like kafka), I don't think it's currently possible to uniquely identify non-committed rows in transactions, as they all have the same `server_id`, `position` and `xid`.

Would it make sense to add an optional `xoffset` to rows, which is a simple counter that's incremented for every row in a transaction, and reset for every new transaction?

This would make it possible for consumers to consume messages in an exactly-once manner by only ever consuming messages by comparing to the last seen (`server_id`, `position`) and (`xid`, `xoffset`) combinations - even in disaster scenarios where maxwell loses track of its position and has to do a restart from the beginning of the binlog.

I'll happily take a stab at a PR, but wanted to have the discussion before doing anything.

**Comment by osheroff** [comment]
sure, that makes a certain degree of sense.  feel free to PR it.

**Comment by liulikun** [comment]
@jkgeyti just want to confirm: the (xid, position) should be unique within the same mysql cluster, so you could check (xid, position) to dedup.

**Comment by jkgeyti** [comment]
@liulikun Unique from what point of view? As far as I understand (position, xid) is unique and strictly increasing in the binlog, sure. However, maxwell may split "a binlog position chunk" into multple events and stream those independently to e.g. kafka. So both `position` and `xid` are monotonically - but not strictly - increasing on the kafka topic.

My suggestion is to add an extra "intra-transaction-offset" counter, such that `(xid, tx-offset)` is strictly increasing, hence allowing consumers to uniquely identify messages.

**Comment by dongxiaohe** [comment]
Would it be better to rollup the db transaction in maxwell ? `RowMapBuffer` is holding one transaction details which contains the list of `RowMap` including contains `xid` and `is_commit`. I guess we can make some changes related to it. Any concern for that ? 

- Big transaction issue
- Caching in maxwell

**Comment by jkgeyti** [comment]
It should be said that if this is found to be too esoteric a safety guarantee for the core producers, the offset can be added by custom producers using the functionality merged in https://github.com/zendesk/maxwell/pull/870 .

**Comment by liulikun** [comment]
@jkgeyti Maxwell publishes `position` for every single row change, and that's unique already, should be good enough for deduplication. I don't think maxwell can split `a binlog position chunk` into multiple events. Do you have an example or some code reference?

**Comment by jkgeyti** [comment]
Use the following config to ensure we show all possible information maxwell allows us:

```
output_row_query=true
output_ddl=true
output_thread_id=true
output_nulls=true
output_binlog_position=true
output_server_id=true
```

Create the following producer:

```
@Override
public void push(RowMap r) throws Exception {
	System.out.println(r.toJSON(this.outputConfig));
}
```

Create a table. Let's use InnoDB to ensure we've got full support for transactions:

```
CREATE TABLE `maxwell_test` (
  `text` varchar(255) NOT NULL DEFAULT ''
) ENGINE=InnoDB DEFAULT CHARSET=utf8;
```

Submit a transaction to mysql:

```
START TRANSACTION;
INSERT INTO maxwell_test (text) VALUES (1);
INSERT INTO maxwell_test (text) VALUES (1);
INSERT INTO maxwell_test (text) VALUES (1);
COMMIT;
```

The output is:

```
{"database":"test","table":"test","type":"insert","ts":1518599667,"xid":1000,"position":"mysql-bin.000001:1000","server_id":269,"thread_id":20245999,"data":{"text":"1"}}
{"database":"test","table":"test","type":"insert","ts":1518599667,"xid":1000,"position":"mysql-bin.000001:1000","server_id":269,"thread_id":20245999,"data":{"text":"1"}}
{"database":"test","table":"test","type":"insert","ts":1518599667,"xid":1000,"commit":true,"position":"mysql-bin.000001:1000","server_id":269,"thread_id":20245999,"data":{"text":"1"}}
```

Notice how I can't distinguish the two first events. If maxwell crashed before writing the third row and storing the offset, the previous messages would be repeated, and I wouldn't be able to tell how many inserts were actually done as part of the transaction (other than guessing based on timing). This can be fixed by adding a transaction offset (`x-offset`):

```
{"database":"test","table":"test","type":"insert","ts":1518599667,"xid":1000,"x-offset":0,"position":"mysql-bin.000001:1000","server_id":269,"thread_id":20245999,"data":{"text":"1"}}
{"database":"test","table":"test","type":"insert","ts":1518599667,"xid":1000,"x-offset":1,"position":"mysql-bin.000001:1000","server_id":269,"thread_id":20245999,"data":{"text":"1"}}
{"database":"test","table":"test","type":"insert","ts":1518599667,"xid":1000,"x-offset":2,"commit":true,"position":"mysql-bin.000001:1000","server_id":269,"thread_id":20245999,"data":{"text":"1"}}
```

I can now readily identify duplicate messages from maxwell using `(xid, x-offset)`.

If this is a reproducable bug, I'm adament the right fix is to add the offset to RowMap, so messages are identifaible in case of network retries etc. I'll create a PR for that once someone confirms this problem is reproducable.

Whether or not it should be added to maxwell's internal positions store is up to your descretion. `MaxwellContext.setPosition(RowMap r)` will only store the position if `RowMap.isTxCommit()` is true, so there's a design decision there to never store uncommitted positions anyway. There's however also a `MaxwellContext.setPosition(Position position)` method which lets you override this behaviour, so it's not a hard rule. Up to you.

**Comment by osheroff** [comment]
@jkgeyti, I'm not totally against your approach, but it seems like you could use a `(binlogposition, kafka-offset)` tuple to uniquely identify a row.

**Comment by jkgeyti** [comment]
You can uniquely identify a kafka event using kafka's offset, but it doesn't help you if maxwell repeats indistinguishable events onto kafka.

Again, let's take the transaction maxwells wants to write:

```
{"database":"test","table":"test","type":"insert","ts":1518599667,"xid":1000,"position":"mysql-bin.000001:1000","server_id":269,"thread_id":20245999,"data":{"text":"1"}}
{"database":"test","table":"test","type":"insert","ts":1518599667,"xid":1000,"position":"mysql-bin.000001:1000","server_id":269,"thread_id":20245999,"data":{"text":"1"}}
{"database":"test","table":"test","type":"insert","ts":1518599667,"xid":1000,"commit":true,"position":"mysql-bin.000001:1000","server_id":269,"thread_id":20245999,"data":{"text":"1"}}
```

Let's simplify this a bit for the sake of this argument:

```
(position=1, xid=1, data=1, commit=false)
(position=1, xid=1, data=1, commit=false)
(position=1, xid=1, data=1, commit=true)
```

Let maxwell crash after writing the second messages to kafka, but before the third containing the commit. Kafka now contains:

```
OFFSET  KEY           VALUE
1       UUID (no PK)  (position=1, xid=1, data=1, commit=false)
2       UUID (no PK)  (position=1, xid=1, data=1, commit=false)
```

When maxwell restarts it resumes from the last known offset. As we didn't reach the commit of the above transaction, we repeat the entire transaciton. Maxwell writes all three messages to kafka, and stores the offset. From maxwell's perspective, this transaction is now done, and we'll never revisit that binlog position.

Kafka now contains the following, and we have no way to tell which of these messages are actually part of the transaction, and which are merely repeated messages:

```
OFFSET  KEY           VALUE
1       UUID (no PK)  (position=1, xid=1, data=1, commit=false)
2       UUID (no PK)  (position=1, xid=1, data=1, commit=false)
3       UUID (no PK)  (position=1, xid=1, data=1, commit=false)
4       UUID (no PK)  (position=1, xid=1, data=1, commit=false)
5       UUID (no PK)  (position=1, xid=1, data=1, commit=true)
```

My proposed solution is to add a transaction offset, such that we'd see the following on maxwell:

```
OFFSET  KEY           VALUE
1       UUID (no PK)  (position=1, xid=1, x-offset=0, data=1, commit=false)
2       UUID (no PK)  (position=1, xid=1, x-offset=1, data=1, commit=false)
3       UUID (no PK)  (position=1, xid=1, x-offset=0, data=1, commit=false)
4       UUID (no PK)  (position=1, xid=1, x-offset=1, data=1, commit=false)
5       UUID (no PK)  (position=1, xid=1, x-offset=2, data=1, commit=true)
```

I think this is the easiest way to guarantee exactly-once consumption by clients, as they only have to keep 1 tuple in memory (position, xid, x-offset), and never consume messages smaller or equal to those previously seen. 

Another potential solution is to have maxwell write a start-up message to all kafka topics telling clients to invalidate any uncommitted transactions:

```
OFFSET  KEY           VALUE
1       UUID (no PK)  (position=1, xid=1, data=1, commit=false)
2       UUID (no PK)  (position=1, xid=1, data=1, commit=false)
3		...           (type=PLEASE_INVALIDATE_ALL_UNCOMMITTED_TRANSACTIONS)
4       UUID (no PK)  (position=1, xid=1, data=1, commit=false)
5       UUID (no PK)  (position=1, xid=1, data=1, commit=false)
6       UUID (no PK)  (position=1, xid=1, data=1, commit=true)
```

Finally, please bear in mind that even if maxwell tracks the x-offset internally to avoid repeatedly producing the same rowmaps from the binlog, we may still send repeated messages to kafka due to network failures. With an x-offset, users can safely use `retries > 1` to ensure healthy at-least-once delivery, while still being able to write exactly-once consumers due to the now strictly (instead of merely monotonically) increasing `(server_id, position, xid, x-offset)` tuple.

**Comment by osheroff** [comment]
@jkgeyti right, right, sorry.  the transaction offset solution is fine.

**Comment by jkgeyti** [comment]
Awesome. I've added a test, and fixed the ones that fail. Are you happy to have xoffset included when `output_commit_info=true`, or do you prefer a separate config? `output_commit_info=true` is default, so this PR will add the extra xcommit field to running setups when people upgrade.

**Comment by osheroff** [comment]
please put it behind its own config option

**Comment by jkgeyti** [comment]
Updated in https://github.com/zendesk/maxwell/pull/882

**Comment by jkgeyti** [comment]
Are there any more considerations before considering merging this?

**Comment by jkgeyti** [comment]
Merged in https://github.com/zendesk/maxwell/pull/882
