### ISSUE TITLE
Add support to encrypt password for maxwell user in MySQL

### ISSUE THREAD

**Issue by nminhquan** [zendesk/maxwell#872]
Hello team,

Right now, we are storing the maxwell username and password of MySQL in plaintext in config.properties file, example:
...
host=192.168.99.146
user=maxwell
password=XXXXXX
...

It violates our company's policy. I wonder if you can enhance to encrypt the password of the maxwell user in MySQL.

Regards,
Quan

**Comment by ericwush** [comment]
@nminhquan You can always pass the args through command line. Have a look: https://github.com/zendesk/maxwell/blob/master/docs/docs/quickstart.md

**Comment by osheroff** [comment]
no, not possible; the best thing to do here is to have a shell script running maxwell that asks for the password (or decrypts it from disk, I'm not sure how exactly that will be more secure, but whatever, company policies), and then writes a temporary `config.properties` from a template.  after maxwell launches the script can then cleanup the file.
