### ISSUE TITLE
Enriching rows with fields from other tables

### ISSUE THREAD

**Issue by rredhatt** [zendesk/maxwell#876]
We have been testing Maxwell to push various tables to a Kinesis stream and so far, it has been working flawlessly. At this stage we would like to explore the ability of having Maxwell enriching a particular event with the values from another table before pushing them to the stream.

**Comment by osheroff** [comment]
I had started something around this here:
https://github.com/zendesk/maxwell-join

But it’s generally non-trivial: there’s an easier path where you simply re-query the database for values from other tables when you receive a row update, but this can’t guarantee that you’re getting a coherent view of your data.
