### ISSUE TITLE
TimeoutException with kafka 1.0.0 version

### ISSUE THREAD

**Issue by MadeInChina** [zendesk/maxwell#879]
11:11:40,582 ERROR MaxwellKafkaProducer - TimeoutException @ Position[BinlogPosition[master.000003:475945], lastHeartbeat=1518512008982] -- {"database":"test","table":"USER","pk.pk_user_id":44}
11:11:40,582 ERROR MaxwellKafkaProducer - Expiring 5 record(s) for USER-0: 30009 ms has passed since batch creation plus linger time

**Comment by MadeInChina** [comment]
https://github.com/zendesk/maxwell/pull/878

**Comment by dongxiaohe** [comment]
@MadeInChina 👋  do you think this issue is related to kafka 1.0 version ? Is there any performance improvement ?

**Comment by MadeInChina** [comment]
@dongxiaohe 
It's not related to kafka 1.0 version.
but 
there are many improvements,bugs fix  and new feature on kafka 1.0.

[Release Notes - Kafka - Version 1.0.0](https://www.apache.org/dist/kafka/1.0.0/RELEASE_NOTES.html)
