### ISSUE TITLE
AWS VPC Links with Kinesis Maxwell producer

### ISSUE THREAD

**Issue by benderTheCrime** [zendesk/maxwell#880]
I'm not sure how much detail I should add to this issue, but I've got a working Kinesis producer implementation.

Is there a way to specify what URL the Kinesis producer should use to PutRecords on the Kinesis stream? What I would like to do is specify a VPC link and not use the generic constructed AWS URL: `http://{region}.{stream}.amazonaws.com` or whatever the generic URL that gets generated is.

Perhaps something in the form of an execArg that can be provided to the Maxwell bin? I would much prefer this over hacking into the existing implementation.

**Comment by benderTheCrime** [comment]
It looks like perhaps this is possible through the actual KPL, via `KinesisProducerConfiguration` by loading a VPC url into the actual configuration file.

**Comment by osheroff** [comment]
no expert on kinesis, but it looks like you should be able to add `KinesisEndpoint=` to the kinesis producer properties file, "kinesis-producer-library.properties"

**Comment by osheroff** [comment]
@benderTheCrime I'm closing this since `KinesisEndpoint` is probably what you want, feel free to re-open if it doesn't work.

**Comment by benderTheCrime** [comment]
Ah yes, thanks for this. I'm still having some trouble because KinesisEndpoint and KinesisPort are configurable, but you cannot specify _no_ KinesisPort. I opened an [issue](https://github.com/awslabs/amazon-kinesis-producer/issues/184) on the KPL
