### ISSUE TITLE
RabbitMQ persistent messages

### ISSUE THREAD

**Issue by anastazya** [zendesk/maxwell#881]
This option "--rabbitmq_message_persistent" is not recognised when starting maxwell. I tried multiple syntax, like --rabbitmq_message_persistent="true", or --rabbitmq_message_persistent="enabled". This is reported by maxwell's --help as a viable option.
Thank you !

**Comment by anastazya** [comment]
maxwell     | Using kafka version: 0.11.0.1
maxwell     | joptsimple.UnrecognizedOptionException: rabbitmq_message_persistent is not a recognized option
maxwell     | 	at joptsimple.OptionException.unrecognizedOption(OptionException.java:108)
maxwell     | 	at joptsimple.OptionParser.handleLongOptionToken(OptionParser.java:449)
maxwell     | 	at joptsimple.OptionParserState$2.handleArgument(OptionParserState.java:56)
maxwell     | 	at joptsimple.OptionParser.parse(OptionParser.java:381)
maxwell     | 	at com.zendesk.maxwell.MaxwellConfig.parse(MaxwellConfig.java:291)
maxwell     | 	at com.zendesk.maxwell.MaxwellConfig.<init>(MaxwellConfig.java:130)
maxwell     | 	at com.zendesk.maxwell.Maxwell.main(Maxwell.java:196)
maxwell exited with code 1

**Comment by osheroff** [comment]
i can't reproduce this error: what's the full command line?

**Comment by anastazya** [comment]
#!/bin/bash
/maxwell-1.11.0/bin/maxwell --user='root' --password="$MYSQL_ROOT_PASSWORD" \
							--host='mysql' --include_dbs=$MYSQL_MAIN_DB \
							--exclude_tables=/trigger_queue*/,/crm_*/ \
							--producer=rabbitmq --rabbitmq_host='rabbitmq' \
							--rabbitmq_user="$RABBITMQ_USERNAME" \
							--rabbitmq_pass="$RABBITMQ_PASSWORD" \
							--rabbitmq_exchange="amq.direct" \
							--rabbitmq_exchange_type="direct" \
							--rabbitmq_exchange_durable="true" \
							--rabbitmq_routing_key_template="test" \
							--rabbitmq_message_persistent

**Comment by osheroff** [comment]
& what version of maxwell are you using?

**Comment by osheroff** [comment]
(I simply can't reproduce this error at all)

**Comment by osheroff** [comment]
you may want to quote your `exclude_tables` argument.

**Comment by anastazya** [comment]
maxwell-1.11.0 , in docker, run as per instructions form here : http://maxwells-daemon.io/quickstart/

**Comment by anastazya** [comment]
Argument quoted.

**Comment by osheroff** [comment]
Ok, that feature wasn’t introduced until 1.12

**Comment by anastazya** [comment]
Thank you, dully noted. It was in the list provided by the "--help" flag, even in version 1.11.0 thou ...
