### ISSUE TITLE
Maxwell ``Unresolveable build extension'' issue with Eclipse

### ISSUE THREAD

**Issue by ashashwat** [zendesk/maxwell#888]
While importing maxwell in Eclipse as a maven project I see the following error: `Plugin execution not covered by lifecycle configuration: org.apache.maven.plugins:maven-dependency-plugin:2.8:copy-dependencies (execution: default, phase: compile)`.  

Eclipse quick-fix does recommend ways to fix it.

![maxwell-eclipse](https://user-images.githubusercontent.com/121233/36366386-e6938042-1573-11e8-8398-333f460f7d52.png)

Alternatively using `<pluginManagement>` tag in pom.xml fixed it as described [here](https://stackoverflow.com/questions/6352208/how-to-solve-plugin-execution-not-covered-by-lifecycle-configuration-for-sprin).  

Is this a bug where it is worth fixing pom.xml or can it simply be ignored?

**Comment by osheroff** [comment]
feel free to fixup the pom.xml to make it work for you.

**Comment by ashashwat** [comment]
@osheroff I did for my local installation.  Should I raise a PR for this or close the issue?
