### ISSUE TITLE
Only produce event when specific column updated on table

### ISSUE THREAD

**Issue by pasali** [zendesk/maxwell#896]
Can i configure maxwell to produce event only specific column updated on table ? There is a option `include_column_values` for matching only column and value. There might be option something like `match_columns` and matches only when specific column updated.

**Comment by ashashwat** [comment]
AFAIK binary log is missing that piece of information.

**Comment by osheroff** [comment]
@ashashwat no, we could do that.  There's currently no maxwell option to do this though.

**Comment by ashashwat** [comment]
@osheroff  I was misinformed then.  Do you think it is something worth implementing?

**Comment by osheroff** [comment]
@ashashwat I'm biting the bullet and looking into a little javascript bridge for maxwell; there's just too many varying use cases and I'd like to be able to support them all behind a "go script it" interface.

**Comment by pasali** [comment]
@osheroff It would be appreciated if this feature could implemented 👍

**Comment by osheroff** [comment]
javascript filters should solve this issue
