### ISSUE TITLE
Log levels expansion ?

### ISSUE THREAD

**Issue by ashashwat** [zendesk/maxwell#898]
According to [config](http://maxwells-daemon.io/config/), Maxwell log level can be `[debug | info | warn | error]` defaulting to _info_.  However internally it uses Log4j meaning the permissible levels are `[all | trace | debug | info | warn | error | fatal | off ]` defaulting to _info_.  

Is it fine to keep the doc as it is or change it to reflect the true state of the code?

**Comment by osheroff** [comment]
I don't think we ever bother with `trace` or `fatal` so I left those out.  No idea what `all` means.

**Comment by ashashwat** [comment]
According to [documentation](https://logging.apache.org/log4j/1.2/apidocs/org/apache/log4j/Level.html#ALL), _ALL_ turns on all logging.  I have never used it myself.  

After giving it some thought, I think the natural state of `[debug | info | warn | error]` is fine.  Maybe `off` can be added at most.  I am closing this considering it a non-issue.
