### ISSUE TITLE
Adding a way to set PORT for rabbitMQ producer

### ISSUE THREAD

**Issue by microThread** [zendesk/maxwell#920]
Hello guys, my team want to say: 
EXCELLENT JOB FOR THIS AWESOME PROJECT AND WE THANK YOU FOR YOUR HARD WORK!
-------

We need to know if there is any way to set the port for RabbitMQ in the config file?

**Comment by microThread** [comment]
https://github.com/zendesk/maxwell/pull/921

**Comment by osheroff** [comment]
PR merged.
