### ISSUE TITLE
怎么同时指定多个schema进行同步

### ISSUE THREAD

**Issue by shubifeng** [zendesk/maxwell#922]

**Comment by osheroff** [comment]
Can you translate this into english?  You might get lucky and find someone who speaks the language, but you might not.

**Comment by kachebb** [comment]
LOL, I'll try to translate it.  
How do I run synchronization for multiple schemas at the same time?  Forgive me if that's not what you mean.

**Comment by ericwush** [comment]
The question was, how to specify the schemas for binlog replication?
Please see `Filters` in http://maxwells-daemon.io/config

**Comment by shubifeng** [comment]
@kachebb @ericwush 同一个binlog能按库 指定 到不同的kafka topic吗?

**Comment by ericwush** [comment]
@shubifeng https://github.com/zendesk/maxwell/blob/873693375bb64ad10716aaa4eeccb4bf72210ea3/src/main/java/com/zendesk/maxwell/producer/MaxwellKafkaProducer.java#L194

Just configure maxwell as per the instruction you pasted.

**Comment by osheroff** [comment]
I'm gonna assume this is solved?  feel free to re-open as needed.
