### ISSUE TITLE
maxwell fails even with option 'kafka_version=0.8.2.2' for kafka cluster 0.8.2.1 version 

### ISSUE THREAD

**Issue by ravikiranks** [zendesk/maxwell#923]
Mar 18 05:56:12 nlpstream-1-001.live.bi2.las1.xyz-inc.com maxwell_1[10802]: java.io.EOFException: null
Mar 18 05:56:12 nlpstream-1-001.live.bi2.las1.xyz-inc.com maxwell_1[10802]: at org.apache.kafka.common.network.NetworkReceive.readFromReadableChannel(NetworkReceive.java:87) ~[maxwell-1.13.2-jar-with-depen
Mar 18 05:56:12 nlpstream-1-001.live.bi2.las1.xyz-inc.com maxwell_1[10802]: at org.apache.kafka.common.network.NetworkReceive.readFrom(NetworkReceive.java:75) ~[maxwell-1.13.2-jar-with-dependencies.jar:?]
Mar 18 05:56:12 nlpstream-1-001.live.bi2.las1.xyz-inc.com maxwell_1[10802]: at org.apache.kafka.common.network.KafkaChannel.receive(KafkaChannel.java:203) ~[maxwell-1.13.2-jar-with-dependencies.jar:?]
Mar 18 05:56:12 nlpstream-1-001.live.bi2.las1.xyz-inc.com maxwell_1[10802]: at org.apache.kafka.common.network.KafkaChannel.read(KafkaChannel.java:167) ~[maxwell-1.13.2-jar-with-dependencies.jar:?]
Mar 18 05:56:12 nlpstream-1-001.live.bi2.las1.xyz-inc.com maxwell_1[10802]: at org.apache.kafka.common.network.Selector.pollSelectionKeys(Selector.java:381) [maxwell-1.13.2-jar-with-dependencies.jar:?]
Mar 18 05:56:12 nlpstream-1-001.live.bi2.las1.xyz-inc.com maxwell_1[10802]: at org.apache.kafka.common.network.Selector.poll(Selector.java:326) [maxwell-1.13.2-jar-with-dependencies.jar:?]
Mar 18 05:56:12 nlpstream-1-001.live.bi2.las1.xyz-inc.com maxwell_1[10802]: at org.apache.kafka.clients.NetworkClient.poll(NetworkClient.java:433) [maxwell-1.13.2-jar-with-dependencies.jar:?]
Mar 18 05:56:12 nlpstream-1-001.live.bi2.las1.xyz-inc.com maxwell_1[10802]: at org.apache.kafka.clients.producer.internals.Sender.run(Sender.java:224) [maxwell-1.13.2-jar-with-dependencies.jar:?]
...skipping...
Mar 18 05:56:12 nlpstream-1-001.live.bi2.las1.xyz-inc.com maxwell_1[10802]: at org.apache.kafka.common.network.NetworkReceive.readFrom(NetworkReceive.java:75) ~[maxwell-1.13.2-jar-with-dependencies.jar:?]
Mar 18 05:56:12 nlpstream-1-001.live.bi2.las1.xyz-inc.com maxwell_1[10802]: at org.apache.kafka.common.network.KafkaChannel.receive(KafkaChannel.java:203) ~[maxwell-1.13.2-jar-with-dependencies.jar:?]
Mar 18 05:56:12 nlpstream-1-001.live.bi2.las1.xyz-inc.com maxwell_1[10802]: at org.apache.kafka.common.network.KafkaChannel.read(KafkaChannel.java:167) ~[maxwell-1.13.2-jar-with-dependencies.jar:?]
Mar 18 05:56:12 nlpstream-1-001.live.bi2.las1.xyz-inc.com maxwell_1[10802]: at org.apache.kafka.common.network.Selector.pollSelectionKeys(Selector.java:381) [maxwell-1.13.2-jar-with-dependencies.jar:?]
Mar 18 05:56:12 nlpstream-1-001.live.bi2.las1.xyz-inc.com maxwell_1[10802]: at org.apache.kafka.common.network.Selector.poll(Selector.java:326) [maxwell-1.13.2-jar-with-dependencies.jar:?]
Mar 18 05:56:12 nlpstream-1-001.live.bi2.las1.xyz-inc.com maxwell_1[10802]: at org.apache.kafka.clients.NetworkClient.poll(NetworkClient.java:433) [maxwell-1.13.2-jar-with-dependencies.jar:?]
Mar 18 05:56:12 nlpstream-1-001.live.bi2.las1.xyz-inc.com maxwell_1[10802]: at org.apache.kafka.clients.producer.internals.Sender.run(Sender.java:224) [maxwell-1.13.2-jar-with-dependencies.jar:?]
Mar 18 05:56:12 nlpstream-1-001.live.bi2.las1.xyz-inc.com maxwell_1[10802]: at org.apache.kafka.clients.producer.internals.Sender.run(Sender.java:162) [maxwell-1.13.2-jar-with-dependencies.jar:?]
Mar 18 05:56:12 nlpstream-1-001.live.bi2.las1.xyz-inc.com maxwell_1[10802]: at java.lang.Thread.run(Thread.java:745) [?:1.8.0_45]
Mar 18 05:56:12 nlpstream-1-001.live.bi2.las1.xyz-inc.com maxwell_1[10802]: 05:56:12,803 DEBUG Selector - Created socket with SO_RCVBUF = 32768, SO_SNDBUF = 131071, SO_TIMEOUT = 0 to node -18
Mar 18 05:56:12 nlpstream-1-001.live.bi2.las1.xyz-inc.com maxwell_1[10802]: 05:56:12,803 DEBUG NetworkClient - Node -13 disconnected.
Mar 18 05:56:12 nlpstream-1-001.live.bi2.las1.xyz-inc.com maxwell_1[10802]: 05:56:12,803 DEBUG NetworkClient - Completed connection to node -18. Fetching API versions.
Mar 18 05:56:12 nlpstream-1-001.live.bi2.las1.xyz-inc.com maxwell_1[10802]: 05:56:12,803 DEBUG NetworkClient - Initiating API versions fetch from node -18.
Mar 18 05:56:12 nlpstream-1-001.live.bi2.las1.xyz-inc.com maxwell_1[10802]: 05:56:12,803 DEBUG NetworkClient - Initialize connection to node prodkafka-1-006.live.bi2.las1.xyz-inc.com:9092 (id: -6 rack: null
Mar 18 05:56:12 nlpstream-1-001.live.bi2.las1.xyz-inc.com maxwell_1[10802]: 05:56:12,803 DEBUG NetworkClient - Initiating connection to node prodkafka-1-006.live.bi2.las1.xyz-inc.com:9092 (id: -6 rack: null
Mar 18 05:56:12 nlpstream-1-001.live.bi2.las1.xyz-inc.com maxwell_1[10802]: 05:56:12,804 DEBUG Selector - Created socket with SO_RCVBUF = 32768, SO_SNDBUF = 131071, SO_TIMEOUT = 0 to node -6
Mar 18 05:56:12 nlpstream-1-001.live.bi2.las1.xyz-inc.com maxwell_1[10802]: 05:56:12,804 DEBUG NetworkClient - Completed connection to node -6. Fetching API versions.
Mar 18 05:56:12 nlpstream-1-001.live.bi2.las1.xyz-inc.com maxwell_1[10802]: 05:56:12,804 DEBUG NetworkClient - Initiating API versions fetch from node -6.
Mar 18 05:56:12 nlpstream-1-001.live.bi2.las1.xyz-inc.com maxwell_1[10802]: 05:56:12,804 DEBUG NetworkClient - Initialize connection to node prodkafka-1-014.live.bi2.las1.xyz-inc.com:9092 (id: -14 rack: nul
Mar 18 05:56:12 nlpstream-1-001.live.bi2.las1.xyz-inc.com maxwell_1[10802]: 05:56:12,804 DEBUG NetworkClient - Initiating connection to node prodkafka-1-014.live.bi2.las1.xyz-inc.com:9092 (id: -14 rack: nul
Mar 18 05:56:12 nlpstream-1-001.live.bi2.las1.xyz-inc.com maxwell_1[10802]: 05:56:12,805 DEBUG Selector - Connection with prodkafka-1-018.live.bi2.las1.xyz-inc.com/10.24.105.145 disconnected
Mar 18 05:56:12 nlpstream-1-001.live.bi2.las1.xyz-inc.com maxwell_1[10802]: java.io.EOFException: null
Mar 18 05:56:12 nlpstream-1-001.live.bi2.las1.xyz-inc.com maxwell_1[10802]: at org.apache.kafka.common.network.NetworkReceive.readFromReadableChannel(NetworkReceive.java:87) ~[maxwell-1.13.2-jar-with-depen
Mar 18 05:56:12 nlpstream-1-001.live.bi2.las1.xyz-inc.com maxwell_1[10802]: at org.apache.kafka.common.network.NetworkReceive.readFrom(NetworkReceive.java:75) ~[maxwell-1.13.2-jar-with-dependencies.jar:?]
Mar 18 05:56:12 nlpstream-1-001.live.bi2.las1.xyz-inc.com maxwell_1[10802]: at org.apache.kafka.common.network.KafkaChannel.receive(KafkaChannel.java:203) ~[maxwell-1.13.2-jar-with-dependencies.jar:?]
Mar 18 05:56:12 nlpstream-1-001.live.bi2.las1.xyz-inc.com maxwell_1[10802]: at org.apache.kafka.common.network.KafkaChannel.read(KafkaChannel.java:167) ~[maxwell-1.13.2-jar-with-dependencies.jar:?]
Mar 18 05:56:12 nlpstream-1-001.live.bi2.las1.xyz-inc.com maxwell_1[10802]: at org.apache.kafka.common.network.Selector.pollSelectionKeys(Selector.java:381) [maxwell-1.13.2-jar-with-dependencies.jar:?]
Mar 18 05:56:12 nlpstream-1-001.live.bi2.las1.xyz-inc.com maxwell_1[10802]: at org.apache.kafka.common.network.Selector.poll(Selector.java:326) [maxwell-1.13.2-jar-with-dependencies.jar:?]
Mar 18 05:56:12 nlpstream-1-001.live.bi2.las1.xyz-inc.com maxwell_1[10802]: at org.apache.kafka.clients.NetworkClient.poll(NetworkClient.java:433) [maxwell-1.13.2-jar-with-dependencies.jar:?]
Mar 18 05:56:12 nlpstream-1-001.live.bi2.las1.xyz-inc.com maxwell_1[10802]: at org.apache.kafka.clients.producer.internals.Sender.run(Sender.java:224) [maxwell-1.13.2-jar-with-dependencies.jar:?]
Mar 18 05:56:12 nlpstream-1-001.live.bi2.las1.xyz-inc.com maxwell_1[10802]: at org.apache.kafka.clients.producer.internals.Sender.run(Sender.java:162) [maxwell-1.13.2-jar-with-dependencies.jar:?]
Mar 18 05:56:12 nlpstream-1-001.live.bi2.las1.xyz-inc.com maxwell_1[10802]: at java.lang.Thread.run(Thread.java:745) [?:1.8.0_45]
Mar 18 05:56:12 nlpstream-1-001.live.bi2.las1.xyz-inc.com maxwell_1[10802]: 05:56:12,805 DEBUG NetworkClient - Node -18 disconnected.
Mar 18 05:56:12 nlpstream-1-001.live.bi2.las1.xyz-inc.com maxwell_1[10802]: 05:56:12,805 DEBUG Selector - Connection with prodkafka-1-006.live.bi2.las1.xyz-inc.com/10.24.81.146 disconnected

**Comment by ravikiranks** [comment]
Note - stream is working ok with 1.10.1 version , though fails sometimes with 'open replicator'.
we want to upgrade to a new version and hence need this to work with 0.8.2.1 kafka cluster for a while!!

**Comment by ravikiranks** [comment]
Also added config explicitly,
ssl-DISABLED

but still see some ssl related configs in the debug's 

Mar 18 03:56:06 nlpstream-1-001.live.bi2.las1.mz-inc.com maxwell_1[21755]: 03:56:06,435 INFO  ProducerConfig - ProducerConfig values:
Mar 18 03:56:06 nlpstream-1-001.live.bi2.las1.mz-inc.com maxwell_1[21755]: acks = 1
Mar 18 03:56:06 nlpstream-1-001.live.bi2.las1.mz-inc.com maxwell_1[21755]: batch.size = 16384
Mar 18 03:56:06 nlpstream-1-001.live.bi2.las1.mz-inc.com maxwell_1[21755]: bootstrap.servers = [xyz:9092]
Mar 18 03:56:06 nlpstream-1-001.live.bi2.las1.mz-inc.com maxwell_1[21755]: buffer.memory = 33554432
Mar 18 03:56:06 nlpstream-1-001.live.bi2.las1.mz-inc.com maxwell_1[21755]: client.id =
Mar 18 03:56:06 nlpstream-1-001.live.bi2.las1.mz-inc.com maxwell_1[21755]: compression.type = none
Mar 18 03:56:06 nlpstream-1-001.live.bi2.las1.mz-inc.com maxwell_1[21755]: connections.max.idle.ms = 540000
Mar 18 03:56:06 nlpstream-1-001.live.bi2.las1.mz-inc.com maxwell_1[21755]: enable.idempotence = false
Mar 18 03:56:06 nlpstream-1-001.live.bi2.las1.mz-inc.com maxwell_1[21755]: interceptor.classes = null
Mar 18 03:56:06 nlpstream-1-001.live.bi2.las1.mz-inc.com maxwell_1[21755]: key.serializer = class org.apache.kafka.common.serialization.StringSerializer
Mar 18 03:56:06 nlpstream-1-001.live.bi2.las1.mz-inc.com maxwell_1[21755]: linger.ms = 0
Mar 18 03:56:06 nlpstream-1-001.live.bi2.las1.mz-inc.com maxwell_1[21755]: max.block.ms = 60000
Mar 18 03:56:06 nlpstream-1-001.live.bi2.las1.mz-inc.com maxwell_1[21755]: max.in.flight.requests.per.connection = 5
Mar 18 03:56:06 nlpstream-1-001.live.bi2.las1.mz-inc.com maxwell_1[21755]: max.request.size = 1048576
Mar 18 03:56:06 nlpstream-1-001.live.bi2.las1.mz-inc.com maxwell_1[21755]: metadata.max.age.ms = 300000
Mar 18 03:56:06 nlpstream-1-001.live.bi2.las1.mz-inc.com maxwell_1[21755]: metric.reporters = []
Mar 18 03:56:06 nlpstream-1-001.live.bi2.las1.mz-inc.com maxwell_1[21755]: metrics.num.samples = 2
Mar 18 03:56:06 nlpstream-1-001.live.bi2.las1.mz-inc.com maxwell_1[21755]: metrics.recording.level = INFO
Mar 18 03:56:06 nlpstream-1-001.live.bi2.las1.mz-inc.com maxwell_1[21755]: metrics.sample.window.ms = 30000
Mar 18 03:56:06 nlpstream-1-001.live.bi2.las1.mz-inc.com maxwell_1[21755]: partitioner.class = class org.apache.kafka.clients.producer.internals.DefaultPartitioner
Mar 18 03:56:06 nlpstream-1-001.live.bi2.las1.mz-inc.com maxwell_1[21755]: receive.buffer.bytes = 32768
Mar 18 03:56:06 nlpstream-1-001.live.bi2.las1.mz-inc.com maxwell_1[21755]: reconnect.backoff.max.ms = 1000
Mar 18 03:56:06 nlpstream-1-001.live.bi2.las1.mz-inc.com maxwell_1[21755]: reconnect.backoff.ms = 50
Mar 18 03:56:06 nlpstream-1-001.live.bi2.las1.mz-inc.com maxwell_1[21755]: request.timeout.ms = 30000
Mar 18 03:56:06 nlpstream-1-001.live.bi2.las1.mz-inc.com maxwell_1[21755]: retries = 0
Mar 18 03:56:06 nlpstream-1-001.live.bi2.las1.mz-inc.com maxwell_1[21755]: retry.backoff.ms = 100
Mar 18 03:56:06 nlpstream-1-001.live.bi2.las1.mz-inc.com maxwell_1[21755]: sasl.jaas.config = null
Mar 18 03:56:06 nlpstream-1-001.live.bi2.las1.mz-inc.com maxwell_1[21755]: sasl.kerberos.kinit.cmd = /usr/bin/kinit
Mar 18 03:56:06 nlpstream-1-001.live.bi2.las1.mz-inc.com maxwell_1[21755]: sasl.kerberos.min.time.before.relogin = 60000
Mar 18 03:56:06 nlpstream-1-001.live.bi2.las1.mz-inc.com maxwell_1[21755]: sasl.kerberos.service.name = null
Mar 18 03:56:06 nlpstream-1-001.live.bi2.las1.mz-inc.com maxwell_1[21755]: sasl.kerberos.ticket.renew.jitter = 0.05
Mar 18 03:56:06 nlpstream-1-001.live.bi2.las1.mz-inc.com maxwell_1[21755]: sasl.kerberos.ticket.renew.window.factor = 0.8
Mar 18 03:56:06 nlpstream-1-001.live.bi2.las1.mz-inc.com maxwell_1[21755]: sasl.mechanism = GSSAPI
Mar 18 03:56:06 nlpstream-1-001.live.bi2.las1.mz-inc.com maxwell_1[21755]: security.protocol = PLAINTEXT
Mar 18 03:56:06 nlpstream-1-001.live.bi2.las1.mz-inc.com maxwell_1[21755]: send.buffer.bytes = 131072
Mar 18 03:56:06 nlpstream-1-001.live.bi2.las1.mz-inc.com maxwell_1[21755]: ssl.cipher.suites = null
Mar 18 03:56:06 nlpstream-1-001.live.bi2.las1.mz-inc.com maxwell_1[21755]: ssl.enabled.protocols = [TLSv1.2, TLSv1.1, TLSv1]

**Comment by osheroff** [comment]
how are you deploying / invoking maxwell?

**Comment by ravikiranks** [comment]
did the git clone , added below maven tag to build a jar 'with dependencies' and ran with my previous script 'maxwell' in my bin directory , referring to a config file as shown below!

      <plugin>
        <artifactId>maven-assembly-plugin</artifactId>
        <configuration>
          <descriptorRefs>
            <descriptorRef>jar-with-dependencies</descriptorRef>
          </descriptorRefs>
        </configuration>
        <executions>
          <execution>
            <id>make-assembly</id>
            <phase>package</phase>
            <goals>
              <goal>single</goal>
            </goals>
          </execution>
        </executions>
      </plugin>

config file --
=======
# general
log_level=debug
client_id=m_stream

# kafka
producer=kafka
kafka_version=0.8.2.2
metrics_type=jmx
ssl=DISABLED

binlog_connector=true
replication_ssl=DISABLED
kafka.bootstrap.servers=xyz:9092
producer_partition_by=primary_key
kafka_topic=batch_email

# metrics

# mysql
host=maindb-1-004.live.ody1.las1.xyz-inc.com
user=maxwell
password=12356!
schema_database=maxwell

# dbs, tables
include_dbs=live_main

include_tables=batch_email

**Comment by osheroff** [comment]
ok, if you want to do a fat-jar approach, you'll need to go about it a bit differently; in a normal tarball deployment the included `bin/maxwell` will switch between different kafka libraries (in order to avoid having to load them from the JVM at runtime).  I think if you build your jar with `-P kafka-0.8.2.2` it should pull in the correct version of kafka, but I haven't tried it.  LMK how that works.

**Comment by osheroff** [comment]
closing this issue, LMK if you need more.
