### ISSUE TITLE
buffer producer  graceful shutdown 

### ISSUE THREAD

**Issue by dfadid** [zendesk/maxwell#924]
hey,
im using maxwell with the Buffer producer integrated in  my app and when im shutting down the up/ deploying a new version i would like to have the ability to terminate the process gracefully , means that i will be able to stop pushing new RowMap to the LinkedBlockingQueue and empty the the list and only after that , terminate the app all together.

is there a way to do it ? (im using version 1.13.0)

thanks

**Comment by osheroff** [comment]
maxwell itself will see shutdown starting and stop pushing rows through the producer.  Your code's responsibility would be to drain the queue on shutdown - you can look into adding a shutdown hook via `Runtime.getRuntime().addShutdownHook` that empties out the buffered producer's queue.

LMK how this works out for you.

**Comment by dfadid** [comment]
ok i think i got it.
what is the best way to signal maxwell buffer producer to shutdown? currently im just calling ,
`BufferedMaxwell.terminate()` 

thanks

**Comment by osheroff** [comment]
that's fine.  after you call `Maxwell#terminate` you can safely drain the buffer.

**Comment by osheroff** [comment]
welcome.
