### ISSUE TITLE
ts in milliseconds

### ISSUE THREAD

**Issue by robertelsinki** [zendesk/maxwell#925]
Hi,

is it possible to configure maxwell to produce ts in milliseconds e.g. "ts": 1449786310123

The reason is our data consolidator program needs to compare data change to millisecond precision from any source, one of it is from mysql database.

Sorry if i have incorrect understanding

**Comment by osheroff** [comment]
unfortunately `ts` comes from the mysql binlog which only contains a 32bit timestamp (second resolution).  options to get milliseconds:

- embed a millisecond-precise date field in the data, ala
` create table test.f2 ( a int, d timestamp(5) default current_timestamp(5) )`
- write a custom producer that adds "fake" millisecond precision to the row (maybe the time at which the producer output the row?)

**Comment by robertelsinki** [comment]
got it, thanks!
