### ISSUE TITLE
Does maxwell support creating index/stored procedure? 

### ISSUE THREAD

**Issue by leonjoyce** [zendesk/maxwell#930]
If no, why? 
Thanks!

**Comment by osheroff** [comment]
It will handle it, but will not output anything in the DDL stream - it doesn’t affect maxwells view of the schema so it just ignores the statements.

**Comment by leonjoyce** [comment]
@osheroff  In some scenario such as myql-to-mysql database synchronization,  when source mysql creates an index/stored procedure, we need do the same to the target site. 
Better to create a switch in properties file of maxwell,  indicating whether to output  index/stored procedure action to the producer.
Do you agree to make this as a PR?
