### ISSUE TITLE
Support environment variable based configurations

### ISSUE THREAD

**Issue by ericwush** [zendesk/maxwell#935]
/cc @zendesk/goanna 

We'd like to bring this up and seek feedback especially from @osheroff regarding supporting environment variable based configurations.

Currently Maxwell supports configurations to be loaded from command line arguments or properties file. In our case, we've got heaps of Kafka configs which are not currently supported and extendable when command line arguments approach is used. Automating the process to compose the properties file is always an option but it could be simplified if Maxwell supports environment variable based configurations, e.g. with a prefix `MAXWELL_`. This could be useful in containers too.

Any thoughts/concerns?

**Comment by osheroff** [comment]
Is there much precedent for this?  I guess some gnu utils allow *some* env based config, I've never heard of a program that can fully configure itself via env.  In theory I don't mind the idea, definitely fits with the way the world is heading wrt containers and such. 

wondering if there's any security risks?  someone upstream injects variables into your env and you don't realize it?  `sudo` seems very concerned about that sort of thing, I'm not sure if we'd need to be.....

**Comment by ericwush** [comment]
@osheroff 

> definitely fits with the way the world is heading wrt containers and such
Exactly. In our case, some configs come from env vars directly, like _mysql_host_, _kafka_host_. The others might be externalised to env vars for easy configuration, like kafka related settings. Rather than env vars -> config file -> maxwell, we think env vars -> maxwell directly should make life easier.

> someone upstream injects variables into your env and you don't realize it?
That was my initial concern, but the prefix should minimise the chance of it. Also the prefix should be configurable too.

I can probably start with a PR and see how it tastes.
