### ISSUE TITLE
alway got the same  position: mysqlbin-log.000001:5783

### ISSUE THREAD

**Issue by kiddyt00** [zendesk/maxwell#940]

**Comment by kiddyt00** [comment]
I flush the mysql bin_log once and then whaterver I try always got the mysqlbin-log.000001:5783,so hao to slove  this problem

**Comment by kiddyt00** [comment]
on v1.13.3, "winner winner chicken dinner" this version

**Comment by osheroff** [comment]
I presume that you removed the binlog that maxwell was pointing to.  `drop database maxwell` will solve this.

**Comment by kiddyt00** [comment]
@osheroff ,thanks a lot ,your plan just match my problem
