### ISSUE TITLE
A slave with the same server_uuid/server_id

### ISSUE THREAD

**Issue by kiddyt00** [zendesk/maxwell#942]
when I start more than one instance of maxwell with different config file ,each istance connect to the same server and the same bin-log but different database,then it happens A slave with the same server_uuid/server_id

so how to slove this problem

**Comment by osheroff** [comment]
give each instance a different (unique) setting for `replica_server_id`. (as well as a different `client_id`)

**Comment by kiddyt00** [comment]
@osheroff it works，thanks a lot

**Comment by fanfanfufu** [comment]
> give each instance a different (unique) setting for `replica_server_id`. (as well as a different `client_id`)

Can you give a detailed example
