### ISSUE TITLE
Read from multiple binary logs

### ISSUE THREAD

**Issue by maheshnayer** [zendesk/maxwell#946]
Hi. I've just started using maxwell and have been experimenting with it. If I have multiple binary logs mentioned in my binary log index file, it appears maxwell detects only the first one in the index list. Changing the order would result in maxwell, throwing the error, "Could not find first log file name in binary log index file" which is because of the file name and position set in the positions table.
So, is there a way for maxwell to read from all the binary logs present in the binary log index file?
Also is it possible for maxwell to read from slave relay log (multiple logs as well)?

Thank you

**Comment by osheroff** [comment]
If it understand your question correctly, you want maxwell to play from the earliest binlog your server has?

This is possible with —init_position, but *only* if the schema hasn’t changed.

**Comment by maheshnayer** [comment]
Understood. Thank you
Also is it possible for maxwell to read from slave relay logs?

**Comment by osheroff** [comment]
@maheshnayer yes, it's possible to read from the slave.  maxwell still needs access to a mysql server to stash the schema in, but see the `--replication_*` series of options to read from the slave.
