### ISSUE TITLE
Is there a Memory leak ?

### ISSUE THREAD

**Issue by jimymodi** [zendesk/maxwell#947]
We are running 4 instances of maxwell, 2 points to the same db and 2 pointing to other respective dbs. 
We are experiencing a gradual increase in memory consumption. While when we restart all 4 instances we see a huge drop in memory consumption. But again it gradually increase. The workload would be 300 messages/s from all 4 instances.
Graph of memory consumption for last 24 hours
![mem_leak_maxwell](https://user-images.githubusercontent.com/415224/39093627-1ddac716-4640-11e8-861e-d1f2f0a78bf6.png)

Is this a normal behaviour or I had missed some important configuration.

Maxwell version : 1.13.3
Kafka version : 1.0 from CP-4.0.0

**Comment by ericwush** [comment]
@jimymodi do you define Xmx for the JVMs? I feel 1.5-2G is probably still more than what Maxwell would require. Bigger heap size will lead to less frequent GC but longer pause time. That's probably what the diagram indicates.

**Comment by jimymodi** [comment]
@ericwush Nope I haven't define any `Xmx` for the JVMs. I didn't get your comment on "Bigger heap size will lead to less frequent GC but longer pause time". Can you please explain.

**Comment by osheroff** [comment]
Also it’s often worth trying the G1 collector if not already in use.  

Also, what producer?  I have a vague memory of the Kafka producer library intentionally “leaking” memory in the form of retained buffers,  but I might be imagining it.

**Comment by jimymodi** [comment]
@ericwush Got your point, thanks for the explaination. But in my case, I don't see the GC problem here. Because the memory is never coming down. 

@osheroff How to check if we are on G1 collector (ps: Haven't changed any defaults) ?
We are using Kafka producer. Can you provide more info on retained buffers problem. Also any pointers for debugging is appreciated.

**Comment by ericwush** [comment]
I had a closer look at the diagram you included, it shows the system memory usage which cannot be used to simply determine whether there is a memory leak. You should use JVM memory usage. I believe once the memory for the JVM heap is allocated, OS won't immediately reclaim it even if it's not fully used. Whereas JVM heap usage shows a clearer picture that how much memory is used before/after GCs. 

Memory usage increased in your diagram because you didn't set `Xmx`. If set, once it reaches the `Xmx` size, you would see a flat line instead. And in most cases if there is a memory leak, the process will eventually crash due to OOM. Setting a relatively small `Xmx` will surface it quicker.

**Comment by osheroff** [comment]
add `-verbose:gc` to the JVM flags to see what the GC is doing.

@ericwush brings up good points too.  Running `java -XX:+PrintFlagsFinal -version | grep MaxHeapSize` will show you the current max heap size, and you can *generally* expect that your JVMs will grow towards that limit. 

Would also to be curious as to whether the memory usage stabilizes over a longer period of time: I'd expect it would.

**Comment by jimymodi** [comment]
@ericwush Currently we have not enabled JVM metrics. Will do that and share the findings there. Would also try setting a `Xmx` after I have JVM metrics to see at.

@osheroff  The MaxHeapSize is `2G`. So is the MaxHeapSize is max for all the java process collectively or individually. I mean does maxheapsize is applied to the sum of memory of all java process ?
Will update about the stabilisation of the memory utilisation over a longer period.

**Comment by osheroff** [comment]
Max heap is per jvm.  Advise you limit to 1gb per maxwell instance.

**Comment by osheroff** [comment]
No evidence of a leak here, closing the issue.
