### ISSUE TITLE
Can maxwell do bootstrapping with specific maxwell client id?

### ISSUE THREAD

**Issue by tanapoln** [zendesk/maxwell#948]
I just wonder that if I run multiple instances of Maxwell with a single master and I want to do bootstrapping data, how can I specify which client id to do that so that other Maxwell instances would just do their job and subscribes would not have to process rows.

If it's not possible at this time, is there an alternative way to achieve that behavior?

Thank you.

**Comment by osheroff** [comment]
this is not currently possible, but clearly needed.

**Comment by osheroff** [comment]
this is possible in 1.14.1
