### ISSUE TITLE
NullPointerException in SchemaCapturer 

### ISSUE THREAD

**Issue by BradyPT** [zendesk/maxwell#950]
```
12:26:09,054 DEBUG MysqlSavedSchema - 12/116 Capturing DOC_goals...
java.lang.NullPointerException
    at com.zendesk.maxwell.schema.SchemaCapturer.captureTablesPK(SchemaCapturer.java:214)
    at com.zendesk.maxwell.schema.SchemaCapturer.captureTables(SchemaCapturer.java:196)
    at com.zendesk.maxwell.schema.SchemaCapturer.captureDatabase(SchemaCapturer.java:140)
    at com.zendesk.maxwell.schema.SchemaCapturer.capture(SchemaCapturer.java:111)
    at com.zendesk.maxwell.schema.AbstractSchemaStore.captureSchema(AbstractSchemaStore.java:44)
    at com.zendesk.maxwell.schema.MysqlSchemaStore.restoreOrCaptureSchema(MysqlSchemaStore.java:68)
    at com.zendesk.maxwell.schema.MysqlSchemaStore.getSchema(MysqlSchemaStore.java:58)
    at com.zendesk.maxwell.Maxwell.start(Maxwell.java:169)
    at com.zendesk.maxwell.Maxwell.main(Maxwell.java:203)
```

I think it's possible we're experiencing a race condition between the captureTables query and captureTablesPK query, it ran fine for the longest time before. This is the line that fails:

table.setPKList(l.get(key));

**Comment by osheroff** [comment]
ping, can you reproduce this issue @BradyPT?

**Comment by BradyPT** [comment]
Not reliably, we're not entirely sure what's going on either that's just our best guess, but it's happened multiple times. It's either the table.setPKList or the l.get, but I'm having trouble finding out how that's possible as well.

**Comment by osheroff** [comment]
What version are you running?  Possible mismatch between the stack-trace and the code we're looking at? 

doing `l.get(null)` wouldn't throw an NPE, `l` is clearly not null, and I can't see a case where `tables` would contain a null value either.

**Comment by BradyPT** [comment]
1.8.1, but the schemacapturer hasn't been updated since. I'll look at updating if you think that'll fix it.

**Comment by osheroff** [comment]
your stack traces don't line up to either 1.8.1 or HEAD.  have you thrown debug logging in there?  In v1.8.1 the call to `captureTablesPK` should have been on line 189, but your stack trace has it on 196.  

Additionally, the line that you suspect is throwing, `table.setPKList`, is on line 215 in 1.8.1.

**Comment by osheroff** [comment]
argh, ok.  please remember in the future that if you have patches in place your stack traces will be wrong.  With that patch in place on v1.8.1, the line that is throwing is this:

https://github.com/zendesk/maxwell/blob/v1.8.1/src/main/java/com/zendesk/maxwell/schema/SchemaCapturer.java#L207

Which could certainly be a race condition if a new table is added while we are capturing the rest of the tables.  There's a bunch of band-aids one could apply here.  The easiest would be to lock everything under the sun, but I feel that that is gonna be a non-starter for most people.  How long does maxwell take to capture your entire schema?

**Comment by osheroff** [comment]
fixed in the latest release.
