### ISSUE TITLE
Error: Could not find or load main class com.zendesk.maxwell.bootstrap.MaxwellBootstrapUtility

### ISSUE THREAD

**Issue by psynet34** [zendesk/maxwell#953]
Maxwell runs fine, maxwell bootstrap
`Error: Could not find or load main class com.zendesk.maxwell.bootstrap.MaxwellBootstrapUtility`

openjdk 1.8.0

ideas?

**Comment by osheroff** [comment]
Is this in the latest maxwell?  What version?

**Comment by osheroff** [comment]
if this is in a development env (not a release) I put in some fixes for that in #951

**Comment by osheroff** [comment]
should be fixed (if this is a dev problem) in master
