### ISSUE TITLE
bootstrapping for one clientid (say clientid_1 ) - dumps data into other clientid (clientid_2)

### ISSUE THREAD

**Issue by ravikrovvidi** [zendesk/maxwell#954]
observation - bootstrap table doesn't have a client id to distinguish for which client id stream we are doing bootstrap. believe this is the core reason, pls correct me if I am wrong!

**Comment by osheroff** [comment]
no you're correct.  This is a dupe of #948 which we are working on for the next release.

**Comment by ravikrovvidi** [comment]
can we expect this feature in the version after 1.14.0? do we have code for this in master branch for testing?

**Comment by osheroff** [comment]
yeah it should be in the next release.  it hasn't landed in master yet, still in PR here https://github.com/zendesk/maxwell/pull/951 as I need to fixup the test suite
