### ISSUE TITLE
partition by xid possible?

### ISSUE THREAD

**Issue by murri71** [zendesk/maxwell#956]
Hello, just had a though...to maintain order of statements in a transaction in a kafka topic - such as inserts in both a parent and child table - i see that having only one partition would accomplish that...but would it not be great to group all maxwell messages by the mysql xid so that we could partition?

For example, this maxwell message:
`{
    "ROWTIME": 1524847219349,
    "ROWKEY": "{\"database\":\"sacarino_es\",\"table\":\"orders\",\"pk.order_pk\":204637530}",
    "database": "sacarino_es",
    "table": "orders",
    "type": "update",
    "ts": 1524847219,
    "xid": 583640888,
    "commit": true,
    "data": {
        "order_PK": 204637530,
        "order_created": "2018-04-27 10:57:50",
        "order_modified": "2018-04-27 16:40:19",
        "order_fraud": "0",
        "order_FK_member_PK": 43114720,
        "order_FK_status_PK": 26,
        "order_items": 1.0,
        "order_taxable": "1",
        "order_amount": 16.94,
        "order_billingName": null,
        "order_billingVatNumber": null,
        "order_iso_country": null,
        "order_last_billed": "2018-04-27 10:57:51",
        "order_FK_bill_PK": 242370280,
        "order_FK_carrier_PK": 90,
        "order_token": "10923679-49f9-11e8-844d-1402ec7b4175",
        "order_billingDir": null,
        "order_billingZipcode": null,
        "order_billingCity": null,
        "order_source": "mobile",
        "order_type": "S",
        "order_FK_mcorder_PK": null,
        "order_fraud_detection": null,
        "order_mirakl_id": null,
        "order_isBlocked": 0
    },
    "old": {
        "order_modified": "2018-04-27 10:35:09",
        "order_FK_status_PK": 22
    }
}`

This is partitioned by table PK, as defined in the producer props.  Would it be possible to partition by the json-insh path of ROWKEY to have the xid instead?

**Comment by liulikun** [comment]
It's not supported currently, but it's possible, just need a PR :-)

**Comment by osheroff** [comment]
so the effects of this would be that we'd basically be partitioning by transaction, but then transactions would appear on a random topic.  I *guess* there could be a use case for this, but you'd lose any guarantee about ordering between different transactions.  

If that's what you want, yeah, ok, open a PR.... :)

**Comment by osheroff** [comment]
someone wrote this feature at some point.
