### ISSUE TITLE
define databases & tables to specific topics

### ISSUE THREAD

**Issue by PsySkeletor** [zendesk/maxwell#957]
I dont know if this possible or not, but now there are two options:

1. All DBs to one topic
2. nDB & Tables to nTopics

Could be possible to manually specific which Dbs + Tables should been pushed to choosen topics?
ie.

included_dbs=db_1, db_2
included_tables=table1,table2

kafka-topics=db_1-table-1, db_2-table-2

Thanks!

**Comment by liulikun** [comment]
One way to achieve this fine controlled topics is to use a custom producer factory as in PR: https://github.com/zendesk/maxwell/pull/836.

**Comment by psynet34** [comment]
oh thanks! i will take a look and come back to you 👍

**Comment by osheroff** [comment]
this should also be possible now with javascript filters, they allow flexible kafka-topic routing.
