### ISSUE TITLE
how to resynchronize 

### ISSUE THREAD

**Issue by zj4775** [zendesk/maxwell#964]
If I didn't have synchronous table A at first, but then I wanted to synchronize table A, how can I resynchronize the database?

**Comment by zj4775** [comment]
i want to synchronize mysqlbinlog to elasticsearch,my way is mysqlbinlog->maxwell->kafka->logstach->elasticsearch. my question is:  I had no synchronize table 'order' one month ago ,but now i want to synchronize it, i add it include_tables in config.properties file,but maxwell  can only synchronize data from now ,i insert a new record in table 'order' ,this record can synchronize to es,but How do I synchronize the data of a month ago

**Comment by osheroff** [comment]
look into bootstrapping the table:

http://maxwells-daemon.io/bootstrapping/
