### ISSUE TITLE
*Question*: Can we exclude or include the databases while pushing the CDC information into Kafka?

### ISSUE THREAD

**Issue by frndtech** [zendesk/maxwell#965]
First and foremost, appreciate all the efforts towards a great tool. We have a MySQL server where we have more than 20+ databases. we would like to capture CDC data only for 5 databases. Will it possible to configure the databases in inclusion/exclusion list?

Thanks in advance!!

Anji.

**Comment by osheroff** [comment]
http://maxwells-daemon.io/config/#filters

**Comment by frndtech** [comment]
Thanks a lot. Somehow I missed it.
