### ISSUE TITLE
Missing thread Id in Maxwell Kafka event

### ISSUE THREAD

**Issue by abhiverma23** [zendesk/maxwell#967]
Hello,

In the event generated by Maxwell to Kafka does not contain `threadId`. I referred [this blog from medium.com](https://medium.com/myheritage-engineering/achieving-real-time-analytics-via-change-data-capture-d69ed2ead889).

I am trying to achieve same results as mentioned in that blog and I am getting event as
```
{
  "database": "DBName",
  "table": "TableName",
  "type": "update",
  "ts": 1525704454,
  "xid": 95466951,
  "data": {...},
  "old": {...}
}
```

But in the above event `threadId` is missing.

How to get `threadId` as part of event?

**Comment by liulikun** [comment]
You can configure it: http://maxwells-daemon.io/config/

**Comment by osheroff** [comment]
see `--output_thread_id`
