### ISSUE TITLE
How can I Filter according to databasename+tablename?

### ISSUE THREAD

**Issue by weiboyiyou** [zendesk/maxwell#972]
Hi ,
   How can I Filter according to databasename+tablename? now only can filter according to databasename or  tablename.

**Comment by liulikun** [comment]
Check the config doc if it helps: http://maxwells-daemon.io/config/#includeexclude

Basically, you can do:

> So an example like --include_dbs=/foo.*/ --exclude_tables=bar will include footy.zab and exclude footy.bar

**Comment by weiboyiyou** [comment]
@liulikun hi, like this  ,have database  a ,b  ,in database a has table a1,a2,a3,in  database b has table a1,b1,b2,b3,  i want  a,b databae except  table  a1 of b database .so you method  can't fit my need.

**Comment by liulikun** [comment]
yeah, that's a bit tricky. Is it possible to rename table a1 in b? Otherwise you can take a look at a custom producer: https://github.com/zendesk/maxwell/pull/836, then you can fully customise the filtering logic.

**Comment by osheroff** [comment]
this is a feature that we should support.  I've wanted for some time now to boil the command line filtering options down to:

```
   include=db.table
   include=*.table
   include=db.*
   exclude=db.table
```
etc

**Comment by weiboyiyou** [comment]
@osheroff   Is this feature   supported now?

**Comment by osheroff** [comment]
@weiboyiyou no it's in the pipeline.

**Comment by osheroff** [comment]
v1.16.0 now supports this feature.
