### ISSUE TITLE
Maxwell down when mysql database crash 

### ISSUE THREAD

**Issue by dula24** [zendesk/maxwell#973]
Hi, 

1. We have 5 maxwell instances which pointing to mysql slave db. when mysql instance crash all the maxwell instances get down. 
2. Each maxwell instance filter seperate tables. There are some maxwell.position records which pointing to old binlog files which not exists. When try to restart those instances it's giving error. Why if there are no records from filtering table binlog position not update in maxwell.position table ?

**Comment by osheroff** [comment]
there was a bug in older versions that would trigger this behavior.  Please upgrade to v1.14.2 or later.

**Comment by dula24** [comment]
Still when mysql instance crash all the maxwell instances get shutdown.
