### ISSUE TITLE
Bootstraping using the maxwell.bootstrap table does not work

### ISSUE THREAD

**Issue by pasali** [zendesk/maxwell#987]
I am using version`v1.14.6`. When i try to bootstrap a table its always return 0 inserted rows.

**Comment by osheroff** [comment]
be more specific, please.  how is maxwell setup?  are there log messages that are relevant?  how are you inserting into maxwell.bootstrap (or are you using the utility?)

**Comment by pasali** [comment]
I am inserting like this:
`INSERT INTO maxwell.bootstrap (database_name, TABLE_NAME) VALUES ('foo', 'bar');`

Same setup work with `v1.13.0`  and there is no log messages at all.

**Comment by pasali** [comment]
@osheroff i found the problem. There is a client_id check in bootstrap java code. So correct sql should be like this:

`INSERT INTO maxwell.bootstrap (database_name, TABLE_NAME, client_id) VALUES ('foo', 'bar', 'dev');
`
